force-icon/main/default/objects/GiftCatalog__c/GiftCatalog__c.object-meta.xml
<CustomObject>
    <description>List of all products that can offered as gift to the clients. Managed by PCR team</description>
    <label>Gift Catalog</label>
    <nameField>
        <label>Gift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gifts Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-icon/main/default/objects/GiftCatalog__c/fields/GiftImageURL__c.field-meta.xml
<CustomField>
    <fullName>GiftImageURL__c</fullName>
    <description>Url of the product Gift Image</description>
    <label>Gift Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-icon/main/default/objects/GiftCatalog__c/fields/SKUGift__c.field-meta.xml
<CustomField>
    <fullName>SKUGift__c</fullName>
    <description>SKU of the gift</description>
    <externalId>true</externalId>
    <label>SKU Gift</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-icon/main/default/classes/GiftCatalogTriggerHandler.cls
public with sharing class GiftCatalogTriggerHandler {
    public static final String baseDefaultImageUrl = 'https://www.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louisvuitton--';

    public static void handleTrigger(List<GiftCatalog__c> newList, Map<Id, GiftCatalog__c> newMap, List<GiftCatalog__c> oldList, Map<Id, GiftCatalog__c> oldMap, System.TriggerOperation triggerEvent) {
        switch on triggerEvent {
            when BEFORE_INSERT {
                handleBeforeInsert(newList);
            }
            when BEFORE_UPDATE {
                handleBeforeUpdate(newList, oldMap);
            }
            when else {
                //do nothing for AFTER_UNDELETE, BEFORE_DELETE, or BEFORE_UPDATE
            }
        }
    }

    public static void handleBeforeInsert(List<GiftCatalog__c> newList) {
        for (GiftCatalog__c c : newList) {
            if (String.isEmpty(c.GiftImageURL__c) && String.isNotEmpty(c.SKUGift__c)) {
                c.GiftImageURL__c = getImageUrlBySKU(c.SKUGift__c);
            }
        }
    }

    public static void handleBeforeUpdate(List<GiftCatalog__c> newList, Map<Id, GiftCatalog__c> oldMap) {
        for (GiftCatalog__c c : newList) {
            GiftCatalog__c oldCat = oldMap.get(c.Id);
            Boolean skuWasChanged = oldCat.SKUGift__c != c.SKUGift__c;
            Boolean urlIsEmpty = String.isEmpty(c.GiftImageURL__c);
            Boolean urlWasRemoved = urlIsEmpty && String.isNotEmpty(oldCat.GiftImageURL__c);
            Boolean urlWasNotAssigned = oldCat.GiftImageURL__c == c.GiftImageURL__c || urlWasRemoved;
            Boolean isEmptyOrDefaultUrl = urlIsEmpty || isDefaultUrl(c.GiftImageURL__c);
            
            if (urlWasNotAssigned && (
                    (skuWasChanged && isEmptyOrDefaultUrl) ||
                    (urlWasRemoved && String.isNotEmpty(c.SKUGift__c))
                )
            ) {
                c.GiftImageURL__c = getImageUrlBySKU(c.SKUGift__c);
            }
        }
    }

    private static String getImageUrlBySKU(String SKU) {
        return baseDefaultImageUrl + SKU + '_PM2_Front%20view.png';
    }

    private static Boolean isDefaultUrl(String url) {
        return url.startsWith(baseDefaultImageUrl);
    }
}