force-app/main/default/objects/TWIST_Settings__c/TWIST_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TWIST - Settings</label>
</CustomObject>

force-app/main/default/objects/TWIST_Settings__c/fields/AOB_Cert_Name__c.field-meta.xml
<CustomField>
    <fullName>AOB_Cert_Name__c</fullName>
    <label>AOB Cert Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/AOB_Client_Id__c.field-meta.xml
<CustomField>
    <fullName>AOB_Client_Id__c</fullName>
    <label>AOB Client Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/AOB_Site_URL__c.field-meta.xml
<CustomField>
    <fullName>AOB_Site_URL__c</fullName>
    <label>AOB Site URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Auth_Path__c.field-meta.xml
<CustomField>
    <fullName>Auth_Path__c</fullName>
    <label>Auth Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SFID_Utils_TEST.cls
@isTest
private class SFID_Utils_TEST {
        
    @isTest
    public static void test_getSalesforceAccessToken() {
        TWIST_Settings__c settings = TWIST_Settings__c.getInstance();
        String clientId = settings.AOB_Client_Id__c;
        String siteUrl = settings.AOB_Site_URL__c;
        String certifName = settings.AOB_Cert_Name__c;
        String authPath = settings.Auth_Path__c;
        SFID_Utils.getJWTAccessToken(Datetime.now().getTime() + 'test@test.com', clientId, siteUrl, certifName, authPath);
    }
}