force-app/main/default/objects/TWIST_Settings__c/TWIST_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TWIST - Settings</label>
</CustomObject>

force-app/main/default/objects/TWIST_Settings__c/fields/Email_Token_Chars__c.field-meta.xml
<CustomField>
    <fullName>Email_Token_Chars__c</fullName>
    <label>Email Token Chars</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Email_Token_Size__c.field-meta.xml
<CustomField>
    <fullName>Email_Token_Size__c</fullName>
    <label>Email Token Size</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Password_checked_duration__c.field-meta.xml
<CustomField>
    <fullName>Password_checked_duration__c</fullName>
    <label>Password checked duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Password_Maxlength__c.field-meta.xml
<CustomField>
    <fullName>Password_Maxlength__c</fullName>
    <label>Password Maxlength</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Pwdless_Email_Verif_Identifier_Validity__c.field-meta.xml
<CustomField>
    <fullName>Pwdless_Email_Verif_Identifier_Validity__c</fullName>
    <label>Pwdless Email Verif Identifier Validity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TwistCacheManager__c/TwistCacheManager__c.object-meta.xml
<CustomObject>
    <label>Twist Cache Manager</label>
    <nameField>
        <displayFormat>CM-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Twist Cache Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwistCacheManager__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGE_RESTRICTION</fullName>
                <label>Age restriction</label>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>CHECKED_PASSWORD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TWIST_CheckPasswordAPI_TEST.cls
@isTest
private class TWIST_CheckPasswordAPI_TEST {

    static String userEmail = 'testmatch' + StringUtils.generateRandomString(10, '0123456789') + '@test.com';

    @testSetup
    static void setup() {
        insert new TWIST_Settings__c(
            Name = 'test',
            Password_checked_duration__c = 24,
            Pwdless_Email_Verif_Identifier_Validity__c = 15,
            Password_Maxlength__c = 20,
            Email_Token_Size__c = 32,
            Email_Token_Chars__c = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz'
        );
    }
    
    @isTest
    static void test_match() {
        Identity_TestFactory.createSimpleUser('check', 'password', userEmail, '0541234567');
        Test.startTest();
        
        Map<String, Object> bodyMap = new Map<String, Object>();
        
        User userTest = [SELECT Id, Email, userName FROM User WHERE username = :userEmail LIMIT 1];
        
        System.setPassword(userTest.Id, 'check1234!');
        
        HttpResponseMock mock = new HttpResponseMock().setStatusCode(200).setBody(new Map<String,String> {
            'access_token' => '1234567891234567890qwertyuwerty'
        });
        UnitTestsHelper.setSingleHttpMock(mock);
        
        // USERNAME & PASSWORD MATCH
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'POST';
        req.requestURI = '/services/apexrest/CheckPassword';
        req.addHeader('Content-Type','application/json');
        RestContext.request = req;
        RestContext.response = res;
        
        bodyMap = new Map<String, Object>{'username' => userTest.username, 'password' => 'check1234!'};
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        
        TWIST_CheckPasswordAPI.doPost();
        System.assertEquals(200, RestContext.response.statusCode, 'Statuscode should be 200');//in the body match = true
        Test.stopTest();
    }
    
    @isTest
    static void test_match_withcache() {
        insert new TwistCacheManager__c(
            Type__c = 'CHECKED_PASSWORD',
            Key__c = userEmail,
            Value__c = String.valueOf(DateTime.now())
        );
        Identity_TestFactory.createSimpleUser('check', 'password', userEmail, '0541234567');

        Test.startTest();
        User userTest = [SELECT Id, Email, userName FROM User WHERE username = :userEmail LIMIT 1];
        
        System.setPassword(userTest.Id, 'check1234!');
        
        HttpResponseMock mock = new HttpResponseMock().setStatusCode(200).setBody(new Map<String,String> {
            'access_token' => '1234567891234567890qwertyuwerty'
        });
        UnitTestsHelper.setSingleHttpMock(mock);
        
        // USERNAME & PASSWORD MATCH
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'POST';
        req.requestURI = '/services/apexrest/CheckPassword';
        req.addHeader('Content-Type','application/json');
        RestContext.request = req;
        RestContext.response = res;
        
        Map<String, Object> bodyMap = new Map<String, Object>{'username' => userTest.username, 'password' => 'check1234!'};
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        
        TWIST_CheckPasswordAPI.doPost();
        System.assertEquals(200, RestContext.response.statusCode, 'Statuscode should be 200');//in the body match = true
        Test.stopTest();
    }
    @isTest
    static void test_not_match() {
        Identity_TestFactory.createSimpleUser('check', 'password', userEmail, '0541234567');
        
        Test.startTest();
        User userTest = [SELECT Id, Email, userName FROM User WHERE username = :userEmail LIMIT 1];
        
        HttpResponseMock mock = new HttpResponseMock().setStatusCode(400);
        UnitTestsHelper.setSingleHttpMock(mock);
        
        // USERNAME & PASSWORD MATCH
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'POST';
        req.requestURI = '/services/apexrest/CheckPassword';
        req.addHeader('Content-Type','application/json');
        RestContext.request = req;
        RestContext.response = res;
        
        Map<String, Object> bodyMap = new Map<String, Object>{'username' => userTest.username, 'password' => 'check1234!'};
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        
        TWIST_CheckPasswordAPI.doPost();
        System.assertEquals(200, RestContext.response.statusCode, 'Statuscode should be 200');//in the body match = false
        Test.stopTest();
    }

    @isTest
    static void test_error() {
        Identity_TestFactory.createSimpleUser('check', 'password', userEmail, '0541234567');

        Test.startTest();
        User userTest = [SELECT Id, Email, userName FROM User WHERE username = :userEmail LIMIT 1];
        
        // USERNAME & PASSWORD MATCH
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'POST';
        req.requestURI = '/services/apexrest/CheckPassword';
        req.addHeader('Content-Type','application/json');
        RestContext.request = req;
        RestContext.response = res;
        
        Map<String, Object> bodyMap = new Map<String, Object>{'username' => userTest.username, 'password' => 'check1234!'};
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        
        TWIST_CheckPasswordAPI.doPost();
        Test.stopTest();
    }
    
}