force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/batchAnniversaryScope__c.field-meta.xml
<CustomField>
    <fullName>batchAnniversaryScope__c</fullName>
    <label>Batch Anniversary Scope</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IC_SchedulerAnniversaryReminder.cls
global class IC_SchedulerAnniversaryReminder implements Schedulable{

    global void execute(SchedulableContext sc) {

        IC_BatchAnniversaryReminder bat = new IC_BatchAnniversaryReminder();
        Integer scope = Integer.valueOf((Decimal)ICONSettings__c.getOrgDefaults().get('batchAnniversaryScope__c'));
        ID batchprocessid = Database.executeBatch(bat,!IC_UTILS.empty(scope) ? scope : 1000);
    }
}