force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/AccLastContactTimeRange__c.field-meta.xml
<CustomField>
    <fullName>AccLastContactTimeRange__c</fullName>
    <description>Defines the time range (in days) studied to display the &quot;Contacted in last X days&quot; in ICON Mobile (+ Batch)</description>
    <label>Account Last Contact Time Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{0000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Settings__mdt/Notification_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Notification Settings</label>
    <pluralLabel>Notifications Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Task/recordTypes/CSC_Call.recordType-meta.xml
<RecordType>
    <fullName>CSC_Call</fullName>
    <active>true</active>
    <description>Record Type for call coming from CTI</description>
    <label>ICONICS Call</label>
</RecordType>

force-app/main/default/classes/IC_Task_AfterUpdate_TEST.cls
@isTest
public class IC_Task_AfterUpdate_TEST {
  
    public static Account acc; 
    public static Task tsk;
    public static Date lstContactedate;
    public static List<Account> accountList = new List<Account>();
    
    static void init(){
       
        acc = IC_TestFactory.createAccount();
        insert acc;
        tsk = IC_TestFactory.createTask(acc);
        tsk.RecordTypeId = IC_UTILS.getTaskRT();
        insert new ICONSettings__c(AccLastContactTimeRange__c=30);
        insert tsk;
        
    }
    
    static testMethod void testTrigger(){
        
        init();
        Test.startTest();
        update tsk;
        accountList = [SELECT LastContactDate__pc FROM Account WHERE Id = :acc.Id];
        //System.assertEquals(accountList.get(0).LastContactDate__pc, tsk.ActivityDate);
        Test.stopTest();
    }
    static testMethod void CreateNotification() {
        // Init data
        Id recordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('CSC_Call').getRecordTypeId();
        init();
        Task t = ICX_TestFactory.creatCallTaskOnAccount(acc.Id);
        // Test
       
        t.recordTypeId = recordTypeId;
        t.CallType = 'Inbound';
        t.ICX_Country__c='USA';
        insert t;

        Test.startTest();
        t.Resolution__c='Immediate Response';
        update t;
        Test.stopTest();       
        
        // Check
        //     
             
        List<Notification_Settings__mdt> notificationSettings = [select id,DeveloperName ,Is_Active__c from Notification_Settings__mdt where DeveloperName ='VOICE_AFTER_CALL_SURVEY'  and Is_Active__c=true];
        integer numOfNotif= 0;
        List<Notification__c> notif = [select id from notification__c];
        if(!notificationSettings.isEmpty()){
           numOfNotif= 1;
        }
        System.assertEquals(numOfNotif, notif.size());


    }
}