force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/AccLastContactTimeRange__c.field-meta.xml
<CustomField>
    <fullName>AccLastContactTimeRange__c</fullName>
    <description>Defines the time range (in days) studied to display the &quot;Contacted in last X days&quot; in ICON Mobile (+ Batch)</description>
    <label>Account Last Contact Time Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/fields/accountPurgeLimit__c.field-meta.xml
<CustomField>
    <fullName>accountPurgeLimit__c</fullName>
    <description>number of mounth to purg account</description>
    <label>accountPurgeLimit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/fields/taskPurgeMaxLimit__c.field-meta.xml
<CustomField>
    <fullName>taskPurgeMaxLimit__c</fullName>
    <description>Task purge maximum limit. for exemple One (6) Months</description>
    <label>task Purge Max Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/fields/taskPurgeMinLimit__c.field-meta.xml
<CustomField>
    <fullName>taskPurgeMinLimit__c</fullName>
    <description>Task purge minimum limit. for exemple One (1) Months</description>
    <label>task Purge Min Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IC_BatchCleanUpTask_TEST.cls
@isTest
private class IC_BatchCleanUpTask_TEST {
    
 static testMethod void testBatch() {
    
        insert new ICONSettings__c (accountPurgeLimit__c=18, taskPurgeMaxLimit__c=6, taskPurgeMinLimit__c=1, AccLastContactTimeRange__c=30);
        ID batchprocessid; 
        
        Task t1 = IC_TestFactory.createTask();
        t1.Channel__c = 'Emailing';
        t1.DREAMID__c = 'CRM_XXXX';
        t1.ActivityDate = Date.today().addMonths(-20);
        insert t1;
        
        Task t2 = IC_TestFactory.createTask();
        t2.ActionType__c = 'oki';
        t2.ActivityDate = Date.today().addMonths(-2);
        insert t2;
        
        IC_BatchCleanUpTask myBatch = new IC_BatchCleanUpTask();
        
        Test.startTest();
        batchprocessid = Database.executeBatch(myBatch,1000);
        Test.stopTest();
        
        List<Task> lst = [SELECT Id FROM Task];
        System.assertequals(lst.size(), 1);
        
    }
    
}