force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/batchBirthdayReminderScope__c.field-meta.xml
<CustomField>
    <fullName>batchBirthdayReminderScope__c</fullName>
    <label>Batch Birthday Reminder Scope</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IC_SchedulerBirthdayReminder.cls
global class IC_SchedulerBirthdayReminder implements Schedulable{

    global void execute(SchedulableContext sc) {
    	
    	Integer scope = Integer.valueOf((Decimal)ICONSettings__c.getOrgDefaults().get('batchBirthdayReminderScope__c'));
        IC_BatchBirthdayReminder bat = new  IC_BatchBirthdayReminder();
        ID batchprocessid = Database.executeBatch(bat,!IC_UTILS.empty(scope) ? scope : 1000);           
        
    }
}