force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Iso2Code__c.field-meta.xml
<CustomField>
    <fullName>Iso2Code__c</fullName>
    <label>Iso2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Iso3Code__c.field-meta.xml
<CustomField>
    <fullName>Iso3Code__c</fullName>
    <label>Iso3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/tech_duplicate__c.field-meta.xml
<CustomField>
    <fullName>tech_duplicate__c</fullName>
    <description>To avoid duplicate countries</description>
    <externalId>true</externalId>
    <label>tech_duplicate</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/CountryLanguage__c.object-meta.xml
<CustomObject>
    <label>CountryLanguage</label>
    <nameField>
        <label>CountryLanguage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountryLanguages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CountryLanguage__c/fields/ATG_Locale__c.field-meta.xml
<CustomField>
    <fullName>ATG_Locale__c</fullName>
    <label>ATG Locale</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Locales</relationshipLabel>
    <relationshipName>CountryLanguages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <referenceTo>Language2__c</referenceTo>
    <relationshipLabel>Locale</relationshipLabel>
    <relationshipName>CountryLanguages</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Mulesoft_Local__c.field-meta.xml
<CustomField>
    <fullName>Mulesoft_Local__c</fullName>
    <label>Mulesoft Local</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Language2__c/Language2__c.object-meta.xml
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Language2__c/fields/Iso2Code__c.field-meta.xml
<CustomField>
    <fullName>Iso2Code__c</fullName>
    <label>Iso2Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Language2__c/fields/Iso3Code__c.field-meta.xml
<CustomField>
    <fullName>Iso3Code__c</fullName>
    <label>Iso3Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-twist/main/default/classes/test/CountryLanguageManager_TEST.cls
@isTest
public with sharing class CountryLanguageManager_TEST {
    
    @isTest
    public static void test_getMulesoftApisPrefix_nominalCase() {
        // Given
        String langCountry = 'eng-us';
        String prefix = 'eco-us';

        Test.startTest();
        Country__c country = new Country__c();
        country.tech_duplicate__c = 'United_States';
        insert country;

        Language2__c language = new Language2__c();
        language.Iso2Code__c = 'US';
        language.Iso3Code__c = 'ENG';
        insert language;

        insert new CountryLanguage__c(
            Country__c = country.Id,
            Language__c = language.Id,
            ATG_Locale__c = langCountry,
            Mulesoft_Local__c = prefix
        );
        
        // When
        String actualPrefix = CountryLanguageManager.getMulesoftApisPrefix(langCountry);
        Test.stopTest();
        
        // Then
        System.assertEquals(prefix, actualPrefix);
    }
    
    @isTest
    public static void test_getMulesoftApisPrefix_shouldThrowException1() {
        // Given
        String langCountry = 'zzz-zz';
        String expectedExceptionMessage = String.format('LangCountry "{0}" is unknown', new List<String> { langCountry });
        
        try {
            // When
            Test.startTest();
            String actualPrefix = CountryLanguageManager.getMulesoftApisPrefix(langCountry);
            Test.stopTest();
        }
        catch (Exception e) {
            // Then
            System.assertEquals(expectedExceptionMessage, e.getMessage());
        }
    }

}