force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/HasOtherValue__c.field-meta.xml
<CustomField>
    <fullName>HasOtherValue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HasOtherValue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Iso2Code__c.field-meta.xml
<CustomField>
    <fullName>Iso2Code__c</fullName>
    <label>Iso2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Iso3Code__c.field-meta.xml
<CustomField>
    <fullName>Iso3Code__c</fullName>
    <label>Iso3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMapping__mdt/fields/HasOtherValue__c.field-meta.xml
<CustomField>
    <fullName>HasOtherValue__c</fullName>
    <defaultValue>false</defaultValue>
    <description>true if the country&apos;s value has no ISO3 code
(ex: StoreDB system has no ISO3 code for some values : ISO3 code will be USA for HAWAII, GBR for England, MNP for SAIPAN, KOR for &apos;KOREA (DOM)&apos;...)</description>
    <inlineHelpText>true if the country&apos;s value has no ISO3 code
(ex: StoreDB system has no ISO3 code for some values : ISO3 code will be USA for HAWAII, GBR for England, MNP for SAIPAN, KOR for &apos;KOREA (DOM)&apos;...)</inlineHelpText>
    <label>Has Other Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CountryMapping__mdt/fields/Iso2Code__c.field-meta.xml
<CustomField>
    <fullName>Iso2Code__c</fullName>
    <description>ISO2 country code</description>
    <label>Iso2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMapping__mdt/fields/Iso3Code__c.field-meta.xml
<CustomField>
    <fullName>Iso3Code__c</fullName>
    <description>ISO3 code</description>
    <label>Iso3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMapping__mdt/fields/QueueMessaging__c.field-meta.xml
<CustomField>
    <fullName>QueueMessaging__c</fullName>
    <label>QueueMessaging</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IconicsSettings__c/IconicsSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings for ICONiCS project</description>
    <label>Iconics Settings</label>
</CustomObject>

force-app/main/default/objects/IconicsSettings__c/fields/MessagingCountriesException__c.field-meta.xml
<CustomField>
    <fullName>MessagingCountriesException__c</fullName>
    <description>List of countries (ISO2) with exception for messaging separated by semicolon
to map according the language and not the country</description>
    <label>MessagingCountriesException</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/IconicsSettings__c/fields/MessagingDefaultQueue__c.field-meta.xml
<CustomField>
    <fullName>MessagingDefaultQueue__c</fullName>
    <label>MessagingDefaultQueue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Language__mdt/Language__mdt.object-meta.xml
<CustomObject>
    <description>Language ISO codes (for transcodification)
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes</description>
    <label>Language</label>
    <pluralLabel>Languages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Language__mdt/fields/QueueMessaging__c.field-meta.xml
<CustomField>
    <fullName>QueueMessaging__c</fullName>
    <label>QueueMessaging</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MessagingEndUser/fields/Tech_GroupID__c.field-meta.xml
<CustomField>
    <fullName>Tech_GroupID__c</fullName>
    <label>Tech_GroupID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Country of client who sent the message</description>
    <label>Country / Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/Queue_Developper_Name__c.field-meta.xml
<CustomField>
    <fullName>Queue_Developper_Name__c</fullName>
    <description>Queue developper name</description>
    <label>Queue Developper Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>Queue_Name__c</fullName>
    <description>Queue Name</description>
    <label>Queue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MessagingSession/fields/TECH_Queue_Messaging__c.field-meta.xml
<CustomField>
    <fullName>TECH_Queue_Messaging__c</fullName>
    <description>Tech Queue of messaging</description>
    <label>TECH Queue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MessagingSession/recordTypes/Messaging.recordType-meta.xml
<RecordType>
    <fullName>Messaging</fullName>
    <active>true</active>
    <description>Record Type for Messaging</description>
    <label>Messaging</label>
</RecordType>

force-app/main/default/classes/UpdateMessagingQueueAsync.cls
global class UpdateMessagingQueueAsync implements Schedulable {
    Set<Id> msgSessionId = new Set<Id>();
    
    public UpdateMessagingQueueAsync (Set<Id> messagingSessionIds){
        if(messagingSessionIds != null){
            msgSessionId = messagingSessionIds;
        }
    }
    public void execute(SchedulableContext ctx) {        
        List<MessagingSession> msgSessionList = [SELECT status ,OwnerId ,Id, Queue_Developper_Name__c,TECH_Queue_Messaging__c,Queue_Name__c,Name,EndUserContactId, 
                                                        MessagingEndUser.Tech_GroupID__c, MessagingEndUser.ContactId,channelType,Country__c,createdDate,ChannelGroup,ChannelLocale ,MessagingEndUserId
                                                  FROM MessagingSession 
                                                  WHERE Id IN :msgSessionId AND channelType = 'AppleBusinessChat'
                                                  ];
        if(!msgSessionList.isEmpty()){  
                      
            handleBeforeInsert(msgSessionList); 
            update msgSessionList;
        }
    }
    
    public static void handleBeforeInsert(List<MessagingSession> newList) {   

        Set<String> channelGroup = new Set<String>();
        Set<String> channelLocale = new Set<String>();
        Set<String> languages = new Set<String>();
        Map<Id,String> groupIdMessagingEndUser = new Map<Id,String>();


        for (MessagingSession mess : newList) {
           
            if (String.isNotEmpty(mess.ChannelGroup)) {
              	channelGroup.add(mess.ChannelGroup);
            }
            if(String.isNotEmpty(mess.MessagingEndUser.Tech_GroupID__c)){
                groupIdMessagingEndUser.put(mess.MessagingEndUserId,mess.MessagingEndUser.Tech_GroupID__c);
            }
            if(String.isNotEmpty(mess.ChannelLocale)){
                languages.add(mess.ChannelLocale.substring(0,2));
                String codeISO2 = mess.ChannelLocale.substringAfter('_');
                if(String.isNotEmpty(codeISO2))
                    channelLocale.add(codeISO2.substring(0,2));
    
            }
        }
        String countriesException =  IconicsSettings__c.getInstance().MessagingCountriesException__c;
        List<String> listCountriesException = String.isNotEmpty(countriesException) ? countriesException.split(';') :new List<String>();

        channelGroup.addall(groupIdMessagingEndUser.values());

        Map<String,String> countryMappingQueue = getCountryMappingQueue(channelGroup,channelLocale);

        Map<String,String> languageMappingQueue = getLanguageMappingQueue(languages);
        
        List<String> QueuesName = new list <String>();
        QueuesName.addAll(countryMappingQueue.values());
        QueuesName.addAll(languageMappingQueue.values());

        Map<String,Group> mapQueue = getQueue(QueuesName);
        
        for (MessagingSession mess : newList) {
            String ownerIdString = String.valueOf(mess.OwnerId);

            String language = String.isNotEmpty(mess.ChannelLocale) ? mess.ChannelLocale.substring(0,2) :'';
            
            String codeISO2 = String.isNotEmpty(mess.ChannelLocale) && String.isNotEmpty(mess.ChannelLocale.substringAfter('_'))? mess.ChannelLocale.substringAfter('_').substring(0,2) : '';

            String chatSuggest = (String.isNotEmpty(mess.ChannelGroup) && countryMappingQueue.containskey(mess.ChannelGroup) ? 
                                  mess.ChannelGroup :
                                  countryMappingQueue.containskey(groupIdMessagingEndUser.get(mess.MessagingEndUserId))?
                                  groupIdMessagingEndUser.get(mess.MessagingEndUserId):'');
                     
            String codeISO3 = String.isNotEmpty(chatSuggest)? chatSuggest:countryMappingQueue.containskey(codeISO2)? countryMappingQueue.get(codeISO2):'';
           
            String queueNameOflanguage = String.isNotEmpty(language) ?languageMappingQueue.get(language) :'';
            
            system.debug('codeISO3 :'+ codeISO3);
             system.debug('mess.channelLocale :'+ mess.channelLocale);
            system.debug('chatSuggest :'+ chatSuggest);

            
            String queueName = (countryMappingQueue.containsKey(codeISO3) || listCountriesException.contains(mess.channelLocale)?
                                codeISO2 =='CA' && String.isEmpty(chatSuggest) && !listCountriesException.contains(mess.channelLocale)? '': countryMappingQueue.get(codeISO3):
                                codeISO2 =='CA'?'' : queueNameOflanguage); 
            system.debug('queueName');
            system.debug(queueName);
                    
            mess.Country__c =  codeISO3;
            String defaultQueue = string.isNotEmpty(IconicsSettings__c.getInstance().MessagingDefaultQueue__c) ?IconicsSettings__c.getInstance().MessagingDefaultQueue__c : mess.ownerId ;
            if(mess.status!='Ended'){
                
                if(String.isNotEmpty(queueName) && mapQueue.containskey(queueName)) {
                    mess.Queue_Name__c = (mapQueue.containsKey(queueName)? mapQueue.get(queueName).Name : 'Messaging US');
                    mess.TECH_Queue_Messaging__c = (mapQueue.containsKey(queueName)? mapQueue.get(queueName).id : defaultQueue);
                    mess.Queue_Developper_Name__c = (mapQueue.containsKey(queueName)? mapQueue.get(queueName).DeveloperName: 'Messaging_US');
                    mess.ownerId =  mapQueue.get(queueName).id;
                }else{
                    mess.ownerId =  defaultQueue ;
                    mess.TECH_Queue_Messaging__c = defaultQueue ; 
                    mess.Queue_Name__c = 'Messaging US' ;
                    mess.Queue_Developper_Name__c = 'Messaging_US';
                }
            }
        }
    }
   
    private static Map<String,Group> getQueue(List<String> QueueName ){
        Map<String,Group> QueueMap = new Map<String,Group>();
        for(Group grp : [SELECT Id,DeveloperName ,Name FROM Group WHERE Type = 'Queue' AND DeveloperName in:QueueName]){
             QueueMap.put(grp.DeveloperName,grp);
        }
        return QueueMap;
    }
    private static Map<String,String> getCountryMappingQueue(Set<String> channelGroup,Set<String> channelLocale){
       Map<String,String> QueueName = new Map<String,String>();
       Map<Id, CountryMapping__mdt> first_query = new Map<Id, CountryMapping__mdt>([SELECT Iso2Code__c,Iso3Code__c,QueueMessaging__c
                                                                                    FROM CountryMapping__mdt 
                                                                                    WHERE Iso3Code__c in: channelGroup and HasOtherValue__c=false]);

       Map<Id, CountryMapping__mdt> second_query = new Map<Id, CountryMapping__mdt>([SELECT Iso2Code__c,Iso3Code__c,QueueMessaging__c
                                                                                    FROM CountryMapping__mdt 
                                                                                    WHERE  Iso2Code__c in:channelLocale and HasOtherValue__c=false]); 
        
       first_query.putAll(second_query);
 
       for(CountryMapping__mdt CountryMapping :first_query.values()){
            if(CountryMapping.QueueMessaging__c != null){
                QueueName.put(CountryMapping.Iso3Code__c,CountryMapping.QueueMessaging__c);
            }
            if(channelLocale.contains(CountryMapping.Iso2Code__c)){
                QueueName.put(CountryMapping.Iso2Code__c,CountryMapping.Iso3Code__c);
            }
        }
       return QueueName; 
    }
    private static Map<String,String> getLanguageMappingQueue(Set<String> languages){
        Map<String,String> QueueName = new Map<String,String>();
        
       for(Language__mdt languagesMapping :[SELECT DeveloperName, QueueMessaging__c 
                                            FROM Language__mdt 
                                            WHERE DeveloperName in: languages and QueueMessaging__c!=null]){
           
        QueueName.put(languagesMapping.DeveloperName,languagesMapping.QueueMessaging__c);
           
       }
       return QueueName; 
        
    }
}