force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Iso2Code__c.field-meta.xml
<CustomField>
    <fullName>Iso2Code__c</fullName>
    <label>Iso2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Iso3Code__c.field-meta.xml
<CustomField>
    <fullName>Iso3Code__c</fullName>
    <label>Iso3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/tech_duplicate__c.field-meta.xml
<CustomField>
    <fullName>tech_duplicate__c</fullName>
    <description>To avoid duplicate countries</description>
    <externalId>true</externalId>
    <label>tech_duplicate</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/CountryLanguage__c.object-meta.xml
<CustomObject>
    <label>CountryLanguage</label>
    <nameField>
        <label>CountryLanguage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountryLanguages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CountryLanguage__c/fields/ATG_Locale__c.field-meta.xml
<CustomField>
    <fullName>ATG_Locale__c</fullName>
    <label>ATG Locale</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Locales</relationshipLabel>
    <relationshipName>CountryLanguages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/defaultStore__c.field-meta.xml
<CustomField>
    <fullName>defaultStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>defaultStore</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>CountryLanguages</relationshipLabel>
    <relationshipName>CountryLanguages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Dispatch_Country__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Country__c</fullName>
    <label>Dispatch Country</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <referenceTo>Language2__c</referenceTo>
    <relationshipLabel>Locale</relationshipLabel>
    <relationshipName>CountryLanguages</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Language2__c/Language2__c.object-meta.xml
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Language2__c/fields/Iso2Code__c.field-meta.xml
<CustomField>
    <fullName>Iso2Code__c</fullName>
    <label>Iso2Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Language2__c/fields/Iso3Code__c.field-meta.xml
<CustomField>
    <fullName>Iso3Code__c</fullName>
    <label>Iso3Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration_Code_Verification_Request__c/Registration_Code_Verification_Request__c.object-meta.xml
<CustomObject>
    <label>Registration Code Verification Request</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Registration Code Verification Request N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Code Verification Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Code_Verification_Request__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Registration_Code_Verification_Request__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/TWIST_Registration_Form_Settings__c/TWIST_Registration_Form_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TWIST Registration Form Settings</label>
</CustomObject>

force-app/main/default/objects/TWIST_Registration_Form_Settings__c/fields/Code_Validity_Time__c.field-meta.xml
<CustomField>
    <fullName>Code_Validity_Time__c</fullName>
    <label>Code Validity Time</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BARBADE</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILE</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>COLOMBIA</fullName>
            </value>
            <value>
                <fullName>CYPRUS</fullName>
            </value>
            <value>
                <fullName>CZECH REPUBLIC</fullName>
            </value>
            <value>
                <fullName>DENMARK</fullName>
            </value>
            <value>
                <fullName>DOMINICAIN REPUBLIC</fullName>
            </value>
            <value>
                <fullName>FINLAND</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>GREECE</fullName>
            </value>
            <value>
                <fullName>GUAM</fullName>
            </value>
            <value>
                <fullName>HONG KONG</fullName>
            </value>
            <value>
                <fullName>HUNGARY</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDONESIA</fullName>
            </value>
            <value>
                <fullName>IRELAND</fullName>
            </value>
            <value>
                <fullName>ISRAEL</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>JORDANIE</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TWIST_Account_Confirmation_TEST.cls
@isTest
public with sharing class TWIST_Account_Confirmation_TEST {
    
    @testSetup
    static void initData(){

        TWIST_Registration_Form_Settings__c  registrationSetting = new TWIST_Registration_Form_Settings__c();
        registrationSetting.Code_Validity_Time__c = 10;
        insert registrationSetting;
        
        Identity_TestFactory.createSettings();

        Registration_Code_Verification_Request__c code = createCodeRequest('12345', 'test@test.test');
        insert code;

        Store__c store = new Store__c();
        store.RetailStoreId__c = 'A06';
        insert store;

        Language2__c lang2 = new Language2__c();
        lang2.Iso2Code__c = 'US';
        lang2.Iso3Code__c = 'US';
        insert lang2;

        Country__c country = new Country__c();
        country.tech_duplicate__c = 'Austria';
        insert country;

        CountryLanguage__c countryLanguage = new CountryLanguage__c();
        countryLanguage.defaultStore__c = store.Id;
        countryLanguage.Dispatch_Country__c = 'US';
        countryLanguage.ATG_Locale__c = 'eng-e1';
        countryLanguage.Country__c = country.Id;
        countryLanguage.Language__c = lang2.Id;
        insert countryLanguage;
    }

    
    @isTest
    static void test_createMyLvUserAndRedirect_registrationMode() {
        // Given
        Map<String,Object> queryParams = new Map<String,Object> {
            TWIST_QueryParamKey_CONST.STATE => 'dummy-state',
            TWIST_QueryParamKey_CONST.CODE_CHALLENGE => 'dummy-code-challenge',
            TWIST_QueryParamKey_CONST.CLIENT_ID => 'dummy-client-id',
            TWIST_QueryParamKey_CONST.REDIRECT_URI => 'https://dummy-redirect.uri'
        };

        Map<String,Object> formData = new Map<String,Object> {
            'firstname' => 'Test',
            'country' => 'USA',
            'lastname' => 'Test',
            'title' => 'Test',
            'email' => 'test@gmail.com',
            'emailconfirmation' => 'test@gmail.com',
            'password' => 'Pass@!123456'
        };
        Map<String,Object> result = TWIST_Account_Confirmation.createMyLvUserAndRedirect('12345', 'test@test.test', formData, queryParams, new Map<String,String>{});
        system.debug('result : '+result);
        Test.setMock(HttpCalloutMock.class, new GetMockData());

        // When
        Test.startTest();
        Map<String,Object> expected = TWIST_Utils.buildFailureResponseObject('form', TWIST_i18nTranslations.translateSingleLabel('CUSTOM_LABEL', 'en')) ;
        Test.stopTest();

        // Then
        System.assertEquals(result, expected);
    }

    @isTest
    static void test_createMyLvUserAndRedirect_invalidCode() {

        Map<String,Object> result = TWIST_Account_Confirmation.createMyLvUserAndRedirect('', 'test@test.test', new Map<String,Object> {}, new Map<String,Object> {}, new Map<String,String>{});
        Map<String,Object> expected = TWIST_Utils.buildFailureResponseObject('form', TWIST_i18nTranslations.translateSingleLabel('Twist_Account_Creation_Form_AccountCreationProcessError', 'en')) ;

        System.assertEquals(result, expected);
    }
    
    @isTest
    static void test_isUserIdentity() {
        User user = Identity_TestFactory.createUser('TEST','TEST','identityUserTest@test.test','0500000000','972');

        boolean result = TWIST_Account_Confirmation.isUserIdentity('identityUserTest@test.test');
        boolean resultEmpty = TWIST_Account_Confirmation.isUserIdentity('');

        System.assertEquals(result, true);
        System.assertEquals(resultEmpty, false);
    }

    @isTest
    static void test_userCreation() {
        Account account1 = Identity_TestFactory.createAccount('test1', 'test1', 'test-FULL_ACTIVATION@test.com', '133456789', '972', true);
        Account account2 = Identity_TestFactory.createAccount('test2', 'test2', 'test-PARTIAL_ACTIVATION@test.com', '133456788', '972', true);

        account2 = TWIST_RegistrationUtils.getClientById(account2.id);

        Id resultFullActivation = TWIST_Account_Confirmation.userCreation(account1, 'Pass86324@!', new Map<String,Object> {}, TWIST_RegistrationUtils.Mode.FULL_ACTIVATION);
        Id resultPartialActivation = TWIST_Account_Confirmation.userCreation(account2, 'Pass86324@!', new Map<String,Object> {}, TWIST_RegistrationUtils.Mode.PARTIAL_ACTIVATION);
        
        try {
            Id resultException = TWIST_Account_Confirmation.userCreation(account2, 'Pass86324@!', new Map<String,Object> {}, TWIST_RegistrationUtils.Mode.LOGIN);
        } catch(Exception e) {
            Exception ex = new AuraHandledException('error');
            System.assertEquals(e.getMessage(), ex.getMessage());
        }

        System.assertEquals(resultFullActivation == null, false);
        System.assertEquals(resultPartialActivation == null, false);
    }


    //Only for code coverage
    @isTest
    static void test_createUser() {

        Account account = Identity_TestFactory.createAccount('test3', 'test3', 'test-createuser@test.com', '133456189', '972', true);
        account.AttachedStoreCode__pc = 'A06';
        update account;

        Map<String,Object> queryParams = new Map<String,Object> {
            'dispatchCountry' => 'US',
            'langCountry' => 'eng-e1'
        };

        TWIST_Account_Confirmation.sendClientRMS(account, queryParams);
        TWIST_Account_Confirmation.sendClientRMS(null, queryParams); //Exception
    }

    @isTest
    static void test_socialMediaCreationAndLogin() {

        User user = Identity_TestFactory.createUser('TEST','TEST','identityUserTest@test.test','0500000000','972');

        Map<String,String> socialParams = new Map<String,String> {
            'social_id' => 'Uf2537919f7f580be5280cd749ce7b86e',
            'social_media_type' => 'Line'
        };

        Map<String,Object> queryParams = new Map<String,Object> {
            'dispatchCountry' => 'US',
            'langCountry' => 'eng-e1'
        };

        TWIST_Account_Confirmation.socialMediaCreationAndLogin('identityUserTest@test.test','test1234', socialParams, queryParams);
    }
    //--------------- PRIVATE METHODS ---------------//
    private static Registration_Code_Verification_Request__c createCodeRequest(String code, String recordId) {
        Registration_Code_Verification_Request__c request = new Registration_Code_Verification_Request__c();
        request.code__c = code;
        request.Record_Id__c = recordId;
        request.State__c = '1';
        return request;
    }

    public class GetMockData implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest request) {
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setStatusCode(200);
            response.setStatus('OK');
            response.setBody(' "IDENTITY_Activation_Confirm_Button" : "IDENTITY_Activation_Confirm_Button" , "CUSTOM_LABEL" : "CUSTOM_LABEL",');

            return response;
        }
    }
}