force-app/main/default/objects/Case/fields/Approval_Type__c.field-meta.xml
<CustomField>
    <fullName>Approval_Type__c</fullName>
    <label>Approval Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRICE_ADJUSTMENT</fullName>
                <label>Price Adjustment</label>
            </value>
            <value>
                <fullName>BANK_TRANSFER</fullName>
                <label>Bank Transfer</label>
            </value>
            <value>
                <fullName>STOCK_ON_HOLD</fullName>
                <label>Stock On Hold</label>
            </value>
            <value>
                <fullName>CLIENTELING_EXCEPTION</fullName>
                <label>Clienteling Exception</label>
            </value>
            <value>
                <fullName>FREE_SHIPPING</fullName>
                <label>Free Shipping</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Shipping__c.field-meta.xml
<CustomField>
    <fullName>Order_Shipping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping group (New format)</label>
    <referenceTo>OrderShipping__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Approval.recordType-meta.xml
<RecordType>
    <fullName>Approval</fullName>
    <active>true</active>
    <businessProcess>Approval</businessProcess>
    <description>Case used for Approbation process</description>
    <label>Approval</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Clienteling.recordType-meta.xml
<RecordType>
    <fullName>Clienteling</fullName>
    <active>true</active>
    <businessProcess>Clienteling</businessProcess>
    <label>Clienteling</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>ATG=order id
KBRW=transaction id</description>
    <externalId>true</externalId>
    <label>Order Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order_Note__c/Order_Note__c.object-meta.xml
<CustomObject>
    <label>Order Note</label>
    <nameField>
        <label>Order Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Note__c/fields/ClientAdvisor__c.field-meta.xml
<CustomField>
    <fullName>ClientAdvisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Advisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Order_Notes_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Notes</relationshipLabel>
    <relationshipName>Order_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Order_Shipping__c.field-meta.xml
<CustomField>
    <fullName>Order_Shipping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Shipping</label>
    <referenceTo>OrderShipping__c</referenceTo>
    <relationshipLabel>Order Notes</relationshipLabel>
    <relationshipName>Order_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ExceptionalClient</fullName>
                <label>Exceptional Client (VIC 50K)</label>
            </value>
            <value>
                <fullName>ExceptionalSituations</fullName>
                <label>Exceptional Situations (Complaints - Defective items received)</label>
            </value>
            <value>
                <fullName>ExceptionalSKU</fullName>
                <label>Exceptional SKU’s (&gt;4.500€*)</label>
            </value>
            <value>
                <fullName>NoneOfAbove</fullName>
                <label>None of the above</label>
            </value>
            <value>
                <fullName>ClientAccomodation</fullName>
                <label>Client accommodation</label>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>SecondLookOrderReplacement</fullName>
                <label>Second look order replacement</label>
            </value>
            <value>
                <fullName>LoyaltyGesture</fullName>
                <label>Loyalty Gesture</label>
            </value>
            <value>
                <fullName>ClientRequest</fullName>
                <label>Client Request</label>
            </value>
            <value>
                <fullName>InitialsNumbersMistake</fullName>
                <label>There is a mistake with the initials/numbers of my personalization</label>
            </value>
            <value>
                <fullName>ColorsMistake</fullName>
                <label>There is a mistake with the colors of my personalization</label>
            </value>
            <value>
                <fullName>StickersMistake</fullName>
                <label>There is a mistake with the stickers of my personalization</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Tech_OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>Tech_OrderNumber__c</fullName>
    <description>This field is used to store the order number if we receive the &quot;Order Note&quot; before the creation of the Order. We use it to populate the lookup &quot;order__c&quot; when the order is created.</description>
    <label>Tech Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Tech_ShippingNumber__c.field-meta.xml
<CustomField>
    <fullName>Tech_ShippingNumber__c</fullName>
    <label>Tech Shipping Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATTACHED_NOTE</fullName>
                <label>Attached Note</label>
            </value>
            <value>
                <fullName>CLIENTELING_EXCEPTION</fullName>
                <label>Clienteling Exception</label>
            </value>
            <value>
                <fullName>PRICE_ADJUSTMENT</fullName>
                <label>Price Adjustment</label>
            </value>
            <value>
                <fullName>BANK_TRANSFER</fullName>
                <label>Bank Transfer</label>
            </value>
            <value>
                <fullName>STOCK_ON_HOLD</fullName>
                <label>Stock On Hold</label>
            </value>
            <value>
                <fullName>FREE_SHIPPING</fullName>
                <label>Free Shipping</label>
            </value>
            <value>
                <fullName>PAYMENT_LINK</fullName>
                <label>Payment Link</label>
            </value>
            <value>
                <fullName>EXTENDED_PAYMENT_LINK</fullName>
                <label>Extended Payment Link</label>
            </value>
            <value>
                <fullName>PERSO_PRODUCT_ACC</fullName>
                <label>Perso Product Accepted</label>
            </value>
            <value>
                <fullName>PERSO_PRODUCT_REF</fullName>
                <label>Perso Product Refused</label>
            </value>
            <value>
                <fullName>PAY_AFTER_AGREEMENT</fullName>
                <label>Pay After Agreement</label>
            </value>
            <value>
                <fullName>General Comment</fullName>
                <isActive>false</isActive>
                <label>General Comment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderLine__c/OrderLine__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderLine__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderShipping__c/OrderShipping__c.object-meta.xml
<CustomObject>
    <description>One order can be sent in several times</description>
    <label>Order Shipping</label>
    <nameField>
        <label>Shipping Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders Shippings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderShipping__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Orders Shippings</relationshipLabel>
    <relationshipName>Orders_Shippings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Action__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>VIC/10K</fullName>
            </value>
            <value>
                <fullName>High Escalated complaint</fullName>
            </value>
            <value>
                <fullName>Technical issue</fullName>
            </value>
            <value>
                <fullName>Defective item</fullName>
            </value>
            <value>
                <fullName>Lost Parcel</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Client Cancelled</fullName>
            </value>
            <value>
                <fullName>Stock issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/ShippingNumber__c.field-meta.xml
<CustomField>
    <fullName>ShippingNumber__c</fullName>
    <description>KBRW=request id
ATG=shipping group</description>
    <externalId>true</externalId>
    <label>Shipping Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Accepted / Rejected</fullName>
            </value>
            <value>
                <fullName>Intransit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/RMS_ID__c.field-meta.xml
<CustomField>
    <fullName>RMS_ID__c</fullName>
    <description>User RMS ID</description>
    <label>RMS ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-twisticonics/main/default/classes/OrderNoteService.cls
global with sharing class OrderNoteService {

    //public Enum OrderNoteType {ATTACHED_NOTE, CLIENTELING_EXCEPTION, PRICE_ADJUSTMENT}
    
    // Type__c : picklist Values
    public static final string ATTACHED_NOTE = 'ATTACHED_NOTE';
    public static final string CLIENTELING_EXCEPTION = 'CLIENTELING_EXCEPTION';
    public static final string PRICE_ADJUSTMENT = 'PRICE_ADJUSTMENT';
    public static final string BANK_TRANSFER = 'BANK_TRANSFER';
    public static final string STOCK_ON_HOLD = 'STOCK_ON_HOLD';
    public static final string FREE_SHIPPING = 'FREE_SHIPPING';
    public static final string PAYMENT_LINK = 'PAYMENT_LINK';
    public static final string EXTENDED_PAYMENT_LINK = 'EXTENDED_PAYMENT_LINK';
    public static final string PAY_AFTER_AGREEMENT = 'PAY_AFTER_AGREEMENT';
    public static final string PERSO_PRODUCT_ACC = 'PERSO_PRODUCT_ACC';
    public static final string PERSO_PRODUCT_REF = 'PERSO_PRODUCT_REF';


    // Contact con = [SELECT Id, Status__c FROM Contact WHERE Id = ‘1234567890’];
    // //To get picklist entries
    // List<Schema.PicklistEntry> values = Contact. Status__c.getDescribe().getPicklistValues();
    // Map<String,String> statusApiToLabelMap = new Map<String,String>();
    // For(Schema.PicklistEntry sp : values){
    //     //Map to hold Picklist API as Key and Picklist Label as Value
    //     statusApiToLabelMap.put(sp. getValue(), sp. values.getLabel());
    // }
    // System.debug(‘Label value of picklist>>’+ statusApiToLabelMap .get(con.Status__c));

    

    @auraEnabled(cacheable=true)
    public static List<Order_Note__c> getOrderNoteByOrders(List<String> orderNumbers, List<String> types) {        
        List<Order_Note__c> orderNotes = [SELECT Id, Type__c, 
                                            Tech_OrderNumber__c, Order__c, Order__r.OrderNumber__c, 
                                            Tech_ShippingNumber__c, Tech_ShippingNumberV2__c, Order_Shipping__c, Order_Shipping__r.ShippingNumber__c ,ClientAdvisor__c, 
                                            Reason__c, toLabel(Reason__c) ReasonLabel, Description__c,CreatedDate
                                        FROM Order_Note__c
                                        WHERE Tech_OrderNumber__c in :orderNumbers
                                          and Type__c in :types];
                                        
        system.debug(orderNotes);

        return orderNotes;
    }

    // List of Attached Note related to order or shipping
    // Param
    // - recordId : could be "order id" or "shipping id"
    @auraEnabled(cacheable=true)
    public static List<Order_Note__c> getAttachedNote(String recordId) {        
        List<Order_Note__c> orderNotes = [SELECT Id, Description__c, 
                                            ClientAdvisor__c, ClientAdvisor__r.Name, ClientAdvisor__r.RMS_ID__c,
                                            CreatedDate, Type__c
                                        FROM Order_Note__c
                                        WHERE ((Order__c = :recordId and Order_Shipping__c = null)
                                          OR (Order_Shipping__c = :recordId))
                                          AND Type__c = 'ATTACHED_NOTE'
                                        ORDER BY CreatedDate];
        system.debug(orderNotes);

        return orderNotes;
    }

    // Map<Order__c or Order_Shipping__c, 
    //  Map<Case.Approval_Type__c, Case>>
    @auraEnabled(cacheable=true)
    public static List<Case> getRelatedApprovalCases(List<String> orderNumbers) { 
        Id caseRecordIdApproval = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Approval').getRecordTypeId();

        List<Case> ApprovalCases = [SELECT Id, Status, CaseNumber,
                                            Approval_Submitter__c, Approval_Type__c, toLabel(Approval_Type__c) ApprovalTypeLabel, 
                                            Order__c, Order__r.OrderNumber__c, 
                                            Order_Shipping__c, Order_Shipping__r.ShippingNumber__c, Order_Shipping__r.ShippingNumberV2__c,
                                            OwnerId, recordTypeId, AccountId, CreatedDate
                                        FROM Case
                                        WHERE recordTypeId = :caseRecordIdApproval
                                            AND (Order__r.orderNumber__c in :orderNumbers
                                                OR Order_Shipping__r.Order__r.orderNumber__c in :orderNumbers)];
                                        
        system.debug(ApprovalCases);

        return ApprovalCases;
    }


    // Sync Order_Note__c records pending with order__c and/or order_shipping__c
    @future
    public static void syncWithOrder(List<String> orderNumbers, List<String> shippingNumbers){
        
        Map<String, OrderShipping__c> orderMap = new Map<String, OrderShipping__c>();
        Map<String, OrderShipping__c> orderShippingMap = new Map<String, OrderShipping__c>();

        List<String> shippingNumbersV2 = new List<String>();

        // ---------- //
        // JIRA-25028 //
        // ---------- //
        // List<Order__c> orders = [SELECT id, orderNumber__c, ownerId__c, 
        //                             (SELECT Id, ShippingNumber__c FROM Orders_Shippings__r WHERE ShippingNumber__c in :shippingNumbers) 
        //                         FROM order__c WHERE orderNumber__c in :orderNumbers];        
        // for (Order__c order: orders) {
        //     orderMap.put(order.orderNumber__c, order);
        //     // orderNumberSet.add(order.orderNumber__c);
        //     for(OrderShipping__c orderShipping: order.Orders_Shippings__r) {
        //         orderShippingMap.put(orderShipping.ShippingNumber__c, orderShipping);
        //         // shippingNumberSet.add(orderShipping.ShippingNumber__c);
        //     }
        // }

        // Kitting -> convert shippingNumber V1 format (xxxxxx-y) to shippingNumber V2 format (xxxxxxx)
        for(String shippingNumber: shippingNumbers) {
            shippingNumbersV2.add(shippingNumber.split('-')[0]);
            if(shippingNumber.contains('-')) {
                shippingNumbersV2.add(shippingNumber);
            }
        }


        List<OrderShipping__c> orderShippings = [SELECT Order__r.Id, Order__r.orderNumber__c, Order__r.ownerId__c, Id, ShippingNumber__c, ShippingNumberV2__c 
                                            FROM OrderShipping__c 
                                            WHERE ShippingNumber__c in :shippingNumbersV2 OR Order__r.orderNumber__c in :orderNumbers];       

        for (OrderShipping__c orderShipping: orderShippings) {
            orderMap.put(orderShipping.order__r.orderNumber__c, orderShipping);
            orderShippingMap.put(orderShipping.ShippingNumberV2__c, orderShipping);
        }

        Integer nbOfTry = 0;
        Boolean hasRetry = false;

        List<Order_Note__c> orderNotes;

        do {
            try {
                hasRetry = false;
                // Does it exist pending : Attached Note, Clienteling Exception or Price adjustment 
                orderNotes = [SELECT Id, Tech_OrderNumber__c, Order__c, 
                                Tech_ShippingNumber__c, Tech_ShippingNumberV2__c, Order_Shipping__c, ClientAdvisor__c,Type__c,Order__r.Account__c,Order_Shipping__r.Order__r.Account__c
                            FROM Order_Note__c
                            WHERE (Order__c = null and Order_Shipping__c = null)
                            and (Tech_OrderNumber__c in :orderNumbers OR Tech_ShippingNumberV2__c in :shippingNumbersV2)
                            FOR UPDATE];
            }
            catch(QueryException e) {
                nbOfTry++;
                if (nbOfTry <= 3) {
                    hasRetry = true;
                }
                else {
                    throw e;
                }
            }
        } while (hasRetry);

        List<Order_Note__c> orderNotesToUpdate = new List<Order_Note__c>();                               
        for (Order_Note__c orderNote: orderNotes) {
            orderNote.Order__c = null;
            orderNote.Order_Shipping__c = null;
            orderNote.ClientAdvisor__c = orderMap.get(orderNote.Tech_OrderNumber__c)?.Order__r.OwnerId__c;

            if (orderNote.Tech_ShippingNumberV2__c != null) {                
                // On Map "Order_Note" avec "Order_Shipping" 
                orderNote.Order_Shipping__c = orderShippingMap.get(orderNote.Tech_ShippingNumberV2__c)?.Id;
            }
            if (orderNote.Tech_OrderNumber__c != null) { 
                // On Map "Order_Note" avec "Order"
                orderNote.Order__c = orderMap.get(orderNote.Tech_OrderNumber__c)?.order__r.Id;
            }
            // IF the order exists and the mapping is a success
            if (orderNote.Order__c != null || orderNote.Order_Shipping__c != null) {
                orderNotesToUpdate.add(orderNote);
            }
        }

        if (!orderNotesToUpdate.isEmpty()) {
            update orderNotesToUpdate;
            approvalCaseCreation(orderNotesToUpdate);
        }
    }


    public static void approvalCaseCreation(List<Order_Note__c> orderNotesList)
    {
        List<Order_Note__c> orderNodeToCreateCase = new List<Order_Note__c>();
        Map<String, Order_Note__c> orderNodeToCreateCaseMap = new Map<String, Order_Note__c>();
        Map<Id, Id> orderAccountMap = new Map<Id, Id>();
        Map<Id, Id> orderContactMap = new Map<Id, Id>();
        Map<Id, String> orderCountryMap = new Map<Id, String>();

        Map<Id, Id> ShipppingOrderMap = new Map<Id, Id>();

        Map<Id, String> CACountryMap = new Map<Id, String>();

        Map<String, String> countryQueueMap = new Map<String, String>();
        Map<String, Id> QueueNameIdMap = new Map<String, Id>();
        Map<String, Id> countryQueueIdMap = new Map<String, Id>();

        Set<Id> CAList = new Set<Id>();
        Set<Id> OrderId = new Set<Id>();
        Set<Id> ShippingId = new Set<Id>();

      

        try{
            List<String> caseApprovalType = new List<String>();
            Schema.DescribeFieldResult fieldDescription = Case.Approval_Type__c.getDescribe();
        List<Schema.PicklistEntry> entries = fieldDescription.getPicklistValues();
        for (Schema.PicklistEntry entry : entries) {
            caseApprovalType.add(entry.getValue());
            }

            System.debug('nao caseApprovalType'+caseApprovalType);
        for(Order_Note__c currentOrderNote : orderNotesList)
        {

            if(caseApprovalType.contains(currentOrderNote.Type__c))
            {

                orderNodeToCreateCaseMap.put(currentOrderNote.Id,currentOrderNote);
                orderNodeToCreateCase.add(currentOrderNote);
                CAList.add(currentOrderNote.ClientAdvisor__c);
                OrderId.add(currentOrderNote.Order__c);
                ShippingId.add(currentOrderNote.Order_Shipping__c);
            }

        }
        if(orderNodeToCreateCase.size()>0)
        {

            
            //List<OrderLine__c> orderAccount = [SELECT Id, Order__c, Order__r.Account__c,Order__r.Account__r.PersonContactId, OrderShipping__c FROM OrderLine__c WHERE (Order__c IN: OrderId OR OrderShipping__c IN: ShippingId)];
            Set<OrderShipping__c> orderAccount = new Set<OrderShipping__c>();
            //need to do 2 query for performance issue
            if(!ShippingId.isEmpty())
            {
                orderAccount.addAll([SELECT Id, Order__c, Order__r.Account__c,Order__r.Account__r.PersonContactId, Order__r.Store__r.StoreCountry__c FROM OrderShipping__c WHERE Id IN: ShippingId ]);
            }
            if(!OrderId.isEmpty())
            {
                orderAccount.addAll ([SELECT Id, Order__c, Order__r.Account__c,Order__r.Account__r.PersonContactId, Order__r.Store__r.StoreCountry__c FROM OrderShipping__c WHERE Order__c IN: OrderId]);
            }

        //List<User> userCA = [SELECT Id, Country__c FROM User WHERE Id IN: CAList];
        

        
        if(orderAccount.size()>0)
        {
            // for(OrderLine__c currentOrder : orderAccount)
            // {
            //     ShipppingOrderMap.put(currentOrder.OrderShipping__c, currentOrder.Order__c);
            //     if(ShippingId.contains(currentOrder.OrderShipping__c) && orderAccountMap.get(currentOrder.OrderShipping__c)==null)
            //     {
            //         orderAccountMap.put(currentOrder.OrderShipping__c,currentOrder.Order__r.Account__c);
            //         orderContactMap.put(currentOrder.OrderShipping__c,currentOrder.Order__r.Account__r.PersonContactId);
            //     }
            //     else if(orderAccountMap.get(currentOrder.Order__c)==null)
            //     {
            //         orderAccountMap.put(currentOrder.Order__c,currentOrder.Order__r.Account__c);
            //         orderContactMap.put(currentOrder.Order__c,currentOrder.Order__r.Account__r.PersonContactId);

            //     }
            // }

            //if country is not in the metadata, we need to map it
            Map<String,String> countryMap = new Map<String,String> {
                'USA' => 'UNITED STATES',
                'MACAU' => 'MACAO'
            };

            String storeCountry;

            for(OrderShipping__c currentOrder : orderAccount)
            {
                storeCountry = currentOrder.Order__r.Store__r.StoreCountry__c;
                if(countryMap.get(storeCountry) != null) {
                    storeCountry = countryMap.get(storeCountry);
                }

                ShipppingOrderMap.put(currentOrder.Id, currentOrder.Order__c);
                if(ShippingId.contains(currentOrder.Id) && orderAccountMap.get(currentOrder.Id)==null)
                {
                    orderAccountMap.put(currentOrder.Id,currentOrder.Order__r.Account__c);
                    orderContactMap.put(currentOrder.Id,currentOrder.Order__r.Account__r.PersonContactId);
                }
                else if(orderAccountMap.get(currentOrder.Order__c)==null)
                {
                    orderAccountMap.put(currentOrder.Order__c,currentOrder.Order__r.Account__c);
                    orderContactMap.put(currentOrder.Order__c,currentOrder.Order__r.Account__r.PersonContactId);
                }
                orderCountryMap.put(currentOrder.Order__c,storeCountry);
            }
        }
        // System.debug('orderAccountMap ' +orderAccountMap);
        // if(userCA.size()>0)
        // {
        //     //if country is not in the metadata, we need to map it
        //     Map<String,String> countryMap = new Map<String,String> {
        //         'USA' => 'UNITED STATES',
        //         'MACAU' => 'MACAO'
        //     };
        //     for(User currentUser : userCA)
        //     {
                
        //         if(CACountryMap.get(currentUser.Id)==null)
        //         {
        //             String userCountry =currentUser.Country__c;
        //             if(countryMap.get(userCountry) != null) {
        //                 userCountry = countryMap.get(userCountry);
        //             }
     
        
        //             CACountryMap.put(currentUser.Id, userCountry);
        //         }
                
        //     }
        // }

        List<CountryMapping__mdt> countryMapping = [SELECT Id, QueueApproval__c, Picklist__c FROM CountryMapping__mdt WHERE Picklist__c IN:  orderCountryMap.values() AND HasOtherValue__c=false];

        for(CountryMapping__mdt countryMap : countryMapping)
        {
            if(countryQueueMap.get(countryMap.Picklist__c)==null)
            {
                countryQueueMap.put(countryMap.Picklist__c, countryMap.QueueApproval__c);
            }
        }


        List<Group> queueApproval = [SELECT Id,Name FROM Group WHERE Type=:'Queue' AND Name IN:countryQueueMap.values()];
        
        for(Group currentQueue : queueApproval)
        {
            QueueNameIdMap.put(currentQueue.Name,currentQueue.Id);
        }

        for(String currentCountry : countryQueueMap.keySet())
        {
            
            countryQueueIdMap.put(currentCountry,QueueNameIdMap.get(countryQueueMap.get(currentCountry)));
        }
        

        List<Case> caseToInsert = new List<Case>();
        for(Order_Note__c currentOrderNote : orderNodeToCreateCase)
        {
            //System.debug(' OwnerId CACountryMap ' + CACountryMap.get(currentOrderNote.ClientAdvisor__c));
            System.debug('countryQueueIdMap: '+countryQueueIdMap);
            System.debug('orderCountryMap: '+orderCountryMap);
            System.debug('currentOrderNote.Order__c: '+currentOrderNote.Order__c);
            
            System.debug(' OwnerId countryQueueIdMap ' + countryQueueIdMap.get(orderCountryMap.get(currentOrderNote.Order__c)));
            
            
            Id caseRecordIdApproval = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Approval').getRecordTypeId();
            
            Case currentCase = new Case();
            currentCase.Approval_Submitter__c = currentOrderNote.ClientAdvisor__c;
            currentCase.Approval_Type__c = currentOrderNote.Type__c;
            currentCase.Subject = 'Approval '+ currentCase.Approval_Type__c;
            currentCase.Order__c = currentOrderNote.Order__c!=null? currentOrderNote.Order__c:ShipppingOrderMap.get(currentOrderNote.Order_Shipping__c);
            currentCase.Order_Shipping__c = currentOrderNote.Order_Shipping__c;
            
            currentCase.OwnerId = countryQueueIdMap.get(OrderCountryMap.get(currentOrderNote.Order__c))!=null?
                                            countryQueueIdMap.get(OrderCountryMap.get(currentOrderNote.Order__c))
                                            :currentOrderNote.ClientAdvisor__c!=null?currentOrderNote.ClientAdvisor__c:UserInfo.getUserId();
            

            currentCase.recordTypeId = caseRecordIdApproval;
            currentCase.AccountId = orderAccountMap.get(currentOrderNote.Order__c)!=null?orderAccountMap.get(currentOrderNote.Order__c):orderAccountMap.get(currentOrderNote.Order_Shipping__C);
            currentCase.ContactId = orderContactMap.get(currentOrderNote.Order__c)!=null?orderContactMap.get(currentOrderNote.Order__c):orderContactMap.get(currentOrderNote.Order_Shipping__C);            
            caseToInsert.add(currentCase);
            
        }
        
        insert caseToInsert;
    }
        
    }
    catch(Exception e)
    {
        System.debug('Case Approval Creation ERROR : ' +e.getMessage());
    }
    
}


}