force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetName>ICX_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolution</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Immediate Response</fullName>
            </value>
            <value>
                <fullName>Request Creation (MyCR - POD - Request)</fullName>
                <label>Request Creation (MyCR - POD - Request - DCS)</label>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Reply to be made by CSC</fullName>
            </value>
            <value>
                <fullName>Reply Made</fullName>
            </value>
            <value>
                <fullName>Request to Store</fullName>
            </value>
            <value>
                <fullName>Transfer to Store</fullName>
            </value>
            <value>
                <fullName>Sent Catalogue_Brochure_TYC_Invitation</fullName>
                <label>Sent Catalogue/ Brochure/ TYC/ Invitation</label>
            </value>
            <value>
                <fullName>Transfer to Headquarters</fullName>
            </value>
            <value>
                <fullName>No Response Required</fullName>
            </value>
            <value>
                <fullName>Book an Appointment</fullName>
            </value>
            <value>
                <fullName>Client Interested or confirmed</fullName>
            </value>
            <value>
                <fullName>Client Reached</fullName>
            </value>
            <value>
                <fullName>Client not interested</fullName>
            </value>
            <value>
                <fullName>Immediate Transaction</fullName>
            </value>
            <value>
                <fullName>Send Mail Card (sample)</fullName>
            </value>
            <value>
                <fullName>Call back another time</fullName>
            </value>
            <value>
                <fullName>Cut Call / Wrong Number</fullName>
            </value>
            <value>
                <fullName>POD with Sku</fullName>
            </value>
            <value>
                <fullName>Send (e-) Business Card</fullName>
            </value>
            <value>
                <fullName>Not available / Voice mail left</fullName>
            </value>
            <value>
                <fullName>Do not disturb / Do not call back</fullName>
            </value>
            <value>
                <fullName>POD without Sku</fullName>
            </value>
            <value>
                <fullName>Wrong number</fullName>
            </value>
            <value>
                <fullName>Operation Exception</fullName>
            </value>
            <value>
                <fullName>Distant Care Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Spam__c.field-meta.xml
<CustomField>
    <fullName>Spam__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Categorized as SPAM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/SpamReason__c.field-meta.xml
<CustomField>
    <fullName>SpamReason__c</fullName>
    <description>[ICONiCS] Reason for spamming the Case</description>
    <label>Spam Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invalid Email</fullName>
            </value>
            <value>
                <fullName>Invalid Subject</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, list all categories for Perso menus.</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/ICX_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Reservation</fullName>
    </customValue>
    <customValue>
        <fullName>Order</fullName>
    </customValue>
    <customValue>
        <fullName>Exchange/Return</fullName>
        <label>Exchange / Return</label>
    </customValue>
    <customValue>
        <fullName>Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Packaging</fullName>
    </customValue>
    <customValue>
        <fullName>Credit note, gift voucher</fullName>
        <label>Credit note / Gift voucher</label>
    </customValue>
    <customValue>
        <fullName>Invoice duplicate</fullName>
    </customValue>
    <customValue>
        <fullName>Tax refund</fullName>
    </customValue>
    <customValue>
        <fullName>Availability</fullName>
    </customValue>
    <customValue>
        <fullName>Price</fullName>
    </customValue>
    <customValue>
        <fullName>Characteristics</fullName>
    </customValue>
    <customValue>
        <fullName>Authentification</fullName>
    </customValue>
    <customValue>
        <fullName>Repair</fullName>
    </customValue>
    <customValue>
        <fullName>Personalization</fullName>
    </customValue>
    <customValue>
        <fullName>Store information</fullName>
    </customValue>
    <customValue>
        <fullName>Horizon assistance</fullName>
    </customValue>
    <customValue>
        <fullName>Website&amp;App</fullName>
    </customValue>
    <customValue>
        <fullName>Head office, Company information, LVMH</fullName>
        <label>Head office / Company information / LVMH</label>
    </customValue>
    <customValue>
        <fullName>Appointment</fullName>
    </customValue>
    <customValue>
        <fullName>Collaboration &amp; Job opportunity</fullName>
    </customValue>
    <customValue>
        <fullName>Product quality</fullName>
    </customValue>
    <customValue>
        <fullName>Service web/CS</fullName>
    </customValue>
    <customValue>
        <fullName>Repair and Care advice</fullName>
    </customValue>
    <customValue>
        <fullName>Service store</fullName>
    </customValue>
    <customValue>
        <fullName>Company, LVMH</fullName>
        <label>Company / LVMH</label>
    </customValue>
    <customValue>
        <fullName>Cosmetovigilance</fullName>
    </customValue>
    <customValue>
        <fullName>Delivery, shipping, packing</fullName>
        <label>Delivery / Shipping / Packing</label>
    </customValue>
    <customValue>
        <fullName>Exhibition</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion show men</fullName>
    </customValue>
    <customValue>
        <fullName>Fashion show women</fullName>
    </customValue>
    <customValue>
        <fullName>Process</fullName>
    </customValue>
    <masterLabel>ICX_Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ICX_Case_SpamButtonController_TEST.cls
@isTest
public class ICX_Case_SpamButtonController_TEST {

    @isTest
    public static void updateCaseTest() {
        Group queue = [SELECT Id FROM Group WHERE Type='Queue' LIMIT 1];

        Case cas = ICX_TestFactory.createCase(null);
        cas.OwnerId = queue.Id;
        insert cas;

        ApexPages.StandardController sc = new ApexPages.StandardController(cas);
        ICX_Case_SpamButtonController ctrl = new ICX_Case_SpamButtonController(sc);

        Test.startTest();
        ctrl.updateCase();
        Test.stopTest();
        
        Case result = [SELECT Spam__c, SpamReason__c FROM Case LIMIT 1];
        System.assertEquals(true, result.Spam__c);
        System.assertEquals('Manual', result.SpamReason__c);
    }

    @isTest
    public static void updateCase_CaseAlreadySpammedTest() {
        Case cas = ICX_TestFactory.createCase(null);
        cas.Spam__c = true;
        insert cas;

        ApexPages.StandardController sc = new ApexPages.StandardController(cas);
        ICX_Case_SpamButtonController ctrl = new ICX_Case_SpamButtonController(sc);

        Test.startTest();
        ctrl.updateCase();
        Test.stopTest();
        
        Case result = [SELECT CreatedDate, LastModifiedDate, Spam__c FROM Case LIMIT 1];
        System.assertEquals(true, result.Spam__c);
        // No change
        //System.assertEquals(result.CreatedDate, result.LastModifiedDate);
    }


    @isTest
    public static void updateCase_CaseClosedTest() {
        Case cas = ICX_TestFactory.createCase(null);
        cas.Resolution__c = 'Immediate Response';
        cas.Type = ICX_CaseDataServiceControllerLC.CASE_TYPE_COMPLAINTS;
        cas.Category__c = 'Process';
        cas.Status = 'Closed';
        insert cas;

        ApexPages.StandardController sc = new ApexPages.StandardController(cas);
        ICX_Case_SpamButtonController ctrl = new ICX_Case_SpamButtonController(sc);

        Test.startTest();
        ctrl.updateCase();
        Test.stopTest();
        
        Case result = [SELECT Spam__c FROM Case LIMIT 1];
        System.assertEquals(false, result.Spam__c);
    }

}