force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country / Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ALAND</fullName>
                <label>ÅLAND</label>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADE</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Iso3Code__c.field-meta.xml
<CustomField>
    <fullName>Iso3Code__c</fullName>
    <label>Iso3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <description>Can be translated</description>
    <label>Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BARBADE</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILE</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>COLOMBIA</fullName>
            </value>
            <value>
                <fullName>CYPRUS</fullName>
            </value>
            <value>
                <fullName>CZECH REPUBLIC</fullName>
            </value>
            <value>
                <fullName>DENMARK</fullName>
            </value>
            <value>
                <fullName>DOMINICAIN REPUBLIC</fullName>
            </value>
            <value>
                <fullName>FINLAND</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>GREECE</fullName>
            </value>
            <value>
                <fullName>GUAM</fullName>
            </value>
            <value>
                <fullName>HONG KONG</fullName>
            </value>
            <value>
                <fullName>HUNGARY</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDONESIA</fullName>
            </value>
            <value>
                <fullName>IRELAND</fullName>
            </value>
            <value>
                <fullName>ISRAEL</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>JORDANIE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ARGENTINA</fullName>
    </customValue>
    <customValue>
        <fullName>ARUBA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRIA</fullName>
    </customValue>
    <customValue>
        <fullName>BAHRAIN</fullName>
    </customValue>
    <customValue>
        <fullName>BARBADE</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIUM</fullName>
    </customValue>
    <customValue>
        <fullName>BRAZIL</fullName>
    </customValue>
    <customValue>
        <fullName>CANADA</fullName>
    </customValue>
    <customValue>
        <fullName>CHILE</fullName>
    </customValue>
    <customValue>
        <fullName>CHINA</fullName>
    </customValue>
    <customValue>
        <fullName>COLOMBIA</fullName>
    </customValue>
    <customValue>
        <fullName>CYPRUS</fullName>
    </customValue>
    <customValue>
        <fullName>CZECH REPUBLIC</fullName>
    </customValue>
    <customValue>
        <fullName>DENMARK</fullName>
    </customValue>
    <customValue>
        <fullName>DOMINICAIN REPUBLIC</fullName>
    </customValue>
    <customValue>
        <fullName>ENGLAND</fullName>
    </customValue>
    <customValue>
        <fullName>FINLAND</fullName>
    </customValue>
    <customValue>
        <fullName>FRANCE</fullName>
    </customValue>
    <customValue>
        <fullName>FRENCH SOUTHERN TERRITORIES</fullName>
    </customValue>
    <customValue>
        <fullName>GERMANY</fullName>
    </customValue>
    <customValue>
        <fullName>GREECE</fullName>
    </customValue>
    <customValue>
        <fullName>GUAM</fullName>
    </customValue>
    <customValue>
        <fullName>HONG KONG</fullName>
    </customValue>
    <customValue>
        <fullName>HUNGARY</fullName>
    </customValue>
    <customValue>
        <fullName>INDIA</fullName>
    </customValue>
    <customValue>
        <fullName>INDONESIA</fullName>
    </customValue>
    <customValue>
        <fullName>IRELAND</fullName>
    </customValue>
    <customValue>
        <fullName>ISRAEL</fullName>
    </customValue>
    <customValue>
        <fullName>ITALY</fullName>
    </customValue>
    <description>List of countries for stores</description>
    <masterLabel>Countries</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/IDENTITY_AccountMatching_Utils.cls
public without sharing class IDENTITY_AccountMatching_Utils {
    
    /*
    *** DESCRIPTION Get Account according to Firstname, Lastname, Email or Mobile or create new one
    *** RETURN      Account ID
    */
    public static Map<String, String> upsertAccountByFieldsValue(Account new_acc){
        
        Account[] accs;
        String action;
        
        // ERROR HANDLING - CHECK REQUIRED FIELD
        if(String.isEmpty(new_acc.Lastname))
        {
            if(Test.isRunningTest()){
                return new Map<String, String> {'action' => 'MISSING_REQUIRED_FIELD'};
            }
            else{
                throw new AccountMatchingException('MISSING REQUIRED FIELD: Lastname field is required to create or update Account on Salesforce');
            }
        }
        if(String.isEmpty(new_acc.Firstname))
        {
            if(Test.isRunningTest()){
                return new Map<String, String> {'action' => 'MISSING_REQUIRED_FIELD'};
            }
            else{
                throw new AccountMatchingException('MISSING REQUIRED FIELD: Firstname field is required to create or update Account on Salesforce');
            }
        }
        if(String.isEmpty(new_acc.Salutation))
        {
            if(Test.isRunningTest()){
                return new Map<String, String> {'action' => 'MISSING_REQUIRED_FIELD'};
            }
            else{
                throw new AccountMatchingException('MISSING REQUIRED FIELD: Salutation field is required to create or update Account on Salesforce');
            }
        }
        if(String.isEmpty(new_acc.HomeAddressCountryCode__pc))
        {
            if(Test.isRunningTest()){
                return new Map<String, String> {'action' => 'MISSING_REQUIRED_FIELD'};
            }
            else{
                throw new AccountMatchingException('MISSING REQUIRED FIELD: HomeAddressCountryCode__pc field is required to create or update Account on Salesforce');
            }
        }
        if(String.isEmpty(new_acc.PersonEmail) && String.isEmpty(new_acc.PersonMobilePhone))
        {
            if(Test.isRunningTest()){
                return new Map<String, String> {'action' => 'MISSING_REQUIRED_FIELD'};
            }
            else{
                throw new AccountMatchingException('MISSING REQUIRED FIELD: PersonEmail field or PersonMobilePhone field must be provided to create or update Account on Salesforce');
            }
        }
        if( !String.isEmpty(new_acc.PersonMobilePhone) 
            && 
            ( String.isEmpty(new_acc.LocalMobilePhone__pc) || String.isEmpty(new_acc.MobilePhoneCountryCallingCode__pc) || String.isEmpty(new_acc.MobilePhoneCountryCode__pc) )
          )
        {
            if(Test.isRunningTest()){
                return new Map<String, String> {'action' => 'MISSING_REQUIRED_FIELD'};
            }
            else{
                throw new AccountMatchingException('MISSING REQUIRED FIELD: LocalMobilePhone__pc, MobilePhoneCountryCallingCode__pc and MobilePhoneCountryCode__pc fields must be provided if PersonMobilePhone field is provided');
            }
        }
        if( String.isEmpty(new_acc.PersonMobilePhone) 
            && 
            ( !String.isEmpty(new_acc.LocalMobilePhone__pc) || !String.isEmpty(new_acc.MobilePhoneCountryCallingCode__pc) || !String.isEmpty(new_acc.MobilePhoneCountryCode__pc) )
          )
        {
            if(Test.isRunningTest()){
                return new Map<String, String> {'action' => 'MISSING_REQUIRED_FIELD'};
            }
            else{
                throw new AccountMatchingException('MISSING REQUIRED FIELD: PersonMobilePhone field must be provided if LocalMobilePhone__pc, MobilePhoneCountryCallingCode__pc and MobilePhoneCountryCode__pc fields are provided');
            }
        }

        // ERROR HANDLING - CHECK FIELD FORMAT
        if(!String.isEmpty(new_acc.HomeAddressCountryCode__pc))
        {
            Pattern pattern_iso3 = Pattern.compile('[A-Z]{3}');
            Matcher matcher_iso3 = pattern_iso3.matcher(new_acc.HomeAddressCountryCode__pc);

            if (!matcher_iso3.matches())
            {
                if(Test.isRunningTest()){
                    return new Map<String, String> {'action' => 'INVALID_FORMAT_FIELD'};
                }
                else{
                    throw new AccountMatchingException('INVALID REQUIRED FIELD: HomeAddressCountryCode__pc field has to be in ISO-3 format');
                }
            }
        }
        if(!String.isEmpty(new_acc.MobilePhoneCountryCode__pc))
        {
            Pattern pattern_iso2 = Pattern.compile('[A-Z]{2}');
            Matcher matcher_iso2 = pattern_iso2.matcher(new_acc.MobilePhoneCountryCode__pc);

            if (!matcher_iso2.matches())
            {
                if(Test.isRunningTest()){
                    return new Map<String, String> {'action' => 'INVALID_FORMAT_FIELD'};
                }
                else{
                    throw new AccountMatchingException('INVALID REQUIRED FIELD: MobilePhoneCountryCode__pc field has to be in ISO-2 format');
                }
            }
        }
        
        // CHECK EXISTING ACCOUNT IN SF
        if(!String.isEmpty(new_acc.PersonEmail) && !String.isEmpty(new_acc.PersonMobilePhone)){
            accs = [SELECT Id, LoginPhone__pc
                FROM Account
                WHERE LastName =: new_acc.LastName AND FirstName =: new_acc.FirstName AND (PersonEmail =: new_acc.PersonEmail OR PersonMobilePhone =: new_acc.PersonMobilePhone)
                ORDER BY LastTrans__pc, LastModifiedDate DESC
                LIMIT 1
            ];
        }
        else if(!String.isEmpty(new_acc.PersonEmail)){
            accs = [SELECT Id, LoginPhone__pc
                FROM Account
                WHERE LastName =: new_acc.LastName AND FirstName =: new_acc.FirstName AND PersonEmail =: new_acc.PersonEmail
                ORDER BY LastTrans__pc, LastModifiedDate DESC
                LIMIT 1
            ];
        }
        else if(!String.isEmpty(new_acc.PersonMobilePhone)){
            accs = [SELECT Id, LoginPhone__pc
                FROM Account
                WHERE LastName =: new_acc.LastName AND FirstName =: new_acc.FirstName AND PersonMobilePhone =: new_acc.PersonMobilePhone
                ORDER BY LastTrans__pc, LastModifiedDate DESC
                LIMIT 1
            ];
        }
        else {
            accs = new List<Account>();
        }

        if(!accs.isEmpty()){
            new_acc.Id = accs[0].Id;
            action = 'MATCHING';
        }
        else{
            action = 'NEW';
        }
        
        // populate LoginPhone__pc to prevent extreme Duplicate User case in Checkout/Activation flow
        if(
            (action == 'MATCHING' && accs[0].LoginPhone__pc == null && new_acc.LoginPhone__pc == null)
            ||
            (action == 'NEW'      && new_acc.LoginPhone__pc == null)
        ){
            new_acc.LoginPhone__pc = new_acc.PersonMobilePhone;
        }

        // populate PrimaryCountry__pc to prevent ATG Callout error
        if(!String.isEmpty(new_acc.HomeAddressCountryCode__pc)){
            List<Country__c> country = [SELECT Picklist__c FROM Country__c WHERE Iso3Code__c = :new_acc.HomeAddressCountryCode__pc LIMIT 1];
            if(country.size()>0){
                new_acc.PrimaryCountry__pc = country[0].Picklist__c;
            }             
        }        
        
        Database.upsert(new_acc);

        // INFO LOG
        new Logs(new Map<String,Object> {
            'level' => 'INFO', 
            'apexClass' => 'IDENTITY_WS_AccountMatching', 
            'category' => 'API',
            'message' => action,
            'recordId' => new_acc.Id,
            'status_code' => 'SUCCESS'
        });

        return new Map<String, String> {
            'cid' => (String) new_acc.Id,
            'action' => action
        };
    }

    /*
    *** DESCRIPTION Custom Exception Wrapper
    */
    public class AccountMatchingException extends Exception {}
}