force-app/main/default/objects/Brand_Experience__c/Brand_Experience__c.object-meta.xml
<CustomObject>
    <description>Object to create Brand Experiences. Parent object of Experience Variation (Brand_Experience_Variation__c)</description>
    <label>Events &amp; Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Experience</description>
    <inlineHelpText>Calculated based on child Variations statuses</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Partially Ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
                <isActive>false</isActive>
                <label>Published</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-experience/main/default/objects/Brand_Experience__c/recordTypes/Experience.recordType-meta.xml
<RecordType>
    <fullName>Experience</fullName>
    <active>true</active>
    <description>used to create Experiences</description>
    <label>In-Store Animation</label>
</RecordType>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/Brand_Experience_Store_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Events &amp; Experiences Store Hierarchy</label>
    <nameField>
        <label>Events &amp; Experiences Store Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences Store Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/fields/Brand_Experience__c.field-meta.xml
<CustomField>
    <fullName>Brand_Experience__c</fullName>
    <label>Events &amp; Experience</label>
    <referenceTo>Brand_Experience__c</referenceTo>
    <relationshipLabel>Events &amp; Experiences Store Hierarchies</relationshipLabel>
    <relationshipName>Events_Experiences_Store_Hierarchies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Events &amp; Experiences Store Hierarchies</relationshipLabel>
    <relationshipName>Events_Experiences_Store_Hierarchies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/Brand_Experience_Variation__c.object-meta.xml
<CustomObject>
    <description>Object to create variations of Brand Experiences (Digital Events, Physical Events, Content, Exclusive Offers, ...)
Child object of Experience (Brand_Experience__c). Parent object of Experience Variation Member (Brand_Experience_Variation_Member__c).</description>
    <label>Event &amp; Experience Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event &amp; Experience Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/Brand_Experience__c.field-meta.xml
<CustomField>
    <fullName>Brand_Experience__c</fullName>
    <description>Experience associated with the Experience Variation</description>
    <label>Event &amp; Experience</label>
    <referenceTo>Brand_Experience__c</referenceTo>
    <relationshipLabel>Event &amp; Experience Activations</relationshipLabel>
    <relationshipName>Brand_Experience_Variations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <description>Date &amp; Time at which Brand Experience Variation ends (GMT+02)</description>
    <label>End Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/Nb_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Nb_Appointment__c</fullName>
    <label>Appointments</label>
    <summarizedField>Brand_Experience_Variation_Member__c.Nb_Appointment__c</summarizedField>
    <summaryForeignKey>Brand_Experience_Variation_Member__c.Brand_Experience_Variation__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/Nb_Target_Clients__c.field-meta.xml
<CustomField>
    <fullName>Nb_Target_Clients__c</fullName>
    <label>Clients Target Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <description>Date &amp; Time at which Experience Variation starts</description>
    <inlineHelpText>Variation status changes to &quot;Participation Opened&quot; at Start Date &amp; Time</inlineHelpText>
    <label>Start Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Brand Experience Variation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>Published</label>
            </value>
            <value>
                <fullName>Preview</fullName>
                <label>Member Preview</label>
            </value>
            <value>
                <fullName>Registration Opened</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Selection Opened</fullName>
            </value>
            <value>
                <fullName>Selection Closed</fullName>
            </value>
            <value>
                <fullName>Participation Opened</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>Experience_Variations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Variation__c/recordTypes/Physical_Event.recordType-meta.xml
<RecordType>
    <fullName>Physical_Event</fullName>
    <active>true</active>
    <description>for Physical Events</description>
    <label>In Store Event</label>
</RecordType>

force-experience/main/default/objects/Brand_Experience_Variation_Member__c/Brand_Experience_Variation_Member__c.object-meta.xml
<CustomObject>
    <label>Event &amp; Experience Activation Member</label>
    <nameField>
        <label>Experience Activation Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event &amp; Experience Activation Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/Assigned_CA__c.field-meta.xml
<CustomField>
    <fullName>Assigned_CA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned CA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Experience_Variation_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/Brand_Experience_Variation__c.field-meta.xml
<CustomField>
    <fullName>Brand_Experience_Variation__c</fullName>
    <description>Experience Variation Identifier</description>
    <label>Activation</label>
    <referenceTo>Brand_Experience_Variation__c</referenceTo>
    <relationshipLabel>Event &amp; Experience Activation Members</relationshipLabel>
    <relationshipName>Brand_Experience_Variation_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client Identifier</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Brand_Experience_Variation_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/GuestNumber__c.field-meta.xml
<CustomField>
    <fullName>GuestNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Variation_Member__c/fields/Nb_Appointment__c.field-meta.xml
<CustomField>
    <fullName>Nb_Appointment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Appointments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Variation_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Experience Member</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Not Registered</fullName>
            </value>
            <value>
                <fullName>To Contact</fullName>
            </value>
            <value>
                <fullName>Removed Manually</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Not Participated</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Not Selected</fullName>
                <isActive>false</isActive>
                <label>Not Selected</label>
            </value>
            <value>
                <fullName>Selected</fullName>
                <isActive>false</isActive>
                <label>Selected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/User/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-experience/main/default/classes/test/Ex_nomination_kpi_controller_TEST.cls
@isTest
public class Ex_nomination_kpi_controller_TEST {
    @TestSetup
    static void setupTestData(){   
        Profile iconProfile = [SELECT Id FROM Profile WHERE Name = 'ICON_SA' LIMIT 1];
        
        User testUser = new User(
            MANAGEMENT_ZONE_LEVEL__c = 'abc',
            profile = iconProfile,
            profileId = iconProfile.Id,
            LastName = 'LV user',
            Alias = 'lvUser',
            Email = 'icon.user@louisvuitton.com.test123',
            TimeZoneSidKey = 'Europe/Paris',
            LocaleSidKey = 'en_US',
            Username = 'icon.user@louisvuitton.com.test123',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            IsActive = True
        );
        insert testUser;
        System.runAs(testUser) {
            Id experienceRT = Schema.SObjectType.Brand_Experience__c.getRecordTypeInfosByDeveloperName().get('Experience').getRecordTypeId();
            Id inStoreRT = Schema.SObjectType.Brand_Experience_Variation__c.getRecordTypeInfosByDeveloperName().get('Physical_Event').getRecordTypeId();

            Brand_Experience__c experience = new Brand_Experience__c(
                recordTypeId = experienceRT,
                Name = 'test',
                Status__c = 'Ongoing'
            );
            insert experience;
    
            Store__c store = new Store__c(Name = 'test', RetailStoreId__c = '123', MANAGEMENT_ZONE_LEVEL__c = 'abc');
            insert store;
    
            Brand_Experience_Store_Hierarchy__c storeHierarchy = new Brand_Experience_Store_Hierarchy__c(Store__c = store.Id, Brand_Experience__c = experience.Id);
            insert storeHierarchy;

            Brand_Experience_Variation__c variation = new Brand_Experience_Variation__c (recordTypeId=inStoreRT, Brand_Experience__c = experience.Id, Name = 'test variation', Store__c=store.Id, Nb_Target_Clients__c = 15, StartDateTime__c = Datetime.now(), EndDateTime__c = Datetime.now().addDays(30));
            insert variation;

            Account acc = IC_TestFactory.createAccount();
            insert acc;

            Account acc2 = IC_TestFactory.createAccount();
            insert acc2;
            List<Brand_Experience_Variation_Member__c> members = new List<Brand_Experience_Variation_Member__c>{ new Brand_Experience_Variation_Member__c (Brand_Experience_Variation__c = variation.Id, GuestNumber__c=2, Nb_Appointment__c=3, client__c = acc.Id, Assigned_CA__c=testUser.Id),
                                                                                                                    new Brand_Experience_Variation_Member__c (Brand_Experience_Variation__c = variation.Id, GuestNumber__c=1, Nb_Appointment__c=1, client__c = acc2.Id, Assigned_CA__c=testUser.Id) };
            insert members;      
        }                                                                         

    }
    @isTest
    static void variationTest() {

        User testUser = [SELECT Id FROM user WHERE Username = 'icon.user@louisvuitton.com.test123'];
        Brand_Experience_Variation__c variation = [SELECT Id FROM Brand_Experience_Variation__c limit 1];

        System.runAs(testUser) {
            
            Test.startTest();
            Map<String,Integer> KPIs =  Ex_nomination_kpi_controller.getKPIValues(variation.Id, 'Brand_Experience_Variation__c', new List<String> {'NOMINATED_CLIENT','CONFIRMED_CLIENT', 'APPOINTMENTS_FIELD', 'GUESTS_FIELD'});
            Test.stopTest();
            System.assertEquals(0,KPIs.get('NOMINATED_CLIENT'));
            System.assertEquals(0,KPIs.get('CONFIRMED_CLIENT'));
            System.assertEquals(3,KPIs.get('GUESTS_FIELD'));
            System.assertEquals(4,KPIs.get('APPOINTMENTS_FIELD'));



        }
    }
    @isTest
    static void experienceTest() {

        User testUser = [SELECT Id FROM user WHERE Username = 'icon.user@louisvuitton.com.test123'];

        Brand_Experience__c experience = [SELECT Id FROM Brand_Experience__c limit 1];

        System.runAs(testUser) {
            
            Test.startTest();
            Map<String,Integer> KPIs =  Ex_nomination_kpi_controller.getKPIValues(experience.Id, 'Brand_Experience__c', new List<String> {'GLOBAL_TARGET_CLIENT','GLOBAL_NOMINATED_CLIENT', 'GLOBAL_CONFIRMED_CLIENT', 'GLOBAL_APPOINTMENTS', 'GLOBAL_GUESTS'});
            Test.stopTest();
            System.assertEquals(15,KPIs.get('GLOBAL_TARGET_CLIENT'));
            System.assertEquals(0,KPIs.get('GLOBAL_NOMINATED_CLIENT'));
            System.assertEquals(0,KPIs.get('GLOBAL_CONFIRMED_CLIENT'));
            System.assertEquals(3,KPIs.get('GLOBAL_GUESTS'));
            System.assertEquals(4,KPIs.get('GLOBAL_APPOINTMENTS'));

        }
    }
}