force-app/main/default/objects/Brand_Experience__c/Brand_Experience__c.object-meta.xml
<CustomObject>
    <description>Object to create Brand Experiences. Parent object of Experience Variation (Brand_Experience_Variation__c)</description>
    <label>Events &amp; Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience__c/fields/ClubName__c.field-meta.xml
<CustomField>
    <fullName>ClubName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Club associated with the Experience</description>
    <label>Club</label>
    <referenceTo>Club_and_Seasons__c</referenceTo>
    <relationshipName>Brand_Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Experience__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Experience</description>
    <inlineHelpText>Calculated based on child Variations statuses</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Partially Ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
                <isActive>false</isActive>
                <label>Published</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/Brand_Experience_Store_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Events &amp; Experiences Store Hierarchy</label>
    <nameField>
        <label>Events &amp; Experiences Store Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences Store Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/fields/Brand_Experience__c.field-meta.xml
<CustomField>
    <fullName>Brand_Experience__c</fullName>
    <label>Events &amp; Experience</label>
    <referenceTo>Brand_Experience__c</referenceTo>
    <relationshipLabel>Events &amp; Experiences Store Hierarchies</relationshipLabel>
    <relationshipName>Events_Experiences_Store_Hierarchies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Events &amp; Experiences Store Hierarchies</relationshipLabel>
    <relationshipName>Events_Experiences_Store_Hierarchies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/MGMT_ZONE_SUB_LEVEL2__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL2__c</fullName>
    <description>Contains the code/translation for the second sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MGMT_ZONE_SUB_LEVEL1__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>179</fullName>
            </value>
            <value>
                <fullName>219</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>259</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>299</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>379</fullName>
            </value>
            <value>
                <fullName>39</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>41</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
            <value>
                <fullName>43</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>49</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>51</fullName>
            </value>
            <value>
                <fullName>53</fullName>
            </value>
            <value>
                <fullName>54</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/MGMT_ZONE_SUB_LEVEL3__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL3__c</fullName>
    <description>Contains the code/translation for the third sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MGMT_ZONE_SUB_LEVEL2__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>1016</fullName>
            </value>
            <value>
                <fullName>108</fullName>
            </value>
            <value>
                <fullName>109</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>112</fullName>
            </value>
            <value>
                <fullName>113</fullName>
            </value>
            <value>
                <fullName>114</fullName>
            </value>
            <value>
                <fullName>115</fullName>
            </value>
            <value>
                <fullName>116</fullName>
            </value>
            <value>
                <fullName>117</fullName>
            </value>
            <value>
                <fullName>1176</fullName>
            </value>
            <value>
                <fullName>118</fullName>
            </value>
            <value>
                <fullName>119</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>121</fullName>
            </value>
            <value>
                <fullName>122</fullName>
            </value>
            <value>
                <fullName>123</fullName>
            </value>
            <value>
                <fullName>124</fullName>
            </value>
            <value>
                <fullName>125</fullName>
            </value>
            <value>
                <fullName>126</fullName>
            </value>
            <value>
                <fullName>127</fullName>
            </value>
            <value>
                <fullName>128</fullName>
            </value>
            <value>
                <fullName>129</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>131</fullName>
            </value>
            <value>
                <fullName>133</fullName>
            </value>
            <value>
                <fullName>138</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/User/fields/MGMT_ZONE_SUB_LEVEL3__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL3__c</fullName>
    <description>Contains the code/translation for the third sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MGMT_ZONE_SUB_LEVEL2__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10056</fullName>
            </value>
            <value>
                <fullName>1016</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>10216</fullName>
            </value>
            <value>
                <fullName>10296</fullName>
            </value>
            <value>
                <fullName>103</fullName>
            </value>
            <value>
                <fullName>10616</fullName>
            </value>
            <value>
                <fullName>10856</fullName>
            </value>
            <value>
                <fullName>109</fullName>
            </value>
            <value>
                <fullName>10936</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>11016</fullName>
            </value>
            <value>
                <fullName>11176</fullName>
            </value>
            <value>
                <fullName>112</fullName>
            </value>
            <value>
                <fullName>11256</fullName>
            </value>
            <value>
                <fullName>113</fullName>
            </value>
            <value>
                <fullName>11336</fullName>
            </value>
            <value>
                <fullName>11416</fullName>
            </value>
            <value>
                <fullName>116</fullName>
            </value>
            <value>
                <fullName>11656</fullName>
            </value>
            <value>
                <fullName>11736</fullName>
            </value>
            <value>
                <fullName>1176</fullName>
            </value>
            <value>
                <fullName>118</fullName>
            </value>
            <value>
                <fullName>11896</fullName>
            </value>
            <value>
                <fullName>119</fullName>
            </value>
            <value>
                <fullName>11976</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>12056</fullName>
            </value>
            <value>
                <fullName>121</fullName>
            </value>
            <value>
                <fullName>123</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-experience/main/default/classes/ex_Event_ListView_Controller_Test.cls
@isTest
public with sharing class ex_Event_ListView_Controller_Test {
    
    @TestSetup
    static void setupTestData() {
        Profile LVProfile = [SELECT Id FROM Profile WHERE Name = 'LV_Club' LIMIT 1];
        User mockUser = new User(
            DefaultStore__c = '123',
            MGMT_ZONE_SUB_LEVEL3__c = 'abc',
            profile = LVProfile,
            ProfileId = LVProfile.Id,
            LastName = 'LV user',
            Alias = 'lvUser',
            Email = 'icon.user@louisvuitton.com.123',
            TimeZoneSidKey = 'Europe/Paris',
            LocaleSidKey = 'en_US',
            Username = 'icon.user@louisvuitton.com.icon',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            IsActive = True
        );
        insert mockUser;
        
        User mockUser1 = new User(
            MGMT_ZONE_SUB_LEVEL3__c = 'abc',
            profile = LVProfile,
            ProfileId = LVProfile.Id,
            LastName = 'LV user',
            Alias = 'lvUser',
            Email = 'icon.user1@louisvuitton.com.123',
            TimeZoneSidKey = 'Europe/Paris',
            LocaleSidKey = 'en_US',
            Username = 'icon.user1@louisvuitton.com.icon',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            IsActive = True
        );
        insert mockUser1;

        Club_and_Seasons__c clubSneakers = new Club_and_Seasons__c(
            Name = 'Sneakers'
        );
        insert clubSneakers;
        
        Brand_Experience__c ex = new Brand_Experience__c(
            Name = 'test',
            Status__c = 'Ongoing',
            ClubName__c = clubSneakers.Id
        );
        insert ex;
        Store__c store = new Store__c(Name = 'test', RetailStoreId__c = '123');
		insert store;

        Brand_Experience_Store_Hierarchy__c storeHierarchy = new Brand_Experience_Store_Hierarchy__c(Store__c = store.Id, Brand_Experience__c = ex.Id);
    }
    @isTest
    static void testGetStoreHierarchiesEvents_DefaultStore() {
        
        User testUser = [SELECT Id, MGMT_ZONE_SUB_LEVEL2__c, MGMT_ZONE_SUB_LEVEL3__c, DefaultStore__c FROM User WHERE Username = 'icon.user@louisvuitton.com.icon'];
        System.runAs(testUser) {
            Test.startTest();
            List<Brand_Experience__c> experiences = ex_Event_ListView_Controller.getStoreHierarchiesEvents();
            Test.stopTest();
        }
    }
    @isTest
    static void testGetStoreHierarchiesEvents_SubLevel3() {
        
        User testUser = [SELECT Id, MGMT_ZONE_SUB_LEVEL3__c FROM User WHERE Username = 'icon.user1@louisvuitton.com.icon'];
        System.runAs(testUser) {
            Test.startTest();
            List<Brand_Experience__c> experiences = ex_Event_ListView_Controller.getStoreHierarchiesEvents();
            Test.stopTest();
        }
    }
    @isTest
    static void testGetStoreHierarchiesEvents_SubLevel2() {
        
        User testUser = [SELECT Id, MGMT_ZONE_SUB_LEVEL2__c, MGMT_ZONE_SUB_LEVEL3__c FROM User WHERE Username = 'icon.user1@louisvuitton.com.icon'];
        testUser.MGMT_ZONE_SUB_LEVEL3__c=null;
        testUser.MGMT_ZONE_SUB_LEVEL2__c='abc';
		update testUser;
        System.runAs(testUser) {
            Test.startTest();
            List<Brand_Experience__c> experiences = ex_Event_ListView_Controller.getStoreHierarchiesEvents();
            Test.stopTest();
        }
    }
    
     @isTest
    static void testGetStoreHierarchiesEvents_SubLevel1() {
        
        User testUser = [SELECT Id, MGMT_ZONE_SUB_LEVEL1__c, MGMT_ZONE_SUB_LEVEL2__c FROM User WHERE Username = 'icon.user1@louisvuitton.com.icon'];
        testUser.MGMT_ZONE_SUB_LEVEL3__c=null;
        testUser.MGMT_ZONE_SUB_LEVEL2__c=null;
        testUser.MGMT_ZONE_SUB_LEVEL1__c='abc';
		update testUser;
        System.runAs(testUser) {
            Test.startTest();
            List<Brand_Experience__c> experiences = ex_Event_ListView_Controller.getStoreHierarchiesEvents();
            Test.stopTest();
        }
    }
    
    @isTest
    static void testGetStoreHierarchiesEvents_SubLevel() {
        
        User testUser = [SELECT Id, MGMT_ZONE_SUB_LEVEL1__c, MANAGEMENT_ZONE_LEVEL__c FROM User WHERE Username = 'icon.user1@louisvuitton.com.icon'];
        testUser.MGMT_ZONE_SUB_LEVEL3__c=null;
        testUser.MGMT_ZONE_SUB_LEVEL2__c=null;
        testUser.MGMT_ZONE_SUB_LEVEL1__c=null;
        testUser.MANAGEMENT_ZONE_LEVEL__c='abc';
		update testUser;
        System.runAs(testUser) {
            Test.startTest();
            List<Brand_Experience__c> experiences = ex_Event_ListView_Controller.getStoreHierarchiesEvents();
            Test.stopTest();
        }
    }
    @isTest
    static void testGetStoreHierarchiesEvents_noLevel() {
        
        User testUser = [SELECT Id, MGMT_ZONE_SUB_LEVEL3__c, MGMT_ZONE_SUB_LEVEL2__c, MGMT_ZONE_SUB_LEVEL1__c, MANAGEMENT_ZONE_LEVEL__c FROM User WHERE Username = 'icon.user1@louisvuitton.com.icon'];
        testUser.MGMT_ZONE_SUB_LEVEL3__c=null;
        testUser.MGMT_ZONE_SUB_LEVEL2__c=null;
        testUser.MGMT_ZONE_SUB_LEVEL1__c=null;
        testUser.MANAGEMENT_ZONE_LEVEL__c=null;
		update testUser;
        System.runAs(testUser) {
            Test.startTest();
            List<Brand_Experience__c> experiences = ex_Event_ListView_Controller.getStoreHierarchiesEvents();
            Test.stopTest();
        }
    }
}