force-app/main/default/objects/Brand_Experience__c/Brand_Experience__c.object-meta.xml
<CustomObject>
    <description>Object to create Brand Experiences. Parent object of Experience Variation (Brand_Experience_Variation__c)</description>
    <label>Events &amp; Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Experience</description>
    <inlineHelpText>Calculated based on child Variations statuses</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Partially Ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
                <isActive>false</isActive>
                <label>Published</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-experience/main/default/objects/Brand_Experience__c/recordTypes/Experience.recordType-meta.xml
<RecordType>
    <fullName>Experience</fullName>
    <active>true</active>
    <description>used to create Experiences</description>
    <label>In-Store Animation</label>
</RecordType>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/Brand_Experience_Store_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Events &amp; Experiences Store Hierarchy</label>
    <nameField>
        <label>Events &amp; Experiences Store Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences Store Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Events &amp; Experiences Store Hierarchies</relationshipLabel>
    <relationshipName>Events_Experiences_Store_Hierarchies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/MANAGEMENT_ZONE_LEVEL_TECH__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL_TECH__c</fullName>
    <description>Contains the label for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL TECH</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/MGMT_ZONE_SUB_LEVEL1__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL1__c</fullName>
    <description>Contains the code/translation for the first sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MANAGEMENT_ZONE_LEVEL__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>1071</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>151</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/MGMT_ZONE_SUB_LEVEL1_TECH__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL1_TECH__c</fullName>
    <description>Contains the label for the first sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL1 TECH</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/MGMT_ZONE_SUB_LEVEL2__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL2__c</fullName>
    <description>Contains the code/translation for the second sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MGMT_ZONE_SUB_LEVEL1__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>179</fullName>
            </value>
            <value>
                <fullName>219</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>259</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>299</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>379</fullName>
            </value>
            <value>
                <fullName>39</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>41</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
            <value>
                <fullName>43</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>49</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>51</fullName>
            </value>
            <value>
                <fullName>53</fullName>
            </value>
            <value>
                <fullName>54</fullName>
            </value>
            <value>
                <fullName>68</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/MGMT_ZONE_SUB_LEVEL2_TECH__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL2_TECH__c</fullName>
    <description>Contains the label for the second sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL2 TECH</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/MGMT_ZONE_SUB_LEVEL3_TECH__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL3_TECH__c</fullName>
    <description>Contains the label for the third sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL3 TECH</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/StoreType__c.field-meta.xml
<CustomField>
    <fullName>StoreType__c</fullName>
    <description>Indicate which type of store it is</description>
    <label>Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>WEB</fullName>
            </value>
            <value>
                <fullName>CSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-experience/main/default/classes/test/Experience_Store_Hierarchy_Ctrl_Test.cls
@isTest
private class Experience_Store_Hierarchy_Ctrl_Test {

    @testSetup
    static void setup() {
        List<Store__c> testStores = new List<Store__c>();
        testStores.add(New Store__c(Name = 'test1', RetailStoreId__c = 'AA11', StoreType__c='Store', Status__c='Opening Soon', MANAGEMENT_ZONE_LEVEL_TECH__c='3', MANAGEMENT_ZONE_LEVEL__c='AMERICAS', MGMT_ZONE_SUB_LEVEL1_TECH__c='151', MGMT_ZONE_SUB_LEVEL1__c ='USA', MGMT_ZONE_SUB_LEVEL2_TECH__c='68', MGMT_ZONE_SUB_LEVEL2__c='WEST COAST', MGMT_ZONE_SUB_LEVEL3_TECH__c='1576', MGMT_ZONE_SUB_LEVEL3__c='OON WESTERN'));
        testStores.add(New Store__c(Name = 'test2', RetailStoreId__c = 'AA22', StoreType__c='CSC', Status__c='Opening Soon', MANAGEMENT_ZONE_LEVEL_TECH__c='15', MANAGEMENT_ZONE_LEVEL__c='EMEA', MGMT_ZONE_SUB_LEVEL1_TECH__c='32', MGMT_ZONE_SUB_LEVEL1__c ='EUROPE SOUTH', MGMT_ZONE_SUB_LEVEL2_TECH__c='24', MGMT_ZONE_SUB_LEVEL2__c='ITALY', MGMT_ZONE_SUB_LEVEL3_TECH__c='351', MGMT_ZONE_SUB_LEVEL3__c='ITALY'));
        testStores.add(New Store__c(Name = 'test3', RetailStoreId__c = 'BB33', StoreType__c='Store', Status__c='Open', MANAGEMENT_ZONE_LEVEL_TECH__c='15', MANAGEMENT_ZONE_LEVEL__c='EMEA', MGMT_ZONE_SUB_LEVEL1_TECH__c='31', MGMT_ZONE_SUB_LEVEL1__c ='EUROPE NORTH', MGMT_ZONE_SUB_LEVEL2_TECH__c='17', MGMT_ZONE_SUB_LEVEL2__c='EASTERN EUROPE', MGMT_ZONE_SUB_LEVEL3_TECH__c='284', MGMT_ZONE_SUB_LEVEL3__c='POLAND'));
        testStores.add(New Store__c(Name = 'test4', RetailStoreId__c = 'BB44', StoreType__c='CSC', Status__c='Open', MANAGEMENT_ZONE_LEVEL_TECH__c='14', MANAGEMENT_ZONE_LEVEL__c='ASIA SOUTH', MGMT_ZONE_SUB_LEVEL1_TECH__c='1351', MGMT_ZONE_SUB_LEVEL1__c ='SE ASIA', MGMT_ZONE_SUB_LEVEL2_TECH__c='289', MGMT_ZONE_SUB_LEVEL2__c='SINGAPORE', MGMT_ZONE_SUB_LEVEL3_TECH__c='1566', MGMT_ZONE_SUB_LEVEL3__c='POP UP SINGAPORE'));

        insert testStores;
        
        Club_and_Seasons__c clubSneakers = new Club_and_Seasons__c(
            Name = 'Sneakers'
        );
        insert clubSneakers;
        
        Id ExperienceRecordType = Schema.SObjectType.Brand_Experience__c.getRecordTypeInfosByDeveloperName().get('Experience').getRecordTypeId();
        Brand_Experience__c ex = new Brand_Experience__c(
            RecordTypeId=ExperienceRecordType,
            Name = 'test',
            Status__c = 'Ongoing',
            ClubName__c = clubSneakers.Id
        );
        insert ex;
        
        Brand_Experience_Store_Hierarchy__c storeHierarchyRecord = new Brand_Experience_Store_Hierarchy__c(Store__c = testStores[0].Id, Brand_Experience__c=ex.Id);
    	insert storeHierarchyRecord;
    }
    @isTest
    static void testGetManagementZoneLevel() {
        Test.startTest();
        List<AggregateResult> result = Experience_Store_Hierarchy_Ctrl.getManagementZoneLevel();
        Test.stopTest();

        System.assertEquals(3, result.size(), 'Expected 3 aggregate results');
    }

    @isTest
    static void testGetManagementZoneSubLevel1() {
        List<String> selectedLevelTech = new List<String>{ '3', '14', '15'};
        Test.startTest();
        List<AggregateResult> result = Experience_Store_Hierarchy_Ctrl.getManagementZoneSubLevel1(selectedLevelTech);
        Test.stopTest();

        System.assertEquals(4, result.size(), 'Expected 4 aggregate result');
    }

    @isTest
    static void testGetManagementZoneSubLevel2() {
        List<String> selectedSubLevel1Tech = new List<String>{ '31', '32', '151', '1351' };
        Test.startTest();
        List<AggregateResult> result = Experience_Store_Hierarchy_Ctrl.getManagementZoneSubLevel2(selectedSubLevel1Tech);
        Test.stopTest();

        System.assertEquals(4, result.size(), 'Expected 4 aggregate result');
    }

    @isTest
    static void testGetManagementZoneSubLevel3() {
        
        List<String> selectedSubLevel2Tech = new List<String>{ '17','24','68' };
        Test.startTest();
        List<AggregateResult> result = Experience_Store_Hierarchy_Ctrl.getManagementZoneSubLevel3(selectedSubLevel2Tech);
        Test.stopTest();

        System.assertEquals(3, result.size(), 'Expected 3 aggregate result');
    }

    @isTest
    static void testGetStoreLevel() {

        List<String> selectedSubLevel3Tech = new List<String>{ '12345' };
        Test.startTest();
        List<AggregateResult> result = Experience_Store_Hierarchy_Ctrl.getStoreLevel(selectedSubLevel3Tech);
        Test.stopTest();

        System.assertEquals(0, result.size(), 'Expected 0 aggregate result');
    }

    @isTest
    static void testGetSelectedStores() {
        Brand_Experience__c brandExp = [SELECT Id FROM Brand_Experience__c LIMIT 1];
        Test.startTest();
        List<Experience_Store_Hierarchy_Ctrl.SelctedStoreHierarchy> result = Experience_Store_Hierarchy_Ctrl.getSelectedStores(brandExp.Id);
        Test.stopTest();

        System.assertEquals(1, result.size(), 'Expected 1 selected store hierarchies');
    }
}