force-app/main/default/objects/Brand_Experience__c/Brand_Experience__c.object-meta.xml
<CustomObject>
    <description>Object to create Brand Experiences. Parent object of Experience Variation (Brand_Experience_Variation__c)</description>
    <label>Events &amp; Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Experience</description>
    <inlineHelpText>Calculated based on child Variations statuses</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Partially Ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
                <isActive>false</isActive>
                <label>Published</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-experience/main/default/objects/Brand_Experience__c/recordTypes/Experience.recordType-meta.xml
<RecordType>
    <fullName>Experience</fullName>
    <active>true</active>
    <description>used to create Experiences</description>
    <label>In-Store Animation</label>
</RecordType>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/Brand_Experience_Store_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Events &amp; Experiences Store Hierarchy</label>
    <nameField>
        <label>Events &amp; Experiences Store Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences Store Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/fields/Brand_Experience__c.field-meta.xml
<CustomField>
    <fullName>Brand_Experience__c</fullName>
    <label>Events &amp; Experience</label>
    <referenceTo>Brand_Experience__c</referenceTo>
    <relationshipLabel>Events &amp; Experiences Store Hierarchies</relationshipLabel>
    <relationshipName>Events_Experiences_Store_Hierarchies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Events &amp; Experiences Store Hierarchies</relationshipLabel>
    <relationshipName>Events_Experiences_Store_Hierarchies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/StoreType__c.field-meta.xml
<CustomField>
    <fullName>StoreType__c</fullName>
    <description>Indicate which type of store it is</description>
    <label>Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>WEB</fullName>
            </value>
            <value>
                <fullName>CSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-experience/main/default/classes/BL_Batch_For_StoreHirerchy_DataFix.cls
/*	* @author: Nechama Wollach
    * @date creation: 13/06/2024
    * @description: Batch for data fix, creation Brand_Experience_Store_Hierarchy__c for each Brand_Experience__c<->Store_c combination. (https://vuitton.atlassian.net/browse/SE-674)
    Script to run:
    DataFixBatch batchJob = new DataFixBatch();
    Database.executeBatch(batchJob, 50);
*/
public class BL_Batch_For_StoreHirerchy_DataFix implements Database.Batchable<sObject> {
    
    private static final String QUERY_EVENTS = 'SELECT Id FROM Brand_Experience__c WHERE RecordType.DeveloperName=\'Experience\'';
    private static final String QUERY_STORES = 'SELECT Id FROM Store__c WHERE StoreType__c IN (\'Store\', \'POP-UP OON\', \'CSC\', \'WEB\') AND Status__c IN (\'Open\', \'Opening Soon\')';

    
    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator(QUERY_STORES);
    }
    
    public void execute(Database.BatchableContext context, List<Store__c> scope) {
        List<Brand_Experience_Store_Hierarchy__c> storeHierarchyRecords = new List<Brand_Experience_Store_Hierarchy__c>();
        List<Brand_Experience__c> events = Database.query(QUERY_EVENTS);

        for(Store__c store : scope) {

            for(Brand_Experience__c event : events) {

            // Create Store_Hierarchy__c records for each Store__c and Brand_Experience__c combination
            
                Brand_Experience_Store_Hierarchy__c storeHierarchy = new Brand_Experience_Store_Hierarchy__c();
                storeHierarchy.Store__c = store.Id;
                storeHierarchy.Brand_Experience__c = event.Id;                
                storeHierarchyRecords.add(storeHierarchy);
            }
        }  
        insert storeHierarchyRecords;
    }
    
    public void finish(Database.BatchableContext context) {
    }
}