force-app/main/default/objects/Brand_Experience__c/Brand_Experience__c.object-meta.xml
<CustomObject>
    <description>Object to create Brand Experiences. Parent object of Experience Variation (Brand_Experience_Variation__c)</description>
    <label>Events &amp; Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience__c/fields/ClubName__c.field-meta.xml
<CustomField>
    <fullName>ClubName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Club associated with the Experience</description>
    <label>Club</label>
    <referenceTo>Club_and_Seasons__c</referenceTo>
    <relationshipName>Brand_Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Experience__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Experience</description>
    <inlineHelpText>Calculated based on child Variations statuses</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Partially Ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
                <isActive>false</isActive>
                <label>Published</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-experience/main/default/objects/Brand_Experience__c/recordTypes/Experience.recordType-meta.xml
<RecordType>
    <fullName>Experience</fullName>
    <active>true</active>
    <description>used to create Experiences</description>
    <label>In-Store Animation</label>
</RecordType>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/Brand_Experience_Store_Hierarchy__c.object-meta.xml
<CustomObject>
    <label>Events &amp; Experiences Store Hierarchy</label>
    <nameField>
        <label>Events &amp; Experiences Store Hierarchy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences Store Hierarchies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/fields/Brand_Experience__c.field-meta.xml
<CustomField>
    <fullName>Brand_Experience__c</fullName>
    <label>Events &amp; Experience</label>
    <referenceTo>Brand_Experience__c</referenceTo>
    <relationshipLabel>Events &amp; Experiences Store Hierarchies</relationshipLabel>
    <relationshipName>Events_Experiences_Store_Hierarchies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Store_Hierarchy__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Events &amp; Experiences Store Hierarchies</relationshipLabel>
    <relationshipName>Events_Experiences_Store_Hierarchies</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_and_Seasons__c/Club_and_Seasons__c.object-meta.xml
<CustomObject>
    <label>Club</label>
    <nameField>
        <label>Club Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/StoreType__c.field-meta.xml
<CustomField>
    <fullName>StoreType__c</fullName>
    <description>Indicate which type of store it is</description>
    <label>Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>WEB</fullName>
            </value>
            <value>
                <fullName>CSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-experience/main/default/classes/test/Ex_new_brand_experience_modal_Ctrl_Test.cls
@isTest
private class Ex_new_brand_experience_modal_Ctrl_Test {

    @testSetup
    static void setup() {

        Id ExperienceRecordType = Schema.SObjectType.Brand_Experience__c.getRecordTypeInfosByDeveloperName().get('Experience').getRecordTypeId();
        Club_and_Seasons__c clubSneakers = new Club_and_Seasons__c(
            Name = 'Sneakers'
        );
        insert clubSneakers;
        
        Brand_Experience__c ex = new Brand_Experience__c(
            RecordTypeId = ExperienceRecordType,
            Name = 'test',
            Status__c = 'Ongoing',
            ClubName__c = clubSneakers.Id
        );
        insert ex;
		
        List<Store__c> testStores = new List<Store__c>();
        testStores.add(New Store__c(Name = 'test1', RetailStoreId__c = 'AA11', StoreType__c='Store', Status__c='Opening Soon'));
        testStores.add(New Store__c(Name = 'test2', RetailStoreId__c = 'AA22', StoreType__c='CSC', Status__c='Opening Soon'));
        testStores.add(New Store__c(Name = 'test3', RetailStoreId__c = 'BB33', StoreType__c='Store', Status__c='Open'));
        testStores.add(New Store__c(Name = 'test3', RetailStoreId__c = 'BB44', StoreType__c='CSC', Status__c='Open'));

        insert testStores;
    }
    @isTest
    static void testgetRecordType() {
        Test.startTest();
        List<RecordType> recordTypeList = Ex_new_brand_experience_modal_Controller.getRecordTypes();
        Test.stopTest();

        System.assertEquals(recordTypeList.size(), 2, 'There are 2 recordtypes availables for this component');
    }
    @isTest
    static void testCreateBrandEventAndStoreHierarchyRecords() {
        // Prepare test data
        Id ExperienceRecordType = Schema.SObjectType.Brand_Experience__c.getRecordTypeInfosByDeveloperName().get('Experience').getRecordTypeId();

        Map<String, Object> eventRecord = new Map<String, Object>{
            'recordTypeId' => ExperienceRecordType, 
            'name' => 'Test Body',
            'startDate' => '2024-06-24T20:48:00.000Z',
            'endDate' => '2024-11-27T21:48:00.000Z',
            'selectedStores' => new List<String>{'AA11', 'AA22'}
        };

        Test.startTest();
        Brand_Experience__c createdEvent = Ex_new_brand_experience_modal_Controller.createBrandEventAndStoreHierarchyRecords(eventRecord);
        Test.stopTest();

        // Perform assertions
        System.assert(createdEvent != null, 'Brand Event should have been created');
    }
    @isTest
    static void testUpdateSelectedStores() {
        
        List<Brand_Experience_Store_Hierarchy__c> initialHierarchyRecords = new List<Brand_Experience_Store_Hierarchy__c>();
        Brand_Experience__c brndEx =[SELECT Id FROM Brand_Experience__c LIMIT 1];
        List<Store__c> stores = [SELECT Id FROM Store__c];
    	initialHierarchyRecords.add(new Brand_Experience_Store_Hierarchy__c(
        Brand_Experience__c = brndEx.Id,
        Store__c = stores[0].Id
    	));
    	initialHierarchyRecords.add(new Brand_Experience_Store_Hierarchy__c(
        Brand_Experience__c = brndEx.Id,
        Store__c = stores[1].Id
    	));
    	insert initialHierarchyRecords;
        
        
        List<String> storeCodes = new List<String>{'BB33', 'BB44'};
        Test.startTest();
        Ex_new_brand_experience_modal_Controller.updateSelectedStores(storeCodes, brndEx.Id);
        Test.stopTest();
        
        List<Brand_Experience_Store_Hierarchy__c> updatedHierarchyRecords = [SELECT Id, Store__r.RetailStoreId__c FROM Brand_Experience_Store_Hierarchy__c WHERE Brand_Experience__c = :brndEx.Id];
        System.assertEquals(2, updatedHierarchyRecords.size(), 'New hierarchy records should have been inserted');

        Set<String> updatedStoreCodes = new Set<String>();
        for (Brand_Experience_Store_Hierarchy__c record : updatedHierarchyRecords) {
            updatedStoreCodes.add(record.Store__r.RetailStoreId__c);
        }
        System.assertEquals(new Set<String>{'BB33', 'BB44'}, updatedStoreCodes, 'Updated store codes should match expected values');
    }

}