force-app/main/default/objects/Catalogue_Settings__c/Catalogue_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Catalogue Settings</label>
</CustomObject>

force-app/main/default/objects/Last_Digital_Store__c/Last_Digital_Store__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Last Digital Store</label>
</CustomObject>

force-app/main/default/objects/Last_Digital_Store__c/fields/StoreRetailId__c.field-meta.xml
<CustomField>
    <fullName>StoreRetailId__c</fullName>
    <label>Store Retail Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/StoreLocation__c.field-meta.xml
<CustomField>
    <fullName>StoreLocation__c</fullName>
    <description>Contains the latitude and longitude positions of the store. Expressed as decimals</description>
    <label>Store Location</label>
    <scale>8</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-catalogs/main/default/classes/TEST_WS_ProductStockAvailability.cls
@isTest
public class TEST_WS_ProductStockAvailability {
    
    
	@isTest
	static void testGetProductsStoreAvailabilities() {
        
        List<String> selectedStoresRetailStoreId = new List<String>();

        Store__c store = TEST_Utils.createStore('test store', 'TE1');
       	store.StoreLocation__Latitude__s = 24.471912;
		store.StoreLocation__Longitude__s = 54.321014;

        upsert store;
        selectedStoresRetailStoreId.add(store.RetailStoreId__c);

        Store__c store2 = TEST_Utils.createStore('test store2', 'TE2');
        store2.StoreLocation__Latitude__s = 24.471912;
		store2.StoreLocation__Longitude__s = 54.321014;

        upsert store2;
        selectedStoresRetailStoreId.add(store2.RetailStoreId__c);
        
        system.debug('selectedStoresRetailStoreId:'+selectedStoresRetailStoreId);

		ProductCatalogue__c product = TEST_Utils.createProductCatalog('test product','1234');
        String productId = (String)product.get('Id');
        
        Catalogue_Settings__c CS  = TEST_Utils.createCatalogue_Settings();
     
		System.debug('CS: ' + CS);
        upsert CS;

       // User u = TEST_Utils.createUser('test');

        
        
        Decimal numOfStoresRequested = selectedStoresRetailStoreId.size();
    	User currentUser = DAL_ProductCatalog.getUser();
    	
        system.debug('currentUser:'+currentUser);
    	Last_Digital_Store__c lastDigitalStore = DAL_ProductCatalog.getLastDigitalStore();

    	Store__c defaultStore = (String.isNotEmpty(lastDigitalStore.StoreRetailId__c)) ? 
    		DAL_ProductCatalog.getStoreByCode(lastDigitalStore.StoreRetailId__c) : 
        	store;
    		//DAL_ProductCatalog.getStoreByCode(currentUser.DefaultStore__c);

        system.debug('defaultStore:'+defaultStore);

    	ProductCatalogue__c selectedProduct = DAL_ProductCatalog.getProductCatalogById(productId);
		for(Integer i = 0; i < selectedStoresRetailStoreId.size(); i++) {
			if(selectedStoresRetailStoreId[i] == defaultStore.RetailStoreId__c) {
				selectedStoresRetailStoreId.remove(i);
			}
		}
		
		List<Store__c> selectedStores = DAL_ProductCatalog.getStoresByCodes(selectedStoresRetailStoreId); 
		
        
		//selectedStores.add(defaultStore);
        system.debug('selectedStore:'+selectedStores);
		
    	if(selectedStores != null && selectedStores.size() == 2 && selectedStores[0].StoreLocation__c != null) {
    		List<Store__c> nearbyStores = DAL_ProductCatalog.getNearbyStoresByStoreLocation(selectedStores[0].StoreLocation__c.getLatitude(),selectedStores[0].StoreLocation__c.getLongitude(), 30, selectedStores[0].RetailStoreId__c);
    		if(nearbyStores != null) {
    			selectedStores.addAll(nearbyStores);
    		}
    	}
        
        

      	  Test.setMock(HttpCalloutMock.class, new MockHttpResponse('successProductAvailabilityResponse_Quantity1' , 'ProductStockAvailability'));

        
        
        Test.startTest();

    	Map<String, List<Wrapper_ProductStoreAvailability>> productAvailabilityMap = WS_ProductStockAvailability.getProductsStoreAvailabilities(selectedStores, new List<ProductCatalogue__c>{selectedProduct}, defaultStore);
        system.debug('result:'+productAvailabilityMap);
        system.assertEquals(productAvailabilityMap.values()[0],productAvailabilityMap.get('1234'));
        

        Test.stopTest();
        

        
        


  
        
        
    }
    
    @isTest
	static void testGetProductsStoreAvailabilitiesWithErrorCode() {
        
        List<String> selectedStoresRetailStoreId = new List<String>();

        Store__c store = TEST_Utils.createStore('test store', 'TE1');
       	store.StoreLocation__Latitude__s = 24.471912;
		store.StoreLocation__Longitude__s = 54.321014;

        upsert store;
        selectedStoresRetailStoreId.add(store.RetailStoreId__c);

        Store__c store2 = TEST_Utils.createStore('test store2', 'TE2');
        store2.StoreLocation__Latitude__s = 24.471912;
		store2.StoreLocation__Longitude__s = 54.321014;

        upsert store2;
        selectedStoresRetailStoreId.add(store2.RetailStoreId__c);
        
        system.debug('selectedStoresRetailStoreId:'+selectedStoresRetailStoreId);

		ProductCatalogue__c product = TEST_Utils.createProductCatalog('test product','1234');
        String productId = (String)product.get('Id');
        
        Catalogue_Settings__c CS  = TEST_Utils.createCatalogue_Settings();
     
		System.debug('CS: ' + CS);
        upsert CS;

       // User u = TEST_Utils.createUser('test');

        
        
        Decimal numOfStoresRequested = selectedStoresRetailStoreId.size();
    	User currentUser = DAL_ProductCatalog.getUser();
    	
        system.debug('currentUser:'+currentUser);
    	Last_Digital_Store__c lastDigitalStore = DAL_ProductCatalog.getLastDigitalStore();

    	Store__c defaultStore = (String.isNotEmpty(lastDigitalStore.StoreRetailId__c)) ? 
    		DAL_ProductCatalog.getStoreByCode(lastDigitalStore.StoreRetailId__c) : 
        	store;
    		//DAL_ProductCatalog.getStoreByCode(currentUser.DefaultStore__c);

        system.debug('defaultStore:'+defaultStore);

    	ProductCatalogue__c selectedProduct = DAL_ProductCatalog.getProductCatalogById(productId);
		for(Integer i = 0; i < selectedStoresRetailStoreId.size(); i++) {
			if(selectedStoresRetailStoreId[i] == defaultStore.RetailStoreId__c) {
				selectedStoresRetailStoreId.remove(i);
			}
		}
		
		List<Store__c> selectedStores = DAL_ProductCatalog.getStoresByCodes(selectedStoresRetailStoreId); 
		
        
		//selectedStores.add(defaultStore);
        system.debug('selectedStore:'+selectedStores);
		
    	if(selectedStores != null && selectedStores.size() == 2 && selectedStores[0].StoreLocation__c != null) {
    		List<Store__c> nearbyStores = DAL_ProductCatalog.getNearbyStoresByStoreLocation(selectedStores[0].StoreLocation__c.getLatitude(),selectedStores[0].StoreLocation__c.getLongitude(), 30, selectedStores[0].RetailStoreId__c);
    		if(nearbyStores != null) {
    			selectedStores.addAll(nearbyStores);
    		}
    	}
        
        
       	  Test.setMock(HttpCalloutMock.class, new MockHttpResponse('successProductAvailabilityResponse' , 'ProductStockAvailability'));


        
        
        Test.startTest();

    	Map<String, List<Wrapper_ProductStoreAvailability>> productAvailabilityMap = WS_ProductStockAvailability.getProductsStoreAvailabilities(selectedStores, new List<ProductCatalogue__c>{selectedProduct}, defaultStore);
        system.debug('result:'+productAvailabilityMap);
        system.assertEquals(productAvailabilityMap.values()[0],productAvailabilityMap.get('1234'));
        

        Test.stopTest();
        

        
        


  
        
        
    }
}