force-app/main/default/objects/Catalogue_Settings__c/Catalogue_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Catalogue Settings</label>
</CustomObject>

force-app/main/default/objects/Catalogue_Settings__c/fields/IntegPassword__c.field-meta.xml
<CustomField>
    <fullName>IntegPassword__c</fullName>
    <description>hold the password for the integration user</description>
    <label>Integ Password</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/IntegUsername__c.field-meta.xml
<CustomField>
    <fullName>IntegUsername__c</fullName>
    <description>hold the username used to make the WS call</description>
    <label>Integ Username</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/WS_Price__c.field-meta.xml
<CustomField>
    <fullName>WS_Price__c</fullName>
    <label>WS_Price</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCatalogue__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <description>SKU code</description>
    <externalId>true</externalId>
    <label>SKU</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Store_CountryCode__c.field-meta.xml
<CustomField>
    <fullName>Store_CountryCode__c</fullName>
    <label>Store Country / Region Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StoreCountry__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>CN</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/StoreCountry__c.field-meta.xml
<CustomField>
    <fullName>StoreCountry__c</fullName>
    <description>Indicates the country in which the store is located</description>
    <label>Store Country / Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BARBADE</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILE</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>COLOMBIA</fullName>
            </value>
            <value>
                <fullName>CYPRUS</fullName>
            </value>
            <value>
                <fullName>CZECH REPUBLIC</fullName>
            </value>
            <value>
                <fullName>DENMARK</fullName>
            </value>
            <value>
                <fullName>DOMINICAIN REPUBLIC</fullName>
            </value>
            <value>
                <fullName>FINLAND</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>GREECE</fullName>
            </value>
            <value>
                <fullName>GUAM</fullName>
            </value>
            <value>
                <fullName>HONG KONG</fullName>
            </value>
            <value>
                <fullName>HUNGARY</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDONESIA</fullName>
            </value>
            <value>
                <fullName>IRELAND</fullName>
            </value>
            <value>
                <fullName>ISRAEL</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>KAZAKHSTAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-catalogs/main/default/classes/WS_ProductPrice.cls
public class WS_ProductPrice {

	@AuraEnabled public static Map<String, Map<String, Map<String, Wrapper_ProductPrice>>> ProductsPrices {
		set;get;
	}


	public static Map<String, Map<String, Map<String, Wrapper_ProductPrice>>> getProductsCountryPrice(
			List<Store__c> stores,
			List<ProductCatalogue__c> selectedProducts,
			Store__c defaultStoreCode) {
		try {
			Map<String, ProductCatalogue__c> selectedProductsSKUs = new Map<String, ProductCatalogue__c>();
			Map<String, ProductCatalogue__c> selectedProductsIds = new Map<String, ProductCatalogue__c>();
			Map<String, Store__c> storeCodemap = new Map<String, Store__c>();
			Set<String> StoreCountryCodes = new Set<String>();
			Map<String, String> StoreCountries = new Map<String, String>();
			List<String> Skus = new List<String>();


			//system.debug('selectedProducts ' + selectedProducts);
			for (ProductCatalogue__c productCatalog : selectedProducts) {
				selectedProductsSKUs.put(productCatalog.SKU__c, productCatalog);
				selectedProductsIds.put(productCatalog.Id, productCatalog);
				Skus.add('"' + productCatalog.SKU__c + '"');
			}

			//system.debug('stores ' + stores);
            for (Store__c store : stores) {
				storeCodemap.put(store.RetailStoreId__c, store);
			}

			for (Store__c store : stores) {
				//system.debug('Store_CountryCode__c ' + store.Store_CountryCode__c);
				if (!StoreCountries.containsKey(store.Store_CountryCode__c)) {
					StoreCountries.put(store.Store_CountryCode__c, store.StoreCountry__c);
				}
				StoreCountryCodes.add('"' + store.Store_CountryCode__c + '"');
			}
			/*Catalogue_Settings__c CS = Catalogue_Settings__c.getInstance(System.Label.WSCatalogueTECHUserId);
			Http httpProtocol = new Http();
			HttpRequest httpRequest = new HttpRequest();

			//httpRequest.setEndpoint('https://lv-api-int.vuitton.biz:11930/ws/EAI_GetPricesByCountry/1.0.0/LVItemAPI/v1/webServices/priceByCountry');
			httpRequest.setEndpoint(CS.WS_Price__c);
			httpRequest.setMethod('POST');
			httpRequest.setTimeout(120000);
			httpRequest.setHeader('Encoding', 'UTF-8');
			httpRequest.setHeader('Accept', 'application/json');
			httpRequest.setHeader('Content-Type', 'application/json');
			String authorizationHeader =
					'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(CS.IntegUsername__c + ':' + CS.IntegPassword__c));
			system.debug('CS.IntegUsername__c ' + CS.IntegUsername__c);
			httpRequest.setHeader('Authorization', authorizationHeader);*/
			Http httpProtocol = new Http();
			HttpRequest httpRequest = new HttpRequest();
			//httpRequest.setEndpoint('callout:WS_Product_Price/ws/EAI_GetPricesByCountry/2.0/LVItemAPI/v2/webServices/priceByCountry');
			httpRequest.setEndpoint('callout:WS_Product_Price');
			httpRequest.setMethod('POST');
			httpRequest.setHeader('Encoding', 'UTF-8');
			httpRequest.setHeader('Accept', 'application/json');
			httpRequest.setHeader('Content-Type', 'application/json');
			String selectedSku = String.join(Skus, ',');
			date myDate = date.today();
			string todayDateString = string.valueOfGmt(myDate);
			String todayDate = todayDateString.replaceAll('-', '').substringBeforeLast(' ');

			//for (String CountryCode:StoreCountryCodes) {
			String CountryCodes = String.join(new List<String>(StoreCountryCodes), ',');
			system.debug('country code ' + CountryCodes);
			httpRequest.setBody(
							'{"LVParameters":{"countryCodeList":[' + CountryCodes + '],"itemList":[' + selectedSku +
							'],"effectiveDate":"' +
							todayDate + '","tariffTypeList":["R"]}}');

			system.debug('selectedSku ' + selectedSku);
			HttpResponse httpResponse = null;
			httpResponse = httpProtocol.send(httpRequest);
			//System.debug('httpResponse ' + httpResponse);
			system.debug(httpResponse.getBody());


			getProductPrice(httpResponse.getBody(), CountryCodes, StoreCountries);
			//}
			system.debug('my map ' + ProductsPrices);

			return ProductsPrices;
		} catch (Exception e) {
			Ctrl_ProductCatalog.log('WS_getProductsCountryPrice', e);
			ProductsPrices = new Map<String, Map<String, Map<String, Wrapper_ProductPrice>>>();
			return ProductsPrices;
		}

	}

	public static void getProductPrice(String jsonPrice, String CountryCode, Map<String,String> MapStoreCountries) {

		Map<String, Map<String, Map<String, Wrapper_ProductPrice>>> countryProductPrice =
				new Map<String, Map<String, Map<String, Wrapper_ProductPrice>>>();
		String newJson = jsonPrice.replace('"currency":', '"currencyCode":');
		system.debug('productPriceBeforeParse ' + newJson);
		ProductPriceJsonToApex productPriceParse = ProductPriceJsonToApex.parse(newJson);

		system.debug('productPriceParse ' + productPriceParse);


		/*if (productPriceParse.LVResponse != null) {
			if (productPriceParse.LVResponse.data != null) {
				if (productPriceParse.LVResponse.data.itemPrices != null) {
					system.debug('yyy ' + productPriceParse.LVResponse.data.itemPrices);
					for (ProductPriceJsonToApex.ItemPrices itemPrice:productPriceParse.LVResponse.data.itemPrices) {
						if (ProductsPrices == null) {
							ProductsPrices = new Map<String, Map<String, Wrapper_ProductPrice>>();
						}

						if(!ProductsPrices.containsKey(itemPrice.item)){
							ProductsPrices.put(itemPrice.item, new Map<String,Wrapper_ProductPrice>());
						}
						countryProductPrice = ProductsPrices.get(itemPrice.item);
						Wrapper_ProductPrice itemProductPrice = new Wrapper_ProductPrice();
						itemProductPrice.price = decimal.valueOf(itemPrice.price);
						itemProductPrice.currencyCoin = itemPrice.currency_price;
						itemProductPrice.Country = StoreCountry;
						itemProductPrice.CountryCode = CountryCode;
						countryProductPrice.put(CountryCode, itemProductPrice);
						productsPrices.put(itemPrice.item,countryProductPrice);

					}
				}
			}
		}*/
		if (productPriceParse.LVResponse != null) {
			if (productPriceParse.LVResponse.data != null) {
				if (productPriceParse.LVResponse.data.itemPrices != null) {
					system.debug('yyy ' + productPriceParse.LVResponse.data.itemPrices);
					for (ProductPriceJsonToApex.ItemPrices itemPrice:productPriceParse.LVResponse.data.itemPrices) {
						if (ProductsPrices == null) {
							ProductsPrices = new Map<String, Map<String, Map<String, Wrapper_ProductPrice>>>();
						}

						system.debug('countryCode '+itemPrice.countryCode);
						String myCountryCode = itemPrice.countryCode;
						for(ProductPriceJsonToApex.ItemList item:itemPrice.itemList) {
							system.debug('item' + item.currencyCode);
							if(!ProductsPrices.containsKey(item.item)){
								ProductsPrices.put(item.item, new Map<String,Map<String, Wrapper_ProductPrice>>());
							}
							Map<String, Map<String, Wrapper_ProductPrice>> itemsMap =  ProductsPrices.get(item.item);
							if(!itemsMap.containsKey(myCountryCode)){
								itemsMap.put(myCountryCode, new Map<String, Wrapper_ProductPrice>());
							}
							Map<String, Wrapper_ProductPrice> countryCodeMap = itemsMap.get(myCountryCode);
							/*if(!countryCodeMap.containsKey(item.tariffType)){
								countryCodeMap.put(item.tariffType, )
							}*/
							Wrapper_ProductPrice itemProductPrice = new Wrapper_ProductPrice();
							itemProductPrice.price = decimal.valueOf(item.price);
							itemProductPrice.currencyCoin = item.currencyCode;
							itemProductPrice.Country = MapStoreCountries.get(myCountryCode);
							system.debug(itemProductPrice.Country);
							itemProductPrice.CountryCode = myCountryCode;
							
							countryCodeMap.put(item.tariffType, itemProductPrice);
							itemsMap.put(myCountryCode,countryCodeMap );
							ProductsPrices.put(item.item, itemsMap);

						}




						/*if(!ProductsPrices[itemPrice.item].containsKey(itemPrice.tariffType)){

						}*/
						/*countryProductPrice = ProductsPrices.get(itemPrice.item);
						Wrapper_ProductPrice itemProductPrice = new Wrapper_ProductPrice();
						itemProductPrice.price = decimal.valueOf(itemPrice.price);
						itemProductPrice.currencyCoin = itemPrice.currencyCode;
						itemProductPrice.tarifType = itemPrice.tariffType;
						itemProductPrice.Country = StoreCountry;
						itemProductPrice.CountryCode = CountryCode;
						countryProductPrice.put(CountryCode, itemProductPrice);
						productsPrices.put(itemPrice.item,countryProductPrice);*/


					}
				}
			}

		}
	}
}