force-app/main/default/objects/Catalogue_Settings__c/Catalogue_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Catalogue Settings</label>
</CustomObject>

force-app/main/default/objects/Catalogue_Settings__c/fields/A90__c.field-meta.xml
<CustomField>
    <fullName>A90__c</fullName>
    <label>A90</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/CatalogueWSURL__c.field-meta.xml
<CustomField>
    <fullName>CatalogueWSURL__c</fullName>
    <label>Catalogue WS URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/Digital_Store_List_Other_Price__c.field-meta.xml
<CustomField>
    <fullName>Digital_Store_List_Other_Price__c</fullName>
    <description>List of digital store that get price from atg and not  from sap</description>
    <label>Digital Store List Other Price</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/Digital_Stores__c.field-meta.xml
<CustomField>
    <fullName>Digital_Stores__c</fullName>
    <label>Digital Stores</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/IntegPassword__c.field-meta.xml
<CustomField>
    <fullName>IntegPassword__c</fullName>
    <description>hold the password for the integration user</description>
    <label>Integ Password</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/IntegUsername__c.field-meta.xml
<CustomField>
    <fullName>IntegUsername__c</fullName>
    <description>hold the username used to make the WS call</description>
    <label>Integ Username</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/Max_stores_for_search__c.field-meta.xml
<CustomField>
    <fullName>Max_stores_for_search__c</fullName>
    <label>Max stores for search</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/Number_Of_New_Porducts__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_New_Porducts__c</fullName>
    <label>Number Of New Porducts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/OptionalHeadersNum__c.field-meta.xml
<CustomField>
    <fullName>OptionalHeadersNum__c</fullName>
    <label>Optional Headers Num</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/User_Agent__c.field-meta.xml
<CustomField>
    <fullName>User_Agent__c</fullName>
    <label>User Agent</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Catalogue_Settings__c/fields/WS_Price__c.field-meta.xml
<CustomField>
    <fullName>WS_Price__c</fullName>
    <label>WS_Price</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Stock__c/Product_Stock__c.object-meta.xml
<CustomObject>
    <description>Stocks used for Wardrobing project (RMS conso stock + e-commerce)</description>
    <label>Product Stock</label>
    <nameField>
        <label>Product Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Stocks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Stock__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Master detail on Product Catalogue</description>
    <label>Product</label>
    <referenceTo>ProductCatalogue__c</referenceTo>
    <relationshipName>Wardrobing_Stocks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Stock__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>RMS Conso</fullName>
            </value>
            <value>
                <fullName>SalesForce</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>Xstore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Stock__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Product Stocks</relationshipLabel>
    <relationshipName>Wardrobing_Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Stock__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>ASIA NORTH</fullName>
            </value>
            <value>
                <fullName>ASIA SOUTH</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCatalogue__c/fields/OrderableEMEA__c.field-meta.xml
<CustomField>
    <fullName>OrderableEMEA__c</fullName>
    <formula>IF(not(isblank(ProductReferential__c)),IF(isblank(TEXT(ProductReferential__r.OrderableEMEA__c)), &apos;Orderable&apos;, Text(ProductReferential__r.OrderableEMEA__c)), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OrderableEMEA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/OrderableJapan__c.field-meta.xml
<CustomField>
    <fullName>OrderableJapan__c</fullName>
    <formula>IF(not(isblank(ProductReferential__c)),IF(isblank(TEXT(ProductReferential__r.OrderableJapan__c)), &apos;Orderable&apos;, Text(ProductReferential__r.OrderableJapan__c)), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OrderableJapan</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/ProductReferential__c.field-meta.xml
<CustomField>
    <fullName>ProductReferential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to ProductReferential. Lookup needed to get some information provided by ProductReferential object (SAP) and not in BCC (ETL / sku.json)</description>
    <label>Product Referential</label>
    <referenceTo>ProductReferential__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <description>SKU code</description>
    <externalId>true</externalId>
    <label>SKU</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/ViewOnline__c.field-meta.xml
<CustomField>
    <fullName>ViewOnline__c</fullName>
    <defaultValue>false</defaultValue>
    <label>View Online</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/ViewOnlineDate__c.field-meta.xml
<CustomField>
    <fullName>ViewOnlineDate__c</fullName>
    <label>ViewOnlineDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/Workshop__c.field-meta.xml
<CustomField>
    <fullName>Workshop__c</fullName>
    <defaultValue>(&quot;0000&quot;)</defaultValue>
    <description>Manufacturing workshop code
(used for JDE system to know in which workshop the product should be sent)
For Perso app, value is set to 11202 (in product creation) but can be changed
Default value changed to 0000 on MIY-2062</description>
    <label>Workshop</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Workshop</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductReferential__c/ProductReferential__c.object-meta.xml
<CustomObject>
    <description>All information about base product</description>
    <label>Product Referential</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Referential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductReferential__c/fields/OrderableEMEA__c.field-meta.xml
<CustomField>
    <fullName>OrderableEMEA__c</fullName>
    <label>OrderableEMEA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SAP_Orderable_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductReferential__c/fields/OrderableJapan__c.field-meta.xml
<CustomField>
    <fullName>OrderableJapan__c</fullName>
    <label>OrderableJapan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SAP_Orderable_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductReferential__c/fields/SKUCode__c.field-meta.xml
<CustomField>
    <fullName>SKUCode__c</fullName>
    <externalId>true</externalId>
    <label>Base SKU Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductReferential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/OpeningHours__c.field-meta.xml
<CustomField>
    <fullName>OpeningHours__c</fullName>
    <label>Opening Hours</label>
    <length>16384</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/StoreType__c.field-meta.xml
<CustomField>
    <fullName>StoreType__c</fullName>
    <description>Indicate which type of store it is</description>
    <label>Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>WEB</fullName>
            </value>
            <value>
                <fullName>CSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup links the store record to the 1st level of hierarchy</description>
    <label>Zone</label>
    <referenceTo>Zone__c</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/User/fields/BypassVR__c.field-meta.xml
<CustomField>
    <fullName>BypassVR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/My_Favorites__c.field-meta.xml
<CustomField>
    <fullName>My_Favorites__c</fullName>
    <description>My Favorits sku Catalog Desktop</description>
    <label>My Favorites</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Zone__c/Zone__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the top level of store Hierarchy</description>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/SAP_Orderable_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Orderable</fullName>
    </customValue>
    <customValue>
        <fullName>Not Orderable</fullName>
    </customValue>
    <customValue>
        <fullName>SC Validation</fullName>
    </customValue>
    <customValue>
        <fullName>OROB SC Validation</fullName>
    </customValue>
    <masterLabel>SAP_Orderable_Status</masterLabel>
</GlobalValueSet>

force-iconics/main/default/classes/TEST_Utils.cls
public with sharing class TEST_Utils {

	public static ProductCatalogue__c createProductCatalog(String name, String sku) {
		ProductCatalogue__c p = new ProductCatalogue__c(Name = name, SKU__c = sku, ViewOnline__c = true, ViewOnlineDate__c =Date.today());
        p.Workshop__c = '1798'; //became required
		insert p;
		return p;
	}
    
    public static ProductReferential__c createProductReferential(String name, String sku) {
		ProductReferential__c pr = new ProductReferential__c(Name = name, SKUCode__c = sku, OrderableEMEA__c='Orderable', OrderableJapan__c='Not Orderable');
		insert pr;
		return pr;
	}

	public static Store__c createStore(String name, String storeCode) {
		Store__c s = new Store__c(Name = name);
		s.StoreType__c = 'Store';
		s.Status__c = 'Open';
		s.OpeningHours__c = '{"Sunday":"10:00-12:00", "Monday":"10:00-12:00", "Tuesday":"10:00-12:00", "Wednesday":"10:00-12:00", "Thursday":"10:00-12:00", "Friday":"10:00-12:00", "Saturday":"10:00-12:00"}';
		s.RetailStoreId__c = storeCode;
		insert s;
		return s;
	}

	/*public static Product_Store_Availability__c createProductAvailability(String name, String productId, String storeId) {
		Product_Store_Availability__c pa = new Product_Store_Availability__c(Name = name, Store__c = storeId, Product_Catalogue__c = productId);
		pa.InTransit__c = 1;
		pa.InStock__c = 10;
		pa.Price__c = 100;
		insert pa;
		return pa;
	}*/

	public static Wrapper_ProductStoreAvailability createProductAvailability(String name, String productId, String storeId) {
		Wrapper_ProductStoreAvailability pa =
				new Wrapper_ProductStoreAvailability();
		//pa.Name = name;
		//pa.Store__c = storeId;
		pa.productCatalogId = productId;
		//pa.InTransit = 1;
		pa.InStock = 10;
		pa.Price = 100;
		pa.locationLatitude = 25;
		pa.locationLongitude = 26;
		pa.googleMapLink = 'test';
		//insert pa;
		return pa;
	}
	/*public static Product_Store_Availability__c createProductAvailability(String name, String storeCode) {
		ProductCatalogue__c p = createProductCatalog(name);
		Store__c s = createStore(name, storeCode);
		return createProductAvailability(name, p.Id, s.Id);
	}*/

    public static User createDreamUser() {
        
               Profile p = [SELECT Id FROM Profile WHERE Name = 'ICON_Interface DREAM'];
        
        		User u = new User(
				UserName = '' + UserInfo.getOrganizationId() + System.now().millisecond() + 'dream@icon.vuitton.com.pprod_test', // Avoiding duplicates
				Email ='icontechnicaluserTEST@louisvuitton.com',
				LastName = 'dreamTest',
				ProfileId = p.id,
                //User License = 'Salesforce',
                //CommunityNickname = 'dreamTest',
                //Role = '# - Corporate',    
				LocaleSidKey = 'en_US',
                BypassVR__c = false,
				LanguageLocaleKey = 'en_US',
				TimeZoneSidKey = 'GMT',
				EmailEncodingKey = 'UTF-8',
				Alias = 'dreamT',
				DefaultStore__c = 'TE1',
                IsActive = true,
				My_Favorites__c = '1234');
		insert u;
		return u;
        
    }
    
	public static User createUser(String uName) {
		Profile sysAdmin = getSysAdminUserProfile();
		User u = new User(
				UserName = '' + UserInfo.getOrganizationId() + System.now().millisecond() + 'test@balink.net', // Avoiding duplicates
				Email ='test@balink.net',
				LastName = 'test',
				ProfileId = sysAdmin.Id,
				LocaleSidKey = 'en_US',
				LanguageLocaleKey = 'en_US',
				TimeZoneSidKey = 'GMT',
				EmailEncodingKey = 'UTF-8',
				Alias = 'userlv',
				DefaultStore__c = 'TE1',
				My_Favorites__c = '1234');
		insert u;
		return u;
	}

	public static Profile getSysAdminUserProfile() {
		return [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
	}

	public static Catalogue_Settings__c createCatalogue_Settings() {
		Catalogue_Settings__c CS = new Catalogue_Settings__c(Digital_Stores__c ='UEC,UIC,URZ,NM5,V02,A90,F90,H90,K90,J90,L36',
				IntegUsername__c = 'username',
				IntegPassword__c = 'password',
				CatalogueWSURL__c = 'http://www.test.com',
				Name = Label.WSCatalogueTECHUserId,
				OptionalHeadersNum__c = 0,
				A90__c = 'http://www.test.com',
				WS_Price__c = 'http://www.test.com',
				User_Agent__c = 'test',
				Number_Of_New_Porducts__c = 10,
				Max_stores_for_search__c = 4,
				Digital_Store_List_Other_Price__c ='Z12');

		insert CS;
		return CS;
	}
    
    public static Product_Stock__c createProductStock(ProductCatalogue__c product, Store__c store) {
		Product_stock__c ps = new Product_Stock__c(
			Zone__c='EMEA', 
			Product__c = product.Id, 
			Store__c = store.Id, 
			Quantity__c = 1,
			Source__c = 'RMS Conso');
        insert ps;
        return ps;
	}

	public static Wrapper_ProductCatalog createProductWrapper(String Sku){
		Wrapper_ProductCatalog wpc =
				new Wrapper_ProductCatalog();
		wpc.sku = Sku;
		return wpc;
	}

	/** Methods dedicated to unit tests, for the sake of simplification */
	
	public static void assertTrue(Object o, Object message) {
		System.assertEquals(true, o, message);
	}

	public static void assertTrue(Object o) {
		assertTrue(o, 'Error');
	}

	public static void assertFalse(Object o, Object message) {
		System.assertEquals(false, o, message);
	}

	public static void assertFalse(Object o) {
		assertFalse(o, 'Error');
	}
	
	public static void assertNull(Object o, Object message) {
		System.assertEquals(null, o, message);
	}

	public static void assertNull(Object o) {
		assertNull(o, 'Error');
	}

	public static void assertNotNull(Object o, Object message) {
		System.assertNotEquals(null, o, message);
	}

	public static void assertNotNull(Object o) {
		assertNotNull(o, 'Error');
	}

}