force-experience/main/default/objects/Activity/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Brand_Experience_Variation_Member__c</referenceTo>
    <relationshipLabel>Appointments</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used for online appointment</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Not Assigned</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>To Be Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Location</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/Brand_Experience_Variation__c.object-meta.xml
<CustomObject>
    <description>Object to create variations of Brand Experiences (Digital Events, Physical Events, Content, Exclusive Offers, ...)
Child object of Experience (Brand_Experience__c). Parent object of Experience Variation Member (Brand_Experience_Variation_Member__c).</description>
    <label>Event &amp; Experience Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event &amp; Experience Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <description>Date &amp; Time at which Brand Experience Variation ends (GMT+02)</description>
    <label>End Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/Guests_Authorized__c.field-meta.xml
<CustomField>
    <fullName>Guests_Authorized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Guests Authorized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Brand Experience Variation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>Published</label>
            </value>
            <value>
                <fullName>Preview</fullName>
                <label>Member Preview</label>
            </value>
            <value>
                <fullName>Registration Opened</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Selection Opened</fullName>
            </value>
            <value>
                <fullName>Selection Closed</fullName>
            </value>
            <value>
                <fullName>Participation Opened</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>Experience_Variations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/Brand_Experience_Variation_Member__c.object-meta.xml
<CustomObject>
    <label>Event &amp; Experience Activation Member</label>
    <nameField>
        <label>Experience Activation Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event &amp; Experience Activation Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/Assigned_CA__c.field-meta.xml
<CustomField>
    <fullName>Assigned_CA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned CA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Experience_Variation_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/Brand_Experience_Variation__c.field-meta.xml
<CustomField>
    <fullName>Brand_Experience_Variation__c</fullName>
    <description>Experience Variation Identifier</description>
    <label>Activation</label>
    <referenceTo>Brand_Experience_Variation__c</referenceTo>
    <relationshipLabel>Event &amp; Experience Activation Members</relationshipLabel>
    <relationshipName>Brand_Experience_Variation_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client Identifier</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Brand_Experience_Variation_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Experience Member</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Not Registered</fullName>
            </value>
            <value>
                <fullName>To Contact</fullName>
            </value>
            <value>
                <fullName>Removed Manually</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Not Participated</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Not Selected</fullName>
                <isActive>false</isActive>
                <label>Not Selected</label>
            </value>
            <value>
                <fullName>Selected</fullName>
                <isActive>false</isActive>
                <label>Selected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Appointments.recordType-meta.xml
<RecordType>
    <fullName>Appointments</fullName>
    <active>true</active>
    <description>Creation of your appointments</description>
    <label>Appointments</label>
</RecordType>

force-app/main/default/objects/Event/recordTypes/Event_Appointment.recordType-meta.xml
<RecordType>
    <fullName>Event_Appointment</fullName>
    <active>true</active>
    <label>Event Appointment</label>
</RecordType>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>An event is a public evenment for the purpose of celebration or marketing related to the customer.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BL_Experience_Variation_Member_Helper.cls
public with sharing class BL_Experience_Variation_Member_Helper {

    public static Object getVariationMember(String variationId, List<String> status, Integer pageSize, Integer pageIndex,  BL_UserInfo me,String storeCode, List<String> caIds) {

        String ownerQuery = getOwnerCondition(me,storeCode, caIds);
       
        String statusQuery = '';
        Brand_Experience_Variation__c  experienceVariation = [ 
                                                                SELECT Id , EndDateTime__c, Guests_Authorized__c
                                                                FROM Brand_Experience_Variation__c
                                                                WHERE Id =: variationId
                                                            ];

        if(experienceVariation.EndDateTime__c < System.now()) {
            status = new List<String> {'Registered','Participated','Not Participated'};
        }

        if(!status.isEmpty()){
            String listStatus = BL_Utils.convertToString(status) ;
            statusQuery = 'Status__c IN' + listStatus;
        }   
      
		List<Brand_Experience_Variation_Member__c> members = (List<Brand_Experience_Variation_Member__c>) new BL_EasyQuery()
            .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_MEMBER)
            .condition(ownerQuery)
            .addCondition('Brand_Experience_Variation__c = \'' +  variationId + '\'')
            .addCondition(statusQuery)
            .pagination(pageIndex, pageSize)
			.executeQuery()
            .getSObjects();
  
        List<String> memberIdsList = new List<String>();    
        for (Brand_Experience_Variation_Member__c member : members) {
            memberIdsList.add(member.id);
        }
        String memberIds = BL_Utils.convertToString(memberIdsList);

        List<Event> appointmentList  = new  List<Event> ();
        if(!memberIdsList.isEmpty()){
            appointmentList = (List<Event>)new BL_EasyQuery()
            .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_APPOINTMENT)
            .condition('Event__c IN ' + memberIds )
            .executeQuery()
            .getSObjects();
        }

        Map<Id, List<Event>> appointmentsToMember = new Map<Id, List<Event>>();
        if(!appointmentList.isEmpty()){
            for (Event evnt : appointmentList) {
                if(!appointmentsToMember.containsKey(evnt.Event__c)){     
                    appointmentsToMember.put(evnt.Event__c, new List<Event>());
                }
                appointmentsToMember.get(evnt.Event__c).add(evnt);
            }
        }
        
        List<Object>records = new List<Object>();
        
        for(Brand_Experience_Variation_Member__c member : members){
            Map<String,Object> record = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(member));
            String recordId = String.valueOf(member.id);
            if (appointmentsToMember.containsKey(recordId)) {
                record.put('Activities__r', appointmentsToMember.get(recordId));
            }
            records.add(record);
        }
        return records;
    }

    public static Object getVariationMemberById(String memberId, BL_UserInfo me) {
        

        String ownerQuery = !me.basicInfos.TECH_IsManager__c ? 'Assigned_CA__c = \'' + me.basicInfos.Id + '\'' : '';
        Object member = new BL_EasyQuery()
                    .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_MEMBER)
                    .condition('Id = \'' +  memberId + '\'')
                    .addCondition(ownerQuery)
                    .executeQuery()
                    .getSObject();

        List<SObject> guests = (List<SObject>) new BL_EasyQuery()
        .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_GUEST)
        .condition('Brand_Experience_Variation_Member__c = \'' +  memberId + '\'')
        .executeQuery()
        .getSObjects();

        List<SObject> appointment = (List<SObject>) new BL_EasyQuery()
        .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_APPOINTMENT)
        .condition('Event__c = \'' +  memberId + '\'')
        .executeQuery()
        .getSObjects();

        Map<String, Object> memberMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(member));
        memberMap.put('guests', guests);
        memberMap.put('Activities__r', appointment);  
        return memberMap;      
    }

    public static Object createVariationMembers(List<Object> records, String experienceVarId ) {

        // remove Clients that are already existing as members 

        Set<String> clientIds = new Set<String>();
        Set<String> existingclientIds = new Set<String>();
        List<Object> recordsToInsert = new List<Object>();

        for (Object record : records) {
            Map<String, Object> recordmapped = (Map<String, Object>) record;
            clientIds.add((String) recordmapped.get('client'));
        }

        List<Object> existingMembers = getExistingVariationMembers(experienceVarId, clientIds);

        for (Object record : existingMembers) {
            Map<String, Object> recordmapped = (Map<String, Object>) record;
            existingclientIds.add( (String) recordmapped.get('client'));
        }
                                         
        for (Object record : records) {

            Map<String, Object> recordmapped = (Map<String, Object>) record;
            String clientId = (String) recordmapped.get('client');
            
            if(!existingclientIds.contains(clientId)){
                recordmapped.put('experienceVariation', experienceVarId);
                recordsToInsert.add(recordmapped);
            }
        }
          
        // Map<String,Object>  members =  (Map<String,Object>) new BL_EasyQuery()
        //                                                     .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_MEMBER)
        //                                                     .upsertWrappersWithChilds(recordsToInsert , null, null);
        List<SObject> members = new BL_EasyQuery()
                                .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_MEMBER)
                                .convertWrapperToSObject(recordsToInsert);
        upsert members;

        if(!existingMembers.isEmpty()){
            return existingMembers;
        }                                                    
        return members;
	}

    public static List<Object> getExistingVariationMembers(String experienceVarId, Set<String> clientIds) {

        return new BL_EasyQuery()
                .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_MEMBER_STATUS)
                .condition('Brand_Experience_Variation__c = \'' +  experienceVarId + '\'')
                .addCondition('Client__c IN' + + BL_Utils.convertToString(clientIds))
                .executeQuery()
                .getMappedObjects();
    }

    public static Object updateVariationMembers(Object recordBody, String memberId, BL_UserInfo me) {
        
        Map<String,Object> record = (Map<String,Object>) recordBody;
        record.put('id',memberId);

        Map<String,Object> members = (Map<String,Object>) new BL_EasyQuery()
                                                            .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_MEMBER)
                                                            .upsertWrappersWithChilds(new List<Object>{record} , null, null);
        
        return getVariationMemberById(memberId,me);
	}
    public static Object saveMemberandRelated(Object recordBody, String memberId, BL_UserInfo me) {
        Map<String,Object> bodyMap = (Map<String,Object>) recordBody;
        List<Object> guestsBody = bodyMap.containsKey('guests') ? (List<Object>) bodyMap.get('guests') : new List<Object>();
        List<Object> appointmentBody = bodyMap.containsKey('appointment') ? (List<Object>) bodyMap.get('appointment') : new List<Object>();
        bodyMap.remove('guests');
        bodyMap.remove('appointment');
        updateVariationMember(bodyMap,memberId); 
        upsertGuests(guestsBody);      
        upsertAppointment(appointmentBody);
        
        return getVariationMemberById(memberId,me);
	}
    public static void updateVariationMember(Object recordBody, String memberId) {
        
        Map<String,Object> record = (Map<String,Object>) recordBody;
        record.put('id',memberId);

        List<SObject> members = new BL_EasyQuery()
                                .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_MEMBER)
                                .convertWrapperToSObject(new List<Object>{record});
        update members;
    }

    public static void upsertGuests(List<Object> items) {   
        List<SObject> guests = new BL_EasyQuery()
                                    .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_GUEST)
                                    .convertWrapperToSObject(items);
        if (guests!=null&&!guests.isEmpty()) {
            upsert guests;  
        }
	}
    
    public static Object upsertGuestsPerMember(Object recordBody, String memberId, BL_UserInfo me) {
        Map<String,Object> bodyMap = (Map<String,Object>) recordBody;
        List<Object> items = (List<Object>) bodyMap.get('guests');
              
        List<SObject> guests = new BL_EasyQuery()
                                    .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_GUEST)
                                    .convertWrapperToSObject(items);
       
        upsert guests;
        return guests;
	}
    public static void upsertAppointment(List<Object> items) {          
        
        Id recordType = Event.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Event_Appointment')?.getRecordTypeId();
        List<Object> appointmentList = new List<Object>();
        for(Object item :items){
            Map<String,Object> appointment = (Map<String,Object>) item;
            appointment.put('recordTypeId',recordType);

            appointmentList.add(appointment);
        }

        List<SObject> appointments = new BL_EasyQuery()
                                    .useCase(BL_Experiences_Constants.USE_CASE_EXPERIENCE_VARIATION_APPOINTMENT)
                                    .convertWrapperToSObject(appointmentList);

        if (appointments!=null&&!appointments.isEmpty()) {
            upsert appointments;
        }
	}

    public static Object deleteGuests(Object recordBody) {
        Map<String,Object> bodyMap = (Map<String,Object>) recordBody;
        List<Object> items = (List<Object>) bodyMap.get('guests');       
        List<Id> gstIdsList = getListOfGuestIds(items);
        Database.delete(gstIdsList, true);
        return 'deleted';
    }

    private static List<Id> getListOfGuestIds(List<Object> guestsIds){
        List<Id> gstList = new List<Id>();
        for(Object item: guestsIds){
            gstList.add(String.valueOf((item)));
        }
        return gstList;
    }


    private static String getOwnerCondition(BL_UserInfo me, String storeCode, List<String> caIdsList) {
        String ownerCondition = 'Assigned_CA__c = \'' + me.basicInfos.Id + '\'';
       
        if(String.isNotEmpty(storeCode) && me.basicInfos.TECH_IsManager__c ){
            ownerCondition =  'Brand_Experience_Variation__r.Store__r.RetailStoreId__c = \'' + storeCode + '\'';
        }
        if (!caIdsList.isEmpty() && me.basicInfos.TECH_IsManager__c){

            String caIds =  BL_Utils.convertToString(caIdsList);
            ownerCondition = 'Assigned_CA__c IN ' + caIds ;
        }
        return ownerCondition;
    }
}