force-app/main/default/objects/CLI_CliList__c/CLI_CliList__c.object-meta.xml
<CustomObject>
    <description>Create your list of clients</description>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CLI_CliList__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check if this is an active Client List.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IM_DeactivateExpiredClientListsBatch.cls
global class IM_DeactivateExpiredClientListsBatch implements Database.Batchable<sObject> {

    global database.querylocator start(Database.BatchableContext CD){
        string query  = 'SELECT Id, Active__c FROM CLI_CliList__c WHERE Active__c = TRUE AND ExpirationDate__c < YESTERDAY';
        return Database.getQueryLocator(query);   
    } 

    global void execute(Database.BatchableContext CD, List<CLI_CliList__c> cliLists){
        for(CLI_CliList__c cli: cliLists) {
            cli.Active__c = false;
        }
        update cliLists;
    }

    global void finish(Database.BatchableContext CD){}

}