force-app/main/default/objects/CLI_CliList__c/CLI_CliList__c.object-meta.xml
<CustomObject>
    <description>Create your list of clients</description>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CLI_CliList__c/fields/Offer_Code__c.field-meta.xml
<CustomField>
    <fullName>Offer_Code__c</fullName>
    <description>for Exclusive Experience campaigns</description>
    <label>Offer Code</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/fields/TECH_TempAccountIds__c.field-meta.xml
<CustomField>
    <fullName>TECH_TempAccountIds__c</fullName>
    <label>TECH Temp account ids</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/fields/Typology__c.field-meta.xml
<CustomField>
    <fullName>Typology__c</fullName>
    <description>for Exclusive Experience campaigns</description>
    <label>Typology</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IC_Config__c/IC_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>IC Config</label>
</CustomObject>

force-app/main/default/classes/IC_BatchCreateListMembers_Test.cls
/**
    About
    -----
    Description: Batch to Create Client List Members for Lists created on Targeted Client list page
    Create date: July 2016

    Details
    -------
    Test class for IC_BatchCreateListMembers

    Update History
    --------------
    July 2016 / Created by Balink
    
    Issues / TODOs
    --------------
*/
@isTest
public with sharing class IC_BatchCreateListMembers_Test {
    @TestSetup
    public static void setup() {
        String identityProfile = [SELECT Id FROM Profile WHERE Name = 'Identity User'][0].Id;
        insert new IC_Config__c(
            Name = 'Identity User',
            Value__c = identityProfile
        );
    }
    
    static testMethod void testLaunchSearch() {
        User u = IC_Test_Common.createTestUser();
        Account acc1 = IC_Test_Common.createPersonAccount('1515');
        Account acc2 = IC_Test_Common.createPersonAccount('1616');
        
        CLI_CliList__c clientList = IC_Test_Common.createClientList();
        clientList.TECH_TempAccountIds__c = '!' + acc1.id + '!' + acc2.id;
        clientList.Typology__c = 'Regular'; 
        clientList.Offer_Code__c = 'exclu_nba_1_2020 ';
        update clientList;
        
        
        //insert lAccount;
        System.runAs(u){ 
            Test.startTest();
        
            IC_BatchCreateListMembers testBatch = new IC_BatchCreateListMembers();
            Database.executeBatch(testBatch,1000);
            
            Test.stopTest();
        }
       
    }
}