force-app/main/default/objects/CLI_CliList__c/CLI_CliList__c.object-meta.xml
<CustomObject>
    <description>Create your list of clients</description>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_CliListMember__c/CLM_CliListMember__c.object-meta.xml
<CustomObject>
    <description>Customers in your client list.</description>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>CLM-{0}</displayFormat>
        <label>Client List Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_CliListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_CliListMember__c/fields/ClientList__c.field-meta.xml
<CustomField>
    <fullName>ClientList__c</fullName>
    <description>Client list which is containing this customer.</description>
    <inlineHelpText>Select the client list to contain this customer.</inlineHelpText>
    <label>Client List</label>
    <referenceTo>CLI_CliList__c</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/IC_BatchClMemberCleanUp_TEST.cls
@isTest
private class IC_BatchClMemberCleanUp_TEST {

 static testMethod void testBatch() {

        ID batchprocessid;
        CLI_CliList__c cl = IC_TestFactory.clientlistMembers();
        insert cl;
        CLM_CliListMember__c Clm = new CLM_CliListMember__c();
        Clm.Client__c = null;
        Clm.ClientList__c = Cl.Id;
        insert Clm;             
        

        IC_BatchClMemberCleanUp myBatch = new IC_BatchClMemberCleanUp();
        
        Test.startTest();
        batchprocessid = Database.executeBatch(myBatch,1000);
        Test.stopTest();
        
        List<CLM_CliListMember__c> lst = [SELECT Id FROM CLM_CliListMember__c WHERE Id = :Clm.Id];
        System.assertequals(lst.size(), 0);
        
    }

}