force-app/main/default/objects/CLI_CliList__c/CLI_CliList__c.object-meta.xml
<CustomObject>
    <description>Create your list of clients</description>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_CliListMember__c/CLM_CliListMember__c.object-meta.xml
<CustomObject>
    <description>Customers in your client list.</description>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>CLM-{0}</displayFormat>
        <label>Client List Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_CliListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_CliListMember__c/fields/ClientList__c.field-meta.xml
<CustomField>
    <fullName>ClientList__c</fullName>
    <description>Client list which is containing this customer.</description>
    <inlineHelpText>Select the client list to contain this customer.</inlineHelpText>
    <label>Client List</label>
    <referenceTo>CLI_CliList__c</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/IC_ClientListStatistics_CltTsk_VFCx_TEST.cls
@isTest
private class IC_ClientListStatistics_CltTsk_VFCx_TEST {

    static testMethod void myUnitTest() {
        CLI_CliList__c cli = IC_TestFactory.clientlistMembers();
        cli.Name = 'Test';
        cli.OwnerId = UserInfo.getUserId();
        insert cli;
        
        Account act = IC_testFactory.createAccount();
        act.OwnerId = UserInfo.getUserId();
        insert act;
        
        Contact ct = [Select Id From Contact WHERE accountId = :act.Id limit 1];
        
        CLM_CliListMember__c clm = new CLM_CliListMember__c(ClientList__c = cli.Id, Client__c = ct.Id);
        insert clm;
        
        Task tsk = IC_TestFactory.createTask();
        tsk.WhatId = act.Id;
        tsk.WhoId = ct.Id;
	    insert tsk;
        
        
        ApexPages.currentPage().getParameters().put('id',cli.Id);
        ApexPages.currentPage().getParameters().put('UserId',UserInfo.getUserId());
        IC_ClientListStatistics_ClientTask_VFCx ctrl = new IC_ClientListStatistics_ClientTask_VFCx();
    }
}