force-app/main/default/objects/ProductConfigurationDetail__c/ProductConfigurationDetail__c.object-meta.xml
<CustomObject>
    <label>Product Configuration Detail</label>
    <nameField>
        <label>Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configuration Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductSettings__c/ProductSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Product settings used for ProductReferential or ProductCatalogue objects (not possible by Custom Metadata Type with Formula fields)</description>
    <label>Product Settings</label>
</CustomObject>

force-app/main/default/objects/ProductSettings__c/fields/Fluid_Products_URL__c.field-meta.xml
<CustomField>
    <fullName>Fluid_Products_URL__c</fullName>
    <defaultValue>&quot;https://configure-published.fluidretail.net/prod/qa/customers/c1562/configureHtml/products&quot;</defaultValue>
    <label>Fluid Products URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ProductSettings__c/fields/Fluid_Products_URL_China__c.field-meta.xml
<CustomField>
    <fullName>Fluid_Products_URL_China__c</fullName>
    <label>Fluid Products URL (China)</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ProductSettings__c/fields/Fluid_Recipe_URL_China__c.field-meta.xml
<CustomField>
    <fullName>Fluid_Recipe_URL_China__c</fullName>
    <label>Fluid Recipe URL (China)</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ProductSettings__c/fields/FluidPictureUrl__c.field-meta.xml
<CustomField>
    <fullName>FluidPictureUrl__c</fullName>
    <description>Absolute path to get Fluid URL to display pictures (used in formula fields in Productatalogue__c, Favorite__c)
For example: &apos;https://configure-imagecomposer.fluidretail.net/recipe/&apos; + (recipe id) 33858728 + &apos;/image/&apos; + Front.jpg</description>
    <label>Fluid Picture Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MIY_ProductConfigCtrl_TEST.cls
@isTest
public with sharing class MIY_ProductConfigCtrl_TEST {

	@isTest
	static void test_getFluidDetails() {
		Test.setMock(HttpCalloutMock.class, new MockHttpResponse('successJsonFluidData', 'json'));
		List<ProductConfigurationDetail__c> configDetails = MIY_ProductConfigCtrl.getFluidDetails('45497832');
		System.assertEquals(5, configDetails.size());
	}
	@isTest
	static void test_getFluidRecipeUrl() {
		System.assertEquals(ProductSettings__c.getInstance().Fluid_Recipe_URL_China__c, MIY_ProductConfigCtrl.getFluidRecipeUrl(true));
		System.assertEquals(ProductSettings__c.getInstance().FluidPictureUrl__c, MIY_ProductConfigCtrl.getFluidRecipeUrl(false));
	}
	@isTest
	static void test_getFluidProductsUrl() {
		System.assertEquals(ProductSettings__c.getInstance().Fluid_Products_URL_China__c, MIY_ProductConfigCtrl.getFluidProductsUrl(true));
		System.assertEquals(ProductSettings__c.getInstance().Fluid_Products_URL__c, MIY_ProductConfigCtrl.getFluidProductsUrl(false));
	}
}