force-app/main/default/objects/TeamMember__c/TeamMember__c.object-meta.xml
<CustomObject>
    <label>TeamMember</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>TeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TeamMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamMember__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamMembersManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamMember__c/fields/TECH_UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>TECH_UniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>TECH_UniqueKey</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TeamMember__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-icon/main/default/classes/BL_ICON_TeamMembers_Helper.cls
global class BL_ICON_TeamMembers_Helper {
    public static List<Object> setTeamMembers(Map<String,Object>body) { 
        List<TeamMember__c> tmToUpsert = new List<TeamMember__c>();
        List<String> teamIds = new List<String>(); 
        for(Object o : (List<Object>)body.get('teamIds')){
           teamIds.add((String)o) ;
        }
        String teamIdsToString =  '\'' + String.join((teamIds), '\',\'') + '\'';
        Set<String> teamMemberIds = new Set<String>();
       
        List<User> teamUsers = new BL_EasyQuery()
                               .useCase(BL_ICON_Constants.USE_CASE_USER)     
                               .condition('Id in (' + teamIdsToString  + ')')
                               .executeQuery()
                               .getSObjects();
            
        List<TeamMember__c> tmToDelete = new BL_EasyQuery()
                               .useCase(BL_ICON_Constants.USE_CASE_TEAM_MEMBER)     
                               .condition('Manager__c = \'' + UserInfo.getUserId() + '\' AND User__c NOT in (' + teamIdsToString  + ')')
                               .executeQuery()
                               .getSObjects();
        if (tmToDelete.size() > 0) {
            delete tmToDelete;
        }

        for(User user : teamUsers) {
            TeamMember__c tm = new TeamMember__c(User__c = user.Id, Manager__c = UserInfo.getUserId(), TECH_UniqueKey__c = UserInfo.getUserId()+user.Id);
            tmToUpsert.add(tm);
        } 

        if (tmToUpsert.size()>0) {
           upsert tmToUpsert TECH_UniqueKey__c;
        }
        
        for(TeamMember__c tm : tmToUpsert) {
            teamMemberIds.add(tm.id); 
        } 
        String teamMemberIdsToString = '\'' + String.join(BL_Utils.toList(teamMemberIds), '\',\'') + '\'';
         return  new BL_EasyQuery()
                 .useCase(BL_ICON_Constants.USE_CASE_TEAM_MEMBER)  
                 .condition('Id in (' + teamMemberIdsToString  + ')')
                 .executeQuery()
                 .getMappedObjects();

    }

}