force-app/main/default/objects/Export_Purchases_Tracability__c/Export_Purchases_Tracability__c.object-meta.xml
<CustomObject>
    <description>Object to trace export of purchases</description>
    <label>Export Purchases Tracability</label>
    <nameField>
        <label>Export Purchases Tracability Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Export Purchases Tracabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Export_Purchases_Tracability__c/fields/API_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>API_Error_Message__c</fullName>
    <label>API Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Export_Purchases_Tracability__c/fields/contentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>contentDocumentId__c</fullName>
    <label>Content Document Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Export_Purchases_Tracability__c/fields/DreamId__c.field-meta.xml
<CustomField>
    <fullName>DreamId__c</fullName>
    <description>dream id of the client on whom we do the export</description>
    <label>DreamId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Export_Purchases_Tracability__c/fields/Public_File_Link__c.field-meta.xml
<CustomField>
    <fullName>Public_File_Link__c</fullName>
    <label>Public File Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Export_Purchases_Tracability__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Export In Progress</fullName>
            </value>
            <value>
                <fullName>Ready To Download</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Export_Purchases_Tracability__c/fields/versionId__c.field-meta.xml
<CustomField>
    <fullName>versionId__c</fullName>
    <label>versionId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/classes/ICX_PurchasesExport.cls
public with sharing class ICX_PurchasesExport {
  public ICX_PurchasesExport() {
  }

  //@AuraEnabled(cacheable=true)
  @AuraEnabled
  @future(callout=true)
  public static void createExportPurchase(String dreamId) {
    System.debug('createExportPurchase dreamId : ' + dreamId);
    String exportDateFormated = JSON.serialize(System.today())
      .replaceAll('-', '');
    String nameFormated = 'Transactions_' + dreamId + '_' + exportDateFormated;

    Export_Purchases_Tracability__c record = new Export_Purchases_Tracability__c(
      DreamId__c = dreamId,
      Status__c = 'New',
      Name = nameFormated.replaceAll('"', '')
    );

    insert record;
    System.debug('createExportPurchase after insert: ' + record);
  }

  public static String Client360_ExportPurchases(
    String dreamId,
    String newSearch,
    String scrollType,
    String refSaleID,
    String numTrans
  ) {
    String endPoint =
      'callout:MULESOFT_CLIENT_360_VISION/cst-eu/icn-client-vision-eapi/v1/clients/' +
      dreamId +
      '/purchases';

    try {
      HttpResponse response = ICX_WS_Client360.Client360_GetPurchases(
        endpoint,
        dreamId,
        newSearch,
        scrollType,
        refSaleID,
        numTrans
      );

      String statusCode = String.valueOf(response.getStatusCode());

      if (response.getStatusCode() == 200) {
        System.debug('The purchases response' + response.getBody());
        return response.getBody();
      } else {
        ICX_Utils.createIconicsLogs(
          'ICONICS - C360',
          'ICX_PurchasesExport',
          endPoint,
          response.getBody(),
          null,
          'ERROR',
          statusCode
        );
        ICX_Client360_API_Helper.errorObj errorObj = (ICX_Client360_API_Helper.errorObj) JSON.deserialize(
          response.getBody(),
          ICX_Client360_API_Helper.errorObj.class
        );
        throw new ICX_Client360_API_Helper.Client360Exception(
          ICX_WS_Client360.HandleError(
            statusCode,
            errorObj?.data?.errorType + ' ' + errorObj?.data?.errorDescription
          )
        );
      }
    } catch (Exception e) {
      System.debug('Error message : ' + e.getMessage());
      throw new ICX_Client360_API_Helper.Client360Exception(e.getMessage());
    }
  }

  public static List<ICX_Client360_API_Helper.data> getAllPurchasesClient(
    String dreamId
  ) {
    String newSearch = '1';
    String scrollType = 'NEXT';
    String refSaleID;
    String numTrans = '50';
    Boolean isMoreTransaction = true;
    List<ICX_Client360_API_Helper.data> finalPurchasesObj = new List<ICX_Client360_API_Helper.data>();

    while (isMoreTransaction) {
      try {
        String purchasesResult = Client360_ExportPurchases(
          dreamId,
          newSearch,
          scrollType,
          refSaleID,
          numTrans
        );
        ICX_Client360_API_Helper.purchasesObj purchasesObj = (ICX_Client360_API_Helper.purchasesObj) JSON.deserialize(
          purchasesResult,
          ICX_Client360_API_Helper.purchasesObj.class
        );
        List<ICX_Client360_API_Helper.data> data = new List<ICX_Client360_API_Helper.data>(
          purchasesObj.data
        );
        finalPurchasesObj.addAll(data);

        if (!finalPurchasesObj.isEmpty()) {
          if (
            Integer.valueOf(purchasesObj.data.size()) <
            Integer.valueOf(numTrans)
          ) {
            isMoreTransaction = false;
          }
          if (isMoreTransaction) {
            newSearch = '0';

            refSaleID = purchasesObj.data[data.size() - 1].wwsid;
          }
        } else
          break;
      } catch (Exception e) {
        system.debug('getAllPurchasesClient error: ' + e);
        throw new ICX_Client360_API_Helper.Client360Exception(e.getMessage());
      }
    }

    System.debug(
      'getAllPurchasesClient finalPurchasesObj: ' + finalPurchasesObj
    );
    ICX_Utils.createIconicsLogs(
      'ICONICS - C360',
      'ICX_PurchasesExport',
      'API-Vision/getPurchases',
      JSON.serialize(finalPurchasesObj),
      null,
      'INFO',
      '200'
    );
    return finalPurchasesObj;
  }

  public static void actionsForExportPurchases(
    string dreamId,
    string exportRecordId
  ) {
    Export_Purchases_Tracability__c record = [
      SELECT Id, Name
      FROM Export_Purchases_Tracability__c
      WHERE Id = :exportRecordId
    ];

    try {
      List<ICX_Client360_API_Helper.data> purchasesObj = getAllPurchasesClient(
        dreamId
      );

      if (!purchasesObj.isEmpty()) {
        record.Status__c = 'Export In Progress';
        update record;

        Set<String> listStoreNameUsed = new Set<String>();

        for (ICX_Client360_API_Helper.data purchase : purchasesObj) {
          listStoreNameUsed.add(purchase.purchaseStoreCode);
        }

        System.debug('listStoreNameUsed : ' + listStoreNameUsed);

        List<Store__c> listStoreName = [
          SELECT Id, Name, RetailStoreId__c
          FROM Store__c
          WHERE RetailStoreId__c IN :listStoreNameUsed
        ];

        Map<String, String> mapStore = new Map<String, String>();

        for (Store__c store : listStoreName) {
          mapStore.put(store.RetailStoreId__c, store.name);
        }

        List<String> csvRowValues = new List<String>();

        for (ICX_Client360_API_Helper.data purchase : purchasesObj) {
          String formattedDate = purchase.purchaseDate;
          String purchaseStoreCode = purchase.purchaseStoreCode != null
            ? mapStore.get(purchase.purchaseStoreCode)
            : null;
          String SKU;
          String productName;
          Integer quantity;
          Integer amountTTC;
          if (
            purchase.purchaseDetail != null &&
            purchase.purchaseDetail[0] != null
          ) {
            SKU = purchase.purchaseDetail[0].productSKU;
            productName = purchase.purchaseDetail[0].product.name;
            quantity = purchase.purchaseDetail[0].quantity;
            amountTTC = purchase.purchaseDetail[0].amountTTC;
          }

          String rowStr =
            '"' +
            formattedDate +
            '"' +
            ',' +
            '"' +
            purchaseStoreCode +
            '"' +
            ',' +
            '"' +
            SKU +
            '"' +
            ',' +
            '"' +
            productName +
            '"' +
            ',' +
            '"' +
            quantity +
            '"' +
            ',' +
            '"' +
            amountTTC +
            '"';
          csvRowValues.add(rowStr);
        }

        String separator = 'sep=,\n';
        String csvColumnHeader = 'Date, Store, SKU, Article, Quantity, Amount\n';
        String csvFile =
          separator +
          csvColumnHeader +
          String.join(csvRowValues, '\n');

        ContentVersion fileContent = new ContentVersion(
          VersionData = Blob.valueOf(csvFile),
          Title = record.Name,
          PathOnClient = 'Client Purchases_' + dreamId + '.csv'
        );

        insert fileContent;

        List<ContentDocument> contDoc = [
          SELECT Id
          FROM ContentDocument
          WHERE LatestPublishedVersionId = :fileContent.Id
          LIMIT 1
        ];

        record.versionId__c = fileContent.Id;
        record.contentDocumentId__c = contDoc[0].Id;
        update record;

        ContentDistribution conDis = new ContentDistribution(
          Name = fileContent.Title,
          ContentVersionId = fileContent.Id,
          PreferencesAllowViewInBrowser = true
        );

        insert conDis;

        List<ContentDistribution> publicLink = [
          SELECT Id, ContentDownloadUrl
          FROM ContentDistribution
          WHERE ContentVersionId = :fileContent.Id
          LIMIT 1
        ];

        record.Public_File_Link__c = publicLink[0].ContentDownloadUrl;
        record.Status__c = 'Ready To Download';
        update record;
        System.debug('actionsForExportPurchases record at the end : ' + record);
      } else {
        record.Status__c = 'Failed';
        record.API_Error_Message__c = 'API return an empty response : No data for this client';
        update record;
        System.debug(
          'actionsForExportPurchases record at the end else else : ' + record
        );
      }
    } catch (Exception e) {
      record.Status__c = 'Failed';
      record.API_Error_Message__c = 'Error API : ' + string.valueOf(e);
      update record;
      System.debug(
        'actionsForExportPurchases record at the end catch: ' + record
      );
    }
  }
}