force-app/main/default/objects/Logs__c/Logs__c.object-meta.xml
<CustomObject>
    <label>Logs</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logs__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <label>Apex Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Akamai_API</fullName>
            </value>
            <value>
                <fullName>ATG_API</fullName>
            </value>
            <value>
                <fullName>Ctrl_ProductCatalog</fullName>
            </value>
            <value>
                <fullName>Fractalist_API</fullName>
            </value>
            <value>
                <fullName>Google_Analytics_API</fullName>
            </value>
            <value>
                <fullName>ICX_GenesysExtensionPoint</fullName>
            </value>
            <value>
                <fullName>ICX_PurchasesExport</fullName>
            </value>
            <value>
                <fullName>ICX_WS_Client360</fullName>
            </value>
            <value>
                <fullName>ICX_WS_IXOPAY</fullName>
            </value>
            <value>
                <fullName>ICX_WS_Manual_Merge</fullName>
            </value>
            <value>
                <fullName>ICX_WS_NewsletterSubscription</fullName>
            </value>
            <value>
                <fullName>IDENTITY_AccountMatching_Utils</fullName>
            </value>
            <value>
                <fullName>IDENTITY_Login_CTRL</fullName>
            </value>
            <value>
                <fullName>IDENTITY_Registration_CTRL</fullName>
            </value>
            <value>
                <fullName>IDENTITY_RegistrationHandler</fullName>
            </value>
            <value>
                <fullName>IDENTITY_URLRewriter</fullName>
            </value>
            <value>
                <fullName>IDENTITY_UserManagement_BATCH</fullName>
            </value>
            <value>
                <fullName>IDENTITY_Utils</fullName>
            </value>
            <value>
                <fullName>IDENTITY_WS_AccountMatching</fullName>
            </value>
            <value>
                <fullName>IDENTITY_WS_Contactability</fullName>
            </value>
            <value>
                <fullName>IM_CheckPushNotifications</fullName>
            </value>
            <value>
                <fullName>IM_ClientListWS</fullName>
            </value>
            <value>
                <fullName>IM_FollowUp_WS</fullName>
            </value>
            <value>
                <fullName>IM_TeamManagment</fullName>
            </value>
            <value>
                <fullName>IM_WS_Assets</fullName>
            </value>
            <value>
                <fullName>IM_WS_CareService</fullName>
            </value>
            <value>
                <fullName>IM_WS_PushNotifications</fullName>
            </value>
            <value>
                <fullName>IM_WSAddCLMembers</fullName>
            </value>
            <value>
                <fullName>IM_WSConfig</fullName>
            </value>
            <value>
                <fullName>IM_WSRemoveCLMembers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Logs__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DEBUG</fullName>
                <default>true</default>
                <label>DEBUG</label>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogsSetting__mdt/LogsSetting__mdt.object-meta.xml
<CustomObject>
    <label>Logs Setting</label>
    <pluralLabel>Logs Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/LogsSetting__mdt/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <label>Apex Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Akamai_API</fullName>
            </value>
            <value>
                <fullName>ATG_API</fullName>
            </value>
            <value>
                <fullName>Fractalist_API</fullName>
            </value>
            <value>
                <fullName>Google_Analytics_API</fullName>
            </value>
            <value>
                <fullName>IDENTITY_AccountMatching_Utils</fullName>
            </value>
            <value>
                <fullName>IDENTITY_Login_CTRL</fullName>
            </value>
            <value>
                <fullName>IDENTITY_Registration_CTRL</fullName>
                <default>true</default>
                <label>IDENTITY_Registration_CTRL</label>
            </value>
            <value>
                <fullName>IDENTITY_RegistrationHandler</fullName>
            </value>
            <value>
                <fullName>IDENTITY_URLRewriter</fullName>
            </value>
            <value>
                <fullName>IDENTITY_UserManagement_BATCH</fullName>
            </value>
            <value>
                <fullName>IDENTITY_Utils</fullName>
            </value>
            <value>
                <fullName>IDENTITY_WS_AccountMatching</fullName>
            </value>
            <value>
                <fullName>IDENTITY_WS_Contactability</fullName>
            </value>
            <value>
                <fullName>IM_CheckPushNotifications</fullName>
            </value>
            <value>
                <fullName>IM_ClientListWS</fullName>
            </value>
            <value>
                <fullName>IM_FollowUp_WS</fullName>
            </value>
            <value>
                <fullName>IM_TeamManagment</fullName>
            </value>
            <value>
                <fullName>IM_WS_Assets</fullName>
            </value>
            <value>
                <fullName>IM_WS_CareService</fullName>
            </value>
            <value>
                <fullName>IM_WS_PushNotifications</fullName>
            </value>
            <value>
                <fullName>IM_WSAddCLMembers</fullName>
            </value>
            <value>
                <fullName>IM_WSConfig</fullName>
            </value>
            <value>
                <fullName>IM_WSRemoveCLMembers</fullName>
            </value>
            <value>
                <fullName>MarketingCloud_API</fullName>
            </value>
            <value>
                <fullName>MYCC_WS_Client</fullName>
            </value>
            <value>
                <fullName>Notification_Sender</fullName>
            </value>
            <value>
                <fullName>SM_WS01_SocialMediaIdentifiers</fullName>
            </value>
            <value>
                <fullName>Tencent_API</fullName>
            </value>
            <value>
                <fullName>BL_ICON_TermsConditions</fullName>
            </value>
            <value>
                <fullName>Line</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogsSetting__mdt/fields/Batch_Limit__c.field-meta.xml
<CustomField>
    <fullName>Batch_Limit__c</fullName>
    <label>Batch_Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogsSetting__mdt/fields/Clean_Up_Every__c.field-meta.xml
<CustomField>
    <fullName>Clean_Up_Every__c</fullName>
    <inlineHelpText>in days</inlineHelpText>
    <label>Clean Up Every</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogsSetting__mdt/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
                <default>true</default>
                <label>ALL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LogsSetting__mdt/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Always run</fullName>
            </value>
            <value>
                <fullName>Per-User</fullName>
                <default>true</default>
                <label>Per-User</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Logs_Cleaner_BATCH.cls
global class Logs_Cleaner_BATCH implements Database.Batchable<sObject> {
    Integer batchLimit = 10000;
    String query;
    DateTime dt = System.now().addDays(-35);
    Map<String,Map<String,LogsSetting__mdt>> settings;
    Integer minimumCleanUpDays;
    
    global Logs_Cleaner_BATCH() {
        //query = 'SELECT Id, Apex_Class__c, Level__c, CreatedDate FROM Logs__c WHERE CreatedDate >: dt';

        // GET SETTINGS 
        List<LogsSetting__mdt> settings_list = [
            SELECT Apex_Class__c, Mode__c, Level__c, Clean_Up_Every__c, Batch_Limit__c
            FROM LogsSetting__mdt 
            WHERE IsActive__c = true
        ];

        settings = new Map<String,Map<String,LogsSetting__mdt>>();
        for(LogsSetting__mdt setting : settings_list){
            
            
             if (setting.Batch_Limit__c != null) {
                batchLimit = setting.Batch_Limit__c.intValue();
                
            }
            if(settings.get(setting.Apex_Class__c) == null){
                settings.put(setting.Apex_Class__c, new Map<String,LogsSetting__mdt>());
            }

            if(String.isEmpty(setting.Level__c) || setting.Level__c == 'ALL'){
                settings.get(setting.Apex_Class__c).put('ALL', setting);
            }
            else {
                settings.get(setting.Apex_Class__c).put(setting.Level__c, setting);
            }
        }
        
        query = 'SELECT Id, Apex_Class__c, Level__c, CreatedDate FROM Logs__c WHERE CreatedDate >: dt LIMIT ' + batchLimit;
        System.debug ('query' + query);
        Global_Settings__mdt minimumCleanUp = Global_Settings__mdt.getInstance('Logs_Cleaner_Minimum_Clean_Up_Days');
        minimumCleanUpDays = minimumCleanUp != null ? Integer.valueOf(minimumCleanUp.Value__c) * -1 : -7;

    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {

        List<Logs__c> toDelete = new List<Logs__c>();

        for(Logs__c log : (List<Logs__c>)scope){

            // REMOVE LOG WITHOUT APEX CLASS AFTER X DAYS
            if(String.isEmpty(log.Apex_Class__c) && log.CreatedDate <= System.now().addDays(minimumCleanUpDays)){
                toDelete.add(log);
            }
            else if(!String.isEmpty(log.Apex_Class__c)){

                // REMOVE LOG WITHOUT SETTINGS AFTER X DAYS
                if(settings.get(log.Apex_Class__c) == null && log.CreatedDate <= System.now().addDays(minimumCleanUpDays)){
                    toDelete.add(log);
                }
                else if(settings.get(log.Apex_Class__c) != null){

                    // ACCORDING  SETTINGS BY LEVEL
                    if(settings.get(log.Apex_Class__c).get(log.Level__c) != null){
                        Integer days = Integer.valueOf(settings.get(log.Apex_Class__c).get(log.Level__c).Clean_Up_Every__c);

                        if(log.CreatedDate <= System.now().addDays(-days)){
                            toDelete.add(log);
                        }
                    }
                    // ACCORDING SETTINGS BY APEX CLASS
                    else if(settings.get(log.Apex_Class__c).get('ALL') != null){
                        Integer days = Integer.valueOf(settings.get(log.Apex_Class__c).get('ALL').Clean_Up_Every__c);

                        if(log.CreatedDate <= System.now().addDays(-days)){
                            toDelete.add(log);
                        }
                    }
                    // REMOVE LOG WITHOUT SETTINGS AFTER X DAYS
                    else if(log.CreatedDate <= System.now().addDays(minimumCleanUpDays)){
                        toDelete.add(log);
                    }
                }
            }
        }

        delete toDelete;
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}