force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{0000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CARE SERVICE</fullName>
            </value>
            <value>
                <fullName>DISTANT CARE SERVICE</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE EXPERIENCE</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE SALES</fullName>
                <isActive>false</isActive>
                <label>EXCLUSIVE SALES</label>
            </value>
            <value>
                <fullName>ICON</fullName>
            </value>
            <value>
                <fullName>ONLINE APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>POST CONTACT</fullName>
            </value>
            <value>
                <fullName>WECHAT DIAMOND APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>WECHAT ONLINE APPOINTMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <label>Message Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Real_Time__c.field-meta.xml
<CustomField>
    <fullName>Real_Time__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Notification sent at the creation of the record</inlineHelpText>
    <label>Real Time</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Relay_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Relay_Datetime__c</fullName>
    <label>Relay Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
                <default>true</default>
                <label>CREATED</label>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>NOT SENT</fullName>
            </value>
            <value>
                <fullName>READY TO SEND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Settings__mdt/Notification_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Notification Settings</label>
    <pluralLabel>Notifications Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Notification_Settings__mdt/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARE SERVICE</fullName>
                <default>true</default>
                <label>CARE SERVICE</label>
            </value>
            <value>
                <fullName>ICON</fullName>
            </value>
            <value>
                <fullName>ONLINE APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>POST CONTACT</fullName>
            </value>
            <value>
                <fullName>WECHAT ONLINE APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE EXPERIENCE</fullName>
            </value>
            <value>
                <fullName>DISTANT CARE SERVICE</fullName>
            </value>
            <value>
                <fullName>WECHAT DIAMOND APPOINTMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Settings__mdt/fields/Delay_Time__c.field-meta.xml
<CustomField>
    <fullName>Delay_Time__c</fullName>
    <description>Hours</description>
    <inlineHelpText>Hours</inlineHelpText>
    <label>Delay Time</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification_Settings__mdt/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <label>Message Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Notification_Sender_BATCH.cls
global class Notification_Sender_BATCH implements Database.Batchable<sObject> {
    
    String query;
    Map<String,Map<String,Notification_Settings__mdt>> settings;
    
    global Notification_Sender_BATCH () {
        query = 'SELECT Id, Application__c, Message_Id__c, CreatedDate, Status__c, Relay_Datetime__c FROM Notification__c WHERE Status__c = \'CREATED\' AND Real_Time__c != true ';

        // GET SETTINGS 
        List<Notification_Settings__mdt> settings_list = [
            SELECT Application__c, Message_Id__c, Delay_Time__c
            FROM Notification_Settings__mdt 
        ];

        settings = new Map<String,Map<String,Notification_Settings__mdt>>();
        for(Notification_Settings__mdt setting : settings_list){

            if(settings.get(setting.Application__c) == null){
                settings.put(setting.Application__c, new Map<String,Notification_Settings__mdt>());
            }

            settings.get(setting.Application__c).put(setting.Message_Id__c, setting);
        }

        System.debug('SETTINGS: ' + settings);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {

        List<Notification__c> toUpdate = new List<Notification__c>();

        for(Notification__c note : (List<Notification__c>)scope){

            // UPDATE NOTIFICATIONS STATUS AFTER *** HOURS
            if(settings.get(note.Application__c) != null){

                if(settings.get(note.Application__c).get(note.Message_Id__c) != null){

                    // ACCORDING TO NOTIFICATIONS By RealTime
                    if(note.Relay_Datetime__c != null){
                        if(note.Relay_Datetime__c <= System.now()){
                            note.Status__c = 'READY TO SEND';
                            toUpdate.add(note);
                        }
                    }
                    // ACCORDING TO SETTINGS BY MessageId
                    else{
                        Integer hours = Integer.valueOf(settings.get(note.Application__c).get(note.Message_Id__c).Delay_Time__c);
                        if(note.CreatedDate <= System.now().addHours(-hours)){
                            note.Status__c = 'READY TO SEND';
                            toUpdate.add(note);
                        }
                    }
                }
            }
        }

        update toUpdate;
    }
    
    global void finish(Database.BatchableContext BC) {}
}