force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{0000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EMAIL TEMPLATE</fullName>
            </value>
            <value>
                <fullName>LINE</fullName>
            </value>
            <value>
                <fullName>EMAIL MARKETING CLOUD</fullName>
            </value>
            <value>
                <fullName>PUSH NOTIFICATION</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WECHAT</fullName>
            </value>
            <value>
                <fullName>REAL TIME</fullName>
            </value>
            <value>
                <fullName>SMS MARKETING CLOUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <label>Message Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
                <default>true</default>
                <label>CREATED</label>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>NOT SENT</fullName>
            </value>
            <value>
                <fullName>READY TO SEND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarketingCloud_API.cls
public with sharing class MarketingCloud_API {
    
    public static Map<String,Object> sendNotification(Notification__c notification, Map<String,Object> params){

        Map<String,Object> session = getSessionId();

        Account client = [SELECT Id, PersonEmail, PersonContactId
            FROM Account
            WHERE Id = :notification.Client__c];

        Map<String,Object> body = new Map<String,Object>{
            'ContactKey' => client.PersonContactId,
            'EventDefinitionKey' => SETTINGS.get(EVENT_KEY),
            'Data' => new Map<String,Object>{}
        };

        // Settings
        ((Map<String,Object>)body.get('Data')).put('Message_Id', (Object)notification.Message_Id__c);
        ((Map<String,Object>)body.get('Data')).put('email', client.PersonEmail);
        ((Map<String,Object>)body.get('Data')).put('account_id', client.Id);
        ((Map<String,Object>)body.get('Data')).put('contact_id', client.PersonContactId);

        // Parameters
        for(String key : params.keySet()){
            ((Map<String,Object>)body.get('Data')).put(key, (Object)params.get(key));
        }
        system.debug(body);
        HTTP_Utils response = new HTTP_Utils()
            .post(getDomain(null) + SETTINGS.get(EVENT))
            .header('Authorization', 'Bearer ' + session.get('access_token'))
            .header('Content-Type', 'application/json')
            .body(JSON.serialize(body))
            .call();

            System.debug('REQUEST BODY: ' + JSON.serialize(body));

        System.debug('RESPONSE CODE: ' + response.statusCode());
        System.debug('RESPONSE BODY: ' + response.responseBody());

        // INSERT IN DB
        insert notification;
        insert Notification_Sender.setNotificationParameters(params, notification.channel__c, notification.external_Id__c);

        Map<String,Object> data = (Map<String,Object>)JSON.deserializeUntyped(response.responseBody());

        if(response.statusCode() == 201 || response.statusCode() == 200) {
            notification.Status__c = 'CLOSED';
            upsert notification;
        }
        else{
            new Logs( new Map<String,Object> {
                'level' => 'ERROR', 
                'apexClass' => 'MarketingCloud_API', 
                'category' => 'CALLOUT',
                'http' => response,
                'message' => data.get('message'),
                'type' => String.valueOf((Decimal)data.get('errorcode'))
            });
        }


        return data;
    }

    /*
    *** DESCRIPTION GET Session number and its confirmation, need to call other API
    *** RETURN      Map of session parameters
    */
    public static Map<String,Object> getSessionId(){

        Map<String,Object> body = new Map<String,Object>{
            'grant_type' => 'client_credentials',
            'client_id' => SETTINGS.get(USERNAME),
            'client_secret' => SETTINGS.get(PASSWORD),
            'scope' => SETTINGS.get(SCOPE)
        };
    
        HTTP_Utils response = new HTTP_Utils()
            .post(getDomain(SETTINGS.get(TOKEN)))
            .header('Content-Type', 'application/json')
            .body(JSON.serialize(body))
            .call();

        System.debug('RESPONSE BODY: ' + response.responseBody());

        if(response.statusCode() == 200){
            return (Map<String,Object>)JSON.deserializeUntyped(response.responseBody());
        }
        
        throw new CustomException(response.responseBody());
    }

    /*
    *** DESCRIPTION GET Endpoint: URL
    *** RETURN      String endpoint 
    */
    public static String getDomain(String url){

        if(String.isEmpty(url)){
            url = SETTINGS.get(ENDPOINT);
        }

        url = url.replace('{org}', SETTINGS.get(ORG));

        return url;
    }

    public static Map<String,String> SETTINGS;
    public final static String ENDPOINT;
    public final static String USERNAME;
    public final static String PASSWORD;
    public final static String EVENT;
    public final static String TOKEN;
    public final static String ORG;
    public final static String EVENT_KEY;
    public final static String SCOPE;

    static {
        SETTINGS = ThirdParty_Utils.getSettings('Marketing_Cloud');

        ENDPOINT = 'endpoint';
        USERNAME = 'username';
        PASSWORD = 'password';
        TOKEN = 'token';
        EVENT = 'event';
        EVENT_KEY = 'eventDefinitionKey';
        ORG = 'org';
        SCOPE = 'scope';
    }

    public class CustomException extends Exception {}
}