force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{0000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CARE SERVICE</fullName>
            </value>
            <value>
                <fullName>DISTANT CARE SERVICE</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE EXPERIENCE</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE SALES</fullName>
                <isActive>false</isActive>
                <label>EXCLUSIVE SALES</label>
            </value>
            <value>
                <fullName>ICON</fullName>
            </value>
            <value>
                <fullName>ONLINE APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>POST CONTACT</fullName>
            </value>
            <value>
                <fullName>WECHAT DIAMOND APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>WECHAT ONLINE APPOINTMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <label>Message Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/tech_address__c.field-meta.xml
<CustomField>
    <fullName>tech_address__c</fullName>
    <label>tech_address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/classes/Wechat_MP_Notification_Center_Test.cls
@IsTest
public class Wechat_MP_Notification_Center_Test {
@IsTest static void testMPNotification_Center() {
		User u = IC_Test_Common.prepareTestUser('System Administrator');
        u.DefaultStore__c = '1234';
        insert u;
        Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
        insert store;
		Notification__c n =  new Notification__c(Message_Id__c = 'OSAW2',External_Id__c = '32350c71-3464-405f-7ed4-8d57b33dc71d',application__c = 'WECHAT ONLINE APPOINTMENT');
        insert n;
        Map<String, Object> params = new Map<String, Object>{'date_osa'=>'test','local_name'=>'test','tech_address__c'=>'test','appointmentType'=>'Event'};
        Wechat_MP_Notification_Center.sendNotification(n,params);
    }
    
}