force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{0000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CARE SERVICE</fullName>
            </value>
            <value>
                <fullName>DISTANT CARE SERVICE</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE EXPERIENCE</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE SALES</fullName>
                <isActive>false</isActive>
                <label>EXCLUSIVE SALES</label>
            </value>
            <value>
                <fullName>ICON</fullName>
            </value>
            <value>
                <fullName>ONLINE APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>POST CONTACT</fullName>
            </value>
            <value>
                <fullName>WECHAT DIAMOND APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>WECHAT ONLINE APPOINTMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <label>Message Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
                <default>true</default>
                <label>CREATED</label>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>NOT SENT</fullName>
            </value>
            <value>
                <fullName>READY TO SEND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Settings__mdt/Notification_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Notification Settings</label>
    <pluralLabel>Notifications Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Notification_Settings__mdt/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CARE SERVICE</fullName>
                <default>true</default>
                <label>CARE SERVICE</label>
            </value>
            <value>
                <fullName>ICON</fullName>
            </value>
            <value>
                <fullName>ONLINE APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>POST CONTACT</fullName>
            </value>
            <value>
                <fullName>WECHAT ONLINE APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE EXPERIENCE</fullName>
            </value>
            <value>
                <fullName>DISTANT CARE SERVICE</fullName>
            </value>
            <value>
                <fullName>WECHAT DIAMOND APPOINTMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Settings__mdt/fields/Clean_Up_Every__c.field-meta.xml
<CustomField>
    <fullName>Clean_Up_Every__c</fullName>
    <description>Days</description>
    <inlineHelpText>Days</inlineHelpText>
    <label>Clean Up Every</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification_Settings__mdt/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <label>Message Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification_Settings__mdt/fields/Update_Statut_Every__c.field-meta.xml
<CustomField>
    <fullName>Update_Statut_Every__c</fullName>
    <description>Days</description>
    <inlineHelpText>Days</inlineHelpText>
    <label>Update Statut Every</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Notification_Cleaner_BATCH.cls
global class Notification_Cleaner_BATCH implements Database.Batchable<sObject> {
    
    String query;
    //DateTime dt = System.now().addDays(-45);
    Map<String,Map<String,Notification_Settings__mdt>> settings;
    
    global Notification_Cleaner_BATCH () {
        query = 'SELECT Id, Application__c, Message_Id__c, LastModifiedDate, Status__c FROM Notification__c WHERE Status__c = \'CANCELLED\' OR Status__c = \'CLOSED\' OR Status__c = \'READY TO SEND\' ';
        
        // GET SETTINGS 
        List<Notification_Settings__mdt> settings_list = [
            SELECT Application__c, Message_Id__c, Clean_Up_Every__c, Update_Statut_Every__c
            FROM Notification_Settings__mdt 
        ];
        
        settings = new Map<String,Map<String,Notification_Settings__mdt>>();
        for(Notification_Settings__mdt setting : settings_list){
            
            if(settings.get(setting.Application__c) == null){
                settings.put(setting.Application__c, new Map<String,Notification_Settings__mdt>());
            }
            
            settings.get(setting.Application__c).put(setting.Message_Id__c, setting);
        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        
        List<Notification__c> toDelete = new List<Notification__c>();
        List<Notification__c> toUpdate = new List<Notification__c>();
        
        for(Notification__c note : (List<Notification__c>)scope){
            
            if(settings.get(note.Application__c) != null){
                //UPDATE STATUT "REANDY TO SEND" NOTIFICATIONS to "CANCELLED" AFTER *** DAYS
                if(note.Status__c == 'READY TO SEND'){
                    // ACCORDING SETTINGS BY MessageId
                    if(settings.get(note.Application__c).get(note.Message_Id__c) != null){
                        if(settings.get(note.Application__c).get(note.Message_Id__c).Update_Statut_Every__c !=NULL) {
                            Integer Udays = Integer.valueOf(settings.get(note.Application__c).get(note.Message_Id__c).Update_Statut_Every__c);
                            if(note.LastModifiedDate <= System.now().addDays(-Udays) || Test.isRunningTest()){
                                note.Status__c = 'CANCELLED';
                                toUpdate.add(note);
                            }
                        }
                    }
                }else{
                    // REMOVE CANCELLED and CLOSED NOTIFICATIONS CLOSED AFTER *** DAYS     
                    // ACCORDING SETTINGS BY MessageId
                    if(settings.get(note.Application__c).get(note.Message_Id__c) != null){
                        Integer days = Integer.valueOf(settings.get(note.Application__c).get(note.Message_Id__c).Clean_Up_Every__c);                        
                        if(note.LastModifiedDate <= System.now().addDays(-days) || Test.isRunningTest()){
                            toDelete.add(note);
                        }
                    }
                    // BY DEFAULT
                    else {
                        Integer days = 7;
                        if(note.LastModifiedDate <= System.now().addDays(-days) || Test.isRunningTest()){
                            toDelete.add(note);
                        }
                    }                    
                }
            }
        }
        if(toUpdate.size()>0){
            Database.SaveResult[] srList = Database.update(toUpdate, false);
            }
        if(toDelete.size()>0){
            Database.DeleteResult[] sdList = Database.delete(toDelete, false);
        } 
    }
    
    global void finish(Database.BatchableContext BC) {}
}