force-app/main/default/objects/due__Diduenjoy_Feedback__c/due__Diduenjoy_Feedback__c.object-meta.xml
<CustomObject>
    <label>Diduenjoy Feedback</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diduenjoy Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__InternalId__c.field-meta.xml
<CustomField>
    <fullName>due__InternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>InternalId</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Last_Resolution_Date__c.field-meta.xml
<CustomField>
    <fullName>due__Last_Resolution_Date__c</fullName>
    <label>Last Resolution Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Solved__c.field-meta.xml
<CustomField>
    <fullName>due__Solved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Status__c.field-meta.xml
<CustomField>
    <fullName>due__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>live</fullName>
                <default>true</default>
                <label>live</label>
            </value>
            <value>
                <fullName>soft_deleted</fullName>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VO_Survey__c/VO_Survey__c.object-meta.xml
<CustomObject>
    <label>Voice</label>
    <nameField>
        <displayFormat>Survey-{00000000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VO_Survey__c/fields/FeedbackID__c.field-meta.xml
<CustomField>
    <fullName>FeedbackID__c</fullName>
    <externalId>true</externalId>
    <label>Feedback ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/LastResolutionDate__c.field-meta.xml
<CustomField>
    <fullName>LastResolutionDate__c</fullName>
    <label>Last Resolution Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Solved__c.field-meta.xml
<CustomField>
    <fullName>Solved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Default value equal to New. Changed to closed if new or pending 2 months after answer date. Changed to No action if the channel equals to No action (old voice)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>live</fullName>
            </value>
            <value>
                <fullName>soft_deleted</fullName>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>No action</fullName>
                <default>true</default>
                <label>No action</label>
            </value>
            <value>
                <fullName>noShow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Diduenjoy_FeedbackTriggerHandler.cls
/**
    @Author : ouramdane.aouci
    Desc :    event handler on the due__Diduenjoy_Feedback Object
    V 1.0 :   08/06/2023
*/
public class Diduenjoy_FeedbackTriggerHandler {
    
    //Update some synchronized Voice fields when updated in Due_Feedback
    public static void afterUpdate(List<due__Diduenjoy_Feedback__c> newList, Map<Id, due__Diduenjoy_Feedback__c> oldMap){
        
        System.debug('newList Size: '+newList.size());
        //Collect only the records concerned by the treatment
        Map<String, due__Diduenjoy_Feedback__c> dueFeedbackMap = new Map<String, due__Diduenjoy_Feedback__c>();
        
        for(due__Diduenjoy_Feedback__c dueFeedback : newList){
            if(dueFeedback.due__Status__c != oldMap.get(dueFeedback.Id).due__Status__c 
               || dueFeedback.due__Solved__c != oldMap.get(dueFeedback.Id).due__Solved__c 
               || dueFeedback.due__Last_Resolution_Date__c != oldMap.get(dueFeedback.Id).due__Last_Resolution_Date__c){
                   //Include this record
                   dueFeedbackMap.put(dueFeedback.due__InternalId__c, dueFeedback);
               }
        }
        
        if(dueFeedbackMap.size() > 0){
            //Retrieve Matching Surveys
            List<VO_Survey__c> surveysToUpdateList = [SELECT Id, Status__c, Solved__c, LastResolutionDate__c, FeedbackID__c FROM VO_Survey__c WHERE FeedbackID__c IN :dueFeedbackMap.keySet()];
            
            if(surveysToUpdateList.size() > 0){
                System.debug('surveysToUpdateList Size: '+surveysToUpdateList.size());
                due__Diduenjoy_Feedback__c dueF;    
                
                for(VO_Survey__c survey : surveysToUpdateList){
                    if(dueFeedbackMap.containsKey(survey.FeedbackID__c)){
                        dueF = dueFeedbackMap.get(survey.FeedbackID__c);
                        if(survey.Status__c != dueF.due__Status__c){
                            survey.Status__c = dueF.due__Status__c;
                        }
                        if(survey.Solved__c != dueF.due__Solved__c){
                            survey.Solved__c = dueF.due__Solved__c;
                        }
                        if(survey.LastResolutionDate__c != dueF.due__Last_Resolution_Date__c){
                            survey.LastResolutionDate__c = dueF.due__Last_Resolution_Date__c;
                        }
                    }
                }
                
                UPDATE surveysToUpdateList;
            }
        }
    }
}