force-app/main/default/objects/Exclusive_Campaign_Order__c/Exclusive_Campaign_Order__c.object-meta.xml
<CustomObject>
    <label>Exclusive Campaign Order</label>
    <nameField>
        <displayFormat>ECO-{000000}</displayFormat>
        <label>Exclusive Campaign Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusive Campaign Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Exclusive_Campaign_Order__c/fields/Reserved__c.field-meta.xml
<CustomField>
    <fullName>Reserved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reserved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exclusive_Campaign_Order__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Name of the Store</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Exclusive Campaign Orders</relationshipLabel>
    <relationshipName>Exclusive_Campaign_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exclusive_Campaign_Product__c/Exclusive_Campaign_Product__c.object-meta.xml
<CustomObject>
    <label>Exclusive Campaign Product</label>
    <nameField>
        <label>Exclusive Campaign Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exclusive Campaign Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exclusive_Campaign_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Description/ Type of the Status</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <label>Allocation</label>
    <nameField>
        <label>Quota Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/Exclusive_Campaign_Product__c.field-meta.xml
<CustomField>
    <fullName>Exclusive_Campaign_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exclusive Campaign Product</label>
    <referenceTo>Exclusive_Campaign_Product__c</referenceTo>
    <relationshipLabel>Quotas</relationshipLabel>
    <relationshipName>Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Reserved__c.field-meta.xml
<CustomField>
    <fullName>Reserved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Reserved ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <formula>&quot;2022-&quot;+ TEXT(MANAGEMENT_ZONE_LEVEL__c) +&quot;-&quot;+ Exclusive_Campaign_Product__r.Name+&quot;-&quot;+Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>UNIQUE Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Pre-Reserved</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Quotas</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/TECH_ZONE__c.field-meta.xml
<CustomField>
    <fullName>TECH_ZONE__c</fullName>
    <formula>CASE( Zone_LVL__c ,
&apos;AMERICAS&apos;, &apos;3&apos;,
&apos;EMEA&apos;, &apos;15&apos;,
&apos;JAPAN&apos;, &apos;2&apos;,
&apos;ASIA SOUTH&apos;, &apos;14&apos;,
&apos;ASIA NORTH&apos;, &apos;13&apos;,
&apos;CHINA&apos;, &apos;CHINA&apos;,
&apos;KOREA&apos;, &apos;KOREA&apos;,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_ZONE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Zone_LVL__c.field-meta.xml
<CustomField>
    <fullName>Zone_LVL__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AMERICAS</fullName>
            </value>
            <value>
                <fullName>ASIA NORTH</fullName>
            </value>
            <value>
                <fullName>ASIA SOUTH</fullName>
            </value>
            <value>
                <fullName>CENTRAL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>KOREA</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
                <label>MAINLAND CHINA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/MGMT_ZONE_SUB_LEVEL1__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL1__c</fullName>
    <description>Contains the code/translation for the first sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MANAGEMENT_ZONE_LEVEL__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>1071</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>151</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BARBADE</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILE</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>COLOMBIA</fullName>
            </value>
            <value>
                <fullName>CYPRUS</fullName>
            </value>
            <value>
                <fullName>CZECH REPUBLIC</fullName>
            </value>
            <value>
                <fullName>DENMARK</fullName>
            </value>
            <value>
                <fullName>DOMINICAIN REPUBLIC</fullName>
            </value>
            <value>
                <fullName>FINLAND</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>GREECE</fullName>
            </value>
            <value>
                <fullName>GUAM</fullName>
            </value>
            <value>
                <fullName>HONG KONG</fullName>
            </value>
            <value>
                <fullName>HUNGARY</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDONESIA</fullName>
            </value>
            <value>
                <fullName>IRELAND</fullName>
            </value>
            <value>
                <fullName>ISRAEL</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>JORDANIE</fullName>
            </value>
            <value>
                <fullName>KOREA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/MGMT_ZONE_SUB_LEVEL1__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL1__c</fullName>
    <description>Contains the code/translation for the first sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MANAGEMENT_ZONE_LEVEL__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>151</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>1231</fullName>
            </value>
            <value>
                <fullName>1071</fullName>
            </value>
            <value>
                <fullName>1111</fullName>
            </value>
            <value>
                <fullName>1151</fullName>
            </value>
            <value>
                <fullName>1191</fullName>
            </value>
            <value>
                <fullName>1271</fullName>
            </value>
            <value>
                <fullName>1311</fullName>
            </value>
            <value>
                <fullName>1351</fullName>
            </value>
            <value>
                <fullName>1391</fullName>
            </value>
            <value>
                <fullName>391</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Tr_ExclusiveCampaignOrder_Handler.cls
/**
 * @description       : 
 * @author            : peyo basso
 * @group             : 
 * @last modified on  : 31-05-2022
 * @last modified by  : PEYO BASSO
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   31-05-2022   peyo basso   Initial Version  
**/
public with sharing class Tr_ExclusiveCampaignOrder_Handler {

    public static void handleTrigger(List<Exclusive_Campaign_Order__c> newList, Map<Id, Exclusive_Campaign_Order__c> newMap,  System.TriggerOperation triggerEvent) {
        switch on triggerEvent {
            when BEFORE_INSERT{
              //  checkSerialNumberExists(newList[0]);
            }
            when BEFORE_UPDATE{
              //  checkSerialNumberExists(newList[0]);
            }
            
        }
    }
 
 static public Boolean checkIfUserHasAssignedPermissionSet(id userid, String permissionSetName) {
    List<PermissionSetAssignment> psas = [ select Id from PermissionSetAssignment where PermissionSetId IN ( select Id from PermissionSet where Name = :permissionSetName) and AssigneeId =:userid];
    return psas.size() > 0;
}
 
 @AuraEnabled(Cacheable=true)
 public static List <Quota__c> getArtyStats() {
     Id CurrentUserId=UserInfo.getUserId();
     List<User> Userinfos= [select id,username,tolabel(MANAGEMENT_ZONE_LEVEL__c),country__c,	tolabel(MGMT_ZONE_SUB_LEVEL1__c),tolabel(DefaultStore__c) from user where id=:CurrentUserId limit 1];
     string ManagementZonelevel=Userinfos[0].DefaultStore__c;
     string Country=Userinfos[0].country__c;
     string Zone=Userinfos[0].MANAGEMENT_ZONE_LEVEL__c;


     System.debug('ManagementZonelevel*****' +ManagementZonelevel);
     System.debug('Country*****' +Country);
     System.debug('Zone*****' +Zone);


     Boolean hasPermission =checkIfUserHasAssignedPermissionSet(CurrentUserId,'ArtyCappucines_Corporate');
     List<Quota__c> contList =new List<Quota__c>();
     if(hasPermission){
        contList = [ SELECT id,Zone_LVL__c,Name,Store__c,Store__r.Name,	Exclusive_Campaign_Product__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
        FROM Quota__c 
         ];
     }else{
        if(country!=null && (country.contains('CHINA')||country.contains('KOREA'))){
         contList = [ SELECT id,Name,Zone_LVL__c,	TECH_ZONE__c ,Exclusive_Campaign_Product__c,Status__c,Store__r.Name,Store__r.StoreCountry__c,Store_Country__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
                                FROM Quota__c where Status__c='Available' and TECH_ZONE__c =:country  /*and Store__r.Name=:ManagementZonelevel*/
                                 ];
                                 System.debug('ManagementZonelevel*****' +ManagementZonelevel);

                                }
                            else{
                                if(Zone=='ASIA NORTH' ){
                                 
                                contList = [ SELECT id,TECH_ZONE__c ,Zone_LVL__c,Name,Status__c,	Exclusive_Campaign_Product__c,Store__r.Name,Store_Country__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
                                FROM Quota__c where Status__c='Available' and tolabel(MANAGEMENT_ZONE_LEVEL__c)=:Zone and TECH_ZONE__c ='13'
                                 ];
                                }else{
                                    contList = [ SELECT id,Name,Status__c,Zone_LVL__c,	Exclusive_Campaign_Product__c,Store__r.Name,Store_Country__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
                                    FROM Quota__c where Status__c='Available' and tolabel(MANAGEMENT_ZONE_LEVEL__c)=:Zone
                                     ];  
                                }

                            }
                        }
     return contList;
 }  

 @AuraEnabled(Cacheable=true)
 public static integer getproductsAvailable() {
    Id CurrentUserId=UserInfo.getUserId();
    List<User> Userinfos= [select id,username,tolabel(MANAGEMENT_ZONE_LEVEL__c),country__c,	tolabel(MGMT_ZONE_SUB_LEVEL1__c),tolabel(DefaultStore__c) from user where id=:CurrentUserId limit 1];
    string ManagementZonelevel=Userinfos[0].DefaultStore__c;
    string Country=Userinfos[0].country__c;
    string Zone=Userinfos[0].MANAGEMENT_ZONE_LEVEL__c;

   integer NbproductsAvailables=0;

    System.debug('ManagementZonelevel*****' +ManagementZonelevel);
    System.debug('Country*****' +Country);
    System.debug('Zone*****' +Zone);


    Boolean hasPermission =checkIfUserHasAssignedPermissionSet(CurrentUserId,'ArtyCappucines_Corporate');
    List<Quota__c> contList =new List<Quota__c>();
    if(hasPermission){
       contList = [ SELECT id,Name,Store__c,Store__r.Name,	Exclusive_Campaign_Product__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
       FROM Quota__c 
        ];
           NbproductsAvailables=contList.size();

    }else{
       if(country!=null && (country.contains('CHINA')||country.contains('KOREA'))){
        contList = [ SELECT id,Name,TECH_ZONE__c ,Zone_LVL__c,	Exclusive_Campaign_Product__c,Status__c,Store__r.Name,Store__r.StoreCountry__c,Store_Country__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
                               FROM Quota__c where Status__c='Available' and TECH_ZONE__c =:country  /*and Store__r.Name=:ManagementZonelevel*/
                                ];
                                System.debug('ManagementZonelevel*****' +ManagementZonelevel);
  NbproductsAvailables=contList.size();

                               }
                           else{
                               if(Zone=='ASIA NORTH' ){
                                
                               contList = [ SELECT id,Zone_LVL__c,Name,Status__c,TECH_ZONE__c ,	Exclusive_Campaign_Product__c,Store__r.Name,Store_Country__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
                               FROM Quota__c where Status__c='Available' and tolabel(MANAGEMENT_ZONE_LEVEL__c)=:Zone and TECH_ZONE__c ='13'
                                ];
                                   NbproductsAvailables=contList.size();

                               }else{
                                   contList = [ SELECT id,Zone_LVL__c,Name,Status__c,	Exclusive_Campaign_Product__c,Store__r.Name,Store_Country__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
                                   FROM Quota__c where Status__c='Available' and tolabel(MANAGEMENT_ZONE_LEVEL__c)=:Zone
                                    ];  
                                       NbproductsAvailables=contList.size();

                               }

                           }
                       }
    return NbproductsAvailables;

} 

 @AuraEnabled(Cacheable=true)
 public static integer getproductsAll() {
    Id CurrentUserId=UserInfo.getUserId();
    List<User> Userinfos= [select id,username,tolabel(MANAGEMENT_ZONE_LEVEL__c),country__c,	tolabel(MGMT_ZONE_SUB_LEVEL1__c),tolabel(DefaultStore__c) from user where id=:CurrentUserId limit 1];
    string ManagementZonelevel=Userinfos[0].DefaultStore__c;
    string Country=Userinfos[0].country__c;
    string Zone=Userinfos[0].MANAGEMENT_ZONE_LEVEL__c;

   integer Nbproducts=0;

    System.debug('ManagementZonelevel*****' +ManagementZonelevel);
    System.debug('Country*****' +Country);
    System.debug('Zone*****' +Zone);


    Boolean hasPermission =checkIfUserHasAssignedPermissionSet(CurrentUserId,'ArtyCappucines_Corporate');
    List<Quota__c> contList =new List<Quota__c>();
    if(hasPermission){
       contList = [ SELECT id,Name,Zone_LVL__c,Store__c,Store__r.Name,	Exclusive_Campaign_Product__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
       FROM Quota__c 
        ];
           Nbproducts=contList.size();

    }else{
       if(country!=null && (country.contains('CHINA')||country.contains('KOREA'))){
        contList = [ SELECT id,Name,TECH_ZONE__c ,Zone_LVL__c,	Exclusive_Campaign_Product__c,Status__c,Store__r.Name,Store__r.StoreCountry__c,Store_Country__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
                               FROM Quota__c where TECH_ZONE__c =:country  /*and Store__r.Name=:ManagementZonelevel*/
                                ];
                                System.debug('ManagementZonelevel*****' +ManagementZonelevel);
  Nbproducts=contList.size();

                               }
                           else{
                               if(Zone=='ASIA NORTH' ){
                                
                               contList = [ SELECT id,Name,TECH_ZONE__c,Zone_LVL__c,Status__c,	Exclusive_Campaign_Product__c,Store__r.Name,Store_Country__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
                               FROM Quota__c where tolabel(MANAGEMENT_ZONE_LEVEL__c)=:Zone  and TECH_ZONE__c ='13' ];
  Nbproducts=contList.size();

                               }else{
                                   contList = [ SELECT id,Name,Zone_LVL__c,Status__c,	Exclusive_Campaign_Product__c,Store__r.Name,Store_Country__c,Exclusive_Campaign_Product__r.Name,toLabel(MANAGEMENT_ZONE_LEVEL__c), Reserved__c,Serial_Number__c
                                   FROM Quota__c where  tolabel(MANAGEMENT_ZONE_LEVEL__c)=:Zone
                                    ];  
  Nbproducts=contList.size();

                               }

                           }
                       }
    return Nbproducts;
 } 
}