force-app/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlan__c/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Zone</label>
    <referenceTo>Zone__c</referenceTo>
    <relationshipLabel>Countries</relationshipLabel>
    <relationshipName>Countries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exclusive_Campaign__c/Exclusive_Campaign__c.object-meta.xml
<CustomObject>
    <label>Exclusive Campaign</label>
    <nameField>
        <label>Exclusive Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exclusive Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exclusive_Campaign__c/fields/AMERICAS__c.field-meta.xml
<CustomField>
    <fullName>AMERICAS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AMERICAS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exclusive_Campaign__c/fields/ASIA_NORTH_sans_COREE_CHINE__c.field-meta.xml
<CustomField>
    <fullName>ASIA_NORTH_sans_COREE_CHINE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ASIA NORTH sans COREE &amp; CHINE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exclusive_Campaign__c/fields/ASIA_SOUTH__c.field-meta.xml
<CustomField>
    <fullName>ASIA_SOUTH__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ASIA SOUTH</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exclusive_Campaign__c/fields/CHINA__c.field-meta.xml
<CustomField>
    <fullName>CHINA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CHINA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exclusive_Campaign__c/fields/EMEA__c.field-meta.xml
<CustomField>
    <fullName>EMEA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EMEA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exclusive_Campaign__c/fields/JAPAN__c.field-meta.xml
<CustomField>
    <fullName>JAPAN__c</fullName>
    <defaultValue>false</defaultValue>
    <label>JAPAN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exclusive_Campaign__c/fields/KOREA__c.field-meta.xml
<CustomField>
    <fullName>KOREA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>KOREA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exclusive_Campaign_Product__c/Exclusive_Campaign_Product__c.object-meta.xml
<CustomObject>
    <label>Exclusive Campaign Product</label>
    <nameField>
        <label>Exclusive Campaign Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exclusive Campaign Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exclusive_Campaign_Product__c/fields/Exclusive_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Exclusive_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exclusive Campaign</label>
    <referenceTo>Exclusive_Campaign__c</referenceTo>
    <relationshipLabel>Exclusive Campaign Products</relationshipLabel>
    <relationshipName>Exclusive_Campaign_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IC_Config__c/IC_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>IC Config</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/AccLastContactTimeRange__c.field-meta.xml
<CustomField>
    <fullName>AccLastContactTimeRange__c</fullName>
    <description>Defines the time range (in days) studied to display the &quot;Contacted in last X days&quot; in ICON Mobile (+ Batch)</description>
    <label>Account Last Contact Time Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/PreReservation__c.object-meta.xml
<CustomObject>
    <label>Pre-Reservation</label>
    <nameField>
        <displayFormat>ECO-{000000}</displayFormat>
        <label>Pre Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pre-Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PreReservation__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pre-Reservations</relationshipLabel>
    <relationshipName>PreReservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>TEXT(Store__r.StoreCountry__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country / Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Exclusive_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Exclusive_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exclusive Campaign</label>
    <referenceTo>Exclusive_Campaign__c</referenceTo>
    <relationshipLabel>Pre-Reservations</relationshipLabel>
    <relationshipName>Pre_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Exclusive_Campaign_Product__c.Exclusive_Campaign__r.Name</field>
            <operation>equals</operation>
            <value>LV x FG</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Admin_Corporate</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Exclusive_Campaign_Product__c</referenceTo>
    <relationshipLabel>Pre-Reservations</relationshipLabel>
    <relationshipName>Pre_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PreReservation__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR (3 AND 4 AND 5) OR (3 AND 6 AND 7 AND 8) OR 9</booleanFilter>
        <errorMessage>Please select a Store in your Zone.</errorMessage>
        <filterItems>
            <field>$User.MANAGEMENT_ZONE_LEVEL__c</field>
            <operation>equals</operation>
            <valueField>Store__c.Zone__r.ZoneId__c</valueField>
        </filterItems>
        <filterItems>
            <field>$User.MANAGEMENT_ZONE_LEVEL__c</field>
            <operation>notEqual</operation>
            <value>ASIA NORTH</value>
        </filterItems>
        <filterItems>
            <field>$User.MANAGEMENT_ZONE_LEVEL__c</field>
            <operation>equals</operation>
            <value>ASIA NORTH</value>
        </filterItems>
        <filterItems>
            <field>$User.MGMT_ZONE_SUB_LEVEL1__c</field>
            <operation>equals</operation>
            <value>KOREA (DF), KOREA (DOM)</value>
        </filterItems>
        <filterItems>
            <field>Store__c.StoreCountry__c</field>
            <operation>contains</operation>
            <value>KOREA</value>
        </filterItems>
        <filterItems>
            <field>$User.MGMT_ZONE_SUB_LEVEL1__c</field>
            <operation>notEqual</operation>
            <value>KOREA (DF), KOREA (DOM)</value>
        </filterItems>
        <filterItems>
            <field>Store__c.StoreCountry__c</field>
            <operation>notContain</operation>
            <value>KOREA</value>
        </filterItems>
        <filterItems>
            <field>Store__c.Zone__r.ZoneId__c</field>
            <operation>equals</operation>
            <value>13</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Pre-Reservations</relationshipLabel>
    <relationshipName>PreReservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup links the store record to the 1st level of hierarchy</description>
    <label>Zone</label>
    <referenceTo>Zone__c</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BARBADE</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILE</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>COLOMBIA</fullName>
            </value>
            <value>
                <fullName>CYPRUS</fullName>
            </value>
            <value>
                <fullName>CZECH REPUBLIC</fullName>
            </value>
            <value>
                <fullName>DENMARK</fullName>
            </value>
            <value>
                <fullName>DOMINICAIN REPUBLIC</fullName>
            </value>
            <value>
                <fullName>FINLAND</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>GREECE</fullName>
            </value>
            <value>
                <fullName>GUAM</fullName>
            </value>
            <value>
                <fullName>HONG KONG</fullName>
            </value>
            <value>
                <fullName>HUNGARY</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDONESIA</fullName>
            </value>
            <value>
                <fullName>IRELAND</fullName>
            </value>
            <value>
                <fullName>ISRAEL</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>JORDANIE</fullName>
            </value>
            <value>
                <fullName>KOREA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zone__c/Zone__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the top level of store Hierarchy</description>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Zone__c/fields/ZoneId__c.field-meta.xml
<CustomField>
    <fullName>ZoneId__c</fullName>
    <description>This field contains the external id (StoreDB) of the Zone record</description>
    <externalId>true</externalId>
    <label>ZoneId</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ArtyCap_ClientDetails_VFCx_TEST.cls
@isTest
private class ArtyCap_ClientDetails_VFCx_TEST {
	
    @TestSetup
    public static void setup() {
        String identityProfile = [SELECT Id FROM Profile WHERE Name = 'Identity User'][0].Id;
        insert new IC_Config__c(
            Name = 'Identity User',
            Value__c = identityProfile
        );
    }
    
    static testMethod void test1() {
        Account acc = IC_TestFactory.createAccount();
        acc.LastModifierStoreCountry__pc = IC_Factory.getPIPACountryCode('KOREA');
        insert acc;
        
         Exclusive_Campaign__c ec = IC_TestFactory.createExclusiveCampaign('Artycapucines 2023');
        ec.Name = 'Artycapucines 2023';
        ec.AMERICAS__c = true;
        ec.ASIA_NORTH_sans_COREE_CHINE__c = true;
        ec.ASIA_SOUTH__c = true;
        ec.CHINA__c = true;
        ec.EMEA__c = true;
        ec.JAPAN__c = true;
        ec.KOREA__c = true;
        
        insert ec;
        
        Exclusive_Campaign_Product__c ecp = IC_TestFactory.createExclusiveCampaignProduct('Product A');
        ecp.Exclusive_Campaign__c = ec.Id;
        insert ecp;
        
        PreReservation__c preResa = new PreReservation__c();
        preResa.Client__c = acc.Id;
        preResa.Product__c = ecp.Id;
        List<Store__c> stores = [Select id from Store__c where Zone__r.ZoneId__c = '13' limit 1];
        if (stores.size()>0)
        	preResa.Store__c = stores[0].Id;
        insert preResa;
        
        ICONSettings__c iconSet = new ICONSettings__c();
		iconSet.AccLastContactTimeRange__c=30;
		insert iconSet;
        
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'ArtyCappucines_Corporate'];

        /***  Pipa user  ***/
        User user1 = IC_TestFactory.createUser('user@korean.com');
        user1.Country__c = 'KOREA';
        user1.ProfileId = IC_TestFactory.PROFILE_MAP.get(IC_TestFactory.PROFILE_ICON_SA_NAME);
        insert user1;     
           
        PermissionSetAssignment psa1 = new PermissionSetAssignment();
		psa1.AssigneeId= user1.Id;
        psa1.PermissionSetId = ps.Id;
        
        User usr = IC_TestFactory.createUser('dreamuserLV@lvtest.com');
	  	usr.profileId = IC_UTILS.getSAProfile();
	  	insert usr;
        
        PermissionSetAssignment psa2 = new PermissionSetAssignment();
		psa2.AssigneeId= usr.Id;
        psa2.PermissionSetId = ps.Id;

        /****Creation of new action plan ***/
        ActionPlan__c c = new ActionPlan__c();  
        c.Comments__c = 'Comments';
        c.IsClosed__c = false;
        c.Subject__c =  'subject'  ;      
        insert c;
	  	
        Test.startTest();
		  	System.runAs(usr) {
                insert psa1;
                insert psa2;
	        ApexPages.StandardController stdController = new ApexPages.Standardcontroller( preResa );
	        ApexPages.currentPage().getParameters().put('id',preResa.Id);
	        
	        Artycap_ClientDetails_VFC controller = new Artycap_ClientDetails_VFC ( stdController );
	        controller = new Artycap_ClientDetails_VFC();

		  	}

        Test.stopTest();        	
    }
        
}