force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/fiftyKCount__c.field-meta.xml
<CustomField>
    <fullName>fiftyKCount__c</fullName>
    <label>fiftyKCount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/LastOneDataKPIUpdate__c.field-meta.xml
<CustomField>
    <fullName>LastOneDataKPIUpdate__c</fullName>
    <label>LastOneDataKPIUpdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/potentialTenKCount__c.field-meta.xml
<CustomField>
    <fullName>potentialTenKCount__c</fullName>
    <label>potentialTenKCount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/tenkCount__c.field-meta.xml
<CustomField>
    <fullName>tenkCount__c</fullName>
    <label>tenkCount</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/tenKYTMCount__c.field-meta.xml
<CustomField>
    <fullName>tenKYTMCount__c</fullName>
    <label>tenKYTMCount</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-icon/main/default/classes/BL_ICON_Batch_Cache.cls
global with sharing class BL_ICON_Batch_Cache implements Database.Batchable<sObject>, Database.AllowsCallouts{

    public String query;
	
	global BL_ICON_Batch_Cache() {
		query = 'select Id, RetailStoreId__c from Store__c  Where Status__c =\'Open\' AND LastOneDataKPIUpdate__c < TODAY';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('#### START - BL_ICON_Batch_Cache');
		System.debug('#### QUERY : ' + query);

		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Store__c> storesToUpdate = new List<Store__c>();
        try{
            Datetime currentdate = System.now();
            for(Store__c s : (List<Store__c>) scope){
                
                try{
                    if(String.isnotBlank(s.RetailStoreId__c)){
                        s.tenKCount__c = getStoreFilterCount('is_10k', s.RetailStoreId__c);
                        s.potentialTenKCount__c = getStoreFilterCount('is_potential_10k', s.RetailStoreId__c);
                        s.tenKYTMCount__c = getStoreFilterCount('is_10k_this_year', s.RetailStoreId__c);
                        s.fiftyKCount__c = getStoreFilterCount('is_50k', s.RetailStoreId__c);
                        s.LastOneDataKPIUpdate__c = System.Today();
                        storesToUpdate.add(s);
                    }
                    
                    
                } catch(Exception e) {
                    System.debug('#### ' + e.getTypeName() + ' Exception:' + e.getMessage() + ' ' + e.getStackTraceString());
                }
            }
            if (storesToUpdate.size() > 0){
                Database.update(storesToUpdate, false);
            }
            while(System.now()< currentdate.addSeconds(5) ){}
        } catch(Exception e) {
            System.debug('#### ' + e.getTypeName() + ' Exception:' + e.getMessage() + ' ' + e.getStackTraceString());
        }
        
    }
    
    global void finish(Database.BatchableContext CD){}

    global Integer getStoreFilterCount(String filter, String storeCode){
        Map<String, Object> filter1 =  new map<String, object>{
            'left'=> 'default_store',
            'operator' => '=',
            'right' => storeCode
        };
            
        Map<String, Object> filter2 =  new map<String, object>{
            'left'=> filter,
            'operator' => '=',
            'right' => true
        };
            
        Map<String, Object> filters =  new map<String, object>{
            'filters'=> new list<Map<String, Object>>{filter1, filter2}
        };

        return BL_ICON_OneData_Helper.getCount(JSON.serialize(filters));
    }
	
}