force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VO_Config__c/VO_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>VO_Config</label>
</CustomObject>

force-app/main/default/objects/VO_Survey__c/VO_Survey__c.object-meta.xml
<CustomObject>
    <label>Voice</label>
    <nameField>
        <displayFormat>Survey-{00000000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VO_Survey__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>populated with VO_Survey apex class before insert from StoreID__c field</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VO_Specific_Statistics_Excel_TEST.cls
@isTest	(seeAllData=false)
private class VO_Specific_Statistics_Excel_TEST {
	
	@testSetup
	static void initDate()
	{
		Test.loadData(VO_Config__c.sobjectType, 'VO_Config_TestCLS');

		List<VO_Survey__c> surveyList = VO_data_Object_Creator_TEST.createSurvayList();
		List<Store__c> storeList = VO_data_Object_Creator_TEST.createStoreByNum(3);
        insert storeList;
        List<VO_Survey__c> surveyListInsert = new List<VO_Survey__c> ();
        for(Integer i = 0; i < surveyList.size(); i++)
        {
            surveyList[i].Store__c = storeList[math.mod(i,3)].id;
            surveyListInsert.add(surveyList[i]);

            if (i== 5)  i= surveyList.size();
    	
                
        }        
        //insert surveyList;
        insert surveyListInsert;

	}
	@isTest static void test_method_one() {
		

		PageReference ref = Page.VO_Specific_Statistics_Excel;
		ref.getParameters().put('lvl1','');
		ref.getParameters().put('lvl2','');
		ref.getParameters().put('lvl3','');
		ref.getParameters().put('lvl4','');
		ref.getParameters().put('storeName','');
		ref.getParameters().put('ca','');
		ref.getParameters().put('surveyType','');
		ref.getParameters().put('fromDate',Datetime.now().addYears(-1).format('MM-dd-yyyy'));
		ref.getParameters().put('surveyType','');
		ref.getParameters().put('toDate',Datetime.now().format('MM-dd-yyyy'));
		Test.setCurrentPage(ref);
	
		VO_Specific_Statistics_Excel_CTRL webPage = new VO_Specific_Statistics_Excel_CTRL();
	}

	
}