force-app/main/default/objects/CountryMapping__mdt/fields/Iso2Code__c.field-meta.xml
<CustomField>
    <fullName>Iso2Code__c</fullName>
    <description>ISO2 country code</description>
    <label>Iso2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMapping__mdt/fields/Iso3Code__c.field-meta.xml
<CustomField>
    <fullName>Iso3Code__c</fullName>
    <description>ISO3 code</description>
    <label>Iso3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMapping__mdt/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <description>Can be translated</description>
    <label>Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AFGHANISTAN</fullName>
            </value>
            <value>
                <fullName>ÅLAND</fullName>
            </value>
            <value>
                <fullName>ALBANIA</fullName>
            </value>
            <value>
                <fullName>ALGERIA</fullName>
            </value>
            <value>
                <fullName>AMERICAN SAMOA</fullName>
            </value>
            <value>
                <fullName>ANDORRA</fullName>
            </value>
            <value>
                <fullName>ANGOLA</fullName>
            </value>
            <value>
                <fullName>ANGUILLA</fullName>
            </value>
            <value>
                <fullName>ANTARCTICA</fullName>
            </value>
            <value>
                <fullName>ANTIGUA AND BARBUDA</fullName>
            </value>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARMENIA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>AZERBAIJAN</fullName>
            </value>
            <value>
                <fullName>BAHAMAS</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BANGLADESH</fullName>
            </value>
            <value>
                <fullName>BARBADOS</fullName>
            </value>
            <value>
                <fullName>BELARUS</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BELIZE</fullName>
            </value>
            <value>
                <fullName>BENIN</fullName>
            </value>
            <value>
                <fullName>BERMUDA</fullName>
            </value>
            <value>
                <fullName>BHUTAN</fullName>
            </value>
            <value>
                <fullName>BOLIVIA</fullName>
            </value>
            <value>
                <fullName>BOSNIA AND HERZEGOVINA</fullName>
            </value>
            <value>
                <fullName>BOTSWANA</fullName>
            </value>
            <value>
                <fullName>BOUVET ISLAND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TWIST_Default_Settings__mdt/TWIST_Default_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Define default values per context (countryLanguage)</description>
    <label>TWIST Default Setting</label>
    <pluralLabel>TWIST Default Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/TWIST_Default_Settings__mdt/fields/Country_Language__c.field-meta.xml
<CustomField>
    <fullName>Country_Language__c</fullName>
    <description>List of all the exsting Locals of lv com/app</description>
    <label>Country Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ara-ae</fullName>
            </value>
            <value>
                <fullName>deu-de</fullName>
            </value>
            <value>
                <fullName>eng-ae</fullName>
            </value>
            <value>
                <fullName>eng-au</fullName>
            </value>
            <value>
                <fullName>eng-ca</fullName>
            </value>
            <value>
                <fullName>eng-e1</fullName>
            </value>
            <value>
                <fullName>eng-gb</fullName>
            </value>
            <value>
                <fullName>eng-hk</fullName>
            </value>
            <value>
                <fullName>eng-nl</fullName>
            </value>
            <value>
                <fullName>eng-sg</fullName>
            </value>
            <value>
                <fullName>eng-us</fullName>
            </value>
            <value>
                <fullName>esp-es</fullName>
            </value>
            <value>
                <fullName>esp-mx</fullName>
            </value>
            <value>
                <fullName>fra-ca</fullName>
            </value>
            <value>
                <fullName>fra-fr</fullName>
            </value>
            <value>
                <fullName>ita-it</fullName>
            </value>
            <value>
                <fullName>jpn-jp</fullName>
            </value>
            <value>
                <fullName>kor-kr</fullName>
            </value>
            <value>
                <fullName>por-br</fullName>
            </value>
            <value>
                <fullName>rus-ru</fullName>
            </value>
            <value>
                <fullName>tha-th</fullName>
            </value>
            <value>
                <fullName>vnm-vn</fullName>
            </value>
            <value>
                <fullName>zhs-cn</fullName>
            </value>
            <value>
                <fullName>zht-hk</fullName>
            </value>
            <value>
                <fullName>zht-tw</fullName>
            </value>
            <value>
                <fullName>eng-in</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TWIST_Default_Settings__mdt/fields/Setting__c.field-meta.xml
<CustomField>
    <fullName>Setting__c</fullName>
    <label>Setting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency Code</fullName>
                <default>true</default>
                <label>Currency Code</label>
            </value>
            <value>
                <fullName>Mobile Phone Country Code</fullName>
            </value>
            <value>
                <fullName>Page Direction</fullName>
            </value>
            <value>
                <fullName>Link Switch To Language</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Twist_HeaderAndFooterUrls__mdt/Twist_HeaderAndFooterUrls__mdt.object-meta.xml
<CustomObject>
    <label>Twist Header And Footer Urls</label>
    <pluralLabel>Twist Header And Footer Urls</pluralLabel>
</CustomObject>

force-app/main/default/objects/Twist_HeaderAndFooterUrls__mdt/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/TWIST_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TWIST - Settings</label>
</CustomObject>

force-app/main/default/objects/TWIST_Settings__c/fields/Countries_New_Locales__c.field-meta.xml
<CustomField>
    <fullName>Countries_New_Locales__c</fullName>
    <description>!! important: locales must be separated by a / surrounded by spaces + first one must be the main one</description>
    <label>Countries New Locales</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Default_Language_Country_Flag_Label__c.field-meta.xml
<CustomField>
    <fullName>Default_Language_Country_Flag_Label__c</fullName>
    <label>Default Language Country Flag Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Default_Language_Country_Flag_Title__c.field-meta.xml
<CustomField>
    <fullName>Default_Language_Country_Flag_Title__c</fullName>
    <label>Default Language Country Flag Title</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Default_Language_Country_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Default_Language_Country_Parameter__c</fullName>
    <label>Default Language Country Parameter</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TWIST_UtilsServices.cls
public with sharing class TWIST_UtilsServices {

    private static final Set<String> LANG_COUNTRY_WITH_RTL_DIRECTION = new Set<String> { 'ara-ae' };
    private static final Set<String> MOBILE_APPS = new Set<String> { 'lvapp', 'lvconnect' };
    private static final String SETTING_LINK_SWITCH_TO_LANGUAGE = 'Link Switch To Language';
    private static final String PICKLIST_COUNTRIES = 'Countries';

    @AuraEnabled(cacheable=true)
    public static String buildError404Url(String langCountry, String origin, String clientId) {
        Map<String,Object> queryParams = new Map<String,Object> ();
        queryParams.put(TWIST_PageKey_CONST.LANG_COUNTRY, langCountry);
        queryParams.put(TWIST_PageKey_CONST.ORIGIN, origin);
        queryParams.put(TWIST_PageKey_CONST.CLIENT_ID, clientId);
        return TWIST_Utils.buildTwistPageUrl(TWIST_IdentityPathsMdt_CONST.ERROR404, queryParams);
    }
    
    public static String buildError404Url(String origin, String clientId) {
        
        return '';
    }

    @AuraEnabled(cacheable=true)
    public static String getPageDirection(String langCountry) {
        return LANG_COUNTRY_WITH_RTL_DIRECTION.contains(langCountry) ? 'rtl' : 'ltr';
    }

    @AuraEnabled(cacheable=true)
    public static Boolean isMobileApp(String origin) {
        return MOBILE_APPS.contains(origin) ? true : false;
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String,String> getHeaderAndFooterUrls(String langCountry) {
        TWIST_Settings__c twistSettings = TWIST_Settings__c.getInstance();
        String[] arabicLocales = twistSettings.Countries_New_Locales__c.split('/');
       	String country = langCountry.substringAfter('-');
       	List <Twist_HeaderAndFooterUrls__mdt> listUrls = [SELECT id, value__c, name__c  FROM Twist_HeaderAndFooterUrls__mdt];
        Map<String,String> mUrls = new Map<String,String>();
        
        for(Twist_HeaderAndFooterUrls__mdt url: listUrls){
            if(url.value__c.contains('careers') && arabicLocales.contains(country)){
                url.value__c = url.value__c.replace('lang-country', twistSettings.Default_Language_Country_Parameter__c);
            }
            url.value__c = url.value__c.replace('lang-country', langCountry);
            mUrls.put(url.name__c, url.value__c);
        }
          	return mUrls;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getSwitchToLanguage(String langCountry) {
        Map<String, Object> settingsSwitchToLanguage = new Map<String, Object>();
        List <TWIST_Default_Settings__mdt> metadata = [SELECT Setting__c, Is_Required__c, Default_Value__c 
                                                       FROM TWIST_Default_Settings__mdt 
                     WHERE Country_Language__c =: langCountry AND Setting__c =: SETTING_LINK_SWITCH_TO_LANGUAGE LIMIT 1];
        if(!metadata.isEmpty()){
           settingsSwitchToLanguage.put('isRequired', metadata[0].Is_Required__c);
           settingsSwitchToLanguage.put('value', metadata[0].Default_Value__c);
        }
        return settingsSwitchToLanguage;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getFlagData(String langCountry, String dispatchCountry, String language) {
        String country = dispatchCountry;
        Map<String, Object> flagDetails = new Map<String, Object>();
        if(String.isEmpty(dispatchCountry)){
            String[] splitLangCountry = langCountry.split('-');
            country = splitLangCountry[1].toUpperCase();
            if(country == 'E1'){
                TWIST_Settings__c twistSettings = TWIST_Settings__c.getInstance();
                flagDetails.put('title', twistSettings.Default_Language_Country_Flag_Title__c);
                flagDetails.put('label', twistSettings.Default_Language_Country_Flag_Label__c);
                return flagDetails;
            }
        }
        List<CountryMapping__mdt> clist = [SELECT Picklist__c, Iso2Code__c ,Iso3Code__c FROM CountryMapping__mdt WHERE Picklist__c != null AND Iso2Code__c =: country];
        if(!clist.isEmpty()){
            Map<String,Object> countryListTranslated = TWIST_i18nTranslations.translatePicklist(PICKLIST_COUNTRIES, language);
            String flagLabel = countryListTranslated.get(clist[0].Picklist__c).toString();
            List <String> countryLabel = flagLabel.split(' ');
            for (Integer i = 0; i < countryLabel.size(); i++) {
                countryLabel[i] = countryLabel[i].toLowerCase().capitalize();
                flagLabel = String.join(countryLabel, ' ');
            }
            flagDetails.put('title', country.toLowerCase());
            flagDetails.put('label', flagLabel);
        }
        return flagDetails;
    }
}