force-icon/main/default/objects/Client_Gift__c/Client_Gift__c.object-meta.xml
<CustomObject>
    <description>Gifts offered to a client</description>
    <label>Client Gift</label>
    <nameField>
        <displayFormat>G-{000000}</displayFormat>
        <label>Client Gift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-icon/main/default/objects/Client_Gift__c/fields/CA_Name__c.field-meta.xml
<CustomField>
    <fullName>CA_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CA who realized the gift</description>
    <label>CA Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Client_Gifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-icon/main/default/objects/Client_Gift__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client linked to the gift</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Gifts</relationshipLabel>
    <relationshipName>Client_Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-icon/main/default/objects/Client_Gift__c/fields/Gift_Date__c.field-meta.xml
<CustomField>
    <fullName>Gift_Date__c</fullName>
    <label>Gift Date</label>
    <type>Date</type>
</CustomField>

force-icon/main/default/objects/Client_Gift__c/fields/Gift_Item__c.field-meta.xml
<CustomField>
    <fullName>Gift_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Client&apos;s Gift information</description>
    <label>Gift Item</label>
    <referenceTo>GiftCatalog__c</referenceTo>
    <relationshipLabel>Client Gifts</relationshipLabel>
    <relationshipName>Client_Gifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-icon/main/default/objects/Client_Gift__c/fields/Gift_Store__c.field-meta.xml
<CustomField>
    <fullName>Gift_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Digital, retail and CSC store</description>
    <label>Gift Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Client Gifts</relationshipLabel>
    <relationshipName>Client_Gifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-icon/main/default/objects/Client_Gift__c/fields/Purchased_Product__c.field-meta.xml
<CustomField>
    <fullName>Purchased_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Gift recorded into transaction</description>
    <label>Purchased Product</label>
    <referenceTo>PPR_PurchProduct__c</referenceTo>
    <relationshipLabel>Client Gifts</relationshipLabel>
    <relationshipName>Client_Gifts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-icon/main/default/objects/GiftCatalog__c/GiftCatalog__c.object-meta.xml
<CustomObject>
    <description>List of all products that can offered as gift to the clients. Managed by PCR team</description>
    <label>Gift Catalog</label>
    <nameField>
        <label>Gift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gifts Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-icon/main/default/objects/GiftCatalog__c/fields/SKUGift__c.field-meta.xml
<CustomField>
    <fullName>SKUGift__c</fullName>
    <description>SKU of the gift</description>
    <externalId>true</externalId>
    <label>SKU Gift</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/PurchasedDate__c.field-meta.xml
<CustomField>
    <fullName>PurchasedDate__c</fullName>
    <label>Purchased Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/RMSSKUCode__c.field-meta.xml
<CustomField>
    <fullName>RMSSKUCode__c</fullName>
    <label>Code RMS du produit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N83</fullName>
            </value>
            <value>
                <fullName>V24</fullName>
            </value>
            <value>
                <fullName>V06</fullName>
            </value>
            <value>
                <fullName>V88</fullName>
            </value>
            <value>
                <fullName>V14</fullName>
            </value>
            <value>
                <fullName>V85</fullName>
            </value>
            <value>
                <fullName>V15</fullName>
            </value>
            <value>
                <fullName>V18</fullName>
            </value>
            <value>
                <fullName>V76</fullName>
            </value>
            <value>
                <fullName>V35</fullName>
            </value>
            <value>
                <fullName>V25</fullName>
            </value>
            <value>
                <fullName>V61</fullName>
            </value>
            <value>
                <fullName>V38</fullName>
            </value>
            <value>
                <fullName>V42</fullName>
            </value>
            <value>
                <fullName>V62</fullName>
            </value>
            <value>
                <fullName>V86</fullName>
            </value>
            <value>
                <fullName>V50</fullName>
            </value>
            <value>
                <fullName>V33</fullName>
            </value>
            <value>
                <fullName>V57</fullName>
            </value>
            <value>
                <fullName>V74</fullName>
            </value>
            <value>
                <fullName>V36</fullName>
            </value>
            <value>
                <fullName>V82</fullName>
            </value>
            <value>
                <fullName>V80</fullName>
            </value>
            <value>
                <fullName>V21</fullName>
            </value>
            <value>
                <fullName>V65</fullName>
            </value>
            <value>
                <fullName>V72</fullName>
            </value>
            <value>
                <fullName>V54</fullName>
            </value>
            <value>
                <fullName>V31</fullName>
            </value>
            <value>
                <fullName>V32</fullName>
            </value>
            <value>
                <fullName>V13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/StoreRetailCode__c.field-meta.xml
<CustomField>
    <fullName>StoreRetailCode__c</fullName>
    <label>Store Retail Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/User/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <externalId>true</externalId>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-icon/main/default/classes/ClientGiftQueueable.cls
public class ClientGiftQueueable implements Queueable{
 	private List<PPR_PurchProduct__c> records;

  public ClientGiftQueueable( List<PPR_PurchProduct__c> records) {
    this.records = records;
  }

  public void execute(QueueableContext context) {

    List<String> rmsSkuCodeList = new List<String>();
    for(PPR_PurchProduct__c purchProd : records) {
      rmsSkuCodeList.add(purchProd.RMSSKUCode__c);
    }
  
    List<GiftCatalog__c> giftCatalogList = [
      SELECT
          Id,
          SKUGift__c
      FROM GiftCatalog__c
      WHERE SKUGift__c IN :rmsSkuCodeList
    ];
  
    Map<String, Id> skuGiftToIdMap = new Map<String, Id>();
    for (GiftCatalog__c giftItem : giftCatalogList) {
      skuGiftToIdMap.put(giftItem.SKUGift__c, giftItem.Id);
    }

    List<Client_Gift__c> clientGiftList = new List<Client_Gift__c>();

    for (PPR_PurchProduct__c purchaseProduct : records) {
      if (skuGiftToIdMap.containsKey(purchaseProduct.RMSSKUCode__c)) {
        User ca = new User(WWEmployeeNumber__c = purchaseProduct.WWEmployeeNumber__c);
        Store__c store = new Store__c(RetailStoreId__c = purchaseProduct.StoreRetailCode__c);
        Client_Gift__c clientGift = new Client_Gift__c();
        clientGift.Purchased_Product__c = purchaseProduct.Id;
        clientGift.Client__c = purchaseProduct.Client__c;
        clientGift.CA_Name__r = ca;
        clientGift.Gift_Item__c =  skuGiftToIdMap.get(purchaseProduct.RMSSKUCode__c);
        clientGift.Gift_Store__r = store;
        clientGift.Gift_Date__c = purchaseProduct.PurchasedDate__c;
        clientGiftList.add(clientGift);
      }
    }

    Database.insert(clientGiftList,false);
  }
  
}