force-app/main/default/objects/Badge_Collection__c/Badge_Collection__c.object-meta.xml
<CustomObject>
    <label>Club Badge Collection</label>
    <nameField>
        <label>Badge Collection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Badge Collection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Badge_Collection__c/fields/badgeFlag__c.field-meta.xml
<CustomField>
    <fullName>badgeFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Badge unlocked by Member</description>
    <label>Badge Unlocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Badge_Collection__c/fields/badgeFlagIsTrueDate__c.field-meta.xml
<CustomField>
    <fullName>badgeFlagIsTrueDate__c</fullName>
    <description>Date at which badge is unlocked</description>
    <label>Badge Unlock Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Badge_Collection__c/fields/badgeId__c.field-meta.xml
<CustomField>
    <fullName>badgeId__c</fullName>
    <label>Badge</label>
    <referenceTo>Badge_Catalog__c</referenceTo>
    <relationshipLabel>Badges Collection</relationshipLabel>
    <relationshipName>Badges_Collection</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Badge_Collection__c/fields/member_Id__c.field-meta.xml
<CustomField>
    <fullName>member_Id__c</fullName>
    <label>Club Member</label>
    <referenceTo>Club_MemberShip__c</referenceTo>
    <relationshipLabel>Badges Collection</relationshipLabel>
    <relationshipName>Badges_Collections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Badge_Collection__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <label>UniqueKey</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-experience/main/default/classes/BadgeCatalogTriggerHandler.cls
public with sharing class BadgeCatalogTriggerHandler {
    public static void handleTrigger(List<Badge_Collection__c> newList, Map<Id, Badge_Collection__c> newMap, List<Badge_Collection__c> oldList, Map<Id, Badge_Collection__c> oldMap, System.TriggerOperation triggerEvent) {
        switch on triggerEvent {
            when BEFORE_INSERT {
                handleBeforeInsert(newList);
            }
            when BEFORE_UPDATE {
                handleBeforeUpdate(newList, oldMap);
            }
            when else {
                //do nothing for AFTER_UNDELETE, BEFORE_DELETE, or BEFORE_UPDATE
            }
        }
    }

    public static void handleBeforeInsert(List<Badge_Collection__c> newList) {
        for (Badge_Collection__c badgeCollection : newList) {
            badgeCollection.UniqueKey__c = badgeCollection.member_Id__c + '_' + badgeCollection.badgeId__c;
        }
    }

    public static void handleBeforeUpdate(List<Badge_Collection__c> newList, Map<Id, Badge_Collection__c> oldMap) {
        for (Badge_Collection__c badgeCollection : newList) {
            Badge_Collection__c oldBadge = oldMap.get(badgeCollection.Id);

            if (badgeCollection.badgeFlag__c && !oldBadge.badgeFlag__c) {
                badgeCollection.badgeFlagIsTrueDate__c = System.today();
            }
        }
    }
}