force-app/main/default/objects/Registration_Code_Verification_Request__c/Registration_Code_Verification_Request__c.object-meta.xml
<CustomObject>
    <label>Registration Code Verification Request</label>
    <nameField>
        <displayFormat>RC-{0000000000}</displayFormat>
        <label>Registration Code Verification Request N</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Code Verification Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TWIST_Settings__c/TWIST_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TWIST - Settings</label>
</CustomObject>

force-app/main/default/objects/TWIST_Settings__c/fields/PurgeVerificationCodeIntervalInDays__c.field-meta.xml
<CustomField>
    <fullName>PurgeVerificationCodeIntervalInDays__c</fullName>
    <label>PurgeVerificationCodeIntervalInDays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-twist/main/default/classes/TWIST_BatchVerificationCodeCleaner.cls
global class TWIST_BatchVerificationCodeCleaner implements Database.Batchable<sObject> , Schedulable {
    
    String query;
	DateTime dt;
	
	global TWIST_BatchVerificationCodeCleaner() {
        dt = DateTime.now().addDays(-(integer.valueOf(TWIST_Settings__c.getInstance().PurgeVerificationCodeIntervalInDays__c)));
		query = 'SELECT Id FROM Registration_Code_Verification_Request__c WHERE CreatedDate < :dt';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		try{
            if(scope.size() > 0){
            	delete scope;
        	}
        }catch (DmlException e){
            // Process exception here
            System.debug('#### '+e.getTypeName()+' Exception:'+e.getMessage()+' '+e.getStackTraceString());
        }
	}

	global void finish(Database.BatchableContext CD){}

	global void execute(SchedulableContext sc) {
		TWIST_BatchVerificationCodeCleaner b = new TWIST_BatchVerificationCodeCleaner();
		database.executebatch(b, 2000);
	}

}