force-app/main/default/objects/Account/fields/BoundToLVLine__c.field-meta.xml
<CustomField>
    <fullName>BoundToLVLine__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BoundToLVLine</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Social_Media_Identifier__c/Social_Media_Identifier__c.object-meta.xml
<CustomObject>
    <label>Social Media Identifier</label>
    <nameField>
        <displayFormat>SMI-{0000}</displayFormat>
        <label>Social Media Identifier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media Identifiers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Media_Identifier__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Client (PersonAccount)</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Social Media Identifiers</relationshipLabel>
    <relationshipName>Social_Media_Identifiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Social_Media_Identifier__c/fields/Social_Id__c.field-meta.xml
<CustomField>
    <fullName>Social_Id__c</fullName>
    <description>User identifier from social media</description>
    <label>Social Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Identifier__c/fields/Social_Media_Type__c.field-meta.xml
<CustomField>
    <fullName>Social_Media_Type__c</fullName>
    <description>Name of the social media</description>
    <label>Social Media Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Line</fullName>
            </value>
            <value>
                <fullName>WeChat</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Kakao</fullName>
            </value>
            <value>
                <fullName>KakaoTalk message</fullName>
            </value>
            <value>
                <fullName>LineWorks</fullName>
            </value>
            <value>
                <fullName>LVxYKGamingApp</fullName>
            </value>
            <value>
                <fullName>LineThai</fullName>
            </value>
            <value>
                <fullName>LineTaiwan</fullName>
            </value>
            <value>
                <fullName>LineTW</fullName>
            </value>
            <value>
                <fullName>LineLV</fullName>
            </value>
            <value>
                <fullName>WeChat_Mobile</fullName>
                <isActive>false</isActive>
                <label>WeChat_Mobile</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BL_ICON_BatchUpdateLineClients_TEST.cls
@isTest
public with sharing class BL_ICON_BatchUpdateLineClients_TEST {
@testsetup static void setupMethod(){
        Account acc =  new Account(LastName = 'test', BoundToLVLine__c = false, PrimaryCountry__pc = 'JAPAN');
        insert acc;
         
        Social_Media_Identifier__c sm = new Social_Media_Identifier__c(Social_Id__c = 'ojqn700Qv3x0kSkVikRDXHt', Social_Media_Type__c = 'Line', Client__c = acc.Id);
        insert sm;
         
   }
    
    @isTest static void test_batchUpdateLineClients() {
		
    Test.startTest();
    String jobId = Database.executeBatch(new BL_ICON_BatchUpdateLineClients(), 200);

    Test.stopTest();
   }
}