force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Deleted_record_log__c/Deleted_record_log__c.object-meta.xml
<CustomObject>
    <label>Deleted record log</label>
    <nameField>
        <displayFormat>DEL-{0}</displayFormat>
        <label>Deleted record log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deleted record logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deleted_record_log__c/fields/DreamId__c.field-meta.xml
<CustomField>
    <fullName>DreamId__c</fullName>
    <label>DreamId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deleted_record_log__c/fields/Object_type__c.field-meta.xml
<CustomField>
    <fullName>Object_type__c</fullName>
    <label>Object type</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deleted_record_log__c/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <externalId>true</externalId>
    <label>ObjectId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Transverse_Batchs_Setup__c/Transverse_Batchs_Setup__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Transverse Batchs Setup</label>
</CustomObject>

force-app/main/default/objects/Transverse_Batchs_Setup__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TR_SchedulerPurgeDeletedRecordLog_Test.cls
@isTest

private class TR_SchedulerPurgeDeletedRecordLog_Test {
@isTest
 static void test_ScheduleBatch() {
        Account a = IC_TestFactory.createAccount();
        insert a;
        Transverse_Batchs_Setup__c setting = new Transverse_Batchs_Setup__c();
        setting.name = 'Batch Deleted record logs';
        setting.Created_Before_Days__c =-2;
        setting.Limit__c = '100000';
        insert setting;
     a.DreamId__c='123232';
     update a;
        Deleted_record_log__c send = new Deleted_record_log__c();
     send.Object_type__c='Account';
     send.ObjectId__c=a.id;

        insert send;
       
        Test.startTest();
        String cron = '0 0 23 * * ?';
        TR_SchedulerPurgeDeletedRecordLog schd = new TR_SchedulerPurgeDeletedRecordLog();
        String jobId = System.schedule('test schedule relate transaction to messaging', cron, schd);
        schd.execute(null);
        
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        
        Test.stopTest();
        System.assertNotEquals(Null, ct.NextFireTime);
    }
}