force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-clientforce/main/default/objects/MergedClients__c/MergedClients__c.object-meta.xml
<CustomObject>
    <description>This object associate an old DreamID to an existing one.</description>
    <label>Merged Client</label>
    <nameField>
        <label>MergedClients Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merged Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-clientforce/main/default/objects/MergedClients__c/fields/Absorbed_DreamId__c.field-meta.xml
<CustomField>
    <fullName>Absorbed_DreamId__c</fullName>
    <description>This field is the old dreamID,</description>
    <externalId>true</externalId>
    <label>Absorbed DreamId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transverse_Batchs_Setup__c/Transverse_Batchs_Setup__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Transverse Batchs Setup</label>
</CustomObject>

force-app/main/default/objects/Transverse_Batchs_Setup__c/fields/Limit__c.field-meta.xml
<CustomField>
    <fullName>Limit__c</fullName>
    <label>Limit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TR_SchedulerPurgeMergedClients_Test.cls
@isTest

private class TR_SchedulerPurgeMergedClients_Test {
    
@isTest
 static void test_ScheduleBatch() {
        Account a = IC_TestFactory.createAccount();
        insert a;
        Transverse_Batchs_Setup__c setting = new Transverse_Batchs_Setup__c();
        setting.name = 'Batch Merge Clients';
        setting.Created_Before_Days__c =-2;
        setting.Limit__c = '100000';
        insert setting;
     a.DreamId__c='123232';
     update a;
        MergedClients__c send = new MergedClients__c();
    send.Absorbed_DreamId__c='123232';
        insert send;
       
        Test.startTest();
        String cron = '0 0 23 * * ?';
        TR_SchedulerPurgeMergedClients schd = new TR_SchedulerPurgeMergedClients();
        String jobId = System.schedule('test schedule relate transaction to messaging', cron, schd);
        schd.execute(null);
        
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        
        Test.stopTest();
        System.assertNotEquals(Null, ct.NextFireTime);
    }
}