force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IC_Config__c/IC_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>IC Config</label>
</CustomObject>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchClientUpdate_TEST.cls
@isTest
private class BatchClientUpdate_TEST {

	@TestSetup
    public static void setup() {
        String identityProfile = [SELECT Id FROM Profile WHERE Name = 'Identity User'][0].Id;
        insert new IC_Config__c(
            Name = 'Identity User',
            Value__c = identityProfile
        );
    }

	static testMethod void testBatch() {

		ID batchprocessid;
		List<String> lstSADreamId = new List<String>();
		
		Account acc = IC_TestFactory.createAccount();
		acc.TECH_DreamIdSA__pc = '123456';
        insert acc;				
		
		User usr = IC_TestFactory.createUser('TestLVBacthCLCreation@lvtest.com');
		usr.profileId = IC_UTILS.getSAProfile();
		usr.DREAMID__C='123456';
		insert usr;
		
		lstSADreamId.add('123456');
		lstSADreamId.add('654321');
		
		BatchClientUpdate myBatch = new BatchClientUpdate(lstSADreamId);
		
		Test.startTest();
		batchprocessid = Database.executeBatch(myBatch,1000);
		Test.stopTest();
		
		List<Account> lst = [SELECT OwnerId FROM Account WHERE Id = :acc.Id];
		//System.assertequals(lst[0].OwnerId, usr.Id);
	}

}