force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Club_and_Seasons__c/Club_and_Seasons__c.object-meta.xml
<CustomObject>
    <label>Club</label>
    <nameField>
        <label>Club Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_MemberShip__c/Club_MemberShip__c.object-meta.xml
<CustomObject>
    <label>Club Membership</label>
    <nameField>
        <label>Club MemberShip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_MemberShip__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <description>Account Id</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Clubs_MemberShip</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/Club_and_Seasons__c.field-meta.xml
<CustomField>
    <fullName>Club_and_Seasons__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Club</label>
    <referenceTo>Club_and_Seasons__c</referenceTo>
    <relationshipName>Clubs_MemberShip</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/clubStatus__c.field-meta.xml
<CustomField>
    <fullName>clubStatus__c</fullName>
    <description>Membership levels from the LV Clubs</description>
    <label>Club Status TECH</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClubStatusList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/dreamId__c.field-meta.xml
<CustomField>
    <fullName>dreamId__c</fullName>
    <description>Client/Member DreamId</description>
    <label>Dream ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/isClubEligible__c.field-meta.xml
<CustomField>
    <fullName>isClubEligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Club Eligibility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/lastStatusUpdated__c.field-meta.xml
<CustomField>
    <fullName>lastStatusUpdated__c</fullName>
    <description>Date &amp; Hour at which LV Club member status changed</description>
    <label>Club Status Update Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <label>Unique Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/ClubStatusList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bronze</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl</fullName>
    </customValue>
    <customValue>
        <fullName>Not Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Client Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultra Rare</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <masterLabel>Club Status List</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchCAClubMembership.cls
public with sharing class BatchCAClubMembership implements Database.Batchable<sObject>, Database.Stateful {
  Club_and_Seasons__c club = new Club_and_Seasons__c();

  public BatchCAClubMembership(String clubName) {
    club = Club_utils.getClubByName(clubName);
  }

  public Database.QueryLocator start(Database.BatchableContext bc) {
    if (club == null) return null;

    List<String> caProfileList = Club_Utils.caProfileList(); 

    String query = 'SELECT Id, FirstName, LastName, Email, Profile.Name ' +
                   'FROM User ' +
                   'WHERE IsActive = TRUE ' +
                   'AND Profile.UserLicense.LicenseDefinitionKey = \'SFDC\' ' +
                   'AND Profile.Name IN :caProfileList '+ 
                   'AND Email LIKE \'%@louisvuitton.com%\'';

    if (Test.isRunningTest()) {
      query += ' ORDER BY CreatedDate DESC LIMIT 1';
    }

    return Database.getQueryLocator(query);
  }

  public void execute(Database.BatchableContext bc, List<User> userCaList) {
    Set<String> userEmailList = Club_utils.userEmailList(userCaList);

    List<User> identityUsers = [
      SELECT id, FirstName, LastName, Email, Profile.Name, AccountId, Account.FirstName, Account.LastName, Account.DREAMID__c, Account.PersonEmail
      FROM User
      WHERE Profile.Name = 'Identity User'
      AND Email IN :userEmailList 
      AND AccountId != NULL
      AND Account.DREAMID__c != NULL
    ];

    Map<string, User> salesforceUsersByPersonKey = Club_utils.userByPersonKeyMap(userCaList);
    
    List<Club_MemberShip__c> members = new List<Club_MemberShip__c>();
    for (User userIdentity : identityUsers) {
      String identityKey = (userIdentity.Email + userIdentity.FirstName + userIdentity.LastName).toLowerCase();
      String identityAccountKey = (userIdentity.Account.PersonEmail + userIdentity.Account.FirstName + userIdentity.Account.LastName).toLowerCase();

      if (identityKey == identityAccountKey && salesforceUsersByPersonKey.containsKey(identityKey)) {
        Club_MemberShip__c member = new Club_MemberShip__c(
          clientId__c = userIdentity.AccountId,
          dreamId__c = userIdentity.Account.DREAMID__c,
          Club_and_Seasons__c = club.Id,
          clubStatus__c = 'Client Advisor',
          isClubEligible__c = true,
          lastStatusUpdated__c = System.now(),
          Unique_Key__c = userIdentity.Account.DREAMID__c + '_' + club.Name
        );

        members.add(member);
      }
    }

    Database.insert(members, false);
  }

  public void finish(Database.BatchableContext bc){
  }
}