force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/ExcepPurchaseUSD__c.field-meta.xml
<CustomField>
    <fullName>ExcepPurchaseUSD__c</fullName>
    <defaultValue>3500</defaultValue>
    <label>Exceptional Purchase Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/fields/Exceptional_Purchase_Currency__c.field-meta.xml
<CustomField>
    <fullName>Exceptional_Purchase_Currency__c</fullName>
    <defaultValue>&quot;EUR&quot;</defaultValue>
    <label>Exceptional Purchase Currency</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ConvertedAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAmountUSD__c</fullName>
    <label>Converted Amount (USD)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <description>DREAM Id Transaction</description>
    <externalId>true</externalId>
    <label>DREAM Id Transaction</label>
    <length>29</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Jewelry</fullName>
            </value>
            <value>
                <fullName>Leather Goods</fullName>
            </value>
            <value>
                <fullName>Perfume</fullName>
            </value>
            <value>
                <fullName>Ready To Wear</fullName>
            </value>
            <value>
                <fullName>Shoes</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/PurchasedDate__c.field-meta.xml
<CustomField>
    <fullName>PurchasedDate__c</fullName>
    <label>Purchased Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/SA__c.field-meta.xml
<CustomField>
    <fullName>SA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link with the SA who sold the product.</description>
    <label>CA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchased_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N83</fullName>
            </value>
            <value>
                <fullName>V24</fullName>
            </value>
            <value>
                <fullName>V06</fullName>
            </value>
            <value>
                <fullName>V88</fullName>
            </value>
            <value>
                <fullName>V14</fullName>
            </value>
            <value>
                <fullName>V85</fullName>
            </value>
            <value>
                <fullName>V15</fullName>
            </value>
            <value>
                <fullName>V18</fullName>
            </value>
            <value>
                <fullName>V76</fullName>
            </value>
            <value>
                <fullName>V35</fullName>
            </value>
            <value>
                <fullName>V25</fullName>
            </value>
            <value>
                <fullName>V61</fullName>
            </value>
            <value>
                <fullName>V38</fullName>
            </value>
            <value>
                <fullName>V42</fullName>
            </value>
            <value>
                <fullName>V62</fullName>
            </value>
            <value>
                <fullName>V86</fullName>
            </value>
            <value>
                <fullName>V50</fullName>
            </value>
            <value>
                <fullName>V33</fullName>
            </value>
            <value>
                <fullName>V57</fullName>
            </value>
            <value>
                <fullName>V74</fullName>
            </value>
            <value>
                <fullName>V36</fullName>
            </value>
            <value>
                <fullName>V82</fullName>
            </value>
            <value>
                <fullName>V80</fullName>
            </value>
            <value>
                <fullName>V21</fullName>
            </value>
            <value>
                <fullName>V65</fullName>
            </value>
            <value>
                <fullName>V72</fullName>
            </value>
            <value>
                <fullName>V54</fullName>
            </value>
            <value>
                <fullName>V31</fullName>
            </value>
            <value>
                <fullName>V32</fullName>
            </value>
            <value>
                <fullName>V13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TicketNumber__c.field-meta.xml
<CustomField>
    <fullName>TicketNumber__c</fullName>
    <externalId>true</externalId>
    <label>Ticket Number</label>
    <length>26</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionRMSId__c.field-meta.xml
<CustomField>
    <fullName>TransactionRMSId__c</fullName>
    <externalId>true</externalId>
    <label>Transaction RMS Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VO_Survey__c/VO_Survey__c.object-meta.xml
<CustomObject>
    <label>Voice</label>
    <nameField>
        <displayFormat>Survey-{00000000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VO_Survey__c/fields/AnswerDate__c.field-meta.xml
<CustomField>
    <fullName>AnswerDate__c</fullName>
    <description>Default value equal to today (old voice)</description>
    <label>Answer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/DreamID__c.field-meta.xml
<CustomField>
    <fullName>DreamID__c</fullName>
    <formula>ClientDreamID__r.DREAMID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DreamID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/DreamIDText__c.field-meta.xml
<CustomField>
    <fullName>DreamIDText__c</fullName>
    <description>Denormalized data from Account --&gt; sent by Clicktools</description>
    <label>Dream ID Text</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/IDTransaction__c.field-meta.xml
<CustomField>
    <fullName>IDTransaction__c</fullName>
    <description>Denormalized data from Purchased Products --&gt; sent by Clicktools</description>
    <label>ID Transaction</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Scoring__c.field-meta.xml
<CustomField>
    <fullName>Scoring__c</fullName>
    <label>Scoring</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>populated with VO_Survey apex class before insert from StoreID__c field</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/StoreID__c.field-meta.xml
<CustomField>
    <fullName>StoreID__c</fullName>
    <description>Denormalized data from Store --&gt; sent by Clicktools</description>
    <label>Store ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/SurveyType__c.field-meta.xml
<CustomField>
    <fullName>SurveyType__c</fullName>
    <description>Sent by Clicktools</description>
    <label>Survey Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VOICE Store Local Sales</fullName>
            </value>
            <value>
                <fullName>VOICE Store After Sales</fullName>
            </value>
            <value>
                <fullName>VOICE Web Sales</fullName>
            </value>
            <value>
                <fullName>VOICE Web Click And Collect</fullName>
            </value>
            <value>
                <fullName>VOICE CSC Sales</fullName>
            </value>
            <value>
                <fullName>VOICE CSC Click And Collect</fullName>
            </value>
            <value>
                <fullName>VOICE Endless Offer</fullName>
            </value>
            <value>
                <fullName>VOICE Post Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VO_SurveyScoring__c/VO_SurveyScoring__c.object-meta.xml
<CustomObject>
    <description>Allow the score recalculation of a Survey type between 2 dates</description>
    <label>Survey scoring</label>
    <nameField>
        <displayFormat>VOSN-{0}</displayFormat>
        <label>Survey scoring Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey scoring</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VO_SurveyScoring__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <description>start date of the period the new scoring should be applied</description>
    <label>Start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VO_SurveyScoring__c/fields/SurveyType__c.field-meta.xml
<CustomField>
    <fullName>SurveyType__c</fullName>
    <description>picklist values should be the same as the ones available in the field Survey Type on Survey object to enable score calculation</description>
    <label>Survey type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VOICE Store Local Sales</fullName>
            </value>
            <value>
                <fullName>VOICE Store After Sales</fullName>
            </value>
            <value>
                <fullName>VOICE Web Sales</fullName>
            </value>
            <value>
                <fullName>VOICE CSC Sales</fullName>
            </value>
            <value>
                <fullName>VOICE CSC Click And Collect</fullName>
            </value>
            <value>
                <fullName>VOICE WEB Click And Collect</fullName>
            </value>
            <value>
                <fullName>VOICE Endless Offer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VO_BatchSurveyScoring_Test.cls
/*
To test VO_BatchSurveyScoring
Created by BW
Creation date : 30/10/2015
*/

@isTest
private class VO_BatchSurveyScoring_Test {

    static testMethod void myUnitTest() {
    	Test.loadData(VO_Config__c.sobjectType, 'VO_Config_TestCLS');
        User usr = IC_TestFactory.createUser('dreamuserLV165E38@lvtest.com');
	  	usr.profileId = IC_UTILS.getSysAdminProfile();
	  	usr.DefaultStore__c = 'LV GUADALAJARA PALACIO DE HIERRO';
	  	//usr.UserRoleId = role.Id;
	  	usr.DREAMId__c = '123456';
	  	usr.isactive = true;
	  	insert usr;
	  	VO_Config__c cs = new VO_Config__c(Name = 'NUM OF Q', Value__c = '50');
	  	insert cs;
    	Account acc = IC_TestFactory.createAccount();
		acc.DREAMID__c = '14712';
		insert acc;
		Store__c st = new Store__c(Name='STLesChamps', RetailStoreId__c = 'P3');
		insert st;
		ICONSettings__c iconSet = new ICONSettings__c();
		iconSet.ExcepPurchaseUSD__c=70;
		iconSet.Exceptional_Purchase_Currency__c='USD';	
		insert iconSet;
		PPR_PurchProduct__c pp = new PPR_PurchProduct__c(Client__c=acc.Id, TransactionRMSId__c='123',
			PurchasedDate__c = System.Today(),
			ProductLine__c = 'Shoes',
			SKU__c = '1515',
			TicketNumber__c = '789',
			Amount__c = 1000,
			ConvertedAmountUSD__c = 1000,
			SA__c=usr.id);
		insert pp; 
		VO_Survey__c srv = new VO_Survey__c(SurveyType__c=VO_Utils.VOICE_WEB_SALES, StoreID__c='P3', DreamIDText__c = '14712', IDTransaction__c='123', Scoring__c = '', AnswerDate__c = Date.newInstance(2015,10,01));
		VO_Survey__c srv2 = new VO_Survey__c(SurveyType__c=VO_Utils.VOICE_CSC_SALES, StoreID__c='P3', DreamIDText__c = '14712', IDTransaction__c='123', Scoring__c = '', AnswerDate__c = Date.newInstance(2015,10,01));
		VO_Survey__c srv3 = new VO_Survey__c(SurveyType__c=VO_Utils.VOICE_SALES, StoreID__c='P3', DreamIDText__c = '14712', IDTransaction__c='123', Scoring__c = '', AnswerDate__c = Date.newInstance(2015,10,01));
		VO_Survey__c srv4 = new VO_Survey__c(SurveyType__c=VO_Utils.VOICE_AFTER_SALES, StoreID__c='P3', DreamIDText__c = '14712', IDTransaction__c='123', Scoring__c = '', AnswerDate__c = Date.newInstance(2015,10,01));
		VO_SurveyScoring__c sc1 = new VO_SurveyScoring__c(SurveyType__c = VO_Utils.VOICE_WEB_SALES, StartDate__c = Date.newInstance(2015,10,01), EndDate__c = Date.newInstance(2015,10,01));
		VO_SurveyScoring__c sc2 = new VO_SurveyScoring__c(SurveyType__c = VO_Utils.VOICE_CSC_SALES, StartDate__c = Date.newInstance(2015,10,01), EndDate__c = Date.newInstance(2015,10,01));
		VO_SurveyScoring__c sc3 = new VO_SurveyScoring__c(SurveyType__c = VO_Utils.VOICE_SALES, StartDate__c = Date.newInstance(2015,10,01), EndDate__c = Date.newInstance(2015,10,01));
		VO_SurveyScoring__c sc4 = new VO_SurveyScoring__c(SurveyType__c = VO_Utils.VOICE_AFTER_SALES, StartDate__c = Date.newInstance(2015,10,01), EndDate__c = Date.newInstance(2015,10,01));

		insert new List<VO_Survey__c>{srv ,srv2,srv3,srv4};
		srv.Scoring__c = 'x';
		srv2.Scoring__c = 'x';
		srv3.Scoring__c = 'x';
		srv4.Scoring__c = 'x';
		update new List<VO_Survey__c>{srv ,srv2,srv3,srv4};

		insert new List<VO_SurveyScoring__c>{sc1 ,sc2,sc3,sc4};
		
		VO_BatchSurveyScoring.startBatch(sc1.Id, 200);
		VO_BatchSurveyScoring.startBatch(sc2.Id, 200);
		VO_BatchSurveyScoring.startBatch(sc3.Id, 200);
		VO_BatchSurveyScoring.startBatch(sc4.Id, 200);
    }
}