force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IC_Config__c/IC_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>IC Config</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/AccLastContactTimeRange__c.field-meta.xml
<CustomField>
    <fullName>AccLastContactTimeRange__c</fullName>
    <description>Defines the time range (in days) studied to display the &quot;Contacted in last X days&quot; in ICON Mobile (+ Batch)</description>
    <label>Account Last Contact Time Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/fields/ExcepPurchaseUSD__c.field-meta.xml
<CustomField>
    <fullName>ExcepPurchaseUSD__c</fullName>
    <defaultValue>3500</defaultValue>
    <label>Exceptional Purchase Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/fields/Exceptional_Purchase_Currency__c.field-meta.xml
<CustomField>
    <fullName>Exceptional_Purchase_Currency__c</fullName>
    <defaultValue>&quot;EUR&quot;</defaultValue>
    <label>Exceptional Purchase Currency</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ConvertedAmountEUR__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAmountEUR__c</fullName>
    <label>Converted Amount (EUR)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ConvertedAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAmountUSD__c</fullName>
    <label>Converted Amount (USD)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ConvertedAmountYEN__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAmountYEN__c</fullName>
    <label>Converted Amount (YEN)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ConvertedAmountYUAN__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAmountYUAN__c</fullName>
    <label>Converted Amount (YUAN)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <description>DREAM Id Transaction</description>
    <externalId>true</externalId>
    <label>DREAM Id Transaction</label>
    <length>29</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Jewelry</fullName>
            </value>
            <value>
                <fullName>Leather Goods</fullName>
            </value>
            <value>
                <fullName>Perfume</fullName>
            </value>
            <value>
                <fullName>Ready To Wear</fullName>
            </value>
            <value>
                <fullName>Shoes</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/PurchasedDate__c.field-meta.xml
<CustomField>
    <fullName>PurchasedDate__c</fullName>
    <label>Purchased Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/SA__c.field-meta.xml
<CustomField>
    <fullName>SA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link with the SA who sold the product.</description>
    <label>CA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchased_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TicketNumber__c.field-meta.xml
<CustomField>
    <fullName>TicketNumber__c</fullName>
    <externalId>true</externalId>
    <label>Ticket Number</label>
    <length>26</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IC_PPurchase_TRG_TEST.cls
@isTest
private class IC_PPurchase_TRG_TEST{

	@TestSetup
    public static void setup() {
        String identityProfile = [SELECT Id FROM Profile WHERE Name = 'Identity User'][0].Id;
        insert new IC_Config__c(
            Name = 'Identity User',
            Value__c = identityProfile
        );
    }
	
   //#####Test method for a USD Currency######		
   static testMethod void myTriggerTestUSD() 
    {   
    	//create a SA User 
    	// Start test
		Test.starttest();
        User usr = IC_TestFactory.createUser('dreamuserLV@lvtest.com');
	  	usr.profileId = IC_UTILS.getSAProfile();
	  	usr.DefaultStore__c = 'LV GUADALAJARA PALACIO DE HIERRO';
	  	//usr.UserRoleId = role.Id;
	  	usr.DREAMId__c = '123456';
	  	usr.isactive = true;
	  	insert usr;
	  	system.debug('### ASA test devise USD');
    	system.debug('### activ user ' + usr.isactive);
    	
    	
    	
    	// Create data for test
    	Account acc1 = new Account(
	        LastName = 'TCLTest',
	        FirstName='TCLTest',
	        DREAMID__c = '1515',
	        Salutation = 'Mr',
	        LastTrans__pc = System.Today(),
	        Segmentation__pc = 'VIC',
	        PersonDoNotCall = true,
	        PersonHasOptedOutOfEmail = true,
	        DoNotSMS__pc = true,
	        DoNotContactbyPost__pc = true,
	        BirthdateMonth__pc = '1',
	        Gender__pc = 'Male',
	        HistoricalSpendEUR__pc = 250000
        );
        insert acc1;
		
		list<PPR_PurchProduct__c> lPP = new list<PPR_PurchProduct__c>();
					
		ICONSettings__c iconSet = new ICONSettings__c();
		iconSet.ExcepPurchaseUSD__c=70;
		iconSet.Exceptional_Purchase_Currency__c='USD';
		iconSet.AccLastContactTimeRange__c=30;
		
		insert iconSet;
		
		// 2 Products With USD Currencies
		PPR_PurchProduct__c p1 = new PPR_PurchProduct__c(
			Client__c = acc1.Id,
			PurchasedDate__c = System.Today(),
			ProductLine__c = 'Shoes',
			SKU__c = '1515',
			TicketNumber__c = '789',
			Amount__c = 1000,
			ConvertedAmountUSD__c = 1000,
			SA__c=usr.id
			
		);
		lPP.add(p1);
		
		PPR_PurchProduct__c p2 = new PPR_PurchProduct__c(
			Client__c = acc1.Id,
			PurchasedDate__c = System.Today(),
			ProductLine__c = 'Shoes',
			SKU__c = '1515',
			TicketNumber__c = '789',
			Amount__c = 5000,
			ConvertedAmountUSD__c = 5000,
			SA__c=usr.id
		);
		lPP.add(p2);
		IC_PPurchase_TRG.ExcepPurchases(lPP);
		Task t = new task();
		t.RelatedTicketNumber__c = '789';
		t.Subject ='test';
		insert t;
				
		
		// Test insert trigger
		insert lPP;		
		Test.stopTest();	
		
    }	
    
	//#####Test method for a EUR Currency######
    static testMethod void myTriggerTestEUR() 
    {
    	User usr = IC_TestFactory.createUser('dreamuserLV@lvtest.com');
	  	usr.profileId = IC_UTILS.getSAProfile();
	  	usr.DefaultStore__c = 'LV GUADALAJARA PALACIO DE HIERRO';
	  	//usr.UserRoleId = role.Id;
	  	usr.DREAMId__c = '123456';
	  	usr.isactive = true;
	  	insert usr;  	
    	system.debug('### ASA test devise eur');
    	system.debug('### activ user ' + usr.isactive);
    	
    	   	
		// Create data for test 
		Account acc1 = new Account(
	        LastName = 'TCLTest',
	        FirstName='TCLTest',
	        DREAMID__c = '1515',
	        Salutation = 'Mr',
	        LastTrans__pc = System.Today(),
	        Segmentation__pc = 'VIC',
	        PersonDoNotCall = true,
	        PersonHasOptedOutOfEmail = true,
	        DoNotSMS__pc = true,
	        DoNotContactbyPost__pc = true,
	        BirthdateMonth__pc = '1',
	        Gender__pc = 'Male',
	        HistoricalSpendEUR__pc = 250000
        );
        insert acc1;
		
		list<PPR_PurchProduct__c> lPP = new list<PPR_PurchProduct__c>();
				
		ICONSettings__c iconSet = new ICONSettings__c();
		iconSet.ExcepPurchaseUSD__c=70;
		iconSet.Exceptional_Purchase_Currency__c='EUR';
		iconSet.AccLastContactTimeRange__c=30;
		
		insert iconSet;
		
		//2 Products With EUR Currencies
		PPR_PurchProduct__c p3 = new PPR_PurchProduct__c(
			Client__c = acc1.Id,
			PurchasedDate__c = System.Today().adddays(-14),
			ProductLine__c = 'Shoes',
			SKU__c = '1515',
			TicketNumber__c = '777',
			Amount__c = 1000,
			ConvertedAmountEUR__c = 1000,
			SA__c=usr.id
		);
		lPP.add(p3);
		
		PPR_PurchProduct__c p4 = new PPR_PurchProduct__c(
			Client__c = acc1.Id,
			PurchasedDate__c = System.Today().adddays(-14),
			ProductLine__c = 'Shoes',
			SKU__c = '1515',
			TicketNumber__c = '777',
			Amount__c = 5000,
			ConvertedAmountEUR__c = 5000,
			SA__c=usr.id
		);
		lPP.add(p4);
		
		IC_PPurchase_TRG.ExcepPurchases(lPP);
		Task t = new task();
		t.RelatedTicketNumber__c = '777';
		t.Subject ='test';
		insert t;
				
		// Start test
		Test.starttest();
		// Test insert trigger
		insert lPP;		
		Test.stopTest();
		
	}
    
    //#####Test method for a YEN Currency######
    static testMethod void myTriggerTestYEN() 
    {   
        User usr = IC_TestFactory.createUser('dreamuserLV@lvtest.com');
	  	usr.profileId = IC_UTILS.getSAProfile();
	  	usr.DefaultStore__c = 'LV GUADALAJARA PALACIO DE HIERRO';
	  	//usr.UserRoleId = role.Id;
	  	usr.DREAMId__c = '123456';
	  	usr.isactive = true;
	  	insert usr;  	
    	system.debug('### ASA test devise yen');
    	system.debug('### activ user ' + usr.isactive);
    	    	
    	// Create data for test
    	Account acc1 = new Account(
	        LastName = 'TCLTest',
	        FirstName='TCLTest',
	        DREAMID__c = '1515',
	        Salutation = 'Mr',
	        LastTrans__pc = System.Today().adddays(-14),
	        Segmentation__pc = 'VIC',
	        PersonDoNotCall = true,
	        PersonHasOptedOutOfEmail = true,
	        DoNotSMS__pc = true,
	        DoNotContactbyPost__pc = true,
	        BirthdateMonth__pc = '1',
	        Gender__pc = 'Male',
	        HistoricalSpendEUR__pc = 250000
        );
        insert acc1;
		
		list<PPR_PurchProduct__c> lPP = new list<PPR_PurchProduct__c>();
			
		ICONSettings__c iconSet = new ICONSettings__c();
		iconSet.ExcepPurchaseUSD__c=70;
		iconSet.Exceptional_Purchase_Currency__c='YEN';
		iconSet.AccLastContactTimeRange__c=30;
		
		insert iconSet;
		
		// 2 Products With USD Currencies
		PPR_PurchProduct__c p1 = new PPR_PurchProduct__c(
			Client__c = acc1.Id,
			PurchasedDate__c = System.Today().adddays(-14),
			ProductLine__c = 'Shoes',
			SKU__c = '1515',
			TicketNumber__c = '666',
			Amount__c = 1000,
			ConvertedAmountYEN__c = 1000,
			SA__c=usr.id
		);
		lPP.add(p1);
		
		PPR_PurchProduct__c p2 = new PPR_PurchProduct__c(
			Client__c = acc1.Id,
			PurchasedDate__c = System.Today().adddays(-14),
			ProductLine__c = 'Shoes',
			SKU__c = '1515',
			TicketNumber__c = '666',
			Amount__c = 5000,
			ConvertedAmountYEN__c = 5000,
			SA__c=usr.id
		);
		lPP.add(p2);
		IC_PPurchase_TRG.ExcepPurchases(lPP);
		Task t = new task();
		t.RelatedTicketNumber__c = '666';
		t.Subject ='test';
		insert t;
				
		// Start test
		Test.starttest();
		// Test insert trigger
		insert lPP;		
		Test.stopTest();	
		
    }	
    
     //#####Test method for a YUAN Currency######
     static testMethod void myTriggerTestYUAN() 
    {   
        User usr = IC_TestFactory.createUser('dreamuserLV@lvtest.com');
	  	usr.profileId = IC_UTILS.getSAProfile();
	  	usr.DefaultStore__c = 'LV GUADALAJARA PALACIO DE HIERRO';
	  	//usr.UserRoleId = role.Id;
	  	usr.DREAMId__c = '123456';
	  	usr.isactive = true;
	  	insert usr;
	  	system.debug('### ASA test devise yuan');
    	system.debug('### activ user ' + usr.isactive);
    	
    	// Create data for test
    	Account acc1 = new Account(
	        LastName = 'TCLTest',
	        FirstName='TCLTest',
	        DREAMID__c = '1515',
	        Salutation = 'Mr',
	        LastTrans__pc = System.Today().adddays(-14),
	        Segmentation__pc = 'VIC',
	        PersonDoNotCall = true,
	        PersonHasOptedOutOfEmail = true,
	        DoNotSMS__pc = true,
	        DoNotContactbyPost__pc = true,
	        BirthdateMonth__pc = '1',
	        Gender__pc = 'Male',
	        HistoricalSpendEUR__pc = 250000
        );
        insert acc1;
		
		list<PPR_PurchProduct__c> lPP = new list<PPR_PurchProduct__c>();
		
		ICONSettings__c iconSet = new ICONSettings__c();
		iconSet.ExcepPurchaseUSD__c=70;
		iconSet.Exceptional_Purchase_Currency__c='YUAN';
		iconSet.AccLastContactTimeRange__c=30;
		
		insert iconSet;
		
		// 2 Products With USD Currencies
		PPR_PurchProduct__c p1 = new PPR_PurchProduct__c(
			Client__c = acc1.Id,
			PurchasedDate__c = System.Today().adddays(-15),
			ProductLine__c = 'Shoes',
			SKU__c = '1515',
			TicketNumber__c = '555',
			Amount__c = 1000,
			ConvertedAmountYUAN__c = 1000,
			SA__c=usr.id
		);
		lPP.add(p1);
		
		PPR_PurchProduct__c p2 = new PPR_PurchProduct__c(
			Client__c = acc1.Id,
			PurchasedDate__c = System.Today().adddays(-15),
			ProductLine__c = 'Shoes',
			SKU__c = '1515',
			TicketNumber__c = '555',
			Amount__c = 5000,
			ConvertedAmountYUAN__c = 5000,
			SA__c=usr.id
		);
		lPP.add(p2);
		IC_PPurchase_TRG.ExcepPurchases(lPP);
		Task t = new task();
		t.RelatedTicketNumber__c = '555';
		t.Subject ='test';
		insert t;
				
		// Start test
		Test.starttest();
		// Test insert trigger
		insert lPP;		
		Test.stopTest();	
		
    }	
    
}