force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/CLI_CliList__c.object-meta.xml
<CustomObject>
    <description>Create your list of clients</description>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CLI_CliList__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Check if this is an active Client List.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/fields/Is_visible_by_CA__c.field-meta.xml
<CustomField>
    <fullName>Is_visible_by_CA__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is visible by CA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/fields/Offer_Code__c.field-meta.xml
<CustomField>
    <fullName>Offer_Code__c</fullName>
    <description>for Exclusive Experience campaigns</description>
    <label>Offer Code</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/fields/Show_In_Icon__c.field-meta.xml
<CustomField>
    <fullName>Show_In_Icon__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show In Icon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/fields/TECH_CreatedFromTCLScreen__c.field-meta.xml
<CustomField>
    <fullName>TECH_CreatedFromTCLScreen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH_CreatedFromTCLScreen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/fields/TECH_LaunchAddMembersBatch__c.field-meta.xml
<CustomField>
    <fullName>TECH_LaunchAddMembersBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TECH Launch Add Members Batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/fields/TECH_TempAccountIds__c.field-meta.xml
<CustomField>
    <fullName>TECH_TempAccountIds__c</fullName>
    <label>TECH Temp account ids</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
                <default>true</default>
                <label>Regular</label>
            </value>
            <value>
                <fullName>Exclusive</fullName>
            </value>
            <value>
                <fullName>Reassign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/fields/Typology__c.field-meta.xml
<CustomField>
    <fullName>Typology__c</fullName>
    <description>for Exclusive Experience campaigns</description>
    <label>Typology</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CLM_CliListMember__c/CLM_CliListMember__c.object-meta.xml
<CustomObject>
    <description>Customers in your client list.</description>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>CLM-{0}</displayFormat>
        <label>Client List Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_CliListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_CliListMember__c/fields/ClientList__c.field-meta.xml
<CustomField>
    <fullName>ClientList__c</fullName>
    <description>Client list which is containing this customer.</description>
    <inlineHelpText>Select the client list to contain this customer.</inlineHelpText>
    <label>Client List</label>
    <referenceTo>CLI_CliList__c</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLM_CliListMember__c/fields/DreamId__c.field-meta.xml
<CustomField>
    <fullName>DreamId__c</fullName>
    <formula>Client__r.Account.DREAMID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dream Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Iso2Code__c.field-meta.xml
<CustomField>
    <fullName>Iso2Code__c</fullName>
    <label>Iso2Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Iso3Code__c.field-meta.xml
<CustomField>
    <fullName>Iso3Code__c</fullName>
    <label>Iso3Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/tech_duplicate__c.field-meta.xml
<CustomField>
    <fullName>tech_duplicate__c</fullName>
    <description>To avoid duplicate countries</description>
    <externalId>true</externalId>
    <label>tech_duplicate</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/CountryLanguage__c.object-meta.xml
<CustomObject>
    <label>CountryLanguage</label>
    <nameField>
        <label>CountryLanguage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountryLanguages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CountryLanguage__c/fields/ATG_Locale__c.field-meta.xml
<CustomField>
    <fullName>ATG_Locale__c</fullName>
    <label>ATG Locale</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Locales</relationshipLabel>
    <relationshipName>CountryLanguages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is default locale for related country</description>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <referenceTo>Language2__c</referenceTo>
    <relationshipLabel>Locale</relationshipLabel>
    <relationshipName>CountryLanguages</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Salesforce_Locale__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Locale__c</fullName>
    <label>Salesforce Locale</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Language2__c/Language2__c.object-meta.xml
<CustomObject>
    <label>Language</label>
    <nameField>
        <label>Language Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Language2__c/fields/Iso2Code__c.field-meta.xml
<CustomField>
    <fullName>Iso2Code__c</fullName>
    <label>Iso2Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Language2__c/fields/Iso3Code__c.field-meta.xml
<CustomField>
    <fullName>Iso3Code__c</fullName>
    <label>Iso3Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BARBADE</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILE</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>COLOMBIA</fullName>
            </value>
            <value>
                <fullName>CYPRUS</fullName>
            </value>
            <value>
                <fullName>CZECH REPUBLIC</fullName>
            </value>
            <value>
                <fullName>DENMARK</fullName>
            </value>
            <value>
                <fullName>DOMINICAIN REPUBLIC</fullName>
            </value>
            <value>
                <fullName>FINLAND</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>GREECE</fullName>
            </value>
            <value>
                <fullName>GUAM</fullName>
            </value>
            <value>
                <fullName>HONG KONG</fullName>
            </value>
            <value>
                <fullName>HUNGARY</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDONESIA</fullName>
            </value>
            <value>
                <fullName>IRELAND</fullName>
            </value>
            <value>
                <fullName>ISRAEL</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>JORDANIE</fullName>
            </value>
            <value>
                <fullName>KOREA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-clienttarget/main/default/classes/CT_CreateNotificationsForCLMBatch_TEST.cls
@isTest
public with sharing class CT_CreateNotificationsForCLMBatch_TEST {
    @isTest
    public static void createNotificationsWithoutLanguageSettings_TEST() {
        List<String> membersList = createClientlistWithMembers();
        List<String> alreadyNotified = new List<String>();
        CT_CreateNotificationsForCLMBatch notificationsBatch = new CT_CreateNotificationsForCLMBatch(membersList, alreadyNotified);
        Database.executeBatch(notificationsBatch);
    }

    @isTest
    public static void createNotificationsForCLMBatch_TEST() {
        List<String> membersList = createClientlistWithMembers();
        createCountryLanguageSettings();
        List<String> alreadyNotified = new List<String>();
        CT_CreateNotificationsForCLMBatch notificationsBatch = new CT_CreateNotificationsForCLMBatch(membersList, alreadyNotified);
        Database.executeBatch(notificationsBatch);
    }

    public static List<String> createClientlistWithMembers() {
        User user = createUser();
        Account acc = createAccount(user.Id, '110592112', true);
        Account acc2 = createAccount(user.Id, '110592116', false);
        Account acc3 = createAccount(user.Id, '110592119', true);
        List<String> clientIdsList = new List<String>{acc.Id, acc2.Id, acc3.Id};
        List<Account> accList = [SELECT PersonContactId FROM Account WHERE Id in :clientIdsList];
        List<String> contactIdsList = new List<String>();

        for (Account a : accList) {
            contactIdsList.add(a.PersonContactId);
        }

        String commaSepIds = contactIdsList.size() > 0 ? String.join(contactIdsList, ';') : '';

        CLI_CliList__c clientList = new CLI_CliList__c(
            Name = 'Test',
            Active__c = true,
            ExpirationDate__c = date.today().addYears(1),
            Description__c = 'Test',
            Is_visible_by_CA__c = true,
            Typology__c = 'NBA Regular',
            Type__c = 'exclusive',
            Offer_Code__c = 'exclu_nba_1_2020',
            Show_In_Icon__c = true,
            TECH_LaunchAddMembersBatch__c = true,
            TECH_TempAccountIds__c = commaSepIds,
            TECH_CreatedFromTCLScreen__c = true,
            OwnerId = user.Id
        );    

        insert clientList;

        List<CLM_CliListMember__c> membersList = new List<CLM_CliListMember__c>();
        for (String id : contactIdsList) {
          CLM_CliListMember__c CLM = new CLM_CliListMember__c(
              ClientList__c = clientList.Id,
              Client__c = id
          );
          membersList.add(CLM);
        }

        insert membersList;

        List<String> clmIds = new List<String>();
        for (CLM_CliListMember__c clm : membersList) {
          clmIds.add(clm.Id);
        }
        return clmIds;
    }

    public static User createUser() {
        ApexPages.standardController controller = new ApexPages.standardController(new Account());
        Global_ClientViewDispatch_VFCx extension = new Global_ClientViewDispatch_VFCx(controller);
        Account currentAccount = extension.currentAccount;
        Profile p = [SELECT Id FROM Profile WHERE Name = 'STAR_Corporate'];
        User user = new User(Alias = 'Tester', Email = 'adminUser@testlv.com',
				EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
				LocaleSidKey = 'en_US', ProfileId = p.Id,
				TimeZoneSidKey = 'America/Los_Angeles', UserName = randomNumber() + 'adminUser@testlv.com');
        insert user;
        return user;
    }

    public static Account createAccount(Id userId, String dreamId, Boolean withCountry) {
        Account acc = new Account(
            Firstname = 'test' + randomNumber(),
            LastName = 'test' + randomNumber(),
            PersonEmail = 'test' + dreamId + '@balink.net',
            OwnerId = userId,
            DREAMID__c = dreamId
        );

        if (withCountry) {
            acc.PreferredLanguage__pc = 'JPN';
            acc.AttachedStoreCountry__pc = 'JPN';
            acc.HomeAddressCountryCode__pc = 'JPN';
        }

        insert acc;
        return acc;
    }

    public static Integer randomNumber() {
        return Integer.valueof((Math.random() * 10));
    }


    public static String randomDreamId() {
      String dreamId = '';
      for (Integer i = 0; i < 8; i++) {
          dreamId += randomNumber();
      }
      return dreamId;
    }

    public static void createCountryLanguageSettings() {
        List<Country__c> countries = new List<Country__c>{
          new Country__c(
            Name = 'CHINA',
            tech_duplicate__c = 'China',
            Iso2Code__c = 'CN',
            Iso3Code__c = 'CHN'
          ),
          new Country__c(
            Name = 'JAPAN',
            tech_duplicate__c = 'Japan',
            Iso2Code__c = 'JP',
            Iso3Code__c = 'JPN'
          ),
          new Country__c(
            Name = 'KOREA',
            tech_duplicate__c = 'Korea',
            Iso2Code__c = 'KR',
            Iso3Code__c = 'KOR'
          ),
          new Country__c(
            Name = 'RUSSIA',
            tech_duplicate__c = 'Russia',
            Iso2Code__c = 'RU',
            Iso3Code__c = 'RUS'
          )
        };
        insert countries;
    
        List<Language2__c> languages = new List<Language2__c>{
          new Language2__c(
            Name = 'CHINESE',
            Iso2Code__c = 'ZH',
            Iso3Code__c = 'ZHO'
          ),
          new Language2__c(
            Name = 'JAPANESE',
            Iso2Code__c = 'JA',
            Iso3Code__c = 'JPN'
          ),
          new Language2__c(
            Name = 'KOREAN',
            Iso2Code__c = 'KO',
            Iso3Code__c = 'KOR'
          ),
          new Language2__c(
            Name = 'RUSSIAN',
            Iso2Code__c = 'RU',
            Iso3Code__c = 'RUS'
          )
        };
        insert languages;
    
        List<Country__c> c = [
          SELECT Id, Name
          FROM Country__c
          WHERE Name IN ('CHINA', 'JAPAN', 'KOREA', 'RUSSIA')
        ];
        List<Language2__c> l = [
          SELECT Id, Name
          FROM Language2__c
          WHERE Name IN ('CHINESE', 'JAPANESE', 'KOREAN', 'RUSSIAN')
        ];
    
        List<CountryLanguage__c> cl = new List<CountryLanguage__c>{
          new CountryLanguage__c(
            Name = 'Chinese China',
            ATG_Locale__c = 'zhs-cn',
            Salesforce_Locale__c = 'zh_CN',
            Country__c = c[0].Id,
            Language__c = l[0].Id,
            Default__c = true
          ),
          new CountryLanguage__c(
            Name = 'Japanese Japan',
            ATG_Locale__c = 'jpn-jp',
            Salesforce_Locale__c = 'ja_JP',
            Country__c = c[1].Id,
            Language__c = l[1].Id,
            Default__c = true
          ),
          new CountryLanguage__c(
            Name = 'Korean Korea',
            ATG_Locale__c = 'kor-kr',
            Salesforce_Locale__c = 'ko_KR',
            Country__c = c[2].Id,
            Language__c = l[2].Id,
            
            Default__c = true
          ),
          new CountryLanguage__c(
            Name = 'Russian Russia',
            ATG_Locale__c = 'rus-ru',
            Salesforce_Locale__c = 'ru_RU',
            Country__c = c[3].Id,
            Language__c = l[3].Id,
            Default__c = true
          )
        };
        insert cl;
      }
}