force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/due__Diduenjoy_Feedback__c.object-meta.xml
<CustomObject>
    <label>Diduenjoy Feedback</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diduenjoy Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Account__c.field-meta.xml
<CustomField>
    <fullName>due__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Diduenjoy Feedbacks</relationshipLabel>
    <relationshipName>Diduenjoy_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Comment__c.field-meta.xml
<CustomField>
    <fullName>due__Comment__c</fullName>
    <label>Comment</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__CreatedAt__c.field-meta.xml
<CustomField>
    <fullName>due__CreatedAt__c</fullName>
    <label>CreatedAt</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__InternalId__c.field-meta.xml
<CustomField>
    <fullName>due__InternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>InternalId</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Last_Resolution_Date__c.field-meta.xml
<CustomField>
    <fullName>due__Last_Resolution_Date__c</fullName>
    <label>Last Resolution Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Permalink__c.field-meta.xml
<CustomField>
    <fullName>due__Permalink__c</fullName>
    <label>Permalink</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Profile__c.field-meta.xml
<CustomField>
    <fullName>due__Profile__c</fullName>
    <label>Profile</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Segments__c.field-meta.xml
<CustomField>
    <fullName>due__Segments__c</fullName>
    <label>Segments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Solved__c.field-meta.xml
<CustomField>
    <fullName>due__Solved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Status__c.field-meta.xml
<CustomField>
    <fullName>due__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>live</fullName>
                <default>true</default>
                <label>live</label>
            </value>
            <value>
                <fullName>soft_deleted</fullName>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__User__c.field-meta.xml
<CustomField>
    <fullName>due__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Diduenjoy_Feedbacks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/Treated__c.field-meta.xml
<CustomField>
    <fullName>Treated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Will be used in Batch processing</description>
    <label>Treated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VO_Config__c/VO_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>VO_Config</label>
</CustomObject>

force-app/main/default/objects/VO_Survey__c/VO_Survey__c.object-meta.xml
<CustomObject>
    <label>Voice</label>
    <nameField>
        <displayFormat>Survey-{00000000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VO_Survey__c/fields/Answer_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Answer_DateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Default value equal to now. Used to compute the status duration.</description>
    <label>Answer Date (time)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/DreamID__c.field-meta.xml
<CustomField>
    <fullName>DreamID__c</fullName>
    <formula>ClientDreamID__r.DREAMID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DreamID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/DreamIDText__c.field-meta.xml
<CustomField>
    <fullName>DreamIDText__c</fullName>
    <description>Denormalized data from Account --&gt; sent by Clicktools</description>
    <label>Dream ID Text</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/FeedbackID__c.field-meta.xml
<CustomField>
    <fullName>FeedbackID__c</fullName>
    <externalId>true</externalId>
    <label>Feedback ID</label>
    <length>36</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/IDTransaction__c.field-meta.xml
<CustomField>
    <fullName>IDTransaction__c</fullName>
    <description>Denormalized data from Purchased Products --&gt; sent by Clicktools</description>
    <label>ID Transaction</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/LastResolutionDate__c.field-meta.xml
<CustomField>
    <fullName>LastResolutionDate__c</fullName>
    <label>Last Resolution Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Solved__c.field-meta.xml
<CustomField>
    <fullName>Solved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Default value equal to New. Changed to closed if new or pending 2 months after answer date. Changed to No action if the channel equals to No action (old voice)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>live</fullName>
            </value>
            <value>
                <fullName>soft_deleted</fullName>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>No action</fullName>
                <default>true</default>
                <label>No action</label>
            </value>
            <value>
                <fullName>noShow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>populated with VO_Survey apex class before insert from StoreID__c field</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Diduenjoy_FeedbackTriggerHandler_Test.cls
/**
    @Author : ouramdane.aouci
    Desc:     test class for Diduenjoy_FeedbackTriggerHandler
    V 1.0 :   12/06/2023
*/
@isTest
private class Diduenjoy_FeedbackTriggerHandler_Test {
    
    @testSetup
    private static void setup(){
        
        Test.loadData(VO_Config__c.sobjectType, 'VO_Config_TestCLS');
        User usr = IC_TestFactory.createUser('dreamuserLV@lvtest.com');
        usr.profileId = IC_UTILS.getSAProfile();
        usr.DefaultStore__c = 'LV Paris';
        usr.DREAMId__c = '123456';
        usr.isactive = true;
        INSERT usr;
        
        VO_Config__c cs = new VO_Config__c(Name = 'NUM OF Q', Value__c = '50');
        INSERT cs;
        
        List<Account> accList = new List<Account>();
        for(Integer i=1; i<=3; i++){
            Account acc = IC_TestFactory.createAccount();
            acc.DREAMID__c = '12345678'+i;
            accList.add(acc);
        }
        INSERT accList;
        
        List<Store__c> storesList = new List<Store__c>();
        Store__c st1 = new Store__c(Name='Store AS', RetailStoreId__c = 'A07');  storesList.add(st1);
        INSERT storesList;
        
        List<due__Diduenjoy_Feedback__c> feedbacksList = new List<due__Diduenjoy_Feedback__c>();
        //Retail Post Purchase
        for(Integer i=1; i<=3; i++){
            feedbacksList.add(new due__Diduenjoy_Feedback__c(Name='FeedBack_'+i, due__CreatedAt__c = DateTime.newInstance(2023,06,15), due__Profile__c = 'NPS',
                                                             due__Permalink__c = 'www.feedback.fdbk'+i, due__Comment__c='Comment test '+i,due__Status__c='live',
                                                             due__Solved__c = false, due__InternalId__c='9348-ebbef4a31f5'+i,
                                                             due__Segments__c = 'survey-name: Retail Post Purchase\r\nclient_dream_id:12345678'+i
                                                             + '\r\ntransaction_id:1239'+i+'\r\nadvisor_ww_id:LVM03075'+i+'\r\nrespondent_profile:Score '+i, 
                                                             due__User__c = usr.Id, due__Account__c = accList[i-1].Id, treated__c=true));										
        }
        INSERT feedbacksList;
        
        //Insert some Surveys
        List<VO_Survey__c> voList =new List<VO_Survey__c>();
        voList.add( new VO_Survey__c(DreamIDText__c = '123456781', IDTransaction__c='12391', FeedbackID__c='9348-ebbef4a31f51', Answer_DateTime__c=DateTime.newInstance(2023,06,15), Status__c='live', Solved__c=false));
        voList.add( new VO_Survey__c(DreamIDText__c = '123456782', IDTransaction__c='12392', FeedbackID__c='9348-ebbef4a31f52', Answer_DateTime__c=DateTime.newInstance(2023,06,15), Status__c='live', Solved__c=false));
        voList.add( new VO_Survey__c(DreamIDText__c = '123456783', IDTransaction__c='12393', FeedbackID__c='9348-ebbef4a31f53', Answer_DateTime__c=DateTime.newInstance(2023,06,15), Status__c='live', Solved__c=false));
        INSERT voList;
        
    }
    
    @isTest
    private static void testAfterUpdateFeedback(){
        System.debug('Launch test ...');
        System.assertEquals(3, [SELECT count() FROM due__Diduenjoy_Feedback__c WHERE Treated__c = true], 'DUE Feedback');
        System.assertEquals(3, [SELECT count() FROM VO_Survey__c], 'VO_Survey');
        
        Test.startTest();
        List<due__Diduenjoy_Feedback__c> feedbackList = [SELECT Id, due__Status__c, due__Solved__c, due__Last_Resolution_Date__c FROM due__Diduenjoy_Feedback__c];
        if(feedbackList.size() > 0){
            feedbackList[0].due__Status__c = 'deleted';
            feedbackList[1].due__Solved__c = true;
            feedbackList[1].due__Last_Resolution_Date__c = DateTime.newInstance(2023,06,15);
            feedbackList[2].due__Comment__c = 'test';
            
            UPDATE feedbackList;
        }   
        Test.stopTest();
        
        for(VO_Survey__c vo : 	[SELECT Id, DreamIDText__c, Status__c, Solved__c, LastResolutionDate__c FROM VO_Survey__c]){
            System.debug(vo);
        }
    }
}