force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Brand_Experience__c/Brand_Experience__c.object-meta.xml
<CustomObject>
    <description>Object to create Brand Experiences. Parent object of Experience Variation (Brand_Experience_Variation__c)</description>
    <label>Events &amp; Experience</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events &amp; Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience__c/fields/ClubName__c.field-meta.xml
<CustomField>
    <fullName>ClubName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Club associated with the Experience</description>
    <label>Club</label>
    <referenceTo>Club_and_Seasons__c</referenceTo>
    <relationshipName>Brand_Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Experience__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Experience</description>
    <inlineHelpText>Calculated based on child Variations statuses</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Partially Ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Published</fullName>
                <isActive>false</isActive>
                <label>Published</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/Brand_Experience_Variation__c.object-meta.xml
<CustomObject>
    <description>Object to create variations of Brand Experiences (Digital Events, Physical Events, Content, Exclusive Offers, ...)
Child object of Experience (Brand_Experience__c). Parent object of Experience Variation Member (Brand_Experience_Variation_Member__c).</description>
    <label>Event &amp; Experience Activation</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event &amp; Experience Activations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/Brand_Experience__c.field-meta.xml
<CustomField>
    <fullName>Brand_Experience__c</fullName>
    <description>Experience associated with the Experience Variation</description>
    <label>Event &amp; Experience</label>
    <referenceTo>Brand_Experience__c</referenceTo>
    <relationshipLabel>Event &amp; Experience Activations</relationshipLabel>
    <relationshipName>Brand_Experience_Variations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <description>Date &amp; Time at which Brand Experience Variation ends (GMT+02)</description>
    <label>End Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/RequiredClientRegistration__c.field-meta.xml
<CustomField>
    <fullName>RequiredClientRegistration__c</fullName>
    <description>The client will be required to register before accessing the Brand Experience Variation.</description>
    <inlineHelpText>Eligible clients will be requested to register between Registration Start Date &amp; Time and Registration End Date &amp; Time</inlineHelpText>
    <label>Client Registration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Registration</fullName>
                <default>true</default>
                <label>No Registration</label>
            </value>
            <value>
                <fullName>Mandatory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <description>Date &amp; Time at which Experience Variation starts</description>
    <inlineHelpText>Variation status changes to &quot;Participation Opened&quot; at Start Date &amp; Time</inlineHelpText>
    <label>Start Date &amp; Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Brand Experience Variation</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>Published</label>
            </value>
            <value>
                <fullName>Preview</fullName>
                <label>Member Preview</label>
            </value>
            <value>
                <fullName>Registration Opened</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Selection Opened</fullName>
            </value>
            <value>
                <fullName>Selection Closed</fullName>
            </value>
            <value>
                <fullName>Participation Opened</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Variation__c/fields/TargetingMethod__c.field-meta.xml
<CustomField>
    <fullName>TargetingMethod__c</fullName>
    <description>Method to target client. Manual targeting is done through Client Target. Dynamic targeting uses eligibility criteria</description>
    <label>Client Targeting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dynamic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
                <label>Client Target</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Variation_Member__c/Brand_Experience_Variation_Member__c.object-meta.xml
<CustomObject>
    <label>Event &amp; Experience Activation Member</label>
    <nameField>
        <label>Experience Activation Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event &amp; Experience Activation Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/Brand_Experience_Variation__c.field-meta.xml
<CustomField>
    <fullName>Brand_Experience_Variation__c</fullName>
    <description>Experience Variation Identifier</description>
    <label>Activation</label>
    <referenceTo>Brand_Experience_Variation__c</referenceTo>
    <relationshipLabel>Event &amp; Experience Activation Members</relationshipLabel>
    <relationshipName>Brand_Experience_Variation_Members</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client Identifier</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Brand_Experience_Variation_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/ClubMember__c.field-meta.xml
<CustomField>
    <fullName>ClubMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Club Member</label>
    <referenceTo>Club_MemberShip__c</referenceTo>
    <relationshipName>Brand_Experience_Variation_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Experience_Variation_Member__c/fields/IsSelected__c.field-meta.xml
<CustomField>
    <fullName>IsSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Client is selected to participate to the Experience</description>
    <label>Is Selected</label>
    <type>Checkbox</type>
</CustomField>

force-experience/main/default/objects/Brand_Experience_Variation_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of an Experience Member</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Not Registered</fullName>
            </value>
            <value>
                <fullName>To Contact</fullName>
            </value>
            <value>
                <fullName>Removed Manually</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <label>Confirmed</label>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Not Participated</fullName>
            </value>
            <value>
                <fullName>Participated</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <isActive>false</isActive>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Not Selected</fullName>
                <isActive>false</isActive>
                <label>Not Selected</label>
            </value>
            <value>
                <fullName>Selected</fullName>
                <isActive>false</isActive>
                <label>Selected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/Club_MemberShip__c.object-meta.xml
<CustomObject>
    <label>Club Membership</label>
    <nameField>
        <label>Club MemberShip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_MemberShip__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <description>Account Id</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Clubs_MemberShip</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/Club_and_Seasons__c.field-meta.xml
<CustomField>
    <fullName>Club_and_Seasons__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Club</label>
    <referenceTo>Club_and_Seasons__c</referenceTo>
    <relationshipName>Clubs_MemberShip</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/clubName__c.field-meta.xml
<CustomField>
    <fullName>clubName__c</fullName>
    <formula>Club_and_Seasons__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Club Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/clubStatus__c.field-meta.xml
<CustomField>
    <fullName>clubStatus__c</fullName>
    <description>Membership levels from the LV Clubs</description>
    <label>Club Status TECH</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClubStatusList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/dreamId__c.field-meta.xml
<CustomField>
    <fullName>dreamId__c</fullName>
    <description>Client/Member DreamId</description>
    <label>Dream ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/isClubEligible__c.field-meta.xml
<CustomField>
    <fullName>isClubEligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Club Eligibility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/isMember__c.field-meta.xml
<CustomField>
    <fullName>isMember__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Status stating the Client passed the Club onboarding steps and accessed the LV Club</description>
    <label>is Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/lastStatusUpdated__c.field-meta.xml
<CustomField>
    <fullName>lastStatusUpdated__c</fullName>
    <description>Date &amp; Hour at which LV Club member status changed</description>
    <label>Club Status Update Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <label>Unique Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/ClubStatusList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bronze</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl</fullName>
    </customValue>
    <customValue>
        <fullName>Not Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Client Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultra Rare</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <masterLabel>Club Status List</masterLabel>
</GlobalValueSet>

force-experience/main/default/classes/ExperienceVariationTriggerHandler_TEST.cls
@IsTest
private class ExperienceVariationTriggerHandler_TEST {
    @testSetup
    static void setup() {
        Club_and_Seasons__c clubSneakers = new Club_and_Seasons__c(
            Name = 'Sneakers'
        );
        insert clubSneakers;
        
        Brand_Experience__c ex = new Brand_Experience__c(
            Name = 'test',
            Status__c = 'Ongoing',
            ClubName__c = clubSneakers.Id
        );

        insert ex;

        Brand_Experience_Variation__c exVar = new Brand_Experience_Variation__c(
            Brand_Experience__c = ex.Id,
            Name = 'test',
            TargetingMethod__c = 'Dynamic',
            StartDateTime__c = system.now() ,
            RequiredClientRegistration__c = 'No Registration',
            EndDateTime__c = system.now() + 2000
        );
        insert  exVar;

        Account acc = new Account(
            FirstName = 'Yon',
            LastName = 'Memos',
            DREAMID__c = 'asdfghj145',
            AttachedStore__pc = 'UEC',
            AttachedStoreCode__pc = 'UEC',
            PersonEmail = 'test@test.com',
            SPO_Country_code__pc = 'USA'
        );
        insert acc;

        Club_MemberShip__c clubM = new Club_MemberShip__c(
            clientId__c = acc.Id,
            dreamId__c = 'asdfghj145',
            Club_and_Seasons__c = clubSneakers.id,
            clubStatus__c = 'Pearl',
            isMember__c = true, 
            isClubEligible__c = true,
            lastStatusUpdated__c = system.now(),
            Unique_Key__c = acc.DREAMID__c + '_' + clubSneakers.Name
        );
        insert clubM;
    }

    @isTest
    static void testHandleAfterUpdate() {
        User testUser = ICX_TestFactory.createUser(ICX_TestFactory.PROFILE_SYSTEM_ADMINNISTRATOR);
        insert testUser;

        System.runAs(testUser) {
            Test.startTest();
            Club_MemberShip__c clubM = [SELECT Id, clientId__c FROM Club_MemberShip__c LIMIT 1];
            Brand_Experience_Variation__c exVar = [SELECT Id FROM Brand_Experience_Variation__c LIMIT 1];


            Brand_Experience_Variation_Member__c exMember = new Brand_Experience_Variation_Member__c(
                Brand_Experience_Variation__c = exVar.Id,
                ClubMember__c = clubM.Id,
                Client__c = clubM.clientId__c,
                Name = 'test',
                Status__c ='Ready',
                isSelected__c = true,
                NominationStatus__c = 'Approved'
            );

          	insert exMember;
            
          
            exVar.Status__c = 'Participation Opened';
            update exVar;
        
            Test.stopTest();
        }
    }
    @isTest
    static void testHandleAfterUpdateForEndedStatus() {
        User testUser = ICX_TestFactory.createUser(ICX_TestFactory.PROFILE_SYSTEM_ADMINNISTRATOR);
        insert testUser;

        System.runAs(testUser) {
            Test.startTest();
            Club_MemberShip__c clubM = [SELECT Id, clientId__c FROM Club_MemberShip__c LIMIT 1];
            Brand_Experience_Variation__c exVar = [SELECT Id FROM Brand_Experience_Variation__c LIMIT 1];


            Brand_Experience_Variation_Member__c exMember = new Brand_Experience_Variation_Member__c(
                Brand_Experience_Variation__c = exVar.Id,
                ClubMember__c = clubM.Id,
                Client__c = clubM.clientId__c,
                Name = 'test',
                Status__c ='Ready',
                isSelected__c = true,
                NominationStatus__c = 'Approved'
            );

          	insert exMember;
            
          
            exVar.Status__c = 'Participation Opened';
            update exVar;
        
         	exVar.Status__c = 'Ended';
            update exVar;
            Test.stopTest();
        }
    }
}