force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>20HeCard</fullName>
            </value>
            <value>
                <fullName>20MDeCard</fullName>
            </value>
            <value>
                <fullName>Client Service</fullName>
            </value>
            <value>
                <fullName>DREAM</fullName>
            </value>
            <value>
                <fullName>Identity</fullName>
            </value>
            <value>
                <fullName>KBRW</fullName>
            </value>
            <value>
                <fullName>Line</fullName>
            </value>
            <value>
                <fullName>LineTaiwan</fullName>
            </value>
            <value>
                <fullName>LineThai</fullName>
            </value>
            <value>
                <fullName>LV&amp;exhiJap</fullName>
            </value>
            <value>
                <fullName>LV App</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>MyCC</fullName>
            </value>
            <value>
                <fullName>MyLV</fullName>
            </value>
            <value>
                <fullName>MyRepairs</fullName>
            </value>
            <value>
                <fullName>On App</fullName>
            </value>
            <value>
                <fullName>Online Appt</fullName>
            </value>
            <value>
                <fullName>WeChat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-clientforce/main/default/objects/C360_Logs__c/C360_Logs__c.object-meta.xml
<CustomObject>
    <label>C360_Logs</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>C360_Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>C360_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-clientforce/main/default/objects/C360_Logs__c/fields/DreamId__c.field-meta.xml
<CustomField>
    <fullName>DreamId__c</fullName>
    <label>DreamId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_APEX_Limits__c.field-meta.xml
<CustomField>
    <fullName>TR_APEX_Limits__c</fullName>
    <label>APEX Limits</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_Error__c.field-meta.xml
<CustomField>
    <fullName>TR_Error__c</fullName>
    <label>Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_Has_Error__c.field-meta.xml
<CustomField>
    <fullName>TR_Has_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_JSON__c.field-meta.xml
<CustomField>
    <fullName>TR_JSON__c</fullName>
    <label>JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_Level__c.field-meta.xml
<CustomField>
    <fullName>TR_Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-clientforce/main/default/objects/C360_Tech_Event__e/C360_Tech_Event__e.object-meta.xml
<CustomObject>
    <label>C360_Tech_Event</label>
    <pluralLabel>C360_Tech_Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/C360_Tech_Event__e/fields/Body_Json__c.field-meta.xml
<CustomField>
    <fullName>Body_Json__c</fullName>
    <label>Body_Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/C360_Tech_Event__e/fields/Tech_Integration_Id__c.field-meta.xml
<CustomField>
    <fullName>Tech_Integration_Id__c</fullName>
    <label>Tech_Integration_Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-clientforce/main/default/objects/C360_Tech_Event__e/fields/TR_Object_Id__c.field-meta.xml
<CustomField>
    <fullName>TR_Object_Id__c</fullName>
    <label>TR_Object_Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-clientforce/main/default/objects/C360_Tech_Event__e/fields/TR_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>TR_Object_Name__c</fullName>
    <label>TR_Object_Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/C360_Tech_Event_Return_Flow__e/C360_Tech_Event_Return_Flow__e.object-meta.xml
<CustomObject>
    <label>C360_Tech_Event_Return_Flow</label>
    <pluralLabel>C360_Tech_Event_Return_Flow</pluralLabel>
</CustomObject>

force-app/main/default/objects/C360_Tech_Event_Return_Flow__e/fields/Body_Json__c.field-meta.xml
<CustomField>
    <fullName>Body_Json__c</fullName>
    <label>Body_Json</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Social_Media_Identifier__c/Social_Media_Identifier__c.object-meta.xml
<CustomObject>
    <label>Social Media Identifier</label>
    <nameField>
        <displayFormat>SMI-{0000}</displayFormat>
        <label>Social Media Identifier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media Identifiers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Media_Identifier__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Client (PersonAccount)</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Social Media Identifiers</relationshipLabel>
    <relationshipName>Social_Media_Identifiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-clientforce/main/default/objects/TECH_IntegrationManager__c/TECH_IntegrationManager__c.object-meta.xml
<CustomObject>
    <label>TECH Integration Managers</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Integration Managers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TECH Integration Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-clientforce/main/default/objects/TECH_IntegrationManager__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <externalId>true</externalId>
    <label>AccountId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-clientforce/main/default/objects/TECH_IntegrationManager__c/fields/Object_Id__c.field-meta.xml
<CustomField>
    <fullName>Object_Id__c</fullName>
    <label>Object_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-clientforce/main/default/objects/TECH_IntegrationManager__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object_Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TR_C360_Field_Mapping__mdt/TR_C360_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>C360 Field Mapping</label>
    <pluralLabel>C360 Fields Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/TR_C360_Field_Mapping__mdt/fields/C360_Field__c.field-meta.xml
<CustomField>
    <fullName>C360_Field__c</fullName>
    <label>C360 Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TR_C360_Field_Mapping__mdt/fields/Is_From_C360__c.field-meta.xml
<CustomField>
    <fullName>Is_From_C360__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is From C360</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TR_C360_Field_Mapping__mdt/fields/SF_Field__c.field-meta.xml
<CustomField>
    <fullName>SF_Field__c</fullName>
    <label>SF_Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-clientforce/main/default/objects/TR_Integration_Manager_Setting__c/TR_Integration_Manager_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TR_Integration_Manager_Setting</label>
</CustomObject>

force-clientforce/main/default/objects/TR_Integration_Manager_Setting__c/fields/Client_default_RecordType__c.field-meta.xml
<CustomField>
    <fullName>Client_default_RecordType__c</fullName>
    <label>Client default RecordType</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-clientforce/main/default/objects/TR_Integration_Manager_Setting__c/fields/Excluded_UserId__c.field-meta.xml
<CustomField>
    <fullName>Excluded_UserId__c</fullName>
    <label>Excluded_UserId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TR_Integration_Manager_Setting__c/fields/Json_Added__c.field-meta.xml
<CustomField>
    <fullName>Json_Added__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Json Added</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BARBADE</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILE</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>COLOMBIA</fullName>
            </value>
            <value>
                <fullName>CYPRUS</fullName>
            </value>
            <value>
                <fullName>CZECH REPUBLIC</fullName>
            </value>
            <value>
                <fullName>DENMARK</fullName>
            </value>
            <value>
                <fullName>DOMINICAIN REPUBLIC</fullName>
            </value>
            <value>
                <fullName>FINLAND</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>GREECE</fullName>
            </value>
            <value>
                <fullName>GUAM</fullName>
            </value>
            <value>
                <fullName>HONG KONG</fullName>
            </value>
            <value>
                <fullName>HUNGARY</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDONESIA</fullName>
            </value>
            <value>
                <fullName>IRELAND</fullName>
            </value>
            <value>
                <fullName>ISRAEL</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>JORDANIE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/World_Wide_Technical_User__mdt/World_Wide_Technical_User__mdt.object-meta.xml
<CustomObject>
    <description>World - Wide Technical User is used by the MyCC flow to define the technical user corresponding to the customer&apos;s country</description>
    <label>World - Wide Technical User</label>
    <pluralLabel>World - Wide Technical User</pluralLabel>
</CustomObject>

force-app/main/default/objects/World_Wide_Technical_User__mdt/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User - Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TR_C360_IntegrationManager_Utils.cls
/***************************************************************************************************
* @File Name          : TR_C360_IntegrationManager_Utils.cls
* @Description        : This class was created for the C360 project To manage all flux 
* @Author             : Imad.alsidchikh.ext@louisvuitton.com
* @Group              : VO2
* @Last Modified By   : Imad.alsidchikh.ext@louisvuitton.com
* @Last Modified On   : 02-22-2022
* @Modification Log   :
* Ver       Date               Author                            Modification
* 1.0       02-22-2022        Imad.alsidchikh.ext@louisvuitton.com     Initial Version
* 1.1       06-19-2023        hamza.bouzid.ext@louisvuitton.com Dynamic insert of json in log
* 1.2       11-13-2023        yann.aquilon.ext@louisvuitton.com take care of Null value from JSon
*****************************************************************************************************/
public without sharing class TR_C360_IntegrationManager_Utils {
    
    
    public static Map<String,List<Social_Media_Identifier__c>> smiRecordMap;
    public static Map<String, Contact> contRecordMap;
    
    public static void initSendMethod(Set<Id> accIds,Set<Id> timIds){
        if(System.IsBatch() == false && System.isFuture() == false){ 
            callSendMethodAs(accIds, timIds);
        }else{
            callSendMethodS(accIds,timIds);  
        }
    }
    @future
    public static void callSendMethodAs(Set<Id> accIds,Set<Id> timIds){
        sendChangeToClient360(accIds,timIds);   
    }
    public static void callSendMethodS(Set<Id> accIds,Set<Id> timIds){
        sendChangeToClient360(accIds,timIds);
    }
    public static void sendChangeToClient360(Set<Id> accIds,Set<Id> timIds){
        List<TECH_IntegrationManager__c> integManags = getTechManagerRecords(timIds);
        List<C360_Tech_Event__e> inkEvents = new List<C360_Tech_Event__e>();
        Map<String,Account> accts = new Map<String,Account>();
        Map<String, User> usersIdentityMap =new Map<String, User>();
        Map<String,TECH_IntegrationManager__c> intMan = new Map<String,TECH_IntegrationManager__c>();
        //INIT data from c360 event
        try{
            TR_C360_Utils.setSalutationVal();
            TR_C360_Utils.setCountryVal();
            TR_C360_Utils.setTitleVal();
            TR_C360_Utils.setPreLangVal();
            TR_C360_Utils.setDefaultStoreVal();
            TR_C360_Utils.setStoreCodeVal();
            
            accts = getAccountRecords(accIds);
            usersIdentityMap = getUsersIdentityMap(accIds);
            User currentUserRecords = TR_C360_Utils.getCurrentUserInfos();
            if(integManags != null){
                for(TECH_IntegrationManager__c TIM : integManags){
                    List<Account> accs = (List<Account>) getRecordsFromMap(accts,TIM.AccountId__c,TIM.Object_Name__c);
                    List<Social_Media_Identifier__c> smis =(List<Social_Media_Identifier__c>) getRecordsFromMaps(smiRecordMap,TIM.AccountId__c,TIM.Object_Name__c);
                    List<User> usIdentity =(List<User>) getRecordsFromMap(usersIdentityMap,TIM.AccountId__c,'User');
                    String bodyJson = TR_JSON_Generator.generateJSONContent(accs[0],usIdentity,smis,TIM,currentUserRecords);
                    inkEvents.add(new C360_Tech_Event__e(Body_Json__c=bodyJson,TR_Object_Id__c=TIM.Object_Id__c,TR_Object_Name__c=TIM.Object_Name__c,Tech_Integration_Id__c=TIM.Id));
                    intMan.put(TIM.Id, TIM);
                }
                // Call method to publish events
                List<Database.SaveResult> results = EventBus.publish(inkEvents);
                //System.debug('INSERT' + results);
            }
        }catch(Exception e) {
            Map<String, String> logParams = new Map<String, String>{
                'apex_class'=>'TR_C360_IntegrationManager_Utils',
                    'apex_Limits' => TR_C360_IntegrationManager_Utils.getCurrentOrgLimits(),
                    'application'=>TR_Constants.APPEVENT,
                    'duration'=>'',
                    'eventUuidLog'=>'',
                    'json'=> String.valueOf(inkEvents),
                    'logLevel'=>'ERROR',
                    'logMessage'=>'',
                    'hasError'=>'true',
                    'error_Message'=>e.getStackTraceString() + '\n\n' + e.getMessage() + '\n\nlineNumber:' + e.getLineNumber(),
                    'Object_Type'=>'Account',
                    'record_Id'=>'',
                    'logType'=>'Outgoing_flow'};
                        database.insert(TR_C360_Utils.CreateLog(logParams));
        }
    }
    public static void setAccountEventBus(C360_Tech_Event_Return_Flow__e evt ,DateTime startTime){
        List<Account> acctManagsById = new List<Account>();
        List<Account> acctManagsByDREAMID = new List<Account>();
        TR_Integration_Manager_Setting__c getLogSetup =TR_Constants.getLogSetup;
        World_Wide_Technical_User__mdt worldwideTechnicalUser = [select DeveloperName ,country__c, user_id__c from World_Wide_Technical_User__mdt where DeveloperName ='World_Wide_TU'  limit 1 ];
        String wwUserId = worldwideTechnicalUser.user_id__c;                
        List<C360_Logs__c> logs = new List<C360_Logs__c>();
        C360_Logs__c log = new C360_Logs__c();
        List<Database.UpsertResult> results1;
        try{
            List<TR_C360_Field_Mapping__mdt > mappingRds = TR_Constants.mappingRds;
            TR_Integration_Manager_Setting__c getClientSetup =TR_Constants.getClientSetup;
            String automatedprocessid = getClientSetup.Excluded_UserId__c;
            TR_C360_Wrapper cwp = new TR_C360_Wrapper();
            if(evt != null && String.isNotBlank(evt.Body_Json__c)){
                TR_C360_Wrapper obj = TR_C360_Wrapper.parse(evt.Body_Json__c);
                String DreamID = (obj.dreamId!=null?obj.dreamId:null);
                String SalesforceID = (obj.salesforceId!= null?obj.salesforceId:null);
                Map<String, String> logParams = new Map<String, String>{
                    'apex_class'=>'TR_C360_IntegrationManager_Utils',
                        'application'=>'C360',
                        'duration'=>String.valueOf((system.now().getTime() - startTime.getTime()) / 1000),
                        'eventUuidLog'=>evt.EventUuid,
                        'json'=> evt.Body_Json__c,
                        'logLevel'=>'DEBUG',
                        'logMessage'=>'',
                        'hasError'=>'false',
                        'error_Message'=>'',
                        'Object_Type'=>'C360_Tech_Event_Return_Flow__e',
                        'record_Id'=>evt.ReplayId,
                        'logType'=>'Incoming_flow', 
                        'DreamID'=> DreamID,
                        'SalesforceID' => SalesforceID};
                            log = TR_C360_Utils.CreateLog(logParams);
                //TR_C360_Wrapper obj = TR_C360_Wrapper.parse(evt.Body_Json__c);
                Map<String, Object> mObjct = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(obj));
                 
                String stAcc = '{';
                for(TR_C360_Field_Mapping__mdt st :mappingRds){
                    if(mObjct.containskey(st.C360_Field__c) && st.Is_From_C360__c){
                        system.debug('### YAAAA  YAAA ' + st.C360_Field__c );
                        if (st.C360_Field__c == 'nationality_code') System.debug(' ## YAA ' + mObjct.get(st.C360_Field__c));
                        if(st.C360_Field__c != 'salesforceId'){
                            
                            if (mObjct.get(st.C360_Field__c) != null ){
                                 stAcc += '"'+st.SF_Field__c+'"'+':'+'"'+mObjct.get(st.C360_Field__c)+'"'+',';
                            }else {if (st.C360_Field__c != 'birthDate'){
                                stAcc += '"'+st.SF_Field__c+'"'+':'+'""'+',';
                            }
                                 
                            }
                        }else if(st.C360_Field__c == 'salesforceId'  && String.IsNotBlank(String.valueOf(mObjct.get(st.C360_Field__c)))){
                            stAcc += '"'+st.SF_Field__c+'"'+':'+'"'+mObjct.get(st.C360_Field__c)+'"'+',';   
                                                        
                        }
                    }
                }
                stAcc = stAcc.removeEnd(',')+'}';
                Account acc = (Account)JSON.deserialize(stAcc, Account.class); 
                if(String.isNotBlank(acc.SPO_Country_code__pc) && String.isBlank(acc.PrimaryCountry__pc)){
                    acc.PrimaryCountry__pc =  TR_C360_Utils.getCountry(acc.SPO_Country_code__pc);
                }
                // Update account according Dream Id                             
                                      
                if(acc.DREAMID__c != null && String.isNotBlank(acc.DREAMID__c) && String.isBlank(acc.Id)){
                    List<Account> accountOwners = [SELECT Id , ownerId from Account where DreamId__c =: acc.DREAMID__c LIMIT 1];
                    String accountOwner;
                    if(accountOwners.size()> 0){
                        accountOwner= accountOwners[0].ownerId;
                    }
                    if(wwUserId != null && (String.IsBlank(accountOwner) || accountOwner ==automatedprocessid)){
                        acc.OwnerId =  wwUserId; 
                    }
                    acc.RecordTypeId =(getClientSetup.Client_default_RecordType__c != null ? getClientSetup.Client_default_RecordType__c : TR_Constants.recordTypeClient);
                    acctManagsByDREAMID.add(acc); 
                }
                else {
                    String accountId = acc.Id;
                    // Update account according Salesforce Id
                    if(String.isNotBlank(accountId) && accountId !='null'){
                        acc.Id = accountId;
                    }
                    // Create Client
                    else {
                        // integrer ici le owner
                        if(wwUserId != null){   
                            acc.OwnerId =  wwUserId; 
                        }
                        acc.RecordTypeId =(getClientSetup.Client_default_RecordType__c != null ? getClientSetup.Client_default_RecordType__c : TR_Constants.recordTypeClient);
                        acc.Source__c = String.valueOf(mObjct.get('touchApplicationCode'));
                    }
                    acctManagsById.add(acc);
                }
            }
            if(logs.Size()>0){
                Database.insert(logs);
            }
            if(acctManagsById.Size()> 0){
                results1 = Database.upsert(acctManagsById);
            }
            if(acctManagsByDREAMID.Size()> 0){
                results1 = Database.upsert(acctManagsByDREAMID, Account.Fields.DREAMID__c);
            }
        }catch(Exception ex) {
            string errorStr = ex.getStackTraceString() + '\n\n' + ex.getMessage() + '\n\nlineNumber:' + ex.getLineNumber();
            log.TR_Has_Error__c = true;
            log.TR_Error__c = errorStr;
            log.TR_Level__c = 'ERROR';
        }
        if  (log.TR_Level__c != 'ERROR' && (getLogSetup != null && !getLogSetup.Json_Added__c)){
            log.TR_JSON__c = null;
        }
        
        log.TR_APEX_Limits__c = TR_C360_IntegrationManager_Utils.getCurrentOrgLimits();
        database.insert(log);
    }
    public static  Map<String, account> getAccountRecords(Set<Id> accountIds){
        List<Account> accountRecords = new List<Account>();
        Map<String, Account> acctRecordMap = new Map<String,Account>();
        smiRecordMap = new Map<String,List<Social_Media_Identifier__c>>();
        contRecordMap = new Map<String, Contact>();
        if(accountIds.size()>0){
            String query = 'SELECT ' + TR_Constants.getClientFields() + '(select '+ TR_Constants.getSocialFields() +' from Social_Media_Identifiers__r),(SELECT Name , tolabel(Title__c) from Contacts) from Account where Id IN : accountIds';
            accountRecords =  Database.query(query);
            If(accountRecords.size()>0){
                for(Account acct : accountRecords){
                    acctRecordMap.put(acct.Id, acct);
                    contRecordMap.put(acct.Id,acct.Contacts[0]);
                    if(acct.Social_Media_Identifiers__r!=null && !acct.Social_Media_Identifiers__r.isEmpty()){
                        smiRecordMap.put(acct.Id,acct.Social_Media_Identifiers__r);  
                    }  
                }
                if(acctRecordMap != null){
                    return acctRecordMap;
                }
            }
        }
        return Null;
    }
    public static List<TECH_IntegrationManager__c> getTechManagerRecords(Set<Id> techManagerIds){
        List<TECH_IntegrationManager__c> integManags = new List<TECH_IntegrationManager__c>();
        if(techManagerIds.size()>0){
            integManags = [SELECT Id, Object_Name__c, Object_Id__c,Operation__c,Trigger_Event__c,AccountId__c,CreatedDate from TECH_IntegrationManager__c where Id IN : techManagerIds];
        }
        If(integManags.size()>0){
            return integManags;
        }
        return Null;
    }
    public static Map<String,User> getUsersIdentityMap(Set<Id> accountIds){
        List<User> idenUsers = new List<User>();
        Map<String, User> usersIdentityMap = new Map<String,User>();
        if(accountIds.size()>0){
            idenUsers = [SELECT Id,UserName,TimeZoneSidKey,Name,AccountId,Email,CreatedDate,LastLoginDate  FROM User where AccountId IN : accountIds];
        }
        If(idenUsers.size()>0){
            for(User us : idenUsers){
                usersIdentityMap.put(us.accountId, us);
            }
            if(usersIdentityMap != null){
                return usersIdentityMap;
            }
        }
        return new Map<String,User>();
    }
    public static List<sObject> getRecordsFromMap(Map<String,sObject> sObj, String accId,String objName){
        List<sObject> records = new List<sObject>();
        if(!sObj.isEmpty()){
            records.add(sObj.get(accId));  
        }
        return records;
    }
    public static List<Sobject> getRecordsFromMaps(Map<String,List<sObject>> sObj, String accId,String objName){
        List<sObject> records = new List<sObject>();   
        if(!sObj.isEmpty()){
            records= sObj.get(accId);  
        }
        return records;
    }
    public static string getCurrentOrgLimits(){
        string limits = '****CURRENT LIMITS****\n' +
            'Maximum CPU time: ' + Limits.getCpuTime()+ ' out of ' + Limits.getLimitCpuTime() + '\n' +
            'Number of future calls: : ' + Limits.getFutureCalls()+ ' out of ' + Limits.getLimitFutureCalls() + '\n' +
            'Aggregate queries : ' + Limits.getAggregateQueries() + ' out of ' + Limits.getLimitAggregateQueries()+ '\n' +
            'Number of DML rows:  ' + Limits.getDMLRows() + ' out of ' + Limits.getLimitDMLRows()+ '\n' +
            'Number of DML statements ' + Limits.getDMLStatements() + ' out of ' + Limits.getLimitDMLStatements() + '\n' +
            'Number of SOQL queries: ' + Limits.getQueries() + ' out of ' + Limits.getLimitQueries() + '\n' +
            'Number of query rows: ' + Limits.getQueryRows() + ' out of ' + Limits.getLimitQueryRows() + '\n' +
            'Number of SOSL queries: ' + Limits.getSoslQueries() + ' out of ' + Limits.getLimitSoslQueries() + '\n' +
            'Maximum heap size: ' + Limits.getHeapSize() + ' out of ' + Limits.getLimitHeapSize() + '\n' +
            'Maximum Async Calls: ' + Limits.getAsyncCalls() + ' out of ' + Limits.getLimitAsyncCalls() + '\n' +
            'Maximum Publish DML(EventBus): ' + Limits.getPublishImmediateDML() + ' out of ' + Limits.getLimitPublishImmediateDML() + '\n' +
            'Number of Mobile Apex push calls:  ' + Limits.getMobilePushApexCalls() + ' out of ' + Limits.getLimitMobilePushApexCalls() + '\n';        
        return limits;
    }
    
}