force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Club_and_Seasons__c/Club_and_Seasons__c.object-meta.xml
<CustomObject>
    <label>Club</label>
    <nameField>
        <label>Club Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_MemberShip__c/Club_MemberShip__c.object-meta.xml
<CustomObject>
    <label>Club Membership</label>
    <nameField>
        <label>Club MemberShip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_MemberShip__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <description>Account Id</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Clubs_MemberShip</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/Club_and_Seasons__c.field-meta.xml
<CustomField>
    <fullName>Club_and_Seasons__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Club</label>
    <referenceTo>Club_and_Seasons__c</referenceTo>
    <relationshipName>Clubs_MemberShip</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/clubStatus__c.field-meta.xml
<CustomField>
    <fullName>clubStatus__c</fullName>
    <description>Membership levels from the LV Clubs</description>
    <label>Club Status TECH</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClubStatusList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/dreamId__c.field-meta.xml
<CustomField>
    <fullName>dreamId__c</fullName>
    <description>Client/Member DreamId</description>
    <label>Dream ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/lastStatusUpdated__c.field-meta.xml
<CustomField>
    <fullName>lastStatusUpdated__c</fullName>
    <description>Date &amp; Hour at which LV Club member status changed</description>
    <label>Club Status Update Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <label>Unique Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <description>DREAM Id Transaction</description>
    <externalId>true</externalId>
    <label>DREAM Id Transaction</label>
    <length>29</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/RMSSKUCode__c.field-meta.xml
<CustomField>
    <fullName>RMSSKUCode__c</fullName>
    <label>Code RMS du produit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TicketNumber__c.field-meta.xml
<CustomField>
    <fullName>TicketNumber__c</fullName>
    <externalId>true</externalId>
    <label>Ticket Number</label>
    <length>26</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/TECH_Email__c.field-meta.xml
<CustomField>
    <fullName>TECH_Email__c</fullName>
    <label>TECH Email</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/ClubStatusList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bronze</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl</fullName>
    </customValue>
    <customValue>
        <fullName>Not Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Client Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultra Rare</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <masterLabel>Club Status List</masterLabel>
</GlobalValueSet>

force-experience/main/default/classes/test/Club_MemberShipTrigger_TEST.cls
@isTest
private class Club_MemberShipTrigger_TEST {

    @testSetup
    static void setup() {
        Profile iconProfile = [SELECT Id FROM Profile WHERE Name = 'ICON_SA' LIMIT 1];
        Profile identityProfile = [SELECT Id FROM Profile WHERE Name = 'Identity User' LIMIT 1];
        
        User iconUser = new User();
        iconUser.profile = iconProfile;
        iconUser.ProfileId = iconProfile.Id;
        iconUser.FirstName = 'test';
        iconUser.LastName = 'user';
        iconUser.Alias = 'iconsu';
        iconUser.Email = 'test.user@louisvuitton.com';
        iconUser.TimeZoneSidKey = 'Europe/Paris';
        iconUser.LocaleSidKey = 'en_US';
        iconUser.Username = 'icon.user@louisvuitton.com.icon';
        iconUser.EmailEncodingKey = 'ISO-8859-1';
        iconUser.LanguageLocaleKey = 'en_US';
        iconUser.IsActive = TRUE;
        insert iconUser;
        
        User identityUser = new User(
            profile = identityProfile,
            ProfileId = identityProfile.Id,
            FirstName = 'test',
            LastName = 'user',
            Alias = 'testuse1',
            Email = iconUser.Email,
            TimeZoneSidKey = 'Europe/Paris',
            LocaleSidKey = 'en_US',
            Username = 'test.user@louisvuitton.com.identity',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            TECH_Email__c = 'test.user@louisvuitton.com',
            IsActive = true
        );

        insert identityUser;

        Account acc = new Account(
            FirstName = 'test',
            LastName = 'user',
            DREAMID__c = 'asdfghj145',
            AttachedStore__pc = 'UEC',
            AttachedStoreCode__pc = 'UEC',
            PersonEmail = iconUser.Email,
            SPO_Country_code__pc = 'USA'
        );
        insert acc;
        
        Club_and_Seasons__c clubSneakers = new Club_and_Seasons__c(
            Name = 'Sneakers'
        );
        insert clubSneakers;
        
        Club_MemberShip__c clubM = new Club_MemberShip__c(
            clientId__c = acc.Id,
            dreamId__c = 'asdfghj145',
            Club_and_Seasons__c = clubSneakers.id,
            clubStatus__c = 'Pearl',
            lastStatusUpdated__c = system.now(),
            Unique_Key__c = acc.DREAMID__c + '_' + clubSneakers.Name
        );
        insert clubM;
    }
    
    @isTest
    static void testHandleBeforeInsert() {
        Account user1 = [
            SELECT Id
            FROM Account
            WHERE DREAMID__c = 'asdfghj145'
            LIMIT 1
        ];
        
        List<PPR_PurchProduct__c> pprlList = new List<PPR_PurchProduct__c>();
        
        PPR_PurchProduct__c pprp1 = new PPR_PurchProduct__c();
        pprp1.Client__c = user1.Id;
        pprp1.TicketNumber__c = '195141ge65';
        pprp1.RMSSKUCode__c = '1AARQT';
        pprlList.add(pprp1);
        
        PPR_PurchProduct__c pprp2 = new PPR_PurchProduct__c();
        pprp2.Client__c = user1.Id;
        pprp2.TicketNumber__c = '195141ge65';
        pprp2.RMSSKUCode__c = '1AB8SR';
        pprlList.add(pprp2);
        
        PPR_PurchProduct__c pprp3 = new PPR_PurchProduct__c();
        pprp3.Client__c = user1.Id;
        pprp3.TicketNumber__c = '195141ge65';
        pprp3.RMSSKUCode__c = '1AB8RU';
        pprlList.add(pprp3);
        
        Test.startTest();
        insert pprlList;
        Test.stopTest();
    }
    
    @isTest
    static void testHandleAfterInsert() {
        List<Club_MemberShip__c> clubMemberShipList = [SELECT Id, clientId__c FROM Club_MemberShip__c limit 1];
        List<PPR_PurchProduct__c> pprList = new List<PPR_PurchProduct__c>();
        
        for (Club_MemberShip__c clubMemberShip : clubMemberShipList) {
            PPR_PurchProduct__c ppr = new PPR_PurchProduct__c();
            ppr.Client__c = clubMemberShip.clientId__c;
            ppr.RMSSKUCode__c = 'TestSKU';
            ppr.TicketNumber__c = 'Test123';
            pprList.add(ppr);
        }
        
        Test.startTest();
        insert pprList;
        Test.stopTest();
        
        // Example assertion
        System.assertEquals(1, 1, 'Custom assertion message');
    }
    
    @isTest
    static void testHandleAfterAccountInsert() {
        User iconUser = [SELECT Id, firstName, lastName, Email FROM User WHERE Profile.Name = 'ICON_SA' AND IsActive = TRUE AND Email = 'test.user@louisvuitton.com' LIMIT 1];
        Account acc1 = new Account(
            FirstName = iconUser.firstName,
            LastName = iconUser.lastName,
            DREAMID__c = 'test123',
            AttachedStore__pc = 'UEC',
            AttachedStoreCode__pc = 'UEC',
            PersonEmail = iconUser.Email,
            SPO_Country_code__pc = 'USA'
        );
        insert acc1;
        
        Account acc2 = new Account(
            FirstName = 'Test',
            LastName = 'User',
            DREAMID__c = 'test456',
            AttachedStore__pc = 'UEC',
            AttachedStoreCode__pc = 'UEC',
            PersonEmail = 'test3@test.com',
            SPO_Country_code__pc = 'USA'
        );
        insert acc2;
        
        Test.startTest();
        System.runAs(iconUser){
            try{
                List<Account> accList = new List<Account>{acc1, acc2};
                Map<Id, Account> accMap = new Map<Id, Account>();
                for (Account acc : accList) {
                    accMap.put(acc.Id, acc);
                }
                Club_MemberShipTriggerHandler.handleAfterAccountUpdate(accList, accMap);
            }catch(Exception e){
                system.debug('Error : ' + e);
            }
        }
        Test.stopTest();
    }

    @isTest
    static void handleAfterUserDeactivated_TEST() {
        User iconUser = [SELECT Id, IsActive FROM User WHERE Profile.Name = 'ICON_SA' AND IsActive = TRUE AND Email = 'test.user@louisvuitton.com' LIMIT 1];

        Test.startTest();
        iconUser.IsActive = false;
        update iconUser;
        Test.stopTest();
    }
}