force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Club_and_Seasons__c/Club_and_Seasons__c.object-meta.xml
<CustomObject>
    <label>Club</label>
    <nameField>
        <label>Club Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clubs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_MemberShip__c/Club_MemberShip__c.object-meta.xml
<CustomObject>
    <label>Club Membership</label>
    <nameField>
        <label>Club MemberShip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Club_MemberShip__c/fields/clientId__c.field-meta.xml
<CustomField>
    <fullName>clientId__c</fullName>
    <description>Account Id</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Clubs_MemberShip</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/Club_and_Seasons__c.field-meta.xml
<CustomField>
    <fullName>Club_and_Seasons__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Club</label>
    <referenceTo>Club_and_Seasons__c</referenceTo>
    <relationshipName>Clubs_MemberShip</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/clubStatus__c.field-meta.xml
<CustomField>
    <fullName>clubStatus__c</fullName>
    <description>Membership levels from the LV Clubs</description>
    <label>Club Status TECH</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClubStatusList</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/dreamId__c.field-meta.xml
<CustomField>
    <fullName>dreamId__c</fullName>
    <description>Client/Member DreamId</description>
    <label>Dream ID</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/lastStatusUpdated__c.field-meta.xml
<CustomField>
    <fullName>lastStatusUpdated__c</fullName>
    <description>Date &amp; Hour at which LV Club member status changed</description>
    <label>Club Status Update Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/Unique_Key__c.field-meta.xml
<CustomField>
    <fullName>Unique_Key__c</fullName>
    <label>Unique Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <description>ICX Client Data Cleaning Campaign</description>
    <label>Family</label>
    <nameField>
        <displayFormat>FAM-{00000000}</displayFormat>
        <label>Family Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LV_Club_Setting__mdt/LV_Club_Setting__mdt.object-meta.xml
<CustomObject>
    <label>LV Club Setting</label>
    <pluralLabel>LV Club Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/LV_Club_Setting__mdt/fields/clubNameFilter__c.field-meta.xml
<CustomField>
    <fullName>clubNameFilter__c</fullName>
    <label>clubNameFilter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LV_Club_Setting__mdt/fields/skusProductCatalogueFiltered__c.field-meta.xml
<CustomField>
    <fullName>skusProductCatalogueFiltered__c</fullName>
    <label>skusProductCatalogueFiltered</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LV_Club_Setting__mdt/fields/skusProductReferentialsFiltered__c.field-meta.xml
<CustomField>
    <fullName>skusProductReferentialsFiltered__c</fullName>
    <label>skusProductReferentialsFiltered</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LV_Club_Setting__mdt/fields/statusClubFilteredList__c.field-meta.xml
<CustomField>
    <fullName>statusClubFilteredList__c</fullName>
    <label>statusClubFilteredList</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <description>DREAM Id Transaction</description>
    <externalId>true</externalId>
    <label>DREAM Id Transaction</label>
    <length>29</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/RMSSKUCode__c.field-meta.xml
<CustomField>
    <fullName>RMSSKUCode__c</fullName>
    <label>Code RMS du produit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TicketNumber__c.field-meta.xml
<CustomField>
    <fullName>TicketNumber__c</fullName>
    <externalId>true</externalId>
    <label>Ticket Number</label>
    <length>26</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCatalogue__c/fields/longSkuId__c.field-meta.xml
<CustomField>
    <fullName>longSkuId__c</fullName>
    <externalId>true</externalId>
    <label>longSkuId</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/ProductReferential__c.field-meta.xml
<CustomField>
    <fullName>ProductReferential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to ProductReferential. Lookup needed to get some information provided by ProductReferential object (SAP) and not in BCC (ETL / sku.json)</description>
    <label>Product Referential</label>
    <referenceTo>ProductReferential__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <description>SKU code</description>
    <externalId>true</externalId>
    <label>SKU</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/Workshop__c.field-meta.xml
<CustomField>
    <fullName>Workshop__c</fullName>
    <defaultValue>(&quot;0000&quot;)</defaultValue>
    <description>Manufacturing workshop code
(used for JDE system to know in which workshop the product should be sent)
For Perso app, value is set to 11202 (in product creation) but can be changed
Default value changed to 0000 on MIY-2062</description>
    <label>Workshop</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Workshop</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductReferential__c/ProductReferential__c.object-meta.xml
<CustomObject>
    <description>All information about base product</description>
    <label>Product Referential</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Referential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductReferential__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductReferential__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductReferential__c/fields/SKUCode__c.field-meta.xml
<CustomField>
    <fullName>SKUCode__c</fullName>
    <externalId>true</externalId>
    <label>Base SKU Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/ClubStatusList.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bronze</fullName>
    </customValue>
    <customValue>
        <fullName>Pearl</fullName>
    </customValue>
    <customValue>
        <fullName>Not Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Client Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Ultra Rare</fullName>
    </customValue>
    <customValue>
        <fullName>Influencer</fullName>
    </customValue>
    <masterLabel>Club Status List</masterLabel>
</GlobalValueSet>

force-experience/main/default/classes/test/PPR_PurchProductTrigger_TEST.cls
@isTest
private class PPR_PurchProductTrigger_TEST {
  @testSetup
  static void setup() {
    Account acc = new Account(
      FirstName = 'Calev',
      LastName = 'Machiah',
      DREAMID__c = 'asdfghj145',
      AttachedStore__pc = 'UEC',
      AttachedStoreCode__pc = 'UEC',
      PersonEmail = 'test@test.com',
      SPO_Country_code__pc = 'USA'
    );
    insert acc;

    Club_and_Seasons__c clubSneakers = new Club_and_Seasons__c(
      Name = 'Sneakers'
    );
    insert clubSneakers;

    Club_MemberShip__c clubM = new Club_MemberShip__c(
      clientId__c = acc.Id,
      dreamId__c = 'asdfghj145',
      Club_and_Seasons__c = clubSneakers.id,
      clubStatus__c = 'Pearl',
      lastStatusUpdated__c = system.now(),
      Unique_Key__c = acc.DREAMID__c + '_' + clubSneakers.Name
    );
    insert clubM;

    /*LV_Club_Setting__mdt setting = new LV_Club_Setting__mdt();
    setting.label
    setting.DeveloperName = 'Sneakers';
    setting.skusProductCatalogueFiltered__c = 'BOQU2PMI%,BPQU1PSC%,BPQU1PTX%,BPQU1PMI%,BL9U1PSR%,BH9U1PSR%,BJ9U1PSR%,BM9U1PSR%,BN9U1PSR%,BJ9U4PSR%,BM9U3PSR%,BM9U2PSR%,BJ9U3PSR%';
    setting.skusProductReferentialsFiltered__c = '%LV TRAINER%,%LV SKATE%,%NIKE%';
    setting.statusClubFilteredList__c = 'Client Advisor,Influencer,Not Eligible	';
    setting.clubNameFilter__c = 'Sneakers';
    insert setting;*/
  }

  @isTest
  static void testHandleAfterInsert() {
    Account user1 = [
      SELECT Id
      FROM Account
      WHERE DREAMID__c = 'asdfghj145'
      LIMIT 1
    ];

    List<PPR_PurchProduct__c> pprlList = new List<PPR_PurchProduct__c>();

    PPR_PurchProduct__c pprp1 = new PPR_PurchProduct__c();
    pprp1.Client__c = user1.Id;
    pprp1.TicketNumber__c = '195141ge65';
    pprp1.RMSSKUCode__c = '1AARQT';
    pprp1.quantity__c = 1;
    pprlList.add(pprp1);

    PPR_PurchProduct__c pprp2 = new PPR_PurchProduct__c();
    pprp2.Client__c = user1.Id;
    pprp2.TicketNumber__c = '195141ge65';
    pprp2.RMSSKUCode__c = '1AB8SR';
    pprp2.quantity__c = 1;
    pprlList.add(pprp2);

    PPR_PurchProduct__c pprp3 = new PPR_PurchProduct__c();
    pprp3.Client__c = user1.Id;
    pprp3.TicketNumber__c = '195141ge65';
    pprp3.RMSSKUCode__c = '1AB8RU';
    pprp3.quantity__c = -1;
    pprlList.add(pprp3);

    Test.startTest();
    insert pprlList;
    Test.stopTest();
  }

  @isTest 
  static void scheduleTest() {
    Account user1 = [
      SELECT Id
      FROM Account
      WHERE DREAMID__c = 'asdfghj145'
      LIMIT 1
    ];

    Test.startTest();
		ProductReferential__c pr1 = new ProductReferential__c(Name = 'LV TRAINER', SKUCode__c = '1ABM2L', Activity__c = 'SHOES', Family__c = 'SNEAKER');
		insert pr1;

    ProductCatalogue__c product1 = new ProductCatalogue__c(SKU__c='TST123', longSkuId__c = 'BN9U1PSR', Workshop__c = '1798');
    insert product1;

    List<PPR_PurchProduct__c> pprlList = new List<PPR_PurchProduct__c>();

    PPR_PurchProduct__c pprp1 = new PPR_PurchProduct__c();
    pprp1.Client__c = user1.Id;
    pprp1.TicketNumber__c = '195141ge65';
    pprp1.RMSSKUCode__c = '1ABM2L';
    pprp1.quantity__c = 1;
    pprlList.add(pprp1);

    PPR_PurchProduct__c pprp2 = new PPR_PurchProduct__c();
    pprp2.Client__c = user1.Id;
    pprp2.TicketNumber__c = '195141ge65';
    pprp2.RMSSKUCode__c = 'TST123';
    pprp2.quantity__c = 1;
    pprlList.add(pprp2);

    PPR_PurchProduct__c pprp3 = new PPR_PurchProduct__c();
    pprp3.Client__c = user1.Id;
    pprp3.TicketNumber__c = '195141ge65';
    pprp3.RMSSKUCode__c = 'TST123';
    pprp3.quantity__c = -1;
    pprlList.add(pprp3);

    insert pprlList;

    String cron = '0 0 23 * * ?';
    BatchCWForClubMembersScheduler schd = new BatchCWForClubMembersScheduler();
    String jobId = System.schedule('test BatchCWForClubMembersScheduler', cron, schd);

    BatchCollectionWallForClubMembers cwMembers = new BatchCollectionWallForClubMembers(false, 1);
    Database.executeBatch(cwMembers);  
    Test.stopTest();
  }
}