force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IC_Config__c/IC_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>IC Config</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/AnniversaryScheduledDays__c.field-meta.xml
<CustomField>
    <fullName>AnniversaryScheduledDays__c</fullName>
    <description>Anniversary Scheduled Days</description>
    <label>Anniversary Scheduled Days</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IC_BatchAnniversaryReminder_TEST.cls
@isTest
private class IC_BatchAnniversaryReminder_TEST {

  @TestSetup
    public static void setup() {
        String identityProfile = [SELECT Id FROM Profile WHERE Name = 'Identity User'][0].Id;
        insert new IC_Config__c(
            Name = 'Identity User',
            Value__c = identityProfile
        );
    }

	    static testMethod void testBatch() {
		//public void  testBatch() {
	
        ID batchprocessid;
        
        Integer thisDay;
        Integer thisMonth;
    	Integer year;
    	String nextMonth;
    	
    	
    	thisDay = Date.today().day();
    	thisMonth = Date.today().month();
   		year =Date.today().year();
   		if(thisMonth==12){thismonth = 1; year = year+1;}
   		else {thismonth = thisMonth + 1;}
		nextMonth=String.valueOf(thisMonth);
		
		ICONSettings__c stt = new ICONSettings__c();
      	stt.AnniversaryScheduledDays__c = String.valueOf(thisDay) + ', 13';
      	insert stt;
      	
        
        User usr = IC_TestFactory.createUser('TestLVBacthCLCreation@lvtest.com');
		usr.profileId = IC_UTILS.getSAProfile();
		usr.DREAMID__C='123456';    
        insert usr;
               
        Account acc = IC_TestFactory.createAccount();
		acc.TECH_DreamIdSA__pc = '123456';
		acc.AnniversaryMonth__pc = nextMonth;
		acc.AnniversaryDay__pc = '3';
        insert acc;		
       
        Test.startTest();
        IC_BatchAnniversaryReminder myBatch = new IC_BatchAnniversaryReminder();
        batchprocessid = Database.executeBatch(myBatch,1000);
        Test.stopTest();


		List<Task> lst = [SELECT OwnerId,status,Subject,priority,ActivityDate FROM TASK WHERE WhatId = :acc.Id and Subject = :System.Label.IC_Anniversary_Reminder];
		Date actDate;
		Integer month=Integer.valueOf(acc.AnniversaryMonth__pc);
		Integer day=Integer.valueOf(acc.AnniversaryDay__pc);
		actDate = date.newInstance(year,month,day);	
		
		//System.assert(lst.size()>0);	
		//System.assertequals(lst[0].OwnerId,usr.Id);
		//System.assertequals(lst[0].status,'New');
		//System.assertequals(lst[0].priority,'Normal');
		//System.assertequals(lst[0].ActivityDate, actDate);
    }

}