force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IC_Config__c/IC_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>IC Config</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/batchBirthdayReminderScope__c.field-meta.xml
<CustomField>
    <fullName>batchBirthdayReminderScope__c</fullName>
    <label>Batch Birthday Reminder Scope</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/fields/BirthdateScheduledDays__c.field-meta.xml
<CustomField>
    <fullName>BirthdateScheduledDays__c</fullName>
    <description>Birthdate Scheduled Days</description>
    <label>Birthdate Scheduled Days</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IC_SchedulerBirthdayReminder_TEST.cls
@isTest
private class IC_SchedulerBirthdayReminder_TEST {

    @TestSetup
    public static void setup() {
        String identityProfile = [SELECT Id FROM Profile WHERE Name = 'Identity User'][0].Id;
        insert new IC_Config__c(
            Name = 'Identity User',
            Value__c = identityProfile
        );
    }

        static testMethod void testBatch() {
        
        String nextMonth;
        
        Integer thisDay = Date.today().day();
        Integer thisMonth = Date.today().month();
        Integer year =Date.today().year();
        if(thisMonth==12){thismonth = 1; year = year+1;}
        else {thismonth = thisMonth + 1;}
        nextMonth=String.valueOf(thisMonth);
        
        ICONSettings__c stt = new ICONSettings__c();
      	stt.BirthdateScheduledDays__c = String.valueOf(thisDay) + ', 13';
      	stt.batchBirthdayReminderScope__c=500;
      	insert stt;
        
        User usr = IC_TestFactory.createUser('TestLVBacthCLCreation@lvtest.com');
        usr.profileId = IC_UTILS.getSAProfile();
        usr.DREAMID__C='123456';    
        insert usr;
         
        Account acc = IC_TestFactory.createAccount();
        acc.TECH_DreamIdSA__pc = '123456';
        acc.BirthdateMonth__pc =nextMonth;
        acc.BirthdateDay__pc = '11';
        insert acc;                 
           
        IC_SchedulerBirthdayReminder myScheduler = new IC_SchedulerBirthdayReminder();
        
        Test.startTest();
        String sch = '0 0 23 L * ?';
        system.schedule('Test check', sch, myScheduler);
        Test.stopTest();
    }

}