force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/ExcepPurchaseUSD__c.field-meta.xml
<CustomField>
    <fullName>ExcepPurchaseUSD__c</fullName>
    <defaultValue>3500</defaultValue>
    <label>Exceptional Purchase Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/fields/Exceptional_Purchase_Currency__c.field-meta.xml
<CustomField>
    <fullName>Exceptional_Purchase_Currency__c</fullName>
    <defaultValue>&quot;EUR&quot;</defaultValue>
    <label>Exceptional Purchase Currency</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/TECH_User_Stores__c.field-meta.xml
<CustomField>
    <fullName>TECH_User_Stores__c</fullName>
    <description>Holds comma separated list of Store codes</description>
    <label>User Stores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/User_Stores__c.field-meta.xml
<CustomField>
    <fullName>User_Stores__c</fullName>
    <description>Holds comma separated list of user stores</description>
    <label>User Stores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Config__c/VO_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>VO_Config</label>
</CustomObject>

force-app/main/default/objects/VO_Survey__c/VO_Survey__c.object-meta.xml
<CustomObject>
    <label>Voice</label>
    <nameField>
        <displayFormat>Survey-{00000000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VO_Survey__c/fields/AnswerDate__c.field-meta.xml
<CustomField>
    <fullName>AnswerDate__c</fullName>
    <description>Default value equal to today (old voice)</description>
    <label>Answer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/DreamID__c.field-meta.xml
<CustomField>
    <fullName>DreamID__c</fullName>
    <formula>ClientDreamID__r.DREAMID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DreamID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/DreamIDText__c.field-meta.xml
<CustomField>
    <fullName>DreamIDText__c</fullName>
    <description>Denormalized data from Account --&gt; sent by Clicktools</description>
    <label>Dream ID Text</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Scoring__c.field-meta.xml
<CustomField>
    <fullName>Scoring__c</fullName>
    <label>Scoring</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Default value equal to New. Changed to closed if new or pending 2 months after answer date. Changed to No action if the channel equals to No action (old voice)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>live</fullName>
            </value>
            <value>
                <fullName>soft_deleted</fullName>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>No action</fullName>
                <default>true</default>
                <label>No action</label>
            </value>
            <value>
                <fullName>noShow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>populated with VO_Survey apex class before insert from StoreID__c field</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/StoreID__c.field-meta.xml
<CustomField>
    <fullName>StoreID__c</fullName>
    <description>Denormalized data from Store --&gt; sent by Clicktools</description>
    <label>Store ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VO_Email_StoreManager_Test.cls
/**
BW - 10/11/2015
*/
@isTest
public with sharing class VO_Email_StoreManager_Test {
    
    //private final static String PS_AFTERSALES_NAME = VO_Utils.VOICE_AFTER_SALES;
    private final static String PS_AFTERSALES_NAME = 'VOICE Store After Sales';
    //private final static String PS_SALES_NAME = VO_Utils.VOICE_SALES;
    private final static String PS_SALES_NAME = 'VOICE Store Local Sales';
    
    @testSetup
    public static void setup1 (){
        User u = IC_TestFactory.createUser('john@acme.com');
        u.ProfileId = IC_UTILS.getSAProfile();
        insert u;
        
        PermissionSet ps;
        ps = [Select Id from PermissionSet Where label =: PS_AFTERSALES_NAME LIMIT 1];
        if (ps == NULL){
            ps = new PermissionSet(Name = 'Test1', label = PS_AFTERSALES_NAME);
            System.debug(ps);
            insert ps;
        }
        
        PermissionSetAssignment per = new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
        System.debug(per);
        
        ps = [Select Id from PermissionSet Where label =: PS_SALES_NAME LIMIT 1];
        if (ps == NULL){
            ps = new PermissionSet(Name = 'Test1', label = PS_SALES_NAME);
            System.debug(ps);
            insert ps;
        }
        
        PermissionSetAssignment per2 = new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id);
        insert new List<PermissionSetAssignment> {per2,per};
        System.debug(per2);
    }
    
    @testSetup
    public static void setup (){		
        Test.loadData(VO_Config__c.sobjectType, 'VO_Config_TestCLS');
        
        User usr = IC_TestFactory.createUser('dreamuserLV161548@lvtest.com');
        usr.profileId = IC_UTILS.getSysAdminProfile();
        usr.email = 'xxx@noemail.com';
        usr.DefaultStore__c = 'P3';
        //usr.UserRoleId = role.Id;
        usr.DREAMId__c = '123456';
        usr.isactive = true;
        insert usr;
        
        VO_Config__c cs = new VO_Config__c(Name = 'NUM OF Q', Value__c = '50');
        insert cs;
        
        Account acc = IC_TestFactory.createAccount();
        acc.DREAMID__c = '14712';
        insert acc;
        
        Store__c st = new Store__c(Name='STLesChamps', RetailStoreId__c = 'P3');
        insert st;
        
        ICONSettings__c iconSet = new ICONSettings__c();
        iconSet.ExcepPurchaseUSD__c=70;
        iconSet.Exceptional_Purchase_Currency__c='USD';	
        insert iconSet;
        
        VO_Survey__c srv = new VO_Survey__c(Status__c='New', Scoring__c='Recovery act', StoreID__c='P3', Store__c = st.Id ,DreamIDText__c = '14712', AnswerDate__c = Date.today());
        VO_Survey__c srv2 = new VO_Survey__c(Status__c='New', Scoring__c='Delighted', StoreID__c='P3', Store__c = st.Id ,DreamIDText__c = '14712', AnswerDate__c = Date.today());
        insert new List<VO_Survey__c> {srv2,srv};
        //		Group gr = new Group(Name='VoiceStoreManager', DeveloperName = 'VoiceStoreManager');
        //		insert gr;
        //		GroupMember gm = new GroupMember(GroupId = gr.Id, UserOrGroupId=usr.Id );
        //		insert gm;
        VO_Config__c cfg = new VO_Config__c(Name='EmailAlertUserGroup', Value__c='VoiceStoreManager');
        VO_Config__c cfg2 = new VO_Config__c(Name='server', Value__c='c.cs1');
		insert new List<VO_Config__c> {cfg,cfg2};        
        
        
    }
    
    static testMethod void myUnitTest() {
        User u = [SELECT id, DefaultStore__c, TECH_User_Stores__c, User_Stores__c FROM User LIMIT 1];
        
        VO_Email_StoreManager_CTRL cont = new VO_Email_StoreManager_CTRL();
        cont.storeCode = 'P3';
        cont.isAfterSalesUser = false;
        cont.isSalesUser = false;
        cont.userId = u.id;
        cont.getStoreName();
        cont.getNbRecoveryActs();
        cont.getNbDelighteds();
        cont.getNbPromoters();
    }
}