force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Exclusive_Experience__c/Exclusive_Experience__c.object-meta.xml
<CustomObject>
    <description>Contains targeted client lists for special sales</description>
    <label>Exclusive Experience</label>
    <nameField>
        <displayFormat>XXPR-{0000000}</displayFormat>
        <label>Exclusive Experience Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusive Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exclusive_Experience__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exclusive Experiences</relationshipLabel>
    <relationshipName>Exclusive_Experiences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exclusive_Experience__c/fields/Dream_Id__c.field-meta.xml
<CustomField>
    <fullName>Dream_Id__c</fullName>
    <label>Dream Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exclusive_Experience__c/fields/Offer_Code__c.field-meta.xml
<CustomField>
    <fullName>Offer_Code__c</fullName>
    <label>Offer Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Typology__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>XXPR_Offer_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exclusive_Experience__c/fields/Typology__c.field-meta.xml
<CustomField>
    <fullName>Typology__c</fullName>
    <label>Typology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>XXPR_Typology</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/XXPR_Offer_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>exclu_nba_1_2020</fullName>
    </customValue>
    <customValue>
        <fullName>exclu_nba_1_2020.</fullName>
    </customValue>
    <customValue>
        <fullName>test_exclusive_sale</fullName>
    </customValue>
    <customValue>
        <fullName>exclu_offer_collectibles_ff</fullName>
    </customValue>
    <customValue>
        <fullName>digital_collectibles_wave_1</fullName>
    </customValue>
    <customValue>
        <fullName>digital_collectibles_wave_2</fullName>
    </customValue>
    <customValue>
        <fullName>digital_collectibles_speedy40_july23</fullName>
    </customValue>
    <customValue>
        <fullName>lv_remix_excluoffer</fullName>
    </customValue>
    <customValue>
        <fullName>men_show_ss24_exclu_offer</fullName>
    </customValue>
    <customValue>
        <fullName>web_digital_collectibles_tile_trunk</fullName>
    </customValue>
    <customValue>
        <fullName>web_via_varsity_blouson</fullName>
    </customValue>
    <customValue>
        <fullName>mylv_volt_202007</fullName>
        <isActive>false</isActive>
        <label>mylv_volt_202007</label>
    </customValue>
    <customValue>
        <fullName>test_exclusive_offer</fullName>
        <isActive>false</isActive>
        <label>test_exclusive_offer</label>
    </customValue>
    <description>Exclusive Experience offer codes. Must be unique + lowercase only + not contain space/special caracters/accent</description>
    <masterLabel>XXPR Offer Code</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/XXPR_Typology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NBA MSG Experience</fullName>
    </customValue>
    <customValue>
        <fullName>NBA Regular</fullName>
    </customValue>
    <customValue>
        <fullName>test_exclusive_sale</fullName>
    </customValue>
    <customValue>
        <fullName>Collectibles</fullName>
    </customValue>
    <customValue>
        <fullName>VIA Speedy 40</fullName>
    </customValue>
    <customValue>
        <fullName>LV Remix</fullName>
    </customValue>
    <customValue>
        <fullName>LV Show Men SS24</fullName>
    </customValue>
    <customValue>
        <fullName>Tile Trunk</fullName>
    </customValue>
    <customValue>
        <fullName>VIA Varsity</fullName>
    </customValue>
    <description>Exclusive Experience typology</description>
    <masterLabel>XXPR Typology</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ICX_Exclusive_Sales_LC_Test.cls
@isTest
public class ICX_Exclusive_Sales_LC_Test {
    
    
    @isTest 
    static void test_trigger() {
        
        Test.StartTest();

        // Create Account
        String code = String.valueOf(Math.round(Math.random() * 100000));
        Account acc = new Account(
            LastName = 'lastName',
            FirstName = 'firstName',
            PersonEmail = code+'test@test.com',  
            PrimaryCountry__pc = 'BELGIUM',
            Salutation = '02',
            HomeAddressCountryCode__pc = 'BEL',
            DREAMID__c = '87654321',
            Can_Be_Contacted_By_Email__pc = true
        );
        insert acc;

        // Get XXPR Picklist values according to Org
        Schema.DescribeFieldResult XXPR_Typology = Exclusive_Experience__c.Typology__c.getDescribe();
        Schema.sObjectField fieldTypology = XXPR_Typology.getSObjectField();
        List<PicklistEntry> picklistValuesTypology = fieldTypology.getDescribe().getPicklistValues();        
        
        Schema.DescribeFieldResult XXPR_OfferCode = Exclusive_Experience__c.Offer_Code__c.getDescribe();
        Schema.sObjectField fieldOfferCode = XXPR_OfferCode.getSObjectField();
        List<PicklistEntry> picklistValuesOfferCode = fieldOfferCode.getDescribe().getPicklistValues();
        
        // Create XXPR
        Exclusive_Experience__c xxpr1 = new Exclusive_Experience__c(
            Account_Id__c = acc.Id,
            Dream_Id__c = acc.DREAMID__c,
            Typology__c = picklistValuesTypology[0].getValue(),
            Offer_Code__c = picklistValuesOfferCode[0].getValue()
        ); 
        insert xxpr1; 
        Integer numOfXXPR = 0 ;
        List<Exclusive_Experience__c> lst = ICX_Exclusive_Sales_LC.getExculisveSales(acc.id);
        if(!lst.isEmpty()){
           numOfXXPR= 1;
        }
        System.assertEquals(numOfXXPR, lst.size());
     
    }

}