force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Has_Private_Data__c.field-meta.xml
<CustomField>
    <fullName>Has_Private_Data__c</fullName>
    <formula>!ISPICKVAL(Jacket__pc, &apos;&apos;)
|| !ISPICKVAL(Dress__pc, &apos;&apos;)
|| !ISPICKVAL(Knit__pc, &apos;&apos;)
|| !ISPICKVAL(Pant__pc, &apos;&apos;)
|| !ISPICKVAL(Shirt__pc, &apos;&apos;)
|| !ISPICKVAL(Skirt__pc, &apos;&apos;)
|| !ISPICKVAL(Suit__pc, &apos;&apos;)
|| !ISPICKVAL(Belt__pc, &apos;&apos;)
|| !ISPICKVAL(Shoes__pc, &apos;&apos;)
|| !ISPICKVAL(Ring__pc, &apos;&apos;)
|| !ISBLANK(Spouse__pc)
|| !ISPICKVAL(AnniversaryMonth__pc, &apos;&apos;)
|| !ISPICKVAL(AnniversaryDay__pc, &apos;&apos;)
|| !ISBLANK(Children__pc)
|| !ISBLANK(Pets__pc)
|| !ISBLANK(ShopsFor__pc)
|| !ISPICKVAL(PersonalInterest1__pc, &apos;&apos;)
|| !ISPICKVAL(PersonalInterest2__pc, &apos;&apos;)
|| !ISPICKVAL(PersonalInterest3__pc, &apos;&apos;)
|| !ISBLANK(FoodPreferences__pc)
|| !ISBLANK(Star_FoodPreferences__pc)
|| !ISBLANK(BeveragePreferences__pc)
|| !ISBLANK(AccessoriesInterest__pc)
|| !ISBLANK(JewelleryInterest__pc)
|| !ISBLANK(LeatherGoodsInterest__pc)
|| !ISBLANK(RTWInterest__pc)
|| !ISBLANK(ShoesInterest__pc)
|| !ISBLANK(WatchesInterest__pc)
|| !ISBLANK(OtherInterest__pc)
|| !ISBLANK(ServiceInterest__pc)
|| !ISBLANK(PersonAssistantName)
|| !ISBLANK(PersonAssistantPhone)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Has Private Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CleanUpLog__c/CleanUpLog__c.object-meta.xml
<CustomObject>
    <label>CleanUpLog</label>
    <nameField>
        <label>CleanUpLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CleanUpLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CleanUpLog__c/fields/DreamIdClient__c.field-meta.xml
<CustomField>
    <fullName>DreamIdClient__c</fullName>
    <label>DreamIdClient</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CleanUpLog__c/fields/IdSFDCAccount__c.field-meta.xml
<CustomField>
    <fullName>IdSFDCAccount__c</fullName>
    <label>IdSFDCAccount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/accountPurgeLimit__c.field-meta.xml
<CustomField>
    <fullName>accountPurgeLimit__c</fullName>
    <description>number of mounth to purg account</description>
    <label>accountPurgeLimit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/fields/ProspectClientPurge__c.field-meta.xml
<CustomField>
    <fullName>ProspectClientPurge__c</fullName>
    <defaultValue>2</defaultValue>
    <description>This field is used to determine the elements to purge.
0 : for Prospects
1 : for Clients
2 ; for Clients and Prospect</description>
    <label>Prospect Client Purge</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Program is an entity related to master information since this entity is linked to : a client, an event, a hotel (not necessarily), a gift (not necessarily), an experience (not necessarily) and a restaurant (not necessarily</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IC_BatchClientCleanUp.cls
/**
    Description: Batch used in the developper console in order to create Bachlog oBject
    Created for: SOW: IC007 ICON project
    Create date: 03/06/2014

    Update History
    --------------
    Create date: Juin 2014  HCH
    
    
    Issues / TODOs
    --------------
*/

   global class IC_BatchClientCleanUp implements Database.Batchable<sObject>{
      
    public String query;
//    Integer isProspectOrAndClient = Integer.valueOf((Decimal)ICONSettings__c.getOrgDefaults().get('ProspectClientPurge__c'));
    Integer accountPurgeLimit = Integer.valueOf((Decimal)ICONSettings__c.getOrgDefaults().get('accountPurgeLimit__c'));
    date DateLimitOfLastTran = Date.today().addMonths(-accountPurgeLimit);
    global IC_BatchClientCleanUp(){
        query = 'SELECT Id,DREAMID__c, Has_Private_Data__c, IsProspect__pc FROM Account Where LastTrans__pc < :DateLimitOfLastTran AND  Date_Identity__pc=null';  
       
       /* 
        if(isProspectOrAndClient == 0)
          query += ' AND IsProspect__pc = true';
        else if (isProspectOrAndClient == 1)
          query += ' AND IsProspect__pc = false';  */
        
     }
        
    global database.querylocator start(Database.BatchableContext CD){
        System.debug('#### START - BatchLogInsert');
        System.debug('#### query : '+query);
        return Database.getQueryLocator(query);   
    } 
    
    global void execute(Database.BatchableContext CD, List<sObject> scope){
        
        Integer isProspectOrAndClient = Integer.valueOf((Decimal)ICONSettings__c.getOrgDefaults().get('ProspectClientPurge__c'));
        
        List<CleanUpLog__c> BatchLogTocreate = new List<CleanUpLog__c>();
        List<Account> lstAccTemp = new List<Account>();
        List<Account> lstAccFinal = new List<Account>();
        
        try{
            for(sObject o:scope){ 
                Account acc = (Account)o;
                lstAccTemp.add(acc); 
            }  
            
            if (isProspectOrAndClient == 0) {
                if (lstAccTemp != null && lstAccTemp.size() > 0) {
                    for (Account act : lstAccTemp) {
                        if(act.IsProspect__pc){
                            lstAccFinal.add(act); 
                        }
                    }
                    
                }  
                
            } else if (isProspectOrAndClient == 1) {
                if (lstAccTemp != null && lstAccTemp.size() > 0) {
                    for (Account act : lstAccTemp) {
                        if(!act.IsProspect__pc){
                            lstAccFinal.add(act); 
                        }
                    }                   
                }  
            }
            
            lstAccTemp.clear();
            lstAccTemp.addAll(lstAccFinal);
            lstAccFinal.clear();

             
            if (lstAccTemp != null && lstAccTemp.size() > 0) {
                for (Account act : lstAccTemp) {
                    if(!act.Has_Private_Data__c){
                        lstAccFinal.add(act); 
                    }
                }
                
            } 
            
            // Deuxieme partie Where
            List<Program__c> lstIdProg = new List<Program__c>();
            lstIdProg = [Select AccountId__c From Program__c]; 
            Set<ID> buffAccountID = new Set<ID>();
            
            for (Program__c prg : lstIdProg) {
                buffAccountID.add(prg.AccountId__c);
            }
                
            for (Account acc : lstAccFinal) {
                if(!buffAccountID.contains(acc.ID)) {
                    CleanUpLog__c BL = new CleanUpLog__c(IdSFDCAccount__c = acc.Id, DreamIdClient__c = acc.DREAMID__c);
                    BatchLogTocreate.add(BL);  
                }
            }
            
            insert BatchLogTocreate; 
       
        }catch (DmlException e){
            // Process exception here
            System.debug('#### '+e.getTypeName()+' Exception:'+e.getMessage()+' '+e.getStackTraceString());
        }       
    }
    
    global void finish(Database.BatchableContext CD){}
    
}