force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/accountPurgeLimit__c.field-meta.xml
<CustomField>
    <fullName>accountPurgeLimit__c</fullName>
    <description>number of mounth to purg account</description>
    <label>accountPurgeLimit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IC_SchedulerBatchClientCleanUp_TEST.cls
@isTest
private class IC_SchedulerBatchClientCleanUp_TEST {

        static testMethod void testBatch() {
        	
        insert new ICONSettings__c (accountPurgeLimit__c=18);
        
        Account acc = IC_TestFactory.createAccount();
        acc.DREAMID__c = '123456';
        acc.LastTrans__pc = Date.today().addMonths(-20);
        insert acc;  
           
        IC_SchedulerBatchClientCleanUp myScheduler = new IC_SchedulerBatchClientCleanUp();
        
        Test.startTest();
        String sch = '0 0 23 L * ?';
        system.schedule('Test check', sch, myScheduler);
        Test.stopTest();
        

    }

}