force-app/main/default/objects/Account/fields/DREAMID__c.field-meta.xml
<CustomField>
    <fullName>DREAMID__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/DreamIdMasterClient__c.field-meta.xml
<CustomField>
    <fullName>DreamIdMasterClient__c</fullName>
    <label>DreamId Master Client</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ToDelete__c.field-meta.xml
<CustomField>
    <fullName>ToDelete__c</fullName>
    <label>To Delete</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlan__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/IsClosed__c.field-meta.xml
<CustomField>
    <fullName>IsClosed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsClosed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CLI_CliList__c/CLI_CliList__c.object-meta.xml
<CustomObject>
    <description>Create your list of clients</description>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CLI_CliList__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
                <default>true</default>
                <label>Regular</label>
            </value>
            <value>
                <fullName>Exclusive</fullName>
            </value>
            <value>
                <fullName>Reassign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CLM_CliListMember__c/CLM_CliListMember__c.object-meta.xml
<CustomObject>
    <description>Customers in your client list.</description>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>CLM-{0}</displayFormat>
        <label>Client List Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_CliListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_CliListMember__c/fields/ClientList__c.field-meta.xml
<CustomField>
    <fullName>ClientList__c</fullName>
    <description>Client list which is containing this customer.</description>
    <inlineHelpText>Select the client list to contain this customer.</inlineHelpText>
    <label>Client List</label>
    <referenceTo>CLI_CliList__c</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CLM_CliListMember__c/fields/DreamId__c.field-meta.xml
<CustomField>
    <fullName>DreamId__c</fullName>
    <formula>Client__r.Account.DREAMID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dream Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>An event is a public evenment for the purpose of celebration or marketing related to the customer.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>End Date of the event</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Zone</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the event</description>
    <label>Location</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of the event</description>
    <inlineHelpText>If you leave this field empty then it will be populated using the program start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <description>Theme of the event</description>
    <label>Theme</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Art &amp; Culture</fullName>
            </value>
            <value>
                <fullName>Food &amp; Wine</fullName>
            </value>
            <value>
                <fullName>Watch &amp; Jewelry</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>Sport &amp; Leisure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Theme of the event</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Theme__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Asnières</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
            </value>
            <value>
                <fullName>Fashion Show Men</fullName>
            </value>
            <value>
                <fullName>Fashion Show Women</fullName>
            </value>
            <value>
                <fullName>Fiesso</fullName>
            </value>
            <value>
                <fullName>Fondation LV</fullName>
            </value>
            <value>
                <fullName>Grasse</fullName>
            </value>
            <value>
                <fullName>La Fabrique du Temps</fullName>
            </value>
            <value>
                <fullName>Maison LVMH</fullName>
            </value>
            <value>
                <fullName>Series</fullName>
            </value>
            <value>
                <fullName>Social Gathering</fullName>
            </value>
            <value>
                <fullName>Sport &amp; Leasure</fullName>
            </value>
            <value>
                <fullName>Store Opening</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Watch &amp; Jewelry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ICONSettings__c/ICONSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ICON_Settings</label>
</CustomObject>

force-app/main/default/objects/ICONSettings__c/fields/AccLastContactTimeRange__c.field-meta.xml
<CustomField>
    <fullName>AccLastContactTimeRange__c</fullName>
    <description>Defines the time range (in days) studied to display the &quot;Contacted in last X days&quot; in ICON Mobile (+ Batch)</description>
    <label>Account Last Contact Time Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ICONSettings__c/fields/clientMergeLimit__c.field-meta.xml
<CustomField>
    <fullName>clientMergeLimit__c</fullName>
    <label>Client Merge Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Program is an entity related to master information since this entity is linked to : a client, an event, a hotel (not necessarily), a gift (not necessarily), an experience (not necessarily) and a restaurant (not necessarily</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/EventId__c.field-meta.xml
<CustomField>
    <fullName>EventId__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/DREAMId__c.field-meta.xml
<CustomField>
    <fullName>DREAMId__c</fullName>
    <externalId>true</externalId>
    <label>DREAM Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/IC_SchedulerClientMerge_TEST.cls
@isTest 
global with sharing class IC_SchedulerClientMerge_TEST {

@testSetup 
    static void TestIC_SchedulerClientMerge() {
        //#### custom settings
        ICONSettings__c stt = new ICONSettings__c();
        stt.clientMergeLimit__c = 2;
        stt.AccLastContactTimeRange__c = 30;
        insert stt;
                
        List<Account> accounts = new List<Account>();        

        // ####### MASTER ACCOUNTS ########
        // ##### MASTER #1
        Account accMaster1;
        accMaster1 = IC_TestFactory.createAccount();
        accMaster1.Dreamid__c = 'TEST894M0';
        accMaster1.lastName = 'MasterClient #0';
        accMaster1.PersonEmail = 'master@master.com';
        accMaster1.Unsubscribe__pc = false;
        accMaster1.UnsubscribeDate__pc = null;
        accMaster1.PersonHasOptedOutOfEmail = false;
        accMaster1.DoNotSMS__pc = false;
        accMaster1.DoNotContactbyPost__pc = false;
        accounts.add(accMaster1);
        // ##### MASTER #2
        Account accMaster2;
        accMaster2 = IC_TestFactory.createAccount();
        accMaster2.Dreamid__c = 'TEST895M0';
        accMaster2.PersonEmail = null;
        accMaster2.lastName = 'MasterClient #1';
        accMaster2.Unsubscribe__pc = false;
        accMaster2.UnsubscribeDate__pc = null;
        accMaster2.PersonHasOptedOutOfEmail = false;
        accMaster2.DoNotSMS__pc = false;
        accMaster2.DoNotContactbyPost__pc = false;
        accounts.add(accMaster2);
        // ####### MASTER ACCOUNTS ########
        // ####### SLAVE ACCOUNTS ########
        // ##### SLAVE #1
        Account account1;
        account1 = IC_TestFactory.createAccount();
        account1.Dreamid__c = 'TEST893S0';
        account1.DreamIdMasterClient__c = 'TEST894M0';
        account1.ToDelete__c = '1';
        account1.lastName = 'SlaveClient #0';
        account1.PersonEmail = 'slave@slave.com';
        account1.Unsubscribe__pc = true;
        account1.UnsubscribeDate__pc = Date.today();
        account1.PersonHasOptedOutOfEmail = true;
        account1.DoNotSMS__pc = true;
        account1.DoNotContactbyPost__pc = true;
        accounts.add(account1);
        // ##### SLAVE #2
        Account account2;
        account2 = IC_TestFactory.createAccount();
        account2.Dreamid__c = 'TEST892S0';
        account2.DreamIdMasterClient__c = 'TEST894M0';
        account2.ToDelete__c = '1';
        account2.lastName = 'SlaveClient #1';
        account2.PersonEmail = 'master@master.com';
        account2.Unsubscribe__pc = true;
        account2.UnsubscribeDate__pc = Date.today();
        account2.PersonHasOptedOutOfEmail = true;
        account2.DoNotSMS__pc = true;
        account2.DoNotContactbyPost__pc = true;
        accounts.add(account2);
        // ##### SLAVE #3
        Account account3;
        account3 = IC_TestFactory.createAccount();
        account3.Dreamid__c = 'TEST891S0';
        account3.DreamIdMasterClient__c = 'TEST895M0';
        account3.ToDelete__c = '1';
        account3.lastName = 'SlaveClient #1';
        account3.PersonEmail = 'slave3@master.com';
        account3.Unsubscribe__pc = true;
        account3.UnsubscribeDate__pc = Date.today();
        account3.PersonHasOptedOutOfEmail = true;
        account3.DoNotSMS__pc = true;
        account3.DoNotContactbyPost__pc = true;
        accounts.add(account3);
        // ####### SLAVE ACCOUNTS ########

        insert accounts;

        // Create new ActionPlan    
        ActionPlan__c actionPlan = new ActionPlan__c();  
        actionPlan.Comments__c = 'Comments';
        actionPlan.IsClosed__c = false;
        actionPlan.AccountId__c = account1.Id;
        actionPlan.Subject__c =  'subject'  ;            
        insert actionPlan;
        
        // Create new IndividualEmailResult 
        et4ae5__IndividualEmailResult__c em;   
        em = new et4ae5__IndividualEmailResult__c();
        em.et4ae5__Contact__c = [Select Id From Contact WHERE AccountId = :account1.Id].id;       
        et4ae5__SendDefinition__c sd = new et4ae5__SendDefinition__c  ();
        insert sd;

        em.et4ae5__SendDefinition__c = sd.id;
        insert em;
        
        // Create new SMSDefinition    
        et4ae5__SMSDefinition__c sms = new et4ae5__SMSDefinition__c();
        sms.et4ae5__Contact__c = [Select Id From Contact WHERE AccountId = :account1.Id].id;             
        insert sms;
        
        //Create new STAR Event ('Event__c' Object ). It will be used when STAR Program is created
        Event__c evt = new Event__c();
        evt.Name='EventTest';
        evt.Start_Date__c =Date.today();
        evt.End_Date__c = Date.today();      
        evt.Location__c='PariSelecs';
        evt.Level__c='International';
        evt.Theme__c='Art & Culture';
        evt.Type__c='Exhibition';
        
        insert evt;
        
        //Create new Program
        Program__c prg;
        prg = New Program__c();
        prg.name='ProgramTest';
        prg.AccountId__c = account1.Id;
        prg.EventId__c = evt.id;
        
        insert prg;
        /*        
        // Create new Event 
        Event event;        
        event = IC_TestFactory.createEvent(account1);
        //event.whoID = account.PersonContactId;
        event.whoID = [Select Id From Contact WHERE AccountId = :account1.Id].id;
        insert event;*/
        
        // Create new Task
        Task task;
        task = IC_TestFactory.createTask(account1);
        //task.whoID = account.PersonContactId;
        task.whoID = [Select Id From Contact WHERE AccountId = :account1.Id].id;
        insert task;
              
        // Create new Task related to an ActionPlan 
        task = IC_TestFactory.createTask(account1);
        task.whoID = [Select Id From Contact WHERE AccountId = :account1.Id].id;
        task.whatID= [SELECT Id FROM ActionPlan__c WHERE AccountId__c = :account1.Id].id;
        insert task;
        
        // Create new Event related to an ActionPlan 
        /*event = IC_TestFactory.createEvent(account1);
        event.whoID = [Select Id From Contact WHERE AccountId = :account1.Id].id;
        event.whatID= [SELECT Id FROM ActionPlan__c WHERE AccountId__c = :account1.Id].id;
        insert event;*/

        CLI_CliList__c cl = IC_TestFactory.clientlistMembers();
        insert cl;
        
        CLM_CliListMember__c Clm = new CLM_CliListMember__c();
        Clm.Client__c = [Select Id From Contact WHERE AccountId = :account1.Id].id;
        Clm.ClientList__c = Cl.Id;
        insert Clm; 
        
        // Create a case attached to the slave account
        Group g = new Group (Name = 'Queue-France', Type = 'Queue');
        insert g;

        System.runAs(new User(Id=UserInfo.getUserId()))
        {
            QueueSObject q = new QueueSobject(QueueID = g.id, SobjectType = 'case');
            insert q;
        }
       
        Case ca = new Case (Type = 'Product Information',
                            Origin = 'Email',
                            Status = 'New',
                            Subject = 'test case subject ' + Datetime.now(),
                            Description = 'test case description ' + Datetime.now(),
                            Accountid = account1.id,
                            ContactID = account1.PersonContactId,
                            Ownerid = g.id);
        insert ca;

        String id = [Select Id From Contact WHERE AccountId = :accMaster1.Id].id;
    }
	
        @isTest static void test_method_three() {

            Test.startTest();
            IC_SchedulerClientMerge bat = new IC_SchedulerClientMerge();
            String sch = '20 30 8 10 2 ?';
			System.schedule('TEST1', sch, bat);
            Test.stopTest();
        }
    }