force-app/main/default/objects/Account/fields/Ind_10K__c.field-meta.xml
<CustomField>
    <fullName>Ind_10K__c</fullName>
    <description>Indicator for clients that spent 10K Euros over the last year or clients that may purchase for 10K Euros this year</description>
    <label>Indic 10K</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>10K</fullName>
            </value>
            <value>
                <fullName>Potential 10K</fullName>
            </value>
            <value>
                <fullName>50K</fullName>
            </value>
            <value>
                <fullName>10K this year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BL_ClientList__mdt/BL_ClientList__mdt.object-meta.xml
<CustomObject>
    <label>BL_ClientList</label>
    <pluralLabel>BL_ClientLists</pluralLabel>
</CustomObject>

force-app/main/default/objects/CLI_CliList__c/CLI_CliList__c.object-meta.xml
<CustomObject>
    <description>Create your list of clients</description>
    <label>Client List</label>
    <nameField>
        <label>Client List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_CliListMember__c/CLM_CliListMember__c.object-meta.xml
<CustomObject>
    <description>Customers in your client list.</description>
    <label>Client List Member</label>
    <nameField>
        <displayFormat>CLM-{0}</displayFormat>
        <label>Client List Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CLM_CliListMember__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CLM_CliListMember__c/fields/ClientList__c.field-meta.xml
<CustomField>
    <fullName>ClientList__c</fullName>
    <description>Client list which is containing this customer.</description>
    <inlineHelpText>Select the client list to contain this customer.</inlineHelpText>
    <label>Client List</label>
    <referenceTo>CLI_CliList__c</referenceTo>
    <relationshipLabel>Client List Members</relationshipLabel>
    <relationshipName>Client_List_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Store object. Gives details on store to which the client is attached to</description>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/TeamMember__c/TeamMember__c.object-meta.xml
<CustomObject>
    <label>TeamMember</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>TeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TeamMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamMember__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamMembersManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamMember__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <externalId>true</externalId>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BL_ICON_ClientList_Test.cls
@isTest
public class BL_ICON_ClientList_Test {
	@isTest
	static void testMethodGet() {
		Account acc = new Account(LastName = 'test');
		insert acc;
		BL_AppSettings.setAppSettings('Icon');
		BL_ICON_ClientList blClient = new BL_ICON_ClientList();
		User u = IC_Test_Common.prepareTestUser('System Administrator');
		u.DefaultStore__c = '1234';
		insert u;
		Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
		insert store;
		CLI_CliList__c clientList = new CLI_CliList__c( /*ExpirationDate__c = Date.newInstance(2020,10,01),*/ Name = '#May Client Birthdays#', OwnerId = u.id);
		insert clientList;
		blClient.me = (BL_UserInfo) Type.forName('BL_ICON_UserInfo').newInstance();
		blClient.pathParameters = new Map < String, String > {
			'id' => clientList.Id
		};
		blClient.queryParams = new Map < String, String > ();
		Test.startTest();
		try{
			blClient.executeGET();
			}
		catch(Exception e){}
		blClient.resource = 'members';
		try{
			blClient.executeGET();
			}
		catch(Exception e){}
		blClient.resource = 'count';
		blClient.pathParameters = new Map < String, String > {
			'id' => null
		};
		try{
			blClient.executeGET();
			}
			catch(Exception e){}
		blClient.queryParams = new Map < String, String > {
			'features' => 'others;categories;main;services;myLists'
		};
		try{
			blClient.executeGET();
			}
			catch(Exception e){}

		Test.stopTest();
	}

    
    @isTest
	static void testMethodGet2() {
		Account acc = new Account(LastName = 'test');
		insert acc;
		BL_AppSettings.setAppSettings('Icon');
		BL_ICON_ClientList blClient = new BL_ICON_ClientList();
		User u = IC_Test_Common.prepareTestUser('System Administrator');
		u.DefaultStore__c = '1234';
        
        User u2 = IC_Test_Common.prepareTestUser('System Administrator');
		u2.DefaultStore__c = '1234';
        u2.WWEmployeeNumber__c = 'FR1235';

        User u3 = IC_Test_Common.prepareTestUser('System Administrator');
		u3.DefaultStore__c = '1234';
        u3.WWEmployeeNumber__c = 'FR5682';
        insert new List < User > {u,u2,u3 };
        
        TeamMember__c tm = new TeamMember__c(User__c = u2.id, Manager__c = u.id);
		TeamMember__c tm1 = new TeamMember__c(User__c = u2.id, Manager__c = u.id);
        
		insert new List < TeamMember__c > {tm,tm1 };
        
		Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
		insert store;
		CLI_CliList__c clientList = new CLI_CliList__c( /*ExpirationDate__c = Date.newInstance(2020,10,01),*/ Name = '#May Client Birthdays#', OwnerId = u.id);
		insert clientList;
        
        BL_ClientList__mdt clientList2 = [SELECT DeveloperName, Id FROM BL_ClientList__mdt WHERE DeveloperName = 'Men_RTW'];
 		BL_ClientList__mdt clientList3 = [SELECT DeveloperName, Id FROM BL_ClientList__mdt WHERE DeveloperName = 'Care_Services'];
        BL_ClientList__mdt clientList4 = [SELECT DeveloperName, Id FROM BL_ClientList__mdt WHERE DeveloperName = 'Recent_Clients'];

		blClient.me = (BL_UserInfo) Type.forName('BL_ICON_UserInfo').newInstance();
		
		Test.startTest();
        
        blClient.queryParams = new Map < String, String > {
			'features' => 'others',
            'filter' =>  'Ind_10K__c = \'10K\'' ,
            'tab' => '1',
            'caIds' => u2.id+';'+u3.id 

		};
        blClient.pathParameters = new Map < String, String > {
			'id' => clientList2.Id
		};   
        blClient.resource = 'members';
        
		blClient.executeGET();

        blClient.queryParams = new Map < String, String > {
			'features' => 'others',
            'filter' =>  'Ind_10K__c = \'10K\'' ,
            'caIds' => u2.id+';'+u3.id 
		};
        blClient.pathParameters = new Map < String, String > {
			'id' => clientList4.Id
		};   
        blClient.resource = 'members';
        
		blClient.executeGET();
        
        blClient.queryParams = new Map < String, String > {
			'features' => 'others',
            'filter' =>  'Ind_10K__c = \'10K\'' ,
            'tab' => '1'
		};
        blClient.pathParameters = new Map < String, String > {
			'id' => clientList2.Id
		};   
        blClient.resource = 'count';
        
		blClient.executeGET();
        
         blClient.queryParams = new Map < String, String > {
			'features' => 'others',
            'filter' =>  'Ind_10K__c = \'10K\'' ,
            'tab' => '1',
             'caIds' => u2.id+';'+u3.id 

		};
        blClient.pathParameters = new Map < String, String > {
			'id' => clientList4.Id
		};   
        blClient.resource = 'count';
        
		blClient.executeGET();
        
        blClient.queryParams = new Map < String, String > {
			'features' => 'others',
            'filter' =>  'Ind_10K__c = \'10K\'' ,
            'tab' => '1'
		};
        blClient.pathParameters = new Map < String, String > {
			'id' => clientList3.Id
		};   
        blClient.resource = 'count';
        
		blClient.executeGET();

    
		Test.stopTest();
	}
    
	@isTest
	static void testMethodPost() {
		BL_AppSettings.setAppSettings('Icon');
		BL_ICON_ClientList blClient = new BL_ICON_ClientList();
		User u = IC_Test_Common.prepareTestUser('System Administrator');
		u.DefaultStore__c = '1234';
		insert u;
		Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
		insert store;
		CLI_CliList__c clientList = new CLI_CliList__c( /*ExpirationDate__c = Date.newInstance(2020,10,01),*/ Name = '#May Client Birthdays#', OwnerId = u.id);
		insert clientList;
		Account c = new Account(LastName = 'test');
		insert c;
		Account c2 = new Account(LastName = 'test2');
		insert c2;
		blClient.me = (BL_UserInfo) Type.forName('BL_ICON_UserInfo').newInstance();
		blClient.pathParameters = new Map < String, String > {
			'id' => null
		};
		List < String > clientsIds = new List < String > {
			c.id
		};
		List < String > clientsIds2 = new List < String > {
			c2.id
		};
		blClient.requestBody = new Map < String, Object > {
			'clientIds' => clientsIds,
			'ownerId' => u.id,
			'name' => 'test'
		};
		Test.startTest();
		blClient.executePOST();
		blClient.pathParameters = new Map < String, String > {
			'id' => clientList.Id
		};
		blClient.requestBody = new Map < String, Object > {
			'clientIds' => clientsIds2,
			'ownerId' => u.id,
			'name' => 'test'
		};
		blClient.executePOST();
		Test.stopTest();
	}
	@isTest
	static void testMethodPUT() {
		BL_AppSettings.setAppSettings('Icon');
		BL_ICON_ClientList blClient = new BL_ICON_ClientList();
		User u = IC_Test_Common.prepareTestUser('System Administrator');
		u.DefaultStore__c = '1234';
		insert u;
		Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
		insert store;
		CLI_CliList__c clientList = new CLI_CliList__c( /*ExpirationDate__c = Date.newInstance(2020,10,01),*/ Name = '#May Client Birthdays#', OwnerId = u.id);
		insert clientList;
		Account c2 = new Account(LastName = 'test', FirstName = 'test');
		insert c2;
        Account c = new Account(LastName = 'test', FirstName = 'test');
		insert c;
        CLM_CliListMember__c Clm = new CLM_CliListMember__c(Client__c= [Select Id From Contact WHERE AccountId = :c.id].id,ClientList__c = clientList.id);
        CLM_CliListMember__c Clm2 = new CLM_CliListMember__c(Client__c= [Select Id From Contact WHERE AccountId = :c2.id].id,ClientList__c = clientList.id);

        insert new list<CLM_CliListMember__c>{Clm,clm2}; 
		blClient.me = (BL_UserInfo) Type.forName('BL_ICON_UserInfo').newInstance();
		List < String > clientsIds = new List < String > {
			c.id,c2.id
		};
		Test.startTest();
		blClient.pathParameters = new Map < String, String > {
			'id' => clientList.Id
		};
		blClient.requestBody = new Map < String, Object > {
			'clientIds' => clientsIds,
			'ownerId' => u.id,
			'name' => 'test'
		};
		blClient.executePUT();
		Test.stopTest();
	}
	@isTest
	static void testMethodDELETE() {
		BL_AppSettings.setAppSettings('Icon');
		BL_ICON_ClientList blClient = new BL_ICON_ClientList();
		User u = IC_Test_Common.prepareTestUser('System Administrator');
		u.DefaultStore__c = '1234';
		insert u;
		Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
		insert store;
		CLI_CliList__c clientList = new CLI_CliList__c( /*ExpirationDate__c = Date.newInstance(2020,10,01),*/ Name = '#May Client Birthdays#', OwnerId = u.id);
		insert clientList;
		blClient.me = (BL_UserInfo) Type.forName('BL_ICON_UserInfo').newInstance();
		Test.startTest();
		blClient.pathParameters = new Map < String, String > {
			'id' => clientList.Id
		};
		blClient.executeDELETE();
		Test.stopTest();
	}
	@isTest
	static void testMethodGetWithQueryId() {
		try {
			Account acc = new Account(LastName = 'test');
			insert acc;
			BL_AppSettings.setAppSettings('Icon');
			BL_ICON_ClientList blClient = new BL_ICON_ClientList();
			User u = IC_Test_Common.prepareTestUser('System Administrator');
			u.DefaultStore__c = '1234';
			insert u;
			Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
			insert store;
			CLI_CliList__c clientList = new CLI_CliList__c( /*ExpirationDate__c = Date.newInstance(2020,10,01),*/ Name = '#May Client Birthdays#', OwnerId = u.id);
			insert clientList;
			blClient.me = (BL_UserInfo) Type.forName('BL_ICON_UserInfo').newInstance();
			blClient.pathParameters = new Map < String, String > {
				'id' => clientList.Id
			};
			blClient.queryParams = new Map < String, String > ();
			blClient.resource = 'members';
			blClient.isStandardRestApiRequired = true;
			blClient.PageSize = 200;
			blClient.pageIndex = 0;
			Test.startTest();
			blClient.executeGET();
			Test.stopTest();
		} catch (Exception e) {}
	}
	@isTest
	static void testMethodGetCount() {
		Account acc = new Account(LastName = 'test');
		insert acc;
		BL_AppSettings.setAppSettings('Icon');
		BL_ICON_ClientList blClient = new BL_ICON_ClientList();
		User u = IC_Test_Common.prepareTestUser('System Administrator');
		u.DefaultStore__c = '1234';
		insert u;
		Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
		insert store;
		CLI_CliList__c clientList = new CLI_CliList__c( /*ExpirationDate__c = Date.newInstance(2020,10,01),*/ Name = '#May Client Birthdays#', OwnerId = u.id);
		insert clientList;
		blClient.me = (BL_UserInfo) Type.forName('BL_ICON_UserInfo').newInstance();
		blClient.pathParameters = new Map < String, String > {
			'id' => clientList.Id
		};
		blClient.queryParams = new Map < String, String > ();
		Test.startTest();
		blClient.resource = 'count';
		blClient.executeGET();
		BL_ClientList__mdt clientList2 = [SELECT DeveloperName, Id FROM BL_ClientList__mdt WHERE DeveloperName = 'Birthday_Wedding_Anniversary'];
		blClient.pathParameters = new Map < String, String > {
			'id' => clientList2.Id
		};
		blClient.executeGET();
		Test.stopTest();
	}
	@isTest
	static void testMethodGetMembers() {
		Account acc = new Account(LastName = 'test');
		insert acc;
		BL_AppSettings.setAppSettings('Icon');
		BL_ICON_ClientList blClient = new BL_ICON_ClientList();
		User u = IC_Test_Common.prepareTestUser('System Administrator');
		u.DefaultStore__c = '1234';
		insert u;
		Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
		insert store;
		CLI_CliList__c clientList = new CLI_CliList__c( /*ExpirationDate__c = Date.newInstance(2020,10,01),*/ Name = '#May Client Birthdays#', OwnerId = u.id);
		insert clientList;
		blClient.me = (BL_UserInfo) Type.forName('BL_ICON_UserInfo').newInstance();
		blClient.pathParameters = new Map < String, String > {
			'id' => clientList.Id
		};
		blClient.queryParams = new Map < String, String > ();
		Test.startTest();
		blClient.resource = 'members';
		try {
			blClient.executeGET();
		} catch (Exception e) {
			
		}
		
		Test.stopTest();
	}
	@isTest
	static void testMethodGetMembersOfPermanentClientList() {
		try {
			Account acc = new Account(LastName = 'test');
			insert acc;
			BL_AppSettings.setAppSettings('Icon');
			BL_ICON_ClientList blClient = new BL_ICON_ClientList();
			User u = IC_Test_Common.prepareTestUser('System Administrator');
			u.DefaultStore__c = '1234';
			insert u;
			Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
			insert store;
			BL_ClientList__mdt clientList = [SELECT DeveloperName, Id FROM BL_ClientList__mdt WHERE DeveloperName = 'Birthday_Wedding_Anniversary'];
			blClient.me = (BL_UserInfo) Type.forName('BL_ICON_UserInfo').newInstance();
			blClient.pathParameters = new Map < String, String > {
				'id' => clientList.Id
			};
			blClient.queryParams = new Map < String, String > ();
			Test.startTest();
			blClient.resource = 'members';
			blClient.executeGET();
			blClient.isStandardRestApiRequired = true;
			blClient.PageSize = 200;
			blClient.pageIndex = 0;
			blClient.executeGET();
			Test.stopTest();
		} catch (Exception e) {}
	}
	@isTest
	static void testMethodGetMembersOfPermanentClientListWithParams() {
		try {
			Account acc = new Account(LastName = 'test');
			insert acc;
			BL_AppSettings.setAppSettings('Icon');
			BL_ICON_ClientList blClient = new BL_ICON_ClientList();
			User u = IC_Test_Common.prepareTestUser('System Administrator');
			u.DefaultStore__c = '1234';
			insert u;
			Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
			insert store;
			BL_ClientList__mdt clientList = [SELECT DeveloperName, Id FROM BL_ClientList__mdt WHERE DeveloperName = 'Reassigned'];
			blClient.me = (BL_UserInfo) Type.forName('BL_ICON_UserInfo').newInstance();
			blClient.pathParameters = new Map < String, String > {
				'id' => clientList.Id
			};
			blClient.queryParams = new Map < String, String > {
				'tab' => '1',
				'storeCode' => 'A06'
			};
			Test.startTest();
			blClient.resource = 'members';
			blClient.executeGET();
			blClient.isStandardRestApiRequired = true;
			blClient.PageSize = 200;
			blClient.pageIndex = 0;
			blClient.executeGET();
			Test.stopTest();
		} catch (Exception e) {}
	}
}