force-app/main/default/objects/Account/fields/ProspectForDream__c.field-meta.xml
<CustomField>
    <fullName>ProspectForDream__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean that indicates if a prospect is new or has been modified (except by DREAM). Set to 1 when a user creates or modifies it. When DREAM retrieves the record, resets the value to 0. Not used on clients</description>
    <label>Prospect for Dream</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/WW_RMSId__c.field-meta.xml
<CustomField>
    <fullName>WW_RMSId__c</fullName>
    <description>Holds the world wild RMS id for clients that have one. This information is provided for stores coming from Xstore only</description>
    <label>WW RMS Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ApplicationSource__c.field-meta.xml
<CustomField>
    <fullName>ApplicationSource__c</fullName>
    <description>Application where the opportunity is created : PERSO / SPO (Special Order) / ECO (ecommerce LV.com)</description>
    <label>Application Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SPO</fullName>
            </value>
            <value>
                <fullName>PERSO</fullName>
            </value>
            <value>
                <fullName>ECO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_BaseSKURefmodelSKU__c.field-meta.xml
<CustomField>
    <fullName>SPO_BaseSKURefmodelSKU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Base SKU (Ref. model SKU)</label>
    <referenceTo>ProductReferential__c</referenceTo>
    <relationshipLabel>Brief</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>SPO_DisplayOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_Exo__c.field-meta.xml
<CustomField>
    <fullName>SPO_Exo__c</fullName>
    <label>Exo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_LiningInteriorMaterial2__c.field-meta.xml
<CustomField>
    <fullName>SPO_LiningInteriorMaterial2__c</fullName>
    <label>Lining (interior) Material 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPO_CreationType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agneau</fullName>
            </value>
            <value>
                <fullName>Chevre</fullName>
            </value>
            <value>
                <fullName>Microfibre</fullName>
            </value>
            <value>
                <fullName>Mouton</fullName>
            </value>
            <value>
                <fullName>Velours</fullName>
            </value>
            <value>
                <fullName>Vgv</fullName>
            </value>
            <value>
                <fullName>Vuittonite</fullName>
            </value>
            <value>
                <fullName>Other (free text)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_OrderType__c.field-meta.xml
<CustomField>
    <fullName>SPO_OrderType__c</fullName>
    <label>Order type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPO_ProductCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Creation (Hardsided &amp; Soft)</fullName>
            </value>
            <value>
                <fullName>MTO on Catalog (Hardsided)</fullName>
            </value>
            <value>
                <fullName>SPO/MTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>SPO_ProductCategory__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hardsided leather goods</fullName>
            </value>
            <value>
                <fullName>Softsided leather goods</fullName>
            </value>
            <value>
                <fullName>Belts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_Store__c.field-meta.xml
<CustomField>
    <fullName>SPO_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCatalogue__c/fields/ProductReferential__c.field-meta.xml
<CustomField>
    <fullName>ProductReferential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to ProductReferential. Lookup needed to get some information provided by ProductReferential object (SAP) and not in BCC (ETL / sku.json)</description>
    <label>Product Referential</label>
    <referenceTo>ProductReferential__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductReferential__c/ProductReferential__c.object-meta.xml
<CustomObject>
    <description>All information about base product</description>
    <label>Product Referential</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Referential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductReferential__c/fields/SKUCode__c.field-meta.xml
<CustomField>
    <fullName>SKUCode__c</fullName>
    <externalId>true</externalId>
    <label>Base SKU Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SO_Settings__c/SO_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SO Settings</label>
</CustomObject>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/User/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SO_OpportunitySPAController_TEST.cls
@isTest
public with sharing class SO_OpportunitySPAController_TEST {
    @TestSetup
    static void init() {
        Store__c st = LV_TestFactory.createStore('LV TEST STORE MIY', 'Store', 'A00', 'FRANCE', 'EUR', 'Open');
		st.MANAGEMENT_ZONE_LEVEL__c = '15';
		insert st;

		Account client = LV_TestFactory.createAccount();
        insert client;

        Profile p = [SELECT id FROM profile WHERE id=:IC_Utils.getSAProfile()];
        User u = new User(Alias = 'Tester', Email = 'adminUser@testlv.com',
				EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
				LocaleSidKey = 'en_US', ProfileId = p.Id,
				TimeZoneSidKey = 'America/Los_Angeles', UserName = 'adminUser@testlv.com');
        insert u;

        Opportunity mypOrder = LV_TestFactory.createOrder('MY Neverfull bag', 'Creation in progress', null, st.id, client.id, null, null, 'PERSO');
        mypOrder.ownerId = u.Id;
        insert mypOrder;
        
        SO_Settings__c setting = new SO_Settings__c(Name='NewOpportunityCloseDate', Value__c='0');
        insert setting;
        SO_Settings__c setting1 = new SO_Settings__c(Name='DummyProduct', Value__c='1');
        insert setting1;
        
        // ProductCatalogue__c pc = LV_TestFactory.createProductCatalog('MY NEVERFULL', 'P0001', 3, 15, 5, 'Leather Goods');
        // insert pc;
        
        ProductReferential__c pr = LV_TestFactory.createProductReferential('MY PRODUCT REF', 'P0001');
        insert pr;
    }
    
    @isTest
    static void test_getMethodes() {
        SO_OpportunitySPAController.getUser();
        SO_OpportunitySPAController.getStoreJson();
        SO_OpportunitySPAController.getSPAPersonalizationJson();
        SO_OpportunitySPAController.getUserProfile();
        SO_OpportunitySPAController.getSessionId();
        SO_OpportunitySPAController.getProductNotFound();
        SO_OpportunitySPAController.getIsMTOEnabled();
        SO_OpportunitySPAController.getNewFile();
        // SO_OpportunitySPAController.getAllUsersDB();
        SO_OpportunitySPAController.getOrderSettings();
        SO_OpportunitySPAController.getDummyProductDB();
    }

    @isTest
    static void test_saveOppWithFiles() {
        Account client = [SELECT Id, IsProspect__pc, ProspectForDream__c FROM Account LIMIT 1];
        Store__c st = [SELECT Id FROM Store__c LIMIT 1];
        User user = [SELECT Id FROM User LIMIT 1];

        Date closeDate = System.today().adddays(100);
		Opportunity opp1 = new Opportunity(Name = 'test',
											StageName = 'Creation in progress',
											ApplicationSource__c = 'SPO',
											SPO_BaseSKURefmodelSKU__c = null, // for SPO only
											AccountId = client.id, // for non display order
											SPO_Store__c = st.id,
											SPO_OrderType__c = null, // for SPO only
											SPO_ProductCategory__c = null, // for SPO only
                                            CloseDate = closeDate,
                                            ownerId = user.Id
										);

        Opportunity order = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
        Id attachmentId1 = SO_OpportunitySPAController.createAttachment(order.Id, 'FILE_NAME', '0000000', 'jpg');

        SO_OpportunitySPAController.FileContent fileContent1 = SO_OpportunitySPAController.getNewFile(); 
        SO_OpportunitySPAController.FileContent fileContent2 = SO_OpportunitySPAController.getNewFile();
        fileContent1.base64Data = 'base64Data';
        fileContent1.contentType = 'fileContent';
        fileContent1.createdDate = System.now();
        fileContent1.fileId = attachmentId1;

        List<SO_OpportunitySPAController.FileContent> fileContentList = new List<SO_OpportunitySPAController.FileContent>{fileContent1, fileContent2};
        String listFilesJSON = JSON.serialize(fileContentList);

        Opportunity opp2 = SO_OpportunitySPAController.saveOppWithFiles(opp1, client, listFilesJSON, 'validate');

        try{
            Opportunity opp3 = SO_OpportunitySPAController.saveOppWithFiles(null, client, listFilesJSON, 'validate');
        }
        catch(Exception error){
            System.assertEquals('Script-thrown exception', error.getMessage());
        }
    }

    @isTest
    static void test_updateOpp() {
        Opportunity mypOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
        SO_OpportunitySPAController.updateOpp(mypOrder);
    }
    @isTest
    static void test_saveOpp() {
        Account client = [SELECT Id, IsProspect__pc, ProspectForDream__c FROM Account LIMIT 1];
        Store__c st = [SELECT Id FROM Store__c LIMIT 1];
        Date closeDate = System.today().adddays(100);
        
        Opportunity opp1 = new Opportunity(Name = 'test1',
                                    SPO_BaseSKURefmodelSKU__c = null, // for SPO only
                                    AccountId = client.id, // for non display order
                                    SPO_Store__c = st.id,
                                    SPO_OrderType__c = 'Creation (Hardsided & Soft)', // for SPO only
                                    SPO_ProductCategory__c = null, // for SPO only
                                    CloseDate = closeDate,
                                    SPO_DisplayOrder__c = false,
                                    SPO_LiningInteriorMaterial2__c = 'exo',
                                    SPO_Exo__c = 'Yes'
        );
        
        Opportunity opp2 = new Opportunity(Name = 'test2',
                                    SPO_BaseSKURefmodelSKU__c = null,
                                    AccountId = client.id,
                                    SPO_Store__c = st.id,
                                    SPO_ProductCategory__c = null,
                                    CloseDate = closeDate,
                                    SPO_OrderType__c = 'MTO on Catalog (Hardsided)',
                                    SPO_DisplayOrder__c = true,
                                    SPO_Exo__c = 'No'
        );

        Opportunity savedOpp1 = SO_OpportunitySPAController.saveOpp(LV_TestFactory.createOrder('MY Neverfull bag', 'Creation in progress', null, st.id, client.id, null, null, 'SPO'), client, 'validate');
        Opportunity savedOpp2 = SO_OpportunitySPAController.saveOpp(opp1, client, 'validate');
        // Opportunity savedOpp3 = SO_OpportunitySPAController.saveOpp(opp2, client, 'validate');
    }

    @isTest
    static void test_saveOpp2() {
        Account client = [SELECT Id, IsProspect__pc, ProspectForDream__c FROM Account LIMIT 1];
        Store__c st = [SELECT Id FROM Store__c LIMIT 1];
        Date closeDate = System.today().adddays(100);
        Opportunity opp4 = new Opportunity(Name = 'test4',
                                StageName = 'Creation in progress',
                                ApplicationSource__c = 'SPO',
                                SPO_BaseSKURefmodelSKU__c = null,
                                AccountId = client.id,
                                SPO_Store__c = st.id,
                                SPO_ProductCategory__c = null,
                                CloseDate = closeDate,
                                SPO_OrderType__c = 'Creation (Hardsided & Soft)'
                            );
        SO_OpportunitySPAController.saveOpp(opp4, client, 'validate and request for quataion');

    }

    @isTest
    static void test_getStore() {
        Store__c st = [SELECT Id, RetailStoreId__c FROM Store__c LIMIT 1];
        SO_OpportunitySPAController.getStore(st.RetailStoreId__c);
        SO_OpportunitySPAController.getStoreCurrency(st.RetailStoreId__c);
    }
    
    // @isTest
    // static void test_getFiles() {
    //     //Opportunity mypOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
    //     SO_OpportunitySPAController.saveTheChunk();
    // }

    @isTest
    static void test_getProductBySku() {
        ProductReferential__c pr = [SELECT id, SKUCode__c FROM ProductReferential__c LIMIT 1];
        SO_OpportunitySPAController.getProductBySku(pr.SKUCode__c);
    }
    // @isTest
    // static void test_getAccountFromRMS() { //error - to retest and correct
    //     Store__c st = [SELECT Id, RetailStoreId__c FROM Store__c LIMIT 1];
    //     Account client = [SELECT Id, RMSId__pc, WW_RMSId__c FROM Account LIMIT 1];
    //     SO_OpportunitySPAController.getAccountFromRMS(st.RetailStoreId__c, client.RMSId__pc, client.WW_RMSId__c);
    // }
    // @isTest
    // static void test_validateCACodeInRMS() { //Methods defined as TestMethod do not support Web service callouts !!
    //     Store__c st = [SELECT Id, RetailStoreId__c FROM Store__c LIMIT 1];
    //     //Account client = [SELECT Id, RMSId__pc, WW_RMSId__c FROM Account LIMIT 1];
    //     SO_OpportunitySPAController.validateCACodeInRMS(st.RetailStoreId__c, 'test');
    // }
    @isTest
    static void test_findOppById() {
        Opportunity mypOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
        SO_OpportunitySPAController.findOppById(mypOrder.Id);
        Account client = [SELECT Id, RMSId__pc, WW_RMSId__c FROM Account LIMIT 1];
        SO_OpportunitySPAController.saveAccountInRMS(client, 'test');
    }
    @isTest
    static void test_saveTheChunk() {
        Opportunity order = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
        SO_OpportunitySPAController.saveTheChunk(order.Id, 'FILE_NAME', '0000000', 'jpg', '');
    }
    @isTest
    static void test_createAttachment() {
        Opportunity order = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
        SO_OpportunitySPAController.createAttachment(order.Id, 'FILE_NAME', '0000000', 'jpg');
    }

    @isTest //test
    static void test_appendToFile() {
        Opportunity order = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];

        //------------------------------------
        //Attachment myAtt = new Attachment();
        Blob b = Blob.valueOf('Test Data');
        Attachment myAtt = new Attachment(ParentId = order.Id, Name = 'Test_Attachment', Body = b);
        insert myAtt;
        //Attachment attachment = [SELECT id, name FROM Attachment LIMIT 1];
        //BL_AccountFileUpload controller=new BL_AccountFileUpload(new ApexPages.StandardController(acc));
        //controller.fileName='Unit Test Attachment';
        //controller.fileBody=Blob.valueOf('Unit Test Attachment Body');
        //controller.uploadFile();
        //List<Attachment> attachments=[select id, name from Attachment where parent.id=:acc.id];
        //System.assertEquals(1, attachments.size());
        //-----------------------------------

        SO_OpportunitySPAController.saveTheChunk(order.Id, 'FILE_NAME', '0000000', 'jpg', myAtt.Id);
        SO_OpportunitySPAController.getFiles(order);
    }
    @isTest
    static void test_getFiles() {
        Opportunity order = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
        //ContentDocument cd = new ContentDocument();
        //insert cd;
        //ContentDocumentLink cdl = new ContentDocumentLink(LinkedEntityId = order.Id, ContentDocumentId = cd.Id);
        //insert cdl;
        
        //SO_OpportunitySPAController.getFiles(order);

        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;
        
        List<ContentVersion> docs = [Select Id,ContentDocumentId, Title From ContentVersion where Id =:cv.Id];
        ContentDocumentLink contentLink = new ContentDocumentLink();
        contentLink.LinkedEntityId = order.id;
        contentLink.ContentDocumentId = docs[0].ContentDocumentId;
        contentLink.ShareType = 'V';
        insert contentLink;

        SO_OpportunitySPAController.getFiles(order);
    }
    
    // @isTest //test
    // static void test_retrievePricesFromRMS() { //Methods defined as TestMethod do not support Web service callouts !!
    //     Store__c st = [SELECT Id, RetailStoreId__c FROM Store__c LIMIT 1];
    //     Account client = [SELECT Id, RMSId__pc, WW_RMSId__c FROM Account LIMIT 1];
    //     SO_OpportunitySPAController.retrievePricesFromRMS(st.RetailStoreId__c, client.RMSId__pc);
    // }
}