force-app/main/default/objects/Account/fields/ProspectForDream__c.field-meta.xml
<CustomField>
    <fullName>ProspectForDream__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Boolean that indicates if a prospect is new or has been modified (except by DREAM). Set to 1 when a user creates or modifies it. When DREAM retrieves the record, resets the value to 0. Not used on clients</description>
    <label>Prospect for Dream</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>20HeCard</fullName>
            </value>
            <value>
                <fullName>20MDeCard</fullName>
            </value>
            <value>
                <fullName>Client Service</fullName>
            </value>
            <value>
                <fullName>DREAM</fullName>
            </value>
            <value>
                <fullName>Identity</fullName>
            </value>
            <value>
                <fullName>KBRW</fullName>
            </value>
            <value>
                <fullName>Line</fullName>
            </value>
            <value>
                <fullName>LineTaiwan</fullName>
            </value>
            <value>
                <fullName>LineThai</fullName>
            </value>
            <value>
                <fullName>LV&amp;exhiJap</fullName>
            </value>
            <value>
                <fullName>LV App</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>MyCC</fullName>
            </value>
            <value>
                <fullName>MyLV</fullName>
            </value>
            <value>
                <fullName>MyRepairs</fullName>
            </value>
            <value>
                <fullName>On App</fullName>
            </value>
            <value>
                <fullName>Online Appt</fullName>
            </value>
            <value>
                <fullName>WeChat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/TECH_CandidateToDeletion__c.field-meta.xml
<CustomField>
    <fullName>TECH_CandidateToDeletion__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Accounts with CandidateToDeletion = true are sent to Dream for deletion. It concerns Accounts from Online Appointment.
Dream checks if OK to delete the account, if yes, Dream update field ToDelete to true in SF and deletion batch is launched.</description>
    <label>TECH_CandidateToDeletion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Appointments.recordType-meta.xml
<RecordType>
    <fullName>Appointments</fullName>
    <active>true</active>
    <description>Creation of your appointments</description>
    <label>Appointments</label>
</RecordType>

force-app/main/default/objects/Event/recordTypes/Online_Appointment.recordType-meta.xml
<RecordType>
    <fullName>Online_Appointment</fullName>
    <active>true</active>
    <label>Online Appointment</label>
</RecordType>

force-app/main/default/classes/BatchAccountFromOSA.cls
/*
VB 22/04/2021
Update all user that have taken an OSA 30 days earlier if:
- the user has no cases
- the user has no other appointments
- the user is IsProspect__pc = true and Source__c ='On App' and Date_Identity__pc = null

if user can be contacted by email --> delete phone number and send to dream.
if user cannot be contacted by email --> send to dream as candidate to deletion.

To run the batch:
BatchAccountFromOSA bscl = new BatchAccountFromOSA();
Database.executeBatch(bscl, 10);
*/

global class BatchAccountFromOSA implements Database.Batchable<sObject> {
    
    private String myQuery;
    
    public BatchAccountFromOSA() {
        myQuery = 'select id, AccountId, ActivityDate from event where Recordtype.DeveloperName=\'Online_Appointment\'  and activityDate = :dt';
    }
    
    public List<sObject> start(Database.BatchableContext BC){
        Date dt = System.today().addDays(-30);
        System.debug(myQuery);
        List<Event> ev = Database.query(myQuery);
        System.debug(ev.size());
        return ev;
    }
    
    public void execute(Database.BatchableContext info, List<sObject> scope){
        Set<Id> acc = setAccounts(scope);
        List<Account> accList = getAcc(acc);
        if(accList.size()>0) {
            for (Account a: accList) {
                if (a.Can_Be_Contacted_By_Email__pc == false) {
                    a.ProspectForDream__c = true;
                    a.TECH_CandidateToDeletion__c = true;
                } else {
                    a.PersonMobilePhone = null;
                    a.ProspectForDream__c = true;
                }
            }
            system.debug('FINAL LIST SIZE '+accList.size());
            DateTime qryStart = DateTime.now();
        	update accList;
            DateTime qryEnd = DateTime.now();
        	system.debug(qryStart+' / '+qryEnd);
            
        }  
    }
    
    global void finish(Database.BatchableContext CD){
        
    }
    
    private Set<Id> setAccounts(List<Event> ev) {
        system.debug('SetAccounts started');
        Set<Id> acc = new Set<Id>();
        if(ev.size()>0){
            for (Event e: ev) {
                if(String.isNotBlank(e.AccountId)){
                    acc.add(e.AccountId);
                }
            }
        }
        system.debug('accountAtStart: '+acc.size());
        
        List<Case> cases = getCases(acc);
        if(cases.size()>0){
            for (Case e: cases) {
                if (acc.contains(e.AccountId)) {
                    acc.remove(e.AccountId);
                }
            }
        }
        
        system.debug('accountAfterCases: '+acc.size());
        
        List<Event> events = getApps(acc);
        for (Event e: events) {
            if (acc.contains(e.AccountId)) {
                acc.remove(e.AccountId);
            }
        }
        
        system.debug('accountWithoutCaseOrApp: '+acc.size());
        return acc;
    }
    
    private List<Account> getAcc(Set<Id> acc) {
        DateTime qryStart = DateTime.now();
        List<Account> acct = [SELECT Id, Can_Be_Contacted_By_Email__pc FROM Account WHERE Id in :acc and IsProspect__pc = true and Source__c ='On App' and Date_Identity__pc = null];
        DateTime qryEnd = DateTime.now();
        system.debug(qryStart+' / '+qryEnd);
        return acct; 
    }
    
    private List<Case> getCases(Set<Id> acc) {
        List<Case> cas = [SELECT Id, AccountId FROM Case WHERE  AccountId IN :acc and isClosed = False];
        return cas; 
    }
    
    private List<event> getApps(Set<Id> acc) {
        Date dt = System.today().addDays(-30);
        system.debug(dt);
        List<event> evt = [SELECT Id, AccountId FROM event WHERE  AccountId IN :acc and activityDate > :dt];
        return evt; 
    }
}