force-app/main/default/objects/Account/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/User/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <externalId>true</externalId>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BL_JOURNEY_Appointment_TEST.cls
@isTest
public with sharing class BL_JOURNEY_Appointment_TEST {
   
    @isTest
    static void testMethodGet(){
    
        BL_AppSettings.setAppSettings('Journey');
        
        User u = IC_Test_Common.prepareTestUser('System Administrator');
        u.WWEmployeeNumber__c = 'w123';
        insert u;

        Store__c store = new Store__c(Name = 'test', RetailStoreId__c = 'A06');
		insert store;
        
        system.runAs(u){

            DateTime currentDT = System.now();
            String strUnixTimeStamp = String.valueof( currentDT.getTime() );


            Account acc = IC_TestFactory.createAccount();
            insert acc;
            Event ev = IC_TestFactory.createEvent(acc);
            ev.startDatetime = currentDT;
            ev.Store_Location__c = store.Id;
    
            Event ev2 = IC_TestFactory.createEvent(acc);
            ev.startDatetime = currentDT;
            ev.Store_Location__c = store.Id;

            insert new List<Event> {ev, ev2};

            Test.startTest();
            BL_JOURNEY_Appointment journeyAppointment = new BL_JOURNEY_Appointment();
      
            journeyAppointment.queryParams =  new Map<String, String> {'storeCode' =>'A06', 
                                                             'from' =>  strUnixTimeStamp, 
                                                             'to' => strUnixTimeStamp, 
                                                             'caUniqueId'=>'w123'};
            

            try{journeyAppointment.executeGET();}
            catch(Exception e){}

            Test.stopTest();
        }
    }
}