force-app/main/default/objects/Account/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/IsTechnicalUser__c.field-meta.xml
<CustomField>
    <fullName>IsTechnicalUser__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Client Visibility development - true if user is a technical user used as owner for unassigned clients</description>
    <label>Is Technical User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <externalId>true</externalId>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Wecome_MP_Manager_Notif_Batch_TEST.cls
@IsTest
public with sharing class Wecome_MP_Manager_Notif_Batch_TEST {
    @IsTest static void testNotifBatch() {
		User u = IC_Test_Common.prepareTestUser('ICON_SA');
        u.DefaultStore__c = '1234';
        u.WWEmployeeNumber__c='AAAA';
        u.IsTechnicalUser__c= true;
        insert u;
        system.runAs(u){
        Account acc = IC_Test_Common.createAccount('12345');
        acc.isProspect__pc = false;
        acc.AttachedStore__pc = '1234';
        update acc;

        Test.startTest();

        Wecome_MP_Manager_Notification_Batch batch = new Wecome_MP_Manager_Notification_Batch('Id = \''+ UserInfo.getUserId()+'\'');
        Database.executeBatch(batch);

        Test.stopTest();
        }
    }
}