force-app/main/default/objects/Account/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Answer__c/due__Diduenjoy_Answer__c.object-meta.xml
<CustomObject>
    <label>Diduenjoy Answer</label>
    <nameField>
        <label>Diduenjoy Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diduenjoy Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/due__Diduenjoy_Answer__c/fields/due__Diduenjoy_Feedback__c.field-meta.xml
<CustomField>
    <fullName>due__Diduenjoy_Feedback__c</fullName>
    <label>Diduenjoy Feedback</label>
    <referenceTo>due__Diduenjoy_Feedback__c</referenceTo>
    <relationshipLabel>Diduenjoy Answers</relationshipLabel>
    <relationshipName>Diduenjoy_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/due__Diduenjoy_Feedback__c.object-meta.xml
<CustomObject>
    <label>Diduenjoy Feedback</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Diduenjoy Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__CreatedAt__c.field-meta.xml
<CustomField>
    <fullName>due__CreatedAt__c</fullName>
    <label>CreatedAt</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__InternalId__c.field-meta.xml
<CustomField>
    <fullName>due__InternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>InternalId</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Permalink__c.field-meta.xml
<CustomField>
    <fullName>due__Permalink__c</fullName>
    <label>Permalink</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/due__Diduenjoy_Feedback__c/fields/due__Profile__c.field-meta.xml
<CustomField>
    <fullName>due__Profile__c</fullName>
    <label>Profile</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <externalId>true</externalId>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VO_Survey__c/VO_Survey__c.object-meta.xml
<CustomObject>
    <label>Voice</label>
    <nameField>
        <displayFormat>Survey-{00000000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DUE_AnswerTriggerHandler_TEST.cls
@isTest
public class DUE_AnswerTriggerHandler_TEST {
    @isTest
    static void testMethodSetup(){
        Account acc = new Account(LastName = 'test');
		insert acc;
        User u = IC_Test_Common.prepareTestUser('System Administrator');
		u.DefaultStore__c = '1234';
        u.DefaultStore__c = 'A06';
        u.WWEmployeeNumber__c = 'WW198765467';
		insert u;
        
        due__Diduenjoy_Feedback__c feed = new due__Diduenjoy_Feedback__c();
        feed.due__InternalId__c = '12345';
        feed.due__CreatedAt__c = Date.today();
        feed.due__Permalink__c  = 'www.test.com';
        feed.due__Profile__c = 'testProfile';
        insert feed;
        
        VO_Survey__c survey = new VO_Survey__c();
        
        
        system.runAs(u) {
            Test.startTest();
            due__Diduenjoy_Answer__c ans = new due__Diduenjoy_Answer__c();
        ans.due__Step__c = 1;
        ans.due__Position__c = 0;
        ans.due__Diduenjoy_Feedback__c = feed.id;
            ans.due__Question__c = 'question';
            ans.due__Question_Type__c = 'rating';
            ans.due__Score__c = 4;
            insert ans;
            
            ans.due__Score__c = 3;
            update ans;
            Test.stopTest();
        }
        
    }

}