force-app/main/default/objects/Account/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <errorMessage>You can&apos;t select a closed store.</errorMessage>
        <filterItems>
            <field>Store__c.Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <filterItems>
            <field>Store__c.Status__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>$User.BypassVR__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <label>Tag</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <externalId>true</externalId>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BL_ICON_Tags_TEST.cls
@istest
public with sharing class BL_ICON_Tags_TEST {
    @TestSetup
    static void createTestData() {
        

        Account acc =  IC_TestFactory.createAccount();
        insert acc;
        Case request = IC_TestFactory.createCase(acc);
        insert request ; 
        User u = IC_Test_Common.prepareTestUser('System Administrator');
        u.DefaultStore__c = 'A06';
        u.WWEmployeeNumber__c = 'WW198765467';
        insert u;


    }

    
	@isTest
    static void testGetTags(){
        
      
        BL_AppSettings.setAppSettings('Icon');
        BL_ICON_Tags blTags = new BL_ICON_Tags();
        
        //BL_ICON_Tags blTags = new BL_ICON_Tags();

        BL_WS_Router.clientPlatform = 'WECHAT';

        Account acc = [SELECT id FROM Account  LIMIT 1];
        User u = [SELECT id,DefaultStore__c FROM user WHERE WWEmployeeNumber__c = 'WW198765467'];
        system.runAs(u){
            
            Store__c store = new Store__c(Name = 'LV Paris', RetailStoreId__c = u.DefaultStore__c);
            insert store;
            blTags.me = (BL_UserInfo)Type.forName('BL_ICON_UserInfo').newInstance();
            blTags.queryParams = new Map<String, String>();
           
           
            Test.startTest();
                blTags.pathParameters = new Map<String, String>{'clientId' =>acc.Id};
                blTags.executeGET();
            Test.stopTest();
        }

    }
    
    @isTest
    static void testPostTags(){
      
        Tag__c tag = new Tag__c();
        insert tag;

        BL_AppSettings.setAppSettings('Icon');
        BL_ICON_Tags blTags = new BL_ICON_Tags();
        
        User u = [SELECT id,DefaultStore__c FROM user Where WWEmployeeNumber__c = 'WW198765467'];
        system.runAs(u){
            
            Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
            insert store;
            blTags.me = (BL_UserInfo)Type.forName('BL_ICON_UserInfo').newInstance();
            blTags.queryParams = new Map<String, String>();
           
           
            Test.startTest();
               String bodyString = '{"records":[{"externalId":"test-send","tagid":"fd466c84a814f9dc1d4b65d4c63f9e2d","tagid_db":"fd466c84a814f9dc1d4b65d4c63f9e2d","type_value":"client_basic","type_label_db":"人的特征","type_label_mp":"备注","dimension_value":"gender","dimension_label_mp":"性别","dimension_label_db":"性别","tag_value":"","tag_label_mp":"","tag_label_db":"女性","intention_label_db":"","relation_value":"client-self","relation_label_db":"本人","relation_label_mp":"本人","relation_color_mp":"black","future_key_dates":[]}]}';
               blTags.requestBody = (Map<String, Object>)JSON.deserializeUntyped(bodyString);
               blTags.executePOST();
            Test.stopTest();
        }
    }


    @isTest
    static void testDeleteTags(){

        // Tag__c tag = new Tag__c();
        // insert tag;
      
        BL_AppSettings.setAppSettings('Icon');
        BL_ICON_Tags blTags = new BL_ICON_Tags();
        
        User u = [SELECT id,DefaultStore__c FROM user Where WWEmployeeNumber__c = 'WW198765467'];
        system.runAs(u){
            
            Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
            insert store;
            blTags.me = (BL_UserInfo)Type.forName('BL_ICON_UserInfo').newInstance();
            blTags.queryParams = new Map<String, String>();
           
           
            Test.startTest();
               // blTags.pathParameters = new Map<String, String>{'tagsId' =>tag.Id};

               // blTags.executeDELETE();
            Test.stopTest();
        }
    }
}