force-clientforce/main/default/objects/C360_Logs__c/C360_Logs__c.object-meta.xml
<CustomObject>
    <label>C360_Logs</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>C360_Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>C360_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/C360_Logs__c/fields/TR_Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>TR_Apex_Class__c</fullName>
    <label>Apex Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TR_C360_IntegrationManager_Utils</fullName>
            </value>
            <value>
                <fullName>apex_class_TEST</fullName>
            </value>
            <value>
                <fullName>TR_IntegrationManagerHandler</fullName>
            </value>
            <value>
                <fullName>TECH_C360_Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_APEX_Limits__c.field-meta.xml
<CustomField>
    <fullName>TR_APEX_Limits__c</fullName>
    <label>APEX Limits</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_Application__c.field-meta.xml
<CustomField>
    <fullName>TR_Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>C360</fullName>
            </value>
            <value>
                <fullName>C360_EVENT_LOG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-clientforce/main/default/objects/C360_Logs__c/fields/TR_Duration__c.field-meta.xml
<CustomField>
    <fullName>TR_Duration__c</fullName>
    <label>Duration</label>
    <precision>17</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_Error__c.field-meta.xml
<CustomField>
    <fullName>TR_Error__c</fullName>
    <label>Error</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-clientforce/main/default/objects/C360_Logs__c/fields/TR_EventUuidLog__c.field-meta.xml
<CustomField>
    <fullName>TR_EventUuidLog__c</fullName>
    <externalId>true</externalId>
    <label>EventUuidLog</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_Has_Error__c.field-meta.xml
<CustomField>
    <fullName>TR_Has_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_JSON__c.field-meta.xml
<CustomField>
    <fullName>TR_JSON__c</fullName>
    <label>JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_Level__c.field-meta.xml
<CustomField>
    <fullName>TR_Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_Message__c.field-meta.xml
<CustomField>
    <fullName>TR_Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_Object_Type__c.field-meta.xml
<CustomField>
    <fullName>TR_Object_Type__c</fullName>
    <label>Object_Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>C360_Tech_Event_Return_Flow__e</fullName>
            </value>
            <value>
                <fullName>TECH_IntegrationManager__c</fullName>
            </value>
            <value>
                <fullName>C360_Tech_Event__e</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-clientforce/main/default/objects/C360_Logs__c/fields/TR_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>TR_Record_Id__c</fullName>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/C360_Logs__c/fields/TR_Type__c.field-meta.xml
<CustomField>
    <fullName>TR_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incoming_flow</fullName>
            </value>
            <value>
                <fullName>Outgoing_flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-clientforce/main/default/objects/TR_Integration_Manager_Setting__c/TR_Integration_Manager_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TR_Integration_Manager_Setting</label>
</CustomObject>

force-clientforce/main/default/objects/TR_Integration_Manager_Setting__c/fields/Created_Before_Days__c.field-meta.xml
<CustomField>
    <fullName>Created_Before_Days__c</fullName>
    <label>Created Before Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/BypassVR__c.field-meta.xml
<CustomField>
    <fullName>BypassVR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/BypassWF__c.field-meta.xml
<CustomField>
    <fullName>BypassWF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Workflow Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ARGENTINA</fullName>
            </value>
            <value>
                <fullName>ARUBA</fullName>
            </value>
            <value>
                <fullName>AUSTRALIA</fullName>
            </value>
            <value>
                <fullName>AUSTRIA</fullName>
            </value>
            <value>
                <fullName>BAHRAIN</fullName>
            </value>
            <value>
                <fullName>BARBADE</fullName>
            </value>
            <value>
                <fullName>BELGIUM</fullName>
            </value>
            <value>
                <fullName>BRAZIL</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
            <value>
                <fullName>CHILE</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>COLOMBIA</fullName>
            </value>
            <value>
                <fullName>CYPRUS</fullName>
            </value>
            <value>
                <fullName>CZECH REPUBLIC</fullName>
            </value>
            <value>
                <fullName>DENMARK</fullName>
            </value>
            <value>
                <fullName>DOMINICAIN REPUBLIC</fullName>
            </value>
            <value>
                <fullName>FINLAND</fullName>
            </value>
            <value>
                <fullName>FRANCE</fullName>
            </value>
            <value>
                <fullName>GERMANY</fullName>
            </value>
            <value>
                <fullName>GREECE</fullName>
            </value>
            <value>
                <fullName>GUAM</fullName>
            </value>
            <value>
                <fullName>HONG KONG</fullName>
            </value>
            <value>
                <fullName>HUNGARY</fullName>
            </value>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>INDONESIA</fullName>
            </value>
            <value>
                <fullName>IRELAND</fullName>
            </value>
            <value>
                <fullName>ISRAEL</fullName>
            </value>
            <value>
                <fullName>ITALY</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>JORDANIE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TR_BatchC360LogPurge_TEST.cls
/**
* @File Name          : TR_BatchC360LogPurge_TEST.cls
* @Description        : 
* @Author             : Imad.alsidchikh.ext@louisvuitton.com
* @Group              : 
* @Last Modified By   : Imad.alsidchikh.ext@louisvuitton.com
* @Last Modified On   : 01-12-2022
* @Modification Log   : 
* Ver       Date            Author      		                     Modification
* 1.0       01-12-2022      Imad.alsidchikh.ext@louisvuitton.com     Initial Version
**/
@isTest
private class TR_BatchC360LogPurge_TEST {
    @TestSetup
    static void setup() {
        List<C360_Logs__c> testLogs = new List<C360_Logs__c>();
        C360_Logs__c   log = new C360_Logs__c(
            TR_Apex_Class__c = 'apex_class_TEST',
            TR_APEX_Limits__c = 'apex_Limits',
            TR_Application__c = 'C360',
            TR_Duration__c = 2 ,
            TR_Error__c = 'error_Message',
            TR_EventUuidLog__c = 'eventUuidLog',
            TR_Has_Error__c  = true,
            TR_JSON__c = 'json',
            TR_Level__c = 'ERROR',
            TR_Message__c = 'logMessage',
            TR_Object_Type__c = 'ACCOUNT',
            TR_Record_Id__c = 'record_Id',
            TR_Type__c = 'Outgoing_flow'
        );
        testLogs.add(log);
        C360_Logs__c   log1 = new C360_Logs__c(
            TR_Apex_Class__c = 'apex_class_TEST',
            TR_APEX_Limits__c = 'apex_Limits',
            TR_Application__c = 'C360',
            TR_Duration__c = 2 ,
            TR_Error__c = '',
            TR_EventUuidLog__c = 'eventUuidLog',
            TR_Has_Error__c  = false,
            TR_JSON__c = 'json',
            TR_Level__c = 'DEBUG',
            TR_Message__c = 'logMessage',
            TR_Object_Type__c = 'ACCOUNT',
            TR_Record_Id__c = 'record_Id',
            TR_Type__c = 'Outgoing_flow'
        );
        testLogs.add(log1);
        C360_Logs__c   log2 = new C360_Logs__c(
            TR_Apex_Class__c = 'apex_class_TEST',
            TR_APEX_Limits__c = 'apex_Limits',
            TR_Application__c = 'C360',
            TR_Duration__c = 2 ,
            TR_Error__c = 'error_Message',
            TR_EventUuidLog__c = 'eventUuidLog',
            TR_Has_Error__c  = true,
            TR_JSON__c = 'json',
            TR_Level__c = 'ERROR',
            TR_Message__c = 'logMessage',
            TR_Object_Type__c = 'ACCOUNT',
            TR_Record_Id__c = 'record_Id',
            TR_Type__c = 'Outgoing_flow'
        );
        testLogs.add(log2);
        C360_Logs__c   log3 = new C360_Logs__c(
            TR_Apex_Class__c = 'apex_class_TEST',
            TR_APEX_Limits__c = 'apex_Limits',
            TR_Application__c = 'C360',
            TR_Duration__c = 2 ,
            TR_Error__c = '',
            TR_EventUuidLog__c = 'eventUuidLog',
            TR_Has_Error__c  = false,
            TR_JSON__c = 'json',
            TR_Level__c = 'INFO',
            TR_Message__c = 'logMessage',
            TR_Object_Type__c = 'ACCOUNT',
            TR_Record_Id__c = 'record_Id',
            TR_Type__c = 'Outgoing_flow'
        );
        testLogs.add(log3);
        C360_Logs__c   log4 = new C360_Logs__c(
            TR_Apex_Class__c = 'apex_class_TEST',
            TR_APEX_Limits__c = 'apex_Limits',
            TR_Application__c = 'C360',
            TR_Duration__c = 2 ,
            TR_Error__c = '',
            TR_EventUuidLog__c = 'eventUuidLog',
            TR_Has_Error__c  = false,
            TR_JSON__c = 'json',
            TR_Level__c = 'DEBUG',
            TR_Message__c = 'logMessage',
            TR_Object_Type__c = 'ACCOUNT',
            TR_Record_Id__c = 'record_Id',
            TR_Type__c = 'Outgoing_flow'
        );
        testLogs.add(log4);
        insert testLogs;
        TR_Integration_Manager_Setting__c setting = new TR_Integration_Manager_Setting__c();
        setting.Name = 'Batch_C360_log';
        setting.Created_Before_Days__c=0;
        insert setting; 
        
    }
    @isTest
    static void testBatch() {	
        User AdminTest = ICX_TestFactory.createUser(ICX_TestFactory.PROFILE_SYSTEM_ADMINNISTRATOR);
        AdminTest.BypassWF__c = true;
        AdminTest.BypassVR__c = true;
        AdminTest.Country__c = 'FRANCE';
        insert AdminTest;
        System.runAs(AdminTest) {
            List<C360_Logs__c> logRecords = [SELECT Id FROM C360_Logs__c];
            System.assertEquals(5,logRecords.size());
            TR_C360LogPurge_Scheduler myScheduler = new TR_C360LogPurge_Scheduler();
            String sch = '0 0 23 L * ?';
            Test.startTest();
            system.schedule('Test check', sch, myScheduler);
            myScheduler.execute(null);
            Test.stopTest();
            List<C360_Logs__c> techRecords2 = [SELECT Id FROM C360_Logs__c];
            System.assertEquals(0,techRecords2.size());
        }
    }    
}