force-app/main/default/objects/Auth_Provider__mdt/fields/Authorize_Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Authorize_Endpoint_URL__c</fullName>
    <label>Authorize Endpoint URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Auth_Provider__mdt/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Auth_Provider__mdt/fields/Token_Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Token_Endpoint_URL__c</fullName>
    <label>Token Endpoint URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Auth_Provider__mdt/fields/User_Info_Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>User_Info_Endpoint_URL__c</fullName>
    <label>User Info Endpoint URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, list all categories for Perso menus.</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IDENTITY_Settings__c/IDENTITY_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>IDENTITY - Settings</label>
</CustomObject>

force-app/main/default/objects/Logs__c/Logs__c.object-meta.xml
<CustomObject>
    <label>Logs</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logs__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <label>Apex Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Akamai_API</fullName>
            </value>
            <value>
                <fullName>ATG_API</fullName>
            </value>
            <value>
                <fullName>Ctrl_ProductCatalog</fullName>
            </value>
            <value>
                <fullName>Fractalist_API</fullName>
            </value>
            <value>
                <fullName>Google_Analytics_API</fullName>
            </value>
            <value>
                <fullName>ICX_GenesysExtensionPoint</fullName>
            </value>
            <value>
                <fullName>ICX_PurchasesExport</fullName>
            </value>
            <value>
                <fullName>ICX_WS_Client360</fullName>
            </value>
            <value>
                <fullName>ICX_WS_IXOPAY</fullName>
            </value>
            <value>
                <fullName>ICX_WS_Manual_Merge</fullName>
            </value>
            <value>
                <fullName>ICX_WS_NewsletterSubscription</fullName>
            </value>
            <value>
                <fullName>IDENTITY_AccountMatching_Utils</fullName>
            </value>
            <value>
                <fullName>IDENTITY_Login_CTRL</fullName>
            </value>
            <value>
                <fullName>IDENTITY_Registration_CTRL</fullName>
            </value>
            <value>
                <fullName>IDENTITY_RegistrationHandler</fullName>
            </value>
            <value>
                <fullName>IDENTITY_URLRewriter</fullName>
            </value>
            <value>
                <fullName>IDENTITY_UserManagement_BATCH</fullName>
            </value>
            <value>
                <fullName>IDENTITY_Utils</fullName>
            </value>
            <value>
                <fullName>IDENTITY_WS_AccountMatching</fullName>
            </value>
            <value>
                <fullName>IDENTITY_WS_Contactability</fullName>
            </value>
            <value>
                <fullName>IM_CheckPushNotifications</fullName>
            </value>
            <value>
                <fullName>IM_ClientListWS</fullName>
            </value>
            <value>
                <fullName>IM_FollowUp_WS</fullName>
            </value>
            <value>
                <fullName>IM_TeamManagment</fullName>
            </value>
            <value>
                <fullName>IM_WS_Assets</fullName>
            </value>
            <value>
                <fullName>IM_WS_CareService</fullName>
            </value>
            <value>
                <fullName>IM_WS_PushNotifications</fullName>
            </value>
            <value>
                <fullName>IM_WSAddCLMembers</fullName>
            </value>
            <value>
                <fullName>IM_WSConfig</fullName>
            </value>
            <value>
                <fullName>IM_WSRemoveCLMembers</fullName>
            </value>
            <value>
                <fullName>Line</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Logs__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <defaultValue>&apos;APEX CODE&apos;</defaultValue>
    <description>Database: 
Includes information about database activity, including every data manipulation language (DML) statement or inline SOQL or SOSL query.

Validation: 
Includes information about validation rules, required fields missing.

Callout:
API calls or troubleshooting user access to external API

Apex Code:
Includes information about Apex code. By default

Visualforce:
Includes information about Visualforce events

System:
Includes information about calls to all system methods

Event:
Includes information about events (email, sms, task … )

API:
External third party or Apex Custom REST API</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APEX CODE</fullName>
            </value>
            <value>
                <fullName>CALLOUT</fullName>
            </value>
            <value>
                <fullName>DATABASE</fullName>
            </value>
            <value>
                <fullName>SYSTEM</fullName>
            </value>
            <value>
                <fullName>VALIDATION</fullName>
            </value>
            <value>
                <fullName>VISUALFORCE</fullName>
            </value>
            <value>
                <fullName>EVENT</fullName>
            </value>
            <value>
                <fullName>API</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Logs__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DEBUG</fullName>
                <default>true</default>
                <label>DEBUG</label>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Logs__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <inlineHelpText>Exception Message Value</inlineHelpText>
    <label>Message</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Logs__c/fields/Other_Details__c.field-meta.xml
<CustomField>
    <fullName>Other_Details__c</fullName>
    <label>Other Details</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Line.cls
/**
    About
    -----
    Description: Auth Provider Flow for LINE
    Created for: Identity project
    Create date: Oct 2018

    Details
    -------
    Implement Oauth protocol 
*/
global without sharing class Line extends Auth.AuthProviderPluginClass {
  
    @TestVisible
    private String authProvider = 'Line';
    private String customMetadataTypeApiName = 'Auth_Provider__mdt';
    
    @TestVisible
    private String customLogsAccessToken;

    global String getCustomMetadataType() {
        return customMetadataTypeApiName;
    }

    global PageReference initiate(Map<String,String> authProviderConfiguration, String stateToPropagate) {

        System.debug('LINE INITIATE');
        System.debug('STATE: ' + stateToPropagate);

        String authUrl = authProviderConfiguration.get('Authorize_Endpoint_URL__c');
        String callbackUrl = authProviderConfiguration.get('Callback_URL__c');

        String key = authProviderConfiguration.get('Consumer_Key__c');
        String scope = authProviderConfiguration.get('Scope__c');

        String url = authUrl + 
            '?response_type=code' + 
            '&client_id='+ key +
            '&redirect_uri=' + EncodingUtil.urlEncode(callbackUrl, 'UTF-8.') + 
            ( !String.isEmpty(scope) ? '&scope=' + EncodingUtil.urlEncode(scope, 'UTF-8.') : '') +
            '&state=' + stateToPropagate +
            '&bot_prompt=normal';  
        
        System.debug('url: ' + url);
        return new PageReference(url); 
    }
    

    global Auth.AuthProviderTokenResponse handleCallback(Map<string,string> authProviderConfiguration, Auth.AuthProviderCallbackState state ) { 
        System.debug('>>> LINE CALLBACK');

        String key = authProviderConfiguration.get('Consumer_Key__c'); 
        String secret = authProviderConfiguration.get('Consumer_Secret__c'); 

        String accessTokenUrl = authProviderConfiguration.get('Token_Endpoint_URL__c');
        String callbackUrl = authProviderConfiguration.get('Callback_URL__c');

        Map<String,String> queryParams = state.queryParameters; 
        String code = queryParams.get('code'); 
        String sfdcState = queryParams.get('state');

        String body = 'client_id=' + key + 
          '&client_secret=' + secret +
          '&code=' + code + 
          '&grant_type=authorization_code' + 
          '&redirect_uri=' + callbackUrl;
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(accessTokenUrl); 
        req.setHeader('Content-Type','application/x-www-form-urlencoded'); 
        req.setMethod('POST');
        req.setBody(body);

        Http http = new Http(); 
        HTTPResponse res = http.send(req);
        
        
        if (isFailureResponse(res)) {
            insertCustomLogsViaHttpRequest(res, 'handleCallback');
            if (Test.isRunningTest()) {
                return null; // No need to test further in this methode when isFailureResponse(res) is true
            }
        }

        
        String token = IDENTITY_AuthProvider.getTokenValue(res.getBody(), 'access_token');
        String id_token = IDENTITY_AuthProvider.getTokenValue(res.getBody(), 'id_token');

        System.debug('BODY: ' + res.getBody());
        System.debug('TOKEN: ' + token);
        System.debug('ID_TOKEN: ' + id_token);

        return new Auth.AuthProviderTokenResponse(authProvider, token, id_token, sfdcState); 
    }
    

    global Auth.UserData getUserInfo(Map<string,string> authProviderConfiguration, Auth.AuthProviderTokenResponse response) { 
        
        System.debug('LINE USER INFO');

        String token = response.oauthToken;
        String id_token = response.oauthSecretOrRefreshToken;

        // GET ID TOKEN 
        String payload_json;
        if(!String.isEmpty(id_token)){
            List<String> id_token_split = id_token.split('\\.');

            try{
                String payload_decoded = EncodingUtil.base64Decode( id_token_split[1] ).toString();
                payload_json = EncodingUtil.urlDecode(payload_decoded, 'UTF-8');
            }
            catch(Exception ex){}
        }

        // GET USER DATA
        String userAPIUrl = authProviderConfiguration.get('User_Info_Endpoint_URL__c');

        HttpRequest req = new HttpRequest(); 
        req.setHeader('Authorization', 'Bearer ' + token);
        req.setEndpoint(userAPIUrl);
        req.setMethod('GET');

        Http http = new Http();
        HTTPResponse res = http.send(req);

        if (isFailureResponse(res)) {
            insertCustomLogsViaHttpRequest(res, 'getUserInfo');
            if (Test.isRunningTest()) {
                return null; // No need to test further in this methode when isFailureResponse(res) is true
            }
        }

        return IDENTITY_AuthProvider.getUserData(authProvider, res.getBody(), payload_json);
    }
    
    private void insertCustomLogsViaHttpRequest(HTTPResponse httpResponse, String methodName) {
        System.debug('>>> call to insertCustomLogsViaHttpRequest()');
        try {
            if (String.isEmpty(this.customLogsAccessToken)) {
                this.getSalesforceAccessToken();
            }
			this.writeCustomLog(httpResponse, methodName);
        }
        catch(Exception e) {
            System.debug('>>> exception:  ' + e.getMessage());
        }
    }
    
    private void getSalesforceAccessToken() {
        System.debug('>>> call to getSalesforceAccessToken()');

        User TechBatchUser = [SELECT Username FROM User WHERE Name = 'Batch Tech' LIMIT 1][0];
        String username = TechBatchUser.Username;
            System.debug('>>> myresponse()'+username); 
        this.customLogsAccessToken = IDENTITY_Utils.getJWTAccessToken(username);
       // System.debug('mytoken1:'+this.customLogsAccessToken.SubString(15));
    }
    
    @TestVisible
    private void writeCustomLog(HttpResponse failedResponse, String methodName) {
        System.debug('>>> call to writeCustomLog()');
        
        String endpoint = IDENTITY_Settings__c.getInstance().Community_URL__c + '/services/data/v53.0/sobjects/Logs__c/';
        System.debug('>>> endpoint: ' + endpoint);
        
        
        Map<String,Object> failedResponseHeadersMap = new Map<String,Object>();
        for (String key: failedResponse.getHeaderKeys()) {
            if (!String.isEmpty(key)) {
                failedResponseHeadersMap.put(key, failedResponse.getHeader(key));
            }
        }
        System.debug('>>> failedResponseHeadersMap: ' + JSON.serializePretty(failedResponseHeadersMap));

        Map<String,Object> logsMap = new Map<String,Object> {
            'Level__c' => 'DEBUG',
            'Apex_Class__c' => this.authProvider,
            'Category__c' => 'APEX CODE',
            'Message__c' => 'HTTP request called from method ' + methodName + '() failed!',
            'Status_Code__c' => failedResponse.getStatusCode(),
            'Other_Details__c' => JSON.serialize(new Map<String,Object> {
                'status' => failedResponse.getStatus(),
                'statusCode' => failedResponse.getStatusCode(),
                'headers' => failedResponseHeadersMap,
                'body' => failedResponse.getBody()
            })
        };
		System.debug('>>> logsMap ' + JSON.serializePretty(logsMap));
        
        callHttpRequestForCustomLogs(endpoint, this.customLogsAccessToken, JSON.serialize(logsMap));
    }
    
    global static void callHttpRequestForCustomLogs(String endpoint, String token, String logsJson) {
        new HTTP_Utils()
            .post(endpoint)
            .header('Authorization', 'Bearer ' + token)
            .header('Content-Type', 'application/json')
            .body(logsJson)
            .call();
    }    

    @TestVisible
    private Boolean isFailureResponse(HttpResponse response) {
        return (response.getStatusCode() != 200 && response.getStatusCode() != 201);
    }
    
    
    
}