force-app/main/default/objects/VO_Survey__c/VO_Survey__c.object-meta.xml
<CustomObject>
    <label>Voice</label>
    <nameField>
        <displayFormat>Survey-{00000000}</displayFormat>
        <label>Survey ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VO_Survey__c/fields/AnswerDate__c.field-meta.xml
<CustomField>
    <fullName>AnswerDate__c</fullName>
    <description>Default value equal to today (old voice)</description>
    <label>Answer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/ClientDreamID__c.field-meta.xml
<CustomField>
    <fullName>ClientDreamID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>populated with VO_Survey apex class before insert from DreamIDText__c field</description>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Survey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/SurveyType__c.field-meta.xml
<CustomField>
    <fullName>SurveyType__c</fullName>
    <description>Sent by Clicktools</description>
    <label>Survey Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VOICE Store Local Sales</fullName>
            </value>
            <value>
                <fullName>VOICE Store After Sales</fullName>
            </value>
            <value>
                <fullName>VOICE Web Sales</fullName>
            </value>
            <value>
                <fullName>VOICE Web Click And Collect</fullName>
            </value>
            <value>
                <fullName>VOICE CSC Sales</fullName>
            </value>
            <value>
                <fullName>VOICE CSC Click And Collect</fullName>
            </value>
            <value>
                <fullName>VOICE Endless Offer</fullName>
            </value>
            <value>
                <fullName>VOICE Post Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VO_Survey__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Neutral</fullName>
            </value>
            <value>
                <fullName>Promoter</fullName>
            </value>
            <value>
                <fullName>Recovery Act</fullName>
            </value>
            <value>
                <fullName>Delighted Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VO_Survey_RelatedList_Controller.cls
/**
     * Controller of the VO_Survey_RelatedList component.
     * @createdBy   RMOU, 10/03/2017
     */

public with sharing class VO_Survey_RelatedList_Controller {

	public VO_Survey_RelatedList_Controller() {
		
	}

	// Returns the list of related surveys
	@AuraEnabled
	public static List<VO_Survey__c> getSurveys (Id accountId){
		return [SELECT id, Name, SurveyType__c, AnswerDate__c, Type__c FROM VO_Survey__c WHERE ClientDreamID__c=:accountId];
	}
}