force-app/main/default/objects/Exclusive_Experience__c/Exclusive_Experience__c.object-meta.xml
<CustomObject>
    <description>Contains targeted client lists for special sales</description>
    <label>Exclusive Experience</label>
    <nameField>
        <displayFormat>XXPR-{0000000}</displayFormat>
        <label>Exclusive Experience Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exclusive Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exclusive_Experience__c/fields/Offer_Code__c.field-meta.xml
<CustomField>
    <fullName>Offer_Code__c</fullName>
    <label>Offer Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Typology__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>XXPR_Offer_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/XXPR_Offer_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>exclu_nba_1_2020</fullName>
    </customValue>
    <customValue>
        <fullName>exclu_nba_1_2020.</fullName>
    </customValue>
    <customValue>
        <fullName>test_exclusive_sale</fullName>
    </customValue>
    <customValue>
        <fullName>exclu_offer_collectibles_ff</fullName>
    </customValue>
    <customValue>
        <fullName>digital_collectibles_wave_1</fullName>
    </customValue>
    <customValue>
        <fullName>digital_collectibles_wave_2</fullName>
    </customValue>
    <customValue>
        <fullName>digital_collectibles_speedy40_july23</fullName>
    </customValue>
    <customValue>
        <fullName>lv_remix_excluoffer</fullName>
    </customValue>
    <customValue>
        <fullName>men_show_ss24_exclu_offer</fullName>
    </customValue>
    <customValue>
        <fullName>web_digital_collectibles_tile_trunk</fullName>
    </customValue>
    <customValue>
        <fullName>web_via_varsity_blouson</fullName>
    </customValue>
    <customValue>
        <fullName>mylv_volt_202007</fullName>
        <isActive>false</isActive>
        <label>mylv_volt_202007</label>
    </customValue>
    <customValue>
        <fullName>test_exclusive_offer</fullName>
        <isActive>false</isActive>
        <label>test_exclusive_offer</label>
    </customValue>
    <description>Exclusive Experience offer codes. Must be unique + lowercase only + not contain space/special caracters/accent</description>
    <masterLabel>XXPR Offer Code</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/TWIST_LWCWrapper_CTRL_TEST.cls
@isTest
public class TWIST_LWCWrapper_CTRL_TEST {
    @isTest
    static void testInit() {
         // Given
         Schema.DescribeFieldResult XXPR_OfferCode = Exclusive_Experience__c.Offer_Code__c.getDescribe();
         Schema.sObjectField fieldOfferCode = XXPR_OfferCode.getSObjectField();
         List<PicklistEntry> picklistValuesOfferCode = fieldOfferCode.getDescribe().getPicklistValues();
         String utmCampaign = picklistValuesOfferCode.get(0).getValue();
 
        PageReference pageRef = Page.Identity_Registration;
        pageRef.getParameters().put('lang-country','eng-e1');
        pageRef.getParameters().put('origin','mylv');
        pageRef.getParameters().put('cid','cid123');
        pageRef.getParameters().put('utm_campaign',utmCampaign);
        Test.setCurrentPage(pageRef);
        TWIST_LWCWrapper_CTRL controller = new TWIST_LWCWrapper_CTRL();
        PageReference result = controller.init();
        TWIST_LWCWrapper_CTRL.getLVappRedirectionLink('cid123', 'myexclusive');
        System.assertNotEquals(null, controller.utagDataStringified);
    }

}