force-app/main/default/objects/CA_Consent__c/CA_Consent__c.object-meta.xml
<CustomObject>
    <label>CA Consent</label>
    <nameField>
        <displayFormat>CAC-{0000000}</displayFormat>
        <label>CA Consent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CA Consents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CA_Consent__c/fields/Consent__c.field-meta.xml
<CustomField>
    <fullName>Consent__c</fullName>
    <label>Consent</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TRUE</fullName>
            </value>
            <value>
                <fullName>FALSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CA_Consent__c/fields/ExKey__c.field-meta.xml
<CustomField>
    <fullName>ExKey__c</fullName>
    <label>ExKey</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CA_Consent__c/fields/Last_Consent__c.field-meta.xml
<CustomField>
    <fullName>Last_Consent__c</fullName>
    <label>Last Consent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CA_Consent__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CA_Consents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ca_ConsentTriggerHandler.cls
public with sharing class Ca_ConsentTriggerHandler {
    
    public static void handleTrigger(List<Ca_Consent__c> newList,Map<Id, Ca_Consent__c> oldMap, System.TriggerOperation triggerEvent) {
        switch on triggerEvent {
            when BEFORE_INSERT {
                handleBeforeInsert(newList);
            }
            when BEFORE_UPDATE {
                handleBeforeUpdate(newList,oldMap);
            }
            when else {
                //do nothing for AFTER_UNDELETE, BEFORE_DELETE, or BEFORE_UPDATE
            }
        }
    }
    public static void handleBeforeInsert(List<Ca_Consent__c> newList){
        for (Ca_Consent__c consent : newList) {

            if(String.isEmpty(consent.user__c)|| consent.user__c != UserInfo.getUserId()){
                consent.addError( new myException('ERROR PLEASE CHECK THE USER'));
                return;
            }

            if(String.isNotEmpty(consent.Consent__c)){
                consent.Last_Consent__c = System.Now();
                consent.ExKey__c = consent.User__c;
            }
        }       
    }


    public static void handleBeforeUpdate(List<Ca_Consent__c> newList , Map<Id, Ca_Consent__c> oldMap ){

        for (Ca_Consent__c consent : newList) {

            if(String.isEmpty(consent.user__c) || consent.user__c != UserInfo.getUserId()){
                consent.addError( new myException('ERROR PLEASE CHECK THE USER'));
                return;
            }

            if(consent.Consent__c != oldMap.get(consent.id).Consent__c ){
                consent.Last_Consent__c = System.Now();
            }
         
        }       
    }
    public class MyException extends Exception {}

}