force-app/main/default/objects/User/fields/Is_Identity_User__c.field-meta.xml
<CustomField>
    <fullName>Is_Identity_User__c</fullName>
    <formula>Profile.Name = &apos;Identity User&apos; &amp;&amp; Profile.UserLicense.Name =&apos;External Identity&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Identity User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/TECH_Email__c.field-meta.xml
<CustomField>
    <fullName>TECH_Email__c</fullName>
    <label>TECH Email</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Batch_CreateIdentity.cls
global class Batch_CreateIdentity implements Database.Batchable<sObject> {
	
	String query;
	
	global Batch_CreateIdentity() {
		query = 'SELECT TECH_Email__c, Email FROM User WHERE Is_Identity_User__c = true AND IsActive = true AND TECH_Email__c = \'\'';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		System.debug('#### START - Batch_CreateIdentity');
		System.debug('#### QUERY : ' + query);

		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
   		try{

			for(User u : (List<User>) scope){
				u.TECH_Email__c = u.Email;
			}

			Database.SaveResult[] SRs = Database.update(scope, false);

			for(Database.SaveResult sr : SRs){
				if (!sr.isSuccess()) {
			    	System.debug('FAILED - USER ID: ' + sr.getId());
			        for(Database.Error err : sr.getErrors()) {
			            System.debug('EXCEPTION: ' + err.getMessage());
			        }
			    }
			}
		 }
		 catch(DmlException e) {
            System.debug('#### ' + e.getTypeName() + ' Exception:' + e.getMessage() + ' ' + e.getStackTraceString());
        }
	}
	
	global void finish(Database.BatchableContext BC) {
		System.debug('#### END - Batch_CreateIdentity');
	}
	
}