force-app/main/default/objects/User/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/MGMT_ZONE_SUB_LEVEL1__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL1__c</fullName>
    <description>Contains the code/translation for the first sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MANAGEMENT_ZONE_LEVEL__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>151</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>1231</fullName>
            </value>
            <value>
                <fullName>1071</fullName>
            </value>
            <value>
                <fullName>1111</fullName>
            </value>
            <value>
                <fullName>1151</fullName>
            </value>
            <value>
                <fullName>1191</fullName>
            </value>
            <value>
                <fullName>1271</fullName>
            </value>
            <value>
                <fullName>1311</fullName>
            </value>
            <value>
                <fullName>1351</fullName>
            </value>
            <value>
                <fullName>1391</fullName>
            </value>
            <value>
                <fullName>391</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/MGMT_ZONE_SUB_LEVEL2__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL2__c</fullName>
    <description>Contains the code/translation for the second sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MGMT_ZONE_SUB_LEVEL1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>43</fullName>
            </value>
            <value>
                <fullName>53</fullName>
            </value>
            <value>
                <fullName>54</fullName>
            </value>
            <value>
                <fullName>68</fullName>
            </value>
            <value>
                <fullName>69</fullName>
            </value>
            <value>
                <fullName>88</fullName>
            </value>
            <value>
                <fullName>97</fullName>
            </value>
            <value>
                <fullName>98</fullName>
            </value>
            <value>
                <fullName>99</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>179</fullName>
            </value>
            <value>
                <fullName>219</fullName>
            </value>
            <value>
                <fullName>259</fullName>
            </value>
            <value>
                <fullName>299</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>63</fullName>
            </value>
            <value>
                <fullName>419</fullName>
            </value>
            <value>
                <fullName>2379</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/MGMT_ZONE_SUB_LEVEL3__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL3__c</fullName>
    <description>Contains the code/translation for the third sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MGMT_ZONE_SUB_LEVEL2__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10056</fullName>
            </value>
            <value>
                <fullName>1016</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>10216</fullName>
            </value>
            <value>
                <fullName>10296</fullName>
            </value>
            <value>
                <fullName>103</fullName>
            </value>
            <value>
                <fullName>10616</fullName>
            </value>
            <value>
                <fullName>10856</fullName>
            </value>
            <value>
                <fullName>109</fullName>
            </value>
            <value>
                <fullName>10936</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>11016</fullName>
            </value>
            <value>
                <fullName>11176</fullName>
            </value>
            <value>
                <fullName>112</fullName>
            </value>
            <value>
                <fullName>11256</fullName>
            </value>
            <value>
                <fullName>113</fullName>
            </value>
            <value>
                <fullName>11336</fullName>
            </value>
            <value>
                <fullName>11416</fullName>
            </value>
            <value>
                <fullName>116</fullName>
            </value>
            <value>
                <fullName>11656</fullName>
            </value>
            <value>
                <fullName>11736</fullName>
            </value>
            <value>
                <fullName>1176</fullName>
            </value>
            <value>
                <fullName>118</fullName>
            </value>
            <value>
                <fullName>11896</fullName>
            </value>
            <value>
                <fullName>119</fullName>
            </value>
            <value>
                <fullName>11976</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>12056</fullName>
            </value>
            <value>
                <fullName>121</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/TECH_User_Stores__c.field-meta.xml
<CustomField>
    <fullName>TECH_User_Stores__c</fullName>
    <description>Holds comma separated list of Store codes</description>
    <label>User Stores</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VO_Config__c/VO_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>VO_Config</label>
</CustomObject>

force-app/main/default/classes/EditUserStores_VFCx.cls
/*
* Controller of the EditUserStores VFP
* @createdBy   Romain Mouchel-Vallon 30/01/17
*/

public with sharing class EditUserStores_VFCx {

    public final Integer max_stores_per_user;

    // User record
	public final User myUser;
    // Temporary User
    public User currentUser {get; set;}
    // Stores that have been highlighted in the list
    public List<String> selectedStoresClicked {get; set;}
    // Stores that have been added to the list
    public List<selectOption> selectedStoresOptions {get; set;}
    // Map holding store code translations
    private final Map<String, String> picklistTranslationsMap = new Map<String, String>();
    // Should add button be disabled
    public Boolean isAddDisabled {
        get {
            return currentUser.DefaultStore__c == null || isSelected(selectedStoresOptions, currentUser.DefaultStore__c) || selectedStoresOptions.size() >= max_stores_per_user;
        }
    }
    // Should remove button be disabled
    public Boolean isRemoveDisabled {
        get {
            return selectedStoresOptions.isEmpty() || selectedStoresClicked.isEmpty();
        }
    }
    // Is Max nb Stores reached
    public Boolean isMaxNbStores {
        get {
            return selectedStoresOptions.size() >= max_stores_per_user;
        }
    }
    // Warning message
    public String warningMessage {
        get {
            return System.Label.Max_Nb_User_Stores.replace('{0}', '' + max_stores_per_user);
        }
    }

    // Constructor
    public EditUserStores_VFCx() {
        // Retrieving User record
        myUser = [SELECT id, FirstName, LastName, MANAGEMENT_ZONE_LEVEL__c, MGMT_ZONE_SUB_LEVEL1__c, MGMT_ZONE_SUB_LEVEL2__c, MGMT_ZONE_SUB_LEVEL3__c, DefaultStore__c, TECH_User_Stores__c FROM User WHERE id = :ApexPages.currentPage().getParameters().get('id') LIMIT 1];
        // Deep copy to temporary User to duplicate field values
        currentUser = myUser.clone(false, true, false, false);

        // Initializing translation map
        List<Schema.PicklistEntry> picklistValues = User.DefaultStore__c.getDescribe().getPicklistValues();
        for (Schema.PicklistEntry pe : picklistValues){
            picklistTranslationsMap.put(pe.getValue(), pe.getLabel());
        }
        
        // Initializing list
        selectedStoresOptions = new List<selectOption>();
        if (currentUser.TECH_User_Stores__c != null){
            for (String s : currentUser.TECH_User_Stores__c.split(','))
                selectedStoresOptions.add (new selectOption(s, picklistTranslationsMap.get(s)));
        }

        selectedStoresClicked = new List<String>();

        VO_Config__c nb = VO_Config__c.getValues('Max stores per user');
        max_stores_per_user = nb == null || !nb.Value__c.isNumeric() ? 5 : Integer.valueOf(nb.Value__c);
    }

    // Adds selected store to the list if it is not already there
    public void add(){
        if (currentUser.DefaultStore__c != null && !isSelected(selectedStoresOptions, currentUser.DefaultStore__c))
            selectedStoresOptions.add(new selectOption(currentUser.DefaultStore__c, picklistTranslationsMap.get(currentUser.DefaultStore__c)));
    }

    // Remove highlighted store(s) from the list
    public void remove(){
        removeAll(selectedStoresOptions, new Set<String>(selectedStoresClicked));
        selectedStoresClicked.clear();
    }

    // Updates TECH field and saves User record
    public PageReference validate(){
        myUser.TECH_User_Stores__c = '';
        List<String> stores = new List<String>();
        for (selectOption o : selectedStoresOptions)
            stores.add(o.getValue());

        myUser.TECH_User_Stores__c = String.join(stores, ',');

        update myUser;

        // Return to User detail page
        return new PageReference ('/' + myUser.id);
    }

    // cancel
    public PageReference cancel(){
        // Return to User detail page
        return new PageReference ('/' + myUser.id);
    }

    // Returns original list without values to remove
    private void removeAll (List<selectOption> l, Set<String> toRemove){
        List<selectOption> newList = new List<selectOption>();

        for (Integer i = 0; i<l.size(); i++)
            if (!toRemove.contains(l.get(i).getValue()))
                newList.add (new selectOption(l.get(i).getValue(), picklistTranslationsMap.get(l.get(i).getValue())));

        l.clear();
        l.addAll(newList);
    }

    // Returns whether store is in the list
    private Boolean isSelected(List<selectOption> l, String store){
        Boolean isFound = false;

        for (selectOption o : l)
            isFound = isFound || o.getValue() == store;

        return isFound;
    }
}