force-app/main/default/objects/Headless_Identity_Flow_Instance__c/Headless_Identity_Flow_Instance__c.object-meta.xml
<CustomObject>
    <description>This object was created to handle process breaks to better handle the headless identity APIs it will handle (storing verification code for passwordless and email verification data and other data if necessary)</description>
    <label>Headless Identity Flow Instance</label>
    <nameField>
        <displayFormat>id-{0000000000}</displayFormat>
        <label>Headless Identity Flow Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Headless Identity Flow Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Flow_Type__c.field-meta.xml
<CustomField>
    <fullName>Flow_Type__c</fullName>
    <label>Flow Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PasswordlessEmailVerification</fullName>
            </value>
            <value>
                <fullName>PasswordlessLogin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Identifier</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IDENTIFIER_ISSUED</fullName>
            </value>
            <value>
                <fullName>IDENTIFIER_USED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <externalId>true</externalId>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Verification_Method__c.field-meta.xml
<CustomField>
    <fullName>Verification_Method__c</fullName>
    <label>Verification Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>sms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/TWIST_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TWIST - Settings</label>
</CustomObject>

force-app/main/default/objects/TWIST_Settings__c/fields/Email_Token_Chars__c.field-meta.xml
<CustomField>
    <fullName>Email_Token_Chars__c</fullName>
    <label>Email Token Chars</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Email_Token_Size__c.field-meta.xml
<CustomField>
    <fullName>Email_Token_Size__c</fullName>
    <label>Email Token Size</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Password_Maxlength__c.field-meta.xml
<CustomField>
    <fullName>Password_Maxlength__c</fullName>
    <label>Password Maxlength</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Pwdless_Email_Verif_Identifier_Validity__c.field-meta.xml
<CustomField>
    <fullName>Pwdless_Email_Verif_Identifier_Validity__c</fullName>
    <label>Pwdless Email Verif Identifier Validity</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-twist/main/default/classes/TWIST_PwdlessEmailVerifGetTokenAPI_TEST.cls
@isTest
private class TWIST_PwdlessEmailVerifGetTokenAPI_TEST {
    
    public final static String PWDLESS_EMAIL_VERIFICATION = 'PasswordlessEmailVerification';
    public final static String EMAIL = 'email';
    public final static String IDENTIFIER_ISSUED = 'IDENTIFIER_ISSUED';
    public final static String IDENTIFIER_USED = 'IDENTIFIER_USED';
         
    @isTest static void test() {
        
        Headless_Identity_Flow_Instance__c pwdlessEmailVerifRequest = new Headless_Identity_Flow_Instance__c (
            Flow_Type__c = PWDLESS_EMAIL_VERIFICATION,
            Username__c = 'userName@test.com', 
            Verification_Method__c = EMAIL,
            Status__c = IDENTIFIER_ISSUED,
        	Identifier__c = 'existing-identifier'
        
        );
        insert pwdlessEmailVerifRequest;
        Identity_TestFactory.createSettings();
        User user = Identity_TestFactory.createUser('TEST','TEST','userName@test.com','0500000000','972');

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse(); 
        req.httpMethod = 'POST';
        req.requestURI = '/services/apexrest/PwdlessEmailVerification/GetAccessToken';
        req.addHeader('Content-Type','application/json');
        RestContext.request = req;
        RestContext.response = res;
        
        
        Test.startTest();
        
        Map<String, Object> bodyMap = new Map<String, Object>();
        
        //EMPTY BODY
        bodyMap = new Map<String, Object>{};
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        TWIST_PwdlessEmailVerifGetTokenAPI.doPost();
        System.assertEquals(400, res.statusCode, 'Statuscode should be 400');
        
        // GENERIC ERROR - MISSING SETTINGS
        bodyMap = new Map<String, Object>{'code' => 'existing-identifier'};
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        TWIST_PwdlessEmailVerifGetTokenAPI.doPost();
        System.assertEquals(400, res.statusCode, 'Statuscode should be 400');
        
        //CREATE SETTINGS
        TWIST_Settings__c settings = new TWIST_Settings__c(	Name = 'test',
                                                           Pwdless_Email_Verif_Identifier_Validity__c = 15,
                                                           Password_Maxlength__c = 20,
                                                           Email_Token_Size__c = 32,
                                                           Email_Token_Chars__c = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz');
        insert settings;
        
        // IDENTIFIER_STATUS_VALID
        bodyMap = new Map<String, Object>{'code' => 'existing-identifier'};
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        TWIST_PwdlessEmailVerifGetTokenAPI.doPost();
        System.assertEquals(200, res.statusCode, 'Statuscode should be 200');
        
        // IDENTIFIER_STATUS_UNKNOWN
        bodyMap = new Map<String, Object>{'code' => 'non-existing-identifier'};
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        TWIST_PwdlessEmailVerifGetTokenAPI.doPost();
        System.assertEquals(400, res.statusCode, 'Statuscode should be 400');
        
        // IDENTIFIER_STATUS_USED
        pwdlessEmailVerifRequest.Status__c = IDENTIFIER_USED;
        update pwdlessEmailVerifRequest;
        bodyMap = new Map<String, Object>{'code' => 'existing-identifier'};
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        TWIST_PwdlessEmailVerifGetTokenAPI.doPost();
        System.assertEquals(400, res.statusCode, 'Statuscode should be 400');
        
        // LOGIN ERROR
        pwdlessEmailVerifRequest.Username__c = '';
        update pwdlessEmailVerifRequest;
        bodyMap = new Map<String, Object>{'code' => 'existing-identifier'};
        req.requestBody = Blob.valueOf(JSON.serialize(bodyMap));
        TWIST_PwdlessEmailVerifGetTokenAPI.doPost();
        System.assertEquals(400, res.statusCode, 'Statuscode should be 400');


        Test.stopTest();
    }
    
}