force-app/main/default/objects/Headless_Identity_Flow_Instance__c/Headless_Identity_Flow_Instance__c.object-meta.xml
<CustomObject>
    <description>This object was created to handle process breaks to better handle the headless identity APIs it will handle (storing verification code for passwordless and email verification data and other data if necessary)</description>
    <label>Headless Identity Flow Instance</label>
    <nameField>
        <displayFormat>id-{0000000000}</displayFormat>
        <label>Headless Identity Flow Instance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Headless Identity Flow Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Flow_Type__c.field-meta.xml
<CustomField>
    <fullName>Flow_Type__c</fullName>
    <label>Flow Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PasswordlessEmailVerification</fullName>
            </value>
            <value>
                <fullName>PasswordlessLogin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <externalId>true</externalId>
    <label>Identifier</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Locale__c.field-meta.xml
<CustomField>
    <fullName>Locale__c</fullName>
    <label>Locale</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Redirect_Uri__c.field-meta.xml
<CustomField>
    <fullName>Redirect_Uri__c</fullName>
    <label>Redirect Uri</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IDENTIFIER_ISSUED</fullName>
            </value>
            <value>
                <fullName>IDENTIFIER_USED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <externalId>true</externalId>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Headless_Identity_Flow_Instance__c/fields/Verification_Method__c.field-meta.xml
<CustomField>
    <fullName>Verification_Method__c</fullName>
    <label>Verification Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>sms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/TWIST_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TWIST - Settings</label>
</CustomObject>

force-app/main/default/objects/TWIST_Settings__c/fields/Email_Token_Chars__c.field-meta.xml
<CustomField>
    <fullName>Email_Token_Chars__c</fullName>
    <label>Email Token Chars</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Email_Token_Size__c.field-meta.xml
<CustomField>
    <fullName>Email_Token_Size__c</fullName>
    <label>Email Token Size</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/fields/Network_Id__c.field-meta.xml
<CustomField>
    <fullName>Network_Id__c</fullName>
    <description>ID of the Experience Cloud site</description>
    <label>Network Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-twist/main/default/classes/TWIST_PwdlessEmailVerifInitAPI.cls
@RestResource(urlMapping='/PwdlessEmailVerification/Init')
global with sharing class TWIST_PwdlessEmailVerifInitAPI {
    public final static String PWDLESS_EMAIL_VERIFICATION = 'PasswordlessEmailVerification';
    public final static String EMAIL = 'email';
    public final static String IDENTIFIER_ISSUED = 'IDENTIFIER_ISSUED';
    public final static String GENERIC_ERROR = 'GENERIC_ERROR';
    public final static String IDENTIFIER_ERROR = 'IDENTIFIER_ERROR';
    @HttpPost
    global static void doPost() {
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        Map<String,Object> responseMap = TWIST_Utils.buildSuccessResponseObject();
        TWIST_Settings__c settings = TWIST_Settings__c.getInstance();
        List<String> requiredFields = new List<String>{'username', 'emailtemplate', 'redirecturi', 'locale'};
        try {
            response.addHeader('Content-Type','application/json');
            response.statusCode = 200;
            
            if(String.isBlank(request.requestBody.toString())){
                 throw new CustomException(Label.EM_required_field_missing + ' : EMPTY BODY');
            }
            
            Map<String,Object> body = (Map<String,Object>)JSON.deserializeUntyped(request.requestBody.toString());

            String missingRequiredFields = getMissingRequiredFields(requiredFields, body);
            if(!String.isBlank(missingRequiredFields)){
                throw new CustomException(Label.EM_required_field_missing + ' : ' + missingRequiredFields);
            }

            String userName = String.ValueOf(body.get('username'));
            String emailTemplate = String.ValueOf(body.get('emailtemplate'));
            String redirectUri = String.ValueOf(body.get('redirecturi'));
            String locale = String.ValueOf(body.get('locale'));
            
            String userId = getUserId(username);
            if(userId == null){
                throw new CustomException(Label.EM_User_Not_Found);
            } 

            String emailTemplateId = getEmailTemplateId(emailTemplate);
            if(emailTemplateId == null){
                throw new CustomException(Label.EM_Emailtemplate_Not_Found);
            }       
            
            String identifier = StringUtils.generateRandomString(Integer.valueOf(settings.Email_Token_Size__c), settings.Email_Token_Chars__c);  
            if(identifier == null){
                throw new CustomException(IDENTIFIER_ERROR);
            }
            
            Boolean isEmailSent = System.UserManagement.sendAsyncEmailConfirmation(userId, emailTemplateId, String.valueOf(settings.get('Network_Id__c')),'TWIST_PwdlessEmailVerif?client-id=null&identifier='+identifier+'&redirect-uri='+redirectUri+'&username='+EncodingUtil.urlEncode(userName, 'UTF-8')+'&locale='+locale);
            
            if(isEmailSent){
                upsertPwdlessEmailVerifRequest(username, identifier, redirectUri, locale);
            }
        }
        catch (Exception e) {
            String errorMessage = e.getTypeName().contains('CustomException') ? e.getMessage() : GENERIC_ERROR;
            new Logs.ERROR('TWIST_PwdlessEmailVerifInitAPI', 'API', e.getMessage(), e.getStackTraceString());
            System.debug('An error occured: ' + e.getMessage() + e.getStackTraceString());
            responseMap = TWIST_Utils.buildFailureResponseObject('message', errorMessage);
            response.statusCode = 400;
        }
        response.responseBody = Blob.valueOf(JSON.serialize(responseMap));
    }

    private static String getMissingRequiredFields(List<String> requiredFields, Map<String, Object> body){
        List<String> missingFields = new List<String>();

        for (String key : requiredFields){
            if(!body.containsKey(key) || String.isBlank(String.ValueOf(body.get(key)))){
                missingFields.add(key);
            }
        }


        if(!missingFields.isEmpty()){
            return String.join(missingFields, ' | ');
        }
          
        return null;
    }

    private static String getUserId(String username){
        List<User> users = [SELECT id, UserName from user WHERE UserName =: userName];
        if(!users.isEmpty()){
            return users[0].Id;
        }  
        return null;
    }

    private static String getEmailTemplateId(String emailTemplate){
        List<EmailTemplate> templates = [SELECT Id from EmailTemplate WHERE DeveloperName =: emailTemplate LIMIT 1];
        if(!templates.isEmpty()){
            return templates[0].Id;
        }  
        return null;
    }

    private static void upsertPwdlessEmailVerifRequest(String username, String identifier, String redirectUri, String locale) {
        Headless_Identity_Flow_Instance__c pwdlessEmailVerifRequest = new Headless_Identity_Flow_Instance__c ();
        List<Headless_Identity_Flow_Instance__c> pwdlessEmailVerifRequestList = [	SELECT 	id 
                                                                                	FROM 	Headless_Identity_Flow_Instance__c 
                                                                                	WHERE 	Username__c =: username 
                                                                                	AND 	Flow_Type__c =: PWDLESS_EMAIL_VERIFICATION
                                                                                	AND 	Verification_Method__c =: EMAIL];
        if(!pwdlessEmailVerifRequestList.isEmpty()){
            pwdlessEmailVerifRequest.Id = pwdlessEmailVerifRequestList[0].Id;
        } 
        else{
            pwdlessEmailVerifRequest.Flow_Type__c = PWDLESS_EMAIL_VERIFICATION;
            pwdlessEmailVerifRequest.Username__c = userName; 
            pwdlessEmailVerifRequest.Verification_Method__c = EMAIL;
        }
        pwdlessEmailVerifRequest.Status__c = IDENTIFIER_ISSUED;
        pwdlessEmailVerifRequest.Identifier__c = identifier;
        pwdlessEmailVerifRequest.Redirect_Uri__c = redirectUri;
        pwdlessEmailVerifRequest.Locale__c = locale;
        Database.upsert(pwdlessEmailVerifRequest);
    }

    public class CustomException extends Exception {}
    
}