force-app/main/default/objects/Push_Notification_Recipient__c/Push_Notification_Recipient__c.object-meta.xml
<CustomObject>
    <label>Push Notification Recipient</label>
    <nameField>
        <displayFormat>PNR-{0000000}</displayFormat>
        <label>Push Notification Recipient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Push Notification Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Push_Notification_Recipient__c/fields/IsRead__c.field-meta.xml
<CustomField>
    <fullName>IsRead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Push_Notification_Recipient__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Push_Notification_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/MGMT_ZONE_SUB_LEVEL1__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL1__c</fullName>
    <description>Contains the code/translation for the first sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MANAGEMENT_ZONE_LEVEL__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>151</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>1231</fullName>
            </value>
            <value>
                <fullName>1071</fullName>
            </value>
            <value>
                <fullName>1111</fullName>
            </value>
            <value>
                <fullName>1151</fullName>
            </value>
            <value>
                <fullName>1191</fullName>
            </value>
            <value>
                <fullName>1271</fullName>
            </value>
            <value>
                <fullName>1311</fullName>
            </value>
            <value>
                <fullName>1351</fullName>
            </value>
            <value>
                <fullName>1391</fullName>
            </value>
            <value>
                <fullName>391</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MP_Mark_as_read_China_PushNotifications.cls
public with sharing class MP_Mark_as_read_China_PushNotifications implements Database.Batchable<sObject>{

    String query;

    public MP_Mark_as_read_China_PushNotifications() {
        //TO REMOVE 'System Administrator'
        Map<String,Profile> SAprofiles = new Map<String, Profile> ([SELECT id FROM profile WHERE name in ('ICON_SA', 'ICON_SA Manager', 'ICON_SAManager_EVERYWHERE','System Administrator')]);
        Set<String> SAprofilesIds = SAprofiles.keySet();
        query = 'SELECT id, IsRead__c from Push_Notification_Recipient__c WHERE IsRead__c = False AND CreatedDate < LAST_N_DAYS:7 AND UserId__c IN (SELECT Id FROM User WHERE MGMT_ZONE_SUB_LEVEL1__c = \'1071\' AND DefaultStore__c <> NULL  AND IsActive = true AND ProfileId IN (' + listToString(SAprofilesIds) +'))';
    }

    public Database.QueryLocator start(Database.BatchableContext BC){

        return Database.getQueryLocator(query);

    }
  
    public void execute(Database.BatchableContext BC, List<sObject> notifications){
        List<Push_Notification_Recipient__c> notificationToUpdate = new List<Push_Notification_Recipient__c>();
        for(sObject notif : notifications){
            Push_Notification_Recipient__c pushNotification = (Push_Notification_Recipient__c) notif;
            pushNotification.IsRead__c = true;
            notificationToUpdate.add(pushNotification);
        }
        update notificationToUpdate;
    }

    public void finish(Database.BatchableContext BC){

    }

    public static String listToString (Set<String> stringSet){
        List<String> stringList = new List<String>();
        stringList.addAll(stringSet);
        return '\''+ String.join(stringList, '\',\'') + '\'';
    }

}