force-app/main/default/objects/Opportunity/fields/ApplicationSource__c.field-meta.xml
<CustomField>
    <fullName>ApplicationSource__c</fullName>
    <description>Application where the opportunity is created : PERSO / SPO (Special Order) / ECO (ecommerce LV.com)</description>
    <label>Application Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SPO</fullName>
            </value>
            <value>
                <fullName>PERSO</fullName>
            </value>
            <value>
                <fullName>ECO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DepositReceived__c.field-meta.xml
<CustomField>
    <fullName>DepositReceived__c</fullName>
    <formula>(SPO_XstoreDeposit__c &gt;= SPO_DepositAmount__c)</formula>
    <label>DepositReceived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_Store__c.field-meta.xml
<CustomField>
    <fullName>SPO_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/CheckXstoreDeposit__c.field-meta.xml
<CustomField>
    <fullName>CheckXstoreDeposit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For activation of validation of deposit using deposit received from Xstore</description>
    <label>CheckXstoreDeposit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateOpportunityBatch.cls
public class UpdateOpportunityBatch implements Database.Batchable<SObject>, Database.Stateful {
    public Database.QueryLocator start(Database.BatchableContext context) {
        // Calculate the date and time 24 hours ago
        DateTime twentyFourHoursAgo = System.now().addDays(-1);
        String formattedDateTime = twentyFourHoursAgo.format('yyyy-MM-dd\'T\'HH:mm:ss.SSSZ');
         System.debug('Formatted DateTime: ' + formattedDateTime);

        // Set your query here
        String query = 'SELECT Id FROM Opportunity WHERE SPO_Store__r.CheckXstoreDeposit__c = true AND CreatedDate <= '+formattedDateTime+' AND StageName = \'Creation in progress\' AND DepositReceived__c = false and ApplicationSource__c =\'PERSO\'';
        System.debug(' query: ' + query);
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext context, List<Opportunity> opportunities) {
        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
        for (Opportunity opp : opportunities) {
            SPO_FirmOrderControllerLC.cancelFirmOrderDB(opp.Id,'Automated process','Production - Other','Deposit not received from Xstore after 24 hours') ;
            opportunitiesToUpdate.add(opp);
        }
        
        // Update the records
        update opportunitiesToUpdate;
    }

    public void finish(Database.BatchableContext context) {
        
    }

}