force-app/main/default/objects/Opportunity/fields/ApplicationSource__c.field-meta.xml
<CustomField>
    <fullName>ApplicationSource__c</fullName>
    <description>Application where the opportunity is created : PERSO / SPO (Special Order) / ECO (ecommerce LV.com)</description>
    <label>Application Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SPO</fullName>
            </value>
            <value>
                <fullName>PERSO</fullName>
            </value>
            <value>
                <fullName>ECO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_Store__c.field-meta.xml
<CustomField>
    <fullName>SPO_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/SPO_FirmOrder__c.object-meta.xml
<CustomObject>
    <description>All informations about about customization, quote, order following</description>
    <label>Order Line Item</label>
    <nameField>
        <label>Firm Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPO_FirmOrder__c/fields/ProductionInProgressDate__c.field-meta.xml
<CustomField>
    <fullName>ProductionInProgressDate__c</fullName>
    <label>ProductionInProgressDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/SPO_BriefName__c.field-meta.xml
<CustomField>
    <fullName>SPO_BriefName__c</fullName>
    <label>Order name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>SpeOrder_Order_Following</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/SPO_FirmOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>SPO_FirmOrderStatus__c</fullName>
    <label>Firm Order status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Creation in progress</fullName>
                <default>true</default>
                <label>Creation in progress</label>
            </value>
            <value>
                <fullName>Production in progress</fullName>
            </value>
            <value>
                <fullName>Distribution in progress</fullName>
            </value>
            <value>
                <fullName>Received in store</fullName>
            </value>
            <value>
                <fullName>Cancelled by production</fullName>
            </value>
            <value>
                <fullName>Cancelled by store</fullName>
            </value>
            <value>
                <fullName>Sent to MyPR</fullName>
            </value>
            <value>
                <fullName>Product delivered to client</fullName>
            </value>
            <value>
                <fullName>Technical error order</fullName>
            </value>
            <value>
                <fullName>Cancelled - Migrated in Xstore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task/recordTypes/To_Do_Assistant.recordType-meta.xml
<RecordType>
    <fullName>To_Do_Assistant</fullName>
    <active>true</active>
    <label>To Do Assistant</label>
</RecordType>

force-app/main/default/classes/BL_ICON_Batch_NY_OrdersTodos.cls
global with sharing class BL_ICON_Batch_NY_OrdersTodos implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    /* ICON requirement - creation of a todo Assitant task 4 & 9 months after hitting the PRODUCTION IN PROGRESS status */

    public String query;
    public static final Id TaskTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('To_Do_Assistant').getRecordTypeId();
  

    global BL_ICON_Batch_NY_OrdersTodos() {

        String progress9months = DateTime.now().addMonths(-9).format('yyyy-MM-dd');
        String progress4months = DateTime.now().addMonths(-4).format('yyyy-MM-dd');

        query =  'SELECT SPO_BriefName__r.SPO_Store__r.ISO3_Code__c ,SPO_BriefName__r.Owner.Is_Store_User__c  , SPO_FirmOrderStatus__c ,Id ,SPO_BriefName__c,SPO_BriefName__r.ApplicationSource__c, SPO_BriefName__r.OwnerId ,SPO_BriefName__r.Owner.IsTechnicalUser__c, SPO_BriefName__r.SPO_Store__c, SPO_BriefName__r.Account.PersonContactId FROM SPO_FirmOrder__c WHERE  SPO_BriefName__r.ApplicationSource__c =\'SPO\' AND (ProductionInProgressDate__c ='+ progress9months +' OR ProductionInProgressDate__c='+progress4months+')';
      
        system.debug(query);

    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('#### START - BL_ICON_Batch_NY_OrdersTodos');
        System.debug('#### QUERY : ' + query);

        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        try{

            Map<String,String>  TechnicalUsers = ICON_Todos_Helper.getTechnicalUsers();

        
            List<Task> lstTask = new List<Task>();
            for(sObject o : scope){
            	SPO_FirmOrder__c order = (SPO_FirmOrder__c) o;
            	String todoCode = '';
                todoCode = order.ProductionInProgressDate__c == Date.today().addMonths(-9) ? 'TD_NY_06' : 'TD_NY_05';
                lstTask.add(ICON_Todos_Helper.createToDoTaskFirmOrderNowYours(order,TechnicalUsers ,'Production in progress', todoCode));              	
            }               
            database.insert(lstTask,false);
        
        }
        catch(Exception e) {
            
        }
    }
    
    
    global void finish(Database.BatchableContext CD){}
    

}