force-app/main/default/objects/Opportunity/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Value set when the opportunity is created:
=  &apos;P&apos; + 7 numbers (if application source = PERSO)
= &apos;SP&apos; + 7 numbers (if application source = SPO)
= To Be Defined for LV.com (number visible to client?)
Perso and SPO will have the same index (starts with 0300000). 
By Workflow, when the Opportyunity is created, set the value with P or SP (depending on application source) and concatenate with Opportunity.SPO_BriefCode__c (by sure to have 7 digits)</description>
    <label>Order Number</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_DepositAmount__c.field-meta.xml
<CustomField>
    <fullName>SPO_DepositAmount__c</fullName>
    <label>Deposit amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_DepositSentStatusDate__c.field-meta.xml
<CustomField>
    <fullName>SPO_DepositSentStatusDate__c</fullName>
    <label>Deposit sent status date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_EstimatedProductionTimeMonths__c.field-meta.xml
<CustomField>
    <fullName>SPO_EstimatedProductionTimeMonths__c</fullName>
    <label>Estimated production time (weeks)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_StopBriefReason__c.field-meta.xml
<CustomField>
    <fullName>SPO_StopBriefReason__c</fullName>
    <label>Stop order reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client - Price</fullName>
            </value>
            <value>
                <fullName>Client - Leadtime too long</fullName>
            </value>
            <value>
                <fullName>Client - Do not answer client need</fullName>
            </value>
            <value>
                <fullName>Client - Client decision</fullName>
            </value>
            <value>
                <fullName>Production - Reject by supply-chain</fullName>
                <label>Production - Liaise with your local supply chain</label>
            </value>
            <value>
                <fullName>Production - Not complient with LV code</fullName>
            </value>
            <value>
                <fullName>Production - Technically not feasible</fullName>
            </value>
            <value>
                <fullName>Production - Transferred / Rebalancing</fullName>
            </value>
            <value>
                <fullName>Production - Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_XstoreDeposit__c.field-meta.xml
<CustomField>
    <fullName>SPO_XstoreDeposit__c</fullName>
    <description>Amount received from Xstore</description>
    <label>Deposit from Xstore</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Workshop__c.field-meta.xml
<CustomField>
    <fullName>Workshop__c</fullName>
    <label>Workshop</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Workshop</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCatalogue__c/fields/Workshop__c.field-meta.xml
<CustomField>
    <fullName>Workshop__c</fullName>
    <defaultValue>(&quot;0000&quot;)</defaultValue>
    <description>Manufacturing workshop code
(used for JDE system to know in which workshop the product should be sent)
For Perso app, value is set to 11202 (in product creation) but can be changed
Default value changed to 0000 on MIY-2062</description>
    <label>Workshop</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Workshop</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/SPO_FirmOrder__c.object-meta.xml
<CustomObject>
    <description>All informations about about customization, quote, order following</description>
    <label>Order Line Item</label>
    <nameField>
        <label>Firm Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPO_FirmOrder__c/fields/ProductCatalogue__c.field-meta.xml
<CustomField>
    <fullName>ProductCatalogue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product used for PERSO app</description>
    <label>Product Catalogue</label>
    <referenceTo>ProductCatalogue__c</referenceTo>
    <relationshipName>Firm_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/SPO_FirmOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>SPO_FirmOrderStatus__c</fullName>
    <label>Firm Order status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Creation in progress</fullName>
                <default>true</default>
                <label>Creation in progress</label>
            </value>
            <value>
                <fullName>Production in progress</fullName>
            </value>
            <value>
                <fullName>Distribution in progress</fullName>
            </value>
            <value>
                <fullName>Received in store</fullName>
            </value>
            <value>
                <fullName>Cancelled by production</fullName>
            </value>
            <value>
                <fullName>Cancelled by store</fullName>
            </value>
            <value>
                <fullName>Sent to MyPR</fullName>
            </value>
            <value>
                <fullName>Product delivered to client</fullName>
            </value>
            <value>
                <fullName>Technical error order</fullName>
            </value>
            <value>
                <fullName>Cancelled - Migrated in Xstore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/SPO_TechETLStatus__c.field-meta.xml
<CustomField>
    <fullName>SPO_TechETLStatus__c</fullName>
    <description>ETL status for JDE/Fiesso(SAP Shoes)/MyPR

&quot;V&quot; : Validated (for Perso orders only). Pending orders to wait 3 days as the client can cancel his order.
&quot;STOCK&quot;: Perso Order ready to be sent to MyPR (after V status)
&quot;S&quot; : Perso order (Souliers product) ready to be sent to SAP Fiesso (after V status)

ETL execution in 3 steps for JDE: Batch creation =&gt; Order creation =&gt; Purchase creation
&quot;A&quot;: Order ready to be sent to JDE (when Opportunity.stageName becomes &apos;Creation in progress&apos; for SPO or 3 days after creation for Perso orders)
&quot;B&quot;: ETL return: Batch creation failure
&quot;C&quot;: ETL return: Batch created with success
&quot;D&quot;: ETL return: Order creation failure
&quot;E&quot;: ETL return: Order created with success
&quot;F&quot;: ETL return: Purchase creation failure
&quot;I&quot;: incorrect/incomplete order for JDE
&quot;Y&quot;: ETL Success (creation in success for JDE / Fiesso / MyPR)
&quot;PAP_ART&quot;: ETL return: Order article sent to SAP
&quot;PAP_ARTE&quot;: ETL return: Sending of article to SAP failed</description>
    <label>ETL Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Order ready to be sent to JDE and SAP FMS</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>ETL/JDE: Batch creation failure</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>ETL/JDE: Batch created with success</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>ETL/JDE: Sale order creation failure</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>ETL/JDE: Sale order created with success</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>Perso order validated</label>
            </value>
            <value>
                <fullName>STOCK</fullName>
                <label>Perso order ready to be sent to MyPR</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>S - Perso order (Shoes) ready to be sent to SAP Fiesso</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>Order sent with success</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>Incorrect Order for JDE</label>
            </value>
            <value>
                <fullName>LG_SOE</fullName>
                <label>LG_SOE Error during export to SAP FMS</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>R - Reprint order for Shoes</label>
            </value>
            <value>
                <fullName>J</fullName>
                <label>J - SKU does not exist on SPP</label>
            </value>
            <value>
                <fullName>LG_SO</fullName>
                <label>LG_SO - Printing order sent to SAP FMS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/User/fields/BypassVR__c.field-meta.xml
<CustomField>
    <fullName>BypassVR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Xstore_APITest.cls
@isTest
public class Xstore_APITest { //MIY-2092
      
    public static User getAdminUser() {
        User adminUser = ICX_TestFactory.createUser(ICX_TestFactory.PROFILE_SYSTEM_ADMINNISTRATOR);
        adminUser.BypassVR__c = true;
        return adminUser;
    }
    
    private static User adminUser = getAdminUser();
    
    @IsTest
    // Running as Admin
    static void testXstoreCreateAmount() {
        User adminUser = adminUser;
        System.runAs(adminUser) {
            Opportunity objOpportunity = new Opportunity();
            objOpportunity.Name = 'Test Opp';
            objOpportunity.CloseDate = system.Today() + 3;
            objOpportunity.SPO_DepositAmount__c = 12345;
            objOpportunity.SPO_XstoreDeposit__c = null;
            objOpportunity.StageName = 'Closed Won';
            insert objOpportunity;
            Opportunity thisOppDeposit = [
                SELECT Id, SPO_DepositAmount__c, SPO_XstoreDeposit__c, OrderNumber__c
                FROM Opportunity
            ];
            
            RestRequest request = new RestRequest();
            RestResponse res = new RestResponse();
            request.requestUri =
                'https://louisvuitton--pprod.my.salesforce.com/services/apexrest/Opportunity/' +
                thisOppDeposit.OrderNumber__c;
            RestContext.request = request;
            RestContext.response = res;
            
            request.httpMethod = 'PATCH';
            request.addHeader('Content-type', 'application/json');
            request.requestBody = Blob.valueOf('{"DepositAmount": 12345}');
            RestContext.request = request;
            Test.setMock(HttpCalloutMock.class, new Xstore_APIHTTPCalloutMock());
            Test.startTest();
            Xstore_API.updateOpportunityAmount();
            Test.stopTest();
        }
    }
    
    @IsTest
    static void testXstoreUpdateAmount() {
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.Name = 'Test Opp';
        objOpportunity.CloseDate = system.Today() + 3;
        objOpportunity.SPO_DepositAmount__c = 12345;
        objOpportunity.SPO_XstoreDeposit__c = 800;
        objOpportunity.StageName = 'Closed Won';
        insert objOpportunity;
        Opportunity thisOppDeposit = [
            SELECT Id, SPO_DepositAmount__c, SPO_XstoreDeposit__c, OrderNumber__c
            FROM Opportunity
        ];
        
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri =
            'https://louisvuitton--pprod.my.salesforce.com/services/apexrest/Opportunity/' +
            thisOppDeposit.OrderNumber__c;
        RestContext.request = request;
        RestContext.response = res;
        
        request.httpMethod = 'PATCH';
        request.addHeader('Content-type', 'application/json');
        request.requestBody = Blob.valueOf('{"DepositAmount": 12345}');
        RestContext.request = request;
        Test.setMock(HttpCalloutMock.class, new Xstore_APIHTTPCalloutMock());
        Test.startTest();
        Xstore_API.updateOpportunityAmount();
        Test.stopTest();
    }
    
    @IsTest
    static void testXstoreQueryException() {
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri = 'https://louisvuitton--pprod.my.salesforce.com/services/apexrest/Opportunity/invalid';
        RestContext.request = request;
        RestContext.response = res;
        
        request.httpMethod = 'PATCH';
        request.addHeader('Content-type', 'application/json');
        request.requestBody = Blob.valueOf('{"DepositAmount": 12345}');
        RestContext.request = request;
        Test.setMock(HttpCalloutMock.class, new Xstore_APIHTTPCalloutMock());
        Test.startTest();
        Xstore_API.updateOpportunityAmount();
        Test.stopTest();
    }
    
    @IsTest
    static void testXstoreCreateAmountException() {
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.Name = 'Test Opp';
        objOpportunity.CloseDate = system.Today() + 3;
        objOpportunity.SPO_DepositAmount__c = 12345;
        objOpportunity.SPO_XstoreDeposit__c = null;
        objOpportunity.StageName = 'Closed Won';
        insert objOpportunity;
        Opportunity thisOppDeposit = [
            SELECT Id, SPO_DepositAmount__c, SPO_XstoreDeposit__c, OrderNumber__c
            FROM Opportunity
        ];
        
        System.debug('ulhaaa' + thisOppDeposit);
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri =
            'https://louisvuitton--pprod.my.salesforce.com/services/apexrest/Opportunity/' +
            thisOppDeposit.OrderNumber__c;
        RestContext.request = request;
        RestContext.response = res;
        
        request.httpMethod = 'PATCH';
        request.addHeader('Content-type', 'application/json');
        request.requestBody = Blob.valueOf('{"DepositAmount": 999}');
        RestContext.request = request;
        Test.setMock(HttpCalloutMock.class, new Xstore_APIHTTPCalloutMock());
        Test.startTest();
        Xstore_API.updateOpportunityAmount();
        Test.stopTest();
    }
    
    @IsTest
    static void testXstoreNotZeroDepositCreationInProgress() {
        //MIY-2092 Starts here
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.Name = 'Test Opp';
        objOpportunity.CloseDate = system.Today() + 3;
        objOpportunity.SPO_DepositAmount__c = 12345;
        objOpportunity.SPO_XstoreDeposit__c = 5000;
        objOpportunity.StageName = 'Creation in progress';
        objOpportunity.OrderNumber__c = 'P1234567';
        insert objOpportunity;
        Opportunity thisOppDeposit = [
            SELECT Id, SPO_DepositAmount__c, SPO_XstoreDeposit__c, OrderNumber__c
            FROM Opportunity
        ];
        
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri =
            'https://louisvuitton--pprod.my.salesforce.com/services/apexrest/Opportunity/' +
            thisOppDeposit.OrderNumber__c;
        RestContext.request = request;
        RestContext.response = res;
        
        request.httpMethod = 'PATCH';
        request.addHeader('Content-type', 'application/json');
        request.requestBody = Blob.valueOf('{"depositAmount": 0}');
        RestContext.request = request;
        Test.setMock(HttpCalloutMock.class, new Xstore_APIHTTPCalloutMock());
        Test.startTest();
        Xstore_API.updateOpportunityAmount();
        Test.stopTest();
    }
    
    @IsTest
    static void testXstoreNotZeroDepositCancelledByStore() {
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.Name = 'Test Opp';
        objOpportunity.CloseDate = system.Today() + 3;
        objOpportunity.SPO_DepositAmount__c = 12345;
        objOpportunity.SPO_XstoreDeposit__c = 5000;
        objOpportunity.StageName = 'Cancelled by store';
        objOpportunity.SPO_StopBriefReason__c = 'Test Cancel';
        insert objOpportunity;
        Opportunity thisOppDeposit = [
            SELECT Id, SPO_DepositAmount__c, SPO_XstoreDeposit__c, OrderNumber__c
            FROM Opportunity
        ];
        
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri =
            'https://louisvuitton--pprod.my.salesforce.com/services/apexrest/Opportunity/' +
            thisOppDeposit.OrderNumber__c;
        RestContext.request = request;
        RestContext.response = res;
        
        request.httpMethod = 'PATCH';
        request.addHeader('Content-type', 'application/json');
        request.requestBody = Blob.valueOf('{"depositAmount": 0}');
        RestContext.request = request;
        Test.setMock(HttpCalloutMock.class, new Xstore_APIHTTPCalloutMock());
        Test.startTest();
        Xstore_API.updateOpportunityAmount();
        Test.stopTest();
    }
    
    @IsTest
    static void testXstoreNotZeroDepositFailCancel() {
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.Name = 'Test Opp';
        objOpportunity.CloseDate = system.Today() + 3;
        objOpportunity.SPO_DepositAmount__c = 12345;
        objOpportunity.SPO_XstoreDeposit__c = 5000;
        objOpportunity.StageName = 'Distribution in progress';
        insert objOpportunity;
        Opportunity thisOppDeposit = [
            SELECT Id, SPO_DepositAmount__c, SPO_XstoreDeposit__c, OrderNumber__c
            FROM Opportunity
        ];
        
        RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri =
            'https://louisvuitton--pprod.my.salesforce.com/services/apexrest/Opportunity/' +
            thisOppDeposit.OrderNumber__c;
        RestContext.request = request;
        RestContext.response = res;
        
        request.httpMethod = 'PATCH';
        request.addHeader('Content-type', 'application/json');
        request.requestBody = Blob.valueOf('{"DepositAmount": 0}');
        RestContext.request = request;
        Test.setMock(HttpCalloutMock.class, new Xstore_APIHTTPCalloutMock());
        Test.startTest();
        Xstore_API.updateOpportunityAmount();
        Test.stopTest();
    }
    
    @IsTest
    // Running as Admin
    static void testXstoreCreateFirmOrderCannotCancel() {
        User adminUser = adminUser;
        System.runAs(adminUser) {
            FirmOrderTriggerHandler_TEST helper = new FirmOrderTriggerHandler_TEST();
            Store__c st = LV_TestFactory.createStore(
                'LV TEST STORE MIY',
                'Store',
                'A00',
                'FRANCE',
                'EUR',
                'Open'
            );
            st.MANAGEMENT_ZONE_LEVEL__c = '15';
            insert st;
            
            // create a client
            Account client = LV_TestFactory.createAccount();
            insert client;
            
            // create a non exotic product catalog
            ProductCatalogue__c pc = LV_TestFactory.createProductCatalog(
                'MY NEVERFULL',
                'P0001',
                3,
                15,
                5,
                'Leather Goods'
            );
            pc.Workshop__c = '1798';
            insert pc;
            
            Opportunity spoOrder = LV_TestFactory.createOrder(
                'SPO_1',
                'Distribution in progress',
                null,
                st.id,
                client.id,
                null,
                null,
                'SPO'
            );
            spoOrder.SPO_DepositSentStatusDate__c = System.today();
            spoOrder.SPO_EstimatedProductionTimeMonths__c = 1;
            spoOrder.SPO_DepositAmount__c = 12345;
            spoOrder.SPO_XstoreDeposit__c = null;
            insert spoOrder;
            List<Opportunity> opps = [
                SELECT OrderNumber__c
                FROM Opportunity
                WHERE Id = :spoOrder.Id
            ];
            String orderNumber;
            if (opps.size() > 0) {
                orderNumber = opps[0].OrderNumber__c;
            }
            
            // create a firm order
            SPO_FirmOrder__c fo = LV_TestFactory.createFirmOrder(spoOrder.id, 1, pc.id);
            fo.SPO_FirmOrderStatus__c = 'Distribution in progress';
            fo.SPO_TechETLStatus__c = 'A';
            insert fo;
            
            fo = [
                SELECT Id, SPO_FirmOrderStatus__c, SPO_TechETLStatus__c
                FROM SPO_FirmOrder__c
                WHERE Id = :fo.Id
            ];
            
            RestRequest request = new RestRequest();
            RestResponse res = new RestResponse();
            request.requestUri =
                'https://louisvuitton--pprod.my.salesforce.com/services/apexrest/Opportunity/' +
                orderNumber;
            
            RestContext.request = request;
            RestContext.response = res;
            
            request.httpMethod = 'PATCH';
            request.addHeader('Content-type', 'application/json');
            request.requestBody = Blob.valueOf('{"depositAmount": 12345}');
            RestContext.request = request;
            Test.setMock(HttpCalloutMock.class, new Xstore_APIHTTPCalloutMock());
            Test.startTest();
            Xstore_API.updateOpportunityAmount();
            Test.stopTest();
        }
    }
}