force-app/main/default/objects/Opportunity/fields/SPO_OrderType__c.field-meta.xml
<CustomField>
    <fullName>SPO_OrderType__c</fullName>
    <label>Order type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPO_ProductCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Creation (Hardsided &amp; Soft)</fullName>
            </value>
            <value>
                <fullName>MTO on Catalog (Hardsided)</fullName>
            </value>
            <value>
                <fullName>SPO/MTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>SPO_ProductCategory__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hardsided leather goods</fullName>
            </value>
            <value>
                <fullName>Softsided leather goods</fullName>
            </value>
            <value>
                <fullName>Belts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SO_QuotationContainer.cls
public class SO_QuotationContainer {
    
	public SO_QuotationContainer() { }
        
	public Opportunity oneOpportunity 	{get; set;} 
	public String opportunityOrderType	{get; set;}
    
    public SO_UTIL.PickListWrapper productCategory	 { 

		get {
			if(null == productCategory) {
				productCategory = new SO_UTIL.PickListWrapper('Opportunity', 'SPO_ProductCategory__c', null,oneOpportunity);
			}
			return productCategory;
		} 
		set; 
	}
    
    public SO_UTIL.PickListWrapper orderType {
        
        get {
			if(null == orderType) {
				orderType = new SO_UTIL.PickListWrapper('Opportunity', 'SPO_OrderType__c', null,oneOpportunity);
			}
			return orderType;
		} 
		set; 
    }

    public List<Attachment> attachmentList { get; set; }

    public Map<String,String> colorNameToCodeMap { get; set; }
}