force-app/main/default/objects/Opportunity/fields/SPO_BaseSKURefmodelSKU__c.field-meta.xml
<CustomField>
    <fullName>SPO_BaseSKURefmodelSKU__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Base SKU (Ref. model SKU)</label>
    <referenceTo>ProductReferential__c</referenceTo>
    <relationshipLabel>Brief</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_CreationType__c.field-meta.xml
<CustomField>
    <fullName>SPO_CreationType__c</fullName>
    <label>Hardsided or Soft ?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPO_ProductCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Hardsided</fullName>
            </value>
            <value>
                <fullName>Soft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_OrderType__c.field-meta.xml
<CustomField>
    <fullName>SPO_OrderType__c</fullName>
    <label>Order type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SPO_ProductCategory__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Creation (Hardsided &amp; Soft)</fullName>
            </value>
            <value>
                <fullName>MTO on Catalog (Hardsided)</fullName>
            </value>
            <value>
                <fullName>SPO/MTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>SPO_ProductCategory__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hardsided leather goods</fullName>
            </value>
            <value>
                <fullName>Softsided leather goods</fullName>
            </value>
            <value>
                <fullName>Belts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_SpecialOrderSKUCodeRef__c.field-meta.xml
<CustomField>
    <fullName>SPO_SpecialOrderSKUCodeRef__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Special Order SKU Code Ref</label>
    <referenceTo>ProductReferential__c</referenceTo>
    <relationshipLabel>Opportunities (Special Order SKU Code Ref)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCatalogue__c/fields/FluidRecipeId__c.field-meta.xml
<CustomField>
    <fullName>FluidRecipeId__c</fullName>
    <description>Recipe id for Fluid app</description>
    <label>Fluid Recipe Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/ProductReferential__c.field-meta.xml
<CustomField>
    <fullName>ProductReferential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to ProductReferential. Lookup needed to get some information provided by ProductReferential object (SAP) and not in BCC (ETL / sku.json)</description>
    <label>Product Referential</label>
    <referenceTo>ProductReferential__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductCategory__c/ProductCategory__c.object-meta.xml
<CustomObject>
    <description>Junction object between Category__c and ProductCatalogue__c</description>
    <label>Product Category</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Product Category Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Categories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductReferential__c/ProductReferential__c.object-meta.xml
<CustomObject>
    <description>All information about base product</description>
    <label>Product Referential</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Referential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductReferential__c/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Leather goods</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Ready to wear</fullName>
            </value>
            <value>
                <fullName>Shoes</fullName>
            </value>
            <value>
                <fullName>Perfume</fullName>
            </value>
            <value>
                <fullName>Jewelry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductReferential__c/fields/SKUCode__c.field-meta.xml
<CustomField>
    <fullName>SKUCode__c</fullName>
    <externalId>true</externalId>
    <label>Base SKU Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/SPO_FirmOrder__c.object-meta.xml
<CustomObject>
    <description>All informations about about customization, quote, order following</description>
    <label>Order Line Item</label>
    <nameField>
        <label>Firm Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPO_FirmOrder__c/fields/FluidRecipeId__c.field-meta.xml
<CustomField>
    <fullName>FluidRecipeId__c</fullName>
    <description>Fluid id</description>
    <externalId>true</externalId>
    <label>Fluid Recipe Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <description>Line number for the Firm Order
- if BriefName__r.ApplicationSource__c = &apos;SPO&apos;, value depends on brief quantity (example: if BriefName__r.SPO_SkuQuantity__c = 3, 3 firm orders will be created with LineNumber__c = 1, 2 or 3)
- if BriefName__r.ApplicationSource__c = &apos;PERSO&apos;, value depends on products and their quantity (example: if 2 products are ordered with quantity =1 for Product1 and quantity=2 for Product2, 3 firm orders are created with LineNumber__c = 1, 2 or 3)</description>
    <label>Line Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/ProductCatalogue__c.field-meta.xml
<CustomField>
    <fullName>ProductCatalogue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product used for PERSO app</description>
    <label>Product Catalogue</label>
    <referenceTo>ProductCatalogue__c</referenceTo>
    <relationshipName>Firm_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/ProductCategory__c.field-meta.xml
<CustomField>
    <fullName>ProductCategory__c</fullName>
    <description>Product category depends on ProductCatalogue__c value (Perso order) or SPO
Used for JDE/ETL</description>
    <formula>IF 
(
	NOT(ISBLANK(ProductCatalogue__c)),
	IF(ProductCatalogue__r.SPO_Category__c == &apos;BELTS&apos;, &apos;Accessories&apos;, ProductCatalogue__r.SPO_Category__c), 
          /*PERSO: displaying Accessories instead of Belts in order to macth ETL query */
	IF
	(
		ISPICKVAL(SPO_BriefName__r.SPO_ProductCategory__c, &apos;Belts&apos;), &apos;Accessories&apos;, 
		TEXT(SPO_BriefName__r.SPO_ProductCategory__c)
	) /* SPO: displaying Accessories instead of Belts in order to macth ETL query */
)</formula>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/SPO_BriefName__c.field-meta.xml
<CustomField>
    <fullName>SPO_BriefName__c</fullName>
    <label>Order name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>SpeOrder_Order_Following</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/classes/SO_ProductController_TEST.cls
@isTest
private class SO_ProductController_TEST {

	@testSetup
	public static void setup(){

		List<Store__c> ls = new List<Store__c>();
		ls.add(new Store__c (Name='ST1', RetailStoreId__c='ST1'));
		ls.add(new Store__c (Name='ST2', RetailStoreId__c='ST2'));
		ls.add(new Store__c (Name='ST3', RetailStoreId__c=''));

		insert ls;

		ProductReferential__c p = new ProductReferential__c(SKUCode__c = 'SKU1');
		insert p;
	}

	@isTest
	public static void test_getUserStr(){
		String uJSON = SO_ProductController.getUserStr();
		User u = (User) JSON.deserialize(uJSON, User.class);
		System.assertEquals(UserInfo.getUserId(), u.id);
	}

	@isTest
	public static void test_getStoreNoStore(){

		Test.startTest();

		ProductReferential__c p = [SELECT id FROM ProductReferential__c WHERE SKUCode__c = 'SKU1' LIMIT 1];

		try{
			String stockJSON = SO_ProductController.getStock(p.id, 'ST0');
			System.assert(false, 'The exception should be thrown');
		} catch (Exception e){
			System.debug('1 - e.getMessage() = ' + e.getMessage());
			System.AssertEquals('Store not found', e.getMessage());
		}

		try{
			String stockJSON = SO_ProductController.getStock(p.id, '');
			System.assert(false, 'The exception should be thrown');
		} catch (Exception e){
			System.debug('2 - e.getMessage() = ' + e.getMessage());
			//System.AssertEquals('Store not found', e.getMessage());
		}

		try{
			String stockJSON = SO_ProductController.getStock(p.id, 'ST3');
			System.assert(false, 'The exception should be thrown');
		} catch (Exception e){
			System.debug('3 - e.getMessage() = ' + e.getMessage());
			System.AssertEquals('No store selected', e.getMessage());
		}

		try{ //
			String stockJSON = SO_ProductController.getStock(p.id, 'ST4');
			System.assert(false, 'The exception should be thrown');
		} catch (Exception e){
			System.debug('4 - e.getMessage() = ' + e.getMessage());
			System.assertEquals('Store not found', e.getMessage());
		}

		// try{ //
		// 	String stockJSON = SO_ProductController.getStock(p.id, null);
		// 	System.assert(false, 'The exception should be thrown');
		// } catch (Exception e){
		// 	System.debug('5 - e.getMessage() = ' + e.getMessage());
		// 	System.assertEquals('Store not found', e.getMessage());
		// }

		Test.stopTest();
	}

	@isTest
	public static void test_getStoreNoProduct(){
		Test.starttest();

		try{
			String stockJSON = SO_ProductController.getStock(null, 'ST0');
			System.assert(false, 'The exception should be thrown');
		} catch (Exception e){
			System.AssertEquals('No product selected', e.getMessage());
		}
	}

	@isTest
	public static void test_getStockOneProduct(){

		Test.setMock(WebServiceMock.class, new SO_WS_RMS_DoItemSearch_MOCK());

		Test.startTest();

		ProductReferential__c p = [SELECT id FROM ProductReferential__c WHERE SKUCode__c = 'SKU1' LIMIT 1];
		String stockJSON = SO_ProductController.getStock(p.id, 'ST1');

		Test.stopTest();

		System.assertNotEquals(null, stockJSON);

		List<SO_ProductController.Stock> stockList = (List<SO_ProductController.Stock>)JSON.deserialize(stockJSON, List<SO_ProductController.Stock>.class);

		System.assertEquals(1, stockList.size());

		SO_ProductController.Stock stock = stockList[0];
		System.assertEquals(120, stock.quantity);
		System.assert(stock.sellable);
		System.assertEquals('Status', stock.status);
	}

	@isTest
	public static void test_getProductCategoryJSON(){
		String pCatJSON = SO_ProductController.getProductCategoryJson();
		List<PicklistEntry> pCat = (List<PicklistEntry>) JSON.deserialize(pCatJSON, List<PicklistEntry>.class);
		System.assertEquals(Opportunity.SPO_ProductCategory__c.getDescribe().getPicklistValues().size(), pCat.size());
	}

    @isTest
    public static void test_findBySku(){

      ProductReferential__c p = new ProductReferential__c();
      p.SKUCode__c = 'SIM';

      insert p;

      ProductReferential__c p0 = SO_ProductController.findBySku(p.SKUCode__c);

     	System.assertEquals(p.SKUCode__c, p0.SKUCode__c);

    }

     @isTest
    public static void test_findByOpportunityId(){

        ProductReferential__c p = new ProductReferential__c();
        p.SKUCode__c = 'SIM';
        insert p;


         Opportunity opp  		= new Opportunity();
        opp.Name = 'otest';
        opp.SPO_ProductCategory__c = 'Leather Goods';
        opp.SPO_OrderType__c = 'SPO/MTO';
        opp.SPO_CreationType__c = 'otest';
        opp.StageName = 'Brief in progress';
        opp.CloseDate = Date.today();
        opp.SPO_BaseSKURefmodelSKU__c= p.Id;
        insert opp;

        SO_ProductController.findByOpportunityId(opp.Id);

    }

    @isTest
    public static void test_findBySObjectId(){
        ProductReferential__c p = new ProductReferential__c();
        p.SKUCode__c = 'SIM';
        insert p;

        Opportunity opp  		= new Opportunity();
        opp.Name = 'otest';
        opp.SPO_ProductCategory__c = 'Leather Goods';
        opp.SPO_OrderType__c = 'SPO/MTO';
        opp.SPO_CreationType__c = 'otest';
        opp.StageName = 'Brief in progress';
        opp.CloseDate = Date.today();
        opp.SPO_SpecialOrderSKUCodeRef__c = p.Id;

        insert opp;

       	SPO_FirmOrder__c fo = new SPO_FirmOrder__c();
        //fo.Name = 'fotest';
        fo.LineNumber__c = 0.0;
        fo.SPO_BriefName__c = opp.Id;
       // fo.ProductCatalogue__r.FluidRecipeId__c = '34257080';

        insert fo;

         System.debug('$$$$$$$$$$$$$$$$$$$$$$$$$'+opp.Id);
         System.debug('$$$$$$$$$$$$$$$$$$$$$$$$$'+fo.Id);
        System.debug('$$$$$$$$$$$$$$$$$$$$$$$$$'+p.Id);

        //SO_ProductController.findBySObjectId(opp.Id);
        //SO_ProductController.findBySObjectId(fo.Id);

		ProductReferential__c pr1 = SO_ProductController.findBySObjectId(p.Id);
		ProductReferential__c pr2 = SO_ProductController.findBySObjectId(null);
    }

    @isTest
    public static void test_findAll(){
        String sk = 'abc';
        String c = 'Belts';
        Boolean b = true;
        Decimal ps = 10;
        Decimal pn = 1;

        SO_ProductPagedResult ppr1 = SO_ProductController.findAll(sk, c, b, ps, pn);

        Boolean b0 = false;
        String c0 = '';

        SO_ProductPagedResult ppr2 = SO_ProductController.findAll(sk, c0, b0, ps, pn);

        String sk1 = 'a';
        String c1 = 'Belt';
        Boolean b1 = false;
        Decimal ps1 = 10;
        Decimal pn1 = 1;

        SO_ProductPagedResult ppr3 = SO_ProductController.findAll(sk1, c1, b1, ps1, pn1);

		SO_ProductPagedResult ppr4 = SO_ProductController.findAll(sk1, 'Leather Goods', b1, ps1, pn1);
		SO_ProductPagedResult ppr5 = SO_ProductController.findAll(sk1, 'Hardsided leather goods', b, ps1, pn1);
    }

    @isTest
    public static void test_getUserLocationPickListValues(){
		String objn = 'otest';
      	String objn0 = 'otest';

      	List<String> l = new List<String>();
		l.add(objn);
      	l.add(objn0);

		String picklistJsonValues1 = SO_ProductController.getUserLocationPickListValues(objn, l);
		String picklistJsonValues2 = SO_ProductController.getUserLocationPickListValues('', null);
    }

    @isTest
    public static void test_getProductNotFound(){
		// ProductReferential__c pr1 = new ProductReferential__c(SKUCode__c = 'SIM', Name = 'Pr1', ProductCategory__c = 'Watches');
		ProductReferential__c pr1 = new ProductReferential__c(SKUCode__c = 'SIM');
		insert pr1;

		ProductReferential__c pr2 = SO_ProductController.getProductNotFound();
    }

    @isTest
    public static void test_getProductSettings(){

        SO_ProductController.getProductSettings();

    }

	@isTest
	public static void test_isMTOEnabled(){
		try{
			Boolean isMtoEnabled = SO_ProductController.isMTOEnabled();
			System.assertEquals(isMtoEnabled, true);
			System.assertEquals(isMtoEnabled, false);
		}

		catch(Exception error){
			System.assertEquals('Attempt to de-reference a null object', error.getMessage());
		}
	}
}