force-app/main/default/objects/Opportunity/fields/SPO_CACode__c.field-meta.xml
<CustomField>
    <fullName>SPO_CACode__c</fullName>
    <label>CA code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_Store__c.field-meta.xml
<CustomField>
    <fullName>SPO_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/MGMT_ZONE_SUB_LEVEL1__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL1__c</fullName>
    <description>Contains the code/translation for the first sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MANAGEMENT_ZONE_LEVEL__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>1071</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>151</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/MGMT_ZONE_SUB_LEVEL2__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL2__c</fullName>
    <description>Contains the code/translation for the second sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MGMT_ZONE_SUB_LEVEL1__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>179</fullName>
            </value>
            <value>
                <fullName>219</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>259</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>299</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>379</fullName>
            </value>
            <value>
                <fullName>39</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>41</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
            <value>
                <fullName>43</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>49</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>51</fullName>
            </value>
            <value>
                <fullName>53</fullName>
            </value>
            <value>
                <fullName>54</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/User/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/MGMT_ZONE_SUB_LEVEL1__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL1__c</fullName>
    <description>Contains the code/translation for the first sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MANAGEMENT_ZONE_LEVEL__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>31</fullName>
            </value>
            <value>
                <fullName>32</fullName>
            </value>
            <value>
                <fullName>62</fullName>
            </value>
            <value>
                <fullName>151</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>1231</fullName>
            </value>
            <value>
                <fullName>1071</fullName>
            </value>
            <value>
                <fullName>1111</fullName>
            </value>
            <value>
                <fullName>1151</fullName>
            </value>
            <value>
                <fullName>1191</fullName>
            </value>
            <value>
                <fullName>1271</fullName>
            </value>
            <value>
                <fullName>1311</fullName>
            </value>
            <value>
                <fullName>1351</fullName>
            </value>
            <value>
                <fullName>1391</fullName>
            </value>
            <value>
                <fullName>391</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/MGMT_ZONE_SUB_LEVEL2__c.field-meta.xml
<CustomField>
    <fullName>MGMT_ZONE_SUB_LEVEL2__c</fullName>
    <description>Contains the code/translation for the second sub-level of management hierarchy</description>
    <label>MGMT ZONE SUB LEVEL2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MGMT_ZONE_SUB_LEVEL1__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>43</fullName>
            </value>
            <value>
                <fullName>53</fullName>
            </value>
            <value>
                <fullName>54</fullName>
            </value>
            <value>
                <fullName>68</fullName>
            </value>
            <value>
                <fullName>69</fullName>
            </value>
            <value>
                <fullName>88</fullName>
            </value>
            <value>
                <fullName>97</fullName>
            </value>
            <value>
                <fullName>98</fullName>
            </value>
            <value>
                <fullName>99</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>102</fullName>
            </value>
            <value>
                <fullName>179</fullName>
            </value>
            <value>
                <fullName>219</fullName>
            </value>
            <value>
                <fullName>259</fullName>
            </value>
            <value>
                <fullName>299</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>63</fullName>
            </value>
            <value>
                <fullName>419</fullName>
            </value>
            <value>
                <fullName>2379</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SO_ChoosePath_CTRL.cls
public class SO_ChoosePath_CTRL extends SO_BaseController {

	//--------------------------- Public fields --------------
	public Opportunity 				newOpportunity 		{get; set;}
	public User 					newUser 			{get; private set;}
	public User 					originalUser 		{get; private set;}
	
	private SO_Session.SessionState theSessionState;


	public SO_ChoosePath_CTRL() {
		this.newOpportunity = new Opportunity();
		theSessionState = new SO_Session.SessionState();

		this.newUser = getUser();
		this.originalUser = new User();
		cloneOriginalZonesValues();
	}

	public PageReference redirectToClientSearchPage() {
		PageReference page = null;
		this.showMessageOnTop = true;
		try {
			theSessionState.mode = SO_Session.OrderMode.CLIENT;
			Boolean notDirtyData = changeOpportunity();
			Boolean caCodeValid = verifyCaCodeWS();

			System.debug('SFDC notDirtyData: ' + notDirtyData + ' caCodeValid: ' + caCodeValid);
			if(notDirtyData && caCodeValid)
			{
				SO_Session.saveSession(this.newOpportunity, theSessionState, true);

				page = System.Page.SO_ClientSearch;
				page.getParameters().put('bid', newOpportunity.Id);
				this.showMessageOnTop = false;
			}
			else{SO_UTIL.addErrorMessage(newUser.DefaultStore__c + ': ' + Label.LV_SO_RetailCodeNotFoundErrorMsg);}

			return page;
		} 
		catch(CalloutException ce){SO_UTIL.addErrorMessage(Label.LV_SO_RMS_ERROR);}
		catch(SO_UTIL.RMSException exp){SO_UTIL.addErrorMessage(exp);}
		catch (DMLException exp){SO_UTIL.addErrorMessage(exp.getdmlMessage(0));}
		catch (Exception exp){SO_UTIL.addErrorMessage(exp);}

		return null;
	}

	public PageReference redirectToProductSearchPage() {
		System.debug('SFDC redirectToProductSearchPage');
		PageReference page = null;
		this.showMessageOnTop = true;
		try {
			theSessionState.mode = SO_Session.OrderMode.PRODUCT;
			Boolean notDirtyData = changeOpportunity();
			Boolean caCodeValid = verifyCaCodeWS();

			if(notDirtyData && caCodeValid)
			{
				SO_Session.saveSession(this.newOpportunity, theSessionState, true);

				page = System.Page.SO_ProductSearch;
				page.getParameters().put('bid', newOpportunity.Id);
				this.showMessageOnTop = false;
			}
			else{SO_UTIL.addErrorMessage(newUser.DefaultStore__c + ': ' + Label.LV_SO_RetailCodeNotFoundErrorMsg);}

			return page;
		} 
		catch(CalloutException ce){SO_UTIL.addErrorMessage(Label.LV_SO_RMS_ERROR);}
		catch(SO_UTIL.RMSException exp){SO_UTIL.addErrorMessage(exp);}
		catch (DMLException exp){SO_UTIL.addErrorMessage(exp.getdmlMessage(0));}
		catch (Exception exp){SO_UTIL.addErrorMessage(exp);}

		return null;
	}

	private Boolean changeOpportunity() 
	{ 
		Boolean ans = false;
		this.newOpportunity.StageName = SO_Settings__c.getValues(SO_UTIL.NEW_OPPORTUNITY_STAGENAME_SETTINGS_NAME).Value__c;//SO_OrderPageSwitch.CREATION_IN_PROGRESS;

		this.newOpportunity.CloseDate = Date.today().addDays(Integer.valueOf(SO_Settings__c.getValues(SO_UTIL.NEW_OPPORTUNITY_CLODEDATE_SETTINGS_NAME).Value__c));

		Store__c store = retStrore(newUser.DefaultStore__c);
		if(null != store) 
		{
			this.newOpportunity.SPO_Store__c = store.Id;
			ans = true;				
		}

		return ans;
	}

	private Boolean verifyCaCodeWS()
	{
		System.debug('SFDC verifyCaCodeWS');
		Boolean wsResult = false;
		String codeVarification = Null;

		System.debug('SFDC SPO_CACode__c: ' + this.newOpportunity.SPO_CACode__c + ' newUser.DefaultStore__c: ' + newUser.DefaultStore__c);
		if(this.newOpportunity.SPO_CACode__c != Null && this.newOpportunity.SPO_Store__c != Null){
			SO_ClientAdvisorEnquiryRMS_Utils.SO_ClientAdvisorEnquiryResults calloutResult = SO_ClientAdvisorEnquiryRMS_Utils.VerifyClientAdvisorEnquiryRMS(this.newOpportunity.SPO_CACode__c, newUser.DefaultStore__c);
		}
		wsResult = true;
		return wsResult;
	}

	private static User getUser(){
		return [SELECT MANAGEMENT_ZONE_LEVEL__c, MGMT_ZONE_SUB_LEVEL1__c, MGMT_ZONE_SUB_LEVEL2__c, MGMT_ZONE_SUB_LEVEL3__c, DefaultStore__c
				FROM User
				WHERE Id =:UserInfo.getUserId()];
	}

	private static Store__c retStrore(String retailStoreId){
		List<Store__c> storeList = 
					   	   [SELECT Id, RetailStoreId__c
							  FROM Store__c
							 WHERE RetailStoreId__c =: retailStoreId];

		return !storeList.isEmpty() ? storeList[0] : null;

	}

	private void cloneOriginalZonesValues()
	{
		this.originalUser.MANAGEMENT_ZONE_LEVEL__c = this.newUser.MANAGEMENT_ZONE_LEVEL__c;
		this.originalUser.MGMT_ZONE_SUB_LEVEL1__c = this.newUser.MGMT_ZONE_SUB_LEVEL1__c;
		this.originalUser.MGMT_ZONE_SUB_LEVEL2__c = this.newUser.MGMT_ZONE_SUB_LEVEL2__c;
		this.originalUser.MGMT_ZONE_SUB_LEVEL3__c = this.newUser.MGMT_ZONE_SUB_LEVEL3__c;
	}
}