force-app/main/default/objects/IDENTITY_Registration_Form__mdt/IDENTITY_Registration_Form__mdt.object-meta.xml
<CustomObject>
    <label>IDENTITY - Form</label>
    <pluralLabel>IDENTITY - Forms</pluralLabel>
</CustomObject>

force-app/main/default/objects/IDENTITY_Registration_Form__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>address1</fullName>
            </value>
            <value>
                <fullName>address2</fullName>
            </value>
            <value>
                <fullName>address3</fullName>
            </value>
            <value>
                <fullName>Analytics_TID</fullName>
                <label>Analytics TID</label>
            </value>
            <value>
                <fullName>ATG createConfirmation</fullName>
            </value>
            <value>
                <fullName>ATG creation before SF</fullName>
            </value>
            <value>
                <fullName>birthdate</fullName>
                <label>Birthdate</label>
            </value>
            <value>
                <fullName>calling_code</fullName>
                <label>Calling Code</label>
            </value>
            <value>
                <fullName>city</fullName>
            </value>
            <value>
                <fullName>country</fullName>
                <label>Country</label>
            </value>
            <value>
                <fullName>currency_code</fullName>
                <label>Currency Code</label>
            </value>
            <value>
                <fullName>default_site</fullName>
                <label>Default Site</label>
            </value>
            <value>
                <fullName>email</fullName>
                <label>Email</label>
            </value>
            <value>
                <fullName>email_confirmation</fullName>
                <label>Email Confirmation</label>
            </value>
            <value>
                <fullName>email_template</fullName>
                <label>Email Template</label>
            </value>
            <value>
                <fullName>firstname</fullName>
                <label>Firstname</label>
            </value>
            <value>
                <fullName>firstname2</fullName>
                <label>Firstname (Kana)</label>
            </value>
            <value>
                <fullName>Kakao</fullName>
            </value>
            <value>
                <fullName>lastname</fullName>
                <label>Lastname</label>
            </value>
            <value>
                <fullName>lastname2</fullName>
                <label>Lastname (Kana)</label>
            </value>
            <value>
                <fullName>Line</fullName>
            </value>
            <value>
                <fullName>mobile_phone</fullName>
                <label>Mobile Phone</label>
            </value>
            <value>
                <fullName>Mx</fullName>
            </value>
            <value>
                <fullName>name_max_length</fullName>
                <label>Name Max Length</label>
            </value>
            <value>
                <fullName>newsletter_agreement</fullName>
                <label>Newsletter Agreement</label>
            </value>
            <value>
                <fullName>page_direction</fullName>
                <label>Page direction</label>
            </value>
            <value>
                <fullName>postal_code</fullName>
                <label>Postal Code</label>
            </value>
            <value>
                <fullName>Prefer not to say</fullName>
            </value>
            <value>
                <fullName>privacy_agreement</fullName>
                <label>Privacy Policy Agreement</label>
            </value>
            <value>
                <fullName>Russia creation before SF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IDENTITY_Registration_Form__mdt/fields/Is_Hidden__c.field-meta.xml
<CustomField>
    <fullName>Is_Hidden__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Hidden</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IDENTITY_Registration_Form__mdt/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login</fullName>
                <default>true</default>
                <label>Login</label>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Verification</fullName>
            </value>
            <value>
                <fullName>Settings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IDENTITY_Registration_Form__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Language_Mapping_ATG_SF__mdt/Language_Mapping_ATG_SF__mdt.object-meta.xml
<CustomObject>
    <label>Language Mapping ATG / SF</label>
    <pluralLabel>Languages Mapping ATG / SF</pluralLabel>
</CustomObject>

force-app/main/default/objects/Language_Mapping_ATG_SF__mdt/fields/ATG__c.field-meta.xml
<CustomField>
    <fullName>ATG__c</fullName>
    <label>ATG</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ara-ae</fullName>
            </value>
            <value>
                <fullName>ara-kw</fullName>
            </value>
            <value>
                <fullName>ara-qa</fullName>
            </value>
            <value>
                <fullName>ara-sa</fullName>
            </value>
            <value>
                <fullName>deu-de</fullName>
            </value>
            <value>
                <fullName>eng-ae</fullName>
            </value>
            <value>
                <fullName>eng-au</fullName>
            </value>
            <value>
                <fullName>eng-ca</fullName>
            </value>
            <value>
                <fullName>eng-e1</fullName>
            </value>
            <value>
                <fullName>eng-gb</fullName>
            </value>
            <value>
                <fullName>eng-hk</fullName>
            </value>
            <value>
                <fullName>eng-id</fullName>
            </value>
            <value>
                <fullName>eng-in</fullName>
            </value>
            <value>
                <fullName>eng-kw</fullName>
            </value>
            <value>
                <fullName>eng-nl</fullName>
            </value>
            <value>
                <fullName>eng-qa</fullName>
            </value>
            <value>
                <fullName>eng-sa</fullName>
            </value>
            <value>
                <fullName>eng-sg</fullName>
            </value>
            <value>
                <fullName>eng-us</fullName>
            </value>
            <value>
                <fullName>esp-es</fullName>
            </value>
            <value>
                <fullName>esp-mx</fullName>
            </value>
            <value>
                <fullName>fra-ca</fullName>
            </value>
            <value>
                <fullName>fra-fr</fullName>
            </value>
            <value>
                <fullName>ind-id</fullName>
            </value>
            <value>
                <fullName>ita-it</fullName>
            </value>
            <value>
                <fullName>jpn-jp</fullName>
            </value>
            <value>
                <fullName>kor-kr</fullName>
            </value>
            <value>
                <fullName>por-br</fullName>
            </value>
            <value>
                <fullName>rus-ru</fullName>
            </value>
            <value>
                <fullName>tha-th</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Language_Mapping_ATG_SF__mdt/fields/Salesforce__c.field-meta.xml
<CustomField>
    <fullName>Salesforce__c</fullName>
    <label>Salesforce</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ar_AE</fullName>
            </value>
            <value>
                <fullName>ar_KW</fullName>
            </value>
            <value>
                <fullName>ar_QA</fullName>
            </value>
            <value>
                <fullName>ar_SA</fullName>
            </value>
            <value>
                <fullName>de</fullName>
                <default>true</default>
                <label>de</label>
            </value>
            <value>
                <fullName>default</fullName>
            </value>
            <value>
                <fullName>en</fullName>
            </value>
            <value>
                <fullName>en_AU</fullName>
            </value>
            <value>
                <fullName>en_CA</fullName>
            </value>
            <value>
                <fullName>en_GB</fullName>
            </value>
            <value>
                <fullName>en_HK</fullName>
            </value>
            <value>
                <fullName>en_ID</fullName>
            </value>
            <value>
                <fullName>en_IE</fullName>
            </value>
            <value>
                <fullName>en_IN</fullName>
            </value>
            <value>
                <fullName>en_SG</fullName>
            </value>
            <value>
                <fullName>en_US</fullName>
            </value>
            <value>
                <fullName>en_ZA</fullName>
            </value>
            <value>
                <fullName>es</fullName>
            </value>
            <value>
                <fullName>es_MX</fullName>
            </value>
            <value>
                <fullName>fr</fullName>
            </value>
            <value>
                <fullName>fr_CA</fullName>
            </value>
            <value>
                <fullName>id</fullName>
            </value>
            <value>
                <fullName>it</fullName>
            </value>
            <value>
                <fullName>ja</fullName>
            </value>
            <value>
                <fullName>ko</fullName>
            </value>
            <value>
                <fullName>pt_BR</fullName>
            </value>
            <value>
                <fullName>ru</fullName>
            </value>
            <value>
                <fullName>th</fullName>
            </value>
            <value>
                <fullName>vi</fullName>
            </value>
            <value>
                <fullName>zh_CN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TWIST_Settings__c/TWIST_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TWIST - Settings</label>
</CustomObject>

force-app/main/default/objects/TWIST_Settings__c/fields/Default_Language_Country_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Default_Language_Country_Parameter__c</fullName>
    <label>Default Language Country Parameter</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-twist/main/default/classes/TWIST_Login.cls
/**
* Note: @AuraEnabled with cachebale=false is needed to execute DML statement in a method called from a LWC
* Explaination: https://www.gammone.com/en/programming/how-to-resolve-the-too-many-dml-statements-1-error-in-salesforce
*/

public without sharing class TWIST_Login {

    private static Map<String,Object> componentConfig = new Map<String,Object>();

    private static final String DOMAIN = 'Louis Vuitton Domain';
    private static final String SECURE_DOMAIN = 'Louis Vuitton Secure Domain';
    private static final String STANDARD_MODE = 'LOGIN';
    private static final String KNOWN_MODE = 'KNOWN_LOGIN';
    private static final String ONE_TIME_CONNECTION = 'Show Alternative Login Link';

    @AuraEnabled(cacheable=true)
    public static String getLanguage(String langCountry) {
        if (String.isEmpty(langCountry)) {
            TWIST_Settings__c settings = TWIST_Settings__c.getInstance();
            langCountry = (String) settings.get('Default_Language_Country_Parameter__c');
            return langCountry;
        }
        Language_Mapping_ATG_SF__mdt mapping = [SELECT Salesforce__c FROM Language_Mapping_ATG_SF__mdt WHERE ATG__c =: langCountry LIMIT 1];
        return (String) mapping.Salesforce__c;
    }

    /**
     * @description Replaces the former IDENTITY_Login_CTRL constructor method
     */
    @AuraEnabled(cacheable=true)
    public static Map<String,Object> initComponentConfig(Map<String,Object> queryParams) {
        String origin = (String) queryParams.get(TWIST_QueryParamKey_CONST.ORIGIN);
        String langCountry = (String) queryParams.get(TWIST_QueryParamKey_CONST.LANG_COUNTRY);
        String dispatchCountry = (String) queryParams.get(TWIST_QueryParamKey_CONST.DISPATCH_COUNTRY);
        String domain = (String) queryParams.get(TWIST_QueryParamKey_CONST.DOMAIN);
        
        String cid = (String) queryParams.get(TWIST_QueryParamKey_CONST.CID);
        String accountId = TWIST_Utils.getAccountId(cid);
        String utmCampaign = queryParams.get(TWIST_QueryParamKey_CONST.UTM_CAMPAIGN) != null ? (String)queryParams.get(TWIST_QueryParamKey_CONST.UTM_CAMPAIGN) : null;
        
        getSettings();
        setContext(origin, langCountry, dispatchCountry);
        langCountry = (String) componentConfig.get('langCountry'); // might have been update by previous method
        setForm(langCountry, (String) componentConfig.get('countryLocal'), origin, accountId, utmCampaign);
        setForgotPasswordUrl(langCountry, origin, queryParams);
        setAlternativeLoginUrl(langCountry, origin, queryParams);
        setRegistrationBaseUrl(langCountry, origin);
        setIsRedirectToRegistration(accountId, cid);
        getSocialSettings(langCountry, queryParams);
        writeLogs(queryParams);

        return componentConfig;
    }

    @AuraEnabled(cacheable=false)
    public static Map<String,Object> login(String email, String password, Map<String,Object> queryParams, String language) {
        
                String cid = queryParams.get(TWIST_QueryParamKey_CONST.CID) != null ? (String)queryParams.get(TWIST_QueryParamKey_CONST.CID) : null;
        String accountId;
        if(cid != null){
            accountId = TWIST_Utils.getAccountId(cid);
        }
        try {
            Boolean isFormValid = String.isEmpty(accountId)
                ? validateFormDataWithEmail(email, password, language)
                : validateFormDataWithoutEmail(password, language);
            if (!isFormValid) {
                return TWIST_Utils.buildFailureResponseObject('form', TWIST_i18nTranslations.translateSingleLabel('Twist_Error_Message_CheckEmailAndPassword', language));
            }

            User user = !String.isEmpty(accountId) ? TWIST_Utils.getUserByAccountId(accountId) : IDENTITY_Utils.getUserByUsername(email);
            if (user == null) {
                return TWIST_Utils.buildFailureResponseObject('form', TWIST_i18nTranslations.translateSingleLabel('Twist_Error_Message_CheckEmailAndPassword', language));
            }

            Pagereference page = TWIST_LoginService.doSalesforceLogin(
                user.Username,
                password,
                String.valueOf(queryParams.get(TWIST_QueryParamKey_CONST.STATE)),
                String.valueOf(queryParams.get(TWIST_QueryParamKey_CONST.CODE_CHALLENGE)),
                String.valueOf(queryParams.get(TWIST_QueryParamKey_CONST.CLIENT_ID)),
                String.valueOf(queryParams.get(TWIST_QueryParamKey_CONST.REDIRECT_URI))
            );
            if (page == null) {
                return TWIST_Utils.buildFailureResponseObject('form', TWIST_i18nTranslations.translateSingleLabel('Twist_Error_Message_CheckEmailAndPassword', language));
            }

            //DEPRECATED
            // String lookId = (String) queryParams.get(TWIST_QueryParamKey_CONST.LOOK_ID);
            // if (!String.isEmpty(lookId)) {
            //     IDENTITY_UTILS.shareLook(lookId, user.AccountId, (String) queryParams.get(TWIST_QueryParamKey_CONST.ORIGIN));
            // }
            return TWIST_Utils.buildSuccessResponseObject('redirectUrl', page.getUrl());
        }
        catch(Exception e) {
            new Logs(new Map<String,Object> { 'level' => 'ERROR', 'apexClass' => 'TWIST_Login', 'category' => 'SYSTEM', 'message' => e.getMessage() }); }
        return TWIST_Utils.buildFailureResponseObject('form', TWIST_i18nTranslations.translateSingleLabel('Twist_Login_Form_LoginProcessError', language));
    }
    @AuraEnabled(cacheable=false)
    public static Boolean isAlternativeLoginEnabled (String langCountry, String origin){
       
        return origin != 'mylv' ? false : new TWIST_FeatureFlagUtils(langCountry).isAlternativeLoginEnabled();
    }

    @AuraEnabled(cacheable=false)
    public static Boolean isLineButtonEnabled (String langCountry, String origin){

         return origin != 'mylv' ? false : new TWIST_FeatureFlagUtils(langCountry).isLineSocialLoginEnabled();
    }

    /** PRIVATE METHODS *********************************************************************************************** */

    @testVisible
    private static void writeLogs(Map<String,Object> queryParams) {
        TWIST_Utils.writeErrorLogs(queryParams, 'TWIST_Login');
    }

    /**
     * @return true if form is valid, false otherwise
     */
    @testVisible
    private static Boolean validateFormDataWithEmail(String email, String password, String language) {
        return !String.isEmpty(email) && !String.isEmpty(password) && !IDENTITY_Utils.passwordTooLong(password);
    }

    /**
     * @return true if form is valid, false otherwise
     */
    @testVisible
    private static Boolean validateFormDataWithoutEmail(String password, String language) {
        return !String.isEmpty(password) && !IDENTITY_Utils.passwordTooLong(password);
    }

    private static void getSettings() {
        componentConfig.putAll(TWIST_Utils.getLoginFormSettings());
    }

    /**
     * @description get URL parameters and define language, country, origin
     */
    private static void setContext(String origin, String langCountry, String dispatchCountry) {
       
        if(String.isEmpty(origin)){
            origin = (String) componentConfig.get('defaultOriginParameter');
        }
       
        componentConfig.put('googleAnalyticsConfig', IDENTITY_GoogleAnalytics_Utils.getConfig(origin));

        TWIST_Utils.setContext(origin, langCountry, dispatchCountry, componentConfig);

      }

    @testVisible
    private static void setForm(String langCountry, String countryLocal, String origin, String accountId, String utmCampaign) {
        try {
            
            List<IDENTITY_Registration_Form__mdt> metadata = [
                SELECT Field__c, Is_Required__c, Section__c, Is_Hidden__c, Value__c
                FROM IDENTITY_Registration_Form__mdt
                WHERE Context__c =: langCountry AND Form__c IN ('Login', 'Settings')
            ];
            
            Map<String,Map<String,IDENTITY_Registration_Form__mdt>> fields = new Map<String,Map<String,IDENTITY_Registration_Form__mdt>>();
            for(IDENTITY_Registration_Form__mdt field : metadata){
                if(fields.get(field.Section__c) == null){
                    fields.put(field.Section__c, new Map<String,IDENTITY_Registration_Form__mdt>());
                }
                fields.get(field.Section__c).put(field.Field__c, field);
            }
            componentConfig.put('fields', fields);
            String pageMode = String.isEmpty(accountId) ? STANDARD_MODE : KNOWN_MODE; // known Mode: if accountId matches an existing user Id, fill his username
            String callingCode;
            String username;
            String mobile;
            if(pageMode == KNOWN_MODE){
                User[] users = [SELECT Id, Username, TECH_Email__c, TECH_MobilePhone__c , AccountId FROM User WHERE AccountId =: accountId];

                if(!users.IsEmpty()) {
                    User user = users[0];
                    if(!fields.get('Login').get('email').Is_Hidden__c && fields.get('Login').get('mobile_phone').Is_Hidden__c){
                        username = user.TECH_Email__c;
                    }
                    else {
                        username = user.Username;
                        mobile = user.TECH_MobilePhone__c;
                        callingCode = getCallingCode(user);
                    }
                    //componentConfig.put('cid', cid);
                    componentConfig.put('mobile',  TWIST_Utils.getUserIdentifier(utmCampaign, mobile));
                    componentConfig.put('username',   TWIST_Utils.getUserIdentifier(utmCampaign, username));
                    componentConfig.put('showUsernameField', false);
                }
            }
            else {
                callingCode = fields.get('Login').get('mobile_phone').Value__c;
                componentConfig.put('showUsernameField', true);
            }
            componentConfig.put('callingCode', callingCode);
            
            // // Email/Mobile field visibility
            Boolean isEmailFieldVisible = false;
            String emailFieldVisibilityStyle = 'none';
            String mobileFieldVisibilityStyle = 'grid';
            if(
                (!fields.get('Login').get('email').Is_Hidden__c && countryLocal != 'cn')
                ||
                (!fields.get('Login').get('email').Is_Hidden__c && countryLocal == 'cn' && (origin == 'lvapp' || origin == 'lvconnect') )
            ){
                isEmailFieldVisible = true;
                emailFieldVisibilityStyle = 'grid';
            }
            if(!fields.get('Login').get('email').Is_Hidden__c && countryLocal != 'cn'){
                mobileFieldVisibilityStyle = 'none';
            }
            componentConfig.put('isEmailFieldVisible', isEmailFieldVisible);
            componentConfig.put('emailFieldVisibilityStyle', emailFieldVisibilityStyle);
            componentConfig.put('mobileFieldVisibilityStyle', mobileFieldVisibilityStyle);

        } catch (Exception ex) {
              new Logs( new Map<String,Object> {
                'level' => 'ERROR',
                'apexClass' => 'TWIST_Login',
                'category' => 'EVENT',
                'exception_case' => ex,
                'message' => 'TWIST_Login.setForm()',
                'application' => origin
            });
        }
    }

    private static void getSocialSettings(String langCountry, Map<String,Object> queryParams){
        componentConfig.put('socialMediaProviders', TWIST_Utils.getSocialProvidersByLangCountry(langCountry, queryParams));
    }

    @testVisible
    private static String getCallingCode(User user) {
        List<Account> accounts = [SELECT Id, LocalLoginPhone__pc, LoginPhoneCountryCode__pc, MobilePhoneCountryCode__pc FROM Account WHERE Id = :user.AccountId];
        if (!accounts.isEmpty()) {
            Account account = accounts.get(0);
            if(!String.isEmpty(account.LoginPhoneCountryCode__pc)) {
                return account.LoginPhoneCountryCode__pc;
            }
            if(!String.isEmpty(account.MobilePhoneCountryCode__pc)) {
                return account.MobilePhoneCountryCode__pc;
            }
        }
        return null;
    }

    // private static void setPathDispatch(String langCountry) {
    //     Map<String,String> paths = new Map<String,String>();
    //     for(IDENTITY_Paths__mdt path : [SELECT Name__c, Value__c
    //                                     FROM IDENTITY_Paths__mdt
    //                                     WHERE Name__c IN ('Louis Vuitton Domain', 'Dispatch')
    //                                     AND (Context__c =: langCountry OR Context__c = null)]){

    //         paths.put(path.Name__c, path.Value__c);
    //     }

    //     componentConfig.put('pathDispatch', paths.get('Louis Vuitton Domain')+paths.get('Dispatch'));
    // }

    private static void setForgotPasswordUrl(String langCountry, String origin, Map<String,Object> queryParams) {
        componentConfig.put('forgotPasswordUrl', TWIST_Utils.buildTwistPageUrl(TWIST_IdentityPathsMdt_CONST.FORGOT_PASSWORD_FORM, queryParams));
    }

    private static void setAlternativeLoginUrl(String langCountry, String origin, Map<String,Object> queryParams) {
        componentConfig.put('alternativeLoginUrl', TWIST_Utils.buildTwistAlternativeLoginPageUrl(TWIST_IdentityPathsMdt_CONST.ALTERNATIVE_LOGIN_FORM, queryParams));
    }

    private static void setRegistrationBaseUrl(String langCountry, String origin){
        componentConfig.put('registrationBaseUrl', TWIST_Utils.getRegistrationFormBaseUrl(langCountry, origin));
    }
    private static void setIsRedirectToRegistration(String accountId, String cid){
        //accountId != null means there is an exisitng user
        componentConfig.put('isRedirectToRegistration', (cid != null && accountId == null) ? true : false) ;
    }

}