force-app/main/default/objects/Order_Note__c/Order_Note__c.object-meta.xml
<CustomObject>
    <label>Order Note</label>
    <nameField>
        <label>Order Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATTACHED_NOTE</fullName>
                <label>Attached Note</label>
            </value>
            <value>
                <fullName>CLIENTELING_EXCEPTION</fullName>
                <label>Clienteling Exception</label>
            </value>
            <value>
                <fullName>PRICE_ADJUSTMENT</fullName>
                <label>Price Adjustment</label>
            </value>
            <value>
                <fullName>BANK_TRANSFER</fullName>
                <label>Bank Transfer</label>
            </value>
            <value>
                <fullName>STOCK_ON_HOLD</fullName>
                <label>Stock On Hold</label>
            </value>
            <value>
                <fullName>FREE_SHIPPING</fullName>
                <label>Free Shipping</label>
            </value>
            <value>
                <fullName>PAYMENT_LINK</fullName>
                <label>Payment Link</label>
            </value>
            <value>
                <fullName>EXTENDED_PAYMENT_LINK</fullName>
                <label>Extended Payment Link</label>
            </value>
            <value>
                <fullName>PERSO_PRODUCT_ACC</fullName>
                <label>Perso Product Accepted</label>
            </value>
            <value>
                <fullName>PERSO_PRODUCT_REF</fullName>
                <label>Perso Product Refused</label>
            </value>
            <value>
                <fullName>PAY_AFTER_AGREEMENT</fullName>
                <label>Pay After Agreement</label>
            </value>
            <value>
                <fullName>General Comment</fullName>
                <isActive>false</isActive>
                <label>General Comment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-twisticonics/main/default/classes/ICX_OrderNoteCleanerBatch.cls
global class ICX_OrderNoteCleanerBatch implements  Database.Batchable<sObject>, Schedulable, Database.AllowsCallouts { 
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        DateTime dt = DateTime.Now().addHours(-1);

        return Database.getQueryLocator([SELECT Id, Type__c, CreatedDate FROM Order_Note__c WHERE (CreatedDate <: dt AND Type__c=:'PAYMENT_LINK') OR (CreatedDate<LAST_N_DAYS:14   AND Type__c=:'EXTENDED_PAYMENT_LINK') ORDER BY CreatedDate DESC  ]);

    }

    global void execute(Database.BatchableContext BC, list<Order_Note__c> scope){

        // for(Order_Note__c currentOrderNote : scope)
        // {
        //     system.debug(currentOrderNote);
        // }

        // system.debug('nb of order note to delete'+scope.size());
        try{

           delete scope;
        }
        catch(EXCEPTION e)
        {
            system.debug('ICX_OrderNoteCleanerBatch ERROR : ' + e.getMessage());

        }
    }
    global void finish(Database.BatchableContext BC){}

    global void execute(SchedulableContext sc) {
        ICX_OrderNoteCleanerBatch b = new ICX_OrderNoteCleanerBatch(); 
        database.executebatch(b,100);
    }

}