force-app/main/default/objects/Contact/fields/AnniversaryDay__c.field-meta.xml
<CustomField>
    <fullName>AnniversaryDay__c</fullName>
    <label>Anniversary Day</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Star_Allergy__c.field-meta.xml
<CustomField>
    <fullName>Star_Allergy__c</fullName>
    <label>Allergy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Don&apos;t know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SO_PicklistFieldController_TEST.cls
@isTest
public with sharing class SO_PicklistFieldController_TEST {
    @testSetup
    static void testSetup(){
        SO_PicklistFieldController.PicklistEntryWrapper pew = new SO_PicklistFieldController.PicklistEntryWrapper();
        pew.active = 'active';
        pew.defaultValue = 'defaultValue';
        pew.label = 'label';
        pew.value = 'value';
        pew.validFor = 'validFor';
    }

    @isTest
    static void test_getDependentOptionsImpl(){
        Map<String, List<String>> dependentOptionsImpl1 = SO_PicklistFieldController.getDependentOptionsImpl('objApiName', 'contrfieldApiName', 'depfieldApiName');
        System.assertEquals(null, dependentOptionsImpl1);

        Contact c = new Contact();
        Map<String, List<String>> dependentOptionsImpl2 = SO_PicklistFieldController.getDependentOptionsImpl('Contact', 'AnniversaryDay__c', 'Star_Allergy__c');

        Map<String, List<String>> dependentOptionsImpl3 = SO_PicklistFieldController.getDependentOptionsImpl('Contact', '', '');
    }

    @isTest
    static void test_getDependentOptions(){
        Contact c = new Contact();
        List<String> dependentOptions = SO_PicklistFieldController.getDependentOptions('Contact', 'AnniversaryDay__c', 'Star_Allergy__c', 'Star_Allergy__c');
    }
}