force-app/main/default/objects/Push_Notification_Item__c/Push_Notification_Item__c.object-meta.xml
<CustomObject>
    <label>Push Notification Item</label>
    <nameField>
        <displayFormat>PNI-{0000000000}</displayFormat>
        <label>Push Notification Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Push Notification Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Push_Notification_Item__c/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <label>ObjectId</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Push_Notification_Item__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Push_Notification_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>ClientList</fullName>
            </value>
            <value>
                <fullName>Feed</fullName>
            </value>
            <value>
                <fullName>Voice</fullName>
            </value>
            <value>
                <fullName>ExceptionalProduct</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>FirmOrder</fullName>
            </value>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>CareService</fullName>
            </value>
            <value>
                <fullName>Appointment</fullName>
            </value>
            <value>
                <fullName>Wardrobing</fullName>
            </value>
            <value>
                <fullName>Variation_Member</fullName>
            </value>
            <value>
                <fullName>Experience_Variation</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
                <isActive>false</isActive>
                <label>Case</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <isActive>false</isActive>
                <label>Opportunity</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Push_Notification_Item__c/fields/UsersIds__c.field-meta.xml
<CustomField>
    <fullName>UsersIds__c</fullName>
    <label>UsersIds</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/IM_WS_PushNotifications.cls
@RestResource(urlMapping='/PushNotfication/*')
global with sharing class IM_WS_PushNotifications {
	@HttpPost
    global static void post() {
        RestRequest req = RestContext.request;
        String service = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
        system.debug(req.requestBody.toString());
        system.debug(req.params);
        Map<String,Object> body = (Map<String,Object>)JSON.deserializeUntyped(req.requestBody.toString());
        RestResponse res = RestContext.response;
        res.addHeader('Content-Type','application/json');
        res.statusCode = 200;
        string response;

        try{
            if(service == ''){
                response = JSON.serialize(createPushNotifications(body));
            }
            res.responseBody = Blob.valueOf(response);
            UtilsLogs.addLog('ICON','IM_WS_PushNotifications', JSON.serialize(req.params), '', response, '');
        }
        catch(Exception ex){
            string error = ex.getMessage() + '\n\n' + ex.getLineNumber();
            res.responseBody = Blob.valueOf(error);
            res.statusCode = 400;
            UtilsLogs.addLog('ICON', 'IM_WS_PushNotifications', JSON.serialize(req.params), '','', error);
        }
    }

    global static Push_Notification_Item__c createPushNotifications(Map<String,Object> body){
    	Push_Notification_Item__c push = new Push_Notification_Item__c(
    		Title__c = (String)body.get('Title__c'),
    		Type__c = (String)body.get('Type__c'),
    		ObjectId__c = (String)body.get('ObjectId__c'),
    		UsersIds__c = (String)body.get('UsersIds__c')
		);
    	insert push;
    	return push;
    }
}