force-app/main/default/objects/Push_Notification_Item__c/Push_Notification_Item__c.object-meta.xml
<CustomObject>
    <label>Push Notification Item</label>
    <nameField>
        <displayFormat>PNI-{0000000000}</displayFormat>
        <label>Push Notification Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Push Notification Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Push_Notification_Item__c/fields/Is_Silent_Push__c.field-meta.xml
<CustomField>
    <fullName>Is_Silent_Push__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Silent Push</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Push_Notification_Item__c/fields/isRead__c.field-meta.xml
<CustomField>
    <fullName>isRead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isRead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Push_Notification_Item__c/fields/Need_To_Be_Send__c.field-meta.xml
<CustomField>
    <fullName>Need_To_Be_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need To Be Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Push_Notification_Item__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Push_Notification_Item__c/fields/UserRecipient__c.field-meta.xml
<CustomField>
    <fullName>UserRecipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserRecipient</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Push_Notification_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Push_Notification_Item__c/fields/UsersIds__c.field-meta.xml
<CustomField>
    <fullName>UsersIds__c</fullName>
    <label>UsersIds</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/IM_CheckNotificationItems_TEST.cls
@isTest
private class IM_CheckNotificationItems_TEST {
  
  @isTest static void FeedItemAfterInsert() {
  	Push_Notification_Item__c pni  =new Push_Notification_Item__c(UsersIds__c = UserInfo.getUserId()+';',
  		Title__c='test',
  		Need_To_Be_Send__c=false);
  		insert pni;
		pni.isRead__c = false;
    	pni.Need_To_Be_Send__c = true;
    	update pni;

		Push_Notification_Item__c pni2  =new Push_Notification_Item__c(UsersIds__c = UserInfo.getUserId()+';',
  		Title__c='test2',
  		Need_To_Be_Send__c=false);
  		insert pni2;
    	pni2.Need_To_Be_Send__c = true;
		pni2.isRead__c = false;
		pni2.UserRecipient__c = UserInfo.getUserId();
		pni2.Is_Silent_Push__c = false;
    	update pni2;

		Push_Notification_Item__c pni3  =new Push_Notification_Item__c(UsersIds__c = UserInfo.getUserId()+';',
  		Title__c='test3',
		CreatedDate = System.now().addDays(-15),
  		Need_To_Be_Send__c=false);
  		insert pni3;
    	pni3.Need_To_Be_Send__c = true;
		pni3.isRead__c = false;
		pni3.UserRecipient__c = null;
		pni3.Is_Silent_Push__c = false;
    	update pni3;

		System.debug('TTTTTTTTTTTTTT pni3: '+ pni3);

		List<Push_Notification_Item__c> push = new List<Push_Notification_Item__c>();
		push.add(pni);
		push.add(pni2);
		RestRequest req = new RestRequest();
		RestResponse res = new RestResponse();

		req.requestURI = '/services/apexrest/CheckPushNotifications/';
		req.httpMethod = 'GET';
		RestContext.request = req;
		RestContext.response = res;

		Map<String,Object> body = new Map<String,Object>();
		body.put('notificationsRead', 'Test');
		body.put('notificationIdsToDelete', pni.Id);
		IM_CheckPushNotifications.CheckPushNotifications();
		IM_CheckPushNotifications.updateRead((String)body.get('notificationsRead'));
		IM_CheckPushNotifications.RemoveNotifications((String)body.get('notificationIdsToDelete'));
		IM_CheckPushNotifications.CheckPushNotificationsToPush(pni2.Id, push);
		IM_CheckPushNotifications.CheckPushNotificationsToPush(pni2.Id, push);
	}
}