force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Article_Body__c.field-meta.xml
<CustomField>
    <fullName>Article_Body__c</fullName>
    <label>Article Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Client_Service__c.field-meta.xml
<CustomField>
    <fullName>Client_Service__c</fullName>
    <label>Client Service</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>Hong_Kong</fullName>
                <isActive>false</isActive>
                <label>Hong_Kong</label>
            </value>
            <value>
                <fullName>Hong_Kong_Macao_Taiwan</fullName>
                <label>Hong Kong Macao/Taiwan</label>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Middle_East</fullName>
                <label>Middle East</label>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Vietnam</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Themes__c.field-meta.xml
<CustomField>
    <fullName>Themes__c</fullName>
    <label>Themes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Corporate_information</fullName>
                <label>Corporate information</label>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Exchange_returns</fullName>
                <label>Exchange returns</label>
            </value>
            <value>
                <fullName>Gifting</fullName>
            </value>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Website__c.field-meta.xml
<CustomField>
    <fullName>Website__c</fullName>
    <label>Website</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>en_sg</fullName>
                <label>APAC</label>
            </value>
            <value>
                <fullName>en_au</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>pt_br</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>en_ca</fullName>
                <label>Canada Eng</label>
            </value>
            <value>
                <fullName>fr_ca</fullName>
                <label>Canada Fra</label>
            </value>
            <value>
                <fullName>zh_cn</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>en_e1</fullName>
                <label>English International</label>
            </value>
            <value>
                <fullName>en_nl</fullName>
                <label>Euroland</label>
            </value>
            <value>
                <fullName>fr_fr</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>de_de</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>en_hk</fullName>
                <label>Hong-Kong Eng</label>
            </value>
            <value>
                <fullName>zh_hk</fullName>
                <label>Hong-Kong Zht</label>
            </value>
            <value>
                <fullName>en_in</fullName>
                <label>India</label>
            </value>
            <value>
                <fullName>en_id</fullName>
                <label>Indonesia Eng</label>
            </value>
            <value>
                <fullName>id_id</fullName>
                <label>Indonesia Ind</label>
            </value>
            <value>
                <fullName>it_it</fullName>
                <label>Italy</label>
            </value>
            <value>
                <fullName>ja_jp</fullName>
                <label>Japan</label>
            </value>
            <value>
                <fullName>ko_kr</fullName>
                <label>Korea</label>
            </value>
            <value>
                <fullName>sa_ar</fullName>
                <label>KSA (Arab) (المملكة العربية السعودية (العربية</label>
            </value>
            <value>
                <fullName>sa_en</fullName>
                <label>KSA (English)</label>
            </value>
            <value>
                <fullName>kw_ar</fullName>
                <label>Kuwait (Arab) (الكويت (العربية</label>
            </value>
            <value>
                <fullName>kw_en</fullName>
                <label>Kuwait (English)</label>
            </value>
            <value>
                <fullName>es_mx</fullName>
                <label>Mexico</label>
            </value>
            <value>
                <fullName>ar_ae</fullName>
                <label>Middle East Ara</label>
            </value>
            <value>
                <fullName>en_ae</fullName>
                <label>Middle East Eng</label>
            </value>
            <value>
                <fullName>qa_ar</fullName>
                <label>Qatar (Arab) (قطر (العربية</label>
            </value>
            <value>
                <fullName>qa_en</fullName>
                <label>Qatar (English)</label>
            </value>
            <value>
                <fullName>ru_ru</fullName>
                <label>Russia</label>
            </value>
            <value>
                <fullName>es_es</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>zh_tw</fullName>
                <label>Taiwan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge__kav/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/Knowledge__kav/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-knowledge/main/default/classes/KnowledgeWidgetController_TEST.cls
@isTest
public with sharing class KnowledgeWidgetController_TEST{
    
    @isTest
    static void searchKnowledgeArticles(){
        Test.startTest(); 
        
        List<RecordType> knowledgeRecordTypes = [SELECT Id, DeveloperName FROM RecordType WHERE IsActive = true AND SobjectType = 'Knowledge__kav' ORDER BY DeveloperName ASC];
        
        system.debug('knowledgeRecordTypes  ==>  '+knowledgeRecordTypes);
        
        Id recordTypeExternalId = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByName().get('External').getRecordTypeId();
		Id recordTypeInternalId = Schema.SObjectType.Knowledge__kav.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        
        system.debug('recordTypeExternalId  ==>  '+recordTypeExternalId);
        
       system.debug('recordTypeInternalId  ==>  '+recordTypeInternalId);
        
        Knowledge__kav aKnowledge = new Knowledge__kav();
            aKnowledge.Title='Test knowledge widget in action';
            aKnowledge.Summary='Searching article for Customer Agent';
            aKnowledge.Article_Body__c='Apex test article creation, is shown how to use knowledge Widget';
            aKnowledge.Themes__c='Services';
            aKnowledge.Client_Service__c='';
            aKnowledge.Website__c='en_e1;';
            aKnowledge.UrlName='test-knowledgewidget-in-action';
            aKnowledge.RecordTypeId=knowledgeRecordTypes[0].Id;
        insert aKnowledge;
        
       system.debug('knowledgeRecordTypes[0].Id  ==> '+knowledgeRecordTypes[0].Id + ' <==> knowledgeRecordTypes[0].DeveloperName  ==> '+knowledgeRecordTypes[0].DeveloperName);
        
        Knowledge__kav anInternalKnowledge = new Knowledge__kav();
        	anInternalKnowledge.Title='Test rank in action';
        	anInternalKnowledge.Summary='Searching article for Customer Agent';
        	anInternalKnowledge.Article_Body__c='Apex article creation, is shown how to use knowledge widget';
        	anInternalKnowledge.Themes__c='Orders';
        	anInternalKnowledge.Client_Service__c='Europe';
        	anInternalKnowledge.Website__c='';
            anInternalKnowledge.UrlName='test-widget-search';
        	anInternalKnowledge.RecordTypeId=knowledgeRecordTypes[1].Id; 
        insert anInternalKnowledge;
        
       system.debug('After Insertion <==> knowledgeRecordTypes[1].Id  ==> '+knowledgeRecordTypes[1].Id + ' <==> knowledgeRecordTypes[1].DeveloperName  ==> '+knowledgeRecordTypes[1].DeveloperName);
        
        // A Knowledge article inserted
        Knowledge__kav insertedKnowledge = [SELECT Id, Title,Themes__c, Client_Service__c, Website__c, RecordTypeId, RecordType.DeveloperName, CreatedDate FROM Knowledge__kav WHERE Id = :aKnowledge.Id];
        Knowledge__kav internalInsertedKnowledge = [SELECT Id, Title,Themes__c, Client_Service__c, Website__c, RecordTypeId, RecordType.DeveloperName, CreatedDate FROM Knowledge__kav WHERE Id = :anInternalKnowledge.Id];

        // A knowledge article not found
        List<SObject> foundArticles = KnowledgeWidgetController.knowledgeArticles('widget', knowledgeRecordTypes[0].DeveloperName, '');

        // A knowledge article found
        List<Knowledge__kav> kFoundArticles = KnowledgeWidgetController.knowledgeArticles('test', 'All', '');

        // A knowledge article found
        List<Knowledge__kav> internalFoundArticles = KnowledgeWidgetController.knowledgeArticles('rank', knowledgeRecordTypes[1].DeveloperName, 'Europe');  
        
        Test.stopTest();

        system.assertNotEquals(null, insertedKnowledge.Id);
        system.debug('External article inserted, is ===>>  ' +insertedKnowledge+ ' and Knowledge Id is ==>> ' +insertedKnowledge.Id);
        
        system.assertNotEquals(null, internalInsertedKnowledge.Id);
        system.debug('Internal article inserted ==>> ' +internalInsertedKnowledge + ' internal article knowledge Id ==>> ' +internalInsertedKnowledge.Id);

        system.assertNotEquals(1, foundArticles.size());
        system.debug('Found Articles size ==>> ' +foundArticles.size() + ' article ===>> ' +foundArticles.toString());
        
        system.assertNotEquals(1, kFoundArticles.size());
        system.debug('Found Articles size ==>> ' +kFoundArticles.size() + ' article ===>> ' +kFoundArticles.toString());

        system.assertNotEquals(1, internalFoundArticles.size());
        system.debug('Found Articles size ==>> ' +internalFoundArticles.size() + ' article ===>> ' +internalFoundArticles.toString()); 
    }
    
    @isTest
    static void searchKnowledgeRecordTypes(){
        // Existing RecordTypes
        List<String> knowledgeRecordTypesValues = KnowledgeWidgetController.knowledgeRecordTypes();
        system.assertEquals(2, knowledgeRecordTypesValues.size(),'Success');
        system.debug('Existing RecordTypes : knowledgeRecordTypesValues <===> ' +knowledgeRecordTypesValues);
    }
}