force-app/main/default/objects/IconBadge__c/IconBadge__c.object-meta.xml
<CustomObject>
    <label>Icon Badge</label>
    <nameField>
        <label>Icon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Icon Badges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IconBadge__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeamMember__c/TeamMember__c.object-meta.xml
<CustomObject>
    <label>TeamMember</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>TeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TeamMembers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamMember__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamMembersManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeamMember__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TeamMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-icon/main/default/classes/BL_ICON_Badges_TEST.cls
@isTest
public class BL_ICON_Badges_TEST {
    @isTest
    static void testMethodGet(){
     
        BL_AppSettings.setAppSettings('Icon');
        BL_ICON_Badges blBadges = new BL_ICON_Badges();
        User u = IC_Test_Common.prepareTestUser('System Administrator');
        u.defaultStore__c = 'N03';
        insert u;
        User ca = IC_Test_Common.prepareTestUser('System Administrator');
        ca.defaultStore__c = 'N03';
        insert ca;
        TeamMember__c teammember = new TeamMember__c( manager__c = u.id, user__c = ca.Id);
        insert teammember;
        insert new IconBadge__c(Type__c = 'Regular', ownerId = ca.Id);

        system.runAs(u){
            
            blBadges.me = (BL_UserInfo)Type.forName('BL_ICON_UserInfo').newInstance();
            
            Test.startTest();   
            blBadges.queryParams = new Map<String, String>();
            blBadges.queryParams.put('managerId',null);
            blBadges.executeGET();
            Test.stopTest();
        }
    }

}