force-app/main/default/objects/Club_MemberShip__c/Club_MemberShip__c.object-meta.xml
<CustomObject>
    <label>Club Membership</label>
    <nameField>
        <label>Club MemberShip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-experience/main/default/objects/Club_MemberShip__c/fields/follower_Count__c.field-meta.xml
<CustomField>
    <fullName>follower_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Follower Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-experience/main/default/objects/Club_MemberShip__c/fields/Following_Count__c.field-meta.xml
<CustomField>
    <fullName>Following_Count__c</fullName>
    <label>Following Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/isClubEligible__c.field-meta.xml
<CustomField>
    <fullName>isClubEligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Club Eligibility</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Club_MemberShip__c/fields/isMember__c.field-meta.xml
<CustomField>
    <fullName>isMember__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Status stating the Client passed the Club onboarding steps and accessed the LV Club</description>
    <label>is Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Favorite_Club_Member__c/Favorite_Club_Member__c.object-meta.xml
<CustomObject>
    <label>Club Favorite Member</label>
    <nameField>
        <label>Favorite Club Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Club Favorite Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Favorite_Club_Member__c/fields/clubMemberId__c.field-meta.xml
<CustomField>
    <fullName>clubMemberId__c</fullName>
    <description>Client’s MemberId for a Club</description>
    <label>Club Member</label>
    <referenceTo>Club_MemberShip__c</referenceTo>
    <relationshipLabel>Favorites Club Members</relationshipLabel>
    <relationshipName>Favorite_Club_Member</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Favorite_Club_Member__c/fields/favoriteClubMemberId__c.field-meta.xml
<CustomField>
    <fullName>favoriteClubMemberId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Club Member favorite Member</description>
    <label>Favorite Club Member</label>
    <referenceTo>Club_MemberShip__c</referenceTo>
    <relationshipLabel>Favorite by a Member</relationshipLabel>
    <relationshipName>Followers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Favorite_Club_Member__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <description>[clubMemberId__c.dreamId__c]-[favoriteClubMemberId__c.dreamId__c]</description>
    <label>UniqueKey</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/FavoriteClubMemberTriggerHandler.cls
public with sharing class FavoriteClubMemberTriggerHandler {
    public static void handleTrigger(List<Favorite_Club_Member__c> newList, Map<Id, Favorite_Club_Member__c> newMap, List<Favorite_Club_Member__c> oldList, Map<Id, Favorite_Club_Member__c> oldMap, System.TriggerOperation triggerEvent) {
        switch on triggerEvent {
            when BEFORE_INSERT {
                handleBeforeInsert(newList);
            }
            when AFTER_INSERT {
                handleAfterInsert(newList);
            }
            when AFTER_DELETE {
                handleAfterDelete(oldList);
            }
            when else {
                //do nothing for AFTER_UNDELETE, BEFORE_DELETE, or BEFORE_UPDATE
            }
        }
    }

    public static void handleBeforeInsert(List<Favorite_Club_Member__c> newList) {
        for (Favorite_Club_Member__c favorite : newList) {
            favorite.UniqueKey__c = favorite.clubMemberId__c + '_' + favorite.favoriteClubMemberId__c;
        }
    }
    public static void handleAfterInsert(List<Favorite_Club_Member__c> newList) {
        updateFollowingFollowersCount(newList, 'inc');
    }
    public static void handleAfterDelete(List<Favorite_Club_Member__c> oldList) {
        updateFollowingFollowersCount(oldList, 'dec');
    }
    private static void updateFollowingFollowersCount(List<Favorite_Club_Member__c> clubMembersList, String operation) {
        List<Id> followingIds = new List<Id>();
        List<Id> followerIds = new List<Id>();
        for (Favorite_Club_Member__c fvrt : clubMembersList) {
            followingIds.add(fvrt.clubMemberId__c);
            followerIds.add(fvrt.favoriteClubMemberId__c);
        }
        queryAndUpdateRecords(followingIds, followerIds, operation);
    }
    private static void queryAndUpdateRecords(List<Id> followingIds, List<Id> followerIds, String operation) {
        Map<Id, Club_Membership__c> updatedFollowRecords = new Map<Id, Club_Membership__c>();
        for (Club_Membership__c member : [SELECT Id, Following_Count__c, follower_Count__c FROM Club_Membership__c WHERE (Id IN:followingIds OR Id IN:followerIds) AND isClubEligible__c=True AND isMember__c=True]) {
            member.Following_Count__c=member.Following_Count__c==null?0:member.Following_Count__c;            
            member.follower_Count__c=member.follower_Count__c==null?0:member.follower_Count__c;
            switch on operation {
                when 'inc' { //on create Favorite_Club_Member__c
                    if (followingIds.contains(member.Id)) {
                        member.Following_Count__c++;
                    }
                    if (followerIds.contains(member.Id)){
                        member.follower_Count__c++; 
                    }
                }
                when 'dec' { //on delete Favorite_Club_Member__c
                    if (followingIds.contains(member.Id)) {
                        member.Following_Count__c--;
                    }
                    if (followerIds.contains(member.Id)){
                        member.follower_Count__c--; 
                    }
                }
            }
            updatedFollowRecords.put(member.Id, member);
        }
        if (!updatedFollowRecords.values().isEmpty()) {
            update updatedFollowRecords.values();
        }
    }
}