force-app/main/default/objects/IDENTITY_AuthProvider_Mapping__mdt/IDENTITY_AuthProvider_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>IDENTITY - AuthProvider Mapping</label>
    <pluralLabel>IDENTITY - AuthProvider Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/IDENTITY_AuthProvider_Mapping__mdt/fields/AuthProvider__c.field-meta.xml
<CustomField>
    <fullName>AuthProvider__c</fullName>
    <label>AuthProvider</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Facebook</fullName>
                <default>true</default>
                <label>Facebook</label>
            </value>
            <value>
                <fullName>Kakao</fullName>
            </value>
            <value>
                <fullName>Line</fullName>
            </value>
            <value>
                <fullName>WeChat</fullName>
            </value>
            <value>
                <fullName>WeChat_Mobile</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IDENTITY_AuthProvider_Mapping__mdt/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>base_address</fullName>
            </value>
            <value>
                <fullName>birthdate_day</fullName>
            </value>
            <value>
                <fullName>birthdate_month</fullName>
            </value>
            <value>
                <fullName>birthdate_year</fullName>
            </value>
            <value>
                <fullName>calling_code</fullName>
                <default>true</default>
                <label>calling_code</label>
            </value>
            <value>
                <fullName>channel_opted_in</fullName>
            </value>
            <value>
                <fullName>connnected_at</fullName>
            </value>
            <value>
                <fullName>detail_address</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>email_verified</fullName>
            </value>
            <value>
                <fullName>firstName</fullName>
            </value>
            <value>
                <fullName>fullName</fullName>
            </value>
            <value>
                <fullName>gender</fullName>
            </value>
            <value>
                <fullName>id</fullName>
            </value>
            <value>
                <fullName>isEmailPrivate</fullName>
                <isActive>false</isActive>
                <label>isEmailPrivate</label>
            </value>
            <value>
                <fullName>isEmailVerified</fullName>
                <isActive>false</isActive>
                <label>isEmailVerified</label>
            </value>
            <value>
                <fullName>lastName</fullName>
            </value>
            <value>
                <fullName>link</fullName>
            </value>
            <value>
                <fullName>locale</fullName>
            </value>
            <value>
                <fullName>login_international_mobile_phone</fullName>
            </value>
            <value>
                <fullName>newsletter_terms</fullName>
            </value>
            <value>
                <fullName>phone</fullName>
            </value>
            <value>
                <fullName>phone_number</fullName>
            </value>
            <value>
                <fullName>phone_number_verified</fullName>
            </value>
            <value>
                <fullName>picture</fullName>
            </value>
            <value>
                <fullName>stiteLoginUrl</fullName>
            </value>
            <value>
                <fullName>userName</fullName>
            </value>
            <value>
                <fullName>zone_number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IDENTITY_AuthProvider_Mapping__mdt/fields/Is_Standard__c.field-meta.xml
<CustomField>
    <fullName>Is_Standard__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>id, firstName, lastName, fullName, email, link, userName, locale, provider, siteLoginUrl</inlineHelpText>
    <label>Is Standard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IDENTITY_AuthProvider_Mapping__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>String</fullName>
                <default>true</default>
                <label>String</label>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Boolean</fullName>
            </value>
            <value>
                <fullName>Url</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IDENTITY_AuthProvider.cls
public without sharing class IDENTITY_AuthProvider {

    public static Map<String,Object> mapping;
    public static Map<String,Object> result;

    /*
    *** DESCRIPTION Get a token value according attribute name
    *** RETURN      Value
    */
    public static String getTokenValue(String body, String token) {
        Map<String,Object> fields = (Map<String,Object>)JSON.deserializeUntyped(body);
        return (String)fields.get(token);
    }

    /*
    *** DESCRIPTION Convert JSON social media user data (body and JWT) to Auth.UserData 
    *** RETURN      Auth.UserData
    */
    public static Auth.UserData getUserData(String provider, String body, String jwt_token){
        System.debug('>>> getUserData() method');

        // GET MAPPING FIELDS
        mapping = getMapping(provider);
        System.debug('> provider: ' + provider);
        System.debug('> body: ' + body);
        System.debug('> jwt_token: ' + jwt_token);
        System.debug('> mapping: ' + JSON.serialize(mapping));

        // SETUP RESULT
        result = new Map<String,Object>();
        result.put('others', new Map<String,String>());

        // GET AUTH PROVIDER FIELDS FROM BODY
        if(!String.isEmpty(body)){
            if(provider == 'Kakao'){
                Map<String,Object> fields = (Map<String,Object>)JSON.deserializeUntyped(body);

                if(fields.get('properties') != null) {
                    Map<String,Object> properties = (Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(fields.get('properties')));
                    fields.putAll(properties);
                    fields.remove('properties');
                }
                if(fields.get('kakao_account') != null) {
                    Map<String,Object> kakao_account = (Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(fields.get('kakao_account')));
                    fields.putAll(kakao_account);
                    fields.remove('kakao_account');
                }

                getFields(JSON.serialize(fields));
            }
            else {
                getFields(body);
            }
        }

        // GET AUTH PROVIDER FIELDS FROM JWT TOKEN
        if(!String.isEmpty(jwt_token)){
            getFields(jwt_token);
        }
        
        return toAuthUserData(provider, result);
    }

    /*
    *** DESCRIPTION Get Mapping between social media fields and salesforce Auth.UserData fields
                    Based on IDENTITY_AuthProvider_Mapping__mdt references
    *** RETURN
    */
    public static void getFields(String json_string){
        System.debug('>>> getFields() method');
        Map<String,Object> fields = (Map<String,Object>)JSON.deserializeUntyped(json_string);
            
        for(String field : fields.keySet()){
            System.debug('getFields() - field: ' + field);
            if(mapping.get(field) != null){
                IDENTITY_AuthProvider_Mapping__mdt salesforce_field = (IDENTITY_AuthProvider_Mapping__mdt)mapping.get(field);
                
                if(salesforce_field != null){
                    // If the field is Standard, add it to Auth.UserData field that corresponds
                    if(salesforce_field.Is_Standard__c){
                        result.put(salesforce_field.Field__c, fields.get(field));
                        System.debug('getFields() - add to result: ' + field + ' > ' + fields.get(field));
                    }
                    // Else add it to the other map attributes of the Auth.UserData
                    else{
                        ((Map<String,Object>)result.get('others')).put(salesforce_field.Field__c, String.valueOf(fields.get(field)));
                    }
                }
            }
        }
    }

    /*
    *** DESCRIPTION Get Mapping between social media fields and salesforce Auth.UserData fields
                    Based on IDENTITY_AuthProvider_Mapping__mdt references
    *** RETURN
    */
    public static Map<String,Object> getMapping(String provider){
        Map<String,Object> mapping = new Map<String,Object>();
        
        List<IDENTITY_AuthProvider_Mapping__mdt> mapping_list = [
            SELECT Field__c, Value__c, Is_Standard__c, Type__c
            FROM IDENTITY_AuthProvider_Mapping__mdt
            WHERE AuthProvider__c =: provider
        ];
        
        for(IDENTITY_AuthProvider_Mapping__mdt mdt : mapping_list){
            mapping.put(mdt.Value__c, mdt);
        }

        return mapping;
    }

    public static Auth.UserData toAuthUserData(String provider, Map<String,Object> fields){
        Auth.UserData userData = new Auth.UserData(
            String.valueOf(fields.get('id')),
            String.valueOf(fields.get('firstName')),
            String.valueOf(fields.get('lastName')),
            String.valueOf(fields.get('fullName')),
            String.valueOf(fields.get('email')),
            String.valueOf(fields.get('link')),
            String.valueOf(fields.get('userName')),
            String.valueOf(fields.get('locale')),
            provider,
            String.valueOf(fields.get('siteLoginUrl')),
            (Map<String,String>)fields.get('others')
        );
        System.debug('toAuthUserData() result: ' + JSON.serializePretty(userData));
        return userData;
    }

    public static Account toAccount(Auth.UserData data){

        Account new_account = new Account();
        new_account.PersonEmail = data.email;
        new_account.LastName = data.firstname;
        new_account.FirstName = data.lastname;
        new_account.PrimaryCountry__pc = data.locale;
        new_account.PersonMobilePhone = data.attributeMap.get('login_international_mobile_phone');

        return new_account;
    }
}