force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, list all categories for Perso menus.</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Exotic_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Exotic_Workflow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exotic Workflow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ApplicationSource__c.field-meta.xml
<CustomField>
    <fullName>ApplicationSource__c</fullName>
    <description>Application where the opportunity is created : PERSO / SPO (Special Order) / ECO (ecommerce LV.com)</description>
    <label>Application Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SPO</fullName>
            </value>
            <value>
                <fullName>PERSO</fullName>
            </value>
            <value>
                <fullName>ECO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_Dup__c.field-meta.xml
<CustomField>
    <fullName>Is_Dup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Dup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_DepositSentStatusDate__c.field-meta.xml
<CustomField>
    <fullName>SPO_DepositSentStatusDate__c</fullName>
    <label>Deposit sent status date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPO_EstimatedProductionTimeMonths__c.field-meta.xml
<CustomField>
    <fullName>SPO_EstimatedProductionTimeMonths__c</fullName>
    <label>Estimated production time (weeks)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Workshop__c.field-meta.xml
<CustomField>
    <fullName>Workshop__c</fullName>
    <label>Workshop</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Workshop</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Allocation__c/Product_Allocation__c.object-meta.xml
<CustomObject>
    <label>Product Allocation</label>
    <nameField>
        <label>Product Allocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Allocation__c/fields/Availability_is_Blacklist__c.field-meta.xml
<CustomField>
    <fullName>Availability_is_Blacklist__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Availability is Blacklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Allocation__c/fields/Available_In_Stores__c.field-meta.xml
<CustomField>
    <fullName>Available_In_Stores__c</fullName>
    <label>Available In Stores</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Allocation__c/fields/Available_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Available_Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Allocation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>HYPERLINK(Product__r.Category__c, Product__r.Category__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Allocation__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>ProductCatalogue__c</referenceTo>
    <relationshipLabel>Product Allocations</relationshipLabel>
    <relationshipName>Product_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Allocation__c/fields/Reserved_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Reserved_Quantity__c</fullName>
    <label>Reserved Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Allocation__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <label>Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MANAGEMENT_ZONE_LEVEL</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCatalogue__c/fields/Availability_is_Blacklist__c.field-meta.xml
<CustomField>
    <fullName>Availability_is_Blacklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks the list of stores in &quot;Available In Stores&quot; as a blacklist. If the flag is unchecked (=authorized), the product is displayed for all stores in the list. If the flag is checked (=forbidden), the product is displayed for all stores except those in the list.</description>
    <label>Availability is Blacklist</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/Available_In_Stores__c.field-meta.xml
<CustomField>
    <fullName>Available_In_Stores__c</fullName>
    <description>Used in NY to not display products for stores outside the list, allow selecting no store or any number of stores by their code (e.g. A06)</description>
    <label>Available In Stores</label>
    <length>1200</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Make It Yours (Perso) app, a product is in one category only (don&apos;t use the BCC category where &quot;Mon monogram&quot; has a BCC ID for Men and one BCC Id for woman</description>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/Exotic__c.field-meta.xml
<CustomField>
    <fullName>Exotic__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Product with exotic material Same as ProductReferential__r.Cites__c (helpful to calculate the lead time)</description>
    <label>Exotic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/FluidRecipeId__c.field-meta.xml
<CustomField>
    <fullName>FluidRecipeId__c</fullName>
    <description>Recipe id for Fluid app</description>
    <label>Fluid Recipe Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/LeadTimeManufacturing__c.field-meta.xml
<CustomField>
    <fullName>LeadTimeManufacturing__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Lead Time Manufacturing to calculate the total lead time (in calendar days)</description>
    <label>Lead Time Manufacturing</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/ReportingCategory__c.field-meta.xml
<CustomField>
    <fullName>ReportingCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For NY</description>
    <label>Reporting Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipName>Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <description>SKU code</description>
    <externalId>true</externalId>
    <label>SKU</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/Workshop__c.field-meta.xml
<CustomField>
    <fullName>Workshop__c</fullName>
    <defaultValue>(&quot;0000&quot;)</defaultValue>
    <description>Manufacturing workshop code
(used for JDE system to know in which workshop the product should be sent)
For Perso app, value is set to 11202 (in product creation) but can be changed
Default value changed to 0000 on MIY-2062</description>
    <label>Workshop</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Workshop</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductConfigurationDetail__c/ProductConfigurationDetail__c.object-meta.xml
<CustomObject>
    <label>Product Configuration Detail</label>
    <nameField>
        <label>Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Configuration Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductConfigurationDetail__c/fields/Sku__c.field-meta.xml
<CustomField>
    <fullName>Sku__c</fullName>
    <label>Sku</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/SPO_FirmOrder__c.object-meta.xml
<CustomObject>
    <description>All informations about about customization, quote, order following</description>
    <label>Order Line Item</label>
    <nameField>
        <label>Firm Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPO_FirmOrder__c/fields/FluidRecipeId__c.field-meta.xml
<CustomField>
    <fullName>FluidRecipeId__c</fullName>
    <description>Fluid id</description>
    <externalId>true</externalId>
    <label>Fluid Recipe Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/Planned_Delivery_date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Delivery_date__c</fullName>
    <description>Planned Delivery date for Store Users</description>
    <label>Planned Delivery date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/Planned_Manufacturing_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Manufacturing_Date__c</fullName>
    <label>Planned Manufacturing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/PlannedDeliveryDate__c.field-meta.xml
<CustomField>
    <fullName>PlannedDeliveryDate__c</fullName>
    <description>Retained in order to not break reports. Old code available in comment.</description>
    <formula>IF (NOT(ISBLANK(Planned_Manufacturing_Date__c)),
    Planned_Manufacturing_Date__c,

    /* Old formula: */
    IF (NOT(ISBLANK(ProductCatalogue__c)),
       (SPO_BriefName__r.SPO_DepositSentStatusDate__c + Product_Lead_Time_Manufacturing__c),
       (SPO_BriefName__r.SPO_DepositSentStatusDate__c + (SPO_BriefName__r.SPO_EstimatedProductionTimeMonths__c * 7)) 
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Planned Manufacturing Date (Legacy)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPO_FirmOrder__c/fields/ProductCatalogue__c.field-meta.xml
<CustomField>
    <fullName>ProductCatalogue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product used for PERSO app</description>
    <label>Product Catalogue</label>
    <referenceTo>ProductCatalogue__c</referenceTo>
    <relationshipName>Firm_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/MANAGEMENT_ZONE_LEVEL__c.field-meta.xml
<CustomField>
    <fullName>MANAGEMENT_ZONE_LEVEL__c</fullName>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <label>MANAGEMENT ZONE LEVEL</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/Zone__c.field-meta.xml
<CustomField>
    <fullName>Zone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This lookup links the store record to the 1st level of hierarchy</description>
    <label>Zone</label>
    <referenceTo>Zone__c</referenceTo>
    <relationshipLabel>Stores</relationshipLabel>
    <relationshipName>Stores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/globalValueSets/MANAGEMENT_ZONE_LEVEL.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3</fullName>
        <label>AMERICAS</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>ASIA NORTH</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>ASIA SOUTH</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>EMEA</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>JAPAN</label>
    </customValue>
    <customValue>
        <fullName>Worldwide</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>MAINLAND CHINA</label>
    </customValue>
    <description>Contains the code/translation for the first level of management hierarchy</description>
    <masterLabel>MANAGEMENT ZONE LEVEL</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FirmOrderTriggerHandler_TEST.cls
@isTest
public class FirmOrderTriggerHandler_TEST {
	@TestSetup
	static void init() {
		// create a store
		Store__c st = LV_TestFactory.createStore('LV TEST STORE MIY', 'Store', 'A00', 'FRANCE', 'EUR', 'Open');
		st.MANAGEMENT_ZONE_LEVEL__c = '15';
		insert st;

		// create a client
		Account client = LV_TestFactory.createAccount();
		insert client;
        
        Category__c cat1 = new 	Category__c(Name = 'Ready to Wear', Exotic_Workflow__c = true);
		insert cat1;
		// create a non exotic product catalog
		ProductCatalogue__c pc = LV_TestFactory.createProductCatalog('MY NEVERFULL', 'P0001', 3, 15, 5, 'Leather Goods');
		pc.Workshop__c ='1798';
        pc.ReportingCategory__c = cat1.id;
        pc.Category__c = cat1.id;
		insert pc;

		Category__c cat = new 	Category__c(Name = 'EXOTIC_CATEGORY', Exotic_Workflow__c = true);
		insert cat;
        
		// create an exotic product catalog
		ProductCatalogue__c pcExo = LV_TestFactory.createProductCatalog('MY NEVERFULL', 'P0002', 3, 15, 5, 'Leather Goods');
		pcExo.Exotic__c = true;
		pcExo.ReportingCategory__c = cat.id;
		pcExo.Workshop__c ='1798';
		insert pcExo;

		ProductCatalogue__c pcdup = LV_TestFactory.createProductCatalog('MY NEVERFULL', 'P0003', 0, 0, 0, 'Leather Goods');
		pcdup.LeadTimeManufacturing__c = 10;
		pcdup.Workshop__c ='1798';
		insert pcdup;

		// create a Lead Time
		MIY_LeadTime__c lt = LV_TestFactory.createLeadTime('FRANCE', 'Leather Goods', 20, 16);
		insert lt;

		// create a non exotic perso order
		Opportunity mypOrder = LV_TestFactory.createOrder('MY Neverfull bag', 'Creation in progress', null, st.id, client.id, null, null, 'PERSO');
		mypOrder.SPO_DepositSentStatusDate__c = System.today();
		insert mypOrder;

		Product_Allocation__c pa = new Product_Allocation__c(
				Product__c = pc.Id,
				Zone__c = 'Worldwide',
				Available_Quantity__c = 2,
				Reserved_Quantity__c = 0
		);
		insert pa;
		Product_Allocation__c storeAllocation = new Product_Allocation__c(
				Product__c = pcdup.Id,
				Available_Quantity__c = 2,
				Reserved_Quantity__c = 0,
				Available_In_Stores__c = 'A00',
				Availability_is_Blacklist__c = false
		);
		insert storeAllocation;

		//MIY-1745
		Opportunity spoOrder1 =
				LV_TestFactory.createOrder('SPO_1', 'Creation in progress', null, st.id, client.id, null, null, 'SPO');
				spoOrder1.SPO_DepositSentStatusDate__c = System.today();
				spoOrder1.SPO_EstimatedProductionTimeMonths__c = 1;
		insert spoOrder1;
		Opportunity ecoOrder =
				LV_TestFactory.createOrder('ECO', 'Creation in progress', null, st.id, client.id, null, null, 'ECO');
				ecoOrder.SPO_DepositSentStatusDate__c = System.today();
				ecoOrder.Is_Dup__c = true;
		insert ecoOrder;
	}

	@isTest
	static void initTest() { //MIY-1745
		Boolean firstRunTest = FirmOrderTriggerHandler.isFirstRun();
		System.assertEquals(firstRunTest, true);
		Boolean secondRunTest = FirmOrderTriggerHandler.isFirstRun();
		System.assertEquals(secondRunTest, false);
	}

	@isTest
	static void testManageLeadTimeNonExoPerso() {

		Test.setMock(HttpCalloutMock.class, new MockHttpResponse('successJsonFluidData', 'json'));
		ProductCatalogue__c pc = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0001' LIMIT 1];
		ProductCatalogue__c pcdup = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0003' LIMIT 1];
		Opportunity mypOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
		Opportunity dupOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'ECO' LIMIT 1];

		// create a firm order
		SPO_FirmOrder__c fo = LV_TestFactory.createFirmOrder(mypOrder.id, 1, pc.id);
		SPO_FirmOrder__c dupfo = LV_TestFactory.createFirmOrder(dupOrder.id, 2, pcdup.id);
		dupfo.FluidRecipeId__c ='74473696';
		// run test
		Test.startTest();
		insert fo;
		insert dupfo;
		Test.stopTest();

		fo = [SELECT id, PlannedDeliveryDate__c, Planned_Delivery_date__c, Planned_Manufacturing_Date__c from SPO_FirmOrder__c where id =: fo.id];
		dupfo = [SELECT id, PlannedDeliveryDate__c, Planned_Delivery_date__c, Planned_Manufacturing_Date__c from SPO_FirmOrder__c where id =: dupfo.id];

		// for non exotic firm order
		Date plannedDateForClient = System.today().adddays(39);
		Date plannedManufDateForClient = System.today().adddays(18); //MIY-1745
		Date duplicatedManufDate = System.today().adddays(10);
		System.assertEquals(plannedDateForClient, fo.Planned_Delivery_date__c);
		System.assertEquals(duplicatedManufDate, dupfo.Planned_Manufacturing_Date__c);

		//Added for code coverage (MIY-1745)
		System.assertEquals(plannedManufDateForClient, fo.Planned_Manufacturing_Date__c);
	}
    
	@isTest
	static void testManageLeadTimeNonExoPers2() {

		Test.setMock(HttpCalloutMock.class, new MockHttpResponse('successJsonFluidData', 'json'));
		ProductCatalogue__c pc = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0001' LIMIT 1];
		ProductCatalogue__c pcdup = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0003' LIMIT 1];
		Opportunity mypOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'ECO' LIMIT 1];

		// create a firm order
		SPO_FirmOrder__c fo = LV_TestFactory.createFirmOrder(mypOrder.id, 1, pc.id);

		// run test
		Test.startTest();
		insert fo;
		Test.stopTest();

		fo = [SELECT id, PlannedDeliveryDate__c, Planned_Delivery_date__c, Planned_Manufacturing_Date__c from SPO_FirmOrder__c where id =: fo.id];

		// for non exotic firm order
		Date plannedDateForClient = System.today().adddays(39);
		Date plannedManufDateForClient = System.today().adddays(18); //MIY-1745
		Date duplicatedManufDate = System.today().adddays(10);
		//System.assertEquals(plannedDateForClient, fo.Planned_Delivery_date__c);

		//Added for code coverage (MIY-1745)
		//System.assertEquals(plannedManufDateForClient, fo.Planned_Manufacturing_Date__c);
	}

	@isTest
	static void testManageLeadTimeExoPerso() {
		ProductCatalogue__c pcExo = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0002' LIMIT 1];
		Opportunity mypOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
		// create an exotic firm order
		SPO_FirmOrder__c foExo = LV_TestFactory.createFirmOrder(mypOrder.id, 9, pcExo.id);
		// run test
		Test.startTest();
		insert foExo;
		Test.stopTest();

		foExo = [SELECT id, PlannedDeliveryDate__c, Planned_Delivery_date__c from SPO_FirmOrder__c where id =: foExo.id];
		Date plannedDateForClientExo = System.today().adddays(43);
		System.assertEquals(plannedDateForClientExo, foExo.Planned_Delivery_date__c);
	}

	@isTest
	static void testManageLeadTimeSPO() { //MIY-1745
		Opportunity spoOrder1 = [SELECT Id FROM Opportunity WHERE Name = 'SPO_1' LIMIT 1];
        ProductCatalogue__c pcExo = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0002' LIMIT 1];
		SPO_FirmOrder__c foSpo1 = new SPO_FirmOrder__c(SPO_BriefName__c = spoOrder1.id, LineNumber__c = 2, ProductCatalogue__c= pcExo.id);

		Test.startTest();
		insert foSpo1;
		Test.stopTest();

		foSpo1 = [SELECT id, Planned_Manufacturing_Date__c from SPO_FirmOrder__c where id =: foSpo1.id];

		Date plannedManufDateForSpo = System.today().adddays(7);
		Date plannedDeliveryDateForSpo = System.today();

		//System.assertEquals(plannedManufDateForSpo, foSpo1.Planned_Manufacturing_Date__c);
	}

	@isTest
	static void test_updateSimpleProdStatus() {
		ProductCatalogue__c pc = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0001' LIMIT 1];
		Opportunity mypOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];

		// create a firm order
		Test.startTest();
		SPO_FirmOrder__c fo = LV_TestFactory.createFirmOrder(mypOrder.id, 1, pc.id);
		insert fo;

		fo.MIY_ProductionStatus__c = '001';
		update fo;

	//	fo.SPO_TechETLStatus__c = 'Y';
	//	update fo;

		
		fo = [SELECT Id, MIY_ProductionStatus__c, MIY_ProductionStatusSimple__c FROM SPO_FirmOrder__c WHERE Id =: fo.Id];
		System.assertEquals('To be manufactured', fo.MIY_ProductionStatusSimple__c);
        Test.stopTest();
	}

	@isTest
	static void test_updateDeliveryDate() {
		ProductCatalogue__c pc = [SELECT Id, LeadTimeDistribution__c FROM ProductCatalogue__c WHERE SKU__c = 'P0001' LIMIT 1];
	//	ProductCatalogue__c pcExo = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0002' LIMIT 1];
		Opportunity mypOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
		MIY_LeadTime__c lt = [SELECT Id, Exotic_Distribution_Lead_Time_in_days__c, Non_Exotic_Distribution_LT_in_days__c FROM MIY_LeadTime__c LIMIT 1];
		
        Test.startTest();

            // create a firm order
            SPO_FirmOrder__c fo = LV_TestFactory.createFirmOrder(mypOrder.id, 1, pc.id);
            insert fo;
        //	SPO_FirmOrder__c foExo = LV_TestFactory.createFirmOrder(mypOrder.id, 9, pcExo.id);
        //	insert foExo;
    
            Date pddTest = Date.today().addDays(Integer.valueOf(pc.LeadTimeDistribution__c));
            Date exoPddTest = pddTest.addDays(Integer.valueOf(lt.Exotic_Distribution_Lead_Time_in_days__c));
            pddTest = pddTest.addDays(Integer.valueOf(lt.Non_Exotic_Distribution_LT_in_days__c));
    
            fo.SPO_FirmOrderStatus__c = 'Distribution in progress';
            update fo;
        //	foExo.SPO_FirmOrderStatus__c = 'Distribution in progress';
        //	update foExo;
    
            fo = [SELECT Id, Planned_Delivery_date__c FROM SPO_FirmOrder__c WHERE Id =: fo.Id LIMIT 1];
        //	foExo = [SELECT Id, Planned_Delivery_date__c FROM SPO_FirmOrder__c WHERE Id =: foExo.Id LIMIT 1];
            System.assertEquals(pddTest, fo.Planned_Delivery_date__c);
        //	System.assertEquals(exoPddTest, foExo.Planned_Delivery_date__c);
    
        	List <SPO_FirmOrder__c> foList = new List <SPO_FirmOrder__c> {fo/*,foExo*/};
            Set< String > ordersIds = new Set< String >{String.valueOf( mypOrder.id)};
    		Set< String > productsIds = new Set< String >{String.valueOf(pc.Id )/*,String.valueOf(pcExo.Id )*/};
            Map<Id,Date> foIdToStartDate= new Map<Id,Date>();
            foIdToStartDate.put(fo.id, pddTest);
        //	foIdToStartDate.put(foExo.id, exoPddTest);
            FirmOrderTriggerHandler.updateDeliveryDate(foList, ordersIds,productsIds, foIdToStartDate);
            
       Test.stopTest();

	}

	@isTest
	static void test_modifyProductAllocations() {
		System.debug('== FirmOrderTriggerHandler_TEST.test_modifyProductAllocations ==');

		ProductCatalogue__c pc = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0001' LIMIT 1];
		//ProductCatalogue__c pc2 = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0003' LIMIT 1];
		Opportunity mypOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];
		Product_Allocation__c pa = [SELECT Id, Reserved_Quantity__c FROM Product_Allocation__c WHERE Product__c = :pc.Id LIMIT 1];
		//Product_Allocation__c storeAllocation = [SELECT Id, Reserved_Quantity__c FROM Product_Allocation__c WHERE Product__c = :pc2.Id LIMIT 1];
		
		Decimal paReservedA = pa.Reserved_Quantity__c;
        Test.startTest();

		System.debug('paReservedA'+paReservedA);
		// create a firm order
		SPO_FirmOrder__c fo = LV_TestFactory.createFirmOrder(mypOrder.id, 1, pc.id);
		//SPO_FirmOrder__c fo2 = LV_TestFactory.createFirmOrder(mypOrder.id, 2, pc2.id);

		// run test
		insert fo;
		//insert fo2;
		pa = [
				SELECT Id, Product__c, Zone__c, Available_Quantity__c, Reserved_Quantity__c
				FROM Product_Allocation__c
				WHERE Id = :pa.Id LIMIT 1
		];
		// storeAllocation = [
		// 		SELECT Id, Product__c, Zone__c, Available_Quantity__c, Reserved_Quantity__c
		// 		FROM Product_Allocation__c
		// 		WHERE Id = :storeAllocation.Id LIMIT 1
		// ];

		Decimal paReservedB = pa.Reserved_Quantity__c;
		System.debug('paReservedB'+paReservedB);

		fo.Cancellation_Reason__c = 'Client - Client decision';
		fo.Cancellation_Comment__c = 'testing';
		fo.SPO_FirmOrderStatus__c = 'Cancelled by store';
		update fo;

		// pa = [
		// 		SELECT Id, Product__c, Zone__c, Available_Quantity__c, Reserved_Quantity__c
		// 		FROM Product_Allocation__c
		// 		WHERE Id = :pa.Id LIMIT 1
		// ];
		Decimal paReservedC = pa.Reserved_Quantity__c;
		System.debug('paReservedC'+paReservedC);

	//	fo = [SELECT id, PlannedDeliveryDate__c, Planned_Delivery_date__c from SPO_FirmOrder__c where id =: fo.id LIMIT 1];

		// for non exotic firm order
		System.assertEquals(0, paReservedA);
		System.assertEquals(1, paReservedB);
	//	System.assertEquals(0, paReservedC);
	       Test.stopTest();

	}

	@isTest
	static void test_insertProductConfigDetails() {
		 //Test.setMock(HttpCalloutMock.class, new MockHttpResponse('successJsonFluidData', 'json'));

		ProductCatalogue__c pc = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0001' LIMIT 1];
		Opportunity mypOrder = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'ECO' LIMIT 1];
		

		ProductCatalogue__c pc2 = [SELECT Id FROM ProductCatalogue__c WHERE SKU__c = 'P0002' LIMIT 1];
		Opportunity mypOrder2 = [SELECT Id FROM Opportunity WHERE ApplicationSource__c = 'PERSO' LIMIT 1];


		// create a firm order
		SPO_FirmOrder__c fo = LV_TestFactory.createFirmOrder(mypOrder.id, 1, pc.id);
		SPO_FirmOrder__c fo2 = LV_TestFactory.createFirmOrder(mypOrder2.id, 2, pc2.id);
		fo.FluidRecipeId__c = '12345';
	//	fo2.FluidRecipeId__c = 'Sendtoprod';

		// run test
		Test.startTest();
	//		insert fo;
	//		insert fo2;
		Test.stopTest();

		List<ProductConfigurationDetail__c> configDetails = [SELECT Id FROM ProductConfigurationDetail__c WHERE Order_Line_Item__c = :fo.Id];
	//	fo2 = [SELECT id, FluidRecipeId__c FROM SPO_FirmOrder__c where id =: fo2.id];
	//	System.assertEquals(5, configDetails.size());
	//	System.assertEquals(fo2.FluidRecipeId__c, null);
	}
}