force-app/main/default/objects/TWIST_App_Setting__mdt/TWIST_App_Setting__mdt.object-meta.xml
<CustomObject>
    <label>TWIST App Setting</label>
    <pluralLabel>TWIST App Settings</pluralLabel>
</CustomObject>

force-twist/main/default/objects/TWIST_App_Setting__mdt/fields/ValueType__c.field-meta.xml
<CustomField>
    <fullName>ValueType__c</fullName>
    <description>Define the type of the Value inserted</description>
    <label>ValueType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-twist/main/default/classes/TWIST_AppSettings_UTIL.cls
public with sharing class TWIST_AppSettings_UTIL {
    
    public static Object getSetting(String key) {
        TWIST_App_Setting__mdt setting = getSettingRaw(key);
        return setting == null ? null : setting.Value__c;
    }
    
    /** PRIVATE METHODS ******************************************************************************************************************* */

    private static TWIST_App_Setting__mdt getSettingRaw(String key) {
        List<TWIST_App_Setting__mdt> settings = !Test.isRunningTest()
            ? [SELECT Value__c, ValueType__c FROM TWIST_App_Setting__mdt WHERE Key__c = :key]
            : getAppSetingWhenRunningTest();
        return settings.isEmpty() ? null : settings.get(0);
    }

    private static List<TWIST_App_Setting__mdt> getAppSetingWhenRunningTest() {
        return new List<TWIST_App_Setting__mdt> { new TWIST_App_Setting__mdt(
            Key__c = TWIST_AppSettings_UTIL_TEST.akamaizedCommunityUrl.get('key'),
            Value__c = TWIST_AppSettings_UTIL_TEST.akamaizedCommunityUrl.get('value')) };
    }

}