force-app/main/default/objects/CountryLanguage__c/CountryLanguage__c.object-meta.xml
<CustomObject>
    <label>CountryLanguage</label>
    <nameField>
        <label>CountryLanguage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountryLanguages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CountryLanguage__c/fields/ATG_Locale__c.field-meta.xml
<CustomField>
    <fullName>ATG_Locale__c</fullName>
    <label>ATG Locale</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryLanguage__c/fields/Mulesoft_Local__c.field-meta.xml
<CustomField>
    <fullName>Mulesoft_Local__c</fullName>
    <label>Mulesoft Local</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CountryLanguageManager.cls
public without sharing class CountryLanguageManager {

    public static String getMulesoftApisPrefix(String langCountry) {
        List<CountryLanguage__c> items = [SELECT Mulesoft_Local__c FROM CountryLanguage__c WHERE ATG_Locale__c = :langCountry AND Mulesoft_Local__c != null LIMIT 1];
        if (items.size() == 0) {
            String message = String.format('LangCountry "{0}" is unknown', new List<String> { langCountry });
            throw new CountryLanguageManagerException(message);
        }

        return items.get(0).Mulesoft_Local__c;
    }

    private class CountryLanguageManagerException extends Exception {}
    
}