force-app/main/default/objects/Translation__c/Translation__c.object-meta.xml
<CustomObject>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Translation__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ICON</fullName>
                <default>true</default>
                <label>ICON</label>
            </value>
            <value>
                <fullName>NOWYOURS</fullName>
            </value>
            <value>
                <fullName>LVDIAMOND</fullName>
            </value>
            <value>
                <fullName>CATALOGDESKTOP</fullName>
            </value>
            <value>
                <fullName>CATALOGWECOM</fullName>
            </value>
            <value>
                <fullName>CATALOGIOS</fullName>
            </value>
            <value>
                <fullName>JOURNEY</fullName>
            </value>
            <value>
                <fullName>OOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>de</fullName>
                <label>German</label>
            </value>
            <value>
                <fullName>es</fullName>
                <label>Spanish</label>
            </value>
            <value>
                <fullName>fr</fullName>
                <label>French</label>
            </value>
            <value>
                <fullName>it</fullName>
                <label>Italian</label>
            </value>
            <value>
                <fullName>ja</fullName>
                <label>Japanese</label>
            </value>
            <value>
                <fullName>ko</fullName>
                <label>Korean</label>
            </value>
            <value>
                <fullName>zh_CN</fullName>
                <label>Chinese (Simplified)</label>
            </value>
            <value>
                <fullName>zh_TW</fullName>
                <label>Chinese (Traditional)</label>
            </value>
            <value>
                <fullName>he</fullName>
                <label>Hebrew</label>
            </value>
            <value>
                <fullName>ru</fullName>
                <label>Russian</label>
            </value>
            <value>
                <fullName>en_US</fullName>
                <label>English US</label>
            </value>
            <value>
                <fullName>pt_BR</fullName>
                <label>Portuguese</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BL_SITE_Translation_Test.cls
@isTest
public class BL_SITE_Translation_Test  {
    @isTest
    static void testMethodGet(){
        try{
            BL_AppSettings.setAppSettings('Icon');
            User u = IC_Test_Common.prepareTestUser('System Administrator');
            insert u;
            BL_SITE_Translation blTrans = new BL_SITE_Translation();
            system.runAs(u){
                Translation__c trans = new Translation__c(Language__c = 'en_US');
                trans.Key__c = 'Ok';
                trans.Value__c='Ok';
                trans.Is_Public__c = true;
                insert trans;
                Test.startTest();
                blTrans.queryParams  = new Map<String, String>();
                blTrans.queryParams.put('language', null);
                blTrans.executeGET();
                Test.stopTest();
            }
        }
        catch(Exception ex){}
    }

    @isTest
    static void testMethodGet2(){
        BL_AppSettings.setAppSettings('Icon');

        User u = IC_Test_Common.prepareTestUser('System Administrator');
        insert u;
        BL_SITE_Translation blTrans = new BL_SITE_Translation();
        system.runAs(u){
            Translation__c trans = new Translation__c(Language__c = 'en_US');
            trans.Key__c = 'Ok';
            trans.Value__c='Ok';
            trans.Is_Public__c = true;
            trans.Application__c = 'NowYours';
            insert trans;
            Test.startTest();
            blTrans.queryParams  = new Map<String, String>();
            blTrans.queryParams.put('language','fr');
            blTrans.queryParams.put('application','NowYours');
            blTrans.executeGET();
            Test.stopTest();
        }
    }
}