force-app/main/default/objects/ProductSettings__c/ProductSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Product settings used for ProductReferential or ProductCatalogue objects (not possible by Custom Metadata Type with Formula fields)</description>
    <label>Product Settings</label>
</CustomObject>

force-app/main/default/objects/ProductSettings__c/fields/ProductCarouselWidth__c.field-meta.xml
<CustomField>
    <fullName>ProductCarouselWidth__c</fullName>
    <defaultValue>400</defaultValue>
    <description>Holds the width of the carousel image on the creation home page (used in ProductTile bundle)</description>
    <label>ProductCarouselWidth</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SO_PictureCarouselController_TEST.cls
@isTest
public class SO_PictureCarouselController_TEST {
    
    @isTest
    public static void testGetProductCarouselWidth(){
        ProductSettings__c settings = new ProductSettings__c(Name = 'Test', ProductCarouselWidth__c = 123);
        insert settings;

        Test.startTest();
        Integer result = SO_PictureCarouselController.getProductCarouselWidth();
        Test.stopTest();
        
        System.assertNotEquals(null, result);
        System.assertEquals(123, result, 'getProductCarouselWidth() did not return the expected value');
    }
}