force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AFN</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARP</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BOV</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYB</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/MacroMaterial__c.field-meta.xml
<CustomField>
    <fullName>MacroMaterial__c</fullName>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/OrderATGId__c.field-meta.xml
<CustomField>
    <fullName>OrderATGId__c</fullName>
    <externalId>true</externalId>
    <label>Order ATG ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Jewelry</fullName>
            </value>
            <value>
                <fullName>Leather Goods</fullName>
            </value>
            <value>
                <fullName>Perfume</fullName>
            </value>
            <value>
                <fullName>Ready To Wear</fullName>
            </value>
            <value>
                <fullName>Shoes</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/RMSSKUCode__c.field-meta.xml
<CustomField>
    <fullName>RMSSKUCode__c</fullName>
    <label>Code RMS du produit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N83</fullName>
            </value>
            <value>
                <fullName>V24</fullName>
            </value>
            <value>
                <fullName>V06</fullName>
            </value>
            <value>
                <fullName>V88</fullName>
            </value>
            <value>
                <fullName>V14</fullName>
            </value>
            <value>
                <fullName>V85</fullName>
            </value>
            <value>
                <fullName>V15</fullName>
            </value>
            <value>
                <fullName>V18</fullName>
            </value>
            <value>
                <fullName>V76</fullName>
            </value>
            <value>
                <fullName>V35</fullName>
            </value>
            <value>
                <fullName>V25</fullName>
            </value>
            <value>
                <fullName>V61</fullName>
            </value>
            <value>
                <fullName>V38</fullName>
            </value>
            <value>
                <fullName>V42</fullName>
            </value>
            <value>
                <fullName>V62</fullName>
            </value>
            <value>
                <fullName>V86</fullName>
            </value>
            <value>
                <fullName>V50</fullName>
            </value>
            <value>
                <fullName>V33</fullName>
            </value>
            <value>
                <fullName>V57</fullName>
            </value>
            <value>
                <fullName>V74</fullName>
            </value>
            <value>
                <fullName>V36</fullName>
            </value>
            <value>
                <fullName>V82</fullName>
            </value>
            <value>
                <fullName>V80</fullName>
            </value>
            <value>
                <fullName>V21</fullName>
            </value>
            <value>
                <fullName>V65</fullName>
            </value>
            <value>
                <fullName>V72</fullName>
            </value>
            <value>
                <fullName>V54</fullName>
            </value>
            <value>
                <fullName>V31</fullName>
            </value>
            <value>
                <fullName>V32</fullName>
            </value>
            <value>
                <fullName>V13</fullName>
            </value>
            <value>
                <fullName>WFR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/StoreRetailCode__c.field-meta.xml
<CustomField>
    <fullName>StoreRetailCode__c</fullName>
    <label>Store Retail Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TicketNumber__c.field-meta.xml
<CustomField>
    <fullName>TicketNumber__c</fullName>
    <externalId>true</externalId>
    <label>Ticket Number</label>
    <length>26</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionCCFlag__c.field-meta.xml
<CustomField>
    <fullName>TransactionCCFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transaction Click &amp; Collect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionEAFlag__c.field-meta.xml
<CustomField>
    <fullName>TransactionEAFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transaction Endless Aisles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionStHFlag__c.field-meta.xml
<CustomField>
    <fullName>TransactionStHFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The order is placed in a store but the product is delivered at home</description>
    <label>Transaction Store To Home</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionStoreType__c.field-meta.xml
<CustomField>
    <fullName>TransactionStoreType__c</fullName>
    <label>Transaction Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>CSC</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionStSFlag__c.field-meta.xml
<CustomField>
    <fullName>TransactionStSFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The order is placed in store A and product is collected at store B</description>
    <label>Transaction Store To Store</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionTotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TransactionTotalAmount__c</fullName>
    <label>Transaction Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/classes/IDENTITY_WS_PurchaseHistory_TEST.cls
@isTest
private class IDENTITY_WS_PurchaseHistory_TEST {

    @testSetup static void setup() {
           
        Account acct = new Account(
            LastName = 'TCLTest'
        );
        insert acct;

        List<String> storeTypes = new List<String>{'Store','Web','CSC','Store'};
        List<Boolean> flag1 = new List<Boolean>{true,false,false,false};
        List<Boolean> flag2 = new List<Boolean>{false,true,false,false};  
        List<Boolean> flag3 = new List<Boolean>{false,false,true,false};
        List<Boolean> flag4 = new List<Boolean>{false,false,false,true};
        List<Integer> price = new List<Integer>{225,225,225,-225};


        List<PPR_PurchProduct__c> purchases = new List<PPR_PurchProduct__c>();
        for (Integer i=0;i<4;i++) {
            purchases.add(new PPR_PurchProduct__c(    
                OrderATGId__c='ABEY69',
                RMSSKUCode__c='LP0001',
                StoreRetailCode__c='WFR',
                Store__c='WFR',
                Quantity__c=1,
                Amount__c=price.get(i),
                TransactionTotalAmount__c=225,
                CurrencyCode__c='EUR',
                MacroMaterial__c='TEXTILE',
                Model__c='HKB05WZQD 2054 MULTI ZIP LIGHT',
                ProductLine__c='Ready To Wear',
                Name='APOGEE 100ML EDP01',
                TransactionCCFlag__c=flag1.get(i),
                TransactionStHFlag__c=flag2.get(i),
                TransactionEAFlag__c=flag3.get(i),
                TransactionStSFlag__c=flag4.get(i),
                TransactionStoreType__c=storeTypes.get(i),
                TicketNumber__c='261779608',
                Client__c=acct.Id));
        }
        // Insert all opportunities for all accounts.
        insert purchases;

        PPR_PurchProduct__c purchase = new PPR_PurchProduct__c(    
            OrderATGId__c='ABEY69',
            RMSSKUCode__c='LP0001',
            StoreRetailCode__c='WFR',
            Store__c='WFR',
            Quantity__c=1,
            Amount__c=225,
            TransactionTotalAmount__c=225,
            CurrencyCode__c='EUR',
            MacroMaterial__c='TEXTILE',
            Model__c='HKB05WZQD 2054 MULTI ZIP LIGHT',
            ProductLine__c='Ready To Wear',
            Name='APOGEE 100ML EDP01',
            TransactionCCFlag__c=false,
            TransactionStHFlag__c=false,
            TransactionEAFlag__c=false,
            TransactionStSFlag__c=false,
            TransactionStoreType__c='Web',
            TicketNumber__c='261779608',
            Client__c=acct.Id);
        //insert purchase;
        
    } 

    
    
    @isTest
    static void test1(){

        Id recordId = [SELECT Id FROM Account LIMIT 1 ].Id;

        RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
        
    req.requestURI = '/identity/purchaseHistory/'+recordId;


    req.httpMethod = 'GET';
        req.addParameter('exclude', '1,2');
        req.addParameter('orderType', 'digital,retail,CSC');
    RestContext.request = req;
    RestContext.response = res;

        Test.startTest();
        IDENTITY_WS_PurchaseHistory.get();
        Test.stopTest();
    }

  
    
   
             
}