force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ICX_ContactChannel__c.field-meta.xml
<CustomField>
    <fullName>ICX_ContactChannel__c</fullName>
    <description>This field was created for customer service for reporting purposes and populated by a batch</description>
    <label>Contact Channel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Product On Demand</fullName>
            </value>
            <value>
                <fullName>Messaging</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
                <isActive>false</isActive>
                <label>Social</label>
            </value>
            <value>
                <fullName>Web&amp;Email</fullName>
                <isActive>false</isActive>
                <label>Web&amp;Email</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ICX_ContactChannel_RecordId__c.field-meta.xml
<CustomField>
    <fullName>ICX_ContactChannel_RecordId__c</fullName>
    <description>This field was created for customer service for reporting purposes and populated by a batch</description>
    <label>Contact Channel Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ICX_CSCContactDate__c.field-meta.xml
<CustomField>
    <fullName>ICX_CSCContactDate__c</fullName>
    <label>CSC Contact Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ICX_CSCUser__c.field-meta.xml
<CustomField>
    <fullName>ICX_CSCUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSC User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchased_Products_Related</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/OrderATGId__c.field-meta.xml
<CustomField>
    <fullName>OrderATGId__c</fullName>
    <externalId>true</externalId>
    <label>Order ATG ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/PurchasedDate__c.field-meta.xml
<CustomField>
    <fullName>PurchasedDate__c</fullName>
    <label>Purchased Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/RMSSKUCode__c.field-meta.xml
<CustomField>
    <fullName>RMSSKUCode__c</fullName>
    <label>Code RMS du produit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TechTransactionId__c.field-meta.xml
<CustomField>
    <fullName>TechTransactionId__c</fullName>
    <formula>if(
!ISBLANK( OrderATGId__c ), 
OrderATGId__c, 
TransactionRMSId__c 
)</formula>
    <label>Tech Transaction Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionRMSId__c.field-meta.xml
<CustomField>
    <fullName>TransactionRMSId__c</fullName>
    <externalId>true</externalId>
    <label>Transaction RMS Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionStoreType__c.field-meta.xml
<CustomField>
    <fullName>TransactionStoreType__c</fullName>
    <label>Transaction Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>CSC</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/CSC_Call.recordType-meta.xml
<RecordType>
    <fullName>CSC_Call</fullName>
    <active>true</active>
    <description>Record Type for call coming from CTI</description>
    <label>ICONICS Call</label>
</RecordType>

force-iconics/main/default/classes/ICX_BatchRelateTransactionToCall.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-13-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global class ICX_BatchRelateTransactionToCall implements Database.Batchable<sObject> {
	
	public class DateFormatException extends Exception {}
	String query;
	
	//Non-parameterized constructor
	global ICX_BatchRelateTransactionToCall() {
		Id CallRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('CSC_Call').getRecordTypeId();

		query = 'SELECT Id,Transaction_Id__c,AccountId,Sku_Number__c,Purchased_Product__c,CreatedDate,CallType ' +
		        'FROM Task WHERE Purchased_Product__c=null AND CreatedDate>=LAST_N_DAYS:7 AND Sku_Number__c != null AND CallType in (\'Outbound\', \'Inbound\') AND ( Transaction_Id__c != null OR AccountId != null ) AND RecordTypeId = \'' + CallRecordTypeId + '\'' ;
	}

	//Constructor that takes a DateTime formated String as a start date
	global ICX_BatchRelateTransactionToCall(String dateInputByUser) {
		Id CallRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('CSC_Call').getRecordTypeId();

		// // Date d;
		// DateTime dt;
		// try {
		// 	// d = Date.valueOf(dateInputByUser);
		// 	dt = DateTime.valueOf(dateInputByUser);
		// }
		// catch(TypeException e) {
		// 	// System.debug('Invalid date format. Please use the format YYYY-MM-DD');
		// 	System.debug('Invalid date format. Please use the format like 2023-02-12T08:42:41.333+02:00');
		// }
		// // String dateTimeFormatedInput = dateInputByUser + 'T00:00:00Z';
		// String dateTimeFormatedInput = dateInputByUser;

		// Check if the input date is in the correct format
		String dateTimeRegex = '\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z';
		if (!Pattern.matches(dateTimeRegex, dateInputByUser)) {
			throw new DateFormatException('Invalid datetime format. Expected format is "YYYY-MM-DDTHH:mm:ssZ".');
		}
		
		query = 'SELECT Id,Transaction_Id__c,AccountId,Sku_Number__c,Purchased_Product__c,CreatedDate,CallType ' +
		        'FROM Task WHERE Purchased_Product__c=null AND CreatedDate >= ' + dateInputByUser + ' AND Sku_Number__c != null AND CallType in (\'Outbound\', \'Inbound\') AND ( Transaction_Id__c != null OR AccountId != null ) AND RecordTypeId = \'' + CallRecordTypeId + '\'' ;
	}

	//Constructor that takes 2 DateTime formated String as a start and end date
	global ICX_BatchRelateTransactionToCall(String startDateInputByUser, String endDateInputByUser) {
		Id CallRecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('CSC_Call').getRecordTypeId();

		// // Date d;
		// DateTime startDt;
		// DateTime endDt;
		// try {
		// 	// d = Date.valueOf(dateInputByUser);
		// 	startDt = DateTime.valueOf(startDateInputByUser);
		// 	endDt = DateTime.valueOf(endDateInputByUser);
		// }
		// catch(TypeException e) {
		// 	// System.debug('Invalid date format. Please use the format YYYY-MM-DD');
		// 	System.debug('Invalid date format. Please use the format like 2023-02-12T08:42:41.333+02:00');
		// }
		// String dateTimeFormatedInput = dateInputByUser + 'T00:00:00Z';
		// String dateTimeFormatedInput = dateInputByUser;

		// Check if the input dates are in the correct format
		String dateTimeRegex = '\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z';
		if (!Pattern.matches(dateTimeRegex, startDateInputByUser) || !Pattern.matches(dateTimeRegex, endDateInputByUser)) {
			throw new DateFormatException('Invalid datetime format. Expected format is "YYYY-MM-DDTHH:mm:ssZ".');
		}
		
		query = 'SELECT Id,Transaction_Id__c,AccountId,Sku_Number__c,Purchased_Product__c,CreatedDate,CallType ' +
				'FROM Task WHERE Purchased_Product__c=null AND CreatedDate >= ' + startDateInputByUser + ' AND CreatedDate < ' + endDateInputByUser + 
				' AND Sku_Number__c != null AND CallType in (\'Outbound\', \'Inbound\') AND ( Transaction_Id__c != null OR AccountId != null ) AND RecordTypeId = \'' + CallRecordTypeId + '\'' ;
	}
	
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
   		try{
            if(scope.size() > 0){
                this.setTransactions((List<Task>) scope);
            }
            
        }catch (DmlException e){
            // Process exception here
            System.debug('#### '+e.getTypeName()+' Exception:'+e.getMessage()+' '+e.getStackTraceString());
        }
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}

	private void setTransactions(List<Task> calls) {
		Map<String,Task> distantOrderCallsMap = new Map<String,Task>();
		Map<String,Task> clientCallsMap = new Map<String,Task>();
		Set<Id> callIds = new Set<Id>();
		Set<String> distantOrderNumbers = new Set<String>();
		Set<Id> clients = new Set<Id>();
		Set<String> skus = new Set<String>();

		Map<Id,PPR_PurchProduct__c> transactionMap = new Map<Id,PPR_PurchProduct__c>();
		List<Task> callsToUpdate = new List<Task>();

		for(Task call : calls) {
			if(String.isNotBlank(call.Transaction_Id__c)&& String.isNotBlank(call.Sku_Number__c)) {
				String transactionId = call.Transaction_Id__c.toLowerCase().trim();
				distantOrderCallsMap.put(transactionId+call.Sku_Number__c, call);
				distantOrderNumbers.add(transactionId);
			}
			clientCallsMap.put(call.AccountId+call.Sku_Number__c, call);
			if(String.isNotBlank(call.AccountId)) {
				clients.add(call.AccountId);
			}
			if(String.isNotBlank(call.Sku_Number__c)) {
				skus.add(call.Sku_Number__c);
			}
		} 

		List<PPR_PurchProduct__c> transactions = [SELECT Id,Client__c,SKU__c,PurchasedDate__c,TechTransactionId__c,RMSSKUCode__c
		FROM PPR_PurchProduct__c
		WHERE Quantity__c >0 AND ((OrderATGId__c IN:distantOrderNumbers OR TransactionRMSId__c IN:distantOrderNumbers) OR Client__c IN:clients) 
		AND (SKU__c IN:skus OR RMSSKUCode__c IN:skus) AND PurchasedDate__c>=LAST_N_DAYS:7 AND ICX_ContactChannel__c=null AND ICX_ContactChannel_RecordId__c=null
		AND ICX_CSCUser__c=null AND ICX_CSCContactDate__c=null AND createdDate < TODAY AND TransactionStoreType__c in ('CSC','WEB', 'Store')] ;

		system.debug('DISTANT ORDER CALL MAP');

		system.debug(distantOrderCallsMap);
		system.debug(transactions);


		Task currentCall;
		Date currentCallCreatedDate;

		for(PPR_PurchProduct__c t : transactions) {
			string skuORrmssku = '';
			system.debug('DISTANT ORDER CALL MAP');

			system.debug(distantOrderCallsMap);

			if(distantOrderCallsMap!=null && (distantOrderCallsMap.containsKey(t.TechTransactionId__c+t.SKU__c)||distantOrderCallsMap.containsKey(t.TechTransactionId__c+t.RMSSKUCode__c))) {

				skuORrmssku =  distantOrderCallsMap.containskey(t.TechTransactionId__c+t.SKU__c) ? t.SKU__c :(distantOrderCallsMap.containskey(t.TechTransactionId__c+t.RMSSKUCode__c) ? t.RMSSKUCode__c: '') ;
				system.debug(skuORrmssku);

				if(!String.isBlank(skuORrmssku)){
					currentCall = distantOrderCallsMap.get(t.TechTransactionId__c+skuORrmssku);
					currentCallCreatedDate = Date.newInstance(currentCall.CreatedDate.year(), currentCall.CreatedDate.month(), currentCall.CreatedDate.day());

					if(t.PurchasedDate__c <= currentCallCreatedDate.addDays(7) && t.PurchasedDate__c >= currentCallCreatedDate){
						currentCall.Purchased_Product__c = t.Id;
						if(!callIds.contains(currentCall.Id)) {
							callsToUpdate.add(currentCall);
							callIds.add(currentCall.Id);
							distantOrderCallsMap.remove(t.TechTransactionId__c+skuORrmssku);
						}
						if(clientCallsMap != null && clientCallsMap.containsKey(t.Client__c+skuORrmssku)) {
							clientCallsMap.remove(t.Client__c+skuORrmssku);
						}
					}
				}
			}
			else if (clientCallsMap != null && (clientCallsMap.containsKey(t.Client__c+t.SKU__c)||clientCallsMap.containsKey(t.Client__c+t.RMSSKUCode__c))) {
				skuORrmssku =  clientCallsMap.containskey(t.Client__c+t.SKU__c) ? t.SKU__c :(clientCallsMap.containskey(t.Client__c+t.RMSSKUCode__c) ? t.RMSSKUCode__c: '') ;

				if(!String.isBlank(skuORrmssku)){
					currentCall = clientCallsMap.get(t.Client__c+skuORrmssku);
					currentCallCreatedDate = Date.newInstance(currentCall.CreatedDate.year(), currentCall.CreatedDate.month(), currentCall.CreatedDate.day());
					
					if(t.PurchasedDate__c <= currentCallCreatedDate.addDays(7) && t.PurchasedDate__c >= currentCallCreatedDate) {
						currentCall.Purchased_Product__c = t.Id;
						if(!callIds.contains(currentCall.Id)) {
							callsToUpdate.add(currentCall);
							callIds.add(currentCall.Id);
							clientCallsMap.remove(t.Client__c+skuORrmssku);
						}
					}
				}


			}
		}

		System.debug(LoggingLevel.ERROR, 'callsToUpdate=' + callsToUpdate);

		if(callsToUpdate.size() > 0) {
			update callsToUpdate;
		}
	}
}