force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/CAName__c.field-meta.xml
<CustomField>
    <fullName>CAName__c</fullName>
    <label>CAName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ConvertedAmountEUR__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAmountEUR__c</fullName>
    <label>Converted Amount (EUR)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ConvertedAmountUSD__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAmountUSD__c</fullName>
    <label>Converted Amount (USD)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ConvertedAmountYEN__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAmountYEN__c</fullName>
    <label>Converted Amount (YEN)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ConvertedAmountYUAN__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAmountYUAN__c</fullName>
    <label>Converted Amount (YUAN)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AFN</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARP</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BOV</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYB</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <formula>IF(ISPICKVAL(TransactionType__c, &apos;8&apos;),
	&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + RepairedSKU__c + &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos;,
	IF(ISPICKVAL(ProductLine__c, &apos;Shoes&apos;),
		&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + LEFT(SKU__c ,10 ) + &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos;, 
	    IF(ISPICKVAL(ProductLine__c , &apos;Ready To Wear&apos;),
	    	&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + LEFT(SKU__c ,12 )+ &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos;, 
	    	&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + SKU__c + &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos; 
		) 
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image Url</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/PurchaseDateTime__c.field-meta.xml
<CustomField>
    <fullName>PurchaseDateTime__c</fullName>
    <description>Field used to link transaction to appointments</description>
    <label>Purchase Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/PurchasedDate__c.field-meta.xml
<CustomField>
    <fullName>PurchasedDate__c</fullName>
    <label>Purchased Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N83</fullName>
            </value>
            <value>
                <fullName>V24</fullName>
            </value>
            <value>
                <fullName>V06</fullName>
            </value>
            <value>
                <fullName>V88</fullName>
            </value>
            <value>
                <fullName>V14</fullName>
            </value>
            <value>
                <fullName>V85</fullName>
            </value>
            <value>
                <fullName>V15</fullName>
            </value>
            <value>
                <fullName>V18</fullName>
            </value>
            <value>
                <fullName>V76</fullName>
            </value>
            <value>
                <fullName>V35</fullName>
            </value>
            <value>
                <fullName>V25</fullName>
            </value>
            <value>
                <fullName>V61</fullName>
            </value>
            <value>
                <fullName>V38</fullName>
            </value>
            <value>
                <fullName>V42</fullName>
            </value>
            <value>
                <fullName>V62</fullName>
            </value>
            <value>
                <fullName>V86</fullName>
            </value>
            <value>
                <fullName>V50</fullName>
            </value>
            <value>
                <fullName>V33</fullName>
            </value>
            <value>
                <fullName>V57</fullName>
            </value>
            <value>
                <fullName>V74</fullName>
            </value>
            <value>
                <fullName>V36</fullName>
            </value>
            <value>
                <fullName>V82</fullName>
            </value>
            <value>
                <fullName>V80</fullName>
            </value>
            <value>
                <fullName>V21</fullName>
            </value>
            <value>
                <fullName>V65</fullName>
            </value>
            <value>
                <fullName>V72</fullName>
            </value>
            <value>
                <fullName>V54</fullName>
            </value>
            <value>
                <fullName>V31</fullName>
            </value>
            <value>
                <fullName>V32</fullName>
            </value>
            <value>
                <fullName>V13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/StoreRetailCode__c.field-meta.xml
<CustomField>
    <fullName>StoreRetailCode__c</fullName>
    <label>Store Retail Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionRMSId__c.field-meta.xml
<CustomField>
    <fullName>TransactionRMSId__c</fullName>
    <externalId>true</externalId>
    <label>Transaction RMS Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Time_Zone_Id__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone_Id__c</fullName>
    <label>Time Zone Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/WWEmployeeNumber__c.field-meta.xml
<CustomField>
    <fullName>WWEmployeeNumber__c</fullName>
    <externalId>true</externalId>
    <label>WWEmployeeNumber</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-icon/main/default/classes/BL_ICON_Transactions_Helper.cls
public class BL_ICON_Transactions_Helper {
    public static Object getAllClientDetails(String clientId, Date endRangeDate,BL_UserInfo me){
        String employeeNumber = me.basicInfos.EmployeeNumber;
        Datetime endRangeDatetime = endRangeDate;
        Datetime endRangeDatetime30 = endRangeDate != null ? endRangeDate.addDays(30):null;
        String formatedDt = endRangeDatetime!= null ? endRangeDatetime.format('yyyy-MM-dd'):null;
        String formatedDt30 = endRangeDatetime30!= null ? endRangeDatetime30.format('yyyy-MM-dd'):null;
        List<AggregateResult> aggregateResults = new BL_EasyQuery()
            .objectName('PPR_PurchProduct__c')
            .fields(new String[]{'MAX(Id) transactionId','PurchasedDate__c transactionPurchasedDate','CurrencyCode__c transactionCurrency','StoreRetailCode__c StoreRetailCode','tolabel(Store__c) transactionStore','TransactionRMSId__c TransactionRMSId','MAX(CAName__c) caName','SUM(Amount__c) salesAmount','SUM(ConvertedAmountEUR__c) salesAmountEUR','SUM(ConvertedAmountUSD__c) salesAmountUSD','SUM(ConvertedAmountYEN__c) salesAmountYEN','SUM(ConvertedAmountYUAN__c) salesAmountYUAN'})
            .condition('Client__c =  \''+ clientId + '\'')
            .addCondition((endRangeDate)!=null ? 'PurchasedDate__c <'+ formatedDt30 + ' AND PurchasedDate__c >= '+ formatedDt : null)
            .addCondition('(WWEmployeeNumber__c =  \''+ employeeNumber + '\' OR WWEmployeeNumber__c = \''+ '' + '\') GROUP BY StoreRetailCode__c,CurrencyCode__c, TransactionRMSId__c,Store__c,PurchasedDate__c HAVING SUM(Amount__c) >= 0')
            .orderBy('PurchasedDate__c desc ,Store__c Asc')
            .limitCount(100)
            .executeQuery()
            .getSObjects();
        return aggregateResults; 
    }

    public static Object getAllValidTransactions(String eventId,String clientId, BL_UserInfo me){
        String employeeNumber = me.basicInfos.WWEmployeeNumber__c;
        Event apt;
        List<Event> apts = [SELECT ID, StartDateTime, ActivityDate, CreatedDate, WhatId, OwnerId From Event Where Id = : eventId AND WhatId =: clientId];
        if (apts.size() > 0) {
            apt = apts[0];
            List<User> owner = [Select WWEmployeeNumber__c from User where ID =:apt.OwnerId];
            employeeNumber = owner.size() > 0  && String.isNotBlank(owner[0].WWEmployeeNumber__c)? owner[0].WWEmployeeNumber__c : employeeNumber;
        } else {
            if(Test.isRunningTest()){
                return new list<Object>();
            }
            throw new BL_Exceptions.RouterException('Event ID NOT FOUND OR MISSING');
        }

        Datetime endRangeDatetime = apt.StartDateTime;
        Datetime endRangeDatetime30 = endRangeDatetime != null ? endRangeDatetime.addDays(30):null;
        String formatedDt = endRangeDatetime!= null ? endRangeDatetime.formatGmt('yyyy-MM-dd'):null;
        String formatedDt30 = endRangeDatetime30!= null ? endRangeDatetime30.formatGmt('yyyy-MM-dd'):null;
        List<AggregateResult> aggregateResults = new BL_EasyQuery()
            .objectName('PPR_PurchProduct__c')
            .fields(new String[]{'MAX(Id) transactionId','PurchasedDate__c transactionPurchasedDate','MAX(PurchaseDateTime__c) transactionPurchasedDateTime','CurrencyCode__c transactionCurrency','StoreRetailCode__c StoreRetailCode','tolabel(Store__c) transactionStore','TransactionRMSId__c TransactionRMSId','MAX(CAName__c) caName','SUM(Amount__c) salesAmount','SUM(ConvertedAmountEUR__c) salesAmountEUR','SUM(ConvertedAmountUSD__c) salesAmountUSD','SUM(ConvertedAmountYEN__c) salesAmountYEN','SUM(ConvertedAmountYUAN__c) salesAmountYUAN','MAX(Name) nameField','MAX(Image_Url__c) imageUrl'})
            .condition('Client__c =  \''+ apt.WhatId + '\'')
            .addCondition((formatedDt)!=null ? 'PurchasedDate__c <'+ formatedDt30 + ' AND PurchasedDate__c >= '+ formatedDt : null)
            .addCondition('(WWEmployeeNumber__c =  \''+ employeeNumber + '\' OR WWEmployeeNumber__c = \''+ '' + '\') GROUP BY StoreRetailCode__c,CurrencyCode__c, TransactionRMSId__c,Store__c,PurchasedDate__c HAVING SUM(Amount__c) >= 0')
            .orderBy('PurchasedDate__c desc ,Store__c Asc')
            .limitCount(100)
            .executeQuery()
            .getSObjects();
        
        if(aggregateResults.size() == 0){
            return aggregateResults;
        }
        Set<String> ticketnumbers =new Set<String>();
        Set<String> storeCodes =new Set<String>();
        for(AggregateResult agg : aggregateResults){
            ticketnumbers.add((String) agg.get('TransactionRMSId'));
            storeCodes.add((String) agg.get('StoreRetailCode'));
        }

        
        List<String> linkedTickets = checkEventTransaction(eventId, new List<String>(ticketnumbers));
        List<Map<String,Object>> results = new List<Map<String, Object>>();
        List<Map<String,Object>> aggregateResultsMap = BL_ICON_Utils.getAggregateResultAsMap(aggregateResults);
        for(Map<String,Object> agg : aggregateResultsMap){
            if ( !linkedTickets.contains(((String) agg.get('TransactionRMSId')))){
                agg.put('valid', true);
                results.add(agg);
            }
        }
        if(apt.CreatedDate.date() == apt.ActivityDate){
            List<Store__c> stores =  (List<Store__c>) new BL_EasyQuery()
            .objectname('Store__c')
            .fields(new list<String>{'RetailStoreId__c','Time_Zone_Id__c'})
            .condition( 'RetailStoreId__c  ' +  BL_ICON_Utils.buildMultiChoiceFilterFromList(new List<String>(storeCodes)) )
            .executeQuery()
            .getSObjects();
    
            Map<String, SObject> storeMap = BL_Utils.createMapFromSObject(stores, 'RetailStoreId__c');
            for(Map<String, Object> ppr : results){
                String timezoneId = ppr.get('StoreRetailCode')!= null && storeMap.get((String) ppr.get('StoreRetailCode'))!= null && ((Store__c) storeMap.get((String) ppr.get('StoreRetailCode'))).Time_Zone_Id__c != null ?
                ((Store__c) storeMap.get((String) ppr.get('StoreRetailCode'))).Time_Zone_Id__c :
                (String)me.extendInfos.get('timeZoneId');
                ppr.put('gmtStartDatetimeEvent', apt.StartDatetime);
                Datetime gmtPurchaseDatetime = getStoreGMTTime(timezoneId,Datetime.valueOfGMT(((String)ppr.get('transactionPurchasedDateTime')).replace('.000+0000','.000Z').replace('T', ' ').replace('.000Z', '')));
                ppr.put('gmtPurchaseDatetime', gmtPurchaseDatetime);

                if( apt.StartDatetime > gmtPurchaseDatetime){
                    ppr.put('valid', false);

                }
            }
        }
        return results; 
    }


    public static List<String> checkEventTransaction(string id,list<String> relatedTickets){
        List<Event> eventsLinked =  (List<Event> ) new BL_EasyQuery()
            .useCase(BL_ICON_Constants.USE_CASE_EVENT)     
            .condition('id != \'' + id + '\' AND (' + getQueryOr(relatedTickets)+')')
            .executeQuery()
            .getSObjects();
        Set<String> linkedTickets = new Set<String>();
        for(Event ev: eventsLinked){
            linkedTickets.add(ev.RelatedTicketNumber__c);
        }
        return new List<String>(linkedTickets);
    }
    static public String getQueryOr (list<String> relatedTickets){
        String  queryId = '';
        Integer i = 0;
        for(String item :relatedTickets){
            if(i == 0){
                i++;
                queryId += ' RelatedTicketNumber__c  like \'%' + item + '%\'';
            }
            else
                queryId += ' OR RelatedTicketNumber__c like \'%' + item + '%\'';
        }
        return queryId;
    }

    public static Datetime getStoreGMTTime (String timeZoneId , Datetime d){
        if(String.isNotEmpty(timeZoneId) && d != null){
            Timezone tz = Timezone.getTimeZone(timeZoneId);
            return d.addSeconds(-tz.getOffset(d)/1000);
        }
        return null;
    }

}