force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ConvertedAmountEUR__c.field-meta.xml
<CustomField>
    <fullName>ConvertedAmountEUR__c</fullName>
    <label>Converted Amount (EUR)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AFN</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARP</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BOV</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYB</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ICX_ContactChannel__c.field-meta.xml
<CustomField>
    <fullName>ICX_ContactChannel__c</fullName>
    <description>This field was created for customer service for reporting purposes and populated by a batch</description>
    <label>Contact Channel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Product On Demand</fullName>
            </value>
            <value>
                <fullName>Messaging</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
                <isActive>false</isActive>
                <label>Social</label>
            </value>
            <value>
                <fullName>Web&amp;Email</fullName>
                <isActive>false</isActive>
                <label>Web&amp;Email</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ICX_ContactChannel_RecordId__c.field-meta.xml
<CustomField>
    <fullName>ICX_ContactChannel_RecordId__c</fullName>
    <description>This field was created for customer service for reporting purposes and populated by a batch</description>
    <label>Contact Channel Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ICX_CSCContactDate__c.field-meta.xml
<CustomField>
    <fullName>ICX_CSCContactDate__c</fullName>
    <label>CSC Contact Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ICX_CSCUser__c.field-meta.xml
<CustomField>
    <fullName>ICX_CSCUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CSC User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchased_Products_Related</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/PurchasedDate__c.field-meta.xml
<CustomField>
    <fullName>PurchasedDate__c</fullName>
    <label>Purchased Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionRMSId__c.field-meta.xml
<CustomField>
    <fullName>TransactionRMSId__c</fullName>
    <externalId>true</externalId>
    <label>Transaction RMS Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionStoreType__c.field-meta.xml
<CustomField>
    <fullName>TransactionStoreType__c</fullName>
    <label>Transaction Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>CSC</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ICX_BatchRelateTransactionToAppointment.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-13-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
// public with sharing class ICX_BatchRelateTransactionToAppointment {
//     public ICX_BatchRelateTransactionToAppointment() {

//     }
// }


///////////////////////////////////////////////////////////////////////////////////////////
global class ICX_BatchRelateTransactionToAppointment implements Database.Batchable<sObject> {
	
	public class DateFormatException extends Exception {}
	String query;
	
	//Non-parameterized constructor
	global ICX_BatchRelateTransactionToAppointment() {
        query = 'SELECT Id, AccountId, CreatedDate ' + 
				'FROM Event WHERE AccountId != null AND CreatedBy.Profile.Name IN (\'ICONiCS_SA\', \'ICONiCS_SA_Manager\', \'ICONiCS_Corporate\', \'System Administrator\') ' + 
				'AND CreatedDate >= LAST_N_DAYS:10 AND Purchased_Product__c = null ORDER BY CreatedDate ASC';
	}

	//Constructor that takes a DateTime formated String
	global ICX_BatchRelateTransactionToAppointment(String dateInputByUser) {

		// Check if the input date is in the correct format
		String dateTimeRegex = '\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z';
		if (!Pattern.matches(dateTimeRegex, dateInputByUser)) {
			throw new DateFormatException('Invalid datetime format. Expected format is "YYYY-MM-DDTHH:mm:ssZ".');
		}

        query = 'SELECT Id, AccountId, CreatedDate ' + 
				'FROM Event WHERE AccountId != null AND CreatedBy.Profile.Name IN (\'ICONiCS_SA\', \'ICONiCS_SA_Manager\', \'ICONiCS_Corporate\', \'System Administrator\') ' + 
				'AND CreatedDate >= ' + dateInputByUser + ' AND Purchased_Product__c = null ORDER BY CreatedDate ASC';
	}

	//Constructor that takes 2 DateTime formated String as a start and end date
	global ICX_BatchRelateTransactionToAppointment(String startDateInputByUser, String endDateInputByUser) {

		// Check if the input dates are in the correct format
		String dateTimeRegex = '\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z';
		if (!Pattern.matches(dateTimeRegex, startDateInputByUser) || !Pattern.matches(dateTimeRegex, endDateInputByUser)) {
			throw new DateFormatException('Invalid datetime format. Expected format is "YYYY-MM-DDTHH:mm:ssZ".');
		}

		query = 'SELECT Id, AccountId, CreatedDate ' + 
				'FROM Event WHERE AccountId != null AND CreatedBy.Profile.Name IN (\'ICONiCS_SA\', \'ICONiCS_SA_Manager\', \'ICONiCS_Corporate\', \'System Administrator\') ' + 
				'AND CreatedDate >= ' + startDateInputByUser + ' AND CreatedDate < ' + endDateInputByUser + ' AND Purchased_Product__c = null ORDER BY CreatedDate ASC';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
   		try {
            if(scope.size() > 0){
                this.setTransactions((List<Event>) scope);
            }
        } catch (DmlException e){
            // Process exception here
            System.debug('#### '+e.getTypeName()+' Exception:'+e.getMessage()+' '+e.getStackTraceString());
        }
	}
	
	global void finish(Database.BatchableContext BC) {}

	private void setTransactions(List<Event> events) {
		 Set<Id> eventIds = new Set<Id>();
		 Set<Id> clients = new Set<Id>();
		 List<Event> eventsToUpdate = new List<Event>();
		 Map<String,Event> clientEventsMap = new Map<String,Event>();

		 for(Event event : events) {
		 	if(event.AccountId != null && String.valueOf(event.AccountId) != '' && !clients.contains(event.AccountId) ) {
				 clients.add(event.AccountId);
				 clientEventsMap.put(Event.AccountId, Event);
			}
		 }

		List<PPR_PurchProduct__c> transactions = [SELECT Id,Client__c,PurchasedDate__c
		FROM PPR_PurchProduct__c
		WHERE Quantity__c > 0 AND Client__c IN:clients AND TransactionStoreType__c in ('CSC','WEB', 'Store')
		AND PurchasedDate__c >= LAST_N_DAYS:10 AND ICX_ContactChannel__c = null AND ICX_ContactChannel_RecordId__c = null
		AND ICX_CSCUser__c = null AND ICX_CSCContactDate__c = null AND createdDate < TODAY ORDER BY CreatedDate ASC];

		Event currentEvent;
		Date currentEventCreatedDate;

		for(PPR_PurchProduct__c t : transactions) {
			if (clients != null && clients.contains(t.Client__c) && clientEventsMap.get(t.Client__c) != null) {
				currentEvent = clientEventsMap.get(t.Client__c);

				currentEventCreatedDate = Date.newInstance(currentEvent.CreatedDate.year(), currentEvent.CreatedDate.month(), currentEvent.CreatedDate.day());

				if(t.PurchasedDate__c <= currentEventCreatedDate.addDays(10) && t.PurchasedDate__c >= currentEventCreatedDate) {
					currentEvent.Purchased_Product__c = t.Id;
					// t.TransactionRMSId__c ? currentEvent.RelatedTicketNumber__c = t.TransactionRMSId__c : false;
					// t.Amount__c ? currentEvent.SaleAmount__c = t.Amount__c : false;
					// t.CurrencyCode__c ? currentEvent.Currency__c = t.CurrencyCode__c : false;
					// t.ConvertedAmountEUR__c ? currentEvent.Transaction_Total_Converted_Amount_EUR__c = t.ConvertedAmountEUR__c : false;

					if(!eventIds.contains(currentEvent.Id)) {
						eventsToUpdate.add(currentEvent);
						eventIds.add(currentEvent.Id);
						clientEventsMap.remove(t.Client__c);
					}
				}
			}
		}

		System.debug(LoggingLevel.ERROR, 'eventsToUpdate=' + eventsToUpdate);

		if(eventsToUpdate.size() > 0) {
			update eventsToUpdate;
		}
	}
}