force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AFN</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARP</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BOV</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYB</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <formula>IF(ISPICKVAL(TransactionType__c, &apos;8&apos;),
	&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + RepairedSKU__c + &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos;,
	IF(ISPICKVAL(ProductLine__c, &apos;Shoes&apos;),
		&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + LEFT(SKU__c ,10 ) + &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos;, 
	    IF(ISPICKVAL(ProductLine__c , &apos;Ready To Wear&apos;),
	    	&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + LEFT(SKU__c ,12 )+ &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos;, 
	    	&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + SKU__c + &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos; 
		) 
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image Url</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Jewelry</fullName>
            </value>
            <value>
                <fullName>Leather Goods</fullName>
            </value>
            <value>
                <fullName>Perfume</fullName>
            </value>
            <value>
                <fullName>Ready To Wear</fullName>
            </value>
            <value>
                <fullName>Shoes</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/PurchaseCountry__c.field-meta.xml
<CustomField>
    <fullName>PurchaseCountry__c</fullName>
    <description>The country in which the product has been purchased.</description>
    <label>Purchase Country</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/PurchasedDate__c.field-meta.xml
<CustomField>
    <fullName>PurchasedDate__c</fullName>
    <label>Purchased Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N83</fullName>
            </value>
            <value>
                <fullName>V24</fullName>
            </value>
            <value>
                <fullName>V06</fullName>
            </value>
            <value>
                <fullName>V88</fullName>
            </value>
            <value>
                <fullName>V14</fullName>
            </value>
            <value>
                <fullName>V85</fullName>
            </value>
            <value>
                <fullName>V15</fullName>
            </value>
            <value>
                <fullName>V18</fullName>
            </value>
            <value>
                <fullName>V76</fullName>
            </value>
            <value>
                <fullName>V35</fullName>
            </value>
            <value>
                <fullName>V25</fullName>
            </value>
            <value>
                <fullName>V61</fullName>
            </value>
            <value>
                <fullName>V38</fullName>
            </value>
            <value>
                <fullName>V42</fullName>
            </value>
            <value>
                <fullName>V62</fullName>
            </value>
            <value>
                <fullName>V86</fullName>
            </value>
            <value>
                <fullName>V50</fullName>
            </value>
            <value>
                <fullName>V33</fullName>
            </value>
            <value>
                <fullName>V57</fullName>
            </value>
            <value>
                <fullName>V74</fullName>
            </value>
            <value>
                <fullName>V36</fullName>
            </value>
            <value>
                <fullName>V82</fullName>
            </value>
            <value>
                <fullName>V80</fullName>
            </value>
            <value>
                <fullName>V21</fullName>
            </value>
            <value>
                <fullName>V65</fullName>
            </value>
            <value>
                <fullName>V72</fullName>
            </value>
            <value>
                <fullName>V54</fullName>
            </value>
            <value>
                <fullName>V31</fullName>
            </value>
            <value>
                <fullName>V32</fullName>
            </value>
            <value>
                <fullName>V13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PurchasedProductControllerLC.cls
public class PurchasedProductControllerLC {

    @AuraEnabled
    public static PagedResult getPurchasedProductList(Id accountId, Decimal pageSize, Decimal pageNumber) {

        Integer pSize = (Integer)pageSize;
        Integer offset = ((Integer)pageNumber - 1) * pSize;

        PagedResult r =  new PagedResult();
        r.pageSize = pSize;
        r.page = (Integer) pageNumber;

        r.total = [SELECT count() FROM PPR_PurchProduct__c WHERE Client__c = :accountId]; 
		r.purchasedProductList = [SELECT id, PurchasedDate__c, Name, SKU__c, ProductLine__c, Quantity__c, Amount__c, CurrencyCode__c, PurchaseCountry__c, Store__c, Image_Url__c 
                                  FROM PPR_PurchProduct__c WHERE Client__c = :accountId 
                                  ORDER BY PurchasedDate__c DESC
                                  LIMIT :pSize OFFSET :offset];
    
    	return r;
    }

    public class PagedResult {
        
        @AuraEnabled
        public Integer pageSize { get;set; }
        
        @AuraEnabled
        public Integer page { get;set; }
        
        @AuraEnabled
        public Integer total { get;set; }
        
        @AuraEnabled
        public List<PPR_PurchProduct__c> purchasedProductList { get;set; }
        
    }

}