force-app/main/default/objects/Look__c/Look__c.object-meta.xml
<CustomObject>
    <label>Look</label>
    <nameField>
        <label>Look Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Looks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Look__c/fields/LayoutId__c.field-meta.xml
<CustomField>
    <fullName>LayoutId__c</fullName>
    <label>LayoutId</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Look__c/fields/Locale__c.field-meta.xml
<CustomField>
    <fullName>Locale__c</fullName>
    <label>Locale</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Look__c/fields/MasterSKU__c.field-meta.xml
<CustomField>
    <fullName>MasterSKU__c</fullName>
    <label>MasterSKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Look__c/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <label>Picture URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Look__c/fields/Picture_URL_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL_Mobile__c</fullName>
    <label>Picture URL Mobile</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Look__c/fields/SKUs__c.field-meta.xml
<CustomField>
    <fullName>SKUs__c</fullName>
    <label>SKUs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Look__c/fields/TECH_LV_DISPATCH_COUNTRY__c.field-meta.xml
<CustomField>
    <fullName>TECH_LV_DISPATCH_COUNTRY__c</fullName>
    <label>TECH LV DISPATCH COUNTRY</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Look__c/fields/TECH_LV_LOCALE__c.field-meta.xml
<CustomField>
    <fullName>TECH_LV_LOCALE__c</fullName>
    <defaultValue>&apos;eng-e1&apos;</defaultValue>
    <label>TECH_LV_LOCALE</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Look__c/fields/TECH_LV_PAGE_NAME__c.field-meta.xml
<CustomField>
    <fullName>TECH_LV_PAGE_NAME__c</fullName>
    <defaultValue>&apos;recommendations&apos;</defaultValue>
    <label>TECH LV PAGE NAME</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCatalogue__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <description>SKU code</description>
    <externalId>true</externalId>
    <label>SKU</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/fields/Tech_Wardrobing_ImageUrl__c.field-meta.xml
<CustomField>
    <fullName>Tech_Wardrobing_ImageUrl__c</fullName>
    <formula>IF(Contains( LOWER (Image1Url__c) , &quot;front&quot;), Image1Url__c, 
IF(Contains( LOWER (Image2Url__c) , &quot;front&quot;), Image2Url__c, 
IF(Contains( LOWER (Image3Url__c) , &quot;front&quot;), Image3Url__c, 
IF(Contains( LOWER (Image4Url__c) , &quot;front&quot;), Image4Url__c, 
IF(Contains( LOWER (Image5Url__c) , &quot;front&quot;), Image5Url__c,
&quot;&quot;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tech_Wardrobing_ImageUrl</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WRDB_Layout__mdt/WRDB_Layout__mdt.object-meta.xml
<CustomObject>
    <label>WRDB Layout</label>
    <pluralLabel>WRDB Layouts</pluralLabel>
</CustomObject>

force-app/main/default/objects/WRDB_Layout__mdt/fields/Image_Path__c.field-meta.xml
<CustomField>
    <fullName>Image_Path__c</fullName>
    <label>Image Path</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WRDB_Layout__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WRDB_Layout__mdt/fields/Number_of_Items__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Items__c</fullName>
    <label>Number of Items</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WRDB_Layout__mdt/fields/Variation__c.field-meta.xml
<CustomField>
    <fullName>Variation__c</fullName>
    <label>Variation</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WRDB_Locale__mdt/WRDB_Locale__mdt.object-meta.xml
<CustomObject>
    <label>WRDB Locale</label>
    <pluralLabel>WRDB Locale</pluralLabel>
</CustomObject>

force-app/main/default/objects/WRDB_Locale__mdt/fields/DispatchCountry__c.field-meta.xml
<CustomField>
    <fullName>DispatchCountry__c</fullName>
    <label>DispatchCountry</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WRDB_Locale__mdt/fields/LV_COM_Locale__c.field-meta.xml
<CustomField>
    <fullName>LV_COM_Locale__c</fullName>
    <label>LV.COM Locale</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WRDB_Locale__mdt/fields/Page_Name__c.field-meta.xml
<CustomField>
    <fullName>Page_Name__c</fullName>
    <label>Page Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LookTriggerHandler.cls
public with sharing class LookTriggerHandler {
       // avoid the recursion https://help.salesforce.com/articleView?id=000133752
	private static boolean run = true;

    //===================================================//
    // Here go the handler methods
    public static boolean runOnce() {
        System.debug('runOnce=' + run);
        if (run) {
            run = false;
            return true;
        } else {
            return run;
        }
    }

    public static Map<String, WRDB_Locale__mdt> getLocalesMap(){
        List<WRDB_Locale__mdt> localeSettings = [SELECT LV_COM_Locale__c, DeveloperName, Page_Name__c,DispatchCountry__c FROM WRDB_Locale__mdt];
        Map<String, WRDB_Locale__mdt> localesMap = new  Map<String, WRDB_Locale__mdt>();
        for (WRDB_Locale__mdt localeSetting : localeSettings){
            localesMap.put(localeSetting.DeveloperName, localeSetting);
        }
        return localesMap;
    }

    public static void beforeInsert(List<Look__c> newLookList, Map<id, Look__c> newLookMap) {
        Map<String, WRDB_Locale__mdt> localesMap = getLocalesMap();
        Long refDateTime = DateTime.now().getTime();
         for(Look__c lookRecord : newLookList){
            lookRecord.TECH_LV_LOCALE__c = localesMap.get(lookRecord.Locale__c) != null ? localesMap.get(lookRecord.Locale__c).LV_COM_Locale__c : localesMap.get('en_E1').LV_COM_Locale__c;
            lookRecord.TECH_LV_PAGE_NAME__c = localesMap.get(lookRecord.Locale__c) != null ? localesMap.get(lookRecord.Locale__c).Page_Name__c : localesMap.get('en_E1').Page_Name__c;
            lookRecord.TECH_LV_DISPATCH_COUNTRY__c = localesMap.get(lookRecord.Locale__c) != null ? localesMap.get(lookRecord.Locale__c).DispatchCountry__c : null;
            Integer skusCount = lookRecord.SKUs__c.split(';').size();
            lookRecord.layoutId__c = String.isEmpty(lookRecord.LayoutId__c) ?  skusCount + '_0' : lookRecord.layoutId__c;

            lookRecord.Reference_Id__c = String.isEmpty(lookRecord.Reference_Id__c)  ?
            lookRecord.OwnerId + lookRecord.skus__c + refDateTime :
            lookRecord.Reference_Id__c;
         }
    }

    public static void beforeUpdate(List<Look__c> newLookList, Map<id, Look__c> newLookMap,
        List<Look__c> oldLookList, Map<id, Look__c> oldLookMap) {
        List<Look__c> toSetPicture = new List<Look__c>();
        Map<String, WRDB_Locale__mdt> localesMap = getLocalesMap();
        Long refDateTime = DateTime.now().getTime();
        for(Look__c lookRecord : newLookList){
            lookRecord.TECH_LV_LOCALE__c = localesMap.get(lookRecord.Locale__c) != null ? localesMap.get(lookRecord.Locale__c).LV_COM_Locale__c : localesMap.get('en_E1').LV_COM_Locale__c;
            lookRecord.TECH_LV_PAGE_NAME__c = localesMap.get(lookRecord.Locale__c) != null ? localesMap.get(lookRecord.Locale__c).Page_Name__c : localesMap.get('en_E1').Page_Name__c;
            lookRecord.TECH_LV_DISPATCH_COUNTRY__c = localesMap.get(lookRecord.Locale__c) != null ? localesMap.get(lookRecord.Locale__c).DispatchCountry__c : null;
            if(lookRecord.MasterSKU__c != oldLookMap.get(lookRecord.Id).MasterSKU__c ||
            lookRecord.SKUs__c != oldLookMap.get(lookRecord.Id).SKUs__c){
                Integer skusCount = lookRecord.SKUs__c.split(';').size();
                lookRecord.layoutId__c = String.isEmpty(lookRecord.LayoutId__c) ?  skusCount + '_0' : lookRecord.layoutId__c;
            }

            lookRecord.Reference_Id__c = String.isEmpty(lookRecord.Reference_Id__c)  ?
            lookRecord.OwnerId + lookRecord.skus__c + refDateTime :
            lookRecord.Reference_Id__c;
        }
    }
    
    public static void afterUpdate(List<Look__c> newLookList, Map<id, Look__c> newLookMap,
     List<Look__c> oldLookList, Map<id, Look__c> oldLookMap)
    {
        // if was executed during the same context / avoid recursion
        // if(runOnce()) {

        //     for(Look__c lookRecord : newLookList){}
        // }
    }

    public static void afterInsert(List<Look__c> newLookList, Map<id, Look__c> newLookMap) {

            // for(Look__c lookRecord : newLookList){
            // }
    }

    // static void setPictureUrl(List<Look__c> newLookList){
    //     Map<String, String> productsMap = new Map<String, String>();
    //     for(Look__c lookRecord : newLookList){
    //         for(String sku : lookRecord.SKUs__c.split(';')){
    //             productsMap.put(sku,'');
    //         }
    //     }

    //     List<ProductCatalogue__c> prList = [Select Id,sku__c, Tech_Wardrobing_ImageUrl__c from ProductCatalogue__c
    //      where Sku__c IN :productsMap.keySet()];
    //     for(ProductCatalogue__c prd : prList){
    //         if (prd.Tech_Wardrobing_ImageUrl__c != null){
    //             productsMap.put(prd.SKU__c, prd.Tech_Wardrobing_ImageUrl__c.substringBetween('louisvuitton--', '.jpg'));
    //         }
    //     }

    //     List<WRDB_Layout__mdt> layoutSettings = [Select Image_Path__c,DeveloperName, Number_of_Items__c, Variation__c 
    //     FROM WRDB_Layout__mdt WHERE Is_Active__c = TRUE ORDER BY Number_of_Items__c, Variation__c];

    //     Map<String, WRDB_Layout__mdt> layoutsMapSetting = new Map<String, WRDB_Layout__mdt>();

    //     for (WRDB_Layout__mdt layout : layoutSettings){
    //         layoutsMapSetting.put(layout.DeveloperName, layout);
    //     }

    //     system.debug(layoutsMapSetting);

    //     for(Look__c lookRecord : newLookList){
    //         List<String> fillers = new List<String>();
                
    //         for(String sku : lookRecord.SKUs__c.split(';')){
    //             if (productsMap.get(sku) != null){ fillers.add(productsMap.get(sku)); }
                    
    //         }
    //         lookRecord.layoutId__c = String.isEmpty(lookRecord.LayoutId__c) ?  fillers.size() + '_0' : lookRecord.layoutId__c;
    //         // String placeholderWeb = getPlaceholder(lookRecord.layoutId__c, layoutsMapSetting, 1200);
    //         // lookRecord.Picture_URL__c = String.format(placeholderWeb, fillers);

    //         // String placeholderMobile = getPlaceholder(lookRecord.layoutId__c, layoutsMapSetting, 300);
    //         // lookRecord.Picture_URL_Mobile__c = String.format(placeholderMobile, fillers);
    //     }
    // }

    // static String getPlaceholder(String layoutId, Map<String, WRDB_Layout__mdt> layoutsMapSetting, Integer size){
    //     String urlHost = 'https://mosaic-prp.louisvuitton.com/composition/';
    //     system.debug('X' + layoutId);
    //     String path = 
    //     layoutsMapSetting.get('X' + layoutId).Image_Path__c
    //     .replaceAll('\\{\\!size\\}',String.valueOf(size))
    //     .replaceAll('\\{\\!size/2\\}',String.valueOf(size/2))
    //     .replaceAll('\\{\\!size1/3\\}',String.valueOf(size/3))
    //     .replaceAll('\\{\\!size2/3\\}',String.valueOf(size*2/3));

    //     return urlHost + path;
    // }
    
}