force-app/main/default/objects/CareService__c/CareService__c.object-meta.xml
<CustomObject>
    <label>Care Service</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Care Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareService__c/fields/CA__c.field-meta.xml
<CustomField>
    <fullName>CA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Care_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Display_ToManagerOnly__c.field-meta.xml
<CustomField>
    <fullName>Display_ToManagerOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display To Manager Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Followup_Status__c.field-meta.xml
<CustomField>
    <fullName>Followup_Status__c</fullName>
    <label>Followup Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Is_Not_Repaired__c.field-meta.xml
<CustomField>
    <fullName>Is_Not_Repaired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Not Repaired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/IsToDo__c.field-meta.xml
<CustomField>
    <fullName>IsToDo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is To Do</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Last_FollowUpStatus_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_FollowUpStatus_Changed_Date__c</fullName>
    <label>Last FollowUpStatus Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Last_MyRepair_Status_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_MyRepair_Status_Changed_Date__c</fullName>
    <label>Last MyRepair Status Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/MessageToCA__c.field-meta.xml
<CustomField>
    <fullName>MessageToCA__c</fullName>
    <label>Message To CA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quotation to validate</fullName>
            </value>
            <value>
                <fullName>EXTRA DELAY</fullName>
            </value>
            <value>
                <fullName>Product ready in store (7 days)</fullName>
            </value>
            <value>
                <fullName>Product ready in store (28 days)</fullName>
                <label>Product ready in store (1 month)</label>
            </value>
            <value>
                <fullName>Product ready in store (3 months)</fullName>
            </value>
            <value>
                <fullName>Product available in store</fullName>
            </value>
            <value>
                <fullName>Shipped to store but NOT REPAIRED</fullName>
            </value>
            <value>
                <fullName>Shipped to store but NOT REPAIRED</fullName>
                <isActive>false</isActive>
                <label>Shipped to store but NOT REPAIRED</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/MyRepair_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>MyRepair_CreatedDate__c</fullName>
    <label>MyRepair Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/MyRepairStatus__c.field-meta.xml
<CustomField>
    <fullName>MyRepairStatus__c</fullName>
    <label>My Repair Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>createdInStore</fullName>
                <label>Created in store</label>
            </value>
            <value>
                <fullName>pendingQualityExpertise</fullName>
                <label>Pending quality expertise</label>
            </value>
            <value>
                <fullName>shippedToRepairCenter</fullName>
                <label>Shipped to repair center</label>
            </value>
            <value>
                <fullName>shippedToLocalPartner</fullName>
                <label>Shipped to Local Partner</label>
            </value>
            <value>
                <fullName>orderPendingValidation</fullName>
                <label>Order pending validation</label>
            </value>
            <value>
                <fullName>waitingForClientDecision</fullName>
                <label>Waiting for client decision</label>
            </value>
            <value>
                <fullName>orderAccepted</fullName>
                <label>Order accepted</label>
            </value>
            <value>
                <fullName>orderRejected</fullName>
                <label>Order rejected</label>
            </value>
            <value>
                <fullName>waitingForSpareParts</fullName>
                <label>Waiting for spare parts</label>
            </value>
            <value>
                <fullName>repairInProgress</fullName>
                <label>Repair in progress</label>
            </value>
            <value>
                <fullName>shippedToStore</fullName>
                <label>Repair finalized</label>
            </value>
            <value>
                <fullName>clientContacted</fullName>
                <label>Client contacted</label>
            </value>
            <value>
                <fullName>paymentConfirmed</fullName>
                <label>Payment confirmed</label>
            </value>
            <value>
                <fullName>productDeliveredToClient</fullName>
                <label>Product delivered to client</label>
            </value>
            <value>
                <fullName>servicePerformed</fullName>
                <label>Service performed</label>
            </value>
            <value>
                <fullName>expertisePerformedInRepairCenter</fullName>
                <label>Expertise performed in repair center</label>
            </value>
            <value>
                <fullName>receivedAndAcceptedInStore</fullName>
                <label>Received and accepted in store</label>
            </value>
            <value>
                <fullName>receivedAndNotAcceptedInStore</fullName>
                <label>Received and not accepted in store</label>
            </value>
            <value>
                <fullName>productStocked</fullName>
                <label>Product stocked</label>
            </value>
            <value>
                <fullName>sentToRMS</fullName>
                <label>Sent to RMS</label>
            </value>
            <value>
                <fullName>cancelled</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>initial</fullName>
                <label>Initial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/NS_Code__c.field-meta.xml
<CustomField>
    <fullName>NS_Code__c</fullName>
    <inlineHelpText>Reason of non-reparability</inlineHelpText>
    <label>NS Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Red_Code__c.field-meta.xml
<CustomField>
    <fullName>Red_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Red Code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Care Services</relationshipLabel>
    <relationshipName>Care_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Yellow_Code__c.field-meta.xml
<CustomField>
    <fullName>Yellow_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Yellow Code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareServiceFlow__mdt/CareServiceFlow__mdt.object-meta.xml
<CustomObject>
    <label>CareServiceFlow</label>
    <pluralLabel>CareServicesFlow</pluralLabel>
</CustomObject>

force-app/main/default/objects/CareServiceFlow__mdt/fields/DaysInStatus__c.field-meta.xml
<CustomField>
    <fullName>DaysInStatus__c</fullName>
    <label>Days In Status</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CareServiceFlow__mdt/fields/ForManagerOnly__c.field-meta.xml
<CustomField>
    <fullName>ForManagerOnly__c</fullName>
    <defaultValue>false</defaultValue>
    <label>For Manager Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareServiceFlow__mdt/fields/MessageToCA__c.field-meta.xml
<CustomField>
    <fullName>MessageToCA__c</fullName>
    <label>Message To CA</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CareServiceFlow__mdt/fields/MyRepairStatus__c.field-meta.xml
<CustomField>
    <fullName>MyRepairStatus__c</fullName>
    <label>My Repair Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareServiceFlow__mdt/fields/To_do__c.field-meta.xml
<CustomField>
    <fullName>To_do__c</fullName>
    <defaultValue>false</defaultValue>
    <label>To do</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/classes/IM_BatchCareServiceStatusFlow.cls
/**
    Description: Batch to update status on careservice__c
    Created for:  ICON project
    Create date: 26/07/2018
*/

global class IM_BatchCareServiceStatusFlow implements Database.Batchable<sObject>{
      
    public String query;
    

    List<CareServiceFlow__mdt> statusSettings = new List<CareServiceFlow__mdt>();
    Map<String, List<CareServiceFlow__mdt>> statusSettingsMap = new Map<String, List<CareServiceFlow__mdt>>();
    List<String> statusList = new List<String>();
    List<CareService__c> careToUpdate = new List<CareService__c>();
    
    global IM_BatchCareServiceStatusFlow(){

        statusSettings = [Select Id,DaysInStatus__c,ForManagerOnly__c,MyRepairStatus__c, To_do__c,MessageToCA__c FROM CareServiceFlow__mdt Order By DaysInStatus__c DESC];
        String statusConditions = '';
        for( CareServiceFlow__mdt statusSet : statusSettings){
            if(statusSettingsMap.get(statusSet.MyRepairStatus__c) == null){
                statusSettingsMap.put(statusSet.MyRepairStatus__c, new List<CareServiceFlow__mdt>());
            }
            statusSettingsMap.get(statusSet.MyRepairStatus__c).add(statusSet);

            if(statusConditions != ''){
                statusConditions += ' OR ';
            }
            String LimitDate = DateTime.now().addDays(-statusSet.DaysInStatus__c.intValue()).format('YYYY-MM-dd');
            statusConditions += ' ( MyRepairStatus__c = \'' + statusSet.MyRepairStatus__c + '\' AND Last_MyRepair_Status_Changed_Date__c =' + LimitDate + ' ) ';
        }

        statusList.addAll(statusSettingsMap.keySet());
       // statusList.addAll(new list<string>{'orderPendingValidation', 'waitingForClientDecision'});
        String LimitDate = DateTime.now().addDays(-7).format('YYYY-MM-dd');
        query = ' SELECT Id, MyRepairStatus__c, MyRepair_CreatedDate__c, MessageToCA__c,Is_Not_Repaired__c, IsToDo__c, Last_FollowUpStatus_Changed_Date__c,NS_Code__c, '+
        ' Yellow_Code__c, Red_Code__c, LastModifiedDate, CreatedDate, Followup_Status__c, ExternalId__c, Display_ToManagerOnly__c, CA__c, Store__c,Last_MyRepair_Status_Changed_Date__c ' +
        ' FROM  CareService__c Where MyRepair_CreatedDate__c = LAST_N_DAYS:365 AND ('+ statusConditions + ' OR (Followup_Status__c = \'Closed\' AND  Last_FollowUpStatus_Changed_Date__c = ' + LimitDate + ' ) '+
        ' OR (MyRepairStatus__c = \'shippedToStore\' AND Is_Not_Repaired__c = true)' +
        ' OR (MyRepairStatus__c NOT IN : statusList AND IsToDo__c = true))' ;
     }
        
    global database.querylocator start(Database.BatchableContext CD){
        System.debug('#### START - IM_BatchCareServiceStatusFlow');
        System.debug('#### query : ' + query);
        return Database.getQueryLocator(query);   
    } 
    
    global void execute(Database.BatchableContext CD, List<sObject> scope){
        try{
            if(scope.size() > 0){
                this.setStatus((List<CareService__c>) scope);
            }
            
        }catch (DmlException e){
            // Process exception here
            System.debug('#### '+e.getTypeName()+' Exception:'+e.getMessage()+' '+e.getStackTraceString());
        }       
    }
    
    global void finish(Database.BatchableContext CD){
        Datetime sysTime = System.now();

       // this would increase the time to 1 hour after current time
        sysTime = sysTime.addHours(1);

        String chron_exp = '' + sysTime.second() + ' ' + sysTime.minute() + ' ' + sysTime.hour() + ' ' + sysTime.day() + ' ' + sysTime.month() + ' ? ' + sysTime.year();
		String strJobName = 'CareServiceJOB-' + sysTime.getTime();
		System.schedule(strJobName, chron_exp, new IM_SchedulerCareServiceStatusFlow());
    }

    private void setStatus( List<CareService__c> careList ) {
        for( CareService__c care : careList ){
            List<CareServiceFlow__mdt>  statusSets =  statusSettingsMap.get(care.MyRepairStatus__c);
            Boolean closedToday = care.Followup_Status__c == 'Closed' && care.Last_FollowUpStatus_Changed_Date__c != null && care.Last_FollowUpStatus_Changed_Date__c == system.today();
            if( statusSets != null ){               
                Boolean toBeUpdated = false;
                for( CareServiceFlow__mdt statusSet : statusSets ){
                    if( care.Last_MyRepair_Status_Changed_Date__c != null &&  system.today().daysBetween(care.Last_MyRepair_Status_Changed_Date__c) == -statusSet.DaysInStatus__c && !toBeUpdated &&  !closedToday ){                  
                        care.IsToDo__c = care.IsToDo__c == true ? true : statusSet.To_do__c ;
                        care.Display_ToManagerOnly__c =  statusSet.ForManagerOnly__c; 
                        care.MessageToCA__c = String.isNotEmpty(statusSet.MessageToCA__c)  ? statusSet.MessageToCA__c : care.MessageToCA__c;
                        care.Followup_Status__c = care.Followup_Status__c != 'Closed' && care.Followup_Status__c!= null ? care.Followup_Status__c : 'New';
                        toBeUpdated = true;
                    } else if ( care.Last_FollowUpStatus_Changed_Date__c != null && system.today().daysBetween(care.Last_FollowUpStatus_Changed_Date__c) == - 7 && care.Followup_Status__c == 'Closed' && toBeUpdated == false){
                        care.IsToDo__c = false ;
                        care.Display_ToManagerOnly__c =  false; 
                        care.MessageToCA__c = null;
                        toBeUpdated = true;
                    } 
                }  
                if (toBeUpdated == true){
                    careToUpdate.add(care);
                }
            } else if (care.IsToDo__c == true){
                care.IsToDo__c = false ;
                care.Display_ToManagerOnly__c =  false; 
                care.MessageToCA__c = null;
                careToUpdate.add(care);
            }

            if(care.MyRepairStatus__c == 'shippedToStore' && care.Is_Not_Repaired__c == true){
                care.IsToDo__c = true;
                care.MessageToCA__c = 'Shipped to store but NOT REPAIRED';
                system.debug('Shipped to store but NOT REPAIRED' + care.Id);
                 careToUpdate.add(care);
            }
        }

        if (careToUpdate.size() > 0){
            update careToUpdate;
        }
    }
    
}