force-app/main/default/objects/CareService__c/CareService__c.object-meta.xml
<CustomObject>
    <label>Care Service</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Care Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareService__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Services</relationshipLabel>
    <relationshipName>Care_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Confirm_Address_Send_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Address_Send_Date__c</fullName>
    <label>Confirm Address Send Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Current_Status_Age__c.field-meta.xml
<CustomField>
    <fullName>Current_Status_Age__c</fullName>
    <formula>TODAY()- Last_ICONiCS_Status_Changed_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Status Age (days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/ICONiCS_Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>ICONiCS_Status_Detail__c</fullName>
    <defaultValue>&quot;New Request&quot;</defaultValue>
    <label>ICONiCS Detail Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Request</fullName>
                <default>true</default>
                <label>New Request</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Pending Customer information</fullName>
            </value>
            <value>
                <fullName>Initiated in MyRepairs as a Draft</fullName>
            </value>
            <value>
                <fullName>Created in MyRepairs</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Preliminary Quote Pending Validation</fullName>
            </value>
            <value>
                <fullName>Preliminary Quote Validated</fullName>
            </value>
            <value>
                <fullName>Preliminary Quote Declined</fullName>
            </value>
            <value>
                <fullName>Spare parts order preparation</fullName>
            </value>
            <value>
                <fullName>Shipped to Repair Center</fullName>
            </value>
            <value>
                <fullName>Received in Repair Center</fullName>
            </value>
            <value>
                <fullName>Order pending validation</fullName>
            </value>
            <value>
                <fullName>Order rejected</fullName>
            </value>
            <value>
                <fullName>Order accepted</fullName>
            </value>
            <value>
                <fullName>Waiting for Spare parts</fullName>
            </value>
            <value>
                <fullName>Repair in progress</fullName>
            </value>
            <value>
                <fullName>Repair finalized</fullName>
            </value>
            <value>
                <fullName>Confirm Address</fullName>
            </value>
            <value>
                <fullName>Waiting for Payment</fullName>
            </value>
            <value>
                <fullName>Payment Confirmed</fullName>
            </value>
            <value>
                <fullName>Shipped to Client</fullName>
            </value>
            <value>
                <fullName>Received In E-Hub</fullName>
            </value>
            <value>
                <fullName>Delivered to Client</fullName>
            </value>
            <value>
                <fullName>Product stocked</fullName>
            </value>
            <value>
                <fullName>Payment Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Review</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Shipped from E-Hub</fullName>
            </value>
            <value>
                <fullName>Payment Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Last_ICONiCS_Status_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_ICONiCS_Status_Changed_Date__c</fullName>
    <description>Last Change Date of INCONiCS status detail</description>
    <label>Last ICONiCS Status Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/PBL_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>PBL_Created_Date__c</fullName>
    <label>PBL Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Quotation_sent_date__c.field-meta.xml
<CustomField>
    <fullName>Quotation_sent_date__c</fullName>
    <label>Quotation sent date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Line_1__c</fullName>
    <label>Shipping Address Line 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <defaultValue>&quot;US&quot;</defaultValue>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_Label_creation_date__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Label_creation_date__c</fullName>
    <label>Shipping Label creation date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Care Services</relationshipLabel>
    <relationshipName>Care_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/StoreRetailCode__c.field-meta.xml
<CustomField>
    <fullName>StoreRetailCode__c</fullName>
    <label>StoreRetailCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <externalId>true</externalId>
    <label>Repair Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CareService__c/recordTypes/DistantCareService.recordType-meta.xml
<RecordType>
    <fullName>DistantCareService</fullName>
    <active>true</active>
    <label>Distant Care Service</label>
</RecordType>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-dcs/main/default/classes/ICX_BatchDCSAutoChangeStatus_TEST.cls
/**
* @author Keman WU
* @date Creation 09/12/2021
* @Test class
* @description test class for batch auto cancellation for distant care service
*/
@isTest 
public with sharing class ICX_BatchDCSAutoChangeStatus_TEST {
    @isTest static void testCancel() {
        Id DistantCareRTId = Schema.SObjectType.CareService__c.getRecordTypeInfosByDeveloperName().get('DistantCareService').getRecordTypeId();      
		
        Store__c store= new Store__c(RetailStoreId__c = 'UE4');
		insert store;
      
        Account acc = ICX_TestFactory.createAccount();
        insert acc;

        CareService__c dcs1 = new CareService__c(recordTypeId = DistantCareRTId, Client__c =acc.Id, StoreRetailCode__c = 'UE4', Store__c = store.Id,TransactionId__c='o123456789');
        CareService__c dcs2 = new CareService__c(recordTypeId = DistantCareRTId,Shipping_Address_Line_1__c='test',Shipping_City__c='test',Shipping_Country__c='US',Shipping_State_Province__c='NY',Shipping_Zip_Postal_Code__c='10001',Client__c =acc.Id, StoreRetailCode__c = 'UE4', Store__c = store.Id); 
       
        insert dcs1;
        insert dcs2;
        Test.startTest();
        dcs1.ICONiCS_Status_Detail__c = 'Preliminary Quote Pending Validation';
        dcs1.Quotation_sent_date__c  = system.today() - 30;
        update dcs1;
        dcs2.ICONiCS_Status_Detail__c = 'Preliminary Quote Validated';
        dcs2.Shipping_Label_creation_date__c  = system.today() - 110;
        update dcs2;
        ICX_BatchDCSAutoChangeStatus batch = new ICX_BatchDCSAutoChangeStatus();
        Database.executeBatch(batch,100);
        Test.stopTest();
        CareService__c csToCancel = [select Current_Status_Age__c,ICONiCS_Status_Detail__c from CareService__c where id=: dcs1.Id];
        system.debug('Current_Status_Age__c csToCancel ' +csToCancel.Current_Status_Age__c);
        system.assertEquals('Cancelled', csToCancel.ICONiCS_Status_Detail__c);
        CareService__c cs = [select Current_Status_Age__c,ICONiCS_Status_Detail__c from CareService__c where id=: dcs2.Id];
        system.debug('Current_Status_Age__c cs ' +cs.Current_Status_Age__c);
        system.assertEquals( 'Cancelled', cs.ICONiCS_Status_Detail__c);
    }
    @isTest static void testConfirmAddress() {
        Id DistantCareRTId = Schema.SObjectType.CareService__c.getRecordTypeInfosByDeveloperName().get('DistantCareService').getRecordTypeId();      
		
        Store__c store= new Store__c(RetailStoreId__c = 'UE4');
		insert store;
      
        Account acc = ICX_TestFactory.createAccount();
        insert acc;

        CareService__c dcs1 = new CareService__c(recordTypeId = DistantCareRTId, Client__c =acc.Id, StoreRetailCode__c = 'UE4', Store__c = store.Id,TransactionId__c='o123456789');
        
        insert dcs1;
       
        Test.startTest();
        dcs1.ICONiCS_Status_Detail__c = 'Confirm Address';
        dcs1.Confirm_Address_Send_Date__c  = system.today() - 3;
        update dcs1;
       
        ICX_BatchDCSAutoChangeStatus batch = new ICX_BatchDCSAutoChangeStatus();
        Database.executeBatch(batch,100);
        Test.stopTest();
        CareService__c csToChange = [select ICONiCS_Status_Detail__c from CareService__c where id=: dcs1.Id];
         system.assertEquals('Payment Received', csToChange.ICONiCS_Status_Detail__c);
        
    }
    @isTest static void testWaitingPayment() {
        Id DistantCareRTId = Schema.SObjectType.CareService__c.getRecordTypeInfosByDeveloperName().get('DistantCareService').getRecordTypeId();      
		
        Store__c store= new Store__c(RetailStoreId__c = 'UE4');
		insert store;
      
        Account acc = ICX_TestFactory.createAccount();
        insert acc;

        CareService__c dcs1 = new CareService__c(recordTypeId = DistantCareRTId, Client__c =acc.Id, StoreRetailCode__c = 'UE4', Store__c = store.Id,TransactionId__c='o123456789',Shipping_Address_Line_1__c='test',Shipping_City__c='New York',Shipping_Country__c='US',Shipping_State_Province__c='NY',Shipping_Zip_Postal_Code__c='10002');
        
        insert dcs1;
       
        Test.startTest();
        dcs1.ICONiCS_Status_Detail__c = 'Waiting for Payment';
        dcs1.Last_ICONiCS_Status_Changed_Date__c  = system.today() - 91;
        update dcs1;
       
        ICX_BatchDCSAutoChangeStatus batch = new ICX_BatchDCSAutoChangeStatus();
        Database.executeBatch(batch,100);
        Test.stopTest();
        CareService__c csToChange = [select ICONiCS_Status_Detail__c from CareService__c where id=: dcs1.Id];
         system.assertEquals('Payment Review', csToChange.ICONiCS_Status_Detail__c);
        
    }
    @isTest static void testPaymentInitiated() {
        Id DistantCareRTId = Schema.SObjectType.CareService__c.getRecordTypeInfosByDeveloperName().get('DistantCareService').getRecordTypeId();      
		
        Store__c store= new Store__c(RetailStoreId__c = 'UE4');
		insert store;
      
        Account acc = ICX_TestFactory.createAccount();
        insert acc;

        CareService__c dcs1 = new CareService__c(recordTypeId = DistantCareRTId, Client__c =acc.Id, StoreRetailCode__c = 'UE4', Store__c = store.Id,TransactionId__c='o123456789',Shipping_Address_Line_1__c='test',Shipping_City__c='New York',Shipping_Country__c='US',Shipping_State_Province__c='NY',Shipping_Zip_Postal_Code__c='10002');
        
        insert dcs1;
       
        Test.startTest();
        dcs1.ICONiCS_Status_Detail__c = 'Payment Initiated';
        dcs1.PBL_Created_Date__c  = system.today() - 91;
        update dcs1;
       
        ICX_BatchDCSAutoChangeStatus batch = new ICX_BatchDCSAutoChangeStatus();
        Database.executeBatch(batch,100);
        Test.stopTest();
        CareService__c csToChange = [select ICONiCS_Status_Detail__c from CareService__c where id=: dcs1.Id];
         system.assertEquals('Payment Review', csToChange.ICONiCS_Status_Detail__c);
        
    }
}