force-app/main/default/objects/CareService__c/CareService__c.object-meta.xml
<CustomObject>
    <label>Care Service</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Care Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareService__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Services</relationshipLabel>
    <relationshipName>Care_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/FollowupBy_Chat__c.field-meta.xml
<CustomField>
    <fullName>FollowupBy_Chat__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Followup By SMS/ChatApps</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/FollowupBy_Email__c.field-meta.xml
<CustomField>
    <fullName>FollowupBy_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Followup By Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/IsToDo__c.field-meta.xml
<CustomField>
    <fullName>IsToDo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is To Do</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Last_MyRepair_Status_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_MyRepair_Status_Changed_Date__c</fullName>
    <label>Last MyRepair Status Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/MYLV_Care_Status__c.field-meta.xml
<CustomField>
    <fullName>MYLV_Care_Status__c</fullName>
    <inlineHelpText>Client Status in LV APP</inlineHelpText>
    <label>MYLV Care Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>dropped_in_store</fullName>
                <label>Dropped in Store</label>
            </value>
            <value>
                <fullName>routing_to_workshop</fullName>
                <label>Routing to Workshop</label>
            </value>
            <value>
                <fullName>Expertise</fullName>
            </value>
            <value>
                <fullName>Restoration</fullName>
            </value>
            <value>
                <fullName>ready_for_pick_up</fullName>
                <label>Ready for pick-up in store</label>
            </value>
            <value>
                <fullName>restoration_not_performed</fullName>
                <label>Restoration not performed</label>
            </value>
            <value>
                <fullName>home_delivery</fullName>
                <label>Home delivery</label>
            </value>
            <value>
                <fullName>dropped_in_store_s</fullName>
                <label>Dropped in Store s</label>
            </value>
            <value>
                <fullName>ready_for_pick_up_s</fullName>
                <label>Ready for Pickup s</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>request_submitted</fullName>
                <label>Request submitted</label>
            </value>
            <value>
                <fullName>preliminary_assessment</fullName>
                <label>Preliminary assessment</label>
            </value>
            <value>
                <fullName>shipping_to_atelier</fullName>
                <label>Shipping to atelier</label>
            </value>
            <value>
                <fullName>received_at_atelier</fullName>
                <label>Received at the atelier</label>
            </value>
            <value>
                <fullName>under_assessment</fullName>
                <label>Under assessment</label>
            </value>
            <value>
                <fullName>repair_in_progress</fullName>
                <label>Repair in progress</label>
            </value>
            <value>
                <fullName>awaiting_payment</fullName>
                <label>Awaiting payment</label>
            </value>
            <value>
                <fullName>payment_confirmed</fullName>
                <label>Payment confirmed</label>
            </value>
            <value>
                <fullName>shipping</fullName>
                <label>Shipping</label>
            </value>
            <value>
                <fullName>delivered_to_client</fullName>
                <label>Delivered to client</label>
            </value>
            <value>
                <fullName>preliminary_assessment_acc</fullName>
                <label>Preliminary assessment accepted</label>
            </value>
            <value>
                <fullName>preliminary_assessment_dec</fullName>
                <label>Preliminary assessment declined</label>
            </value>
            <value>
                <fullName>final_assessment_acc</fullName>
                <label>Final assessment accepted</label>
            </value>
            <value>
                <fullName>final_assessment_dec</fullName>
                <label>Final assessment declined</label>
            </value>
            <value>
                <fullName>cancelled</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>payment_initiated</fullName>
                <label>Payment initiated</label>
            </value>
            <value>
                <fullName>payment_contact</fullName>
                <label>Payment contact</label>
            </value>
            <value>
                <fullName>confirm_address</fullName>
                <label>Confirm address</label>
            </value>
            <value>
                <fullName>shipping_in_preparation</fullName>
                <label>Shipping in preparation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/MyRepair_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>MyRepair_CreatedDate__c</fullName>
    <label>MyRepair Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Line_1__c</fullName>
    <label>Shipping Address Line 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <defaultValue>&quot;US&quot;</defaultValue>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <defaultValue>&quot;M99999&quot;</defaultValue>
    <label>SKU</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/StoreRetailCode__c.field-meta.xml
<CustomField>
    <fullName>StoreRetailCode__c</fullName>
    <label>StoreRetailCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <externalId>true</externalId>
    <label>Repair Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CareService__c/recordTypes/DistantCareService.recordType-meta.xml
<RecordType>
    <fullName>DistantCareService</fullName>
    <active>true</active>
    <label>Distant Care Service</label>
</RecordType>

force-app/main/default/classes/WS_PaymentStatusNotification_TEST.cls
/*	 * @author Keman WU
* @date creation 28/07/2023
* @description test class for WS_PaymentStatusNotification
*/
@isTest 
public with sharing class WS_PaymentStatusNotification_TEST {
    
    static testMethod void succesTest() {
        Id DistantCareRTId = Schema.SObjectType.CareService__c.getRecordTypeInfosByDeveloperName().get('DistantCareService').getRecordTypeId(); 
             
         Account acc = ICX_TestFactory.createAccount();
         insert acc;       
         CareService__c dcs1 = new CareService__c(recordTypeId = DistantCareRTId,MYLV_Care_Status__c = 'preliminary_assessment_acc',Shipping_Address_Line_1__c='test',Shipping_City__c='test',Shipping_Country__c='US',Shipping_State_Province__c='NY',Shipping_Zip_Postal_Code__c='10001',TransactionId__c ='o12345678', Client__c =acc.Id, StoreRetailCode__c = 'F92', IsToDo__c=false,Product_Family__c='test family',SKU__c='M9999',MyRepair_CreatedDate__c = system.today(),Last_MyRepair_Status_Changed_Date__c = system.today(),FollowupBy_Email__c=true,FollowupBy_Chat__c=true);
         insert dcs1;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
       
        req.requestURI = '/IxopayPaymentStatus';
        req.httpMethod = 'POST';
        req.addHeader('Content-Type','application/json');
        String requestString = '{'+
		'"result": "OK",'+
		'"uuid": "524fea6f5ed864b06741",'+
		'"merchantTransactionId": "20230413155356",'+
		'"purchaseId": "20230525-524fea6f5ed864b06741",'+
		'"transactionType": "PREAUTHORIZE",'+
		'"paymentMethod": "Creditcard",'+
		'"amount": 9.99,'+
		'"currency": "EUR",'+
		'"merchantMetaData": "o12345678",'+
		'"customer": {'+
		'"identification": "00003001",'+
		'"firstName": "Max",'+
		'"lastName": "Mustermann",'+
		'"billingPhone": "0679258098",'+
		'"billingAddress1": "3 rue Bailleul",'+
		'"billingCity": "Paris",'+
		'"billingPostcode": "75001",'+
		'"billingState": "Ile-de-france",'+
		'"billingCountry": "FR",'+
		'"shippingFirstName": "Max",'+
		'"shippingLastName": "Mustermann",'+
		'"shippingAddress1": "3 rue Bailleul",'+
		'"shippingCity": "Paris",'+
		'"shippingPostcode": "75001",'+
		'"shippingState": "Ile-de-france",'+
		'"shippingCountry": "EN",'+
		'"email": "Max.Mustermann.ext@louisvuitton.com",'+
		'"ipAddress": "165.225.20.239"'+
		'},'+
		'"returnData": {'+
		'"_TYPE": "cardData",'+
		'"type": "visa",'+
		'"cardHolder": "marouen bachoual",'+
		'"expiryMonth": "05",'+
		'"expiryYear": "2023",'+
		'"binDigits": "41111111",'+
		'"firstSixDigits": "411111",'+
		'"lastFourDigits": "1111",'+
		'"fingerprint": "FNjYSZpHtQLgKuqvvOJ7+u+cmvgRets0jEwL1SZrgXXvPTPiPYlqb9oSy+ps7OB9HwLZYFx3SK05Zl5saVHMsA",'+
		'"threeDSecure": "OFF",'+
		'"eci": "05",'+
		'"binBrand": "VISA",'+
		'"binBank": "JPMORGAN CHASE BANK N.A.",'+
		'"binType": "",'+
		'"binLevel": "",'+
		'"binCountry": "US"'+
		'}'+
		'}';
        req.requestBody =  blob.valueOf(requestString);
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();       
        WS_PaymentStatusNotification.doPost();
        Test.stopTest();
    }
    
    static testMethod void ErrorTest1() {
        Id DistantCareRTId = Schema.SObjectType.CareService__c.getRecordTypeInfosByDeveloperName().get('DistantCareService').getRecordTypeId(); 
             
         Account acc = ICX_TestFactory.createAccount();
         insert acc;       
         CareService__c dcs1 = new CareService__c(recordTypeId = DistantCareRTId,MYLV_Care_Status__c = 'preliminary_assessment_acc',Shipping_Address_Line_1__c='test',Shipping_City__c='test',Shipping_Country__c='US',Shipping_State_Province__c='NY',Shipping_Zip_Postal_Code__c='10001',TransactionId__c ='o12345678', Client__c =acc.Id, StoreRetailCode__c = 'F92', IsToDo__c=false,Product_Family__c='test family',SKU__c='M9999',MyRepair_CreatedDate__c = system.today(),Last_MyRepair_Status_Changed_Date__c = system.today(),FollowupBy_Email__c=true,FollowupBy_Chat__c=true);
         insert dcs1;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
       
        req.requestURI = '/IxopayPaymentStatus';
        req.httpMethod = 'POST';
        req.addHeader('Content-Type','application/json');
        String requestString = '{'+
		'"result": "ERROR",'+
		'"uuid": "524fea6f5ed864b06741",'+
		'"merchantTransactionId": "20230413155356",'+
		'"purchaseId": "20230525-524fea6f5ed864b06741",'+
		'"transactionType": "PREAUTHORIZE",'+
		'"paymentMethod": "Creditcard",'+
		'"amount": 9.99,'+
		'"currency": "EUR",'+
		'"merchantMetaData": "o12345678",'+
		'"customer": {'+
		'"identification": "00003001",'+
		'"firstName": "Max",'+
		'"lastName": "Mustermann",'+
		'"billingPhone": "0679258098",'+
		'"billingAddress1": "3 rue Bailleul",'+
		'"billingCity": "Paris",'+
		'"billingPostcode": "75001",'+
		'"billingState": "Ile-de-france",'+
		'"billingCountry": "FR",'+
		'"shippingFirstName": "Max",'+
		'"shippingLastName": "Mustermann",'+
		'"shippingAddress1": "3 rue Bailleul",'+
		'"shippingCity": "Paris",'+
		'"shippingPostcode": "75001",'+
		'"shippingState": "Ile-de-france",'+
		'"shippingCountry": "EN",'+
		'"email": "Max.Mustermann.ext@louisvuitton.com",'+
		'"ipAddress": "165.225.20.239"'+
		'},'+
		'"returnData": {'+
		'"_TYPE": "cardData",'+
		'"type": "visa",'+
		'"cardHolder": "marouen bachoual",'+
		'"expiryMonth": "05",'+
		'"expiryYear": "2023",'+
		'"binDigits": "41111111",'+
		'"firstSixDigits": "411111",'+
		'"lastFourDigits": "1111",'+
		'"fingerprint": "FNjYSZpHtQLgKuqvvOJ7+u+cmvgRets0jEwL1SZrgXXvPTPiPYlqb9oSy+ps7OB9HwLZYFx3SK05Zl5saVHMsA",'+
		'"threeDSecure": "OFF",'+
		'"eci": "05",'+
		'"binBrand": "VISA",'+
		'"binBank": "JPMORGAN CHASE BANK N.A.",'+
		'"binType": "",'+
		'"binLevel": "",'+
		'"binCountry": "US"'+
		'}'+
		'}';
        req.requestBody =  blob.valueOf(requestString);
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();       
        WS_PaymentStatusNotification.doPost();
        Test.stopTest();
    }
    static testMethod void ErrorTest2() {
        Id DistantCareRTId = Schema.SObjectType.CareService__c.getRecordTypeInfosByDeveloperName().get('DistantCareService').getRecordTypeId(); 
             
         Account acc = ICX_TestFactory.createAccount();
         insert acc;       
         CareService__c dcs1 = new CareService__c(recordTypeId = DistantCareRTId,MYLV_Care_Status__c = 'preliminary_assessment_acc',Shipping_Address_Line_1__c='test',Shipping_City__c='test',Shipping_Country__c='US',Shipping_State_Province__c='NY',Shipping_Zip_Postal_Code__c='10001',TransactionId__c ='o12345678', Client__c =acc.Id, StoreRetailCode__c = 'F92', IsToDo__c=false,Product_Family__c='test family',SKU__c='M9999',MyRepair_CreatedDate__c = system.today(),Last_MyRepair_Status_Changed_Date__c = system.today(),FollowupBy_Email__c=true,FollowupBy_Chat__c=true);
         insert dcs1;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
       
        req.requestURI = '/IxopayPaymentStatus';
        req.httpMethod = 'POST';
        req.addHeader('Content-Type','application/json');
        String requestString = '{Hello}';
        req.requestBody =  blob.valueOf(requestString);
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();       
        WS_PaymentStatusNotification.doPost();
        Test.stopTest();
    }
}