force-app/main/default/objects/CareService__c/CareService__c.object-meta.xml
<CustomObject>
    <label>Care Service</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Care Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareService__c/fields/Has_Unread_Email__c.field-meta.xml
<CustomField>
    <fullName>Has_Unread_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Unread Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/My_Repairs__c.field-meta.xml
<CustomField>
    <fullName>My_Repairs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please be sure to fill this field otherwise the Operation Exception will not appear on the Distant Care Service</inlineHelpText>
    <label>Care Service</label>
    <referenceTo>CareService__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/TECH_NewEmailReceived__c.field-meta.xml
<CustomField>
    <fullName>TECH_NewEmailReceived__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Email Received</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EmailMessage/fields/Has_Files__c.field-meta.xml
<CustomField>
    <fullName>Has_Files__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Files</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ICX_Emails.cls
public with sharing class ICX_Emails  {
	
	// Function used also in ICX_IPDTransfer_CTL and ICX_Files

	@AuraEnabled
	public static List<EmailMessage> getEmails(Id recordId){
		string soql = 'Select Id, Subject, MessageDate, toLabel(Status), Has_Files__c,HasAttachment, Incoming From EmailMessage Where ';
        
        /*  Description: if on CareService record page, show emails related to the case which is linked to CareService
         * Modification: 08/07/2021 by Keman WU 
        */
         if (recordId.getSobjectType() == CareService__c.SobjectType)  
             soql+= 'parentId in (select id from case where My_Repairs__c=:recordId) ';
        else{
		soql += (recordId.getSobjectType() == Case.SobjectType)?'parentId':'relatedToId';
		soql+= '=:recordId ';
    }
        soql+= 'order by MessageDate Desc';
        system.debug(soql);
        List<EmailMessage> allEmails = Database.query(soql);
        List<String> lstStatus = new List<String>();
        if(allEmails.size()>0){            
        for(EmailMessage mail : [select Status from EmailMessage where id in:allEmails]){
            lstStatus.add(mail.Status);
        }
        if(!lstStatus.contains('0')){
        if(recordId.getSobjectType() == Case.SobjectType){
            //update case TECH_NewEmailReceived__c
             case currentCase = [select id,TECH_NewEmailReceived__c from case where id =:recordId ];
             currentCase.TECH_NewEmailReceived__c = false; 
             update currentCase;        
        }
        if(recordId.getSobjectType() == CareService__c.SobjectType){
            //update careService Has_Unread_Email__c
            CareService__c currentCareService = [select id,Has_Unread_Email__c from CareService__c where id =:recordId ];
            currentCareService.Has_Unread_Email__c = false;   
            update currentCareService;
        }     
            }
    }
		return Database.query(soql);
	}

}