force-app/main/default/objects/CareService__c/CareService__c.object-meta.xml
<CustomObject>
    <label>Care Service</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Care Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareService__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Services</relationshipLabel>
    <relationshipName>Care_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>Currency Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/ICONiCS_Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>ICONiCS_Status_Detail__c</fullName>
    <defaultValue>&quot;New Request&quot;</defaultValue>
    <label>ICONiCS Detail Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Request</fullName>
                <default>true</default>
                <label>New Request</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Pending Customer information</fullName>
            </value>
            <value>
                <fullName>Initiated in MyRepairs as a Draft</fullName>
            </value>
            <value>
                <fullName>Created in MyRepairs</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Preliminary Quote Pending Validation</fullName>
            </value>
            <value>
                <fullName>Preliminary Quote Validated</fullName>
            </value>
            <value>
                <fullName>Preliminary Quote Declined</fullName>
            </value>
            <value>
                <fullName>Spare parts order preparation</fullName>
            </value>
            <value>
                <fullName>Shipped to Repair Center</fullName>
            </value>
            <value>
                <fullName>Received in Repair Center</fullName>
            </value>
            <value>
                <fullName>Order pending validation</fullName>
            </value>
            <value>
                <fullName>Order rejected</fullName>
            </value>
            <value>
                <fullName>Order accepted</fullName>
            </value>
            <value>
                <fullName>Waiting for Spare parts</fullName>
            </value>
            <value>
                <fullName>Repair in progress</fullName>
            </value>
            <value>
                <fullName>Repair finalized</fullName>
            </value>
            <value>
                <fullName>Confirm Address</fullName>
            </value>
            <value>
                <fullName>Waiting for Payment</fullName>
            </value>
            <value>
                <fullName>Payment Confirmed</fullName>
            </value>
            <value>
                <fullName>Shipped to Client</fullName>
            </value>
            <value>
                <fullName>Received In E-Hub</fullName>
            </value>
            <value>
                <fullName>Delivered to Client</fullName>
            </value>
            <value>
                <fullName>Product stocked</fullName>
            </value>
            <value>
                <fullName>Payment Initiated</fullName>
            </value>
            <value>
                <fullName>Payment Review</fullName>
            </value>
            <value>
                <fullName>Payment Received</fullName>
            </value>
            <value>
                <fullName>Shipped from E-Hub</fullName>
            </value>
            <value>
                <fullName>Payment Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/LanguageLocaleKey__c.field-meta.xml
<CustomField>
    <fullName>LanguageLocaleKey__c</fullName>
    <defaultValue>IF ($RecordType.DeveloperName = &quot;DistantCareService&quot;, &quot;en_US&quot;, null)</defaultValue>
    <label>LanguageLocaleKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Last_ICONiCS_Status_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_ICONiCS_Status_Changed_Date__c</fullName>
    <description>Last Change Date of INCONiCS status detail</description>
    <label>Last ICONiCS Status Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/PBL_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>PBL_Created_Date__c</fullName>
    <label>PBL Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/PBL_Link__c.field-meta.xml
<CustomField>
    <fullName>PBL_Link__c</fullName>
    <label>PBL Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/PBL_Number__c.field-meta.xml
<CustomField>
    <fullName>PBL_Number__c</fullName>
    <label>PBL Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/PBL_Status__c.field-meta.xml
<CustomField>
    <fullName>PBL_Status__c</fullName>
    <label>PBL Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>active</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>ProductCatalogue__c</referenceTo>
    <relationshipLabel>Care Services</relationshipLabel>
    <relationshipName>Care_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <defaultValue>&quot;US&quot;</defaultValue>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <defaultValue>&quot;M99999&quot;</defaultValue>
    <label>SKU</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/StoreRetailCode__c.field-meta.xml
<CustomField>
    <fullName>StoreRetailCode__c</fullName>
    <label>StoreRetailCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/TotalAmount_Updated__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount_Updated__c</fullName>
    <label>Total Amount Updated</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <externalId>true</externalId>
    <label>Repair Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ICX_Repair_Store__mdt/ICX_Repair_Store__mdt.object-meta.xml
<CustomObject>
    <label>ICX Repair Store</label>
    <pluralLabel>ICX Repair Stores</pluralLabel>
</CustomObject>

force-app/main/default/objects/ICX_Repair_Store__mdt/fields/API_Key_Ixopay__c.field-meta.xml
<CustomField>
    <fullName>API_Key_Ixopay__c</fullName>
    <label>API Key Ixopay</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICX_Repair_Store__mdt/fields/Integrated_PBL__c.field-meta.xml
<CustomField>
    <fullName>Integrated_PBL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Integrated PBL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICX_Repair_Store__mdt/fields/LanguageLocaleKey__c.field-meta.xml
<CustomField>
    <fullName>LanguageLocaleKey__c</fullName>
    <label>LanguageLocaleKey</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICX_Repair_Store__mdt/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICX_Repair_Store__mdt/fields/Shared_Secret_Ixopay__c.field-meta.xml
<CustomField>
    <fullName>Shared_Secret_Ixopay__c</fullName>
    <label>Shared Secret Ixopay</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ixopay_Transaction__c/Ixopay_Transaction__c.object-meta.xml
<CustomObject>
    <label>Ixopay Transaction</label>
    <nameField>
        <displayFormat>IT-{0000000}</displayFormat>
        <label>Ixopay Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ixopay Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ixopay_Transaction__c/fields/Care_Service__c.field-meta.xml
<CustomField>
    <fullName>Care_Service__c</fullName>
    <label>Care Service</label>
    <referenceTo>CareService__c</referenceTo>
    <relationshipLabel>Ixopay Transactions</relationshipLabel>
    <relationshipName>Ixopay_Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ixopay_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initiated</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ixopay_Transaction__c/fields/Statut_Date__c.field-meta.xml
<CustomField>
    <fullName>Statut_Date__c</fullName>
    <label>Statut Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ixopay_Transaction__c/fields/uuid__c.field-meta.xml
<CustomField>
    <fullName>uuid__c</fullName>
    <label>UUID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logs__c/Logs__c.object-meta.xml
<CustomObject>
    <label>Logs</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logs__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MYLV</fullName>
            </value>
            <value>
                <fullName>LVAPP</fullName>
            </value>
            <value>
                <fullName>Distant Care Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Logs__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <inlineHelpText>Important record data</inlineHelpText>
    <label>Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MuleSoft_API_Callout__mdt/MuleSoft_API_Callout__mdt.object-meta.xml
<CustomObject>
    <label>MuleSoft API Callout</label>
    <pluralLabel>MuleSoft_API_Callouts</pluralLabel>
</CustomObject>

force-app/main/default/objects/MuleSoft_API_Callout__mdt/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>ClientId</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MuleSoft_API_Callout__mdt/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>ClientSecret</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MuleSoft_API_Callout__mdt/fields/ContentType__c.field-meta.xml
<CustomField>
    <fullName>ContentType__c</fullName>
    <label>ContentType</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MuleSoft_API_Callout__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCatalogue__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <description>SKU code</description>
    <externalId>true</externalId>
    <label>SKU</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-dcs/main/default/classes/ICX_WS_IXOPAY.cls
public with sharing class ICX_WS_IXOPAY {
    public ICX_WS_IXOPAY() {
    }
    
    @future (callout=true)
    public static void createLinkPBL(set<ID> careIds) {
        
        List<CareService__c> listCare =[select id,StoreRetailCode__c,TransactionId__c,PBL_Created_Date__c,PBL_Link__c,PBL_Number__c,PBL_Status__c,LanguageLocaleKey__c,TotalAmount_Updated__c,SKU__c,CurrencyCode__c,Product__r.Name,Client__c,Shipping_Country__c from CareService__c where id IN:careIds];
        List<CareService__c> listCareToUpdate = new List<CareService__c>() ;
        List<Logs__c> listLogs = new List<Logs__c> () ;
        List<Ixopay_Transaction__c> lstTransaction = new List<Ixopay_Transaction__c> () ;
        
        
        for(CareService__c care : listCare){     
            MuleSoft_API_Callout__mdt ApiCallout = MuleSoft_API_Callout__mdt.getInstance('PayByLink_Ixopay');
            ICX_Repair_Store__mdt repairCountry = ICX_Repair_Store__mdt.getInstance(String.valueOf(care.StoreRetailCode__c));
            if(care.TotalAmount_Updated__c>0 && ApiCallout != null && repairCountry != null && repairCountry.Integrated_PBL__c == true){
            String endpoint = ApiCallout.Endpoint__c + '/'+ repairCountry.API_Key_Ixopay__c + '/debit';
            //String username = ApiCallout.Username__c;
            //String password = ApiCallout.Password__c;
            String successUrlIxopay = System.Label.ICX_SuccessUrlIxopay; 
            String cancelUrlIxopay = System.Label.ICX_CancelUrlIxopay;
            String errorUrlIxopay =  System.Label.ICX_ErrorUrlIxopay; 
            String callbackUrlIxopay = System.Label.ICX_CallbackUrlIxopay;
            //Request      
            HttpRequest request = new HttpRequest();           
            request.setEndpoint(endpoint);
            request.setMethod('POST');
           // request.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
            request.setHeader('Content-Type', ApiCallout.ContentType__c);
            request.setHeader('client_id', ApiCallout.ClientId__c);
            request.setHeader('client_secret', ApiCallout.ClientSecret__c); 
            request.setHeader('X-Sign', repairCountry.Shared_Secret_Ixopay__c);
            request.setTimeout(Integer.valueOf(ApiCallout.Timeout__c));     
            
            requestDebitIxopay myRequest = new requestDebitIxopay();    
            
            //productCare productC = new productCare();    
            //productC.name = care.Product__r.name == null? 'Unknown Product' : care.Product__r.name;
            
            customerCare customerC = new customerCare();
            customerC.identification = care.Client__c;
            customerC.shippingCountry =  care.Shipping_Country__c;
            //myRequest.items.add(productC);
            myRequest.customer = customerC;
            myRequest.additionalId1 = care.StoreRetailCode__c;
            myRequest.merchantTransactionId = String.valueOf(System.now().getTime());
            myRequest.merchantMetaData = care.TransactionId__c == null ? 'MyRepairs_Id' : care.TransactionId__c;
            myRequest.amount =  String.valueOf(care.TotalAmount_Updated__c) == null ? '0' : String.valueOf(care.TotalAmount_Updated__c);
            myRequest.currency_x = care.CurrencyCode__c == null ? 'EUR' : care.CurrencyCode__c;
            myRequest.successUrl = successUrlIxopay;
            myRequest.cancelUrl = cancelUrlIxopay;
            myRequest.errorUrl = errorUrlIxopay;
            myRequest.callbackUrl = callbackUrlIxopay;
            myRequest.language = care.LanguageLocaleKey__c == null ? 'en' : care.LanguageLocaleKey__c.substring(0,2); //LanguageLocaleKey__c=en_US         
            
            String jsonBody = JSON.serialize(myRequest).replace('"currency_x":', '"currency":');
            
            
            system.debug('JSON BODY IXOPAY To Process ==> '+jsonBody);
            
            request.setBody(jsonBody);
            
            //Reponse
            HttpResponse response = new HttpResponse();
            try {
                
                Http http = new Http();            
                response = http.send(request);
                
                system.debug('### Ixopay Reponse Status : '+response.getStatusCode()+' '+response.getStatus());
                System.debug('### Ixopay Reponse Body : '+response.getBody());
                responseIxopay ixoPayResponse = parse(response.getBody());
                if(ixoPayResponse.success==true){
                    care.PBL_Created_Date__c = system.now();
                    care.PBL_Link__c = ixoPayResponse.redirectUrl;
                    System.debug('Ixopay Response Redirect URL : ' + ixoPayResponse.redirectUrl);                
                    care.PBL_Number__c = ixoPayResponse.uuid;
                    care.PBL_Status__c = 'Initiated';
                    care.ICONiCS_Status_Detail__c = 'Payment Initiated';
                    //care.Last_ICONiCS_Status_Changed_Date__c = system.today();
                    listCareToUpdate.add(care);         
                    
                    Ixopay_Transaction__c payment = new Ixopay_Transaction__c ();
                    payment.uuid__c = ixoPayResponse.uuid;
                    payment.Status__c = 'Initiated';
                    payment.Statut_Date__c = system.now();
                    payment.Transaction_Type__c = 'DEBIT';
                    payment.Care_Service__r = new CareService__c(TransactionId__c=care.TransactionId__c);
                    lstTransaction.add(payment);
                    
                }else{ 
                    Logs__c log = new Logs__c ();
                    log.Application__c = 'Distant Care Service';
                    log.Record_Id__c = care.Id;
                    log.Apex_Class__c = 'ICX_WS_IXOPAY';
                    log.API_Request__c = jsonBody;
                    log.API_Response__c = response.getBody();
                    log.Has_Error__c = true;
                    if(ixoPayResponse.error != null){
                        log.Error__c = ixoPayResponse.error;                    	
                    }else if(ixoPayResponse.errors!=null){
                        log.Error__c = ixoPayResponse.errors[0].errorCode +' '+ixoPayResponse.errors[0].errorMessage;
                    }else{
                        log.Error__c = ixoPayResponse.errorCode +' '+ixoPayResponse.errorMessage;
                    }
                    listLogs.add(log);
                }
                
                
                
            } catch (CalloutException e) {               
                throw  new CalloutException(e.getMessage());
            }
          }
        }
        if(listCareToUpdate.size()>0)
            update listCareToUpdate; 
        if(listLogs.size()>0)  
            insert listLogs; 
        if(lstTransaction.size()>0)
            insert lstTransaction; 
    }
    
    @AuraEnabled (cacheable=true)
    public static String createRefund(ID careId) {
        String returnString = null;
        Ixopay_Transaction__c myTransaction = [select id,uuid__c,Amount__c,Currency__c,Care_Service__r.TransactionId__c,Care_Service__r.StoreRetailCode__c, Care_Service__r.Refund_Amount__c from Ixopay_Transaction__c where Care_Service__c =:careId and Status__c = 'Success' and Transaction_Type__c ='DEBIT' limit 1];
        MuleSoft_API_Callout__mdt ApiCallout = MuleSoft_API_Callout__mdt.getInstance('PayByLink_Ixopay');
        ICX_Repair_Store__mdt repairCountry = ICX_Repair_Store__mdt.getInstance(String.valueOf(myTransaction.Care_Service__r.StoreRetailCode__c));
        if(ApiCallout != null && repairCountry != null){
        String endpoint = ApiCallout.Endpoint__c + '/'+ repairCountry.API_Key_Ixopay__c + '/refund';
        //String username = ApiCallout.Username__c;
        //String password = ApiCallout.Password__c;
        String callbackUrlIxopay = System.Label.ICX_CallbackUrlIxopay;
        //Request      
        HttpRequest request = new HttpRequest();           
        request.setEndpoint(endpoint);
        request.setMethod('POST');
        //request.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
        request.setHeader('Content-Type', ApiCallout.ContentType__c);
        request.setHeader('client_id', ApiCallout.ClientId__c);
        request.setHeader('client_secret', ApiCallout.ClientSecret__c); 
        request.setHeader('X-Sign', repairCountry.Shared_Secret_Ixopay__c);
        request.setTimeout(Integer.valueOf(ApiCallout.Timeout__c));     
        
        requestRefundIxopay myRequest = new requestRefundIxopay();    
        myRequest.referenceUuid = myTransaction.uuid__c;
        myRequest.additionalId1 = myTransaction.Care_Service__r.StoreRetailCode__c;
        myRequest.merchantTransactionId = String.valueOf(System.now().getTime());
        myRequest.merchantMetaData = myTransaction.Care_Service__r.TransactionId__c;
        myRequest.amount =  String.valueOf(myTransaction.Care_Service__r.Refund_Amount__c) == null ? '0' : String.valueOf(myTransaction.Care_Service__r.Refund_Amount__c);
        myRequest.currency_x = myTransaction.Currency__c == null ? 'EUR' : myTransaction.Currency__c;
        myRequest.callbackUrl = callbackUrlIxopay;
        String jsonBody = JSON.serialize(myRequest).replace('"currency_x":', '"currency":');
        
        
        system.debug('JSON BODY IXOPAY To Process ==> '+jsonBody);
        
        request.setBody(jsonBody);
        
        //Reponse
        HttpResponse response = new HttpResponse();
        try {
            
            Http http = new Http();            
            response = http.send(request);
            
            system.debug('### Ixopay Reponse Status : '+response.getStatusCode()+' '+response.getStatus());
            System.debug('### Ixopay Reponse Body : '+response.getBody());
            responseIxopay ixoPayResponse = parse(response.getBody());
            if(ixoPayResponse.success==true){
                /*Ixopay_Transaction__c refund = new Ixopay_Transaction__c ();
                refund.uuid__c = ixoPayResponse.uuid;
                refund.Status__c = 'Initiated';
                refund.Statut_Date__c = system.now();
                refund.Transaction_Type__c = 'REFUND';
                refund.Amount__c = myTransaction.Amount__c;
                refund.Currency__c = myTransaction.Currency__c;
                refund.Care_Service__r = new CareService__c(TransactionId__c=myTransaction.Care_Service__r.TransactionId__c);
                insert refund;*/
               
                returnString = 'Success';
            }else{   
               /* Logs__c log = new Logs__c ();
                log.Application__c = 'Distant Care Service';
                log.Record_Id__c = careId;
                log.Apex_Class__c = 'ICX_WS_IXOPAY';
                log.API_Request__c = jsonBody;
                log.API_Response__c = response.getBody();
                log.Has_Error__c = true;
                if(ixoPayResponse.error != null){
                    log.Error__c = ixoPayResponse.error;
                    returnString = 'Error '+ ixoPayResponse.error;
                }else if(ixoPayResponse.errors!=null){
                    log.Error__c = ixoPayResponse.errors[0].errorCode +' '+ixoPayResponse.errors[0].errorMessage;
                    returnString = 'Error '+ ixoPayResponse.errors[0].errorCode +' '+ixoPayResponse.errors[0].errorMessage;
                }else{
                    log.Error__c = ixoPayResponse.errorCode +' '+ixoPayResponse.errorMessage;
                    returnString = 'Error '+ ixoPayResponse.errorCode +' '+ixoPayResponse.errorMessage;
                }
                insert log;  */
                if(ixoPayResponse.error != null){                   
                    returnString = 'Error '+ ixoPayResponse.error;
                }else if(ixoPayResponse.errors!=null){                  
                    returnString = 'Error '+ ixoPayResponse.errors[0].errorCode +' '+ixoPayResponse.errors[0].errorMessage;
                }else{                   
                    returnString = 'Error '+ ixoPayResponse.errorCode +' '+ixoPayResponse.errorMessage;
                }
            }              
            
            
            
        } catch (CalloutException e) {               
            throw  new CalloutException(e.getMessage());
        }
    } 
        return returnString;
     
    }

    @AuraEnabled (cacheable=true)
    public static String createPaymentReviewPBL(ID careId) {  
        String returnString = null;
        CareService__c care =[select id,StoreRetailCode__c,TransactionId__c,PBL_Created_Date__c,PBL_Link__c,PBL_Number__c,PBL_Status__c,LanguageLocaleKey__c,TotalAmount_Updated__c,SKU__c,CurrencyCode__c,Product__r.Name,Client__c,Shipping_Country__c from CareService__c where id =:careId];
        List<Logs__c> listLogs = new List<Logs__c> () ;
        List<Ixopay_Transaction__c> lstTransaction = new List<Ixopay_Transaction__c> () ;        
           
            MuleSoft_API_Callout__mdt ApiCallout = MuleSoft_API_Callout__mdt.getInstance('PayByLink_Ixopay');
            ICX_Repair_Store__mdt repairCountry = ICX_Repair_Store__mdt.getInstance(String.valueOf(care.StoreRetailCode__c));
            if(care.TotalAmount_Updated__c>0 && ApiCallout != null && repairCountry != null && repairCountry.Integrated_PBL__c == true){
            String endpoint = ApiCallout.Endpoint__c + '/'+ repairCountry.API_Key_Ixopay__c + '/debit';
           
            String callbackUrlIxopay = System.Label.ICX_CallbackUrlIxopay;
            //Request      
            HttpRequest request = new HttpRequest();           
            request.setEndpoint(endpoint);
            request.setMethod('POST');
            request.setHeader('Content-Type', ApiCallout.ContentType__c);
            request.setHeader('client_id', ApiCallout.ClientId__c);
            request.setHeader('client_secret', ApiCallout.ClientSecret__c); 
            request.setHeader('X-Sign', repairCountry.Shared_Secret_Ixopay__c);
            request.setTimeout(Integer.valueOf(ApiCallout.Timeout__c));     
            
            requestPBLIxopay myRequest = new requestPBLIxopay();    
         
            customerCare customerC = new customerCare();
            extraDataType myExtraData = new extraDataType();
            payByLinkType myPayByLink =  new payByLinkType();

            customerC.identification = care.Client__c;
            customerC.shippingCountry =  care.Shipping_Country__c;                    
            myExtraData.PBL = '1';
            myPayByLink.sendByEmail = false;

            myRequest.customer = customerC;            
            myRequest.extraData = myExtraData;
            myRequest.payByLink = myPayByLink;
            myRequest.additionalId1 = care.StoreRetailCode__c;
            myRequest.merchantTransactionId = String.valueOf(System.now().getTime());
            myRequest.merchantMetaData = care.TransactionId__c == null ? 'MyRepairs_Id' : care.TransactionId__c;
            myRequest.amount =  String.valueOf(care.TotalAmount_Updated__c) == null ? '0' : String.valueOf(care.TotalAmount_Updated__c);
            myRequest.currency_x = care.CurrencyCode__c == null ? 'EUR' : care.CurrencyCode__c;
            myRequest.callbackUrl = callbackUrlIxopay;
            myRequest.language = care.LanguageLocaleKey__c == null ? 'en' : care.LanguageLocaleKey__c.substring(0,2); //LanguageLocaleKey__c=en_US         
           
            String jsonBody = JSON.serialize(myRequest).replace('"currency_x":', '"currency":');
            
            
            system.debug('JSON BODY IXOPAY To Process ==> '+jsonBody);
            
            request.setBody(jsonBody);
            
            //Reponse
            HttpResponse response = new HttpResponse();
            try {
                
                Http http = new Http();            
                response = http.send(request);
                
                system.debug('### Ixopay Reponse Status : '+response.getStatusCode()+' '+response.getStatus());
                System.debug('### Ixopay Reponse Body : '+response.getBody());
                responseIxopay ixoPayResponse = parse(response.getBody());
                if(ixoPayResponse.success==true){
                    returnString = ixoPayResponse.uuid+';'+ixoPayResponse.redirectUrl;
                    
                }else{ 
                    if(ixoPayResponse.error != null){                   
                        returnString = 'Error '+ ixoPayResponse.error;
                    }else if(ixoPayResponse.errors!=null){                  
                        returnString = 'Error '+ ixoPayResponse.errors[0].errorCode +' '+ixoPayResponse.errors[0].errorMessage;
                    }else{                   
                        returnString = 'Error '+ ixoPayResponse.errorCode +' '+ixoPayResponse.errorMessage;
                    }
                }
                
                
                
            } catch (CalloutException e) {               
                throw  new CalloutException(e.getMessage());
            }
          }
          return returnString;
    }
    
    public class requestDebitIxopay {
        public String merchantTransactionId; //Timestamp       
        public String additionalId1; //F92	
        public String merchantMetaData;	//Blue Bag - ModelM671
        public String amount; // 9.99 
        public String currency_x; // EUR
        public String successUrl; // URL
        public String cancelUrl; // URL
        public String errorUrl; // URL
        public String callbackUrl; // URL
        //public list<productCare> items = new list<productCare>(); //SET VALS!!!
        public customerCare customer; 
        public String language; //Two first Capital of language local key
       
    }

    public class requestPBLIxopay {
        public String merchantTransactionId; //Timestamp       
        public String additionalId1; //F92	
        public String merchantMetaData;	//Blue Bag - ModelM671
        public String amount; // 9.99 
        public String currency_x; // EUR       
        public String callbackUrl; // URL
        //public list<productCare> items = new list<productCare>(); //SET VALS!!!
        public customerCare customer; 
        public String language; //Two first Capital of language local key
        public extraDataType extraData;
        public payByLinkType payByLink;
    }
   /* public class productCare {
        public string name;
    }*/
    
    public class customerCare {
        public String identification; 	//SF accId (00003001)
        public String shippingCountry; // FR
    }

    public class extraDataType {
        public string PBL;
    }

    public class payByLinkType {
        public Boolean sendByEmail;
    }

    public class requestRefundIxopay {
        public String merchantTransactionId; //Timestamp     
        public String referenceUuid;//352532d6962eeb33ec14
        public String additionalId1; //F92	
        public String merchantMetaData;	//Blue Bag - ModelM671
        public String amount; // 9.99 
        public String currency_x; // EUR       
        public String callbackUrl; // URL  
    }
    public class responseIxopay {
        public String   error;
        public boolean	success;		//true
        public String 	uuid;			//6ff0f5eeac3adcd1ea1c
        public String	purchaseId;		//20230512-6ff0f5eeac3adcd1ea1c
        public String	returnType;		//REDIRECT
        public String	redirectUrl;	//https:\/\/louisvuitton.ixopaysandbox.com\/redirect\/6ff0f5eeac3adcd1ea1c\/YzhjMjUxMGYzYTY1NWNhYzhiN2RiMGYyNDg0MWMxNDAyYmE0OTk0OWM5Y2RjMGNkNTk4MTQ3MDY4ZjkzZjVlZDZmNGQyNGI4OWE5ZTk4NGRkNzhhNDFkYWY2Y2YzMGEwMGEwMWMyNWE0NjRmY2RmYTg5MDIwMTM1NDZhZTZhN2U=	
        public String 	paymentMethod;	//Creditcard
        public String   errorMessage;    //Signature invalid
        public Integer  errorCode;      //3004
        public List <responseError> errors = new List <responseError> ();
    }
    public class responseError {
        public String errorMessage;
        public Integer errorCode;
    }
    
    public static responseIxopay parse(String json) {
        return (responseIxopay) System.JSON.deserialize(json, responseIxopay.class);
    }
}