force-app/main/default/objects/CareService__c/CareService__c.object-meta.xml
<CustomObject>
    <label>Care Service</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Care Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareService__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Services</relationshipLabel>
    <relationshipName>Care_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/FollowupBy_Chat__c.field-meta.xml
<CustomField>
    <fullName>FollowupBy_Chat__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Followup By SMS/ChatApps</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/FollowupBy_Email__c.field-meta.xml
<CustomField>
    <fullName>FollowupBy_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Followup By Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/IsToDo__c.field-meta.xml
<CustomField>
    <fullName>IsToDo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is To Do</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Last_MyRepair_Status_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_MyRepair_Status_Changed_Date__c</fullName>
    <label>Last MyRepair Status Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/MyRepair_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>MyRepair_CreatedDate__c</fullName>
    <label>MyRepair Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <defaultValue>&quot;M99999&quot;</defaultValue>
    <label>SKU</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Care Services</relationshipLabel>
    <relationshipName>Care_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/StoreRetailCode__c.field-meta.xml
<CustomField>
    <fullName>StoreRetailCode__c</fullName>
    <label>StoreRetailCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <externalId>true</externalId>
    <label>Repair Number</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CareService__c/recordTypes/DistantCareService.recordType-meta.xml
<RecordType>
    <fullName>DistantCareService</fullName>
    <active>true</active>
    <label>Distant Care Service</label>
</RecordType>

force-app/main/default/objects/CareServiceLineItem__c/CareServiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Care Service Line Item</label>
    <nameField>
        <displayFormat>CSLI-{0000000}</displayFormat>
        <label>Care Service Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Service Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareServiceLineItem__c/fields/CareService__c.field-meta.xml
<CustomField>
    <fullName>CareService__c</fullName>
    <label>Care Service</label>
    <referenceTo>CareService__c</referenceTo>
    <relationshipName>CareService_LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CareServiceLineItem__c/fields/Instruction_Name_ICONiCS__c.field-meta.xml
<CustomField>
    <fullName>Instruction_Name_ICONiCS__c</fullName>
    <label>Repair Instruction</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CareServiceLineItem__c/fields/InstructionCode__c.field-meta.xml
<CustomField>
    <fullName>InstructionCode__c</fullName>
    <label>Instruction Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductCatalogue__c/ProductCatalogue__c.object-meta.xml
<CustomObject>
    <description>For PERSO app, products to be imported with Heroku Connect to get only Perso products (Heroku Connect can&apos;t filter in ProductReferential__c)</description>
    <label>Product (Catalogue)</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products (Catalogue)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductCatalogue__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <description>SKU code</description>
    <externalId>true</externalId>
    <label>SKU</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ICX_ReceiptCareServiceCtl_TEST.cls
/*	 * @author Keman WU
* @date creation 04/11/2021
* @description test class for ICX_ReceiptCareServiceCtl
*/
@isTest
public with sharing class ICX_ReceiptCareServiceCtl_TEST {
    @isTest static void myTest() {
        Id DistantCareRTId = Schema.SObjectType.CareService__c.getRecordTypeInfosByDeveloperName().get('DistantCareService').getRecordTypeId();   	

        Store__c store1= new Store__c(RetailStoreId__c = 'UE4');
		insert store1;      
        Account acc = ICX_TestFactory.createAccount();
        insert acc;
        ProductCatalogue__c product = new ProductCatalogue__c(SKU__c ='M55555');
        insert product;
        CareService__c dcs = new CareService__c(recordTypeId = DistantCareRTId, transactionId__c='o658757969',Client__c =acc.Id, StoreRetailCode__c = 'UE4', Store__c = store1.Id, IsToDo__c=false,Product_Family__c='test family',SKU__c='M9999',MyRepair_CreatedDate__c = system.today(),Last_MyRepair_Status_Changed_Date__c = system.today(),FollowupBy_Email__c=true,FollowupBy_Chat__c=true);
       insert dcs;
       CareServiceLineItem__c csl = new CareServiceLineItem__c(Quantity__c=1, InstructionCode__c='1234', Instruction_Name_ICONiCS__c='TEST',CareService__c=dcs.id);
       insert csl;
        test.startTest();
        PageReference pageRef = Page.ICX_ReceiptCareService;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(dcs);
        ICX_ReceiptCareServiceCtl controller = new ICX_ReceiptCareServiceCtl(sc);
        controller.getQuotations();
        controller.getUppercaseRepairNumber();
        test.stopTest();

    }
}