force-app/main/default/objects/CareService__c/CareService__c.object-meta.xml
<CustomObject>
    <label>Care Service</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Care Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareService__c/fields/CA_Code__c.field-meta.xml
<CustomField>
    <fullName>CA_Code__c</fullName>
    <label>CA Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Services</relationshipLabel>
    <relationshipName>Care_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Estimated end of repair</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CareService__c/fields/FollowupBy_Email__c.field-meta.xml
<CustomField>
    <fullName>FollowupBy_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Followup By Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Hot_Status__c.field-meta.xml
<CustomField>
    <fullName>Hot_Status__c</fullName>
    <label>Hot Status(deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/MyRepair_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>MyRepair_CreatedDate__c</fullName>
    <label>MyRepair Created Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/MyRepairStatus__c.field-meta.xml
<CustomField>
    <fullName>MyRepairStatus__c</fullName>
    <label>My Repair Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
                <label>Draft</label>
            </value>
            <value>
                <fullName>createdInStore</fullName>
                <label>Created in store</label>
            </value>
            <value>
                <fullName>pendingQualityExpertise</fullName>
                <label>Pending quality expertise</label>
            </value>
            <value>
                <fullName>shippedToRepairCenter</fullName>
                <label>Shipped to repair center</label>
            </value>
            <value>
                <fullName>shippedToLocalPartner</fullName>
                <label>Shipped to Local Partner</label>
            </value>
            <value>
                <fullName>orderPendingValidation</fullName>
                <label>Order pending validation</label>
            </value>
            <value>
                <fullName>waitingForClientDecision</fullName>
                <label>Waiting for client decision</label>
            </value>
            <value>
                <fullName>orderAccepted</fullName>
                <label>Order accepted</label>
            </value>
            <value>
                <fullName>orderRejected</fullName>
                <label>Order rejected</label>
            </value>
            <value>
                <fullName>waitingForSpareParts</fullName>
                <label>Waiting for spare parts</label>
            </value>
            <value>
                <fullName>repairInProgress</fullName>
                <label>Repair in progress</label>
            </value>
            <value>
                <fullName>shippedToStore</fullName>
                <label>Repair finalized</label>
            </value>
            <value>
                <fullName>clientContacted</fullName>
                <label>Client contacted</label>
            </value>
            <value>
                <fullName>paymentConfirmed</fullName>
                <label>Payment confirmed</label>
            </value>
            <value>
                <fullName>productDeliveredToClient</fullName>
                <label>Product delivered to client</label>
            </value>
            <value>
                <fullName>servicePerformed</fullName>
                <label>Service performed</label>
            </value>
            <value>
                <fullName>expertisePerformedInRepairCenter</fullName>
                <label>Expertise performed in repair center</label>
            </value>
            <value>
                <fullName>receivedAndAcceptedInStore</fullName>
                <label>Received and accepted in store</label>
            </value>
            <value>
                <fullName>receivedAndNotAcceptedInStore</fullName>
                <label>Received and not accepted in store</label>
            </value>
            <value>
                <fullName>productStocked</fullName>
                <label>Product stocked</label>
            </value>
            <value>
                <fullName>sentToRMS</fullName>
                <label>Sent to RMS</label>
            </value>
            <value>
                <fullName>cancelled</fullName>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>initial</fullName>
                <label>Initial</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Red_Code__c.field-meta.xml
<CustomField>
    <fullName>Red_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Red Code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address_Line_1__c</fullName>
    <label>Shipping Address Line 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <defaultValue>&quot;US&quot;</defaultValue>
    <label>Shipping Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_ISO_2</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CareService__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <defaultValue>&quot;M99999&quot;</defaultValue>
    <label>SKU</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/StoreRetailCode__c.field-meta.xml
<CustomField>
    <fullName>StoreRetailCode__c</fullName>
    <label>StoreRetailCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CareService__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>NOTIF-{0000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CARE SERVICE</fullName>
            </value>
            <value>
                <fullName>DISTANT CARE SERVICE</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE EXPERIENCE</fullName>
            </value>
            <value>
                <fullName>EXCLUSIVE SALES</fullName>
                <isActive>false</isActive>
                <label>EXCLUSIVE SALES</label>
            </value>
            <value>
                <fullName>ICON</fullName>
            </value>
            <value>
                <fullName>ONLINE APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>POST CONTACT</fullName>
            </value>
            <value>
                <fullName>WECHAT DIAMOND APPOINTMENT</fullName>
            </value>
            <value>
                <fullName>WECHAT ONLINE APPOINTMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notifications</relationshipLabel>
    <relationshipName>Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <label>Message Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
            <value>
                <fullName>CLOSED</fullName>
            </value>
            <value>
                <fullName>CREATED</fullName>
                <default>true</default>
                <label>CREATED</label>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>NOT SENT</fullName>
            </value>
            <value>
                <fullName>READY TO SEND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notification_Parameter__c/Notification_Parameter__c.object-meta.xml
<CustomObject>
    <label>Notification Parameter</label>
    <nameField>
        <displayFormat>NP-{0000000}</displayFormat>
        <label>Notification Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Parameters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification_Parameter__c/fields/LongValue__c.field-meta.xml
<CustomField>
    <fullName>LongValue__c</fullName>
    <label>LongValue</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Notification_Parameter__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <referenceTo>Notification__c</referenceTo>
    <relationshipLabel>Notification Parameters</relationshipLabel>
    <relationshipName>Notification_Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Notification_Sender_TEST.cls
@isTest
private class Notification_Sender_TEST {
    
    @isTest static void testClass() {

        Integer i = 5;
        Long l = 5;
        Decimal d = 5;
        Notification_Sender.getType(i);
        Notification_Sender.getType(l);
        Notification_Sender.getType(d);

            Identity_TestFactory.createSettings();
            Account acc = Identity_TestFactory.createAccount('gege', 'test1', 'gege@test1.com', '+972549876543', '', true);
            CareService__c care = new CareService__c(
                    ExternalId__c = 'abcdefgh12345',
                    Hot_Status__c = 'New',
                    Red_Code__c = true,
                    SKU__c = 'M51904',
                    TotalAmount__c = null,
                    CA_Code__c = null,
                    StoreRetailCode__c = 'A06',
                    Delivery_Date__c = null,
                    MyRepair_CreatedDate__c = Date.valueOf('2019-06-05'),
                    MyRepairStatus__c = 'productDeliveredToClient',
                    Client__c = acc.id,
                    Shipping_Address_Line_1__c = 'dummy address',
                    Shipping_City__c = 'dummy city',
                    Shipping_Country__c = 'US',
                    Shipping_State_Province__c = 'dummy province',
                    Shipping_Zip_Postal_Code__c = '75001',
                    FollowupBy_Email__c = true);

        Test.startTest();
            insert care;
         Test.stopTest();

         //trigger handler calls to Notification_Sender send method: Notification_Sender.send('CARE SERVICE', 1, null, client_ids, params);        
        list<Notification__c> notifs = [SELECT Id, Application__c, Message_Id__c, Client__c, External_Id__c, LastModifiedDate, Status__c FROM Notification__c];
        list<Notification_Parameter__c> nparams = [SELECT Id, Notification__c, Field__c, LongValue__c FROM Notification_Parameter__c];
        System.debug(notifs);
        System.debug(nparams);
    }
 }


 /************** be carefull for class coverage: must be: 
 MyRepair_CreatedDate__c > System.now().addMonths(-1)
 --> change the date!!!
 ********************************************************/