force-app/main/default/objects/CareService__c/CareService__c.object-meta.xml
<CustomObject>
    <label>Care Service</label>
    <nameField>
        <displayFormat>CS-{0000000}</displayFormat>
        <label>Care Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Care Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CareService__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Care Services</relationshipLabel>
    <relationshipName>Care_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ShipmentTracking__c/ShipmentTracking__c.object-meta.xml
<CustomObject>
    <label>Shipment tracking</label>
    <nameField>
        <displayFormat>ST-{00000000}</displayFormat>
        <label>Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ShipmentTracking__c/fields/CareService__c.field-meta.xml
<CustomField>
    <fullName>CareService__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Care Service</label>
    <referenceTo>CareService__c</referenceTo>
    <relationshipLabel>Shipment trackings</relationshipLabel>
    <relationshipName>Shipment_trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ShipmentTracking_TriggerHandler.cls
/*	 * @author Keman WU
* @date creation 27/05/2022
* @description Trigger Handler of ShipmentTrackingTrigger 
*/
public class ShipmentTracking_TriggerHandler {   
    
    public static void beforeInsert(List<ShipmentTracking__c> newShipmentTrackingList, Map<id, ShipmentTracking__c> newShipmentTrackingMap) {
        Map<Id,String> mapAccountUser = new Map<Id,String>();
        Map<Id,String> mapCareAccount = new Map<Id,String>();
        set<Id> setCareId = new Set<Id> ();
        for(ShipmentTracking__c myRecord : newShipmentTrackingList){           
            setCareId.add(myRecord.CareService__c);           
        }

        for(CareService__c care :[select id,Client__c from CareService__c where Id in:setCareId]){
            mapCareAccount.put(care.Id,care.Client__c);
        }
        for(User u :[select Id, AccountId from User where AccountId IN :mapCareAccount.values() and IsActive = true]){
            mapAccountUser.put(u.AccountId, u.Id);
        }
        //Change ShipmentTracking Owner
        for(ShipmentTracking__c myRecord : newShipmentTrackingList){        
            if(mapAccountUser.get(mapCareAccount.get(myRecord.CareService__c)) != null){   
           myRecord.OwnerId = mapAccountUser.get(mapCareAccount.get(myRecord.CareService__c));
           system.debug('owner user '+myRecord.OwnerId );
            }
        }
       
    
    }
}