force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>An event is a public evenment for the purpose of celebration or marketing related to the customer.</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>End Date of the event</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>Zone</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Location of the event</description>
    <label>Location</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of the event</description>
    <inlineHelpText>If you leave this field empty then it will be populated using the program start date</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Theme__c.field-meta.xml
<CustomField>
    <fullName>Theme__c</fullName>
    <description>Theme of the event</description>
    <label>Theme</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fashion</fullName>
            </value>
            <value>
                <fullName>Art &amp; Culture</fullName>
            </value>
            <value>
                <fullName>Food &amp; Wine</fullName>
            </value>
            <value>
                <fullName>Watch &amp; Jewelry</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>Sport &amp; Leisure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Theme of the event</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Theme__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Asnières</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Exhibition</fullName>
            </value>
            <value>
                <fullName>Fashion Show Men</fullName>
            </value>
            <value>
                <fullName>Fashion Show Women</fullName>
            </value>
            <value>
                <fullName>Fiesso</fullName>
            </value>
            <value>
                <fullName>Fondation LV</fullName>
            </value>
            <value>
                <fullName>Grasse</fullName>
            </value>
            <value>
                <fullName>La Fabrique du Temps</fullName>
            </value>
            <value>
                <fullName>Maison LVMH</fullName>
            </value>
            <value>
                <fullName>Series</fullName>
            </value>
            <value>
                <fullName>Social Gathering</fullName>
            </value>
            <value>
                <fullName>Sport &amp; Leasure</fullName>
            </value>
            <value>
                <fullName>Store Opening</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Watch &amp; Jewelry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>An experience can be created into the application and linked to the program.</description>
    <label>Experience</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Experience Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Experience_Name__c.field-meta.xml
<CustomField>
    <fullName>Experience_Name__c</fullName>
    <label>Experience Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Private Shopping</fullName>
            </value>
            <value>
                <fullName>La Fabrique du Temps</fullName>
            </value>
            <value>
                <fullName>Asnières</fullName>
            </value>
            <value>
                <fullName>Cultural</fullName>
            </value>
            <value>
                <fullName>Fiesso</fullName>
            </value>
            <value>
                <fullName>Beauty &amp; Spa</fullName>
            </value>
            <value>
                <fullName>High Jewellry</fullName>
            </value>
            <value>
                <fullName>La Fondation Louis Vuitton</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Wines and spirits</fullName>
            </value>
            <value>
                <fullName>Dining</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Experience__c/fields/ProgramId__c.field-meta.xml
<CustomField>
    <fullName>ProgramId__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>If you leave this field empty then it will be populated using the program start date</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Gift__c/Gift__c.object-meta.xml
<CustomObject>
    <description>A gift can be created into the application and linked to the program.</description>
    <label>Gift</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Gift Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gift__c/fields/Gift_Name__c.field-meta.xml
<CustomField>
    <fullName>Gift_Name__c</fullName>
    <label>Gift Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Champagne</fullName>
            </value>
            <value>
                <fullName>Chocolates</fullName>
            </value>
            <value>
                <fullName>Flowers</fullName>
            </value>
            <value>
                <fullName>LV Gift</fullName>
            </value>
            <value>
                <fullName>Non LV Gift</fullName>
            </value>
            <value>
                <fullName>Wine</fullName>
            </value>
            <value>
                <fullName>Néo Nano Fuschia</fullName>
            </value>
            <value>
                <fullName>Pochette Jour Taiga Grizzli</fullName>
            </value>
            <value>
                <fullName>Dom Pérignon P2</fullName>
            </value>
            <value>
                <fullName>Leather Envelope</fullName>
            </value>
            <value>
                <fullName>Guerlain Sunscreen</fullName>
            </value>
            <value>
                <fullName>Guerlain Cosmetics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gift__c/fields/ProgramId__c.field-meta.xml
<CustomField>
    <fullName>ProgramId__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Gifts</relationshipLabel>
    <relationshipName>Gifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <displayFormat>H-{00000}</displayFormat>
        <label>Hotel Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/HotelName__c.field-meta.xml
<CustomField>
    <fullName>HotelName__c</fullName>
    <label>Hotel Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/ProgramId__c.field-meta.xml
<CustomField>
    <fullName>ProgramId__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Hotels</relationshipLabel>
    <relationshipName>Hotels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hotel__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>To</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <description>Program is an entity related to master information since this entity is linked to : a client, an event, a hotel (not necessarily), a gift (not necessarily), an experience (not necessarily) and a restaurant (not necessarily</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/EventId__c.field-meta.xml
<CustomField>
    <fullName>EventId__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/Restaurant__c.object-meta.xml
<CustomObject>
    <label>Restaurant</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Restaurant Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Restaurants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Restaurant__c/fields/Booking_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date_Time__c</fullName>
    <label>Booking Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/ProgramId__c.field-meta.xml
<CustomField>
    <fullName>ProgramId__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Restaurants</relationshipLabel>
    <relationshipName>Restaurants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Restaurant__c/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <label>Restaurant Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transport__c/Transport__c.object-meta.xml
<CustomObject>
    <label>Transport</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Transport Ref.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport__c/fields/ProgramId__c.field-meta.xml
<CustomField>
    <fullName>ProgramId__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Transports</relationshipLabel>
    <relationshipName>Transports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transport__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal Chauffeur</fullName>
            </value>
            <value>
                <fullName>Private Jet</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>Airplane</fullName>
            </value>
            <value>
                <fullName>Car Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/STAR_ProgramView_VFCx_TEST.cls
/**

 */
@isTest
private class STAR_ProgramView_VFCx_TEST {

    static testMethod void DisplayProgramAndRelatedList() {
        
        Event__c evt;
        Program__c prg;
        Gift__c gft;
        Hotel__c htl;
        Experience__c exp;
        Restaurant__c rest;
        Transport__c trp;
        
        //Create new Account
        Account account = IC_TestFactory.createAccount();
        insert account;
        
               
        //Create new STAR Event ('Event__c' Object ). It will be used when STAR Program is created
        evt = new Event__c();
        evt.Name='EventTest';
        evt.Start_Date__c =Date.today();
        evt.End_Date__c =Date.today();      
        evt.Location__c='PariSelecs';
        evt.Level__c='International';
        evt.Theme__c='Art & Culture';
        evt.Type__c='Exhibition';
        
        insert evt;
        
        //Create new Program
        prg = New Program__c();
        prg.name='ProgramTest';
        prg.AccountId__c = account.Id;
        prg.EventId__c = evt.id;
        //prgView.IdProgram= prg.id; 
        insert prg;
        
        //Create Gift related to the Program [ProgramTest]
        gft = new Gift__c();
        //gft.Name='GiftTest';
        gft.Gift_Name__c='Wine';
        gft.ProgramId__c=prg.id;
        
        insert gft;
        
                
        //Create Experience Related to the program [ProgramTest]
        exp = new Experience__c();
        exp.Experience_Name__c='Other';
        exp.ProgramId__c=prg.id;
        
        insert exp;
        
        // Create Hotel Related to the program [ProgramTest]
        htl = new Hotel__c();
        htl.HotelName__c='HotelTest';
        htl.ProgramId__c=prg.id;
        htl.Location__c='Paris';
        htl.To__c=Date.today();
        htl.From__c=Date.today();
        
        insert htl;
        
        
        // Create Restaurant Related to the program [ProgramTest]
         rest = new Restaurant__c();
         rest.Restaurant_Name__c='RestaurantTest';
         rest.ProgramId__c=prg.id;
         rest.Booking_Date_Time__c=DateTime.newInstance(1993, 6, 6, 3, 3, 3);
        
        insert rest;
        
        // Create Transport Related to the program [ProgramTest]
         trp = new Transport__c();
         trp.ProgramId__c=prg.id;
         trp.Type__c='VTC';
        
        insert trp;
        
        Test.setCurrentPageReference(new PageReference('/apex/STAR_ProgramViewXls'));
        System.currentPageReference().getParameters().put('id', prg.Id);

        STAR_ProgramView_VFCx prgView = new STAR_ProgramView_VFCx();
     
        STAR_ProgramView_VFCx.getLocale();
        STAR_ProgramView_VFCx.getLang();
        
        List<Gift__c> giftLists = prgView.getGiftProg();
        system.debug('giftLists :' +giftLists.size());
        //System.assertequals(giftLists.size(), 3); 
        
        List<Experience__c> experienceLists = prgView.getExperienceProg();
        //System.assertequals(experienceLists.size(), 1);
        
        List<Hotel__c> hotelLists = prgView.getHotelProg();
        system.debug('hotelLists :' +hotelLists.size());
        //System.assertequals(hotelLists.size(), 1);
        
        List<Restaurant__c> restaurantLists = prgView.getRestaurantProg();
        //System.assertequals(restaurantLists.size(), 1); 
        
        List<Transport__c> transportLists = prgView.getTransportProg();
        //System.assertequals(transportLists.size(), 1);  
        
    }
}