force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OwnerId__c.field-meta.xml
<CustomField>
    <fullName>OwnerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OwnerId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderShipping__c/OrderShipping__c.object-meta.xml
<CustomObject>
    <description>One order can be sent in several times</description>
    <label>Order Shipping</label>
    <nameField>
        <label>Shipping Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders Shippings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderShipping__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>standard</fullName>
                <label>Standard</label>
            </value>
            <value>
                <fullName>express</fullName>
                <label>Express</label>
            </value>
            <value>
                <fullName>overnight</fullName>
                <label>Overnight</label>
            </value>
            <value>
                <fullName>premium</fullName>
                <label>Premium</label>
            </value>
            <value>
                <fullName>clickandcollect</fullName>
                <label>Click &amp; Collect</label>
            </value>
            <value>
                <fullName>shipforpickup</fullName>
                <label>Click and Collect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Orders Shippings</relationshipLabel>
    <relationshipName>Orders_Shippings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Accepted / Rejected</fullName>
            </value>
            <value>
                <fullName>Intransit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/StatusDate__c.field-meta.xml
<CustomField>
    <fullName>StatusDate__c</fullName>
    <description>Last modification date of the status</description>
    <label>Status Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/ISO3_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO3_Code__c</fullName>
    <label>ISO3 Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>FRA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/fields/StoreType__c.field-meta.xml
<CustomField>
    <fullName>StoreType__c</fullName>
    <description>Indicate which type of store it is</description>
    <label>Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>WEB</fullName>
            </value>
            <value>
                <fullName>CSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/To_Do_Assistant.recordType-meta.xml
<RecordType>
    <fullName>To_Do_Assistant</fullName>
    <active>true</active>
    <label>To Do Assistant</label>
</RecordType>

force-app/main/default/classes/BL_ICON_Batch_XstoreOrdersTodos.cls
global with sharing class BL_ICON_Batch_XstoreOrdersTodos implements Database.Batchable<sObject>, Database.AllowsCallouts{

    public String query;
    public static final Id TaskTypeId = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('To_Do_Assistant').getRecordTypeId();
   // public static Map<String,String> TechnicalUsers = new Map<String,String>();

    
    global BL_ICON_Batch_XstoreOrdersTodos() {

        String homeDeliveryDate = DateTime.now().addDays(-15).format('yyyy-MM-dd');
        String pickInStoreDate = DateTime.now().addDays(-7).format('yyyy-MM-dd');
        query =  'SELECT id ,Order__c, DeliveryType__c ,Order__r.Account__r.PersonContactId  ,Order__r.Store__c  ,Order__r.OwnerId__c , Order__r.Store__r.ISO3_Code__c FROM OrderShipping__c WHERE  Order__r.Store__r.StoreType__c IN (\'Store\' , \'POP UP - OON\') AND  Status__c = \'Fulfilled\' AND ((DAY_ONLY(StatusDate__c) ='+ homeDeliveryDate + ' AND DeliveryType__c = \'DELIVERY\')  OR (DAY_ONLY(StatusDate__c) ='+ pickInStoreDate + ' AND DeliveryType__c = \'shipforpickup\') )';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
       
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        try{

            Map<String,String>  TechnicalUsers = ICON_Todos_Helper.getTechnicalUsers();

        
            List<Task> lstTask = new List<Task>();
            for(sObject o : scope){
            	OrderShipping__c order = (OrderShipping__c) o;
            	
                lstTask.add(ICON_Todos_Helper.createToDoTaskXstore(order,TechnicalUsers,'Follow-up after purchase', 'TD_XSTO_03'));              	
            }               
            database.insert(lstTask,false);
        
        }
        catch(Exception e) {
            
        }
    }
    
    
    global void finish(Database.BatchableContext CD){}
    

}