force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>ATG=order id
KBRW=transaction id</description>
    <externalId>true</externalId>
    <label>Order Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order_Note__c/Order_Note__c.object-meta.xml
<CustomObject>
    <label>Order Note</label>
    <nameField>
        <label>Order Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Note__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Notes</relationshipLabel>
    <relationshipName>Order_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Order_Shipping__c.field-meta.xml
<CustomField>
    <fullName>Order_Shipping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Shipping</label>
    <referenceTo>OrderShipping__c</referenceTo>
    <relationshipLabel>Order Notes</relationshipLabel>
    <relationshipName>Order_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ExceptionalClient</fullName>
                <label>Exceptional Client (VIC 50K)</label>
            </value>
            <value>
                <fullName>ExceptionalSituations</fullName>
                <label>Exceptional Situations (Complaints - Defective items received)</label>
            </value>
            <value>
                <fullName>ExceptionalSKU</fullName>
                <label>Exceptional SKU’s (&gt;4.500€*)</label>
            </value>
            <value>
                <fullName>NoneOfAbove</fullName>
                <label>None of the above</label>
            </value>
            <value>
                <fullName>ClientAccomodation</fullName>
                <label>Client accommodation</label>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>SecondLookOrderReplacement</fullName>
                <label>Second look order replacement</label>
            </value>
            <value>
                <fullName>LoyaltyGesture</fullName>
                <label>Loyalty Gesture</label>
            </value>
            <value>
                <fullName>ClientRequest</fullName>
                <label>Client Request</label>
            </value>
            <value>
                <fullName>InitialsNumbersMistake</fullName>
                <label>There is a mistake with the initials/numbers of my personalization</label>
            </value>
            <value>
                <fullName>ColorsMistake</fullName>
                <label>There is a mistake with the colors of my personalization</label>
            </value>
            <value>
                <fullName>StickersMistake</fullName>
                <label>There is a mistake with the stickers of my personalization</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Tech_OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>Tech_OrderNumber__c</fullName>
    <description>This field is used to store the order number if we receive the &quot;Order Note&quot; before the creation of the Order. We use it to populate the lookup &quot;order__c&quot; when the order is created.</description>
    <label>Tech Order Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Tech_ShippingNumber__c.field-meta.xml
<CustomField>
    <fullName>Tech_ShippingNumber__c</fullName>
    <label>Tech Shipping Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Note__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ATTACHED_NOTE</fullName>
                <label>Attached Note</label>
            </value>
            <value>
                <fullName>CLIENTELING_EXCEPTION</fullName>
                <label>Clienteling Exception</label>
            </value>
            <value>
                <fullName>PRICE_ADJUSTMENT</fullName>
                <label>Price Adjustment</label>
            </value>
            <value>
                <fullName>BANK_TRANSFER</fullName>
                <label>Bank Transfer</label>
            </value>
            <value>
                <fullName>STOCK_ON_HOLD</fullName>
                <label>Stock On Hold</label>
            </value>
            <value>
                <fullName>FREE_SHIPPING</fullName>
                <label>Free Shipping</label>
            </value>
            <value>
                <fullName>PAYMENT_LINK</fullName>
                <label>Payment Link</label>
            </value>
            <value>
                <fullName>EXTENDED_PAYMENT_LINK</fullName>
                <label>Extended Payment Link</label>
            </value>
            <value>
                <fullName>PERSO_PRODUCT_ACC</fullName>
                <label>Perso Product Accepted</label>
            </value>
            <value>
                <fullName>PERSO_PRODUCT_REF</fullName>
                <label>Perso Product Refused</label>
            </value>
            <value>
                <fullName>PAY_AFTER_AGREEMENT</fullName>
                <label>Pay After Agreement</label>
            </value>
            <value>
                <fullName>General Comment</fullName>
                <isActive>false</isActive>
                <label>General Comment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderShipping__c/OrderShipping__c.object-meta.xml
<CustomObject>
    <description>One order can be sent in several times</description>
    <label>Order Shipping</label>
    <nameField>
        <label>Shipping Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders Shippings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderShipping__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Orders Shippings</relationshipLabel>
    <relationshipName>Orders_Shippings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Action__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>VIC/10K</fullName>
            </value>
            <value>
                <fullName>High Escalated complaint</fullName>
            </value>
            <value>
                <fullName>Technical issue</fullName>
            </value>
            <value>
                <fullName>Defective item</fullName>
            </value>
            <value>
                <fullName>Lost Parcel</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Client Cancelled</fullName>
            </value>
            <value>
                <fullName>Stock issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/ShippingNumber__c.field-meta.xml
<CustomField>
    <fullName>ShippingNumber__c</fullName>
    <description>KBRW=request id
ATG=shipping group</description>
    <externalId>true</externalId>
    <label>Shipping Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-twisticonics/main/default/classes/WS_OrderNotes.cls
@RestResource(urlMapping='/orderNotes/*')
global with sharing class WS_OrderNotes {

    @HttpPost
    global static void upsertOrderNotes() {
        
        RestRequest httpRequest = RestContext.request;
        RestResponse httpResponse = RestContext.response;        
        httpResponse.addHeader('Content-Type','application/json');

        String body = httpRequest.requestBody.toString();

        JSON2OrderNotes orderNotesWS;

        Map<String,Map<String, JSON2OrderNotes.OrderNote>> orderNotesMap = new Map<String,Map<String, JSON2OrderNotes.OrderNote>>();
        
        try {
            orderNotesWS = JSON2OrderNotes.parse(body);
            system.debug(orderNotesWS);
            // To store the orderNumbers
            List<String> orderNumbers = new List<String>();
            List<String> shippingNumbers = new List<String>();
            String keyMap;
            if (orderNotesWS?.orderNotes == null) throw new WSOrderNotesException('Exception in WS_OrderNotes. Missing attribute "orderNotes"');
            
            for(JSON2OrderNotes.OrderNote orderNote : orderNotesWS.orderNotes) {
                // ****************************************** //
                // STEP 1 - CHECK mandatory values            //
                // ****************************************** //
                WS_OrderNotes.checkMandatoryFields(orderNote);

                // ***************************************************** //
                // STEP 2 - Construct MAP in order to identify duplicate //
                // ***************************************************** //                
                keyMap = orderNote.orderNumber+(orderNote.shippingNumber!=null?'_'+orderNote.shippingNumber:'');
                
                if (orderNotesMap.get(keyMap) == null) {
                    orderNotesMap.put(keyMap, new Map<String, JSON2OrderNotes.OrderNote>());
                }
                
                if (orderNotesMap.get(keyMap).get(orderNote.orderType) == null) {
                    orderNotesMap.get(keyMap).put(orderNote.orderType, orderNote);                    
                }
                else {
                    // We can create only one record for same OrderNumber/shippingNumber and OrderType
                    throw new WSOrderNotesException('Exception in WS_OrderNotes. Duplicate "orderType": '+orderNote+' AND '+(orderNotesMap.get(keyMap)).get(orderNote.orderType));
                }
                
                // List of "orderNumber"
                orderNumbers.add(orderNote.orderNumber);
                // List of "shippingNumber"
                if (orderNote.shippingNumber!=null) shippingNumbers.add(orderNote.shippingNumber);
            }

            // ****************************************** //
            // STEP 3 - Create Order Note                 //
            // ****************************************** //
            List<Order_note__c> orderNotesToAdd = new List<Order_Note__c>();
            Order_note__c newOrderNote;
            for(JSON2OrderNotes.OrderNote orderNote : orderNotesWS.orderNotes) {
                newOrderNote = new Order_Note__c();
                
                // if (orderNote.shippingNumber == null) {
                //     newOrderNote.Tech_OrderNumber__c = orderNote.OrderNumber;
                //     newOrderNote.Type__c            = orderNote.orderType.name();
                //     newOrderNote.Description__c     = orderNote.description;

                //     orderNotesToAdd.add(newOrderNote);                        
                //    }
                // else {
                    newOrderNote.Tech_OrderNumber__c = orderNote.OrderNumber;
                    newOrderNote.Tech_shippingNumber__c = orderNote.shippingNumber;
                    newOrderNote.Type__c            = orderNote.orderType;
                    newOrderNote.Description__c     = orderNote.description;
                    newOrderNote.Reason__c          = orderNote.reasonCode;

                    orderNotesToAdd.add(newOrderNote);
                //   }

                system.debug('newOrderNote: ' + newOrderNote);

                
            }


            // // ****************************************** //
            // // STEP 4 - Insert Order Notes                //
            // // ****************************************** //
            Database.SaveResult[] srList = Database.insert(orderNotesToAdd, true);


            for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                    // Operation was successful, so get the ID of the record that was processed
                    System.debug('Successfully inserted Order Note. Order Note ID: ' + sr.getId());
                }
                else {
                    // Operation failed, so get all errors                
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('Order Note fields that affected this error: ' + err.getFields());
                    }
                }
            }

            // // ****************************************** //
            // // STEP 5a - Response OK                       //
            // // ****************************************** //
            WS_OrderNotesHttpResponse response = new WS_OrderNotesHttpResponse();
            httpResponse.responseBody = Blob.valueOf(JSON.serialize(response));
            httpResponse.statusCode = 200;

            
            OrderNoteService.syncWithOrder(orderNumbers, shippingNumbers);
        }
        Catch(Exception ex) {
            // // ****************************************** //
            // // STEP 5b - Response Error                   //
            // // ****************************************** //
            WS_OrderNotesHttpResponseError response = new WS_OrderNotesHttpResponseError(ex);
            httpResponse.responseBody = Blob.valueOf(JSON.serialize(response));
            httpResponse.statusCode = 400;
        }
        finally{
        }

        // return response;
    }

    public static void checkMandatoryFields(JSON2OrderNotes.OrderNote orderNote) {
        // Common mandatory fields

        // ** orderType **
        if (orderNote.orderType == null) throw new WSOrderNotesException('Exception in WS_OrderNotes. Missing "orderType": '+orderNote);
        // ** orderNumber **
        if (orderNote.orderNumber == null) throw new WSOrderNotesException('Exception in WS_OrderNotes. Missing "orderNumber": '+orderNote);
        
        // ** description **
        if (orderNote.isAttachedNote() || orderNote.isPaymentLink() || orderNote.isExtendedPaymentLink() || orderNote.isPayAfterAgreement()) {
           if (orderNote.description == null) throw new WSOrderNotesException('Exception in WS_OrderNotes. Missing "description": '+orderNote);
        }

        // ** shippingNumber **
        if (orderNote.isClientelingException() || orderNote.isPriceAdjustment()) {
            if (orderNote.shippingNumber == null) throw new WSOrderNotesException('Exception in WS_OrderNotes. Missing "shippingNumber": '+orderNote);
        }
        else {
            if (orderNote.shippingNumber != null) throw new WSOrderNotesException('Exception in WS_OrderNotes. "shippingNumber" not allowed: '+orderNote);
        }

        // ** reasonCode **
        if (orderNote.isClientelingException() || orderNote.isPriceAdjustment() || orderNote.isFreeShipping()) {
            if (orderNote.reasonCode == null) throw new WSOrderNotesException('Exception in WS_OrderNotes. Missing "reasonCode": '+orderNote); 
            // ** description ** If Reason is None of Above
           if (orderNote.reasonCode == 'NoneOfAbove' && orderNote.description == null) throw new WSOrderNotesException('Exception in WS_OrderNotes. Missing "description": '+orderNote);
        }
        else if (!orderNote.isPersoProductRefused()) {            
            if (orderNote.reasonCode != null) throw new WSOrderNotesException('Exception in WS_OrderNotes. "reasonCode" not allowed: '+orderNote);
        }

        // Specific mandatory fields 
        // if (orderNoteWS.orderType.equals(JSON2OrderNotes.OrderType.CLIENTELING_EXCEPTION)) {    
        // }
        // else if (orderNoteWS.orderType.equals(JSON2OrderNotes.OrderType.PRICE_ADJUSTMENT)) {                
        // }
    }

    
    public class WSOrderNotesException extends Exception {}

    // global static void upsertOrderNotes() {
        
    //     RestRequest httpRequest = RestContext.request;
    //     RestResponse httpResponse = RestContext.response;        
    //     httpResponse.addHeader('Content-Type','application/json');

    //     String body = httpRequest.requestBody.toString();

    //     JSON2OrderNotes orderNotesWS;

    //     Map<String,Map<String, JSON2OrderNotes.OrderNote>> orderNotesMap = new Map<String,Map<String, JSON2OrderNotes.OrderNote>>();

    //     try {
    //         orderNotesWS = JSON2OrderNotes.parse(body);
    //         system.debug(orderNotesWS);
    //         // To store the orderNumbers
    //         Set<String> orderNumberSet = new Set<String>();
    //         Set<String> shippingNumberSet = new Set<String>();
    //         String keyMap;
    //         if (orderNotesWS?.orderNotes == null) throw new WSOrderNotesException('Exception in WS_OrderNotes. Missing attribute "orderNotes"');
            
    //         for(JSON2OrderNotes.OrderNote orderNote : orderNotesWS.orderNotes) {
    //             // ****************************************** //
    //             // STEP 1 - CHECK mandatory values            //
    //             // ****************************************** //
    //             WS_OrderNotes.checkMandatoryFields(orderNote);

    //             // ***************************************************** //
    //             // STEP 2 - Construct MAP in order to identify duplicate //
    //             // ***************************************************** //                
    //             keyMap = orderNote.orderNumber+(orderNote.shippingNumber!=null?'_'+orderNote.shippingNumber:'');
                
    //             if (orderNotesMap.get(keyMap) == null) {
    //                 orderNotesMap.put(keyMap, new Map<String, JSON2OrderNotes.OrderNote>());
    //             }
                
    //             if (orderNotesMap.get(keyMap).get(orderNote.orderType.name()) == null) {
    //                 orderNotesMap.get(keyMap).put(orderNote.orderType.name(), orderNote);                    
    //             }
    //             else {
    //                 // We can create only one record for same OrderNumber/shippingNumber and OrderType
    //                 throw new WSOrderNotesException('Exception in WS_OrderNotes. Duplicate "orderType": '+orderNote+' AND '+(orderNotesMap.get(keyMap)).get(orderNote.orderType.name()));
    //             }
                
    //             // List of "orderNumber"
    //             orderNumberSet.add(orderNote.orderNumber);
    //             // List of "shippingNumber"
    //             if (orderNote.shippingNumber!=null) shippingNumberSet.add(orderNote.shippingNumber);
    //         }
            
    //         // Does the OrderNumber exists in Salesforce ?
            
    //         Map<String, Order__c> existingOrderMap = new Map<String, Order__c>();
    //         Map<String, OrderShipping__c> existingOrderShippingMap = new Map<String, OrderShipping__c>();

    //         system.debug('orderNumberSet: '+orderNumberSet);
    //         Order__c[] orders = [SELECT id, orderNumber__c, ownerId FROM Order__c WHERE orderNumber__c in :orderNumberSet];
    //         for(Order__c order: orders) {
    //             existingOrderMap.put(order.orderNumber__c,order);
    //         }

    //         system.debug('shippingNumberSet: '+shippingNumberSet);
    //         OrderShipping__c[] orderShippings = [SELECT id, shippingNumber__c, order__c FROM OrderShipping__c WHERE shippingNumber__c in :shippingNumberSet];
    //         for(OrderShipping__c orderShipping: orderShippings) {
    //             existingOrderShippingMap.put(orderShipping.shippingNumber__c, orderShipping);
    //         }

    //         system.debug('existingOrderMap: '+existingOrderMap);
    //         system.debug('existingOrderShippingMap: '+existingOrderShippingMap);

    //         // ****************************************** //
    //         // STEP 3 - Create Order Note                 //
    //         // ****************************************** //
    //         List<Order_note__c> orderNotesToAdd = new List<Order_Note__c>();
    //         Order_note__c newOrderNote;
    //         for(JSON2OrderNotes.OrderNote orderNote : orderNotesWS.orderNotes) {
    //             newOrderNote = new Order_Note__c();
                
    //             if (orderNote.shippingNumber == null) {
    //                 // Order hasn't yet been created
    //                 if (!existingOrderMap.containsKey(orderNote.orderNumber)) {                        
    //                     System.debug('Order hasn\'t yet been created');
    //                     newOrderNote.Tech_OrderNumber__c = orderNote.OrderNumber;
    //                     newOrderNote.Type__c            = orderNote.orderType.name();
    //                     newOrderNote.Description__c     = orderNote.description;

    //                     orderNotesToAdd.add(newOrderNote);                        
    //                 }
    //                 // Order already exists
    //                 else {
    //                     newOrderNote.Order__c       = existingOrderMap.get(orderNote.OrderNumber).Id;
    //                     newOrderNote.Type__c        = orderNote.orderType.name();
    //                     newOrderNote.Description__c = orderNote.description;
    //                     newOrderNote.OwnerId        = existingOrderMap.get(orderNote.OrderNumber).OwnerId;

    //                     orderNotesToAdd.add(newOrderNote);
    //                 }
    //             }
    //             else {
    //                 // OrderShipping hasn't yet been created
    //                 if (!existingOrderShippingMap.containsKey(orderNote.shippingNumber)) {
    //                     System.debug('OrderShipping hasn\'t yet been created');
    //                     //newOrderNote.Tech_OrderNumber__c = orderNote.OrderNumber;
    //                     newOrderNote.Tech_shippingNumber__c = orderNote.shippingNumber;
    //                     newOrderNote.Type__c            = orderNote.orderType.name();
    //                     newOrderNote.Description__c     = orderNote.description;
    //                     newOrderNote.Reason__c          = orderNote.reasonCode;

    //                     orderNotesToAdd.add(newOrderNote);
    //                 }
    //                 // OrderShipping already exists
    //                 else {
    //                     // Check if orderNumber matches with shippingNumber
    //                     if (existingOrderMap.get(orderNote.OrderNumber).Id != existingOrderShippingMap.get(orderNote.shippingNumber).Order__c) {
    //                         throw new WSOrderNotesException('Exception in WS_OrderNotes. "orderNumber" doesn\'t match with "shippingNumber". '+orderNote);      
    //                     }
    //                     else {
    //                         //newOrderNote.Order__c           = existingOrderMap.get(orderNote.OrderNumber).Id;
    //                         newOrderNote.Order_Shipping__c  = existingOrderShippingMap.get(orderNote.shippingNumber).Id;
    //                         newOrderNote.Type__c            = orderNote.orderType.name();
    //                         newOrderNote.Description__c     = orderNote.description;
    //                         newOrderNote.OwnerId            = existingOrderMap.get(orderNote.OrderNumber).OwnerId;
    //                         newOrderNote.Reason__c          = orderNote.reasonCode;

    //                         orderNotesToAdd.add(newOrderNote);
    //                     }
    //                 }
    //             }

    //             system.debug('newOrderNote: ' + newOrderNote);

                
    //         }


    //         // // ****************************************** //
    //         // // STEP 4 - Insert Order Notes                //
    //         // // ****************************************** //
    //         Database.SaveResult[] srList = Database.insert(orderNotesToAdd, true);


    //         for (Database.SaveResult sr : srList) {
    //             if (sr.isSuccess()) {
    //                 // Operation was successful, so get the ID of the record that was processed
    //                 System.debug('Successfully inserted Order Note. Order Note ID: ' + sr.getId());
    //             }
    //             else {
    //                 // Operation failed, so get all errors                
    //                 for(Database.Error err : sr.getErrors()) {
    //                     System.debug('The following error has occurred.');                    
    //                     System.debug(err.getStatusCode() + ': ' + err.getMessage());
    //                     System.debug('Order Note fields that affected this error: ' + err.getFields());
    //                 }
    //             }
    //         }

    //         // // ****************************************** //
    //         // // STEP 5a - Response OK                       //
    //         // // ****************************************** //
    //         WS_OrderNotesHttpResponse response = new WS_OrderNotesHttpResponse();
    //         httpResponse.responseBody = Blob.valueOf(JSON.serialize(response));
    //         httpResponse.statusCode = 200;
    //     }
    //     Catch(Exception ex) {
    //         // // ****************************************** //
    //         // // STEP 5b - Response Error                   //
    //         // // ****************************************** //
    //         WS_OrderNotesHttpResponseError response = new WS_OrderNotesHttpResponseError(ex);
    //         httpResponse.responseBody = Blob.valueOf(JSON.serialize(response));
    //         httpResponse.statusCode = 400;
    //     }
    //     finally{

    //     }

    //     // return response;
    // }

}