force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDate__c</fullName>
    <label>Order Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>ATG=order id
KBRW=transaction id</description>
    <externalId>true</externalId>
    <label>Order Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderLine__c/OrderLine__c.object-meta.xml
<CustomObject>
    <label>Order Line</label>
    <nameField>
        <label>Order Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderLine__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderLine__c/fields/OrderShipping__c.field-meta.xml
<CustomField>
    <fullName>OrderShipping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Shipping</label>
    <referenceTo>OrderShipping__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderLine__c/fields/ProductReferential__c.field-meta.xml
<CustomField>
    <fullName>ProductReferential__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product referential has more SKU than Product Catalogue</description>
    <label>Product Referential</label>
    <referenceTo>ProductReferential__c</referenceTo>
    <relationshipLabel>Order Lines</relationshipLabel>
    <relationshipName>Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderLine__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <description>The field is used if the SKU is unknown in the Product Referential table</description>
    <label>SKU</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderShipping__c/OrderShipping__c.object-meta.xml
<CustomObject>
    <description>One order can be sent in several times</description>
    <label>Order Shipping</label>
    <nameField>
        <label>Shipping Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders Shippings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderShipping__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>standard</fullName>
                <label>Standard</label>
            </value>
            <value>
                <fullName>express</fullName>
                <label>Express</label>
            </value>
            <value>
                <fullName>overnight</fullName>
                <label>Overnight</label>
            </value>
            <value>
                <fullName>premium</fullName>
                <label>Premium</label>
            </value>
            <value>
                <fullName>clickandcollect</fullName>
                <label>Click &amp; Collect</label>
            </value>
            <value>
                <fullName>shipforpickup</fullName>
                <label>Click and Collect</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Orders Shippings</relationshipLabel>
    <relationshipName>Orders_Shippings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/ShippingNumber__c.field-meta.xml
<CustomField>
    <fullName>ShippingNumber__c</fullName>
    <description>KBRW=request id
ATG=shipping group</description>
    <externalId>true</externalId>
    <label>Shipping Number</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Accepted / Rejected</fullName>
            </value>
            <value>
                <fullName>Intransit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderShipping__c/fields/StatusDate__c.field-meta.xml
<CustomField>
    <fullName>StatusDate__c</fullName>
    <description>Last modification date of the status</description>
    <label>Status Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ProductReferential__c/ProductReferential__c.object-meta.xml
<CustomObject>
    <description>All information about base product</description>
    <label>Product Referential</label>
    <nameField>
        <label>Product name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products Referential</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductReferential__c/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <description>Holds the parent order number (if it exists). This field is populated by SAP on SKU starting with &apos;S&apos;. It is used by datastage in order to find the order (opportunity) which generated the creation of this S code SKU.</description>
    <label>Order Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductReferential__c/fields/SKUCode__c.field-meta.xml
<CustomField>
    <fullName>SKUCode__c</fullName>
    <externalId>true</externalId>
    <label>Base SKU Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProductReferential__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the store</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Opening soon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/classes/Account_OrderListControllerLC_TEST.cls
@isTest
public class Account_OrderListControllerLC_TEST {

    @isTest
    public static void getOrderLineList_TEST() {
        Account acc = ICX_TestFactory.createAccount();
        insert acc;

        Store__c store = ICX_TestFactory.createStore('storeName', 'TESTCODE');
        insert store;

        Order__c order = createOrder(store.Id, '123456', acc.Id);
        insert order;

        ProductReferential__c prod = createProductReferential('SKUTEST');
        insert prod;

        OrderShipping__c shipping = createOrderShipping(order.Id, 'SN-01');
        insert shipping;

        OrderLine__c line = createOrderLine(order.Id, shipping.Id, prod);
        insert line;

        ProductReferential__c prod2 = createProductReferential('SKUTEST2');
        insert prod2;
        OrderLine__c line2 = createOrderLine(order.Id, shipping.Id, prod2);
        insert line2;

        Test.startTest();
        Account_OrderListControllerLC.PagedResult result = Account_OrderListControllerLC.getOrderLineList(acc.Id, 5, 1);
        Test.stopTest();

        List<OrderLine__c> orderLineList = result.orderLineList;
        System.assertEquals(2, orderLineList.size());
    }

    private static Order__c createOrder(Id storeId, String orderNumber, Id accountId) {
        Order__c order = new Order__c();
		order.Store__c = storeId;
        order.OrderNumber__c = orderNumber;
        order.OrderDate__c = Datetime.now();
        order.Account__c = accountId;

        return order;
    }

    private static ProductReferential__c createProductReferential(String sku) {
        ProductReferential__c prod = new ProductReferential__c();
        prod.SKUCode__c = sku;
        prod.Name = 'DEMO PRODUCT';
        return prod;
    }
    
    private static OrderShipping__c createOrderShipping(Id orderId, String shippingNumber) {
        OrderShipping__c ship = new OrderShipping__c();
        ship.Order__c = orderId;
        ship.ShippingNumber__c = shippingNumber;
        ship.Status__c = 'New';
        ship.StatusDate__c = DateTime.now();
        ship.DeliveryType__c = 'standard';
        return ship;
    }

    private static OrderLine__c createOrderLine(Id orderId, Id shippingId, ProductReferential__c prod) {
        OrderLine__c line = new OrderLine__c();
        line.Order__c = orderId;
        line.OrderShipping__c = shippingId;
        line.ProductReferential__c = prod.Id;
        line.SKU__c = prod.SKUCode__c;
        return line;
    }
}