force-app/main/default/objects/OnboardingItem__c/OnboardingItem__c.object-meta.xml
<CustomObject>
    <label>Learning</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Learning Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Learnings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OnboardingItem__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ICON</fullName>
                <default>true</default>
                <label>ICON</label>
            </value>
            <value>
                <fullName>Make It Yours</fullName>
                <label>Now Yours</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/RetailStoreId__c.field-meta.xml
<CustomField>
    <fullName>RetailStoreId__c</fullName>
    <description>Contains the Store Code. Used as external id</description>
    <externalId>true</externalId>
    <label>Retail Store ID</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-icon/main/default/classes/BL_ICON_Onboarding_Test.cls
@isTest
public class BL_ICON_Onboarding_Test {
	    @IsTest static void testExecuteGet() {
        try{
            Test.startTest();
            User u = IC_Test_Common.prepareTestUser('ICON_LV Administrator');
       	    u.DefaultStore__c = '1234';
             insert u;               
            BL_AppSettings.setAppSettings('Wechat');
            BL_ICON_Onboarding Onboarding = new BL_ICON_Onboarding();
            Store__c store = new Store__c(Name = 'test', RetailStoreId__c = u.DefaultStore__c);
            insert store;
            Onboarding.me = (BL_UserInfo)Type.forName('BL_ICON_UserInfo').newInstance();
            BL_WS_QueryMergeFields.init(Onboarding.me.userMergeFields);
            OnboardingItem__c o = new OnboardingItem__c(IsActive__c = true, Language__c = UserInfo.getLanguage(),Application__c = 'ICON');
            insert o;
            Onboarding.executeGET();
            Test.stopTest();   
        }
        catch (Exception ex){
            
        }     
    }
}