force-app/main/default/objects/IDENTITY_Settings__c/IDENTITY_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>IDENTITY - Settings</label>
</CustomObject>

force-app/main/default/objects/IDENTITY_Settings__c/fields/Excluded_SKU_for_Purchase_History_API__c.field-meta.xml
<CustomField>
    <fullName>Excluded_SKU_for_Purchase_History_API__c</fullName>
    <label>Excluded SKU for Purchase History API</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/PPR_PurchProduct__c.object-meta.xml
<CustomObject>
    <description>Purchased product by customers</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <description>Client who buyed the product</description>
    <inlineHelpText>Select the client who buyed this product.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchased Products</relationshipLabel>
    <relationshipName>Purchased_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>Currency Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AFN</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARP</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>AZN</fullName>
            </value>
            <value>
                <fullName>BAM</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BOV</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BYB</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Image_Url__c.field-meta.xml
<CustomField>
    <fullName>Image_Url__c</fullName>
    <formula>IF(ISPICKVAL(TransactionType__c, &apos;8&apos;),
	&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + RepairedSKU__c + &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos;,
	IF(ISPICKVAL(ProductLine__c, &apos;Shoes&apos;),
		&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + LEFT(SKU__c ,10 ) + &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos;, 
	    IF(ISPICKVAL(ProductLine__c , &apos;Ready To Wear&apos;),
	    	&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + LEFT(SKU__c ,12 )+ &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos;, 
	    	&apos;http://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_L/louis%20vuitton--&apos; + SKU__c + &apos;_PM2_&apos; + &apos;Front%20view&apos; + &apos;.jpg&apos; 
		) 
	)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Image Url</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/MacroMaterial__c.field-meta.xml
<CustomField>
    <fullName>MacroMaterial__c</fullName>
    <label>Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/OrderATGId__c.field-meta.xml
<CustomField>
    <fullName>OrderATGId__c</fullName>
    <externalId>true</externalId>
    <label>Order ATG ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>Jewelry</fullName>
            </value>
            <value>
                <fullName>Leather Goods</fullName>
            </value>
            <value>
                <fullName>Perfume</fullName>
            </value>
            <value>
                <fullName>Ready To Wear</fullName>
            </value>
            <value>
                <fullName>Shoes</fullName>
            </value>
            <value>
                <fullName>Watches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/PurchasedDate__c.field-meta.xml
<CustomField>
    <fullName>PurchasedDate__c</fullName>
    <label>Purchased Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/RMSSKUCode__c.field-meta.xml
<CustomField>
    <fullName>RMSSKUCode__c</fullName>
    <label>Code RMS du produit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <label>Store</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N83</fullName>
            </value>
            <value>
                <fullName>V24</fullName>
            </value>
            <value>
                <fullName>V06</fullName>
            </value>
            <value>
                <fullName>V88</fullName>
            </value>
            <value>
                <fullName>V14</fullName>
            </value>
            <value>
                <fullName>V85</fullName>
            </value>
            <value>
                <fullName>V15</fullName>
            </value>
            <value>
                <fullName>V18</fullName>
            </value>
            <value>
                <fullName>V76</fullName>
            </value>
            <value>
                <fullName>V35</fullName>
            </value>
            <value>
                <fullName>V25</fullName>
            </value>
            <value>
                <fullName>V61</fullName>
            </value>
            <value>
                <fullName>V38</fullName>
            </value>
            <value>
                <fullName>V42</fullName>
            </value>
            <value>
                <fullName>V62</fullName>
            </value>
            <value>
                <fullName>V86</fullName>
            </value>
            <value>
                <fullName>V50</fullName>
            </value>
            <value>
                <fullName>V33</fullName>
            </value>
            <value>
                <fullName>V57</fullName>
            </value>
            <value>
                <fullName>V74</fullName>
            </value>
            <value>
                <fullName>V36</fullName>
            </value>
            <value>
                <fullName>V82</fullName>
            </value>
            <value>
                <fullName>V80</fullName>
            </value>
            <value>
                <fullName>V21</fullName>
            </value>
            <value>
                <fullName>V65</fullName>
            </value>
            <value>
                <fullName>V72</fullName>
            </value>
            <value>
                <fullName>V54</fullName>
            </value>
            <value>
                <fullName>V31</fullName>
            </value>
            <value>
                <fullName>V32</fullName>
            </value>
            <value>
                <fullName>V13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/StoreRetailCode__c.field-meta.xml
<CustomField>
    <fullName>StoreRetailCode__c</fullName>
    <label>Store Retail Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TECH_TransactionIdConso__c.field-meta.xml
<CustomField>
    <fullName>TECH_TransactionIdConso__c</fullName>
    <description>For Conso to call the Document webservice, the transaction id must match to the transaction id from Conso. As TECH_TransactionId__c is maybe used by another call, this field is created.</description>
    <formula>IF (
  AND (
				OR (
    ISPICKVAL(TransactionStoreType__c, &apos;Web&apos;),
    ISPICKVAL(TransactionStoreType__c, &apos;CSC&apos;)
			 ),
    NOT(ISBLANK(OrderATGId__c))
  ),
  OrderATGId__c,
  TransactionRMSId__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TECH_TransactionIdConso</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionCCFlag__c.field-meta.xml
<CustomField>
    <fullName>TransactionCCFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transaction Click &amp; Collect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionEAFlag__c.field-meta.xml
<CustomField>
    <fullName>TransactionEAFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transaction Endless Aisles</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionStHFlag__c.field-meta.xml
<CustomField>
    <fullName>TransactionStHFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The order is placed in a store but the product is delivered at home</description>
    <label>Transaction Store To Home</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionStoreType__c.field-meta.xml
<CustomField>
    <fullName>TransactionStoreType__c</fullName>
    <label>Transaction Store Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store</fullName>
            </value>
            <value>
                <fullName>CSC</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionStSFlag__c.field-meta.xml
<CustomField>
    <fullName>TransactionStSFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The order is placed in store A and product is collected at store B</description>
    <label>Transaction Store To Store</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PPR_PurchProduct__c/fields/TransactionTotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TransactionTotalAmount__c</fullName>
    <label>Transaction Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>This object contains the referential for the stores (Stores - CSC - Web)</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <description>Recordtype for Stores</description>
    <label>Store</label>
</RecordType>

force-app/main/default/classes/IDENTITY_WS_PurchaseHistory.cls
@RestResource(urlMapping='/identity/purchaseHistory/*')
global with sharing class IDENTITY_WS_PurchaseHistory {

    @HttpGet
    global static void get() {

        RestResponse res = RestContext.response;
        res.addHeader('Content-Type', 'application/json');

        Pattern pattern = Pattern.compile('/identity/purchaseHistory/([a-zA-Z0-9]{18})');
        Matcher matcher = pattern.matcher(RestContext.request.requestUri);
        System.debug(RestContext.request.requestUri);

        if (matcher.matches()) {
            String id = matcher.group(1);

            // GET Excluded IDS
            String[] ids = new List<String>();
            if(RestContext.request.params.get('exclude') != null){
                ids = RestContext.request.params.get('exclude').split(',');
            }

            // GET Excluded SKUS
            String[] skus = new List<String>();
            if(String.isNotEmpty(IDENTITY_Settings__c.getInstance().Excluded_SKU_for_Purchase_History_API__c)){
                skus = IDENTITY_Settings__c.getInstance().Excluded_SKU_for_Purchase_History_API__c.split(';');
            }

            // GET Excluded orderTypes
            String[] orderTypes = new List<String>();
            String[] orderTypesForQuery = new List<String>();
            if(RestContext.request.params.get('orderType') != null){
                orderTypes = RestContext.request.params.get('orderType').split(',');
                for(String ot : orderTypes){
                    if(ot.toLowerCase() == 'digital'){
                        orderTypesForQuery.add('Web');
                    }
                    else if(ot.toLowerCase() == 'retail'){


                        
                        orderTypesForQuery.add('Store');
                    }
                    else{
                        orderTypesForQuery.add(ot.substring(0,1).toUpperCase() + ot.substring(1).toLowerCase());   
                    }
                }
            }
            else{
                orderTypesForQuery = new List<String>{'Store', 'Web', 'CSC', 'Other'};
            }
            
            PPR_PurchProduct__c[] purchases = [
                SELECT Id, TECH_TransactionIdConso__c, OrderATGId__c, RMSSKUCode__c, StoreRetailCode__c, Store__c, PurchasedDate__c, Quantity__c,
                    Amount__c, TransactionTotalAmount__c, CurrencyCode__c,
                    MacroMaterial__c, Model__c, ProductLine__c, Image_Url__c, Name,
                    TransactionCCFlag__c, TransactionStHFlag__c, TransactionEAFlag__c, TransactionStSFlag__c, TransactionStoreType__c
                FROM PPR_PurchProduct__c
                WHERE Client__c = :id
                AND RMSSKUCode__c NOT IN :skus
                AND TECH_TransactionIdConso__c NOT IN :ids
                AND TransactionStoreType__c IN :orderTypesForQuery
                ORDER BY TECH_TransactionIdConso__c, PurchasedDate__c ASC
            ];

            // GROUP BY TECH_TransactionIdConso__c
            Map<String,List<PPR_PurchProduct__c>> groupByTransactionId = new Map<String,List<PPR_PurchProduct__c>>();
            for(PPR_PurchProduct__c purchase : purchases){
                if(groupByTransactionId.get(purchase.TECH_TransactionIdConso__c) == null){
                    groupByTransactionId.put(purchase.TECH_TransactionIdConso__c, new List<PPR_PurchProduct__c>());
                }
                groupByTransactionId.get(purchase.TECH_TransactionIdConso__c).add(purchase);
            }

            // BUILD WRAPPER
            Purchase[] body = new List<Purchase>();
            for(String key : groupByTransactionId.keySet()){
                body.add(new Purchase(groupByTransactionId.get(key)));
            }

            res.statusCode = 200;
            res.responseBody = Blob.valueOf(JSON.serialize(new RestResource_Utils.Response(body), true));
        }
        else {

            res.statusCode = 400;
            res.responseBody = Blob.valueOf(JSON.serialize(new RestResource_Utils.Error(Label.MALFORMED_ID,'400')));
        }
    }

    private class Purchase {
        String orderId;
        String orderType;
        String transactionId;
        Date purchasedDate;
        String currencyCode;
        Decimal totalPriceWithVAT;
        Decimal totalItems;
        Decimal totalPurchased;
        Decimal totalReturned;
        Decimal totalCancelled;
        String shippingMethod;
        String storeCode;
        Item[] items;
        

        public Purchase(PPR_PurchProduct__c[] purchases){
            initiate(purchases);
            calculate(purchases);
        }

        public void initiate(PPR_PurchProduct__c[] purchases){
            this.totalItems = 0;
            this.totalPurchased = 0;
            this.totalReturned = 0;
            this.totalCancelled = 0;

            if(!purchases.isEmpty()){
                this.purchasedDate = purchases[0].PurchasedDate__c;
                this.transactionId = purchases[0].TECH_TransactionIdConso__c;
                this.orderId = purchases[0].OrderATGId__c;
                this.currencyCode = purchases[0].CurrencyCode__c;
                this.totalPriceWithVAT = purchases[0].TransactionTotalAmount__c;
                this.storeCode = purchases[0].StoreRetailCode__c;
                this.orderType = purchases[0].TransactionStoreType__c;
                
                if(this.orderType == 'Web'){
                    this.orderType = 'Digital';
                }
                if(this.orderType == 'Store'){
                    this.orderType = 'Retail';
                }

                if(purchases[0].TransactionCCFlag__c){
                    this.shippingMethod = 'CLICK_COLLECT';
                }
                else if(purchases[0].TransactionStHFlag__c){
                    this.shippingMethod = 'STORE_TO_HOME';
                }
                else if(purchases[0].TransactionEAFlag__c){
                    this.shippingMethod = 'ENDLESS_AISLES';
                }
                else if(purchases[0].TransactionStSFlag__c){
                    this.shippingMethod = 'STORE_TO_STORE';
                }
            }

            this.items = new List<Item>();
        }

        public void calculate(PPR_PurchProduct__c[] purchases){

            Map<String,Item> itemsMap = new Map<String,Item>();
            for(PPR_PurchProduct__c purchase : purchases){

                //CALCULATE TOTALS
                if(purchase.Quantity__c != null){
                    if(purchase.Amount__c > 0){
                        if(itemsMap.get(purchase.RMSSKUCode__c) != null && itemsMap.get(purchase.RMSSKUCode__c).priceWithVAT < 0){
                            this.totalReturned -= Math.abs(purchase.Quantity__c);
                            this.totalCancelled += Math.abs(purchase.Quantity__c);
                        }
                        else {
                            this.totalPurchased += Math.abs(purchase.Quantity__c);
                            this.totalItems += Math.abs(purchase.Quantity__c);
                        }
                        
                    }
                    else{
                        if(itemsMap.get(purchase.RMSSKUCode__c) != null && itemsMap.get(purchase.RMSSKUCode__c).priceWithVAT > 0){
                            this.totalPurchased -= Math.abs(purchase.Quantity__c);
                            this.totalCancelled += Math.abs(purchase.Quantity__c);
                        }
                        else {
                            this.totalReturned += Math.abs(purchase.Quantity__c);
                            this.totalItems += Math.abs(purchase.Quantity__c);
                        }

                    }
                }    


                // IS RETURNED PRODUCT
                if(itemsMap.get(purchase.RMSSKUCode__c) != null && (
                        (itemsMap.get(purchase.RMSSKUCode__c).priceWithVAT < 0 && purchase.Amount__c > 0) ||
                        (itemsMap.get(purchase.RMSSKUCode__c).priceWithVAT > 0 && purchase.Amount__c < 0))){
                    itemsMap.get(purchase.RMSSKUCode__c).isCancelled = true;
                    itemsMap.get(purchase.RMSSKUCode__c).isReturned = false;
                }
                else {
                    itemsMap.put(purchase.RMSSKUCode__c, new Item(purchase));
                }
            }

            this.items = itemsMap.values();
        }
    }

    private class Item {
        String sku;
        String name;
        String material;
        String image;
        Boolean isReturned;
        Boolean isCancelled;
        Decimal priceWithVAT;
        Decimal quantity;
        
        public Item(PPR_PurchProduct__c purchase){
            this.sku = purchase.RMSSKUCode__c;
            this.name = purchase.Name;
            this.material = purchase.MacroMaterial__c;
            this.image = purchase.Image_Url__c;
            this.isReturned = (purchase.Amount__c < 0 ? true : false);
            this.isCancelled = false;
            this.priceWithVAT = purchase.Amount__c;
            this.quantity = purchase.Quantity__c;                        
        }
    }
}